### ISSUE TITLE
Accession agent role business rule not working correctly for new accessions.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#100]
If you add two agents with the same role to trigger the invalid warning, it doesn't show up until you switch between the agents. Correcting the conflict also does not remove the warning or allow you to save. The JS console records the following exception:
```
Bad resource uri: /api/specify/accession/
```

**Comment by garrettgirard** [comment]
The bug mentioned was fixed, however I should mention that while agent roles are required to be unique here, they were not required to be unique in Specify 6.
