### ISSUE TITLE
[a11y] Improve touch-screen support

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1000]
While Specify 7 is usable on a touch-screen device like an iPad or a Surface Book, some actions in Specify 7 require a mouse/keyboard.

In particular:
- [x] **Tooltips** on all buttons and fields (and issue description tooltips in the workbench)
- Other problems are already covered by other issues

Plus, some text may be to small to read on a tablet's screen or buttons may be too close to each other making them hard to hit on smaller screens

**Comment by maxxxxxdlp** [comment]
Need to test tooltip behavior on mobile after https://github.com/specify/specify7/pull/3002 is fixed

I.e, check if there is a way to trigger the tooltip without it registering as a button click

**Comment by grantfitzsimmons** [comment]
The 1 task is complete, so I will mark this as closed. Please reopen if you feel it is necessary Max!
