### ISSUE TITLE
Support Calculated fields in Collection Object and Preparation

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1009]
The latest version of specify 6 added two calculated fields to Collection Object and one to Preparation.  The fields are blank in Specify 7

**Comment by grantfitzsimmons** [comment]
Calculated fields such as Preparations -> Current Count, CollectionObject -> Total Items, and Collection Object -> Total Current Items are not displaying in 7. 

![image](https://user-images.githubusercontent.com/37256050/159039066-d2e3307b-a921-43c1-9fd5-b03bc1070ee9.png)

I was able to recreate this on several databases. 

**Reported By:** CSIRO

**Comment by maxxxxxdlp** [comment]
Counts on the accession form don't work either.

![image](https://user-images.githubusercontent.com/40512816/163457257-1277416b-9bd2-4158-9644-b4453869293d.png)



Definitions:
```xml
			<row>
                <cell type="label" label="Lot Count:" initialize="align=right"/>
                <cell type="field" id="coc" name="collectionObjectCount" uitype="text" readonly="true"/>
                <cell type="label" label="Preparation Count:" initialize="align=right"/>
                <cell type="field" id="pc" name="preparationCount" uitype="text" readonly="true"/>
			</row>
			<row>
                <cell type="label" label="Specimen Count:" initialize="align=right"/>
                <cell type="field" id="tca" name="totalCountAmt" uitype="text" readonly="true"/>
                <cell type="label" label="Actual Specimen Count:" initialize="align=right"/>
                <cell type="field" id="atca" name="actualTotalCountAmt" uitype="text" readonly="true"/>
			</row>
```

Reported by @acbentley

**Comment by benanhalt** [comment]
This is waiting for front end support for the calculated fields. See the PR.

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp @benanhalt What is the timeline for this implementation? It seems that both the front and back end support is functioning.

**Comment by benanhalt** [comment]
This breaks backwards compatibility with 6.8.00 so I think we should hold it back until a tagged release. https://github.com/specify/specify7/pull/1829#issuecomment-1197075207

**Comment by grantfitzsimmons** [comment]
Great job @benanhalt and @maxxxxxdlp !!! I was so excited when I saw the calculated fields working. This is great!
