### ISSUE TITLE
Uploading Attachments to Accessions causes exception

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#101]
On KUFish - master

When creating a new accession, if you try to add an attachment (I did a .png) and select the file, an "Uploading" window pops up, but nothing happens and it causes an exception. This makes it impossible to add attachments to accessions.

It was unclear what the log for the exception was, but here's the exception message: "SCRIPT5007: Unable to get property 'uploadFile' of undefined or null reference"

**Comment by garrettgirard** [comment]
This bug happens for all tables that have Attachment, not just Accession.

**Comment by benanhalt** [comment]
This is because the test server is not setup for attachments, right now. So, the bug is that it shouldn't allow you to try and upload attachments when there is no attachment server configured.

**Comment by benanhalt** [comment]
Superseded by #121 and #122.
