### ISSUE TITLE
Recordsets from different collections are visible in all collections within the same database

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#102]
Whether in KUFish Tissue or KUFish Voucher, all record sets between the two are visible. This is a problem when creating anything that gives you the option of choosing from a recordset or entering catalog numbers (Gifts, Loans, Information Requests, etc.) because if you choose to make them from a recordset, recordsets from different collections are available.

If you try to choose any recordsets from a different collection, you get an exception "Uncaught TypeError: Cannot read property 'length' of undefined" and nothing happens.

**Comment by benanhalt** [comment]
Wait, I still need to limit the items shown in the dialog for other modules...
