### ISSUE TITLE
Should picklist size even be enforced?

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#1025]
**Is your feature request related to a problem? Please describe.**
Currently there is a business rule that rejects additions to picklists that would cause them to exceed their size limit parameter.
Because of #108 that just results in an exception.

**Describe the solution you'd like**
Does anyone really care about size limits on picklists? Does Sp6 enforce it even? Maybe this is an antifeature.

**Describe alternatives you've considered**
Just fixing #108 would at least make it clear what is happening.

**Additional context**

**Comment by maxxxxxdlp** [comment]
@benanhalt Sp6 had a use case for size limit.
Sp7 treats size limit differently. Thus, the field should either be set to follow sp6 behavior, or sp7 should ignore the field altogether

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-7-3-release-announcement/774/1

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-7-4-release-announcement/807/1
