### ISSUE TITLE
Add ability to merge duplicated records

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1030]
requested by multiple institutions.  Most recently west virginia and otago.
End up with lots of examples where agents and records from other tables are duplicated.  Would like a simple and easy way to merge those through Specify

**Comment by tlammer** [comment]
Gothenburg requesting this as well

**Comment by tlammer** [comment]
requested by SAIAB

**Comment by grantfitzsimmons** [comment]
New Mexico needs an interface like this to remove duplicate taxon nodes

**Comment by grantfitzsimmons** [comment]
Larry from Delaware Museum of Nature and Science would like to merge localities
https://discourse.specifysoftware.org/t/locality-merging/848

**Comment by maxxxxxdlp** [comment]
Back-end for this for Agents table is implemented in #2446.
Front-end to be implemented in 7.8.1
Will be expanded to more tables in the future

**Comment by grantfitzsimmons** [comment]
Will be closed by #3648 :tada:

**Comment by grantfitzsimmons** [comment]
> Back-end for this for Agents table is implemented in #2446.
> Front-end to be implemented in 7.8.1
> Will be expanded to more tables in the future

so naîve :wink:
