### ISSUE TITLE
Replace slider bar on forms with explicit buttons like in Sp6

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1039]
When a subform is one-to-many, a horizontal scroll bar appears after 2 or more children are created.
In sp6, there is an explicit count of total items, current position and buttons to go to next/previous element
It would also be nice to be able to go to nth index instead of clicking the button n times

**Comment by maxxxxxdlp** [comment]
Could use something like this:
<img width="1680" alt="Screen Shot 2021-11-09 at 11 55 12 AM" src="https://user-images.githubusercontent.com/40512816/142517524-4e4fc036-737d-4cfe-84d8-332d13224ea9.png">

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/145085898-d2bac7b1-3d02-49ec-84f9-3ee8efce7ae4.png)
*DNA Sequences* paginator is misaligned

**Comment by maxxxxxdlp** [comment]
Unable to replicate.
Can you try to replicate it again?
Also, do you remember which database this happened in?

**Comment by grantfitzsimmons** [comment]
I am unable to replicate it as well. I modified forms to attempt to recreate this issue but the paginator is correctly positioned now.

**Comment by maxxxxxdlp** [comment]
Then it probably was a a browser cache related issue
