### ISSUE TITLE
Forms not displaying fields from other tables

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1046]
The issue is on the accession items subform, I added preparation count.  I added it by adding the field preparations.countAmt to the accession items subform (which is actually an alternate collection object table view).  It works in 6 but not 7.

An example of how it is added:
```xml
              <rows>
                <row>
                    <cell type="label" labelfor="1"/>
                    <cell type="field" id="1" name="catalogNumber" uitype="formattedtext"/>
                    <cell type="label" labelfor="4"/>
                    <cell type="field" id="4" name="preparations.countAmt" uitype="text"/>
                    <cell type="label" labelfor="3"/>
                    <cell type="field" id="3" name="collection.collectionName" uitype="dsptextfield"/>
                </row>
             </rows>
```
The Collection Name value is showing up in the field but the count amt field is not.

**Comment by benanhalt** [comment]
I don't understand how this is supposed to work. This on a collectionobject form, right? So if the collectionobject has two preparations, one with countAmt = 10 and one with countAmt = 20, what should it show? 10? 20? 30?
