### ISSUE TITLE
Implement "icon" view type / Add ability to see more than one attachment thumbnail at a time

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1048]
When looking at attachments in 7, users can only see one attachment thumbnail at a time.
![image](https://user-images.githubusercontent.com/12532430/140422161-1670e856-e155-4966-bed7-a59026cc6f41.png)

The same record in 6 shows multiple attachment thumbnails at a time
![image](https://user-images.githubusercontent.com/12532430/140422299-05c5c307-ab3d-43d1-bd22-02b80d84fb41.png)

**Comment by maxxxxxdlp** [comment]
Current work around: display attachments as a form table

**Comment by grantfitzsimmons** [comment]
Sp6 allows viewing attachments subview as a grid of squares. Sp7 does not support that. The closest thing in sp7 is displaying attachments subview as a form table:

![image](https://user-images.githubusercontent.com/40512816/201249638-56834a84-7e29-48e7-9a61-a0f2b3066be9.png)


> There is a difference between the display of an image attachment in Specify 6 and Specify 7, even though they are sharing the same xml views:
>
> ![image](https://user-images.githubusercontent.com/37256050/229597061-f4e1f08c-c251-484b-8693-125e8dbc18bc.png)
> ![image](https://user-images.githubusercontent.com/37256050/229597070-432fff17-b00d-4462-a572-88d685a59ebb.png)
> 
>  Is it possible to display the icon view in Specify 7? If not, how can the Attachment form be configured to choose the fields to display and their layout?

**Requested By:** [@sorovi on the Speciforum](https://discourse.specifysoftware.org/t/attachment-icon-and-form-views-in-specify-7/1130)

**Comment by grantfitzsimmons** [comment]
Should be solved by https://github.com/specify/specify7/pull/3624 once it is finished
