### ISSUE TITLE
Query does not show tree rank titles

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1050]
Barcelona observed that the query was showing the rank name instead of the title, which they had changed to their own language.
this is what the query looks like:
![image](https://user-images.githubusercontent.com/12532430/140556559-5afbe358-b3dc-4f36-9240-eaab858f54ea.png)
This is what the titles look like in their definitions:
![image](https://user-images.githubusercontent.com/12532430/140556613-6bf6069b-b49f-422c-aed7-f90019b18d27.png)

**Comment by maxxxxxdlp** [comment]
Which version of Specify 7 are they using?
This should be fixed in v7.6.1 - https://github.com/specify/specify7/issues/740

**Comment by tlammer** [comment]
not sure.  Ben would know.  We're hosting them

**Comment by maxxxxxdlp** [comment]
Nevermind. Seems like I forgot about the Query builder when fixing that issue.
Should be fixed now on the branch `issue-1050`
