### ISSUE TITLE
Taxon.isAccepted should be set to true if the taxon is preferred.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#1054]
**To Reproduce**
Here is one symptom that can be reproduced:

1. Upload a collection object data set with determinations and taxon mapped (don't map Taxon.isPreferred).
2. Open the uploaded records in Specify 6.
3. Any record that is determined to a newly uploaded taxon will show a blank preferred taxon.
4. The preferred taxon does appear in Specify 7.
See screenshots below.

**Screenshots**
![image](https://user-images.githubusercontent.com/287254/140822915-6924434e-63ba-4b12-a81c-268a83e9218d.png)
![image](https://user-images.githubusercontent.com/287254/140822993-b4a2c071-acb2-44a5-bbed-be362955a49f.png)

**Desktop (please complete the following information):**

 - Specify 7 Version 7.6.1

**Reported By**
Andy

**Comment by benanhalt** [comment]
To fix this, I will add a business rule that automatically sets `isAccepted` according to whether `acceptedId` is null.

**Comment by benanhalt** [comment]
This applies to other trees as well.

**Comment by maxxxxxdlp** [comment]
Should I hide isAccepted for other trees too?

**Comment by benanhalt** [comment]
Probably. But I'm still investigating why these fields even exist. Let me finish that and I'll let you know.

**Comment by maxxxxxdlp** [comment]
If it helps, `isAccepted` is a field many taxon and geography authorities have to mark names as being widely accepted by authorities.

I usually exclude all non accepted taxa from the tree when doing imports

**Comment by grantfitzsimmons** [comment]
May be fixed in `xml-editor`

**Comment by melton-jason** [comment]
@specify/ux-testing 

This was made into a businessrule as of #2965.
(See https://github.com/specify/specify7/pull/3157#issuecomment-1885683963 for more context). 

Can the fix be verified and this issue closed?

**Comment by melton-jason** [comment]
Specify 7 is now correctly setting the `isAccepted` depending on whether the Taxon is synonymized (True if the Taxon is not synonymzied and False otherwise).
