### ISSUE TITLE
Upgrade to 7.6 fails after dependency warnings and error

### ISSUE THREAD

**Issue by FedorSteeman** [specify/specify7#1057]
Attempted on several different servers (RHEL) to upgrade the web app to 7.6 following the online instructions to the letter. 

Building specify7 ("make") fails after a string of dependency warnings and finally an error revolved around "gyp" after failing to locate packages "x11", "xi" and "xext". 

Excerpt from the output is attached here: [bash-output.txt](https://github.com/specify/specify7/files/7503967/bash-output.txt)

**Comment by FedorSteeman** [comment]
More precisely, the build command that is failing is "npm install" in folder /specify7/specifyweb/frontend/js_src

**Comment by maxxxxxdlp** [comment]
Try running this command: `sudo apt-get install build-essential node-gyp`
Source: https://stackoverflow.com/questions/21155922/error-installing-node-gyp-on-ubuntu

**Comment by FedorSteeman** [comment]
Thanks! We're running Specify7 on a RHEL7 server, but I can try with yum...

**Comment by FedorSteeman** [comment]
Results: 

`No package build-essential available. `

However node-gype did install, but to no avail. 
Running "make" in the specify7 afterwards yielded more or less the same problem. 

```
gl@4.9.2 install /home/specify/versions/v7.6.1/specify7/specifyweb/frontend/js_src/node_modules/gl
prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=6.17.1 runtime=node arch=x64 libc= platform=linux)
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing 'x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
Package xi was not found in the pkg-config search path.
Perhaps you should add the directory containing 'xi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xi' found
Package xext was not found in the pkg-config search path.
Perhaps you should add the directory containing 'xext.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xext' found
gyp: Call to 'pkg-config --libs-only-l x11 xi xext' returned exit status 1 while in angle/src/angle.gyp. while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: 'gyp' failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 3.10.0-1160.45.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/specify/versions/v7.6.1/specify7/specifyweb/frontend/js_src/node_modules/gl
gyp ERR! node -v v6.17.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN @stylelint/postcss-css-in-js@0.37.2 requires a peer of postcss@>=7.0.0 but none was installed.
npm WARN @stylelint/postcss-markdown@0.36.2 requires a peer of postcss@>=7.0.0 but none was installed.
npm WARN eslint-config-next@11.1.2 requires a peer of next@>=10.2.0 but none was installed.
npm WARN gpu-mock.js@1.3.1 requires a peer of gpu.js@^2.10.3 but none was installed.
npm WARN terser@5.10.0 requires a peer of acorn@^8.5.0 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gl@4.9.2 (node_modules/gl):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gl@4.9.2 install: 'prebuild-install || node-gyp rebuild'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npx webpack -o ../static/js
make[1]: execvp: npx: Permission denied
make[1]: *** [build] Error 127
make[1]: Leaving directory '/home/specify/versions/v7.6.1/specify7/specifyweb/frontend/js_src'
make: *** [frontend] Error 2
```

**Comment by ezaton** [comment]
[shell-out.txt](https://github.com/specify/specify7/files/7743736/shell-out.txt)

**Comment by ezaton** [comment]
I've had such a nice long post about my actions, but it was eaten, and I've noticed it just now. So...
To solve the above mentioned problem on Centos 7, you need to run:
yum install -y libX11-devel libXi-devel libXext-devel mesa-libGL-devel gcc-c++
Then you will encounter a new problem, where the compilation of nodejs-gl fails. It might be related to incorrect (albeit the suggested one!) version of nodejs, or NPM, however, this is the result, when going by the guide (full output in the file provided by me above):
`# make
make -C specifyweb/frontend/js_src
make[1]: Entering directory `/var/www/html/specify7/specifyweb/frontend/js_src'
npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN prefer global node-gyp@7.1.2 should be installed with -g

> gl@4.9.2 install /var/www/html/specify7/specifyweb/frontend/js_src/node_modules/gl
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=6.17.1 runtime=node arch=x64 libc= platform=linux)
make[2]: Entering directory `/var/www/html/specify7/specifyweb/frontend/js_src/node_modules/gl/build'
...
  CXX(target) Release/obj.target/webgl/src/native/webgl.o
../src/native/webgl.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE WebGLRenderingContext::DrawBuffersWEBGL(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/native/webgl.cc:2087:100: error: ‘class v8::Maybe<unsigned int>’ has no member named ‘ToChecked’
     buffers[i] = Nan::Get(buffersArray, i).ToLocalChecked()->Uint32Value(Nan::GetCurrentContext()).ToChecked();
                                                                                                    ^
make[2]: *** [Release/obj.target/webgl/src/native/webgl.o] Error 1
make[2]: Leaving directory `/var/www/html/specify7/specifyweb/frontend/js_src/node_modules/gl/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 3.10.0-1062.12.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/html/specify7/specifyweb/frontend/js_src/node_modules/gl
gyp ERR! node -v v6.17.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN eslint-config-next@12.0.7 requires a peer of next@>=10.2.0 but none was installed.
npm WARN gpu-mock.js@1.3.1 requires a peer of gpu.js@^2.10.3 but none was installed.
npm WARN postcss-safe-parser@6.0.0 requires a peer of postcss@^8.3.3 but none was installed.
npm WARN terser@5.10.0 requires a peer of acorn@^8.5.0 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gl@4.9.2 (node_modules/gl):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gl@4.9.2 install: `prebuild-install || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npx webpack -o ../static/js
make[1]: npx: Command not found
make[1]: *** [build] Error 127
make[1]: Leaving directory `/var/www/html/specify7/specifyweb/frontend/js_src'
make: *** [frontend] Error 2`

I am unable to create (using npm) the package "gl" - it fails at the same location, with the same error.
I might try to switch to different (!= the documented version recommended in the installation process) nodejs, to run several tests.
It is important to point out that I have tried looking for prebuilt packages, but for no avail.

I would appreciate any insight.
Thanks!

**Comment by FedorSteeman** [comment]
We have finally gotten the upgrade to 7.6.1 to work. This may be due to a combination of RHEL7 server updates and some fixes on our side. Most notably, make sure that node.js was at the latest stable version (1.16.5) by using nvm cleared the way. I gathered our little "recipe" here: 
https://github.com/NHMDenmark/DanSpecify/blob/master/Scripts/Server/specify7-serverupgrade-bash.txt
