### ISSUE TITLE
[a11y] Be consistent about links that open in new tab

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1063]
- [x] Come up with intuitive rules for which links should open in the same tab and which in the new tab 
  - All external links open in a new tab
  - Query results, WB upload results, WB disambiguation records open in new tab
- [x] Make sure that behavior is consistent across all links.
- [x] Ad an indicator for links that open in a new tab.
- [x] If a link normally opens in new tab, allow opening it in the same tab by alt+clicking on it

**Comment by grantfitzsimmons** [comment]
> Genbank links open in the same tab (Check Cat #4695 in freshfish)
> Alt+click downloads broken .htm files (Try on Genbank button or CT scan button)

**Comment by grantfitzsimmons** [comment]
![referenceworkissue](https://user-images.githubusercontent.com/37256050/145468637-39b2d648-1536-47f8-a804-31d0453dbf57.gif)

Alt+clicking on an external link on a Reference Work asks if I have unsaved changes without making any modifications, then when clicking Leave sends me to Page Not Found.
