### ISSUE TITLE
In query, fields have two-way relationship that allows choosing same field multiple times

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#107]
If you go in a query and a two fields have each other as options for querying, you can end up with an endless circle by choosing those fields over and over.

For example, if you go to query and do a CE, one of the options is CO. If you choose CO, one of it's options is CE. You can then keep going between CO and CE endlessly.

**Comment by benanhalt** [comment]
From meeting: Maybe some kind of warning should be shown for this.

**Comment by maxxxxxdlp** [comment]
Fixed in 62528f74
