### ISSUE TITLE
Visible=false not making a field invisible on forms

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1070]
Reported by CSIRO
they are attempting to hide a field on the form, but not comment it out.  They want the field to autopopulate, which means it must be on the form, but they don't want to see it.  They are using the following code:
                <row>

                    <cell type="label" labelfor="4"/>

                    <cell type="field" id="4" name="cataloger" uitype="querycbx" initialize="name=Agent;title=Catalog Agent" isrequired="true"/>

                    <cell type="field" id="5" uitype="plugin" name="this" initialize="name=PartialDateUI;df=catalogedDate;tp=catalogedDatePrecision;visible=false" uifieldformatter="Date" default="Today"/>

                </row>

It works in 6; they don't see it but they can see the field is filling out through queries and MySQL.

**Comment by maxxxxxdlp** [comment]
Fixed in fd5ef290.
Invisible fields still occupy space on the form, because otherwise there would be some complications. If that is a problem, all invisible fields can be moved down to the bottom of the form or put inside a Panel with many columns

**Comment by maxxxxxdlp** [comment]
@tlammer You mentioned here that "It works in 6"
Did it use to work? Or did CSIRO get it to work?

**Comment by maxxxxxdlp** [comment]
For future reference:
Support for making cells invisible was cut out from Specify 7.7.0 release.
The reason why is explained here: https://github.com/specify/specify7/commit/81c8e970#diff-e9817a0cf90e53795c4ab83ae407b0de9410f106fd17342794d8cbad37d93a49R264-R281

**Comment by maxxxxxdlp** [comment]
Documentation: https://github.com/specify/specify7/wiki/Form-System#:~:text=in%20the%20cell-,invisible,-(boolean%2C%20optional%2C%20default
