### ISSUE TITLE
JavaScript error when using GEOLocate without a Max Uncertainty Est value

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1077]
**Describe the bug**
When there is no value in the maxUncertaintyEst field, GEOLocate does not launch when the button is pressed.

**To Reproduce**
1. Create a locality
2. Add Geography and verify GEOLocate functions.
3. Add Geo Coord Details and leave the maxUncertaintyEst field empty.

**Expected behavior**
GEOLocate should either require a Max uncertainty Est to operate or assume no uncertainty is 0.

**Screenshots**

![geolocateplugin js error](https://user-images.githubusercontent.com/37256050/143068143-667e8f7f-3953-423d-b661-7c27b8ecd41c.png)
Console output when attempting to open GEOLocate without a maxUncertaintyEst value

![image](https://user-images.githubusercontent.com/37256050/143068384-67800e9b-f329-40d9-80a6-48a1f300c939.png)
The TypeError in geolocateplugin.js that Edge is pointing to when this occurs.

**Desktop:**
 - OS: Windows 10
 - Browser: Edge
 - Specify 7.6.1 (next-release)

**Reported By**
University of Michigan

**Comment by maxxxxxdlp** [comment]
Fixed in 7.7.0. Please test this

**Comment by grantfitzsimmons** [comment]
Resolved!
