### ISSUE TITLE
Deleting a View Set Object redirects to App Resources

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1078]
**Describe the bug**
Deleting a View Set Object redirects to the App Resource page after completion.

**To Reproduce**
1. Create a New View Set Object under any View Set Object. 
2. Delete the object.
3. You are now on the App Resource page instead of the View Set Object parent page.

**Expected behavior**
I anticipated to be directed back to the View Sets resource.

**Screenshots**
![Sp7Redirect](https://user-images.githubusercontent.com/37256050/143084260-b01c6cb1-1708-4e89-ac7c-a038cf42e108.gif)

**Comment by maxxxxxdlp** [comment]
Fixed in 97b258751
