### ISSUE TITLE
Sp6 and Sp7 use different CollectingTrip views

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1079]
**Describe the bug**
Specify 6 and 7 show different viewdefs for Collecting Trips.
Specify 7 is using the CollectingTripForm viewdef rather than the CollectingTrip viewdef that Specify 6 refers to.
The XML is supposed to tell Specify 7 which viewdef the QCB should open, but only 6 is reading that information.

**To Reproduce**
1. Modify your form to include a collectingTrip viewdef. (Andy's database has the Collecting Event form)
2. Open the same database in both Specify 6 and 7
3. Press the + on the QCB and the Collecting Trip table is different in each version of Specify.

**Expected behavior**
I expected these QCB to use the same viewdef.

**Screenshots**
![Specify6View](https://user-images.githubusercontent.com/37256050/143086790-e45d2f67-2c9f-43a4-b1cf-cc803b699bde.png)
Specify 6 View
![CollectingTrip7](https://user-images.githubusercontent.com/37256050/143086815-04e779ec-4de8-4718-9343-9ae347df2fb7.png)
Specify 7 View

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Specify 7 Version: 7.6.1+edge

**Reported By**
CSIRO

**Comment by maxxxxxdlp** [comment]
This might be a specify 6 bug.

If you remove the `Haul` field from the form definition, would `Number1` field disappear in specify 6?

**Comment by grantfitzsimmons** [comment]
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/37256050/180677338-fa78ae62-5d8f-4714-aa7b-9b93fc58a7d5.png">

I'm not able to recreate this issue anymore.
