### ISSUE TITLE
Queries menu links to the wrong query builders

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1098]
**Describe the bug**
Log in as nonkoliso. The database Manager 'collection' does not have this issue.
When creating a new Taxon query, the user gets a Storage query.
When creating a new Storage query, the user gets an Audit Log query.
When creating a new Treatment Event query, the user gets a Taxon query.

**To Reproduce**
1. On the Specify 7 test panel, set up an instance of 7.6.1 with the database '2021_11_25_20_18_40'
2. Log in with nonkoliso as the user.
3. Attempt to create a new Taxon query, a new Treatment Event query, and a new Storage query.
4. See error on each of the above. For 'nonkoliso', this problem persists through each collection.

**Expected behavior**
The new queries should have aligned with the expected query builder.

**Screenshots**
![iyjy5fsGIS](https://user-images.githubusercontent.com/37256050/144088819-e3f2c3ad-9800-4cf1-9832-a60c8155c5cd.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Edge
 - Specify 7 Version: 7.6.1

**Reported By**
Willem

**Comment by maxxxxxdlp** [comment]
Not sure what was going on here, but it might be now since I made changes to the query creation dialog since this bug was reported

**Comment by maxxxxxdlp** [comment]
does it also happen on a11y?

**Comment by benanhalt** [comment]
I just made a PR to fix this since it was easy and RBGE mentioned it. 

The bug only occurs for non manager users. For those users the audit log tables are suppressed and it throws the following links off by one.
