### ISSUE TITLE
Allow exporting records to KML. Was: Google Earth	

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#11]
The Google Earth plugin has been implemented as an embedded google map. But there is no function to export KML yet.

**Comment by maxxxxxdlp** [comment]
Update from 7.6.0:
Google Earth is no longer embedded on the Locality Form. Leaflet map is used instead
It should still be possible to implement export to KML.

**Comment by maxxxxxdlp** [comment]
@benanhalt is this fixed?
Query builder has support for KML exports.
Or is this about exporting Record Sets?

**Comment by benanhalt** [comment]
I don't remember. I'm going to close this issue b/c KML is supported in queries. A more specific issue can be added later if we need to add KML export somewhere else.
