### ISSUE TITLE
Replace Mode in WB for next occurrence should work by pressing enter

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1100]
![enter key only changes next](https://user-images.githubusercontent.com/37256050/144135793-39deb221-22e9-4b69-b62e-f775737fb873.gif)

**Is your feature request related to a problem? Please describe.**
This is not related to a problem. When using the WorkBench with the Replace Mode set to 'Replace next occurance', you can press enter after selecting the find & replace box and immediately replace the first instance of the found word. In most applications, you could proceed to press enter and replace the next entry, however you have to go and click the find & replace box again, then press enter.

**Describe the solution you'd like**
After finding & replacing something in one cell, you should be able to press enter once again and replace it in the following cell.

**Comment by maxxxxxdlp** [comment]
That's a behavior we decided on as it allows to skip cells easier.

The current workaround to atchive what you want is:
1. Enter the replacement value
2. Hit Enter to replace
3. If you want to replace the next occurrence, click on the replacement box again
4. Repeat steps 2 and 3 until satisfied
