### ISSUE TITLE
Deleting record set does not remove it from the list

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#1101]
Deleting a recordset does not remove it from the list of record sets until a page refresh
Trying to delete the same recordset twice leads to this error message on the back-end: "Recordset object 1138 is out of date"
Disabling browser cache through dev tools does not fix the issue

Replicated on the production branch

**Comment by maxxxxxdlp** [comment]
Similar problem for query results as discovered by @beach53:
Open a query result in new tab
Delete it
Go back to the query tab
The query result is still there
Trying to open it again results in a "Not Found" page

No easy solution for all cases where some form of this problem can occur, without investing seriously into cross-tab communication

**Comment by beach53** [comment]
No need to allow users to delete records from the database when QR and RS
individual records are opened in a new tab.  I.e. no need for cross-tab
communication. Just delete the delete button.


James H. Beach, Executive Director
Specify Collections Consortium
Biodiversity Institute
University of Kansas
1345 Jayhawk Boulevard
Lawrence, KS 66045, USA

***@***.***
www.specifysoftware.org
Office: +1 785.864.4645
Cell: +1 785.331.8508

**Comment by maxxxxxdlp** [comment]
Similar issues when using the browser's back arrow to go back to the record you have just deleted.

(Imagine deleting a query, and then using the browser back button to go back to that query, or a record set, or a data set, or an app resource, or user).

**Comment by emenslin** [comment]
Fixed
