### ISSUE TITLE
Add way to have pick list take user to section of pick list

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1102]
Requested by CSIRO
They have some very long pick lists and they would like to enter a first value and be taken to the section of the pick list that starts with that value so they can choose the appropriate one.

**Comment by maxxxxxdlp** [comment]
I think this already is the current behaviour.

If picklist is read-only, you can open a pick list and start typing. The picklist would be scrolled to the right place automatically (this is handled by the browser, not specify)

If picklist is not readonly, it's even simpler: there is an explicit input box that can filter the values
