### ISSUE TITLE
Collecting Event dialog can stack unlimited times

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1106]
**Describe the bug**
When using a data entry form and adding a Collecting Event, new windows can be opened over and over 

**To Reproduce**
1. Go to the 2021_11_25_20 database on edge
2. Log in as "collection"
3. Go to the Mammal Observation collection
4. Create a collection object and click Add next to Collection Event
5. Repeat Step 4 until satisfied

**Expected behavior**
I expected a limit of one window at a time

**Screenshots**
![specify7windows](https://user-images.githubusercontent.com/37256050/144511117-a188f20f-edf2-4851-a5fc-edf99ab75cad.gif)

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Safari 15.1 & Edge
 - Specify 7 Version: edge, 7.6.1

**Comment by maxxxxxdlp** [comment]
Fixed
