### ISSUE TITLE
Reports and Labels should display the icon for their base table

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1109]
Reports and Labels currently use unhelpful icons:

![image](https://user-images.githubusercontent.com/37256050/145081596-375f4f98-e906-4a4a-80c4-5f628c73896c.png) ![image](https://user-images.githubusercontent.com/37256050/145081612-716f0a78-b38a-423c-97c8-59bec2e00f7d.png)

These should instead display an indicator of what kind of record set is compatible with each:

![image](https://user-images.githubusercontent.com/37256050/145081683-d02da73b-1b77-42c7-a255-aeb9c716155d.png) (or the respective table used in their creation query.)

**Reported By:** UMich

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-6-release-announcement/1064/1
