### ISSUE TITLE
Searching without quotes yields different results

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1117]
**Describe the bug**
Searching without quotes results in a different result in 7. Quotes are required around large queries.

**To Reproduce**
1. Create a Locality in the MCNB database
2. Search "Azilal, Tadla-Azilal, Marroc, Àfrica"
3. Search Azilal, Tadla-Azilal, Marroc, Àfrica

**Expected behavior**
This search should have the same result as it does in 6.

**Screenshots**
![sp6_azilal](https://user-images.githubusercontent.com/37256050/146060209-f8a6ad5e-9634-4c0f-8f62-0802d5ee713f.png)
![sp7_azilal](https://user-images.githubusercontent.com/37256050/146060212-94f8761a-dc00-42b9-afa5-433ec238e9fc.png)
With quotes

![sp6_noquotes](https://user-images.githubusercontent.com/37256050/146060229-dac4093f-955b-4ad3-b131-5db4994dccd2.png)
![sp7_noquotes](https://user-images.githubusercontent.com/37256050/146060232-131eb765-8e81-41ea-9b7a-6da2c9a1b36a.png)
Without quotes

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Specify 7 Version: edge

**Reported By**
Museu De Ciencies Naturals De Barcelona

**Comment by maxxxxxdlp** [comment]
Merging this with #1215
