### ISSUE TITLE
Taxon author not displaying in the tree

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1121]
**Describe the bug**
When Specify 6 has "Display Taxon Author in the tree view" checked in Preferences, the author of each taxon is displayed in the tree. In 7, this behavior is not replicated and there is no way to enable this.

**To Reproduce**
1. Enable "Display Taxon Author in the tree view" in Specify 6.
![image](https://user-images.githubusercontent.com/37256050/146393095-ac63aba7-dd01-4fbd-b42a-3b4c1f20e5a4.png)
2. View tree in 6 to verify this change was successful.
3. View tree in 7.

**Expected behavior**
The author should display after each taxon entry.

**Screenshots**

![sp6](https://user-images.githubusercontent.com/37256050/146393216-da1e4288-77c6-4eca-a710-d554a45fc3bc.png)

![sp7](https://user-images.githubusercontent.com/37256050/146393213-8fb1ddb1-9a00-4410-a8fd-500dc6f09672.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Specify 7 Version: 7.6.1

**Reported By**
Unitec

**Comment by maxxxxxdlp** [comment]
For future reference:
The remotepref responsible for this is called `TaxonTreeEditor.DisplayAuthor`

Need to add a needed column to the response object created in this function:
https://github.com/specify/specify7/blob/b65375f18063d6bcc2ea546ff1e83baa728ac867/specifyweb/specify/tree_views.py#L39

**Comment by maxxxxxdlp** [comment]
No, not yet

**Comment by benritchie** [comment]
what's the plan with this fix?  It looks from the above like the fix is known, but it doesn't seem to be in 7.7?  
Is it likely this change will be made?
Thanks.

**Comment by grantfitzsimmons** [comment]
This has been requested by New Mexico, Unitec, and CSIRO. This should be addressed soon!

**Comment by grantfitzsimmons** [comment]
Requested by [@Schuchert at the Community Forum](https://discourse.specifysoftware.org/t/authors-of-taxon-names-in-sp7/937) as well.

This is something that _should_ be addressed soon!

Geneva, New Mexico, Unitec, and CSIRO have requested

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/authors-of-taxon-names-in-sp7/937/5

**Comment by grantfitzsimmons** [comment]
Requested by Heather Cole at Agriculture and Agri-Food Canada too.

This is something we need to prioritize.

**Comment by heathercole** [comment]
> Requested by Heather Cole at Agriculture and Agri-Food Canada too.
> 
> This is something we need to prioritize.

This is VITAL to our collection's quality-control and clean up of our tree (which is amazing in some taxo, and messy in others), particularly in botany where there can be multiple published names with different authors which reflect holdings in the collections. Tons of time lost clicking to view this basic info when there are taxa with the same names in the tree.

**Comment by heathercole** [comment]
my heroes!!!!! 

will help so much with quality-control and management of the tree!!!!

![image](https://user-images.githubusercontent.com/50373105/213535947-cc519eed-46c1-44ec-af5f-83ab59555f3b.png)

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-5-release-announcement/1023/1
