### ISSUE TITLE
[a11y] Workbench does not allow you to define an upload plan

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1122]
**Describe the bug**
Workbench does not allow you to define an upload plan

**To Reproduce**
1. Upload a dataset to the WB without an upload plan.
2. 
![image](https://user-images.githubusercontent.com/37256050/146422473-1ae24e0f-6412-4914-bd91-b59d6ee34f62.png)
Click create.
3 See error
![jZhcEFr6NZ](https://user-images.githubusercontent.com/37256050/146422587-1f1ef70a-a37d-4c9d-9bb2-dbc1905a8af3.gif)

**Expected behavior**
I expected to be able to make an upload plan.

**Screenshots**
Here's a full example of what is happening:
![basetable_uploadplan](https://user-images.githubusercontent.com/37256050/146422369-2869c460-77d2-41d8-900f-fe8a698d0f08.gif)

_On MCNB test database. Using Collection_Object_Citation data set._

**Comment by maxxxxxdlp** [comment]
The real bug here is that the "Choose Base Table" dialog did not close once you selected "Collection Object"

The bug is not specific to schema-editor branch (reproducible on the parent a11y branch)
Fixed on the a11y branch
