### ISSUE TITLE
PartialDateUI erases stored date value

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1125]
**Describe the bug**
When switching the PartialDateUI from Full Date -> Month/Year -> Year, the date is erased.

**To Reproduce**
1. Go to a date field on any form
2. Change the date format from Full Date to Month/Year or Year
3. Switch the date format back to Full Date
4. See 01/01/YEAR

**Expected behavior**
The date value should be maintained

**Screenshots**
![changing date field resets date](https://user-images.githubusercontent.com/37256050/146795163-df27c9f7-3600-47b8-9968-7422ed34d31e.gif)

**Additional context**
[Identical to a bug in Specify 6](https://github.com/specify/specify6/issues/1107)

**Comment by maxxxxxdlp** [comment]
Fixed on the a11y branch (in 4eeaf5aa)
