### ISSUE TITLE
TreatmentEvent table does not exist

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1126]
**Describe the bug**
TreatmentEvent table does not exist error appears when saving a CO form on the 2021_11_25_20_18_40 database.

**To Reproduce**
1. Create a collection object
2. Give it a date
3. Press save
4. See "1146, "Table '2021_11_25_20_18_40.treatmentevent' doesn't exist")"

**Expected behavior**
There should be a visual error that explains the error in a user friendly way, or this should be self-corrected.

**Screenshots**
![a11y no treatment event](https://user-images.githubusercontent.com/37256050/146799700-a06201d3-4bd1-4fac-a9b6-9e549b7fbbf3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge

**Comment by maxxxxxdlp** [comment]
This doesn't sound related to accessibility changes.
Here is a similar issue I had in the past: https://github.com/specify/specify7/issues/791
It's probably database-specific.

**Comment by maxxxxxdlp** [comment]
@benanhalt  says:
"It's usually because the database didn't restore completely and is missing some tables."
