### ISSUE TITLE
Labels are made for every synonymized taxon

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1132]
**Describe the bug**
In Specify 7, when printing a label for a collection object that has multiple synonymized taxon, 
 
**To Reproduce**
1. Go to the florida database on the old test server
2. Go to CO # 33014
3. Print labels (use Small Labels for this test, but it happens to every kind of label)

**Expected behavior**
Only one label should print for each CO.

**Screenshots**
## Specify 6 (correct behavior)
![sp6_labl](https://user-images.githubusercontent.com/37256050/146962739-88c8bbde-488c-492b-904d-dd9639803b07.png)

## Specify 7 (incorrect behavior)
![sp7_labels](https://user-images.githubusercontent.com/37256050/146962764-1659001e-734e-40cb-87cd-5c292d644a56.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Specify 7 Version 7.6.1

**Reported By**
Paul Larson, Phd of the Florida Fish and Wildlife Conservation Commission

**Comment by emenslin** [comment]
Fixed

**Comment by melton-jason** [comment]
This is likely a duplicate of https://github.com/specify/specify7/issues/3570 and was fixed in https://github.com/specify/specify7/pull/4299
