### ISSUE TITLE
Jaspersoft Studio deprecated PDF Font while reports and labels require it

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1138]
**Describe the bug**
Currently, to preserve a chosen font in a report or label you must use the PDF Font property in iReport. Nearly 7 years ago Jaspersoft Studio deprecated PDF fonts in favor of font extensions, but Specify 7 does not support any other font association when running a label or report. Because all modern versions of Jaspersoft Studio lack PDF Font assignment, it is difficult to pick a font for a label or report when only using Specify 7. 

**To Reproduce**
1. Create a label or report in Specify 7 from a query
2. Build label or report
3. Attempt to change the font
4. See there is no current way to assign a font in modern versions of Jaspersoft Studio

**Expected behavior**
I would expect Sp7 to pull the font data from
`fontName="Times New Roman"`
rather than attempt to pull it from pdfFontName.

It should inherit the font assigned to it in Jaspersoft Studio.

**Screenshots**

### Label Made in SpiReport, downloaded from Specify 7
Here is a working label in Specify 7:
![image](https://user-images.githubusercontent.com/37256050/148081889-b2056a0c-08d1-4352-b042-522e4bc5258a.png)

`<font fontName="Times New Roman" size="10" isBold="true" pdfFontName="Times-Bold" isPdfEmbedded="false"/>`
Currently to print a PDF font in Specify 7, the pdfFontName must have a value of a font installed on the server.
Here is the working label output:
![pdfFont](https://user-images.githubusercontent.com/37256050/148084977-19ea6fbf-5bda-4ebe-8d3d-18e59edd9fe0.png)

### Label Made in SpiReport, download from Specify 7, removed pdfFontName attribute
![image](https://user-images.githubusercontent.com/37256050/148085362-920e3bdc-be65-4825-8a9e-a30eba1f04ed.png)

Here is a preview inside of Jaspersoft Studio
![image](https://user-images.githubusercontent.com/37256050/148085461-15275cf5-e8d5-49be-8b75-fe69af09c425.png)

Here is the output when run from Specify 7:
![noPDFfont](https://user-images.githubusercontent.com/37256050/148085837-844358a9-7fce-4b1a-b8b5-c3a32dc21840.png)

There is no easy way to add the pdfFontName attribute in modern versions of Jaspersoft Studio.

**Comment by benanhalt** [comment]
This has to do with how the report-runner service is configured on the server. I made a few adjustments to the test panel report-runner, and I think it should be behaving correctly now. That is, you shouldn't need to add any of the pdf attributes to the font elements. All of the following fonts are supported there:
- Arial
- SansSerif
- Arial Narrow
- Calibri
- Copperplate Gothic Light
- Baskerville Old Face
- Franklin Gothic Demi Cond
- Garamond
- Georgia
- Lucida Fax
- Lucida Sans
- Palatino Linotype
- Times New Roman
- Trebuchet MS
- Verdana

I can add others if needed.

**Comment by grantfitzsimmons** [comment]
I can confirm Times New Roman and Arial are working just fine! Thank you for reconfiguring the server. Will we need to configure the servers we host to support these fonts as well?

**Comment by benanhalt** [comment]
Yep. I'll be doing that shortly.
