### ISSUE TITLE
Add a "Map Explorer" to query builder

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1142]
**Is your feature request related to a problem? Please describe.**
The Map Explorer feature in the Workbench Mapping Editor is very useful.

**Describe the solution you'd like**
It would be nice to add something similar to the query builder

**Reported By** @acbentley

**Comment by maxxxxxdlp** [comment]
Fixed in 2df24e9e

**Comment by grantfitzsimmons** [comment]
This is so amazing. Just wanted to add a comment mentioning how exciting this feature is.
