### ISSUE TITLE
Data entry in the WB from specimen images

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1153]
**Is your feature request related to a problem? Please describe.**
UMich uses Specify 6 to enter its main herbarium specimen data into the workbench directly from specimen images linked to the workbench.

**Describe the solution you'd like**
Specify 7 should replicate this capability that 6 currently offers.

**Reported By**
UMich

**Comment by maxxxxxdlp** [comment]
Possible duplicate of https://github.com/specify/specify7/issues/764
