### ISSUE TITLE
collectingEventAttribute text fields should have larger limits

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1155]
The extra text fields in the schema currently have 50 character limit. It would be a welcome change to expand the character limit for all of these fields within collectingEventAttribute. While there are existing customizable fields that are larger than 50 chars, some institutions would benefit from having more.

![image](https://user-images.githubusercontent.com/37256050/152566602-833754c5-5199-4870-bab1-6ef784db5938.png)

**Requested By**
Gothenburg

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-6-8-02-and-schema-2-10-release-notes/830/1

**Comment by grantfitzsimmons** [comment]
Finished in schema 2.10
