### ISSUE TITLE
User settable default sort for subform grids on forms

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1158]
Requested by Borror lab and several other collections
They would like to be able to set a default field for the records in a subform grid to sort by.

**Comment by tlammer** [comment]
Also requested by CSIRO
https://app.asana.com/0/1201972579963460/1201974754694634/f

**Comment by maxxxxxdlp** [comment]
Fixed by adding a `sortField` attribute to subviews and grids
Documentation: https://github.com/specify/specify7/wiki/Form-System#:~:text=sortField%20(string%2C%20optional%2C%20case%2Dinsensitive)
Can also change sort direction on the fly by clicking on table headers in grid view

**Comment by grantfitzsimmons** [comment]
```
                <row>
                    <cell type="subview" viewname="Preparation" id="8" name="preparations" defaulttype="table" sortField="-countAmt" colspan="12" rows="3"/>
                </row>
```

![image](https://user-images.githubusercontent.com/37256050/167703974-1c8376da-840d-42d4-8ca8-452d0844660c.png)


I am not seeing the sorting behavior here- 

db: `oldfish`

**Comment by maxxxxxdlp** [comment]
It seems like I made a mistake in the documentation.
sortField attribute should be inside the `initialize` attribute. Like this: `initialize="sortField=-countAmt"`)
See more: [sortField (string, optional, case-insensitive)](https://github.com/specify/specify7/wiki/Form-System#:~:text=sortField%20(string%2C%20optional%2C%20case%2Dinsensitive))

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/167860230-c98294f7-c4aa-4974-9566-1de555a0b637.png)

No sorting seems to start by default.

```
                <row>
                    <cell type="subview" viewname="Preparation" id="8" name="preparations" defaulttype="table" initialize="sortField=-countAmt" colspan="12" rows="3"/>
                </row>
```

When tried without the "-" in front of countAmt, I also had no luck.

`kufish`

`/specify/view/collectionobject/21969/`

**Comment by maxxxxxdlp** [comment]
That record works fine for me:
<img width="1800" alt="Screen Shot 2022-05-11 at 22 54 20" src="https://user-images.githubusercontent.com/40512816/167988785-757d6352-4b24-4104-ae28-32c927bc1262.png">

Are you expecting it to be sorted as soon as you add a new record to the form table? It only does the sorting on record save, unless you manually press on the column header

**Comment by grantfitzsimmons** [comment]
Actually that was after clearing my cache twice and logging out and back in. No record modifications were made… I will test again tomorrow!

**Comment by grantfitzsimmons** [comment]
Appears to work correctly now. Thanks!
