### ISSUE TITLE
Exception when changing a user's collection access in 7 after changing their permissions in 6

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#1161]
**To Reproduce**
1. Choose a database w/ multiple collections
2. In Sp7 create a new user with access to some collections but not others
3. In Sp6 add the user to some role in some collection and then change their permission by e.g. enabling access to the export mapper
4. Back in Sp7 attempt to grant the user access to some other collections
5. The following exception occurs:
```
IntegrityError at /context/user_collection_access/14/
(1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`fresherfish6801`.`spprincipal_sppermission`, CONSTRAINT `FK9DD8B2FA99A7381A` FOREIGN KEY (`SpPrincipalID`) REFERENCES `spprincipal` (`SpPrincipalID`))')
```

**Reported By**
SELU 
Gothenburg museum of natural history
and others

**Comment by grantfitzsimmons** [comment]
I was able to recreate the original issue and the fix is working on the test server.
