### ISSUE TITLE
Add ability to batch update Storage Location

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1164]
Requested by UOregon
They would like to be able to batch edit the location for a group of collection objects they moved

**Comment by grantfitzsimmons** [comment]
@tlammer This is what we were talking about with Jim, correct?

**Comment by tlammer** [comment]
@grantfitzsimmons Not what Joslyn wanted.  They aren't looking for item level representation in the storage tree.  But if they move a box of flies with 50 specimens to a new cabinet, they would like to update the location for all 50 of those in one action.
Essentially, they want batch editing to allow them to edit storage location, which it does not in Specify 6

**Comment by emenslin** [comment]
Fixed by https://github.com/specify/specify7/pull/4682
