### ISSUE TITLE
Is public is set to false by default and user can't change it

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1167]
Reported by FWRI
when importing attachments, the Is Public flag is set to false by default, which is consistent with Specify 6, but 7 doesn't offer a way to change that, so no attachments imported through 7 can be shared.

**Comment by maxxxxxdlp** [comment]
Fixed in 7b1164e3

**Comment by maxxxxxdlp** [comment]
Specify 7 now respects the `attachment.is_public_default` remote pref set in Specify 6 (79d81bad)

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp How can I test this?

**Comment by maxxxxxdlp** [comment]
Set `attachment.is_public_default` remote pref to true or false
Create a new attachment
Open meta data for that dialog for that attachment and take a look at the value of ispublic field (if it is not on the form, then add it to the form, or in case of default forms, add it to the form). The ispublic value should match the value of attachment.is_public_default
