### ISSUE TITLE
does support [at] specifysoftware exist anymore?

### ISSUE THREAD

**Issue by waterfleas** [specify/specify7#1169]
Hi,
Over the past few months I have contacted support [at] specify regarding several issues while trying to get specify functioning properly, but I have never received a reply. It is super frustrating.

Do you know if the mailbox is still functioning?  or should I ask my questions here? or is support only available for $$$
(in particular I want to deploy specify7 with an attachment server using docker - and the instructions here say to contact support[@]....

thanks for any reply (even if it "please go away")

**Comment by maxxxxxdlp** [comment]
Yes, our support email is still working: support@specifysoftware.org
Support is primarily available to members of the Specify Collections Consortium.
Production-ready docker compositions of Specify 7 (with attachments server and etc) are available to members only at this time.

**Comment by beach53** [comment]
Stuart,

Technical support from our staff is only available for Consortium members.
Their fees pay for our help desk and tech support activities.

Jim Beach


James H. Beach, Executive Director
Specify Collections Consortium
Biodiversity Institute
University of Kansas
1345 Jayhawk Boulevard
Lawrence, KS 66045, USA

***@***.***
www.specifysoftware.org
Office: +1 785.864.4645
Cell: +1 785.331.8508

**Comment by waterfleas** [comment]
Thanks for the information. I will communicate this to our collections manager.
