### ISSUE TITLE
Project is not showing up on Collection Object data entry forms

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1172]
Reported by UMich

they tried to add projects to the CO form, it appears in 6 but not in 7.
Code added:
cell type="subview" viewname="Project" id="proj" name="projects" initialize="btn=true"

error in the console:
unhandled relationship type: many-to-many

**Comment by grantfitzsimmons** [comment]
Duplicate of https://github.com/specify/specify7/issues/2928

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-6-vs-specify-7-feature-comparison/551/3
