### ISSUE TITLE
Specify7 does not use token when requesting attachments from attachment server

### ISSUE THREAD

**Issue by foozleface** [specify/specify7#1173]
Either requesting all attachments or inspecting the attachment via the collectionobject. Logged query:

GET /fileget?coll=Botany&type=T&filename=12363c53-5a0d-474f-85ea-b48b19cfeac7.JPG&token=&scale=256

  Note missing "token" information. Same is true for non-thumbnail:

http://ibss-images.calacademy.org/fileget?coll=Botany&type=O&filename=12363c53-5a0d-474f-85ea-b48b19cfeac7.JPG&downloadname=CAS0624442.JPG&token=

Specify6 uses the token correctly in these situations. We use the token for auth when requesting redacted imagery as a belt-and-suspenders security approach in case of a misconfigured export.

This will also break the REQUIRE_KEY_FOR_GET feature in the attachment server for s7.

# Set this to True to require authentication for downloads in addition
# to uploads and deletes.  Static file access, if enabled, is not
# affected by this setting.
REQUIRE_KEY_FOR_GET = False

**Comment by maxxxxxdlp** [comment]
To make specify7 use the token, set it to the `WEB_ATTACHMENT_KEY` variable in the specify 7 settings file

**Comment by foozleface** [comment]
Excellent, closing, thanks for the quick response
