### ISSUE TITLE
Allow multiple CO record relationships on a CO record

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1176]
**Is your feature request related to a problem? Please describe.**
New Brunswick wants to have multiple CO record links on a single CO record. This relationship is not feasible in an elegant way currently in 7 or 6.

**Describe the solution you'd like**
There should be an easy way to link multiple collection objects to each other on the forms. There is no way to directly navigate to a CO in a collection from the URL as it links to the DB ID and not the catalog number. There is way to link multiple collection objects to one collection object and navigate between them.

**Requested By**
New Brunswick

**Comment by maxxxxxdlp** [comment]
Does CollectionRelOneToManyPlugin work for their use case?
https://github.com/specify/specify7/wiki/Form-System#collectionrelonetomanyplugin

Additionally, you can link to a Collection Object record directly like this:
https://sp7demofish.specifycloud.org/specify/bycatalog/KUI/19198/
Where `KUI` is collection code and `19198` is the catalog number

**Comment by grantfitzsimmons** [comment]
This should stay open as a feature request. There should be some element that allows you to query for a CO and add it as a link on the form

**Comment by maxxxxxdlp** [comment]
CollectionRelOneToManyPlugin is exactly that - a link to a CO in another collection.

If you need more customization, you can create a weblink, which has an associated Catalog number and collection code fields. Collection code can be a pick list.

The weblink should have a format like `https://sp7demofish.specifycloud.org/specify/bycatalog/KUI/19198/`, where KUI is collection code and 19198 is catalog number

**Comment by grantfitzsimmons** [comment]
Cumbersome, no? Especially as it is **impossible** to establish a CoR in Specify 7 at the moment. This is a Specify 7 request

**Comment by maxxxxxdlp** [comment]
> Especially as it is impossible to establish a CoR in Specify 7 at the moment

@grantfitzsimmons do you remember if we have an issue for creating collection relationships in sp7?

**Comment by grantfitzsimmons** [comment]
I couldn't find one, so I made a new one:

https://github.com/specify/specify7/issues/3120

**Comment by grantfitzsimmons** [comment]
Closing this as @maxxxxxdlp is right, of course. This is the answer:

> Does CollectionRelOneToManyPlugin work for their use case?
> https://github.com/specify/specify7/wiki/Form-System#collectionrelonetomanyplugin
> 
> Additionally, you can link to a Collection Object record directly like this:
> https://sp7demofish.specifycloud.org/specify/bycatalog/KUI/19198/
> Where `KUI` is collection code and `19198` is the catalog number

Better requests are on GitHub with more specific requests.
