### ISSUE TITLE
[a11y] Trees are not working

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1177]
**Describe the bug**
Trees cannot expand when a node is clicked on.

**To Reproduce**
1. Go to any tree
2. Click on the root node
3. See error

**Expected behavior**
Clicking on a node should allow me to expand and view its children.

**Screenshots**
<img width="528" alt="Screen Shot 2022-03-16 at 8 33 19 AM" src="https://user-images.githubusercontent.com/37256050/158601487-af2b26d6-7969-486f-bd5b-2a097d8882f8.png">

**Desktop (please complete the following information):**
 - OS: Windows 10 and macOS 12.3
 - Browser: Safari, Edge on Windows, Edge on Mac

**Comment by maxxxxxdlp** [comment]
Fixed
