### ISSUE TITLE
[a11y] Resizing Reports dialog changes padding

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1178]
**Describe the bug**
Resizing the Reports dialog modifies the padding inside the dialog.

**To Reproduce**
1. Open the **Reports** dialog
2. Resize the window
3. See issue

**Expected behavior**
It should not do this.

**Screenshots**
![image](https://user-images.githubusercontent.com/37256050/158603555-2b892e01-ec5e-430e-9b26-d824ca054f8a.png)
![resizingerror](https://user-images.githubusercontent.com/37256050/158603865-03f33925-b84d-4177-ad39-608adf32cec6.gif)

**Desktop (please complete the following information):**
 - Windows 10 & macOS, Safari, Edge on Mac & Windows

**Comment by maxxxxxdlp** [comment]
That was a bug with a previous dialog library.
Should be fixed now
