### ISSUE TITLE
[a11y] Reports & Labels dialog tables are different sizes

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1180]
The tables inside of the Reports dialog are sized differently.

**Screenshots**
![image](https://user-images.githubusercontent.com/37256050/158604408-47315892-3bc8-41c7-b757-2bd524751c2a.png)

**Comment by maxxxxxdlp** [comment]
Fixed in [14de695](https://github.com/specify/specify7/commit/14de695ed7005749d87864c09a60a2a2b633b48e)
