### ISSUE TITLE
[a11y] Schema config loads indefinitely

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1184]
**Describe the bug**
After selecting a base table, the schema configurator loads indefinitely.

**To Reproduce**
1. Click on user
2. Click on Schema Config
3. Select a base table

**Expected behavior**
The schema configurator should open

Windows 10, macOS - Edge on both & Safari

**Comment by maxxxxxdlp** [comment]
It may take a while to load, as it has to make A TON of requests to the back end, but it should load eventually
See https://github.com/specify/specify7/issues/1211

**Comment by grantfitzsimmons** [comment]
In March I was unable to load the 7 schema config after waiting upwards of 10 minutes, but now I can load it within seconds. Seriously good work.
