### ISSUE TITLE
[a11y] Record Sets do not display

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1187]
**Describe the bug**
Record sets do not load forms at all.

**To Reproduce**
1. Click on **Record Sets**
2. Select any record set
3. See error

**Expected behavior**
A form should appear for items in a record set

**Screenshots**
![image](https://user-images.githubusercontent.com/37256050/158609633-c06d5dfb-b655-4eaf-9da5-a96aab76570a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 and macOS
 - Browser: Safari & Edge

**Comment by maxxxxxdlp** [comment]
Fixed
