### ISSUE TITLE
[a11y] Collapsing headers in the tree displays as single character

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1194]
**Describe the bug**
If you collapse the headers in the tree view they are only one character.

**Expected behavior**
The name should collapse into either multiple characters (3 or so) or become vertical to be discernible.

**Screenshots**
![collapsing](https://user-images.githubusercontent.com/37256050/158650937-6099d2f4-df1d-4803-9a62-ab3626c4fc46.gif)

*Previous*
![image](https://user-images.githubusercontent.com/37256050/158651411-4638448b-6d5e-4cc5-972b-79399673b34b.png)

**Comment by maxxxxxdlp** [comment]
This is probably a wontfix since that feature probably isn't even needed in sp7.
It was needed in sp6 because, if I remember correctly, it did not have a horizontal scroll bar in the tree viewer
