### ISSUE TITLE
[a11y] catalogNumber can be modified

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1206]
**Describe the bug**
You can change the catalog number formatting!!!!! 

**Screenshots**
<img width="1512" alt="Screen Shot 2022-03-29 at 10 37 32 AM" src="https://user-images.githubusercontent.com/37256050/160653346-e713f750-ff6a-4181-93da-628e1a4a41b0.png">

**Comment by maxxxxxdlp** [comment]
For future reference, see also https://github.com/specify/specify7/issues/1277
