### ISSUE TITLE
Improve Schema Config performance

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1211]
It sends lots of requests, which causes it to take long to load.
Potential solution would be to render the UI before all fields are fetched

**Comment by maxxxxxdlp** [comment]
Fixed in 
472f13b

**Comment by grantfitzsimmons** [comment]
Is there a way to objectively test this? It seems much faster to me.

**Comment by maxxxxxdlp** [comment]
Not needed.

You could open DevTools and see that it only has about 5 requests when you open a table in the schema config instead of ~100 like before. But, there are other things to test that are much higher priority
