### ISSUE TITLE
QCBX duplicate record overwritten by form XML default

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1216]
**Describe the bug**
A field that has a default value assigned via the form XML. When a Locality is duplicated via the query combobox functionality, the existing value is overwritten with the default value from the form xml. This only occurs in S7, not in S6.

**To Reproduce**
1. Create a record using a QCBX.
2. Try to clone and create a new record using the function in 7.
3. See default form definition overwrites existing data.

**Expected behavior**
In Specify 6, the data overwrites the form's field default. This behavior should be replicated in 7.

**Screenshots**
![image](https://user-images.githubusercontent.com/37256050/162005499-845f7b23-aff9-4041-bec4-11bbb308f911.png)
Before duplication

![image](https://user-images.githubusercontent.com/37256050/162005555-7340a544-99c2-4623-8907-c8d3c774c888.png)
After duplication (form default is 100)

![image](https://user-images.githubusercontent.com/37256050/162004767-bcec3a9a-1b33-4587-bc8c-1485fa95a224.png)
Form definition was set to 0.89761

**Reported By**
CSIRO

**Additional context**
On edge branch. Could not test in a11y.

**Comment by maxxxxxdlp** [comment]
Is there a reason why this can't be tested on a11y?
Is there another bug on a11y?

**Comment by grantfitzsimmons** [comment]
> Is there a reason why this can't be tested on a11y? Is there another bug on a11y?

![image](https://user-images.githubusercontent.com/37256050/162010790-eef540c2-3319-42aa-b97f-b29dd9b8ef69.png)

I cannot even get the QCBX to open

**Comment by maxxxxxdlp** [comment]
> I cannot even get the QCBX to open

Just pushed a fix. Should be working after server updates
