### ISSUE TITLE
Implement attachment server for testing.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#122]

**Comment by maxxxxxdlp** [comment]
Is this fixed now?
https://github.com/specify/web-asset-server

**Comment by benanhalt** [comment]
No.... I've never really figured out how to deal with the fact that the databases in the test server can be changed.

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp What exactly do we have to do to fix this?

**Comment by maxxxxxdlp** [comment]
I was never told what this was about, but here is my guess:

I belive Ben meant that Specify 6 stores attachment server credentials in the remote prefs, and so when those were loaded on a test server, any changes would affect someone's production asset server.

Currently, specify 7 looks at the asset server configuration in a separate place, and the test server uses the sp7demofish's asset server


Or, maybe this meant implementing a mock asset server that could be used in the automated tests for the back-ends integration with the asset server

**Comment by grantfitzsimmons** [comment]
Not sure what this is. You can create a new attachment server when you would like to test.
