### ISSUE TITLE
Add Query Import/Export functionality

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1220]
Add ability to export and import queries between users and databases

**Comment by benritchie** [comment]
2 thoughts:
worth noting there's currently a quite good workaround for sharing queries between users: (also works with record sets)
* send the URL of the query to another user.  
* They can then click save, to add it to their queries.  
As a side note, assume this will continue to work with the reworked UI?

For me, more useful than import / export would be a concept of shared queries.  
the problem with import/export is that everyone ends up with slightly different version of the queries, doesn't get new queries automatically that are added later, etc.  
what I'd love to be able to do would be to add "shared" queries, which automatically are available to all users.  - and updates to them are again available to all users.

**Comment by benritchie** [comment]
good to hear can still share by URL.  thanks
