### ISSUE TITLE
performing a query from the taxon view on a large taxon takes several minutes to run

### ISSUE THREAD

**Issue by benritchie** [specify/specify7#1222]
**Describe the bug**
see summary.  

**To Reproduce**
* open taxon view
* select an entry - e.g. I used betula utilis.  
* right click, select query.  
* get this query:
![image](https://user-images.githubusercontent.com/8005676/162710771-dcce08f1-83a2-4f74-bfab-d3f17aaae708.png)
click run.  
query consistently takes over a minute to run (irrespective of the number of items returned.  )
![image](https://user-images.githubusercontent.com/8005676/162711101-aa1102e3-1567-40f8-acbb-76d4501d6f9d.png)

**Expected behavior**
this query doesn't look computationally intensive.  I'd have expected it to be able to occur far faster.  
e.g. if I hand craft a query to return the same results, it runs in a couple of seconds:
![image](https://user-images.githubusercontent.com/8005676/162711326-f846a7d5-b818-4b1a-86e1-be16946b21e6.png)

This maybe suggests a possible fix?

**Reported By**
RBGE (discussed in our regular call last week)

**Additional context**

**Comment by realVinayak** [comment]
Actually, Ben Ritchie was running two different queries. Query that tree viewer generates includes climbing the tree till a particular rank. Looks like the query he made here takes direct join to taxon, and doesn't climb - and that is why it is fast. However, they are two different queries with different results.

**Comment by realVinayak** [comment]
Actually reopening it since it can still be a problem. This was partially resolved in `recursive-cte-experimental` branch.

**Comment by grantfitzsimmons** [comment]
Test this again when looking at the #3613 branch
