### ISSUE TITLE
Add a "no restrictions" mode to the WorkBench mapper

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1226]
In some cases, access is needed to map to a system table.
For example, to upload a taxon tree, a taxontreedef table needs to be mapped.
Should add some way to map to fields that are normally hidden.
Maybe some sort of "no restrictions" pref that would add all fields and tables to the mapper?

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/168130961-d7491b82-dfb9-4cb1-985d-8b52d269d263.png)

This is too much power...
