### ISSUE TITLE
[a11y] Agent form displays a comma after New Agent: conditionally

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1227]
**Describe the bug**
<img width="300" alt="image" src="https://user-images.githubusercontent.com/37256050/163507713-4ed5de44-c4bc-4ba3-bb85-e3b56c7f2272.png">

When other option is selected:
<img width="347" alt="image" src="https://user-images.githubusercontent.com/37256050/163507820-7913a383-8c61-4eb5-aecc-d9dc449d6e35.png">

**To Reproduce**

1. Go to the Agent form
2. See Person is selected in the pick list (default)
3. See comma after New Agent:

**Comment by maxxxxxdlp** [comment]
Fixed in 7f50112 by returning a blank formatter if all relevant fields are blank
