### ISSUE TITLE
[a11y] collectionrelonetomanyplugin indistinguishable from background

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1229]
**Describe the bug**
The collectionrelonetomanyplugin falls into the background. It has never appeared entirely properly in previous 7 versions but now it is difficult to distinguish.

**To Reproduce**
1. Create a CO record
2. Add a CO relationship

**Screenshots**
How it appears currently:
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/37256050/163509365-b5012523-b2cf-45a1-8e7c-fafa9f3d5e2e.png">

How it could or should look:
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/37256050/163509494-78e2863a-73f4-4a66-a510-532af61b02ee.png">

How it looks currently:
<img width="426" alt="image" src="https://user-images.githubusercontent.com/37256050/163509504-464be597-a070-4113-a10b-bf02cf58ef46.png">

<img width="518" alt="image" src="https://user-images.githubusercontent.com/37256050/163509689-c73bde89-2d9b-463b-9323-ad2683cc8b97.png">
The checkmark is a questionable placement for icon as well

**Comment by maxxxxxdlp** [comment]
Fixed in [0c3b99c](https://github.com/specify/specify7/commit/0c3b99c7766352cf988c2649505d8c834679002a)
