### ISSUE TITLE
"save and add another" Gift doesn't save

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#123]
If you create a Gift and use the "Save and Add Another" feature, it grays out the "save" and "save and add another" features until you make any changes to the gift, however it doesn't actually save the gift.

So if you select the "save and add another" option and then make changes and save a second gift, only the second gift will be saved; any gifts saved using "save and add another" will not be saved.

**Comment by benanhalt** [comment]
@timo11 Does "save and add another" make sense for interaction forms? Does Sp6 support it?

**Comment by timo11** [comment]
I don't think it's necessary or sensible.
Especially not for loans and gifts.
