### ISSUE TITLE
[a11y] Some pick lists show the value instead of title

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1230]
**Describe the bug**
Saving a Collection Object record prompts the user to select a label or report.

**To Reproduce**
1. Go to the Agent form
2. Add variants
3. See error

**Expected behavior**
It should display the title and not the value.

**Screenshots**
<img width="377" alt="image" src="https://user-images.githubusercontent.com/37256050/163510372-9be24b53-c91f-4f00-8f43-0ba096fda2d1.png">

<img width="318" alt="image" src="https://user-images.githubusercontent.com/37256050/163510423-70f9c2d6-38ed-487e-814f-56fd4a5cff7c.png">

<img width="350" alt="image" src="https://user-images.githubusercontent.com/37256050/163511559-3d68454c-1bff-4d6b-bb07-606695946977.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Edge, Safari

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/163585352-feebac1a-8529-4410-8018-b5990a5576e9.png)

**Comment by maxxxxxdlp** [comment]
Fixed in 98865f7
