### ISSUE TITLE
[a11y] Add option appears on read-only pick lists

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1231]
**Describe the bug**
Add option is present on read-only pick lists. It does not have a function.

**Screenshots**
<img width="243" alt="image" src="https://user-images.githubusercontent.com/37256050/163510528-d06ed2c8-222b-42d8-88bd-6faed1a39557.png">

**Comment by maxxxxxdlp** [comment]
Fixed in [c7b85eb](https://github.com/specify/specify7/commit/c7b85ebd3d86af320f0af821afce65612f322e73)
