### ISSUE TITLE
[a11y] Collectors form displaying incorrectly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1233]
**Screenshots**
How it currently appears:
![](https://user-images.githubusercontent.com/37256050/163510681-44a8e719-07e2-4d77-a0a2-133876b4790d.png)

Authors subform on Reference Work:
<img width="581" alt="image" src="https://user-images.githubusercontent.com/37256050/163511898-5eb36da9-5f51-47bf-895e-f7aff427c734.png">

How it should appear:
<img width="956" alt="image" src="https://user-images.githubusercontent.com/37256050/163511003-d364a767-819f-470e-844f-493cbc1d777c.png">

**Comment by maxxxxxdlp** [comment]
Fixed in [06bd112](https://github.com/specify/specify7/commit/06bd112237c84a936b8e266c210387f6c080cc88)
