### ISSUE TITLE
[a11y] Some lists briefly display the API request

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1236]
**Describe the bug**
See screenshot

**To Reproduce**
1. Pick an Agent from a picklist
2. See flash of text before the name finishes loading

**Expected behavior**
It should be blank until the name appears.

**Screenshots**
_This was taken with a screen recording since it happens so fast. It is visible however._
<img width="542" alt="image" src="https://user-images.githubusercontent.com/37256050/163513279-2c4f0448-62c7-47af-970a-26f5e283ed55.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Edge

**Comment by maxxxxxdlp** [comment]
Fixed in [866e777](https://github.com/specify/specify7/commit/866e777682ce81cbdae5ec16cf644d63b62c7424)
