### ISSUE TITLE
[a11y] Email button is non-functional

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1238]
**Describe the bug**
The email button does not work

**To Reproduce**
1. Go to the Agent form
2. Attempt to use the mailto button
3. See nothing happens 

**Expected behavior**
It should open a new email compose window.
_Tested in edge, is working fine._

**Screenshots**
![image](https://user-images.githubusercontent.com/37256050/163586107-d25bee87-e3e2-42f6-9fbe-5a1ab760249a.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/163601754-394e0cfa-457b-4acd-9f32-fd21f8a3d73d.png)

Weblinks may just be non-functional currently.

**Comment by maxxxxxdlp** [comment]
Fixed in [0352d0a](https://github.com/specify/specify7/commit/0352d0a929f32439f1a59014c09f3a38fa711c80)
