### ISSUE TITLE
[a11y] Agent Attachments not appearing

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1239]
**Describe the bug**
Agent attachments are not appearing.

**To Reproduce**
1. Go to the Agent form
2. See missing attachments

**Expected behavior**
![image](https://user-images.githubusercontent.com/37256050/163586416-96014a89-c954-4ab9-a809-7620d675f309.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/37256050/163586399-53726a5c-5a1c-482f-8c51-4f4184ff034e.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari

**Comment by maxxxxxdlp** [comment]
Seems to be working now
May have been fixed by af326cbf
