### ISSUE TITLE
"Save and Add Another" error on next save

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#124]
For permits, loans, and RAs (possibly other fields that have the "save and add another" ability, although there is a different issue with this for Gifts - see #123), selecting "save and add another" and then either attempting to save or save and add another causes an error.

This is probably because it lets you try to save even without changing the data in fields that are required to be unique (permit number, loan number, RA number). The expected action is that these fields are highlighted red with a warning message "value must be unique to division" if you select the "save" or "save and add another" options.

**Comment by benanhalt** [comment]
Still present in accession. The underlying problem is the carry-forward mechanism that replaces the accession number field when it should be unique. Maybe carry forward should ignore unique fields that are not autonumbered.

**Comment by garrettgirard** [comment]
This is also a problem when adding new users. If you create a user and do "Save and Add Another", saving will give you a "duplicate entry" error.

Error:
IntegrityError at /api/specify/specifyuser/
(1062, "Duplicate entry 'usetester' for key 'Name'")
