### ISSUE TITLE
[a11y] Tree node's parent is greater than itself error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1240]
**Describe the bug**
Save and add another immediately causes this error in Specify if there is no greater node

Maybe a user friendly error should appear instead.

**Expected behavior**
A friendly warning perhaps.

**Screenshots**
![image](https://user-images.githubusercontent.com/37256050/163586617-3269cf38-d6ac-4f09-80d0-b398b35fff99.png)

**Comment by maxxxxxdlp** [comment]
This would be fixed by the fix for #1235
