### ISSUE TITLE
[a11y] Determinations not appearing on the CO form

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1242]
**Describe the bug**
Determinations that are present do not appear on the form.

**To Reproduce**
1. Go to the CO form (`/specify/view/collectionobject/5327/` for freshfish)
2. See missing determinations

**Expected behavior**
![image](https://user-images.githubusercontent.com/37256050/163588398-acd97efe-b006-464d-a47e-6936ed8e046e.png)
Using 'edge'

**Screenshots**
![image](https://user-images.githubusercontent.com/37256050/163588383-f3e9cd4c-577f-4a5c-a34f-590808078b6a.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Edge

**Comment by maxxxxxdlp** [comment]
Does not seem to happen anymore
Can you test this again?
