### ISSUE TITLE
[a11y] Date edited does not show the correct date

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1245]
**Describe the bug**
Date Edited shows mm/dd/yyyy instead of the previous edit date.

**To Reproduce**
1. Go to the CO form (`/specify/view/collectionobject/5327/` for freshfish)
2. See missing Col Obj Attributes

**Expected behavior**
![image](https://user-images.githubusercontent.com/37256050/163589986-5aa666c8-0ffc-4628-b775-2461c9ff18ab.png)
Using 'edge'

**Screenshots**
![image](https://user-images.githubusercontent.com/37256050/163589955-69a44ebd-fcbb-4cf6-b079-d98643a01d19.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Edge

**Comment by maxxxxxdlp** [comment]
Fixed in 31c3d639
