### ISSUE TITLE
[a11y] Subview modifications do not make the form savable

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1246]
**Describe the bug**
Modifying or adding something in a subview does not prompt the form to be savable.

**To Reproduce**
1. Go to the CO form (`/specify/view/collectionobject/5327/` for freshfish)
2. Add preparations/determinations
3. See the issue

**Expected behavior**
![Screen Shot 2022-04-15 at 10 32 55 AM](https://user-images.githubusercontent.com/37256050/163590193-deb4378f-9601-4338-8bd0-d2bef6030a83.png)
Using 'edge'

**Screenshots**
![image](https://user-images.githubusercontent.com/37256050/163590172-e1057466-256f-46dd-9474-83ce3e679842.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Edge

**Comment by maxxxxxdlp** [comment]
Unable to replicate it.
Can you check again if the issue has been fixed?

**Comment by grantfitzsimmons** [comment]
Cannot replicate on any browser

**Comment by grantfitzsimmons** [comment]
![msedge_qwFngCAMto](https://user-images.githubusercontent.com/37256050/167658357-8ec4a930-3c4c-47c5-8363-d58e16d10a55.gif)

I was able to recreate this today.

db: fwri
user: plarson
col: ichthyology
form: CO Attribute

**Comment by maxxxxxdlp** [comment]
Seems fixed now
