### ISSUE TITLE
[a11y] QCBX selection broken

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1247]
**Describe the bug**
I cannot select items from the dropdown in QCBXs. This is true with the mouse as well as with the keyboard.

**To Reproduce**
1. Go to the Geography form
2. Type some value into the Parent of Geo
3. See error when trying to select with keyboard

**Expected behavior**
![image](https://user-images.githubusercontent.com/37256050/163600035-403ad905-f1c7-4eca-a1d3-56e2557252b3.png)
**Screenshots**
My arrow keys just move the | to the front and back of the field instead of up and down the list.
![image](https://user-images.githubusercontent.com/37256050/163599948-562b3ddb-545d-4e00-bd83-7664aa523afa.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Edge

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/163600334-8aba7f53-4a58-44a9-8cc3-9192e9a058b4.png)

As an aside, I cannot select the final option with my keyboard in the Preferred Geo either. When attempting to select it with the keyboard the dropdown closes.

**Comment by maxxxxxdlp** [comment]
Just tested this in different browsers.
Seems to only happen in Edge.
Should be fixed by 4da13316

**Comment by grantfitzsimmons** [comment]
Bunch of issues, related https://github.com/specify/specify7/issues/1347

**Comment by grantfitzsimmons** [comment]
In most cases, QCBX are now working in the DB

**Comment by maxxxxxdlp** [comment]
Can you test this again in Safari and Edge?

**Comment by grantfitzsimmons** [comment]
Working in Chrome, Edge, and Safari on my Mac. 

Had to manually select the field with the keyboard to get it to work on Safari.
