### ISSUE TITLE
[a11y] Repair tree menu gives a blank menu for non-managers

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1250]
**To Reproduce**
1. Go to Repair Tree
2. See error

**Expected behavior**
![image](https://user-images.githubusercontent.com/37256050/163603862-ff73d56c-2001-4d1b-8fa8-e4f10fda2413.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/37256050/163603879-db9d6941-9019-4a8f-aa75-414497dc989e.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Edge

**Comment by grantfitzsimmons** [comment]
After testing this further the account I was using was a regular user.

**Comment by maxxxxxdlp** [comment]
Fixed by restricting tree repair to super admins
