### ISSUE TITLE
Tree ranks not showing up correctly

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1256]
**Describe the bug**
When opening a tree form the rank field contains API information rather than the rank name

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**
![Tree ranks](https://user-images.githubusercontent.com/7501989/163878583-5905998b-9add-4658-81c0-ca43c19aeca8.JPG)

**Comment by maxxxxxdlp** [comment]
Fixed in 49f997ec
