### ISSUE TITLE
Picklists not working

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1257]
**Describe the bug**
When using arrow keys to navigate a picklist, more than one click makes the picklist disappear

**To Reproduce**
1. Type a couple of letters into a picklist
2. Use arrow keys to navigate through options presented
3. Click more than once
4. Picklist should disappear

**Expected behavior**
You should be able to navigate all options in a picklist using arrow keys

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Fixed in [5183965](https://github.com/specify/specify7/commit/51839655d429ccc5c9178a937647955b6ce68cbb)
