### ISSUE TITLE
Picklists not working - changing items

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1258]
**Describe the bug**
Entering a new name into the agent field after entering an existing name causes unexpected behavior

**To Reproduce**
1. Type the first letter of an agent last name into the agent field
2. Click the x to remove it
3. The name reappears
4. Click the x again
5. The name disappears
6. Click in the field again
7. The previous picklist shows up again even though nothing is typed in
8. Choose a different name from the list
9. The field indicates that the field needs to be filled out even though the previous name gets reinserted

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Fixed in 
9ecf853
