### ISSUE TITLE
Form button icons too small

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1259]
**Describe the bug**
The icons associated with buttons on forms are too small

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**
![icons](https://user-images.githubusercontent.com/7501989/163880627-0b4996f7-73ea-4e39-836f-e9585de59a3c.JPG)

**Comment by maxxxxxdlp** [comment]
Fixed in [b60f062](https://github.com/specify/specify7/commit/b60f06278f6ac1114e37437b61fb25edaf565bab)
