### ISSUE TITLE
Report window always shown when saving a record

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1260]
**Describe the bug**
The report window always shows when saving a record.  In Specify 6 this is governed by a "create label on save" field on the form.  Users do not want to have to navigate this window each time unless necessary

**To Reproduce**
1. Save a collection object record
2. Report window pops up
3. Have to close it before another record can be saved

**Expected behavior**
Report window should be generated only when "Create label on save" field is checked

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
The "Create Label on Save" checkbox is present on that form, but has `initialize="visible=false"` attribute
See https://github.com/specify/specify7/issues/1244
The current Sp7 release ignored that attribute, but the new one respects it.
I updated the forms on a11y.test.specifysystems.org to unhide the checkbox. Note, you may have to clean the cache before you see the form definition changes (to do that, open the "User Tools" menu and click on "Clear Cache")
