### ISSUE TITLE
Report window shows unrelated reports

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1261]
**Describe the bug**
The report window shows all active reports even if they do not pertain to this data - loan reports for collection objects.  There needs to be some context built in to prevent this

**To Reproduce**
1. Save a collection object
2. Report window is shown
3. Other reports (loan forms, etc.) are able to be clicked and produce blank reports

**Expected behavior**
Context should prevent unrelated reports from being active in certain circumstances

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Fixed in the process of rewriting reports to React
