### ISSUE TITLE
[a11y] When creating a new app resource, it does not populate the list of resources

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1265]
**Describe the bug**

When creating a new app resource, it does not populate the list of resources on the left.

See /specify/appresources/146/ on fresh fish.

It does not appear in the left menu but it exists.

**Comment by maxxxxxdlp** [comment]
Same cause as https://github.com/specify/specify7/issues/1101
Moving away from Backbone would fix it

**Comment by grantfitzsimmons** [comment]
This is fixed, but unfortunately databases that had resources created in them while it was an issue still do not show the resource in the sidebar.

`nm3`, `/specify/viewsets/2/`

Currently live: https://a11y-2-2-2.test.specifysystems.org/specify/viewsets/2/

**Comment by maxxxxxdlp** [comment]
Yes, that would be the case.
The bug caused app resources to be created without a name.
You can find them by searching on SpAppResource.name = Empty using the query builder

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/168329511-a66a3765-3495-4325-b53d-4a0f8679a958.png)
![image](https://user-images.githubusercontent.com/37256050/168329540-620b0c51-e9f3-4a23-98ff-84edd9246299.png)

**Comment by grantfitzsimmons** [comment]
If Name -> Any
![image](https://user-images.githubusercontent.com/37256050/168329623-f7ed889d-5838-4190-9251-531457d1d427.png)

**Comment by maxxxxxdlp** [comment]
Ah, view sets are stored in a separate table
Search for SpViewSetObj.name = Empty

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/168330890-ed0b3c97-297b-4b44-aed3-e67a59f0eb8e.png)

The forms don't generate for those tables... would you like me to open a bug?

**Comment by maxxxxxdlp** [comment]
That's probably because all fields are hidden. Sure open an issue
