### ISSUE TITLE
QCBX search not working as expected

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1267]
**Describe the bug**
The search dialog associated with QCBX's (magnifying glass) does not allow selection of items searched for

**To Reproduce**
1. Click the magnifying glass icon next to a QCBX
2. Search for a name
3. Select that name
4. Dialog disappears and the name is not inserted into the field

**Expected behavior**
I would expect the selected name to be inserted in the field

**Screenshots**
![Taxon search](https://user-images.githubusercontent.com/7501989/164032772-1f1d8598-7776-498c-a089-80cb56a14c09.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**

Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Fixed in [f8aac21](https://github.com/specify/specify7/commit/f8aac21211ef07577b2e26f4970c63b753ab3511)
