### ISSUE TITLE
QCBX search through query builder has large whitespace above results

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1268]
**Describe the bug**
There is a large white space above the query results created from a QCBX search that obscures the results

**To Reproduce**
1. Click on magnifying glass associated with QCBX
2. Click on Query builder button on the resulting form
3. Search for a taxon name
4. Results appear but there is a large section of white space above the results that obscure them
5. There is also no way of selecting a result to insert into the relevant field (check boxes do not work and there is no button to select)

**Expected behavior**
No white space and method to insert selected value into field

**Screenshots**
![Taxon search](https://user-images.githubusercontent.com/7501989/164033651-e4846282-b6bd-4d8b-ae63-7d5f987720df.JPG)
![Taxon search results](https://user-images.githubusercontent.com/7501989/164033658-f338f1d7-38f7-4534-9a5b-cf1ee448dbdf.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Fixed in [f546904](https://github.com/specify/specify7/commit/f5469042e8210b60deb6cf1e0b626a2610966baa)
