### ISSUE TITLE
Search associated with accessions QCBX produces error

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1269]
**Describe the bug**
Searching on accessions QCBX (magnifying glass) from collection object form produces error

**To Reproduce**
1. Click on magnifying glass associated with accessions QCBX on collection object form
2. Error message results

**Expected behavior**

**Screenshots**
![Accessions search](https://user-images.githubusercontent.com/7501989/164034463-26c889f6-a878-448b-849b-a5726b674f9a.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Fixed in 
ac78548
