### ISSUE TITLE
Date picker not working

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1270]
**Describe the bug**
Date picker widget in date fields not working

**To Reproduce**
1. Go to a date field
2. Click on the date picker on the right-hand side of the field
3. Select a date
4. Dialog disappears and date is not selected

**Expected behavior**

**Screenshots**
![Date picker](https://user-images.githubusercontent.com/7501989/164035673-1d5afcc2-d3e1-4b85-8202-6cbcea0c09fe.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Fixed in [98d6c0a](https://github.com/specify/specify7/commit/98d6c0aa104c49ec8b14b0951dfde74b3c00ab92)
