### ISSUE TITLE
Agent drop down list not alphabetically sorted

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1271]
**Describe the bug**
The drop-down list associated with agent QCBX's is not sorted alphabetically

**To Reproduce**
1. Go to an agent field
2. Type in the first couple of letters of a name
3. Agent last names are not alphabetically sorted

**Expected behavior**
Alphabetically sorted

**Screenshots**
![Agent drop-down list](https://user-images.githubusercontent.com/7501989/164036437-e652da39-fca6-4c7a-9a70-eb8d93442d21.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Fixed in [83e1061](https://github.com/specify/specify7/commit/83e10616eaad871be510d0782cad1285f0bdf776)
