### ISSUE TITLE
Cancel button remains red after resolving issue on form

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1272]
**Describe the bug**
After resolving an issue on a form that is preventing save, the cancel button remains red

**To Reproduce**
1. Go to any form
2. Create an error on the form that will not allow save
3. Correct the error
4. Save button turns orange but cancel button remains red

**Expected behavior**
Cancel button should revert to orange like save button

**Screenshots**
![Cancel button](https://user-images.githubusercontent.com/7501989/164037314-49dcebe2-ba5f-4217-afd4-ed94c07f39e3.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
The cancel button being red indicates that there are unsaved changes on the form and that pressing the button would mean losing those changes.
Currently, the button changes color from Blue to Red once changes were made, and the label changes from "Close" to "Cancel".
