### ISSUE TITLE
Determination save automatically inserting Holotype in type status field

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1273]
**Describe the bug**
Determination save automatically inserting Holotype in type status field

**To Reproduce**
1. Go to determinations
2. Add a new determination
3. Click save on collection object record
4. Holotype automatically inserted into type status field

**Expected behavior**

**Screenshots**
Before save
![Determination before save](https://user-images.githubusercontent.com/7501989/164038836-f6de7545-3b47-41a2-b6d8-979695a1c6eb.JPG)
After save
![Determination after save](https://user-images.githubusercontent.com/7501989/164038879-bbc3beb4-95fe-4b88-b4b8-e22274e7d103.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Fixed in 328a81b9
`Holotype` is the default value for that picklist according to the form definition.
The default value was being set, but not visible on the form. That bug is now fixed
