### ISSUE TITLE
[a11y] CO fields with custom labels not displaying correctly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1274]
**Describe the bug**
Collection Object fields with custom labels are not displaying.

**Expected behavior**
![image](https://user-images.githubusercontent.com/37256050/164039827-e4ce0a36-7227-4822-bc03-af13e2e85f00.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/37256050/164039773-ae22a22a-5cae-425e-92f0-84fd8d3deb68.png)

macOS, Edge

db: newmexico

**Comment by grantfitzsimmons** [comment]
Also I just noticed the strange height difference between the date picker and the date pick list

**Comment by maxxxxxdlp** [comment]
The schema config is missing captions for those fields:

![Screen Shot 2022-04-19 at 15 54 07](https://user-images.githubusercontent.com/40512816/164093932-8238afe7-8327-4af6-8417-917338338fc4.png)

Created a separate issue for the temporal date height inconsistency: https://github.com/specify/specify7/issues/1285

**Comment by grantfitzsimmons** [comment]
How would it show up in edge? When SSH'in into the db with 6 the fields have captions.

**Comment by maxxxxxdlp** [comment]
@benanhalt It seems like `splocaleitemstr.country=""` should be treated the same as `splocaleitemstr.country=null`

Here is the difference between the schema_localization.json (text5 name differs between branches):
![Screen Shot 2022-04-19 at 16 24 55](https://user-images.githubusercontent.com/40512816/164104449-5caeec64-f622-43b6-945d-9a00624447c7.png)
![Screen Shot 2022-04-19 at 16 24 58](https://user-images.githubusercontent.com/40512816/164104454-b8f72490-a519-4581-8087-08699ae2a947.png)

Database is newmexico in both cases (it is deployed on the test server on both a11y and edge branches)
