### ISSUE TITLE
[a11y] Tab previews not appearing

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1278]
**Describe the bug**
Currently a tab name is generated and allows users to switch between tabs. The next release only displays "Specify 7".

![image](https://user-images.githubusercontent.com/37256050/164050067-b481a178-2c5d-4e80-90f5-1f646de65c81.png)
Left: edge
Right: a11y

**Desktop (please complete the following information):**
 - OS: macOS, Safari

**Comment by grantfitzsimmons** [comment]
Both are on a blank CO form

**Comment by maxxxxxdlp** [comment]
Fixed. The tab content now reflects current resource or dialog

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/167216746-e16a9047-eb7a-4651-b8c9-3d6daee2b3ec.png)

Maybe Borrow should still be visible

**Comment by maxxxxxdlp** [comment]
Revered previous behavior in [51019c7](https://github.com/specify/specify7/commit/51019c709db68cd3347e24c4592c8e9c84e8ff86)

Added a pref to remove table name from the title
