### ISSUE TITLE
Collection Relationship form gives error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1281]
**Describe the bug**
Opening a CR record gives an error. It should open the Cat # record.

**To Reproduce**
1. Go to `freshfish` at `/specify/query/127/`
2. Run the query
3. Click to open a Cat # from another collection
4. See **Missing form definition**

**Expected behavior**
It should open the record in the appropriate collection.

**Screenshots**

**From KU Fish**
![image](https://user-images.githubusercontent.com/37256050/164059678-371739ea-f08a-4517-a4e3-56431fba5284.png)

After opening:
![image](https://user-images.githubusercontent.com/37256050/164059708-bb6e215e-dd3d-4f70-a983-57d263c4ae78.png)

After opening `a11y`:
![image](https://user-images.githubusercontent.com/37256050/164060063-c2b7e8b6-8713-4685-a0ac-eb3225278ba0.png)

**From CSIRO**
![image](https://user-images.githubusercontent.com/37256050/164059394-09a36902-d6fb-473f-a979-3e77060a82a7.png)

**Desktop (please complete the following information):**
macOS, Safari

**Reported By**
CSIRO

**Comment by maxxxxxdlp** [comment]
There is no form definition for the CollectionRelationship table.
If the form is not present, the current release shows a "Missing form definition" error.
The new release generates a view on the fly using all nonhidden fields. Except, all collection relationship fields are hidden by the schema config, thus the generated form is blank.

Thus, either define a view for CollectionRelationship, or unhide some of it's fields

**Comment by grantfitzsimmons** [comment]
> Thus, either define a view for CollectionRelationship, or unhide some of it's fields

I cannot unhide any fields using the schema editor in 7. I can query the table but not modify the fields.

`/specify/task/schema-config/?language=en&table=collectionrelationship` does not work

**Comment by maxxxxxdlp** [comment]
Opened https://github.com/specify/specify7/issues/1322 for that
