### ISSUE TITLE
Bring back drag sort in Query Builder

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1282]
Add a draggable region to query lines like this:
![image](https://user-images.githubusercontent.com/40512816/164061989-5aaec599-5bd1-4d72-a0ca-f0271aec9429.png)

**Comment by grantfitzsimmons** [comment]
**Requested By:** [Plarson on the Specify Forum](https://discourse.specifysoftware.org/t/arrange-query-items-with-mouse-drag-specify-7/554)

**Comment by maxxxxxdlp** [comment]
Can testify to this being a useful feature and the new "buttons only" solution being insufficient.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-9-release-announcement/1131/1
