### ISSUE TITLE
Collection Relationships should work without matching Cat # formatters

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1283]
**Is your feature request related to a problem? Please describe.**
Specify 6 and 7 have no way to create a collection relationship with collections that use different catalog number formats. This restriction is very frustrating for users.

CSIRO wants to create collection relationships for their Fish Collection, connecting the main collection to tissues and X-rays. They use unique catalog number formatting making this difficult to implement due to the current restrictions.

**Describe the solution you'd like**
CRs should be configurable between all collections of varying Catalog Number formatting.

**Screenshots**

The restriction seems to be arbitrary:

![image](https://user-images.githubusercontent.com/37256050/164062327-b91355d8-ed95-4cd1-a6ad-8200c20c4558.png)
_Screenshot from CSIRO_

**Reported By**
CSIRO

**Comment by maxxxxxdlp** [comment]
I don't know enough about how collection relationships work, but what specific part in specify 7 is preventing collection relationships between collections with different catalog numbers?

Is there some error message?

Or is it just a matter of the search dialog enforcing a certain catalog number formatter?

If the latter is the case, you can open the "Query Builder" dialog, and add a "Contains" or "Like" filter on the "Catalog Number" (those don't have auto-formatting enabled)

**Comment by benanhalt** [comment]
It is my strong suspicion that this restriction stems from the Specify 6 UI determining the formatters for fields based on the logged in collection. Obviously using a collection relationship will involve dealing with catalog numbers of the associated collection. If those are different, then there would have to be some mechanism for handling two different formatters for the "same" field.

The same problem would arise in Specify 7. Resolving it would probably involve adding a mechanism to any UI involved with the collection relationships to keep track of the "foreign" catalog number formatter. That would include being able to access the formatter definition itself. A collection's catalog number formatter is indicated in the collection table, so at least it wouldn't be necessary to access the schema config of the related collection, but it would be necessary to load the "UIFormatters" app resource of the foreign collection. That is relatively straightforward on the back end and could be accomplished by adding a collectionid  parameter to the app resource endpoint.

I'll let @maxxxxxdlp address the front end ramifications.

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/189924311-bf33a4c4-2a4d-4f4a-9189-6ba1c8d9a755.png)

For the record, I was able to establish a Collection Object Relationship between two collections with different catalogNumber formatters.

This required the following form definition to establish:

```
        <viewdef
            type="form"
            name="CollectionRelType"
            class="edu.ku.brc.specify.datamodel.CollectionRelType"
            gettable="edu.ku.brc.af.ui.forms.DataGetterForObj"
            settable="edu.ku.brc.af.ui.forms.DataSetterForObj">
            <desc><![CDATA[The Journal form - unknown use in schema]]></desc>

            <columnDef>100px,2px,195px,5px,86px,2px,210px,5px,74px,2px,146px,15px,p:g</columnDef>
            <columnDef os="lnx">115px,2px,195px,5px,125px,2px,210px,5px,125px,2px,131px,15px,p:g</columnDef>
            <columnDef os="mac">130px,2px,215px,5px,138px,2px,260px,5px,138px,2px,155px,15px,p:g</columnDef>
            <columnDef os="exp">p,2px,min(p;220px),5px:g,p,2px,p,5px:g,p,2px,200px,p,p:g</columnDef>
            <rowDef auto="true" cell="p" sep="2dlu"/>

            <rows>
                <row>
                    <cell type="label" labelfor="1"/>
                    <cell type="field" id="1" name="name" uitype="text"/>
                    <cell type="label" labelfor="2"/>
                    <cell type="field" id="2" name="remarks" uitype="text"/>
                </row>
                <row>
                    <cell type="label" labelfor="4"/>
                    <cell type="field" id="4" name="leftSideCollection" uitype="querycbx" initialize="name=Collection" isrequired="true" colspan="6"/>
                </row>
                <row>
                    <cell type="label" labelfor="5"/>
                    <cell type="field" id="5" name="rightSideCollection" uitype="querycbx" initialize="name=Collection" isrequired="true" colspan="6"/>
                </row>
            </rows>
        </viewdef>
```

**Comment by maxxxxxdlp** [comment]
Having an incorrect catalog number format no longer prevents running the query (#2186), but it still shows the query filter as incorrect.

@grantfitzsimmons do you think I should completely disable the validation for catalog numbers for queries from this plugin?

If so, do you thin it would be desirable to disable that in other places too? If so, I would add a button for toggling formatter enforcement, and set it to `off` by default for queries from this plugin.

Also, for cases when the catalog number formats do match, you probably don't want to disable validation completely as it can help catch typos

**Comment by maxxxxxdlp** [comment]
The regular search dialog (not the query builder search) does not seem to force a particular catalog number format.

Also, it limits the results to collection objects from the other collection.

@grantfitzsimmons can you check if that is the case, and if that is the desirable behavior?

**Comment by grantfitzsimmons** [comment]
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/37256050/191854198-eb1edd05-3732-4c5a-9dab-addc6fc64ba0.png">

**Fish Col:** https://willemcatno-issue-2185.test.specifysystems.org/specify/view/collectionobject/352109/

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/37256050/191854553-3c0061dc-ac6e-40ec-bc25-fe49d7df07d6.png">

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/37256050/191855284-f44558db-9907-4fbb-a72b-5abd4b89f606.png">

It is only returning the results from the current collection.

https://willemcatno-issue-2185.test.specifysystems.org/specify/view/collectionreltype/14/

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/37256050/191855738-4c2960ed-f157-456f-96ea-e918e9210403.png">

In this db, the QCBX for Collection isn't working correctly. It only returns the current collection when running the QB- which is unexpected behavior. Is something in the TypeSearches app resource amiss?

I'm happy to continue investigating @maxxxxxdlp but I'd like to hear your thoughts before I continue.

username: `collection`
browser: `Chrome, macOS`
branch: `issue-2185`

**Comment by benanhalt** [comment]
I should have anticipated this problem. The query engine automatically limits results to the currently logged in collection. The API will have to be extended to indicate the collection the query should operate under.

**Comment by benanhalt** [comment]
Actually, the ability already exists, though with the permission bug #2208. Just add `collectionid` to the top level request object like this:
```json
{
    "collectionid": 4,
    "contextname": "CollectingEvent",
    "contexttableid": 10,
    "countonly": false,
    "createdbyagent": null,
    "fields": [
        {
            "createdbyagent": null,
            "fieldname": "stationFieldNumber",
            "isdisplay": false,
            "isnot": false,
            "isrelfld": false,
            "mappings": null,
            "modifiedbyagent": null,
            "operstart": 15,
            "position": 0,
            "query": null,
            "resource_uri": "/api/specify/spqueryfield/0/",
            "sorttype": 0,
            "startvalue": "123",
            "stringid": "10.collectingevent.stationFieldNumber",
            "tablelist": "10"
        },
        {
            "createdbyagent": null,
            "fieldname": "",
            "isdisplay": true,
            "isnot": false,
            "isrelfld": false,
            "mappings": null,
            "modifiedbyagent": null,
            "operstart": 8,
            "position": 1,
            "query": null,
            "resource_uri": "/api/specify/spqueryfield/0/",
            "sorttype": 1,
            "startvalue": "",
            "stringid": "10.collectingevent.",
            "tablelist": "10"
        }
    ],
    "isfavorite": false,
    "limit": 1000,
    "modifiedbyagent": null,
    "name": "Ephemeral QueryCBX query",
    "reports": null,
    "resource_uri": "/api/specify/spquery/0/",
    "selectdistinct": false,
    "specifyuser": "/api/specify/specifyuser/1/"
}
```

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons The collection relationship plugin is set up to use the "SlideIs" relationship, not the "Fishy" relationship. 
(`Fishy` is set up in the `Iziko Marine Fish Types` collection instead)

The relationship links collection objects within the same collection `Alga Collection`:

![Screen Shot 2022-09-23 at 13 23 33](https://user-images.githubusercontent.com/40512816/192032726-78879aa1-fc51-44c0-af64-1e109cfc9e11.png)

That is why searching for `hello` does not return anything (that record is in a different collection)

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons Query builder should now scope the results to the other collection as per Ben's comment. The fix should be available on the `issue-2185` branch

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp Why is that the way it is?

<img width="683" alt="image" src="https://user-images.githubusercontent.com/37256050/192034719-f0cd8055-3780-4a8a-a6f6-78196205e771.png">

No SlideIs in the viewdef.

https://willemcatno-issue-2185.test.specifysystems.org/specify/viewsets/1192/

**Comment by maxxxxxdlp** [comment]
Ah, my browser cached old view definition. You are right.

Though, it looks like the search dialog is still not returning the results:

<img width="641" alt="Screen Shot 2022-09-23 at 13 45 32" src="https://user-images.githubusercontent.com/40512816/192036174-354541ed-8baf-4a7d-a950-9dec2d028c38.png">

Where `458752` is the id of the `Iziko Marine Fish Types` collection, and `hello` is https://willemcatno-issue-2185.test.specifysystems.org/specify/view/collectionobject/352109/

@benanhalt Do you know why this is?
It is probably not a high priority, assuming the query builder search would work correctly

**Comment by grantfitzsimmons** [comment]
The QB solution isn't working for me now either. Not really sure why this is the case.

**Comment by benanhalt** [comment]
It might be a separate bug to do with express search. Express search on the Iziko Marine Fish Types collection for "hello" also returns no results. Or it could be something to do with this database.

**Comment by maxxxxxdlp** [comment]
> The QB solution isn't working for me now either. Not really sure why this is the case.

Fixed. @grantfitzsimmons Please test again
