### ISSUE TITLE
Taxon name from taxon tree query not being filled into query

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1284]
**Describe the bug**
When highlighting a name in the taxon tree and querying on that name using the query option, taxon name is not being incorporated into the relevant query field

**To Reproduce**
1. Go to taxon tree
2. Highlight a name
3. Select Query from the menu
4. The name is not being incorporated into the query and the resulting query brings back all CO records

**Expected behavior**
Query should only query for selected name

**Screenshots**
![taxon tree query2](https://user-images.githubusercontent.com/7501989/164067298-0199fa4c-0b9d-454c-b5a5-53d8d5494124.JPG)
![taxon tree query](https://user-images.githubusercontent.com/7501989/164067312-6396a5cd-a5f1-416a-befd-5e576eb6c87c.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Fixed in [6275b8a](https://github.com/specify/specify7/commit/6275b8a2331549d8c970feaef66a8e78fd17be29)
