### ISSUE TITLE
[a11y] Locality not parsing Longitude

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1287]
**Describe the bug**
The LatLong entry form is not correctly parsing the Longitude field.

![image](https://user-images.githubusercontent.com/37256050/164129899-e5ef174a-9818-45ed-8a57-7bb134ddfb82.png)

When the same data is entered on `edge` this does not occur.

This results in the Longitude field not being filled correctly.

![image](https://user-images.githubusercontent.com/37256050/164129946-4f439002-5fc0-41ea-b7d7-cae6bee3be88.png)

**To Reproduce**
1. Create a new locality record
2. Enter some coordinates
3. Run a query to view these fields (`/specify/query/128/`)
4. See error (`/specify/view/locality/10346/`)
 
**DB:** freshfish

**Screenshots**

![image](https://user-images.githubusercontent.com/37256050/164129441-e29463d2-21e0-44f8-8092-147e7f2e01c9.png)

**Desktop (please complete the following information):**
 - macOS, Edge

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/164130314-bcc77d12-321c-46a9-b5bf-a0fb9b4946ab.png)

**Comment by maxxxxxdlp** [comment]
Fixed in 
7b68bcd
