### ISSUE TITLE
Rename resource files

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1288]
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/37256050/164130616-b4b66302-b775-4535-9c58-579802c332da.png">

We should be able to easily rename an app or view resource file

**Comment by maxxxxxdlp** [comment]
Fixed in 97b258751

**Comment by grantfitzsimmons** [comment]
I can't believe this wasn't easy before!
