### ISSUE TITLE
Can't add "Address of Record" to Exchanges

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#129]
Adding "Address of Record" to Exchange In or Exchange Out causes 404 error "Page Not Found"

**Comment by timo11** [comment]
geek alert: at line 21 in querycbxsearch.js, searchdialog for the AddressOfRecord model is undefined. So this is probably a sp 6 config file problem. Is addressofrecord even implemented in Sp6?

**Comment by benanhalt** [comment]
These can't be shared so maybe it should be set as a dependent field allowing the form to be embedded.

**Comment by timo11** [comment]
I made the relation to AddressOfRecord dependent for
Accession
Borrow
Gift
ExchangeIn
ExchangeOut
Loan
RepositoryAgreement.

I only tested the fix on ExchangeIn, ExchangeOut because in my db those were the only forms that had AddressOfRecord visible.
