### ISSUE TITLE
Clear Cache button

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1290]
It would be helpful to have a clear cache button available in the user tools menu (even if it is hidden).

Form editing currently requires logging in and out to view the changes in most cases, so being able to clear that info would make it much easier.

**Comment by maxxxxxdlp** [comment]
The clear cache button is already available in the User Tools menu on the a11y branch.
It is visible for all users regardless of permissions
If you want to clear cache for a specific form, open that form, then open the user tools menu and click clear cache

**Comment by grantfitzsimmons** [comment]
Easiest fix ever. Thanks!
