### ISSUE TITLE
[a11y] Permissions with "all" user issues

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1291]
**Describe the bug**
What happens when you are a user with only "All" permissions (`notsuper` on `freshfish`) the following occurs.

**To Reproduce**
1. Log into **notsuper**
2. Go to Security Panel
3. See error, dismiss.
![Screen Shot 2022-04-20 at 1 36 06 PM](https://user-images.githubusercontent.com/37256050/164303378-bbcc68c2-a0fa-40ca-9b32-505cb5b565f2.png)
4. Click on Institution or collection
5. See access!!!
6. Once you click on a user, this pair of errors appear:
![image](https://user-images.githubusercontent.com/37256050/164303732-32b57ea2-2505-4f0e-a825-636340381892.png)
7. When attempting to save one of the users:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/37256050/164305117-e2ab7351-0c92-48b3-8935-cfa6237bbb9d.png">

**Comment by maxxxxxdlp** [comment]
@benanhalt
This is a problem with institutional policies and the permissions query endpoint.
A user has all access to all resources on a collection, but doesn't have any policies on the institution level. The permission query says that the has full access to library roles, but in reality that is not the case:

![Screen Shot 2022-05-13 at 16 03 33](https://user-images.githubusercontent.com/40512816/168389314-13c2b017-9dba-483a-a96d-5e22d8a5016d.png)

**Comment by maxxxxxdlp** [comment]
Fixed by making front-end check if the policy is scoped to an institution and if so, making sure that for a given policy,  matching_user_policies[any].collectionid === null
