### ISSUE TITLE
Red permission checkboxes

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1293]
**Describe the bug**
Not sure why the below checkboxes are red when unchecked.  They should just be blank white like all other unchecked boxes on the same screen

**To Reproduce**
1. Go to security panel
2. Click on collection and then user
3. Add a policy

**Expected behavior**
Checkboxes should just be blank white like all other unchecked boxes on the same screen

**Screenshots**
![security panel3](https://user-images.githubusercontent.com/7501989/164308362-a6ca24bc-a9b8-43d3-b553-3495730eab48.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Fixed in 91533197
Now they are blue!

Blue background means a field is required. You are required to give permission to at least one action for each resource. As soon as you check one checkbox, all others become optional, thus they turn white
