### ISSUE TITLE
Login under rmartin to freshfish creates error in security panel

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1294]
**Describe the bug**
I get the below error message when trying to access the security panel using rmartin login

**To Reproduce**
1. Login to freshfish using rmartin/testuser
2. Click on Security Panel
3. Click on rmartin user

**Expected behavior**

**Screenshots**
![permission denied](https://user-images.githubusercontent.com/7501989/164315573-3bb9ea33-4a0b-4a74-bee0-856651a5eafe.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Duplicate of #1291
