### ISSUE TITLE
Desynonymize not unsynonymize

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1295]
**Describe the bug**
The opposite of synonymize is desynonymize and not unsynonymize

**To Reproduce**

**Expected behavior**

**Screenshots**
![synonymize](https://user-images.githubusercontent.com/7501989/164319115-8c150b95-6150-4ca6-9428-ecc9df123a26.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by benanhalt** [comment]
@maxxxxxdlp The endpoint for that is also currently named unsynonymize. Do you want me to rename it also, for consistency?

**Comment by maxxxxxdlp** [comment]
Sure, go ahead

**Comment by grantfitzsimmons** [comment]
Visually correct, cannot test until security panel is working
