### ISSUE TITLE
FishBase plugin doesn't appear on non fish collection forms

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1296]
If I add the fishbase plugin to a non-fish collection form, the plugin does not appear.

**Comment by tlammer** [comment]
it isn't showing up for me in either.
Andy has it working in his database in both versions

**Comment by maxxxxxdlp** [comment]
FishBase is not a plugin. It is a weblink
If weblink is defined in the database, it should just work, regardless of the collection type

**Comment by tlammer** [comment]
ahh, I read plugin in the xml and assumed it was a plugin but I couldn't get it working before.  I just tried again and it is working so maybe it was a caching issue when I added it to the form?  I'll mark as invalid
