### ISSUE TITLE
[a11y] WorkBench error cells not highlighted

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1300]
**Describe the bug**
Error cells have no red background

**To Reproduce**
1. Validate a WB import
2. Find error cells
3. See no red

**Expected behavior**
These cells should have red backgrounds

**Screenshots**
![image](https://user-images.githubusercontent.com/37256050/164472998-eb6ab778-a4c4-4e38-a113-573091baa9dd.png)

**Desktop (please complete the following information):**
 macOS, Edge

**Comment by grantfitzsimmons** [comment]
Important addition, it also does not display the tooltip associated with the error

**Comment by maxxxxxdlp** [comment]
Fixed in [f7f8921](https://github.com/specify/specify7/commit/f7f8921c8f527bd6b5dbbb698a282ef31215acd8)

**Comment by grantfitzsimmons** [comment]
Somehow this issue has returned
