### ISSUE TITLE
[a11y] No contrast for headings in WB preview

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1301]
**Describe the bug**
Headings have dark text on a dark background in the WB import preview.

**Screenshots**
![image](https://user-images.githubusercontent.com/37256050/164473550-1af20865-9dfc-47a5-93f6-75628b2d8741.png)

**Comment by maxxxxxdlp** [comment]
Fixed in [74a67af](https://github.com/specify/specify7/commit/74a67af1fbccf04d3bd34ee4e5809ea7e10e86f9)
