### ISSUE TITLE
[a11y] Required fields are different than before

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1303]
**Describe the bug**
a11y now requires fields that were not required in the previous version to upload.

**To Reproduce**
1. Go to a WB import
2. See table like Geography or Taxon
3. See difference

**Expected behavior**
These fields should not be required to upload- right?

**Screenshots**

## Geography
![image](https://user-images.githubusercontent.com/37256050/164476629-be7c521e-5b8a-4f4a-b1d1-7950fe71e436.png)

![image](https://user-images.githubusercontent.com/37256050/164476746-54f665b4-9984-4612-8857-33d70a74c3e9.png)

## Taxon
![image](https://user-images.githubusercontent.com/37256050/164476950-a6eef86c-ad26-4603-ac85-c9b379e776f0.png)

![image](https://user-images.githubusercontent.com/37256050/164476913-dd666bba-844b-4fd5-ba2c-7be224ce3fc1.png)

**Desktop (please complete the following information):**
 - OS: macOS, Edge

**Comment by maxxxxxdlp** [comment]
Does not happen for me
Looks like it is fixed now
