### ISSUE TITLE
[a11y] Data mapper validation showing duplicates

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1304]
**Describe the bug**
Duplicate fields displaying when validating WB data in the data mapper.

**Screenshots**
![image](https://user-images.githubusercontent.com/37256050/164477216-ab93189e-c80e-4ff4-8153-b26b638dce9a.png)

macOS, Edge

**Comment by maxxxxxdlp** [comment]
This may be fixed now. Needs testing again

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/166033833-e17f437c-c173-429a-9219-bc7f353e515e.png)
