### ISSUE TITLE
Ctrl or ⌘ + Enter should trigger button event in dialog/form

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1305]
**Is your feature request related to a problem? Please describe.**
When you have configured a query and are ready to run it you have to move the mouse down to run it.
If you finish entering in the data you want to query for a report you have to move the mouse down to run it.
There are many small situations like this in Specify.

**Describe the solution you'd like**
The dominant button should be triggered when ⌘ or CMD + Enter is performed.

It could work like sending a message by entering text and pressing ⌘ + Enter to send it

**Comment by maxxxxxdlp** [comment]
Just hit "Enter" and it will press the "Save" button in forms and form dialogs.
That action is automatically suppressed when you are in a multiline text field, or when focus is on a button.
That behavior is controlled by the browser

**Comment by maxxxxxdlp** [comment]
For dialogs that are not forms, just press "Tab" at it would focs the next focussable element, which is likely to be the dialog close button.
If there are other focusable elements in the dialog (i.e, input fields), you can press `Shify+Tab` to focus the previous element (i.e., the last button in a dialog)
