### ISSUE TITLE
Saving a CO produces an unexpected pop up message

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1307]
Occurred in the nbm-mnb database on server 6.
Clicked Data entry
Clicked to create a new CO
typed a few letters in Observation Remarks and saved the record.  Got the notice below

![image](https://user-images.githubusercontent.com/12532430/164518646-98b83a7f-2bd1-4e8a-ac10-cd9bf2f0448a.png)

**Comment by maxxxxxdlp** [comment]
The form has a "Print on Save" checkbox that has `initialize="visibility:false"`
Either remove the checkbox from the form or unhide it in the form definition

**Comment by maxxxxxdlp** [comment]
Also, the checkbox has `default="true"`, which is why it is checked by default
