### ISSUE TITLE
[a11y] Clearing the cache repeats indefinitely

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1309]
**Describe the bug**
When using the cache buster, it will continually clear your cache.

**To Reproduce**
1. Go to Clear Cache
2. Clear cache
3. Clear cache
4. Clear cache
5. Clear cache

**Expected behavior**
The reload button should redirect you to the base URL when it reloads.

**Desktop (please complete the following information):**
 - OS: macOS, Edge

**Comment by maxxxxxdlp** [comment]
Fixed in 093767dd
