### ISSUE TITLE
[a11y] Users can map multiple fields to the same location

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1312]
**Describe the bug**
Users can assign multiple columns to the same field.

**To Reproduce**
1. Select two fields
2. See that map still allows them to be assigned the same field.

**Screenshots**
![image](https://user-images.githubusercontent.com/37256050/164740352-39c9c611-1bed-45df-b757-069d297c4926.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, Edge

**Comment by grantfitzsimmons** [comment]
Click on an already mapped field, then select an unassigned field, then click map.

**Comment by maxxxxxdlp** [comment]
Cheater!

Fixed bf68674
Good luck breaking it now 😃

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp Thank you for your good luck!

![image](https://user-images.githubusercontent.com/37256050/166015121-3a839946-19bd-4d46-850f-dbc58afcccbd.png)

I can assign as many fields as I want to this
