### ISSUE TITLE
[a11y] All full date pickers are cut off

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1314]
**Screenshots**
![image](https://user-images.githubusercontent.com/37256050/164746180-93c1e8be-1bc0-4cd7-878b-82f82cdafc3b.png)

How it should look:
![image](https://user-images.githubusercontent.com/37256050/164746121-4c77e4e0-2212-41d4-aaba-331394973a29.png)

macOS, Edge

**Comment by maxxxxxdlp** [comment]
Fixed in [6ab8f48](https://github.com/specify/specify7/commit/6ab8f481a9e3eb16e452bd054af084ae1fa6b051)
