### ISSUE TITLE
[a11y] Can't export query results to CSV

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1316]
**Describe the bug**
Exporting to CSV is not working.

**To Reproduce**
1. Build a query
2. Attempt to export to CSV
3. Try to download from the notification once it has completed.

After exporting, the URL goes to a page not found.

https://a11y-2.test.specifysystems.org/specify/static/depository/query_results_2022-04-22T16:53:01.422517.csv

macOS, Edge

**Comment by maxxxxxdlp** [comment]
Fixed in [887fad3](https://github.com/specify/specify7/commit/887fad35275763fd42875a870b81c0a88b5d5141)
