### ISSUE TITLE
[a11y] QCBX doesn't allow you to select option

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1317]
**Describe the bug**
In some QCBX instances, I cannot select the options with a mouse or keyboard.

**To Reproduce**
1. Go to a new accession
2. Go to Accession Authorizations
3. Try to select a permit

**Screenshots**
![msedge_5g2ZwLjHgn](https://user-images.githubusercontent.com/37256050/164763426-aa9c866a-d747-4ca9-8450-77a36443fd9e.gif)

Windows 10, Edge

**Comment by maxxxxxdlp** [comment]
Duplicate of https://github.com/specify/specify7/issues/1317
