### ISSUE TITLE
Repository Agreement business rule trickiness

### ISSUE THREAD

**Issue by timo11** [specify/specify7#133]
Specify6 has no uniqueness constraint defined for accessionagent relative to repositoryagreement.
But it does enforce repositoryagreement, agentid, role uniqueness in the front end.
Specify7 also enforces that constraint in its front end business rules. 
Since that constraint is not 'built-in' to the db schema, Sp7 probably ought to have a backend businessrule for it, but its backend bus rule system doesn't current allow multiple field unique constraints, i.e. it doesn't support role AND agent being unique in repoagreement.

**Comment by realVinayak** [comment]
Should be resolved in [Uniqueness Rule handling](https://github.com/specify/specify7/pull/3839)
