### ISSUE TITLE
Add preferences menu to forms

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1330]
For controlling things like:
- Carry forward (#1793)
- Autonumbering (#1794)
- Whether default or custom form is used
- A button to see the history of changes for a record (#1703)
- For Collection Objects, a button to copy a link to current record (where the link is in the `/specify/bycatnum/<collectionCode>/<catNum>/` format, rather than by ID)
- For tree records, add a button to see associated collection objects: (#1728)
- For SubViews, add an option to change the sort order
- For SubViews, add an option to toggle between grid and form view (#1723)
- For pick lists, a way to see which fields the pick list is used by
- A button to go to form definition
- A switch to temporary disable field labels (#1581)
- "Generate Label on Save" checkbox (it doesn't really belong on the form, since it does not edit the record, and is not specific to a given record)
- A button to create a label/report from the record (https://github.com/specify/specify7/issues/1996)

**Comment by maxxxxxdlp** [comment]
The link to form definition currently assumes that the view definition is coming from collection's view set.

The `/context/view.json?name=Taxon` endpoint provides correct view set location. Front-end needs to listen to it

**Comment by grantfitzsimmons** [comment]
Looks good to me. This is very broad, so issues that occur from this change should be addressed independently in my opinion. Please reopen if there is more to this that needs discussion.
