### ISSUE TITLE
Attachments for all Interactions

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1333]
It would be great if all the different interactions tables supported Attachments.

It seems that at least Exchange Out is currently be missing this function.

In terms of use cases for this - in general interactions will have a paper trial associated with them - regardless of type (as they generally involve interacting with external organisations), and it would be great to be able to consistently store all of these trails in Specify.

**Requested By:** Ben Ritchie, RBGE

**Comment by benritchie** [comment]
any update on ETA for fixing this, it seems a pretty bizarre omission that some, but not all interactions support this function?
is there any workaround possible?

**Comment by benanhalt** [comment]
Will add attachments for exchange out and exchange in.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-6-8-02-and-schema-2-10-release-notes/830/1

**Comment by benritchie** [comment]
This is not resolved - see https://github.com/specify/specify7/issues/2525 - although the new function was present in 7.8, it was Dead on Arrival.  
is there an ETA for a fix?
thanks
