### ISSUE TITLE
Allow admins to edit user prefs of other users

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1336]

**Comment by grantfitzsimmons** [comment]
How do I test this? I can't see an option to do this, but I might be missing it. This could be alternatively solved by https://github.com/specify/specify7/issues/2223.

**Comment by maxxxxxdlp** [comment]
Each user that edited their User`Prefs would have a `UserPreferences` App resource associated with them (one for each user in each collection)

If they don't already have one, you can create it
