### ISSUE TITLE
[a11y] Saving a user after granting permissions does nothing

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1339]
**Describe the bug**
Saving a user after choosing permissions gives a "Page Not Found" and does not save changes.

**To Reproduce**
1. Create a new user role
2. Give permissions
3. Try to save
4. See not found

**Screenshots**
Before saving:
![image](https://user-images.githubusercontent.com/37256050/165419185-6a1ba44b-ad3c-4dcf-bcd5-2bc9c56e0fb5.png)

After saving:
![image](https://user-images.githubusercontent.com/37256050/165419139-3868f084-88a8-41f7-b743-0d7d1ba6c2a8.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Edge

**Comment by maxxxxxdlp** [comment]
Seems fixed now
