### ISSUE TITLE
Adding same loan prep twice duplicates

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#134]
If you have a CO with count = 10, and you add a quantity of 5 of that CO to loan prep in a loan, adding the same CO with quantity 5 again doesn't combine the count to 10. Instead it makes two separate loan preps each with quantity 5 and count 10. The expected action here is that Specify will recognize that 5 of the count is already in the loan prep table (opening the "add" loan prep window would display 5 of the CO as unavailable), and adding the other 5 doesn't create a new loan prep, but adds to the first.

Because these loan preps aren't recognized as being the same CO, you can have an overall quantity between the two that exceeds the total count of the CO in the Database (ex: you can have two loan preps of the same CO, each with quantity = 10, totaling a quantity of 20, even though the count in the database is only 10). The expected action here is that after adding all 10 of the CO, opening the "add" loan prep window will show that CO as having a count of 10, all of which are unavailable.

Saving does not change anything, thus allowing duplicates of the same CO in loan preps.

**Comment by garrettgirard** [comment]
This is also a problem in Specify 6, although it acts slightly different. If you add the same Cat# to the loan preps, a new loan prep isn't added and the quantity increases under the same CO. However, it's count remains the same. So if you add a duplicate of a CO that only has a count of 1, you can have a loan prep with quantity = 2 and count = 1.

NOTE: For both Specify 6 and Specify 7, this is only an issue before saving. Once you save, the loans see that the CO is unavailable, and you can't add it again.

**Comment by timo11** [comment]
There is really not a problem in Sp7, the count indicates the number of specimens in a prep. As long as you can't loan more than the prep's count it's not a big deal. Also, it's remotely possible - about as remote as somebody unintentionally adding the same prep - that more items from a prep would be added with notes - 'these two can be dissected' or something - or maybe they might be added later after the the loan was originally shipped.

**Comment by timo11** [comment]
Ah, Disregard last comment. You CAN loan more specs than are available if you click 'add' loan preps, then, without saving, click 'add' again. The quantities for the unsaved loan preps won't be accounted for the second time.

**Comment by benanhalt** [comment]
From meeting: It seems like there are real use cases that this would support.
