### ISSUE TITLE
[a11y] Page scrollbar appears and disappears when scrolling form

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1342]
**Describe the bug**
Scroll on a form and you will see.

**Screenshots**
![msedge_9cyfXLkapy](https://user-images.githubusercontent.com/37256050/165788428-c376d81e-494a-43bf-bafc-5d64fb797bc3.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10, Edge

**Comment by maxxxxxdlp** [comment]
Unable to replicate
Windows 10, Edge

Does it happen for you in other browsers? Chrome?

**Comment by maxxxxxdlp** [comment]
For future reference:
This also happens in Edge 101.0.1210.32 on macOS
Unable to replicate consistently

Possibly caused by autocomplete boxes

**Comment by grantfitzsimmons** [comment]
Happens pretty consistenly with `nm3` CO form

**Comment by grantfitzsimmons** [comment]
Can recreate 100% of the time in a record set on Windows 10, Edge `nm3`

**Comment by maxxxxxdlp** [comment]
I haven't heard about this in a while. Does it still happen, or did microsoft finally fix this on their end?

**Comment by emenslin** [comment]
Fixed
