### ISSUE TITLE
[a11y] Saving WB mapping unfinished breaks WB

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1344]
**Describe the bug**
After saving an unfinished mapping, I received this error:

![image](https://user-images.githubusercontent.com/37256050/165790942-a7a99d4b-caf9-4331-a633-5564af693ab5.png)

Now every time I try to open the WB data set I get the same error.

**To Reproduce**
1. Import a data set
2. Partially map it
3. Save unfinished

**Desktop (please complete the following information):**
 - OS: Windows 10, Edge

**Comment by grantfitzsimmons** [comment]
Importing a new copy of the same data set, used the previous mapping as the base.

![image](https://user-images.githubusercontent.com/37256050/165794578-95247061-1435-468a-9cbd-3842c9616b45.png)

Received this error after saving

**Comment by maxxxxxdlp** [comment]
![Screen Shot 2022-04-28 at 16 58 58](https://user-images.githubusercontent.com/40512816/165854772-92eab792-5118-4b4c-994c-ced5c4231fbd.png)
I believe this isn't about unfinished mapping but about this particular mapping.
Do you still have the data set you used for this? Can you send me screenshots of the mapping?

**Comment by maxxxxxdlp** [comment]
Likely same cause as #1362
Closing the duplicate
