### ISSUE TITLE
[a11y] App Resources sidebar has a width:100%

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1346]
**Describe the bug**
huge sidebar 

**To Reproduce**
1. Go to App Resources
2. See _huge_ sidebar!

w-full class is applied to the sidebar, making it giant.

**Screenshots**
![image](https://user-images.githubusercontent.com/37256050/165799899-f0d706cd-bdce-4bf7-ae30-a2cde4e2f64b.png)

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/165802000-0cab7cb3-2270-42bb-bf61-efd5c53dcfd6.png)

**Comment by maxxxxxdlp** [comment]
Fixed in 765ada9f
