### ISSUE TITLE
[a11y] Tree node creation is bugged out

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1347]
**Describe the bug**
When attempting to create a tree node, there are a few complicated issues happening.

**To Reproduce**
1. Create a new Geography entry
2. See errors

---

## Edge

No problem when using most QCBXes, but on the geography form on Edge, it still occurs.

![image](https://user-images.githubusercontent.com/37256050/165803516-ea205acd-bc97-4804-9779-1d839ea51f45.png)

![image](https://user-images.githubusercontent.com/37256050/165803719-3d72fa3d-af63-4963-9657-0ae693d0b67e.png)

Both fields acts as if they are empty when is populated.

---

## Safari 

On Safari, I cannot even use the keyboard to select an item.

![image](https://user-images.githubusercontent.com/37256050/165803587-70179967-c1ae-46f7-be38-c6699ddf6d49.png)

When I select an item with my mouse, I get this:

Still no ability to select Geographic rank:

![image](https://user-images.githubusercontent.com/37256050/165803635-66e37ba5-ba20-4889-8f9e-0a916a71fb40.png)

**Desktop (please complete the following information):**
 - OS: macOS, Edge & Safari

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/168139579-0c5d033d-eec9-4dd5-b07a-e1e3bbd4e16d.png)

The Name field still highlights as invalid until you add the Parent of Node. Once that is complete, it works great!

**Comment by maxxxxxdlp** [comment]
Wow. Congrats, you just found a quite critical bug.
Should be fixed now
