### ISSUE TITLE
[a11y] Queries not using saved dates

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1348]
## a11y

![image](https://user-images.githubusercontent.com/37256050/165806054-4774bdd6-531a-4a0c-836c-5be771dd1be8.png)

## Edge

![image](https://user-images.githubusercontent.com/37256050/165805913-62b07e53-88c8-4356-ba03-4521627dd5c3.png)

**Comment by maxxxxxdlp** [comment]
Turns out dates in query fields are stored as `MM/DD/YYYY` in sp6, but `MM-DD-YYYY` in sp7.
`edge` was able to handle both, so I made `a11y` handle both too (in 622c8875).
@grantfitzsimmons it would be good to test if query with a date filter created in sp7 opens properly in sp6
