### ISSUE TITLE
[a11y] Some picklists do not indicate visually it is a picklist

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1350]
**Describe the bug**
Some picklists do not indicate visually it is a picklist

**To Reproduce**
1. Go to a CO form in `freshfish`
2. See **Sex** under CoA
3. See no indication it is a picklist

**Expected behavior**
![image](https://user-images.githubusercontent.com/37256050/165807053-f40c53a3-3af5-4c0c-9763-17c2826e7600.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/37256050/165807008-4b1678cd-6d5b-4e4b-a0b2-5ad16f5886e5.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Edge

**Comment by maxxxxxdlp** [comment]
Read-only pick lists have a down arrow, but non-read-only pick lists don't.
@acbentley suggested that all picklists should have a down arrow.
This would be a bit challenging since read-only and non-read-only pick lists are rendered using different components

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/167188708-209e73be-020f-40e6-bb38-5c0a2311ac74.png)

![image](https://user-images.githubusercontent.com/37256050/167188739-885b66bd-3f61-4e3d-8e3b-6110079ecb23.png)

Very important! 😀

**Comment by grantfitzsimmons** [comment]
While not ideal, even that dropdown box to the right would be better than no distinction I'd say
![image](https://user-images.githubusercontent.com/37256050/167489721-cff22836-7342-44e0-a029-7616e12fa593.png)

**Comment by acbentley** [comment]
Agreed.  It is important to have designation that a field is a picklist.

Andy

     A  :                A  :               A  :
 }<(((_°>.,.,.,.}<(((_°>.,.,.,.}<)))_°>
     V                   V                  V
Andy Bentley
Ichthyology Collection Manager
University of Kansas
Biodiversity Institute
Dyche Hall
1345 Jayhawk Boulevard
Lawrence, KS, 66045-7561
USA

Tel: (785) 864-3863
Fax: (785) 864-5335
Email: ***@***.******@***.***>
http://ichthyology.biodiversity.ku.edu<http://ichthyology.biodiversity.ku.edu/>

     A  :                A  :                A  :
 }<(((_°>.,.,.,.}<(((_°>.,.,.,.}<)))_°>
     V                   V                   V

**Comment by maxxxxxdlp** [comment]
This turned out to be much easier to fix than I expected
@grantfitzsimmons it would be great if you could test non-readOnly pick lists in all browsers to make sure the arrow displays correctly.
Similarly, some browsers draw an "x" button to clear the input. Need to test that "x" and the arrow button do not overlap.

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp Here you go:
macOS, **Safari** -> No X overlap, works great
Windows 10, macOS, **Edge** -> No X overlap, works great
Windows 10, macOS, **Chrome** -> No X overlap, works great
Windows 10, **Firefox** -> No X appears at all
![image](https://user-images.githubusercontent.com/37256050/167899452-589d9fa2-6d80-4aca-9b33-4a360f78e356.png)
