### ISSUE TITLE
Security panel left hand panel too large

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1351]
**Describe the bug**
The left-hand panel of the security panel window is too large

**To Reproduce**
1. Go to the Security panel
2. Click on Institution or collection
3. See error

**Expected behavior**
I would expect that left-hand window to only be as wide as the longest string of text so that the right-hand panel could take up as much space as possible

**Screenshots**
![Security panel](https://user-images.githubusercontent.com/7501989/165811065-58399870-7a4b-41e7-97d0-3e32b567fc4d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Fixed in 765ada9
