### ISSUE TITLE
Autonumbering overflow after a typo

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#1352]
Freshfish database.
Catalog number formatter is `\d{9}`
After creating a CO with catalog number `999999999`, subsequent CO objects that use autonumbering cause this warning in the console:

```yml
[WARNING] [specifyweb.specify.api:381] autonumbering overflow: created value: 1000000000 longer than limit: 9 current max: 999999999
```

Additionally, the back-end endpoint responds by sending back the content of body request, thus creating new CO fails, as back-end returns a record with `{id:null}`

**Comment by emenslin** [comment]
Probably related to #3964

**Comment by melton-jason** [comment]
Also related to #4362

**Comment by emenslin** [comment]
Closing in favor of #4362
