### ISSUE TITLE
[a11y] Collapsed tree headers are wide

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1357]
![image](https://user-images.githubusercontent.com/37256050/165962876-c4383d98-3102-442f-8f59-63e70c8cd34d.png)

Either the ability to collapse tree ranks should be removed or the space between ranks should be much smaller

Something like this:
![image](https://user-images.githubusercontent.com/37256050/165963052-06e3804f-ca85-45b6-a1b8-b7a969c0e42a.png)

Since there is a horizontal scroll bar, it does not seem necessary.

**Comment by maxxxxxdlp** [comment]
Since there aren't many ranks in your tree, they stretch to occupy the full width of the screen.
For a tree with lots of ranks, like Taxon, collapsed ranks would occupy less space.
