### ISSUE TITLE
[a11y] Prep type not appearing

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1358]
![image](https://user-images.githubusercontent.com/37256050/165965936-728b4765-8e44-4eef-91b3-774d9f5e583f.png)

freshfish, andy's main CO form under Preparations.

![Screen Shot 2022-04-29 at 9 34 23 AM](https://user-images.githubusercontent.com/37256050/165965990-6eca2a15-a84a-4ba7-b16b-856177986325.png)

![image](https://user-images.githubusercontent.com/37256050/165966006-43aac02f-1c2b-4f89-8f60-4c99486ec52c.png)

Fish Tissue Collection

macOS, Edge

**Comment by maxxxxxdlp** [comment]
Not sure what was going on there, but it works alright now:

<img width="1800" alt="Screen Shot 2022-04-29 at 14 25 43" src="https://user-images.githubusercontent.com/40512816/166055487-748614ee-048e-4cd4-a604-16ab5da1ff7e.png">

**Comment by grantfitzsimmons** [comment]
Not sure either... it is fixed on my end as well
