### ISSUE TITLE
Deleting tree nodes causes error

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#136]
Attempting to delete a parent node that has children causes an error, regardless of whether it or any of its children are associated with a record. Deleting the lowest level children nodes only gives same error when there is an associated collection object (so deleting parent nodes without associated records is only possible by going through and deleting each child node from the lowest level up).

When a parent node and it's children don't have any records associated with them, you should be able to delete them.
When a parent node or it's children do have records associated with them, some message should pop up telling you that you can't delete them because they reference a collection object, or the delete button should be grayed out or something.

Deleting any of the nodes mentioned above causes this same error message (with different numbers depending on where it is in the taxon tree):
ProtectedError at /api/specify/taxon/11175/
("Cannot delete some instances of model 'Taxon' because they are referenced through a protected foreign key: 'Determination.preferredtaxon'", [<Determination: Determination object>, <Determination: Determination object>, <Determination: Determination object>, <Determination: Determination object>, <Determination: Determination object>, <Determination: Determination object>])

**Comment by garrettgirard** [comment]
You actually can get the same error from deleting children nodes without associated records. This only seems to happen when the child node has a sibling node that has associated records and doesn't have any children nodes of its own. If the sibling does have children, any of its siblings without associated records can be deleted.

**Comment by benanhalt** [comment]
I changed the business rules to not allow any tree node to be deleted if it has children or if it is referenced by other records. This makes deleting subtrees difficult, but in a future release structural tree editing will be added, and I think it makes more sense to integrate subtree deletes through that mechanism.
