### ISSUE TITLE
[a11y] Windows are following, not moving with the cursor

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1361]
**Describe the bug**
Moving a dialog on all browsers feels like the cursor is being chased rather than dragging the window.

**To Reproduce**
1. Open a dialog
2. Move it
3. See behavior

**Screenshots**
![moving_a11y](https://user-images.githubusercontent.com/37256050/165976183-7a1912f6-407d-4d64-bcc0-4267d7c05bc6.gif)

On edge they are stuck to the cursor.

**Desktop (please complete the following information):**
 - OS: macOS, Safari, Edge - Windows 10, Edge, Chrome

**Comment by maxxxxxdlp** [comment]
Unable to replicate in different browsers.
Does this still happen for you?
It might be happening if your computer is overloaded

**Comment by grantfitzsimmons** [comment]
This happens on both Windows & Mac even if it's not being overloaded for me

**Comment by maxxxxxdlp** [comment]
Ahh I see what's going on.
Specify says that all transitions should last `100ms`.
Moving dialog window is considered at transition.
In my system settings I said that I don't like animations, and so Specify set transition duration to `0ms`, thus making this bug not occur on my machine.

That's an easy fix - dialog dragging should not have transitions.

**Comment by grantfitzsimmons** [comment]
![wind](https://user-images.githubusercontent.com/37256050/167496376-c1e04ca3-11f8-4a4e-b0f0-8961c5b9f41e.gif)

Slow behavior today on Edge, Windows 10

**Comment by maxxxxxdlp** [comment]
Weird. It shouldn't happen anymore.
Does it still happen if you disable animations in user preferences?
Does it happen in other browsers?
