### ISSUE TITLE
[a11y] Data set mapping breaks WB

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1362]
**Describe the bug**
I created a WB data set that breaks the workbench. `freshfish` db, abentley.

[New Data Set Fri Apr 29 2022](https://a11y.test.specifysystems.org/specify/workbench/36/)
`/specify/workbench/36/`

![image](https://user-images.githubusercontent.com/37256050/165977452-b3ca56db-5761-4fd5-aeb2-b59c757a7082.png)

[**Full error log**](https://drive.google.com/open?id=1R20UUyS5pm9StyQRbfcCyFK85VsoBt_y&authuser=grant%40specifysoftware.org&usp=drive_fs)

**To Reproduce**
1. Go to my data set
2. See error

I created a mapping for an empty data set and saved it. Now it is broken.

**Desktop (please complete the following information):**
 - macOS, Safari

**Comment by maxxxxxdlp** [comment]
Fixed in a1aae66c
