### ISSUE TITLE
Add ability to export/import data set mappings

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1363]
This would be very helpful to have access to in the edit menu for the WB data sets.

**Comment by maxxxxxdlp** [comment]
From @grantfitzsimmons:

> https://discourse.specifysoftware.org/t/export-data-set-mapping/809
>
> https://github.com/specify/specify7/assets/37256050/92c86190-27ea-4a81-b33d-9267d7e53f70
> 
> The simplest solution is literally unhiding the `[DEV] Show Plan` button in the UI (removing DEV, of course).
> 
> I would like there to be a button to see the mapping, and it should include an **export** and an **import** button so that the plan can be shared between multiple users or modified manually outside of the WorkBench.

**Comment by maxxxxxdlp** [comment]
From @grantfitzsimmons (in 2024):
> ... (same issue again 😊)

**Comment by grantfitzsimmons** [comment]
I will open a 5th duplicate if nobody solves this
