### ISSUE TITLE
[a11y] A downward arrow is present in the Schema Config

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1371]
**Describe the bug**
<img width="921" alt="image" src="https://user-images.githubusercontent.com/37256050/166261246-2eef2b49-24ec-410e-b247-43816acf1507.png">

It does nothing

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari

**Comment by grantfitzsimmons** [comment]
I think it is being considered a pick list. When selecting an item and double clicking on the "Fields" label, this occurs:

```
TypeError: undefined is not an object (evaluating 'n[r].pickListName')

D@https://a11y-2.test.specifysystems.org/static/js/80.427d13fbf7b02bc214f3.bundle.js:2:54016
@https://a11y-2.test.specifysystems.org/static/js/80.427d13fbf7b02bc214f3.bundle.js:2:57473
c@https://a11y-2.test.specifysystems.org/static/js/main.12136f3e07cfafe3a786.bundle.js:2:92952
k@https://a11y-2.test.specifysystems.org/static/js/main.12136f3e07cfafe3a786.bundle.js:2:29762
b@https://a11y-2.test.specifysystems.org/static/js/main.12136f3e07cfafe3a786.bundle.js:2:26711
```

**Comment by maxxxxxdlp** [comment]
Removed arrow in 3b77ee48

The exception message is caused by a Safari weirdness.
I tested these browsers: Chomre Windows, Edge Windows, Chrome macOS, Edge macOS, Safari macOS, and Safari is the only one where this happens!
