### ISSUE TITLE
Shadow on navigation bar is not consistent

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1372]
![image](https://user-images.githubusercontent.com/37256050/166261539-91f507f2-93da-4597-8590-355df0bd0968.png)

macOS, Safari

**Comment by maxxxxxdlp** [comment]
Likely still happens, despite the menu refactor.
Could be browser dependent

**Comment by grantfitzsimmons** [comment]
![image](https://github.com/specify/specify7/assets/37256050/2d1580db-0733-4779-8a54-cb64e3f51228)

still a thing :wink:

**Comment by emenslin** [comment]
Fixed
