### ISSUE TITLE
[a11y] Workbench mapper shows different labels than the schema config

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1373]
**Describe the bug**
The WB mapper shows different labels than the schema config does.

![image](https://user-images.githubusercontent.com/37256050/166267853-a2434dad-e207-4766-a5f5-08908b8a194f.png)

text5 is shown as "UTM Zone" here

It should be LatLongSource:

![image](https://user-images.githubusercontent.com/37256050/166267925-ec1ff6f1-a93b-45fa-a7d2-c0e78bf6a1ad.png)

**Desktop (please complete the following information):**
 - OS: macOS, Safari

**Comment by maxxxxxdlp** [comment]
This may be fixed now
