### ISSUE TITLE
[a11y] Error in WB: Field is a relationship

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1378]
**Describe the bug**
Opening the FMNH_Exchange data set in the WB causes an error in the `freshfish` db

**Expected behavior**
FMNH_Exchange should not error

**Screenshots**
<img width="1512" alt="Screen Shot 2022-05-03 at 9 54 44 AM" src="https://user-images.githubusercontent.com/37256050/166499574-79ec30b5-91f4-4652-9e1a-651dff3446c1.png">

macOS, Safari

**Comment by maxxxxxdlp** [comment]
The mapping is invalid (you mapped a column to a relationship)
WorkBench had a bug that allowed such mapping
The bug has been fixed.
See https://github.com/specify/specify7/issues/1362
The mapping for this data set was created before that bug was fixed
