### ISSUE TITLE
[a11y] Agents in a record set display their ID

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1384]
![image](https://user-images.githubusercontent.com/37256050/166505059-b7b7c09e-a9a2-4474-9f42-c1d3aab54f0c.png)

`nm3` database
spadmin username

macOs, Edge

**Comment by maxxxxxdlp** [comment]
The screenshot is wrong.
Although, this seems to be fixed now

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp oddly I was able to recreate this issue this morning on the nm3 database after doing a new import. Currently there are no records on the db anymore but it occurred when the Agent record had no first, last, or middle name, just an abbreviation. On `edge` it showed nothing

**Comment by maxxxxxdlp** [comment]
Ah now it makes sense.
It was showing the URL because there wasn't anything else it could show for that record.
I changed now to display table name and id instead (like `Agent #332`)
