### ISSUE TITLE
Unable to change field read-only and required status in schema config

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1389]
**Describe the bug**
I am unable to deselect read-only for any field in the Schema Config

**To Reproduce**
1. Go to schema config
2. Click on a base table
3. Select a field
4. Try changing read-only or required status

**Expected behavior**
I would expect to be able to select and deselect this status for any field.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Fixed "isRequired" checkbox not workgin.
As far as readOnly, I don't think there is an option to change that in schema config in sp6 either, correct?
As far as I am aware, field can only be made readOnly in the form definition, unless it is already made read only by the data model

**Comment by maxxxxxdlp** [comment]
The checkbox is not checked, it is just disabled. Here is how a checked disabled checkbox looks like:

![Screen Shot 2022-05-04 at 12 48 18](https://user-images.githubusercontent.com/40512816/166748464-41d63277-89db-463f-8df0-5a99af95c081.png)

And disabled unchecked:
![Screen Shot 2022-05-04 at 12 48 19](https://user-images.githubusercontent.com/40512816/166748460-f6bb421b-470c-4d4f-a4a8-032102ac30e7.png)

Most fields are not readOnly. Some examples of readOnly fields:
timestampCreated, Preparation.isOnLoan, Taxon.isAccepted, Taxon.acceptedTaxon, Loan.totalPreps

**Comment by tlammer** [comment]
the presence is incredibly confusing.  I would take the option out.  I was about to create the same error.  If it is there, it makes it seem like it is something that can be edited there.  At the very least the words should be greyed out as well not just the checkbox, but I'd vote for just taking it out

**Comment by maxxxxxdlp** [comment]
Done.
You can still check if a field is read-only from the data model viewer
