### ISSUE TITLE
[a11y] WB Mapper menus not expanding

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1391]
![image](https://user-images.githubusercontent.com/37256050/166930293-a916b019-5866-4c5a-b8f2-27ab765187c7.png)

Selecting a table in the WB menu that appears when selecting a field requiring a mapping results in no second menu appearing. This occurs every time a relationship table is selected.

macOS, Edge

**Comment by maxxxxxdlp** [comment]
Unable to replace.

https://user-images.githubusercontent.com/40512816/166950601-91035624-395d-4fda-8cc9-66911f30e7f8.mov

Make sure data set is not uploaded. If data set is uploaded, you can't edit the mapping
