### ISSUE TITLE
[a11y] Record Set not saved after pressing Enter with a name present

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1394]
After creating a record set from a query and entering a name in the Name field, press Enter.

It does not save & believes there is no value in the text box.

![image](https://user-images.githubusercontent.com/37256050/166952514-7385fe84-8253-43f3-8ffa-6cb99b5e1ed4.png)

It works once Save is clicked

**Comment by maxxxxxdlp** [comment]
Probably caused by https://github.com/specify/specify7/issues/1392
