### ISSUE TITLE
WB Grid Editor doesn't display generated table icons

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1396]
**Describe the bug**
Locality Details (and other tables with generated icons) shows a question mark in the WB grid editor.

**Screenshots**
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/37256050/166956548-cc8bb01b-25bc-4b66-a0c8-01de9f2abbc2.png">

**Desktop (please complete the following information):**
 - macOS, Edge

**Comment by maxxxxxdlp** [comment]
Fixing #2864 would fix this, so I would close this as duplicate
