### ISSUE TITLE
View sets are exported as TXT

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1397]
View sets should be exported as XML

**Comment by maxxxxxdlp** [comment]
Fixed in 97b258751

**Comment by grantfitzsimmons** [comment]
App resources should be exported as the type of file they are (mime type?)

Currently downloading a report or label downloads it as an XML file rather than JRXML.

**Comment by chanulee1** [comment]
Reports and labels downloaded as XML instead of JRXML.
Link: https://freshfish-testability.test.specifysystems.org/specify/resources/app-resource/167/
db: `freshfish`
browser: Chrome
os: Windows 10

**Comment by chanulee1** [comment]
Type of file an app resource is exported as is determined by mime type.
db: `freshfish`
