### ISSUE TITLE
Tree parent field querycbx should only offer legal choices.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#140]
The query should filter out nodes that are descendents of the current node and not wait for the business rule to detect the bad structure.

See #91.

**Comment by benanhalt** [comment]
Also #141. Filter out bottom ranks that cannot have children.

**Comment by timo11** [comment]
see #377 and #378

**Comment by yvonneekanim** [comment]
Tested in a test database; specify filters out invalid choices for rank .
