### ISSUE TITLE
Can add county as parent in geography form

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#141]
When creating a new geography, you can add a County as a parent. If you select that County, you will notice that the Geography Rank picklist is empty, and has no available options. This is because there can't be a geography with a rank lower than County. Saving from here causes an error.

Here is the error message:
BusinessRuleException at /api/specify/geography/
Tree object has parent with rank not greater than itself.

This doesn't appear to be an issue for taxon, however it is present in chronostratigraphy and possibly lithostratigraphy (although the lithostratigraphy one may be a different bug, which I'll test later)

**Comment by garrettgirard** [comment]
You may run into the same issue by going into the tree and right-clicking a county, then selecting "Add child". From there, doing the same action from above causes the error.

**Comment by maxxxxxdlp** [comment]
Fixed in #701
