### ISSUE TITLE
[a11y] Collection Object Relationships not appearing

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1412]
![image](https://user-images.githubusercontent.com/37256050/167188265-a69af4d2-513a-4296-9b34-2885fff6a5fa.png)

![image](https://user-images.githubusercontent.com/37256050/167188224-6fed612f-2f32-454f-a8d9-da9eb99da001.png)

`saiab` database, CO form

**Comment by maxxxxxdlp** [comment]
Do you still have the URL for this record?
