### ISSUE TITLE
Support shift+click to select multiple checkboxes

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1414]
https://cross-browser.com/x/examples/clickndrag_checkboxes.php

![image](https://user-images.githubusercontent.com/37256050/167196987-60079ad5-ec3c-46cf-8930-cdacf2c23c62.png)

Useful when creating a record set from a group of items in query results

**Comment by maxxxxxdlp** [comment]
The implementation in the demo is quite buggy: if you drag quickly, not all checkboxes get selected.

Perhaps a better solution (and the one I saw implemented in other places) is to allow clicking on one checkbox, then shift+clickign on the other one, which would select all checkboxes in between the two.

S7 already does this in the query results. It is also implemented in Gmail, Google Drive, Google Photos and many other Google services


Some other solutions: https://www.raymond.cc/blog/checkfox-check-uncheck-all-checkboxes-firefox/

**Comment by grantfitzsimmons** [comment]
I think the shift+click option between selection makes more sense. This is definitely a better way to handle this relationship. @maxxxxxdlp Do you want to rename this issue?

**Comment by maxxxxxdlp** [comment]
Are there any other places where this behavior should be selected?

Query Results and Express Search results already support this
Prep Return Dialog is the only one I can think of

**Comment by grantfitzsimmons** [comment]
Those are the only places that come to mind for me as well. Could this be available anywhere checkboxes may appear?

**Comment by maxxxxxdlp** [comment]
Probably no, as there can be unforeseen consequences for this.

For example, doing this shift+click on a form would select all checkboxes in between horizontally, not vertically

**Comment by CarolineDenis** [comment]
@grantfitzsimmons does this need to be kept open?

**Comment by grantfitzsimmons** [comment]
No, this has been implemented
