### ISSUE TITLE
[a11y] Running a report gives a blank page

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1416]
![image](https://user-images.githubusercontent.com/37256050/167201755-2c49256f-299e-44d5-8c3d-167f87c93ec9.png)

**To Reproduce**
1. Go to `saiab`
2. Run a report
3. See blank screen

**Desktop (please complete the following information):**
 - macOS, Edge

**Comment by maxxxxxdlp** [comment]
Please test this again on the server after it updates with the commits I have just pushed

**Comment by grantfitzsimmons** [comment]
This is still the case across several databases
![image](https://user-images.githubusercontent.com/37256050/167435064-75512a2d-284a-455a-b551-0c966d574122.png)
