### ISSUE TITLE
Required fields in a query should default to Any if empty

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1419]
Required fields in a query should default to Any if empty to prevent an error message when trying to run a query with a blank value

**Comment by grantfitzsimmons** [comment]
Required fields in the schema or fields that use the "Contain" operator still require a manual switch to "Any" before the query can be run.

Ben suggests removing field validation before running a query entirely.

**Comment by maxxxxxdlp** [comment]
Closing this in favor of #1826
