### ISSUE TITLE
[a11y] Selecting an agent from the dropdown does not register as a valid value

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1422]
**Describe the bug**
After selecting an Agent using the dropdown suggestions, the form does not accept the value.

**To Reproduce**
1. Go to **Exchange In**
2. Start typing an agent name
3. Select it

![image](https://user-images.githubusercontent.com/37256050/167204658-581bbb0c-4a0d-43eb-901c-86cf31c80833.png)

macOS, Edge

**Comment by grantfitzsimmons** [comment]
`saiab`,`collection` is the user

**Comment by maxxxxxdlp** [comment]
Should be fixed by dc492370
Needs testing
