### ISSUE TITLE
[a11y] Scroll bars appear if preparations subview overflows

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1425]
![msedge_g9sSHtDsMr](https://user-images.githubusercontent.com/37256050/167210617-2626d851-3754-41ca-bccf-e78dd329bab5.gif)

If you scroll the Preparations subview (while collapsed) all the way to the right, the unnecessary scrollbars disappear

`saiab`, collection is the username

**Comment by maxxxxxdlp** [comment]
Duplicate of [1342](https://github.com/specify/specify7/issues/1342)
