### ISSUE TITLE
[a11y] Discrepancy in new cell count

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1428]
**Describe the bug**
![image (18)](https://user-images.githubusercontent.com/37256050/167215381-b2527f20-f6ab-4982-b331-54d64251c5ef.png)

`unitec` db, pbellbutler user

**Comment by maxxxxxdlp** [comment]
Fixed in a9c315af

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/167678658-950690c5-ef30-426a-a134-d57df449941f.png)

`/specify/workbench/2/` on `oldfish`
