### ISSUE TITLE
[a11y] Some data entry forms are formatted oddly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1429]
![image](https://user-images.githubusercontent.com/37256050/167215844-8094e0b5-ee3d-4a2e-a596-17ce5faeb4e9.png)

For instance, the Exisccata form for Unitec.

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/167216413-fc0613cd-9589-4c53-8336-17caf53bccb1.png)

Repository Agreement Interaction, Unitec

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/167216565-069f4ce2-ea10-453e-b113-5c75f177acc8.png)

Borrow Interaction, Unitec

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/167660452-6bae991b-ea06-46fd-b0ef-141708df6e6f.png)

So close!

**Comment by grantfitzsimmons** [comment]
![msedge_4LkpilBU4V](https://user-images.githubusercontent.com/37256050/167856755-8481ab14-f31f-493e-aff9-05d2711cfa68.png)

![msedge_hbyqqDN968](https://user-images.githubusercontent.com/37256050/167856794-0d388402-7312-491d-b13d-9988bc3aad18.png)

Still having some issue with those two (Authors, Members)

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/168324387-d85d81bf-df8b-4786-b330-38a2dca0b80e.png)

![image](https://user-images.githubusercontent.com/37256050/168324483-161d093c-4838-4afd-a9f7-3260d14d6d51.png)

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/168853096-61c37a8e-3d8b-4e3b-b648-e8fa1de922e1.png)

This behavior is new I believe

**Comment by maxxxxxdlp** [comment]
That's because we added a limit on maximum field width.
You can disable it in user preferences

**Comment by grantfitzsimmons** [comment]
Shouldn't the form adjust to be as wide as the fields inside of it?

**Comment by maxxxxxdlp** [comment]
If there is only one column and it is an autogenerated form, the form width is now limited so as not to have extra long fields.
Again, you can disable that behavior in preferences

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/168872228-9509476e-6058-4446-8dbb-fe771d8ed3a1.png)

Can the width of this be set in the viewdef? It is displaying in a less viewable way now (Determinations)

**Comment by maxxxxxdlp** [comment]
Fixed. Form tables are no longer stretched more than needed
