### ISSUE TITLE
Add script to automatically manage github issue tags.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#143]
It ought to be possible to create a webhook to trigger a script to automatically add priority and milestone tags to newly created issues, if they are not assigned by the reporter. It could also add the **res:fixed** tag if the commit message is `fixed #XXX`.

**Comment by benanhalt** [comment]
It should probably also automatically move any closed issues to **prerelease** milestone.

**Comment by maxxxxxdlp** [comment]
7 years later, this is implemented natively by GitHub

Closing an issue would move it to the `Deployed` column in all associated columns thanks to the automation we have setup in the projects.
Mentioning `Fixes #xxx` in a pull request description and then merging the pull request would close the associated issue.
However, issues are not yet added to a milestone automatically, and there is no easy way to automate that, as different features are going into different milestones (i.e, 7.7.2 and 7.8 development was happening at the same time)
