### ISSUE TITLE
[a11y] Required tooltip is always on top

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1436]
**Describe the bug**
Required tooltip is automatically on top

**Screenshots**
<img width="853" alt="image" src="https://user-images.githubusercontent.com/37256050/167425766-cec278b9-2be4-4693-98ff-277f3cf0bd0f.png">

macOS, Edge

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/167648258-36066561-0fe9-4a7c-a7bc-42bbc5cf73f8.png)

**Comment by maxxxxxdlp** [comment]
Both issues should be fixed now
