### ISSUE TITLE
[a11y] GEOLocate default window smaller than embeded instance

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1437]
![image](https://user-images.githubusercontent.com/37256050/167429279-f73aa023-e3ed-4d24-bcd7-7507e8f47195.png)

Should look like this:
![image](https://user-images.githubusercontent.com/37256050/167429401-1d827ccf-38ee-46c1-bc30-7c7e6f7d5bd9.png)

macOS, Edge

**Comment by maxxxxxdlp** [comment]
It remembers the dialog size from the last time you opened in. Thus you can resize it to fit your screen.
This is the reason why: https://specifydev.slack.com/archives/CC6V12D3J/p1650306242669909?thread_ts=1650290979.484669&cid=CC6V12D3J

Though It seems like the default size was too small, so I increased it in 4811ea63 so as not to cause scroll bars

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/167680272-a4a8ef46-1ee8-4c16-8f25-b1727ee01b8b.png)

This database has never used GEOLocate on `a11y`, it is `oldfish`. This and GeoMap should probably have their own custom window containers that are inconsistent for functional reasons. (**X** in the top right perhaps?)
