### ISSUE TITLE
[a11y] Page navigator has misaligned numbers

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1440]
![image](https://user-images.githubusercontent.com/37256050/167436562-d5cffd23-0729-4030-a4ef-0f9027323337.png)

![image](https://user-images.githubusercontent.com/37256050/167436635-f3bc9145-269c-46ae-9589-0fd94a08c6ee.png)

Edge, Windows 10

**Comment by cdamyx** [comment]
Hey guys! It looks like this issue may have already been resolved. If not, please let me know what page(s) the misaligned numbers are on and I can take a look.
![image](https://user-images.githubusercontent.com/40224280/211320913-373bfe63-c9da-40ff-81b6-1759ce653a40.png)

**Comment by grantfitzsimmons** [comment]
This has since been solved! We can close this issue :-)
