### ISSUE TITLE
[a11y] Some form items are smaller

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1441]
![image](https://user-images.githubusercontent.com/37256050/167437977-e5426788-c21d-4e7a-b7bf-975fa13b32e4.png)

See the top two fields on the right

`colorado_paleo` db
`topdog_CUpaleo` user
Rock collection

[Current URL](https://a11y-2-2-2-2.test.specifysystems.org/specify/view/locality/1184/)

**Comment by maxxxxxdlp** [comment]
A11y was reading column definitions from a different place (`<coldef>` vs `<coldef os="lnx">`) becaseu.
For most forms, those were the same, but on this form they have a typo in `<coldef>`, which caused that issue)

Should be fixed now
