### ISSUE TITLE
[a11y] WB validation is not working correctly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1444]
![image](https://user-images.githubusercontent.com/37256050/167440859-6887bd6f-7166-43ae-bec3-50cbae6b7639.png)

![image](https://user-images.githubusercontent.com/37256050/167441040-b617e240-f80f-4a3e-9e5b-126f1110db4e.png)

A single issue cell invalidates the entire row, and every cell has the error message of the errored cell

**Comment by maxxxxxdlp** [comment]
What is the URL for this data set?

**Comment by grantfitzsimmons** [comment]
https://user-images.githubusercontent.com/37256050/168154616-d8dd4aae-c5f2-42a5-82f9-4eed5322cb48.mov

It no longer takes up the entire row, but it is acting incorrectly.

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons Not sure what is going on there, but we already have a separate bug open for it and Ben is looking into it:
https://github.com/specify/specify7/issues/1554

**Comment by grantfitzsimmons** [comment]
> @grantfitzsimmons Not sure what is going on there, but we already have a separate bug open for it and Ben is looking into it:
> #1554

Multiple columns are showing the same error while only one column needs to be corrected to fix it. Only the error column should be highlighted ideally
