### ISSUE TITLE
[a11y] Modifying WB mapping gives JSON error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1446]
Reassigned a couple fields and I got this error:

![image](https://user-images.githubusercontent.com/37256050/167444049-3fc04c78-3b62-4597-b5b8-2ed2353c5fd6.png)

[Specify 7 Crash Report - 2022-05-09T15_27_55.436Z.json.zip](https://github.com/specify/specify7/files/8653069/Specify.7.Crash.Report.-.2022-05-09T15_27_55.436Z.json.zip)

Cannot replicate - may be due to schema changes before saving. Instance was opened and modifications were made before schema changes were done

**Comment by maxxxxxdlp** [comment]
This probably happened because the test server deployments were changed by someone else.
Schema changes should not cause this bug.
Please reopen this if it happens again.
