### ISSUE TITLE
[a11y] Creating a new record set from a query asks permission and ID questions

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1447]
![image](https://user-images.githubusercontent.com/37256050/167444936-eaa0977d-24fa-4075-8144-42a6b8cae5a3.png)

![image](https://user-images.githubusercontent.com/37256050/167444966-76fc4469-78cc-4eeb-9bf7-8b90c629e09d.png)

These questions should be invisible or at least disabled by default. If this is intended, it should not display IDs

**Comment by maxxxxxdlp** [comment]
Your database does not have a view for the RecordSet table, so it used a default view.
The default view displays all the fields from the RecordSet table that are not hidden in your schema config.
Hide those fields in the schema or define a view for the RecordSet table
