### ISSUE TITLE
[a11y] Is On Loan & Interactions buttons not appearing correctly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1451]
<img width="253" alt="image" src="https://user-images.githubusercontent.com/37256050/167453770-3f01a327-b734-4f3e-85b3-52f703eb0e4e.png">

![image](https://user-images.githubusercontent.com/37256050/167453782-9f9decc6-7571-442e-8958-df3776a3abb2.png)

[nm3](https://a11y-2-2.test.specifysystems.org/specify/view/collectionobject/77933/)

**Comment by maxxxxxdlp** [comment]
For "SHOW_INTERACTIONS" button, need to add a `[label]` attribute
https://github.com/specify/specify7/wiki/Form-System#:~:text=them%20for%20return.-,label%20(string%2C%20optional),-Label%20to%20be

The "IS_ON_LOAN" is a bug. Should be fixed
