### ISSUE TITLE
[a11y] TypeError in Record Set

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1454]
**Describe the bug**
A TypeError occurs when viewing the CO form in a record set (potentially outside as well)

db: mariamitchell
user: jablyth
collection: Edith F Andrews

**To Reproduce**
1. Go to the MMA Ornithology record set
2. Wait on any record
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/37256050/167463323-2dc92500-3343-4e30-b8fc-83f9a5055826.png)

Windows 10, Edge

**Comment by maxxxxxdlp** [comment]
Unable to replicate in my local freshfish database.

There are no record sets in that database on the server:
![Screen Shot 2022-05-09 at 13 05 58](https://user-images.githubusercontent.com/40512816/167470525-4ead5983-152d-4b53-98ff-93f6b3822f94.png)

If you are able to replicate that again, send me the URL
