### ISSUE TITLE
[a11y] Choose Collection behavior not being respected in all cases

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1455]
![image](https://user-images.githubusercontent.com/37256050/167464798-a3aedf37-9e14-455b-90e2-fff13217a8b2.png)

Choose Collection behavior is acting irregularly.

**Comment by maxxxxxdlp** [comment]
To clarify this:
Grant unchecked the checkbox and hit "Save", but it was checked again the next time he signed in

**Comment by maxxxxxdlp** [comment]
Likely was caused by 206b6f79
