### ISSUE TITLE
[a11y] Adding a Taxon name to the Taxon Attribute WB mapping gives an error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1457]
![image](https://user-images.githubusercontent.com/37256050/167467519-8001ce1c-7e1b-49f9-96ff-bd28861fc81f.png)

db: westvirginia
user: spadmin

[WB Plan](https://a11y-2.test.specifysystems.org/specify/workbench-plan/2/)

**Recreate this issue:**
Map a field to the Taxons relationship, then choose a rank and map to a name.

![image](https://user-images.githubusercontent.com/37256050/167467727-ecf09930-a495-4fe9-b455-ce6eacabd799.png)

[Specify 7 Crash Report - 2022-05-09T17_48_42.369Z.zip](https://github.com/specify/specify7/files/8654000/Specify.7.Crash.Report.-.2022-05-09T17_48_42.369Z.zip)

**Comment by maxxxxxdlp** [comment]
Unfortunately, it seems like WB does not currently support a -to-many mapping to a tree table.
I will disable this feature in the WbPlanView to not cause this exception in the future

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/taxon-attribute-loading-up-data/3543/2
