### ISSUE TITLE
Copy & paste system information button for support

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1466]
![image](https://user-images.githubusercontent.com/37256050/167492958-32982fab-9c7f-446d-82c8-d01b1deb720c.png)

When troubleshooting 7 issues on a non-hosted database, it would be really nice to be able to have a user export all of these items in a file that we could read. It would be nice to have:

Could potentially be accessed from the **User Tools** (maybe hidden in the "i" icon) so we can have users share this information from wherever they are. These are always helpful when troubleshooting.

1. Version
2. Specify 6 version
3. Database version
4. Schema version
5. Database name
6. Username
7. Institution
8. Discipline
9. Collection
10. Browser/User agent
11. Current URL

**Comment by maxxxxxdlp** [comment]
Good idea!
FYI, this information is already included as part of the crash report, along with current user info, permissions, preferences and collection settings

**Comment by maxxxxxdlp** [comment]
Added a "Download Information" button to the About dialog.

The button would download a file similar to the crash report.

Do you have a suggestion for a label better than `Download Information` or is it good enough?

**Comment by grantfitzsimmons** [comment]
For reference:

<img width="518" alt="image" src="https://user-images.githubusercontent.com/37256050/192677805-53a55f4b-cdde-4203-80e8-690f2bd75a5f.png">
