### ISSUE TITLE
Issue with saving lithostrat/chronostrat without parent/rank selected

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#147]
In a paleo database, when trying to add lithostrat and chronostrat to Paleo Context, I created new nodes for each. When on a new lithostrat/chronostrat form, no rank (you can't choose any ranks until a parent is selected) or parent is initially filled in, so when you try to save after giving the node a name, you get an error.

This could probably be fixed by making the parent field required (like how it is in taxon and geography forms). This way, you can't save without choosing a rank (which causes the error), because once you add a parent, it automatically fills in rank and allows you to pick different ranks as long as they are valid (no empty choice).

Error message:
AttributeError at /api/specify/lithostrat/
'NoneType' object has no attribute 'rankid'

**Comment by benanhalt** [comment]
Is the parent field required for these in Sp6? They can't be made non-nullable at the db level, which means the taxon and geo parent must be required by the forms. In which case, this is a form configuration issue not a code issue.

**Comment by garrettgirard** [comment]
Parent is not a required field for Lithostrat and Chronostrat in Specify 6. I guess the way it works in Sp6 is that the rank field is grayed out until a parent is chosen. Maybe this would be a better solution for this issue. This is how it works for taxon/geography as well, so it might be a good idea to just implement it for all the tree forms (graying out the rank field until parent is chosen).

**Comment by garrettgirard** [comment]
This actually doesn't fix the issue, because you can still click the save button after entering a name. Since name is still the only field that's required for litho/chrono forms, you can save without choosing a rank or a parent, resulting in the same error. Is it possible to disable the save/save and add another buttons for these forms without making the parent fields required? If so, doing this should fix the bug for good.
