### ISSUE TITLE
[a11y] Query gives differing count of results

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1471]
**Describe the bug**
Using the same query, db, user, and collection, the number of results are different between `a11y ` (2584) and `edge` (2649).

db: fwri
user: plarson
query: `/specify/query/75/`
collection: Marine Invertebrates

![image](https://user-images.githubusercontent.com/37256050/167498784-7df3568a-3146-4a73-b637-0d8d75058bee.png)

**Comment by maxxxxxdlp** [comment]
The query on the left is run in the distinct mode.
The query on the right is not, plus edge does not support distinct mode
