### ISSUE TITLE
[a11y] Query field only resizes after interaction

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1472]
![msedge_Rf2ZvrIYjw](https://user-images.githubusercontent.com/37256050/167499061-34c476f3-8d47-4210-a660-ac5459f1d572.gif)

Same query on previous version:

![image](https://user-images.githubusercontent.com/37256050/167499115-6bc6efdb-2b30-408a-bb51-b0e906424daf.png)

db: fwri
user: Plarson
collection: Marine INvertebrates
/specify/query/254/

**Comment by maxxxxxdlp** [comment]
Unable to replicate on maxOS in Edge and Safari
