### ISSUE TITLE
[a11y] Labels are not showing the same results

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1478]
[Image here](https://drive.google.com/open?id=1YLgJZT4Rr_hNCyeE5ikr-fWXa_g3rfrv&authuser=grant%40specifysoftware.org&usp=drive_fs)

Left is `a11y`, right is `edge`

db: fwri
user: Plarson
report: FishLargeLabel
Record Set: Check the tissue box

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/167668407-4d0439c6-2bb1-40b7-99dd-1395b2087238.png)

In both cases, the query was configured so that the **Packaged By Last Name** equals Bentley.

![image](https://user-images.githubusercontent.com/37256050/167668595-aeaf0f34-948d-4f48-a26d-6997fd1acf8c.png)

![image](https://user-images.githubusercontent.com/37256050/167668704-be583fe0-02ed-47fc-bbd6-4de5cc56a523.png)
![image](https://user-images.githubusercontent.com/37256050/167668767-8e06cc89-2932-4454-b640-b3aace796ba0.png)

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/167669304-a5b724db-a59a-4ed5-824a-9fcd300edccf.png)

More elements not appearing- **Datamax Jar labels** on `oldfish`

**Comment by benanhalt** [comment]
Confirmed that the FWRI label mentioned at the beginning is working in current build.
