### ISSUE TITLE
[a11y] Make a Record Set is visible in the QCBX QB

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1483]
**Describe the bug**
The **Make Record Set** feature is visible in the QCBX QB. It has no function and should be hidden.

**Screenshots**
![msedge_U9pCMmjk6T](https://user-images.githubusercontent.com/37256050/167654227-a03bddea-015e-4ecc-b4cc-9850af7d048c.gif)

Windows 10, Edge

**Comment by maxxxxxdlp** [comment]
It had no function because of this bug: https://github.com/specify/specify7/issues/1489
Should be functional now
