### ISSUE TITLE
[a11y] Giving no value to an integer field results in an error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1484]
If a user wants no value in an integer field, the following error occurs:

![image](https://user-images.githubusercontent.com/37256050/167655050-bd070256-3571-4405-846c-2f10a083f75e.png)

You must have 0 or an integer to save the form.

**Comment by maxxxxxdlp** [comment]
This probably field specifc.
Can you try to replicate this and add a comment saying which specific field is causing the exception?

**Comment by grantfitzsimmons** [comment]
This issue was caused by removing the inserted 0 integer and saving the forms. I will try to recreate but I haven't had any issue since you solved that issue
