### ISSUE TITLE
[a11y] Integer fields are given a default value of 0

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1485]
Record 36471 was created in `edge`
Record 36472 was created in `a11y`

Integer fields defaulting to "0" can give the impression that the data was intentionally entered rather than left out. This can cause issues for collections understsanding if there really is a count of 0 or no data was entered.

![image](https://user-images.githubusercontent.com/37256050/167654887-a815e52d-5118-478f-a849-84957391600b.png)

![image](https://user-images.githubusercontent.com/37256050/167655693-c9edd847-823d-43bb-a2a5-f0cf8c38ab65.png)

**Comment by maxxxxxdlp** [comment]
Fixed in ccb055ef
