### ISSUE TITLE
DNA Sequences pick list discrepancy 

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1491]
![image](https://user-images.githubusercontent.com/37256050/167672626-b01735e8-c851-4f18-9adb-5c3fbbab0709.png)

![image](https://user-images.githubusercontent.com/37256050/167672684-de896fd3-3f89-41b5-8126-757e8a4e4315.png)

The pick list items are different between `edge` and `a11y`.

db: oldfish

**Comment by maxxxxxdlp** [comment]
Can you test this again?
I see only one pick list item for that pick list in my copy of freshfish, on a11y on the test server, on edge on test server and on the edge branch of sp7demofish.specifycloud.org

<img width="811" alt="Screen Shot 2022-05-10 at 22 47 29" src="https://user-images.githubusercontent.com/40512816/167765277-2caabcee-569d-4a96-a7be-7ace6480822d.png">

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/168158843-81e84356-2387-4d09-a8dd-2319bbc4fa3f.png)

![image](https://user-images.githubusercontent.com/37256050/168158862-2cc9d3ce-f734-4332-a8c6-9e9d1dce0964.png)

db: `kufish`
col: `KU Fish Tissue Collection`
`/specify/view/collectionobject/46516/?recordsetid=89`

**Comment by grantfitzsimmons** [comment]
[Slack](https://specifydev.slack.com/archives/CC6V12D3J/p1664804375295269)

We need to solve this issue. It cannot be recreated in Specify 6.

On the [KU Ichthyology server](https://ichthyology.specify.ku.edu/specify/view/collectionobject/45285/)

In the schema, the MoleculeType field is pointing to a pick list that is not being used ([Link](https://freshfish-v773.test.specifysystems.org/specify/view/picklist/224/))

On my test DB, I am not seeing a pick list in 7 at all for this table.

![image](https://user-images.githubusercontent.com/37256050/193614002-7e3371cf-d84f-4647-a68f-441e57c0bb84.png)


**Reported By:** @acbentley

**Comment by maxxxxxdlp** [comment]
That is a separate issue. See https://github.com/specify/specify7/issues/1064#issuecomment-1267382697

**Comment by grantfitzsimmons** [comment]
> ![image](https://user-images.githubusercontent.com/37256050/168158843-81e84356-2387-4d09-a8dd-2319bbc4fa3f.png)
> 
> ![image](https://user-images.githubusercontent.com/37256050/168158862-2cc9d3ce-f734-4332-a8c6-9e9d1dce0964.png)
> 
> db: `kufish` col: `KU Fish Tissue Collection` `/specify/view/collectionobject/46516/?recordsetid=89`

Why did this work in 7.6.1 and not in 7.7?? @maxxxxxdlp

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons should be fixed by https://github.com/specify/specify7/pull/2286

**Comment by chanulee1** [comment]
<img alt="image" width="500px" src="https://user-images.githubusercontent.com/103299204/194600383-94c5d870-f159-4672-baf2-40d02ba1f955.png">

db: `kufish`
col: `KU Fish Tissue Collection`
user: `spfishadmin`
ver: `edge`

<img alt="image"  width="500px" src="https://user-images.githubusercontent.com/103299204/194601074-d3842482-2eb7-4fc1-bb9c-059af92475b9.png">

db: `kufish`
col: `KU Fish Tissue Collection`
user: `spfishadmin`
ver: `7.6.1`

Can still see picklist discrepancy.

**Comment by maxxxxxdlp** [comment]
It could be that you tested this before the code got merged into production. Can you try this again?

**Comment by chanulee1** [comment]
Looks like the discrepancy between `edge` and `7.6.1` is still there.
