### ISSUE TITLE
[a11y] Saving an Accession record does not save Modified By Agent

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1492]
![image](https://user-images.githubusercontent.com/37256050/167676213-698a4c09-ce1c-4562-b8b7-e7bb79bb798f.png)

On `freshfish`, saving a new accession did not fill in Modified by Agent. Viewing on `edge` confirms that the field was still blank. Saving on `edge `then filled the Modified By Agent.

**Comment by maxxxxxdlp** [comment]
Creating new record does not populate the `modified by` field
Modifying an existing record does populate `modified by` field

Not sure why the `timestamp modified` was populated though. May be a bug. I will ask Ben

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/167862783-77c42f4c-7ad9-4f41-b691-b88cee82c575.png)

Records created in edge and a11y both populate the modified date so I expected the behavior to be replicated for the modified by agent

**Comment by maxxxxxdlp** [comment]
Reply from Ben;
> It's probably because there is a mechanism in Django that automatically sets the timestampmodified
It's never been clear to me if a new record should be considered modified. It doesn't seem like those fields would be nullable if so.
