### ISSUE TITLE
[a11y] CE subview appearing improperly 

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1499]
![image](https://user-images.githubusercontent.com/37256050/167690374-99b3797b-7d35-4269-9718-523f3825b9dc.png)

Collecting Event subview is compacted to the left side of the screen.

db: `oldfish`
user: `abentley`
col: Fish Voucher

`/specify/view/collectingtrip/6147/`

**Comment by maxxxxxdlp** [comment]
Does not seem to happen anymore (tested in `kufish`)
Probably was caused by same bug as https://github.com/specify/specify7/issues/1441.
Please reopen this if it happens again

**Comment by grantfitzsimmons** [comment]
I can successfully recreate on `kufish`

Same link - `/specify/view/collectingtrip/6147/`

![image](https://user-images.githubusercontent.com/37256050/167850729-8e116367-9c01-46db-8af9-76aaed48b9ba.png)

**Comment by grantfitzsimmons** [comment]
macOS, Safari

![image](https://user-images.githubusercontent.com/37256050/168129432-23cee83b-03d8-49d0-9470-d51d3e8285d6.png)
