### ISSUE TITLE
Form switching between View and Edit mode.	

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#15]
I am not convinced this is important. Although, it is important to have a 'view-only' mode for those that only have read-only permissions.

**Comment by beach53** [comment]
I would like to know the use cases, this also seems like a marginal capability on the face of it.

**Comment by benanhalt** [comment]
Most of the early issues (#1 - #25 or so) were things I copied over from a really early requirements list. Some of them may not be relevant anymore.

For this particular issue, the only reason I can see for it would be to prevent anything from accidentally being changed by someone with edit level access. But since they would have to click *Save* anyways, it doesn't seem very likely.

**Comment by maxxxxxdlp** [comment]
Fixed. Can be enabled from the form preferences dialog.

When in read-only mode, the user can't delete, update or create any records.
