### ISSUE TITLE
Can't Delete Agents with Groups

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#150]
Similar to #103, if you add any agents to the Groups field in the Agent form and save, attempting to delete the Agent results in an error. You must first remove any agents in the Groups field and then save before being able to delete the Agent.

**Comment by garrettgirard** [comment]
The same is true for Variants on the Agent form. They must be deleted before being able to delete the Agent form.

**Comment by benanhalt** [comment]
Maybe this is actually a feature? As a double-check before deleting.

**Comment by melton-jason** [comment]
This issue seems fixed. I can not replicate the issue. 
Was this able to be replicated anywhere?

**Comment by grantfitzsimmons** [comment]
I can't replicate either. I think we can close this issue.
