### ISSUE TITLE
[a11y] Items that are added to picklists that exceed the limit throw an error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1502]
![image](https://user-images.githubusercontent.com/37256050/167692181-285e5ad1-ace5-44af-bd87-a552098c2ff7.png)

The option to add an item to a picklist should not appear if there is no room to add. If this behavior is not correctable, then there should be a dismissible error or check before allowing the user to lose all progress and send them to the homepage.

**Comment by maxxxxxdlp** [comment]
Duplicate of #108
