### ISSUE TITLE
Show map button not working on Locality form

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1510]
**Describe the bug**
Clicking the show map button on the locality form pops up dialog that locality must have coordinates even though it does

**To Reproduce**
1. Go to Locality form for existing locality with coordinates
2. Click on Show Map
3. See error

**Expected behavior**
Map should show when coordinates are present

**Screenshots**
![Capture](https://user-images.githubusercontent.com/7501989/167717037-8b7b6aba-0c06-431e-b60f-8265ebfb651e.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by grantfitzsimmons** [comment]
Maybe related to https://github.com/specify/specify7/issues/1497
