### ISSUE TITLE
Heading mismatch in loan preparation dialog

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1511]
**Describe the bug**
When preparing a loan from a list of specimens, the loan preparation list dialog has a weird header mismatch

**To Reproduce**
1. Go to Loan from record set
2. Select record set
3. Shows list of preparations

**Expected behavior**
I would expect the headers to be aligned with the content below each header - maybe center justify them

**Screenshots**
![Capture2](https://user-images.githubusercontent.com/7501989/167717566-91671352-7621-4ad2-aee9-13ed58d179d5.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
The content of Cat #, Available and Unavailable columns in right-aligned so that numbers between the rows can be easily compared.
The other columns are text, thus left aligned. The table headers are left-aligned (which is consistent with all other places in new release)

**Comment by acbentley** [comment]
It does not look good though.  Why is there so much space between the checkboxes and the catalog number?  Similarly for Available and Unavailable?  Surely they would look better center justified or removing unnecessary space in each column (make them fit to longest string)?  The whole window could be reduced in width then.

**Comment by maxxxxxdlp** [comment]
Fixed the issue with columns being too wide
