### ISSUE TITLE
When changing a pick list to read only, it requires a size limit of at least two

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1515]
When checking the box to make a pick list read only, it won't save unless you enter a size limit of at least two.  However, that field becomes irrelevant when a pick list is read only so it should be greyed out.

To replicate:
Open an existing pick list that is NOT read only (I used
Check the read only box 
Click save
A message saying the count should be at least two appears

![image](https://user-images.githubusercontent.com/12532430/167741601-c27b71bf-9ae9-45e4-a6b3-6b4750958b0f.png)

**Comment by maxxxxxdlp** [comment]
It is set that way in the form definition:

```xml
<cell id="sizeLimit" initialize="max=500;min=2" isrequired="true" name="sizeLimit" type="field" uitype="spinner" />
```

Other than the form definition, there is no reason why it can't be -1. Specify 7 would handle both 0 and -1 as "no limit"

**Comment by tlammer** [comment]
Which form definition is it reading from?  the accession form definition for that field just says make it a pick list, it does not include size or other information.

**Comment by maxxxxxdlp** [comment]
It looks like the picklist view is part of system views.
It is not editable in the UI, but you can overwrite the default view by adding your own definition.
Here is how a default view looks like:
https://github.com/specify/specify6/blob/24cbca18e126ac0a68d1343eb4ee32326e3b5bf5/config/backstop/system.views.xml#L166

It also means that we can update this view with new specify 6 release

**Comment by maxxxxxdlp** [comment]
To clarify, Specify 6 disables the "sizeLimit" field if pick list is read only.
It probably makes sense to replicate that behavior in Specify 7

**Comment by emenslin** [comment]
Can recreate in edge (7.9.6)

**Comment by grantfitzsimmons** [comment]
## New
![Image](https://github.com/user-attachments/assets/1109386a-45bc-4d64-bd9c-04723da38943)

## Old
![Image](https://github.com/user-attachments/assets/fc989485-08d8-4872-9eab-a1a9f191d567)

**Comment by grantfitzsimmons** [comment]
Fixed in https://github.com/specify/specify7/commit/56c4059eeb414ec461c1c6bfb8032d62b160af06
