### ISSUE TITLE
[a11y] (deaccprep) appearing in collapsed Preparation subview

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1518]
![aad12](https://user-images.githubusercontent.com/37256050/167863951-d5d96909-4c76-434c-9065-fc6cf3ae0410.gif)

Windows 10, Edge

db: `nm3`

**Comment by maxxxxxdlp** [comment]
They have this in their form definition:
```xml
<cell colspan="12" id="deaccprep" name="deaccessionPreparations" type="subview" viewname="DeaccessionPreparation2" />
```
The relationship "deaccessionPreparations" does not exist on the Preparation table.

Since it can't use field label as a column heading, it was using cell ID.
Fixed by not using the cell id as column heading

**Comment by grantfitzsimmons** [comment]
> They have this in their form definition:

This is actually in the default botany forms definition!

**Comment by maxxxxxdlp** [comment]
@benanhalt Do you why that field is not known to specify 7?

**Comment by benanhalt** [comment]
DeaccessionPreparation table was removed in 6.8.01. Probably the default form didn't get updated to reflect the change.
