### ISSUE TITLE
[a11y] Users can navigate away from an unsaved record set page

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1521]
**To Reproduce**
1. Edit a record inside of a record set
2. Navigate to the following page
3. See no warning

You can save the changes after navigating back even after modifying another record and saving its changes. It should warn you so you do not forget, or the record set should support a "Save All" feature.

db: `kufish`

**Comment by maxxxxxdlp** [comment]
Fixed. Due to a bug, the unload protect dialog was only appearing for new records
