### ISSUE TITLE
[a11y] Can expand window bounds outside of viewable area

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1522]
![msedge_59U92YYigM](https://user-images.githubusercontent.com/37256050/167877538-89819562-8714-4b16-a99c-e0427451fbae.gif)

This issue has made me resize windows to be able to move them out of the way.

db: `nm3`
Windows 10, Edge

**Comment by maxxxxxdlp** [comment]
Superseded by #3012
