### ISSUE TITLE
Specify 7 is not reading in interaction preferences from Specify 6

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1524]
**Describe the bug**
Specify 7 is not using the preferences for interactions as set in the Specify 6 preference panel, interactions tab

**To Reproduce**
1. Go to Loan
2. Click on Record set
3. Create loan
4. Loan due date and shipping details are not entered
5. See error

**Expected behavior**
Without the corresponding prefs in Specify 7 I would expect Sp 7 to read in prefs from Sp 6

**Screenshots**
![Capture](https://user-images.githubusercontent.com/7501989/167883315-8d84566a-77b4-44e3-8f04-a95cd2d4e835.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by grantfitzsimmons** [comment]
@acbentley This is now specified in the form definition for the time being

**Comment by grantfitzsimmons** [comment]
> @grantfitzsimmons So, how does that work if I am using 6 and 7. Will the form defs overwrite the prefs or vice versa in 6 and 7?

My understanding of it is that 7 ignores the 6 prefs and 6 will ignore the 7 prefs.

**Comment by grantfitzsimmons** [comment]
@acbentley Max confirmed; it is likely that 6 overrides the form definition in 7. I am going to test this, but this change is intentional.

**Comment by maxxxxxdlp** [comment]
@acbentley Here is documentation on how to set a default value in the form definition:
[default (string, optional)](https://github.com/specify/specify7/wiki/Form-System#:~:text=For%20date%20fields%2C%20can%20set%20this%20to)

It is similar to how Specify 6 works, except Specify 7 also added support for relative dates as default values: `today + 1 month`
