### ISSUE TITLE
[a11y] Can scroll down infinitely in the WB Mapper

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1525]
![image](https://user-images.githubusercontent.com/37256050/167883995-67862663-1b44-4b59-88c6-4d758d290e96.png)

db: `nm3`
`/specify/workbench-plan/13/`

macOS, Edge

**Comment by maxxxxxdlp** [comment]
Are you able to reproduce this?

**Comment by grantfitzsimmons** [comment]
This has been resolved as far as I can tell. I cannot recreate on Windows or Mac on Chrome or Edge.
