### ISSUE TITLE
Lat/long controls not showing up correctly on locality form

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1528]
**Describe the bug**
The latitude and longitude controls for decimal degrees, degrees minutes seconds, etc. are not showing on the locality form as they do in Specify 6.  Also, line information coming from Specify 6 is not being handled correctly.

**To Reproduce**
1. Go to EAST 33K:16532 collecting event in KUfish
2. Open Locality
3. See error

**Expected behavior**
I would expect to be able to select type of lat long I want to enter and for start and end lat and long to be in the same format.

**Screenshots**
![Capture4](https://user-images.githubusercontent.com/7501989/167894362-46136745-0e78-43c2-88cb-5ea13e5c7597.JPG)
![Capture5](https://user-images.githubusercontent.com/7501989/167894446-b0a3b8f1-68e3-4dbe-a2cf-d762bb3326cd.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by acbentley** [comment]
Oops, I just fixed it but you can see from screenshots what it looked like originally

**Comment by maxxxxxdlp** [comment]
For some reason, the `lat2text` and `long2text` fields are empty for that record.
`latitude2` and `longitude2` are not empty though, so I would use them in such cases.
