### ISSUE TITLE
Deleting agent that is referenced by CO causes error

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#153]
As of right now, whenever you try to delete an agent who is a cataloger of an associated CO, you get a pop up message warning you that you can't delete the agent because they are referenced by the CO.

However, this is not true for other agent roles, such as determiner, collector, member, author, etc.

If you try to delete agents that are associated with anything, you get an error.
This is the error message:
IntegrityError at /api/specify/agent/695/
(1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`KU Invp`.`collector`, CONSTRAINT `FK7043CC8D384B3622` FOREIGN KEY (`AgentID`) REFERENCES `agent` (`AgentID`))')

**Comment by benanhalt** [comment]
I started adding business rules for these, but there are 44 separate instances. It makes more sense to handle them automatically, which falls under #132.

**Comment by benanhalt** [comment]
Also, deleting agents should almost never happen.
