### ISSUE TITLE
Web link buttons not working

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1531]
**Describe the bug**
Web link buttons do not take you to the URL - nothing happens

**To Reproduce**
1. Do a search for collection objects where CT Scan is not empty
2. Click on CT scan web link button on CO form
3. See error

**Expected behavior**
Should work.  Similar or Fishbase web link button on taxon form or Genbank sequence web links

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by grantfitzsimmons** [comment]
Can recreate on Safari

**Comment by grantfitzsimmons** [comment]
mailto, fishbase, and genbank are all not working. I think it is safe to assume all web links are broken currently
