### ISSUE TITLE
Doesn't look like you can copy Master Key

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1537]
When Generating the Master Key, a red stop sign appears when you hover over the text, making it seem like you can't copy it, which is the purpose of the feature

![image](https://user-images.githubusercontent.com/12532430/167904976-436e1631-d343-45b2-a219-357690799d14.png)

Okay, you can't see the red circle with a line through it but it appears when you hover over the text.  It should appear as a cursor so you can highlight it all.  Or a Copy button should be available, but either way, it should not show as a circle with a line through it

**Comment by grantfitzsimmons** [comment]
@tlammer Looks great!

![image](https://user-images.githubusercontent.com/37256050/168086081-c62d11b8-fa16-4e43-8c96-e2f5d3b91429.png)
