### ISSUE TITLE
Security panel policy selections with only a single option should be selected by default

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1542]
**Describe the bug**
There are multiple policy options where only one option exists in the resulting drop-down menu (see screenshot).  These should be selected by default so as to prevent multiple clicks.

**To Reproduce**
1. Go to Security Panel
2. Click on role
3. Select Policy

**Expected behavior**
Each policy option with only a single option should select that option by default to prevent additional clicks.  

**Screenshots**
![Capture](https://user-images.githubusercontent.com/7501989/167921689-71bc8fea-71c7-4ea2-ace4-872201098926.JPG)
Also Preferences -> User not shown

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Fixed. Now checkbox is checked automatically if there is only one.

For other things, please create a separate issue as they are not related.

**Comment by maxxxxxdlp** [comment]
Ah, I see.
Fixed. If there is only one policy, in a given parent policy, it would be selected automatically
