### ISSUE TITLE
Opening forms should highlight first field for data entry

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1543]
**Describe the bug**
As in Specify 6, Specify 7 should place the cursor in the fist field on the form ready for data entry rather than opening with nothing selected.

**To Reproduce**
1. Go to any data entry form
2. Note that cursor is not active in any field
3. See error

**Expected behavior**
Would expect top left hand most field to have cursor active for data entry on opening form

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Actually, when you open a form, the form itself is selected.
Pressing the "Tab" key just once would bring focus to the first interactive element (be it a field or a button)

**Comment by acbentley** [comment]
Why would we have focus on the form if it doesn't perform any action?  We should focus on the first field so there is no need to click any buttons to get started.

**Comment by maxxxxxdlp** [comment]
It is bad for accessibility. Here is the explanation - https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus#accessibility_considerations

Also, there are some difficulties with it (it can be buggy and predictable).
If you still want this feature, I can add it in the next release. This behavior won't be enabled by default but could be enabled through user preferences menu.

**Comment by acbentley** [comment]
Yes.  I have wanted this for collectors too.  That extra click to get into the focus field is annoying and time-consuming.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-13-release-announcement/1230/1
