### ISSUE TITLE
Security Panel preview does not accurately show policy information for new user created

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1544]
**Describe the bug**
When creating a new user and saving it, the first screenshot indicates that this FullAccess user has full privileges to all tables.  However, when closing and reopening this user, it now indicates that this user only has read access

**To Reproduce**
1. Go to Security Panel
2. Click on a collection
3. Create a new user and save
4. Close user and reopen
5. See error

**Expected behavior**
I would expect the initial policy preview to show the correct privileges.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/7501989/167941012-2d8241d0-627d-47ad-af28-f6820d9edf39.JPG)
![Capture2](https://user-images.githubusercontent.com/7501989/167941027-ad01366f-a42d-41d4-ab51-5081fb0b023b.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
The first screenshot shows a single policy for this user (collection access) and a "Preview" of all user permissions when their policies and roles are factored in.
After you saved the user, read access to several tables was added automatically as every user who has any hope of signing in must have access to those tables.
The "Preview" portion is still present, but you have to scroll below the policies to see it

**Comment by acbentley** [comment]
But he is listed as a FullAccess user and so should have privileges accordingly.  Why do you not show that preview?  It doesn't seem to make sense and will be confusing to users.

**Comment by acbentley** [comment]
This seems counterintuitive:

![Capture](https://user-images.githubusercontent.com/7501989/168100273-96cffabf-fe40-4b81-8889-389453f59f12.JPG)

**Comment by maxxxxxdlp** [comment]
@acbentley That user has a "Full Access" role which gives them access to all tables.
You can find this out by clicking on any checkbox in the "Preview" table and it will explain why this user has or doesn't have this permission

**Comment by maxxxxxdlp** [comment]
Fixed. It won't be auto adding those policies anymore
