### ISSUE TITLE
Security panel policy All option should be removed

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1548]
**Describe the bug**
Remove the all option for Security Panel policy options as it is not all and items lose their context

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Fixed by hiding the policy lines for institutional admins
