### ISSUE TITLE
Determination sorts author in full name like taxon

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1553]
https://user-images.githubusercontent.com/37256050/168115796-4de80cf2-c088-4d80-b3d1-7153b3fd9cbb.mov

Genus Author is being sorted the same as Genus Species Author, causing an issue. This is after adding Author to the full name displayed for Taxon.

![image](https://user-images.githubusercontent.com/37256050/168115925-d46ec554-1b22-4521-8a3c-1c98d5179c61.png)

**Reported By:** RBGE

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons Is this fixed by fixing https://github.com/specify/specify7/issues/1921?

**Comment by grantfitzsimmons** [comment]
It looks like it would be. I will reopen if I encounter this issue again.
