### ISSUE TITLE
Workbench not accepting catalog number formatter

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1554]
**Describe the bug**
Inserting #'s should auto-assign catalog numbers in the Workbench but is instead throwing an error

**To Reproduce**
1. Go to Workbench
2. Open dataset with catalog number field
3. Enter ######### into catalog number field and copy down

**Expected behavior**
Expect to be able to enter field formatted to auto-assign catalog numbers

**Screenshots**
![Capture](https://user-images.githubusercontent.com/7501989/168118332-e014d074-3f20-4bbd-a28a-f2bc14eaf742.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by acbentley** [comment]
It is showing it again now for that dataset.  Seems to be inconsistent

**Comment by grantfitzsimmons** [comment]
Seeing the same error as @acbentley. @maxxxxxdlp You should open the data set in Safari or another browser & give it a look
