### ISSUE TITLE
[a11y] Form size needs to be improved

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1555]
Adjusting the form width is a pain right now- maybe it should be a regular number/text field with an apply button instead of happening in real time.

![form width](https://user-images.githubusercontent.com/37256050/168119277-0cba4da4-9c99-43c0-88dd-6a5399e1c384.gif)

**Comment by grantfitzsimmons** [comment]
I think most people will not increment the form width 1 pixel at a time and likely use a mouse (user prefs should assume little technical literacy), leading them to click the up or down arrow repeatedly, potentially hundreds of times.

Maybe even a delay would suffice to allow a few seconds to type a new number

**Comment by maxxxxxdlp** [comment]
Fixed. The value won't be anymore applied until field looses focus
