### ISSUE TITLE
[a11y] QCBX icons have solid color backgrounds

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1558]
![image](https://user-images.githubusercontent.com/37256050/168127732-a4192d7c-3f8a-443d-b6c4-b9fe96389ba8.png)

QCBX buttons have a solid background behind the icons

**Comment by maxxxxxdlp** [comment]
Only disabled icons have a background.
I don't remember why I added that, but my excuse, in this case 😄 , would be that in increases the contrast between the background and the gray icon

**Comment by emenslin** [comment]
Fixed
