### ISSUE TITLE
[a11y] Form navigation buttons jump

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1560]
Navigation buttons jump up and down when pressed. The outline on the furthest right icon is thicker on the right side as well.

https://user-images.githubusercontent.com/37256050/168129216-0dee5514-acdf-4cc7-9177-dd1e91484227.mov

Safari, macOS

`kufish`
`/specify/view/collectingtrip/7729/`

**Comment by maxxxxxdlp** [comment]
I belive this was a UI bug in the early version of 7.7.0. Fixed in the release version of 7.7.0. Does not happen for me anymore.

@grantfitzsimmons can you check this again on 7.7.2

**Comment by grantfitzsimmons** [comment]
This was an early 7.7.0 bug, I can't recreate on any browser (Chrome, Safari, Edge)
