### ISSUE TITLE
[a11y] Prep Type showing as API

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1572]
![image](https://user-images.githubusercontent.com/37256050/168156624-1f40dc66-af32-41d1-aa9f-e57ca2e69dd7.png)

db: `kufish`
col: `KU Fish Tissue Collection`

https://a11y.test.specifysystems.org/specify/view/collectionobject/41396/

**Comment by grantfitzsimmons** [comment]
Pick list option is also not working correctly

**Comment by maxxxxxdlp** [comment]
The database has two pick lists with the same name.

This is is correct:

<img width="1800" alt="Screen Shot 2022-05-12 at 20 26 57" src="https://user-images.githubusercontent.com/40512816/168193161-eea22a43-dc66-4b3f-be42-aa3eae97734e.png">

This one should be deleted:

<img width="1800" alt="Screen Shot 2022-05-12 at 20 27 04" src="https://user-images.githubusercontent.com/40512816/168193163-12d6aa93-0e9a-4a05-90ad-3b8935644e01.png">

Picklists names must be unique (see #1064). For some reason, they are not in this case.
On `edge` if there are duplicate pick lists name, the first occurrence is used. On `a11y` the last one is used.

While pick lists should must not have duplicate names, I will still change the behavior on `a11y` to match that of `edge`.
