### ISSUE TITLE
Exported CSV column headers should be their labels

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1575]
When exporting query results to CSV, all column headers are the field names from the schema rather than the caption for those fields (e.g. “10.collectingevent.text4” rather than “Station number”). This request is to make the CSVs export with the captions so we don’t have to rename the columns every time we want to send data to someone.

**Requested By:** Plarson

**Comment by benritchie** [comment]
I've just hit this also.  
This is a really key enhancement.  without this, export to CSV isn't really useable, as many of the columns have headings like "text 1".  
There's a second related issue - even for the built in fields, the headers get some wider extra numbers in their names - e.g. see screenshot.  
Not sure what the numbers are, but pretty sure they can be removed?
![image](https://user-images.githubusercontent.com/8005676/171159964-c90c8845-d548-4ae6-a4fc-b8e72a2599b2.png)

**Comment by maxxxxxdlp** [comment]
I have a utility on the front-end that can abbreviate mapping paths.

Example results: https://github.com/specify/specify7/blob/a11y/specifyweb/frontend/js_src/lib/tests/testwbplanviewmappingpreview.ts

Can you add a body parameter to the export_csv endpoint to specify column captions? (I believe you already did that for some other endpoint)

**Comment by benanhalt** [comment]
Yeah something like that could work. Also opens the possibility for allowing user chosen headings.

**Comment by grantfitzsimmons** [comment]
Ran into this again. A reminder that Specify 6 supports this properly!

**Comment by grantfitzsimmons** [comment]
@specify/developers Is this something we are going to tackle in 7.8?

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-4-announcement/999/1
