### ISSUE TITLE
[a11y] Running a Report through a record set -> query causes an error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1576]
https://user-images.githubusercontent.com/37256050/168162793-3460da2b-a091-489a-8d8d-09fe7d77d682.mov

1. Run a report
2. Select **Query** instead of Record Set
3. Customize the query

macOS, Safari
`kufish`
`abentley`

**Comment by maxxxxxdlp** [comment]
The server was probably overloaded
Try a smaller record set

**Comment by grantfitzsimmons** [comment]
Not able to reproduce. Likely the server was overloaded
