### ISSUE TITLE
Workbench geocoordinate converter not working

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1580]
**Describe the bug**
The Convert Geocoordinate screen does not allow anything to be picked

**To Reproduce**
1. Go to workbench
2. Click on dataset that has lat and long columns
3. Select Convert geocoordinates

**Expected behavior**

**Screenshots**
![Capture](https://user-images.githubusercontent.com/7501989/168174379-9bc1f400-4a76-44f9-9e39-cb73fc793ea9.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Unable to replicate.
Can you try this again to see if it still happens?

![Screen Shot 2022-05-12 at 17 15 06](https://user-images.githubusercontent.com/40512816/168176548-9291eb7e-e506-413a-a4b3-d9e983560814.png)

**Comment by grantfitzsimmons** [comment]
Can confirm, the issue has been resolved for me across several workbench sets

**Comment by acbentley** [comment]
After testing some more it just seems to be taking a long time to activate.  Not sure why.
