### ISSUE TITLE
Numbering for Loan return Preps is buggy

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1587]
**Describe the bug**
When clicking on a loan return prep to try amending a return prep manually, the numbering does not function correctly

**To Reproduce**
1. Go to an existing loan with returned preps
2. Click on the Loan Return Prep table for a returned prep
3. Try editing the numbers

**Expected behavior**

**Screenshots**
![chrome_iEZIwSNxO8](https://user-images.githubusercontent.com/7501989/168329137-c3e47e99-b0ba-40cc-ae46-4c56787172c6.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by grantfitzsimmons** [comment]
https://user-images.githubusercontent.com/37256050/168333884-240e3c37-f5f6-495d-ad3a-14af9b758e5a.mov

Handling correctly on `edge`

**Comment by grantfitzsimmons** [comment]
https://user-images.githubusercontent.com/37256050/168337414-e2a429e3-9a88-4463-ba32-f1f24eac10fc.mov

This is acting incorrectly, I see it now

**Comment by grantfitzsimmons** [comment]
Making the quantity resolved negative makes the quantity returned negative, but increasing the value of this field does not effect the quantity returned. The loan is resolved even if the quantity returned is negative as long as the quantity resolved is the same count as the preparation quantity.
