### ISSUE TITLE
[a11y] Entering an invalid string in a picklist and pressing enter disables the picklist

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1589]
Entering an invalid string in a picklist and pressing enter disables the picklist

https://user-images.githubusercontent.com/37256050/168332472-8731a6fc-e8cd-4fcc-92bd-884bca259911.mov

db: rbge
user: robyn

https://a11y-2-2-2-2.test.specifysystems.org/specify/view/agent/new/

**Comment by grantfitzsimmons** [comment]
Can be resolved by deleting the contents of the field. Minor issue.

**Comment by maxxxxxdlp** [comment]
What do you mean by disables the picklist?
It returns to the previous value on focus loss if you entered a non-existent value

**Comment by grantfitzsimmons** [comment]
When you click on the field, the pick list functionality disappears. You can see the ▼ symbol disappear
