### ISSUE TITLE
Saving Taxon records sometimes creates many unsaved dialogs at once

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1590]
Sometimes (I haven’t figured out the specific conditions) after editing a taxon in the taxon tree and saving, the taxon form doesn’t automatically close. When I try to close it, the background becomes dark and the ‘unsaved changes’ warning dialogue pops up. The dialog box doesn’t go away until you repeatedly click “Leave.” Each time you click, the background gets lighter and the string of numbers in the URL gets shorter until the dialog box finally goes away and brings you back to the tree.
See below: after 7 or 8 times clicking “leave” the background tree is starting to fade in to view. After a few more clicks, I’m returned to the tree, and yes, my changes were actually saved.

![image](https://user-images.githubusercontent.com/37256050/168336208-1be5321e-ee64-41d2-99ae-48adde530cc4.png)

**Reported By:** Paul (Plarson, Florida Fish & Wildlife)

**Comment by maxxxxxdlp** [comment]
Probably fixed in the new release
