### ISSUE TITLE
UI can be color coded by Collection for quick recognition

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1591]
My suggestion is palette swap or other color options for different collections. I sometimes spend an embarassing amount of time looking for something in the icthyology collection that only exists in the invertebrate collection. The little text in the corner isn’t quite enough to always remind me of where I am in the database.
I don’t care if we can customize it or not, just some visual difference for multiple collections would be nice.

![image](https://user-images.githubusercontent.com/37256050/168336787-1a364daf-0ec2-4e4a-a1ed-ddc2f7f3c0ec.png)

**Requested By:** [Plarson on the Specify Forum](https://discourse.specifysoftware.org/t/seeking-new-user-settable-preferences-for-specify-7/386/2?u=specify)

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/168883276-7201b6f5-a8cc-41bf-9654-cbc4538ae2b4.png)

This would be even better. Collection-specific accent colors? Maybe the user chooses a color and a palette is generated and applied.

**Comment by maxxxxxdlp** [comment]
Actually, thanks for reminding me. This is already possible!
User preferences are scoped to a collection, so you can have different accent colors in different collections for the same user.

Admins can also set default user preferences that would apply to all users unless users explicitly overwrite them:
https://github.com/specify/specify7/wiki/Setting-default-user-preferences
