### ISSUE TITLE
Search on trees not working

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1594]
Found by @grantfitzsimmons 
![image](https://user-images.githubusercontent.com/40512816/168378932-008024c9-cdb9-44ec-9443-3c5dce7f6363.png)

**Comment by maxxxxxdlp** [comment]
Fixed
![image](https://user-images.githubusercontent.com/40512816/168379026-4b915a1e-24f5-4ff2-9d3c-7dd869974a08.png)

**Comment by grantfitzsimmons** [comment]
After all these years! Works great.

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/168877198-98da943a-92d4-45d4-af4f-7e57de0d14f8.png)

Having trouble searching the Georaphy tree in `rbge_herb`

https://a11y-2-2-2.test.specifysystems.org/specify/view/geography/11023/
