### ISSUE TITLE
Some headings in security panel "greyed out"

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1608]
**Describe the bug**
Some headings in the security panel appear as "greyed out" rather than in black like other headings (Name, Agent, User Group).  Specify 6 Permissions is greyed out because you cannot interact with it which makes this all confusing.

**To Reproduce**
1. Go to Security panel
2. Click on user
3. See error

**Expected behavior**

**Screenshots**
![Capture](https://user-images.githubusercontent.com/7501989/168648940-3c676198-f4aa-4ec0-ba27-6a99725e8637.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Fixed in #2b75daa5
