### ISSUE TITLE
Taxon imports cannot be rolled back

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1611]
```
{
  "uploaderstatus": {
    "operation": "unuploading",
    "taskid": "791b1f97-21da-407d-ade3-04c9325df5bf"
  },
  "taskstatus": "FAILURE",
  "taskinfo": "ProtectedError(\"Cannot delete some instances of model 'Taxon' because they are referenced through a protected foreign key: 'Taxon.parent'\", '<QuerySet [<Taxon: Taxon object (17074)>]>')"
}
```

It would be nice to be able to undo an import into a tree.

**Comment by maxxxxxdlp** [comment]
From @beach53:

> When a Workbench rollback fails, the user gets the first dialog.  A little geeky, not clear what the user should do, except click the stop button.  Also is that error text useful for the user, it does identify the record that fails although you have to scroll to find it.  Is this OK as is?

![image](https://user-images.githubusercontent.com/40512816/169077011-b036721e-965a-4f61-b8e2-402ba9de241b.png)

**Comment by grantfitzsimmons** [comment]
Good news! I tested this 5 minutes ago with success on a new Taxon import.

**Comment by grantfitzsimmons** [comment]
Closed since it seems like this was solved
