### ISSUE TITLE
[a11y] Changing items in Permission Panel do not make it saveable

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1613]
![abl](https://user-images.githubusercontent.com/37256050/168840858-6bfc61db-5ea2-4440-858e-d52c059245da.gif)

This can be recreated with many fields.

browser: Chrome
db: `kufish`

**Comment by maxxxxxdlp** [comment]
Which user are you signed in as?
It could be that your user doesn't have necessary permissions (although, in that case it shouldn't have even allowed you to open this page in the first place)

**Comment by maxxxxxdlp** [comment]
Unable to replicate:

https://user-images.githubusercontent.com/40512816/169146346-5f2ab02a-a777-4c5f-a787-3f345be90722.mov
