### ISSUE TITLE
[a11y] Creating a new Division from a QCBX causes an error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1615]
![image](https://user-images.githubusercontent.com/37256050/168845756-af36cba0-807d-4e43-ab67-5b9670713f09.png)

Left is Firefox, Right is Chrome

Error 500 on Firefox while on Chrome there is a 

`(1364, "Field 'UserGroupScopeId' doesn't have a default value")`

db: `kufish`

**Comment by grantfitzsimmons** [comment]
Solved somewhat by disabling the **+** on the Division QCBX

**Comment by emenslin** [comment]
Can no longer add a new division through the qcbx
