### ISSUE TITLE
Low-risk errors should be dismissable

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1616]
Errors that do not risk harming the database should not cause the user to lose all progress. The fields should be saved when the page is refreshed.

**Comment by maxxxxxdlp** [comment]
Another case when errors should be dismissable:
If more than one error dialog pop-ups, all but the last dialog must be dismissable so that the user has a way to get to the error messages behind the top one.

**Comment by grantfitzsimmons** [comment]
Great addition!
