### ISSUE TITLE
[a11y] Query Builder rounding causing aesthetic conflicts

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1623]
![image](https://user-images.githubusercontent.com/37256050/168859539-932b8ee8-69fa-4446-bbaf-e33647c9208f.png)

Firefox, Windows 10

**Comment by grantfitzsimmons** [comment]
<img width="289" alt="image" src="https://user-images.githubusercontent.com/37256050/188659310-15dcfbff-ab1b-477d-b355-ffdd35fb7b22.png">

**Comment by CarolineDenis** [comment]
@grantfitzsimmons I think I fixed this in one branch during another issue fix and should be good in production. Could you confirm?
