### ISSUE TITLE
[a11y] Typing in a QCBX and clicking add results in error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1625]
![image](https://user-images.githubusercontent.com/37256050/168860915-d6a46d1a-2357-4084-a5eb-c2ebcef46d9f.png)

Happened after I entered text into the Taxon field on the Determinations subview and clicked "Add".

db: `kufish`
Firefox, Windows 10

**Comment by maxxxxxdlp** [comment]
Fixed. The problem was that QCBX did not send the `countonly:false` field when running the query builder query
