### ISSUE TITLE
[a11y] Attempting to Clear Web Cache gives an unsaved warning

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1626]
![image](https://user-images.githubusercontent.com/37256050/168861195-891df561-f0ff-4eff-8db9-f2e39f4bfdb2.png)

Firefox, Windows 10

"another popup, are you sure you want to leave this page.   User has no choice!  No they dont want to leave and lose their data but if you click cancel then the user is back to the main error message.  Round trip to nowhere.   Click on Clear Cache, and a another dialog comes up and says Web Cache cleared, do you want to reload page?  Yes, reload page -- always goes back the splash page!    Can't leave this workflow path in there.  It slaps and frustrates the user, does nothing for them, an drops the off the cliff at the end anyway.   No way to treat your friends.   LOL!" - @beach53

**Comment by maxxxxxdlp** [comment]
Fixed in 01854d12 by replacing the save cache button with a checkbox
