### ISSUE TITLE
[a11y] When creating a new record in a set, page rapidly reloads if existing CO is added

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1627]
![firefox_Jah9ZOiYf4](https://user-images.githubusercontent.com/37256050/168861707-19ef81d3-6b8c-4cdd-b30d-94ea38186018.gif)

When creating a new record in a set, page rapidly reloads if existing CO is added. This GIF is not showing how bad it can sometimes appear, as it can reload the entire view under other circumstances.

Firefox, Windows 10

**Comment by grantfitzsimmons** [comment]
![firefox_SXfakro2E3](https://user-images.githubusercontent.com/37256050/168861980-646b9532-a56c-42d3-ad07-6a037bd063fa.gif)

Caught it on video for you!

**Comment by maxxxxxdlp** [comment]
Fixed in 5613e0fc
