### ISSUE TITLE
[a11y] Deleting 19-20 records in a set sends Specify back to the splash screen

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1628]
Open up a **Record Set**, start deleting from the front of the RS with the red minus symbol.   

After 19-20 record deletions the form crashes and specify goes back to the splash screen.  

This one is from the front of the RS starting with record # 1.

**Reported By:** @beach53 

Tested & confirmed by me

**Comment by maxxxxxdlp** [comment]
Should be fixed by 5613e0fc
