### ISSUE TITLE
[a11y] Change all use of "Abort" to "Stop"

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1631]
It should have said 'Stop' not 'abort (referring to the WB uploading or roll back prompt working button)

**Comment by maxxxxxdlp** [comment]
I believe this was taken from a Slack message: https://specifydev.slack.com/archives/C03F8G52ZQF/p1652806766576589
Don't think though it referred to renaming the button. It was about the dialog message being wrong
