### ISSUE TITLE
[a11y] Blank forms should not be saveable 

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1633]
There is no functional/workflow reason to create an agent record without a name.

**Requested By:** Jim Beach

**Comment by grantfitzsimmons** [comment]
https://github.com/specify/specify7/issues/199

Maybe this should be implemented. Theresa and Jim requested this change today again.

**Comment by maxxxxxdlp** [comment]
If the form has required fields, then a blank form won't be savable.
Fixing #199 would fix this issue for agent form, thus I would close this issue in favor of that one
