### ISSUE TITLE
[a11y] Pick list discrepancy between CE

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1636]
db: `rbge_herb`
user: `robyn`

[Current URL](https://a11y-2-2-2.test.specifysystems.org/specify/view/collectionobject/264/?recordsetid=40)
[Current URL for Edge](https://edge-2-5.test.specifysystems.org/specify/view/collectionobject/264/?recordsetid=40)

![image](https://user-images.githubusercontent.com/37256050/168872601-976c341a-027b-4da2-936b-2e3dfdd3a3e3.png)
![image](https://user-images.githubusercontent.com/37256050/168872619-e8e11762-d484-4cb1-b9b9-8fa871adf60d.png)

**Comment by maxxxxxdlp** [comment]
It filtered the results dow to all the items that start with "4 - Inner China, Korea and Taiwan" and there is only one.
It should have disabled filtering in cases when there is only one search result and it is already selected, but it did not do so because of a bug. Should be fixed now
