### ISSUE TITLE
[a11y] Division should not be a QCBX

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1637]
Division should not be a query combo box and should return to being a picklist

**Comment by maxxxxxdlp** [comment]
Why?

**Comment by grantfitzsimmons** [comment]
Have you encountered a situation where there are more than 5 divisions in a single database?

The ability to add a Division from a form is also absurd in a way, but it does not work - https://github.com/specify/specify7/issues/1615

**Comment by maxxxxxdlp** [comment]
Partially fixed by removing the "+" button from query combo boxes from some tables.
We can convert it to a pick list, but it is simpler to leave it as it is in this release.
If someone wants it to be a pick list, than they should explicitly define a pick list for that field.
