### ISSUE TITLE
Reports prompt appears when clicking Add Another (not saving)

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1645]
When you click to Add Another after you've already saved a record, the Reports prompt pops up, but it should only pop up when you save.  Since the record was already saved, it should not pop up as a result of the Generate Label On Save checkbox.

On Chrome in Colorado_paleo

**Comment by maxxxxxdlp** [comment]
Are you saying reports should only auto-run for new records?
Wouldn't it be confusing to have a "Run report on save" checkbox checked, but not working because you edited an existing record?
If no, I can easily disable that checkbox for non-new records
