### ISSUE TITLE
Error deleting from taxon tree

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1652]
**Describe the bug**
I get an error when trying to delete an unused taxon node in the tree

**To Reproduce**
1. Go to taxon tree
2. Click on unused node (no collection objects)
3. Click Edit and then delete

**Expected behavior**

**Screenshots**
![Capture](https://user-images.githubusercontent.com/7501989/169072273-b493de26-7d2a-4be7-83bb-556dc8394e74.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
This was likely a session timeout error or the server was restarting at the moment.

The bug is the fact that it does not show the correct error message. Fixed in f0ad1cddb
