### ISSUE TITLE
Unable to delete unused parent and children at once in the trees 

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1653]
**Describe the bug**
Trying to delete a parent and all its children that are all unused (no collection objects) is blocked

**To Reproduce**
1. Go to Ophidiidae genus in taxon tree
2. Click on 'edit' and then delete
3. See error

**Expected behavior**
You should be able to delete multiple nodes at once as long as the node and all of its children are unused

**Screenshots**
![Capture](https://user-images.githubusercontent.com/7501989/169073248-09055b5b-f18d-455d-b131-5c05563af0fe.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by grantfitzsimmons** [comment]
Here's a demonstration of the Storage tree deleting unreferenced children when a parent is removed:

https://github.com/specify/specify7/assets/37256050/6912f67d-99d0-4591-b581-620b7b4be3d6

**Comment by grantfitzsimmons** [comment]
This was requested by [MCNB on Trello](https://trello.com/c/qCYuQQHF/92-removing-branches-on-storage-taxon-tree-on-specify7)

> After regornatization, we did some changes on our Storage Taxon and now, we have few secondlevel (below “site” level) elements we want to remove. Problem is from specify7 we can’t do it if it has children, so that means going one by one by +10000 elements and delete them. (a merge wouldnt work here)
> 
> Is there any way to do that in specify 7?  Offcourse it can be done by sql script or remote code script but that’s not a good option.
> 
> Also, it can be done by specify6 so… Way is not possible in specify7????

**Comment by grantfitzsimmons** [comment]
From Heather Cole at AAFC on [Discourse](https://discourse.specifysoftware.org/t/various-tree-feature-requests-sp7/499/5?u=specify):

> I would like to be able to delete Parent Taxon nodes with all their children! The same way we can in S6. In S7, I seem to have to delete all the children (and their children) first. Not only time-consuming, but just really not feasible at all when your tree needs a lot of pruning…

Supported by Mark Pitblado at UBC, Heryk and Amelie at NRCan, and many others.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/various-tree-feature-requests-sp7/499/7

**Comment by realVinayak** [comment]
Looks like it was once supported in specify 7. See https://github.com/specify/specify7/issues/136. Need to revisit why it was removed

**Comment by grantfitzsimmons** [comment]
Requested by Becky at Brown University!

**Comment by grantfitzsimmons** [comment]
>Just need a migration updating the Taxon -> parent field to have CASCADE deletion behavior
>Everything else is handled
