### ISSUE TITLE
Move, merge, synonymize functionality not intuitive

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1654]
**Describe the bug**
These three operations are not intuitive given button messages and tooltip

**To Reproduce**
1. Go to taxon tree
2. Select node
3. Select Move
4. Button says "Move *** here" when I haven't selected where to move it yet.  However, the tooltip says "Select a new parent for *** and press the button"
5. When I select a new parent, the button turns grey and is active
6. If I select an invalid node, the button turns white again but still says "Move *** here"
7. See error

**Expected behavior**
I would expect

In #4 above I would expect the button to say "Select new parent for *** and Click here"
In #6 above I would expect the button (or at least the tooltip) to say "Invalid selection"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by grantfitzsimmons** [comment]
@acbentley Can you try this on the following branch:

https://freshfish-testability.test.specifysystems.org/specify/

and close this issue if you find it to be intuitive?

**Comment by acbentley** [comment]
Yes, those button messages are more intuitive than previous ones.  I am happy now.
