### ISSUE TITLE
[a11y] Trying to edit a picklist should open a new tab rather than exit the current instance

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1659]
Editing the picklist should be done in a new tab so I don't have to lose my progress when modifying the schema.

![image](https://user-images.githubusercontent.com/37256050/169119600-eed6034c-3034-4cca-bc13-ba6f578d74bb.png)

Can be circumvented with a middle-click or open in new tab. Should be default behavior

**Comment by maxxxxxdlp** [comment]
It was made this way because it is simpler, but we can revisit it in the future.
The problem is that if you create a new pick list or delete a pick lists, the schema config would need to have it's list of pick lists refreshed

**Comment by maxxxxxdlp** [comment]
Fixed on branch `xml-editor`

Now plus and pencil open dialogs for editing/adding pick lists

On any edits, the list of pick lists updates

Yet, if you want, you can right click on the plus/pencil to open it new tab instead

**Comment by chanulee1** [comment]
Able to edit/add pick lists in dialog.
