### ISSUE TITLE
Warn when opening a query that has fields without read access

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1661]
When opening a query that contains relationships to related tables to which the current user does not have read permissions, some sort of warning dialog should be shown.

The user should see a list of relationships they don't have read permission to as well as a one-click option to remove those fields from the query

See also #1318

**Comment by grantfitzsimmons** [comment]
This looks like more work than it's worth, what do you think?

**Comment by maxxxxxdlp** [comment]
It's a good practice assignment before we get to more interesting tasks

**Comment by maxxxxxdlp** [comment]
Also, this would become more useful once's shared queries mechanism is in place

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-6-release-announcement/1064/1
