### ISSUE TITLE
Add ability to merge record sets

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#1665]
Add ability to merge record sets

Suggested by @tlammer

**Comment by maxxxxxdlp** [comment]
From @grantfitzsimmons:

> In Specify 6, record sets can be merged together by dragging and dropping on top of each other. There is no equivalent option in Specify 7. 
>
> **Requested By:** Geneva
>
> Related to #3609

**Comment by grantfitzsimmons** [comment]
This was requested again by James C. Sagebiel at The University of Texas

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/combine-record-sets-in-specify-7/1972/2

**Comment by grantfitzsimmons** [comment]
> I frequently need to combine search results into a single record set.
> 
> For example, today, I was asked for a loan of 4 taxa from specific stratigraphic levels in 6 caves in central Texas.
> 
> The cave excavations are not uniform, so those require separate queries, especially given that caves have >10,000 specimens per cave, so scrolling through results is impractical.
> 
> I need to save record sets to produce loans, loan forms, labels to ship with specimens, new labels for the collection, etc.
> 
> Similarly, a lot of researchers study, for example, “large carnivores”, which is not a taxonomic group, so I would typically need to perform several queries, again, especially if they were only interested in certain strata, geographic areas, and anatomical parts.
> 
> Given that I am often searching for limited stratigraphy, anatomy, geography, and taxa, it is difficult (sometimes not possible) to create queries that limit results for those fields in a way that doesn’t inadvertently exclude records of interest.
> 
> Ideally, it would be great to combine queries such that the results are an intersection, difference or complement of those queries.

From Chris at The University of Texas ([Discourse](https://discourse.specifysoftware.org/t/combine-record-sets-in-specify-7/1972/3?u=grant))

**Comment by grantfitzsimmons** [comment]
Requested by Basel and Berlin
