### ISSUE TITLE
When you enter a taxon by hand, it assigns a guid

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#167]
This shouldn't be possible for taxon, geography, etc.

**Comment by benanhalt** [comment]
The GUIDs should be automatically set, but shouldn't be editable.

**Comment by benanhalt** [comment]
There is some question as to whether we should be generating these or if they should match some authority or something. Right now, the behavior of generating them is consistent with what Specify 6 is doing. That is, Specify 6 also assigns a new guid when Taxa are added.

**Comment by tlammer** [comment]
Specify 6 does not assign a guid when taxa are added.  It does not assign a guid when new geographies are added either.
