### ISSUE TITLE
Institutional Admin users don't get a role next to their name in the users list

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1672]
In the list of users, their roles are listed next to their names.  IA users don't have anything next to their names, leading to confusion.  Institutional Admin should be listed for those users.  For example, see newuser in the image below.
![image](https://user-images.githubusercontent.com/12532430/169416689-2da93a35-5ac4-432a-a75e-0d46480f6f5e.png)

**Comment by maxxxxxdlp** [comment]
The institution page shows users and whether they are admins
The collection page shows users and their roles
I didn't want to mix the two together
