### ISSUE TITLE
Attachment form not showing up

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1673]
**Describe the bug**
The form view for attachments is not showing up in Specify 7.  It appears that the control that allows you to switch between icon, grid and form view has been removed.  This does not allow me to enter metadata associated with attachments in Sp 7

**To Reproduce**
1. Go to a collection object form
2. Click on attachments
3. See error

**Expected behavior**

**Screenshots**
Specify 6 - ![Capture](https://user-images.githubusercontent.com/7501989/169546692-ca2c9187-0da2-4c9c-9056-d016c1b92f34.JPG)
Specify 7 - ![Capture2](https://user-images.githubusercontent.com/7501989/169546704-5156b0fe-db64-4169-ade7-3e6728bd26d0.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
> It appears that the control that allows you to switch between icon, grid and form view has been removed

It wasn't removed. It was never there to begin with.
This release added the ability to see and edit attachment metadata. To do so click on the `i` icon in the upper left corner of the attachment image.
The `i` button is also available next to every attachment in the attachments viewer

**Comment by acbentley** [comment]
Ah, OK, not intuitive to me.  Anyway, when I click on the i, I get the following window that does not show the file I selected and will not let me choose a file even though I have a file selected in the previous window.

![Capture3](https://user-images.githubusercontent.com/7501989/169548335-dcc38b2e-7741-4ab2-8447-56f75eeb87aa.JPG)

**Comment by maxxxxxdlp** [comment]
You can't select a file through this window. it is only for editing metadata.
To select a different file, delete this attachment (the `-` button) and add another one (the `+` button)
> Ah, OK, not intuitive to me
What would make it more intuitive? The control that allows you to switch between icon, grid and form view? It won't be trivial to add it, thus not for this release

**Comment by acbentley** [comment]
But I am editing the metadata for the file I just uploaded.  Surely that file information should show up in the resulting window?

I meant not intuitive for someone using Sp 6.  It will take some getting used to for those using both.
