### ISSUE TITLE
Error inputting date in Workbench

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1674]
I created a dataset in Shell Museum with catalog number, cataloged date, and fields from accession.
I put 01/01/2022 as the date and cataloged date got highlighted with an error on date format.  I tried 2022/01/01 and got the same error.  I tried 22/01/01 and got an error saying I needed to have a four digit date.

![image](https://user-images.githubusercontent.com/12532430/169559756-98ff1fa0-44d8-47ae-a4a2-df0914addc50.png)

![image](https://user-images.githubusercontent.com/12532430/169559893-36f8b272-bbef-4295-9f22-077a9b100d25.png)

**Comment by maxxxxxdlp** [comment]
@tlammer This is the date format in that database:

```
ui.formatting.scrdateformat=yyyy-MM-dd
```

`2020-01-02` validates successfully for me
