### ISSUE TITLE
Add New button to top of Query page

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1680]
Currently, the only way to add a New query is to go up to queries then click to add new.  It would be helpful if users could just click new from the query page instead.  It would save clicks.

**Comment by maxxxxxdlp** [comment]
Wouldn't that button be out of context though?
Everything in the query builder is for a given query only.
I don't think we violated the context in such way anywhere else either

**Comment by grantfitzsimmons** [comment]
Not planned
