### ISSUE TITLE
Move number of records into header for simple query results

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1681]
**Describe the bug**
Any chance we can move the number of records returned by the simple search into the header bar rather than have to open each one to see how many records are available?

**To Reproduce**
1. Go to Simple/Express search
2. Run a query
3. See error

**Expected behavior**
Easier to see summary of results returned rather than have to open each result set.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/7501989/169883833-abda5ad2-4eb5-47d2-a760-fb49b2eae6bc.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by grantfitzsimmons** [comment]
<img width="565" alt="image" src="https://user-images.githubusercontent.com/37256050/192672697-e9297919-25bb-49cb-97ba-0448430c6ef5.png">

The second heading is redundant now in my opinion. If you agree, I can open another issue for that. If you see a purpose, we can leave it as-is.
