### ISSUE TITLE
Adding data to COAttribute subform on CO form in RS does not activate SAVE button.

### ISSUE THREAD

**Issue by beach53** [specify/specify7#1683]
**Describe the bug**
Adding data to CO Attribute sub-form on CO form does not activate SAVE button.

**To Reproduce**
1. Go to Record Sets, get  a CO into it or select one
2. Click on editable COA field, enter data
4. See error  SAVE Button not activated

**Expected behavior**
Save button should activate to allow save

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]   Win 11 64
 - Browser [e.g. Chrome, Safari]  firefox
 - Specify 7 Version [e.g. 7.6.1]  77

**Reported By**
Name of your institution

**Additional context**

**Comment by beach53** [comment]
Activating the add button by editing some other field activates SAVE button but COA field data are not saved.

**Comment by maxxxxxdlp** [comment]
Same cause as #1682
