### ISSUE TITLE
Open query result on double click

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1684]
Suggested by @tlammer 

Make query results record open in the same tab on double-click.
Currently, this is possible by `Alt`+`Click` on the "new tab" icon

**Comment by maxxxxxdlp** [comment]
There are some difficulties with this:
Before emitting a double click event, the browser would emit a single click event twice.
Since a single click is supposed to open a new tab, which would prevent doing a double click, we would have to delay the opening of the new tab until some time has passed after the click, so as to make sure a second click is not coming.

(for reference: https://stackoverflow.com/a/60177326/8584605)

Alternatively, we can listen for double clicks on the row itself, but that creates another usability issue:
If you want to select text from a row (double-clicking can be used for text selection), you will accidentally trigger the link.

**Comment by grantfitzsimmons** [comment]
Closing this as not planned for now. @tlammer if you feel this is important, please reopen.
