### ISSUE TITLE
Add an indicator for unsaved changes

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1685]
It is hard to tell if there are unsaved changes until you actually try to navigate away from the page.
Consider adding a `*` to the page title or changing the page icon in some way whenever there are unsaved changes.

Also add a user pref in General -> Behavior -> Show unsaved changed indicator to disable this behavior (for screen readers)

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-6-release-announcement/1064/1
