### ISSUE TITLE
Error in rolling back workbench dataset

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1687]
**Describe the bug**
When trying to roll back a dataset I get an error message but then it says that it rolled back successfully.  Thereafter dataset is still in read-only mode

**To Reproduce**
1. Go to KUFish database
2. Click on Workbench and open Tulsa Series 4 dataset
3. Click on Rollback
4. See error message
5. See error

**Expected behavior**
Should not see rollback successful message in this scenario

**Screenshots**
![Capture](https://user-images.githubusercontent.com/7501989/170065375-bf329cad-111e-40ee-9195-719e5959a65f.JPG)
![Capture2](https://user-images.githubusercontent.com/7501989/170065389-c74762ef-887f-48b8-a0e7-2efd57a30ae2.JPG)
![Capture3](https://user-images.githubusercontent.com/7501989/170065403-b1398a9d-e68c-4a90-b88b-dd98df636f1b.JPG)
![Capture4](https://user-images.githubusercontent.com/7501989/170065420-0d86d5f7-e85e-4a01-9b68-08726978194f.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by grantfitzsimmons** [comment]
@bronwyncombs @melton-jason Can you try to recreate this sometime soon and close if it cannot be recreated?

**Comment by carlosmbe** [comment]
Couldn't recreate. Additional details would be greatly appreciated. Otherwise, uploading the Data Set and rolling it back didn't do anything strange 

https://github.com/specify/specify7/assets/53784701/a07d0f74-f7cc-4ed3-9ab6-e6e31708247e

**Comment by grantfitzsimmons** [comment]
Thanks @carlosmbe !
