### ISSUE TITLE
Longitude Directional Character inconsistency

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#169]
I'm not completely sure if this is a bug or if it's how it's supposed to work, but when in a database on Specify 7, it seems to ignore the Directional Character preference of Longitude from Specify 6. For example, if you have your preference set to automatically appear as "W" whenever you enter longitude data on Sp6, entering the same number in the longitude field on Sp7 will appear as "E", unless you put a "-" in front of the number.

**Comment by benanhalt** [comment]
If you mean the "Default to longitude West" preference in Sp6, that just controls whether the control starts out as W or E before you change it.

In Sp7 you can put  W after the value to or enter the value as negative for longitudes in the western hemisphere.

**Comment by tlammer** [comment]
I think the issue is that people are used to it defaulting to W without having to indicate it.  They would like Specify to do it automatically.  As it is something you can do in Specify 6, they would like to continue the functionality in 7

**Comment by benanhalt** [comment]
Extends #159
