### ISSUE TITLE
Enhance "Record Set Created" dialog layout

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1695]
Suggested by @tlammer 

When creating a record set from query results, this dialog pops up:
<img width="1800" alt="Screen Shot 2022-05-26 at 21 38 18" src="https://user-images.githubusercontent.com/40512816/170617791-c9cec149-9515-4265-b2c2-74123a5fef2c.png">

It needs to be improved.
Instead of asking user whether to open the record set, display the record set name and table icon as a link. Then, the user has a choice of closing the dialog, clicking on the link, or opening the link in new tab

**Comment by grantfitzsimmons** [comment]
Maybe the interface should include the Open button still in case the user does not understand that the name and icon is interactable.

**Comment by maxxxxxdlp** [comment]
Fixed

**Comment by grantfitzsimmons** [comment]
<img width="539" alt="image" src="https://user-images.githubusercontent.com/37256050/178287200-6758c2f7-d2c7-4cde-b92f-47c2823f3205.png">

@beach53 Max can remove the "Open" button- though users might not understand that the record set name is a link.

**Comment by maxxxxxdlp** [comment]
Fixed by removing the button
