### ISSUE TITLE
Remarks field renders as huge in grid format when there is a lot of text

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1700]
added a preparation to a co and put a lot of text in the remarks field.  when the preps were shown in grid format, the remarks field automatically rendered as very large, taking up the entire screen.  When I made it smaller, the window got smaller but the space remained the same as seen in the image below.  It would be better if when in grid format, the amount of space taken up is automatically limited and the user can expand if desired.
![image](https://user-images.githubusercontent.com/12532430/170762277-bf80708a-5a70-465b-be76-7c856588cc8a.png)

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/176775967-a3b8f5e2-c168-4921-8b1a-216ebbec267a.png)
