### ISSUE TITLE
Uniqueness rules not checked by front end when cloning a record.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#1706]
**To Reproduce**
1. View an existing CO record with some catalog number.
2. Click on 'Clone'
3. A new CO form is presented with the same catalog number.
4. Click "Save"
5. A server error occurs due to the uniqueness constraint on catalog number.

**Expected behavior**
The catalog number should be flagged as a duplicate before saving as it is when it is entered manually.

**Comment by maxxxxxdlp** [comment]
Would be fixed by fixing https://github.com/specify/specify7/issues/124
Alternatively, we could run business rules on all fields before saving, but that would slow down saving too much

**Comment by tlammer** [comment]
currently, I dont' think we need business rules for all fields.  We only need it for unique fields; catalog number, guid, uniqueIdenfier fields.
Eventually we will want a user interface to say which fields to carry forward, but even then, the fields that must have unique values should be excluded

**Comment by maxxxxxdlp** [comment]
Duplicat of #124
