### ISSUE TITLE
Allow adding multiple records to a record set via a query

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#1708]
**To Reproduce**

1. Open a record set.
2. Click on + to add an item
3. Choose "Query Builder" from the dialog
4. Create a query that returns multiple items
5. Click the select box to choose an item
6. The item is immediately added to RS and the dialog closes

**Expected behavior**
The select box should be selected and the query results should remain present allowing more items to be selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/287254/171282600-5013e163-2725-46ce-880e-da13092483e8.png)

**Comment by maxxxxxdlp** [comment]
This is probably a feature request.
You can only select one record at the moment because the search dialog is also used in Query combo boxes, which allow only one record to be selected.

**Comment by benanhalt** [comment]
The presence of the select boxes produces a bait and switch effect by making it seem like more than one can be selected.

**Comment by maxxxxxdlp** [comment]
Fixed. Now you can select multiple. Applies to all places where the search dialog appears and it makes sense to add multiple records:
- SubViews for -to-manys
- FormTables for -to-manys
- Adding Record Set items
- Adding users to a security role

**Comment by maxxxxxdlp** [comment]
Yes!

**Comment by chanulee1** [comment]
In the query builder for adding new records to the record set, the results do not appear and cannot select records to be added. It just shows the number of records, which is constant regardless of how many items the query should return.

![image](https://user-images.githubusercontent.com/103299204/192828345-1f724d44-930b-492c-be8d-3e54683796cb.png)

**Comment by grantfitzsimmons** [comment]
> In the query builder for adding new records to the record set, the results do not appear and cannot select records to be added. It just shows the number of records, which is constant regardless of how many items the query should return.

I have an issue for this, https://github.com/specify/specify7/issues/2224

**Comment by grantfitzsimmons** [comment]
It doesn't work

**Comment by grantfitzsimmons** [comment]
It works!
