### ISSUE TITLE
coordinates not read correctly when entered in Degrees Decimal Minutes

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#171]
in Specify 7, enter coordinates degrees decimal minutes format (44 23.9, 100 23.5).  When the Specify 6 instance reads it, it reads the "23.9" and "23.5" as directions and they appear where the N, S, E, or W should appear

**Comment by garrettgirard** [comment]
This issue also causes lat/long fields in SpiReport to print as "null"

**Comment by benanhalt** [comment]
I think the report part of this is fixed in 1555fbcfdedbaa5edebfbe298f906c7c4b8deb41

**Comment by maxxxxxdlp** [comment]
Seems to be fixed:

<img width="1056" alt="Screen Shot 2022-07-10 at 21 46 48" src="https://user-images.githubusercontent.com/40512816/178179417-c7051534-31b7-461e-8ea3-571248bd2610.png">
