### ISSUE TITLE
Integrate Query Builder with attachments

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#1711]
When querying on a table that has attachments, display a button to see all attachments from records returned by the query.

Need to take a closer look at how this works in sp6

Suggested by @tlammer

**Comment by maxxxxxdlp** [comment]
You can see attachments for a single record at a time by pressing the "Browse In Forms" button.

To see attachments for all record together would probably require a new back-end endpoint

**Comment by maxxxxxdlp** [comment]
Similarly, need to support this for the express search feature. (Sp6 has that)

Since express search is using query builder API, implementing it in one place should make the feature available in both places

**Comment by CarolineDenis** [comment]
https://github.com/specify/specify7/pull/3363

**Comment by maxxxxxdlp** [comment]
Indeed it might. @grantfitzsimmons can you check if that solution is satisfactory, and thus if this issue can be closed once that PR is merged?

**Comment by grantfitzsimmons** [comment]
This is satisfactory for me, unless a user asks for a more sophisticated implementation.

**Comment by maxpatiiuk** [comment]
@CarolineDenis good job on implementing the attachment viewer in a way that resolved the use cases both in the record set and in the form!
