### ISSUE TITLE
Field value disappears when adding new pick list

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1712]
Discovered in VIMSfish database
I filled out the locality form and in the drainage pick list, I added a new value "AAtest".  When I click save, the drainage field is empty and the value has not been added to the pick list.
The pick list is NOT read only and allows for a lot more values than are in the list and the value I added was definitely new (I checked before adding it)
the console says
picklist.tsx:86 Duplicate picklist entries found (2) [Array(186), LocalityDetailResource]
(anonymous) @ picklist.tsx:86
Oi @ react-dom.production.min.js:262
e.unstable_runWithPriority @ scheduler.production.min.js:18
HA @ react-dom.production.min.js:122
Ri @ react-dom.production.min.js:261
bi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
HA @ react-dom.production.min.js:122
WA @ react-dom.production.min.js:123
VA @ react-dom.production.min.js:122
di @ react-dom.production.min.js:237
Da @ react-dom.production.min.js:170
(anonymous) @ hooks.tsx:234
Promise.then (async)
(anonymous) @ hooks.tsx:233
Oi @ react-dom.production.min.js:262
e.unstable_runWithPriority @ scheduler.production.min.js:18
HA @ react-dom.production.min.js:122
Ri @ react-dom.production.min.js:261
bi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
HA @ react-dom.production.min.js:122
WA @ react-dom.production.min.js:123
VA @ react-dom.production.min.js:122
di @ react-dom.production.min.js:237
Da @ react-dom.production.min.js:170
(anonymous) @ hooks.tsx:234
Promise.then (async)
(anonymous) @ hooks.tsx:233
Oi @ react-dom.production.min.js:262
e.unstable_runWithPriority @ scheduler.production.min.js:18
HA @ react-dom.production.min.js:122
Ri @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
P @ scheduler.production.min.js:16
U.port1.onmessage @ scheduler.production.min.js:12

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/176777692-36efa2df-284e-420d-a21a-a216d6a1d4b8.png)

As you can see the picklist is not read-only

![chrome_HAvszjFqFa](https://user-images.githubusercontent.com/37256050/176777750-85f4deab-edb8-431c-ac5f-0658ad7d72cb.gif)

I cannot add any value to this field.

```
            <rows>
                <row>
                    <cell type="label" labelfor="wb"/>
                    <cell type="field" id="wb" name="waterBody" uitype="combobox"/>
                    <cell type="label" labelfor="t1"/>
                    <cell type="field" id="t1" name="text1" uitype="combobox"/>
                    <cell type="label" labelfor="dra"/>
                    <cell type="field" id="dra" name="drainage" uitype="combobox"/>
                </row>
```

The size limit is 50 yet there is also 59 items in the list...

This should be investigated!

db: `vimsfish_40`
user: `spadmin`
collection: `Ichthyology`

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons in the new release, to add a new value to a picklist, you have to explicitly select the `Add` option from the picklist results (it would be the last option at the very bottom).

However, the option won't be there if the picklist has more items than the limit. Thus if you want to add more items, either increase the limit or delete other items
