### ISSUE TITLE
Add Spatial search capability to query

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1713]
requested by SAIAB
They would like to be able to identify an area on a map to search.  They understand they can use the coordinates in the search but it becomes clunky and difficult to identify the points needed.

From Willem:
In the world of GIS we are now completely spoilt by Google imagery that is available at no more than four clicks. Compared to 20 years ago, that is a dream come true. My dream is that we will have the same capability in Specify, and a selection tool to drag rectangles or circles or polygons of any shape around the points, to select them spatially. I know that this is a big ask, because Specify is not a GIS. The Google Earth plugin in Specify is great, but we need something that enables you to do the query in the opposite direction (instead of selecting on the basis of values in the database and creating a spatial output, we want to select on the basis of spatial values and get the corresponding database records).

 

I wonder if there is technology that you can just plug into Specify?

 

Here you can see how I have had to first export the data from the Specify database and then import the data into QGIS. But this requires expertise beyond most people’s daily job requirements

 

cid:image001.png@01D87602.2D94AC80

 

 

GBIF has the functionality that I describe above, but unfortunately their base maps are not detailed enough to be useful. Even if they were, one would first have to publish a new version to GBIF before being able to do a spatial search (and that is a significant task).

**Comment by maxxxxxdlp** [comment]
This sounds cool and won't be hard to do!
A polygon is just 2 coordinates (4 numbers total)
The front-end can easily translate that to a filter on latitude1 and longitude1 columns without requiring any back-end customizations.
This would work for polygons only though (not circles or arbitrary shapes). And only one polygon per query, until we add ability to run OR queries across different fields.

**Comment by tlammer** [comment]
I think one polygon per query is a reasonable restriction for the first iteration.  It would look pretty impressive as well

**Comment by benanhalt** [comment]
Um... Any polygon other than a rectangle requires more than two coordinate pairs.

**Comment by maxxxxxdlp** [comment]
Can you specify a polygon of more than two points on the locality form?
I though all locality coordinates are points, lines and rectangles with optional error radius?
Neither can we specify rectangles that are not aligned with the grid

**Comment by benanhalt** [comment]
I think the request is to be able to draw a polygon and have the query return results from within that area. Maybe selecting a grid aligned rectangle is good enough, and it is possible without GIS functions b/c you can formulate the query in terms of numeric comparisons on the lat and long fields. But even in that case you have to be careful because there are literal edge cases. Namely the 180 degree longitude line and the poles.

**Comment by maxxxxxdlp** [comment]
Implemented with the following limitations:
- Spatial query searches on latitude1 and longitude1 columns only
- You can only select a polygon area
- You can only select a single area
- The polygon's sides must be parallel to the equator and the prime meridian

Despite all of this, the feature is still quite capable.

To activate it, add a latitude1 or longitude1 column to the query builder and press on the new pin button (`📍`)

**Comment by grantfitzsimmons** [comment]
Please create additional issues about individual problems with this implementation. [The documentation for using these queries will be available on Discourse.](https://discourse.specifysoftware.org/t/how-to-use-spatial-search-in-a-query/776)

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/how-to-use-spatial-search-in-a-query/776/1
