### ISSUE TITLE
Nucleotide sequence fields not calculating numbers of each base type

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1718]
In Specify 6, the user can paste or type a genomic sequence into the gene sequence field and the Total Residues, Comp A, Comp C, Comp G, Comp T, and Ambiguous fields all auto calculate how many of each are in the gene sequence.
7 doesn't calculate or let the user type in the field (which it shouldn't).

**Comment by maxxxxxdlp** [comment]
Duplicate of #676
