### ISSUE TITLE
Query not panning down to results

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1719]
discovered in KUBirds
I created a locality query and added locality name with the criteria contains lawrence and geodeticdatum.  I clicked query and the screen blipped but didn't seem to change.
There were results but the window didn't pan down to them

https://user-images.githubusercontent.com/12532430/171752492-10046ffa-cb72-450d-b8c9-29a4da7b20fd.mp4

**Comment by maxxxxxdlp** [comment]
Seems to happen in Chromium on Windows only and only if the "Sticky Scroll Bar" option in user preferences is turned on.
I would make that option turned off by default for now, but would return after release to explore the cause futher

**Comment by CarolineDenis** [comment]
@maxxxxxdlp  any new insights about this?

**Comment by maxxxxxdlp** [comment]
We didn't fix the bug yet (unless it was fixed by Chrome), so the feature remains disabled by default

**Comment by emenslin** [comment]
Fixed
