### ISSUE TITLE
Cannot sort on a table header for a column pulling data from a related table

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#1730]
When the formTable column refers to a field in a related table, the record sorting by clicking on the column header does not work.

For example, this happens in the Collectors form table, as columns are from the related table, Agent.

Same probably also happens for SubViews and SubView buttons when the `sortField` parameter is specified

**Comment by grantfitzsimmons** [comment]
**Original Title:** FormTable sort on field from related table not working

Changed so this issue can be found when searched for average users

**Comment by maxxxxxdlp** [comment]
> Changed so this issue can be found when searched for average users

write an AI-based plugin for that! I heard that's trendy nowadays 😂

**Comment by emenslin** [comment]
Fixed
