### ISSUE TITLE
Can't add New record to record set without cloning record before

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1731]
When creating a new record set by going to record sets -> New, you start on a new record.  But after that, you can't add another record without cloning the record before or searching for an existing one.

**Comment by maxxxxxdlp** [comment]
This would be fixed by adding an option to configure or disable carry over (https://github.com/specify/specify7/issues/1330)
Or do you want a separate button for adding a record without carryover?

**Comment by maxxxxxdlp** [comment]
Fixed in 138ee908

**Comment by grantfitzsimmons** [comment]
A little confusing- but implementation works. Add Another button in the bottom right is the solution. Admittedly, a **+** icon to me indicates create new. Maybe a search icon should allow you to add a record to the record set and the plus should create a new one? Something to think about for the future.

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons I should have been more explicit when I added that `Fixed` comment

Forms now have both `Add another` and `Clone` buttons. The former one creates a new record, the later does so with carry over.

The `+` button at the top is for adding records, not creating
