### ISSUE TITLE
Delete row in Workbench mapping when not matched to a spreadsheet column

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1732]
Reported by edinburgh
When creating a workbench mapping from scratch, there is no way to entirely remove a line added.  You can remove the mapping by clicking the x but it doesn't remove the line, which can quickly lead to clutter.
It would be nice if when a line represents a blank space rather than a spreadsheet column, if the line would disappear when you click the x, so where the line then says "New Column x" it would just get deleted.
![image](https://user-images.githubusercontent.com/12532430/172221334-1369741f-b9c7-4c3a-ba91-96a776469cab.png)

**Comment by grantfitzsimmons** [comment]
Should be fixed by #3602 once it is finished.
