### ISSUE TITLE
Close button does not work when searching for items to add to a record set

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1733]
click on a record set
Click the add button
Click query builder
Then decide I don’t want to use the query builder after all, and click close – the close button doesn’t work.  I’m stuck in the query builder. 
![image](https://user-images.githubusercontent.com/12532430/172224557-f1802401-e47d-4d89-add5-a39d5b20bb5c.png)

**Comment by maxxxxxdlp** [comment]
Fixed. And added a thing to prevent this type of bug in the future
