### ISSUE TITLE
Allowed to choose synonymized parent in Taxon Parent query combobox

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1735]
discovered by rbge and confirmed to still be present in a11y
When adding a taxon through the forms, you are allowed to choose a synonymized parent.  The user is not notified that there is an issue until they click save. The error mentions the issue is with trying to add a child to synonymized parent x but doesn't say the synonymized aspect is the problem.

**Comment by benanhalt** [comment]
Specify 7 now looks for a remote pref to override the business rule that prevents children from being added to synonymized nodes. The remote pref of the form `sp7.allow_adding_child_to_synonymized_parent.TREENAME=true` where TREENAME is Taxon, Geography, etc.

**Comment by grantfitzsimmons** [comment]
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/37256050/192035301-ee1d506d-8cef-4616-8751-02a5cc8ce808.png">

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/37256050/192035380-bfd29d19-41fd-436d-a251-6aaa1bb5d9b8.png">

[Tree Location](https://willemcatno-issue-2185.test.specifysystems.org/specify/tree/taxon/?conformation=%7E%7E22554%7E22556%7E33210-%7E33214%7E33208%7E33471%7E33239%7E33427%7E33553----%7E33473%7E33273%7E33403%7E33535---------)

This is straight from the source code. Do I need to restart the server to fix this? Has this been tested?

**Comment by maxxxxxdlp** [comment]
Looks like this is implemented on the back-end, but front-end support has not been added

**Comment by grantfitzsimmons** [comment]
RBGE has been requesting this functionality and would really appreciate its addition.

**Comment by maxxxxxdlp** [comment]
Actually, this issue is for query combo box, which was fixed in 7.7.1
For the Tree Viewer issue, we have https://github.com/specify/specify7/issues/751
@grantfitzsimmons I will repost your message there
