### ISSUE TITLE
Unexpected results from express search

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1736]
Discovered by @beach53 in Shell Museum's database

Screenshots of the same search from Specify 6 (expected results) and Specify 7 (incorrect results):

![image](https://user-images.githubusercontent.com/40512816/172285843-28644132-7199-4406-a8d5-f0955e14aa0c.png)

![image](https://user-images.githubusercontent.com/40512816/172285829-f5c896cd-1c99-4d1a-b6cf-8c432c92d2a8.png)

**Comment by benanhalt** [comment]
It's due to a bad interaction between the way express search queries are generated and the "implicit or" mechanism that is added in this release to support OR'd fields in the query builder. Fix to be committed momentarily.
