### ISSUE TITLE
Lithostrat adding child in KUInvp causes error

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#174]
I'm not sure why this is happening, but whenever I try to add a child to the "tan" member node in the lithostrat tree of the KUInvp database, I get an error. (For replicating, the tree order is Earth -> Alta Formation -> tan)

Error message:
ValueError at /api/specify/lithostrat/
Cannot use None as a query value

NOTE: This particular node is one that is referenced in a paleo context for a Collection Object, which means it can't be deleted. Not sure if this has anything to do with the problem.

**Comment by benanhalt** [comment]
The exception is occuring because the parent node "tan" has no node numbering.
