### ISSUE TITLE
Preferences  - general font family field not showing full list

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1742]
**Describe the bug**
In the preferences/general/font family, the font list only shows variations of Arial and not the full list that is displayed in the corresponding field in Forms in preferences

**To Reproduce**
1. Go to Preferences/general/font family
2. Click on down arrow
3. See error

**Expected behavior**
Should show full font list as in forms/font family

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
It was only showing items that started with the current value (`Arial`).
Fixed by disabling filtering of items once an item is selected
