### ISSUE TITLE
Table 'SpDataset' not created upon upgrade from 7.5.0/6.8.00

### ISSUE THREAD

**Issue by FedorSteeman** [specify/specify7#1743]
After a successful upgrade of both Sp6 and Sp7 we experience some features throwing an error because the table 'spdataset' appears to be missing from the database.  This is apparent in the following use cases: 

In Specify7
1. Click username to summon User Tools popup
2. Click 'Manage Users'
3. Select username of interest
4. Error message is presented: ![image](https://user-images.githubusercontent.com/10909008/172791233-1ac81a8f-2615-45ef-8555-8219cd000823.png)

It appears that the following API call triggers the server error (500): 
https://specify-naturama.science.ku.dk/api/delete_blockers/specifyuser/2/

When going through the logs, I could find the following error line: 

> django.db.utils.ProgrammingError: (1146, "Table 'Naturama.spdataset' doesn't exist")

**System**
 - OS: Windows 10
 - Browser: Firefox
 - Specify7 Version 7.6.1
 - Server: RHEL 7.9

**Reported By**
Natural History Museum of Denmark reporting for Naturama, Svendborg, Denmark. 

**Additional context**
Oddly enough, it's possible to create a dataset in Specify6's Workbench and save it. It's unclear what table this dataset is otherwise saved in. When trying to access WorkBench in Specify7, the windows remains stuck on the loading screen. Looking behind the scenes, the same error message appears to be involved. 

 - Specify6 Version 6.8.01

![image](https://user-images.githubusercontent.com/10909008/172792867-627629ea-32bd-4317-aeb9-4a44cd4069c3.png)

![image](https://user-images.githubusercontent.com/10909008/172793158-e35f68c1-3b0d-4293-b0c1-37bfe0795c39.png)

**Comment by FedorSteeman** [comment]
I hacked a solution by directly adding the table to the database using following SQL script, but this is not optimal: 

[CreateSpDataset.sql.txt](https://github.com/specify/specify7/files/8868790/CreateSpDataset.sql.txt)

**Comment by FedorSteeman** [comment]
I just realized simply running the django migration command in the specify7 folder ensures that all models are created into the database. I just assumed that would be part of the compilation process run with 'make' 

`python manage.py migrate`

**Comment by benanhalt** [comment]
Hmm. It seems that the migration step got lost out of the main build at some point.

**Comment by FedorSteeman** [comment]
Note: Even after upgrading the database using the Specify6 wizard and manually running the django migrations, I noticed this warning in the logs: 

> [wsgi:error] [pid 22516] [10/Jun/2022 03:55:22] [WARNING] [specifyweb.specify.load_datamodel:249] missing table or relationship setting dependent field: Deaccession.deaccessionpreparations

**Comment by maxxxxxdlp** [comment]
@FedorSteeman You can safely ignore that warning. See more: https://github.com/specify/specify7/issues/1031

**Comment by FedorSteeman** [comment]
> @FedorSteeman You can safely ignore that warning. See more: #1031

Though yet with one of our database I get this blocking server error when attempting to restart: 

> AssertionError: Expected relationship for Deaccession.deaccessionpreparations, got None, in <SpecifyTable: Deaccession>

**Comment by FedorSteeman** [comment]
@maxxxxxdlp  And yet I got the following error when I wanted to look up a specific specimen: 

> ProgrammingError at /api/delete_blockers/collectionobject/75753/
> (1146, "Table 'spsandbox.deaccessionpreparation' doesn't exist")

**Comment by benanhalt** [comment]
Can you confirm that this is Specify 7.6.1 and that using Specify 6.8.0 as its Specify 6 reference? The /context/system_info.json endpoint will provide this information. It's also available by clicking on the "Specify 7" logo on the bottom right of the welcome screen.

**Comment by FedorSteeman** [comment]
Bug has disappeared.
