### ISSUE TITLE
Add a DATABASE_OPTIONS setting.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#1753]
Django supports passing extra options to the database client library via a configuration setting. We can add it to the Specify settings file so that it gets passed through to Django. This allows configuring things like SSL connections to MySQL.

**Comment by benanhalt** [comment]
Added in c0ac53d831024a56672c20ae309affb48cb2850c

**Comment by maxxxxxdlp** [comment]
This is good to know.
I am afraid that your message would get lost, so I reposted it here - https://github.com/specify/specify7/wiki/Docker-Workflow-for-Development
