### ISSUE TITLE
Clone Button should not clone Attachments

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1754]
Currently, when I click the clone button, it clones the record including attachments.  Attachments should not get cloned as they are almost always object specific.  It may be good to have the choice to include it or not when we add a UI for which fields to clone as Collecting Information attachments may carry forward, but for now, they should not be included.

**Comment by maxxxxxdlp** [comment]
It doesn't actually create a duplicate attachment file.
It duplicates the metadata, but the new attachment record is pointing to the same attachment file on the asset server.

@benanhalt Is there a problem with that from the technical standpoint? If they delete an attachment record, would it delete the file too, and leave the original attachment record referring to a non-existed file?

@tlammer There is no support at the moment for attachment metadata to exist without an associated attachment file. Would you rather I remove the Clone button for the Attachment records for this release?

**Comment by benanhalt** [comment]
Yeah, it is kind of assumed that each Attachment record points to a unique file. If we were going to allow sharing attachments it would probably make more sense to allow multiple CollectionObjectAttachment records point to the same Attachment record. Other *Attachment tables too.

**Comment by benanhalt** [comment]
Really should probably think of the Attachment records as "asset" records that represent the asset files. Really the attachmentLocation field should contain unique values. A given file shouldn't have multiple representations in the database.
