### ISSUE TITLE
Show query results before totalCount is fetched

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1758]
Currently, the query results are not displayed until the total count is fetched.
As @benanhalt mentioned, the total count might take a long time to fetch in cases when query matches many records.
The query results component needs total count to be fetched before rendering.
Need to modify the query results component to allow for delayed initialization of the `totalCount` prop, which would improve perceived performance when running large queries.

**Comment by grantfitzsimmons** [comment]
How can I verify this change?

**Comment by maxxxxxdlp** [comment]
Run a query that returns a TON of records.
The query results should become visible, even while `Count` still says `Loading...`
