### ISSUE TITLE
Can't delete Recordsets

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#176]
When trying to delete any recordset, you aren't able to, and you get this message "The resource cannot be deleted because it is referenced through the following fields: Recordsetitem.recordset", which shouldn't be happening. Theresa said it has something to do with there being two tables for recordset, but they're being deleted in the wrong order. The first table, the record set item table, should be deleted before the second table, the record set table. However, there is an ordering issue and it's happening the other way around, which is preventing recordsets from being deleted.

**Comment by benanhalt** [comment]
Record set items shouldn't be made dependent because then they all get fetched when a recordset is loaded.
