### ISSUE TITLE
If a user doesn't have permissions to Query, they shouldn't be able to get into query

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1765]
I created a user that did not have query privileges, but was able to click query, select to create a new query, and add fields to the query before it became apparent that I could not actually run the query. 
Query should have never been an option in the first place if I didn't have any privileges to it.

**Comment by maxxxxxdlp** [comment]
If your user has read access to all tables or has `Tools > Query Builder > [READ]` access, they have access to open Queries.
Remove those, and Query Builder would disappear from the top menu.
