### ISSUE TITLE
Get a message indicating don't have permission that I have

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1767]
I tried changing my user's username and when i clicked to save the record, I got the following dialog.  It looks like I don't have permission to update Agents, which my user has
![image](https://user-images.githubusercontent.com/12532430/175131972-8b180f80-5e8e-4dc9-a95a-2b8e58f209c7.png)

**Comment by maxxxxxdlp** [comment]
Fixed:

- Updated permission denied dialog to display the full resource path:
  <img width="789" alt="Screen Shot 2022-06-22 at 20 31 05" src="https://user-images.githubusercontent.com/40512816/175188158-8efad079-3936-4a0e-ae1e-e6200b530f4d.png">

- Made `Agent` query combo box read-only if the user does not have permission to assign agents, which will prevent this error message from coming up in the first place
