### ISSUE TITLE
User created pick list only appears after logging back in

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1770]
User created pick list only appears after logging back in. Exactly as it sounds. After creating a new pick list, it only populates the Field Format Schema Config pick list after logging out and back in again.

**Comment by maxxxxxdlp** [comment]
Unable to replicate it. The pick list appeared in the list after a page refresh:

[Screen Recording 2022-07-06 at 17.34.11.mov.zip](https://github.com/specify/specify7/files/9058985/Screen.Recording.2022-07-06.at.17.34.11.mov.zip)

Please try again. Or send a video recording

**Comment by grantfitzsimmons** [comment]
Unable to replicate now. Seems to be resolved!
