### ISSUE TITLE
Users can modify system tables

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1772]
![image](https://user-images.githubusercontent.com/37256050/175989866-0ebeb94d-5fa9-4ef7-83d1-5db808b83719.png)

Result of cloning or adding a second entry into the Sp Version table:

![image](https://user-images.githubusercontent.com/37256050/175989854-8562e66a-27b3-4ac2-9b33-c471918799d3.png)

Modifying, adding, or deleting an entry in this table (spversion) actually corrupts the database.

**Comment by maxxxxxdlp** [comment]
Looking at the error stack trace from your screenshot, I see that this was the cause: "an error occurred displaying the error message" 😄 

Unable to replicate

Tested in KU Fish on https://a11y-2-2-2-2.test.specifysystems.org/specify/

Deleting the last SpVersion record in my local database and reloading the page did not cause errors either.

https://user-images.githubusercontent.com/40512816/176066288-4aa78944-f74d-40bb-a2c3-d0546c0a4aae.mov
