### ISSUE TITLE
Make tree tiles interactive

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1776]
Suggested by @beach53 

Clicking on a tile should run a query on CO records associated with that Taxon, thus allowing you to look through them in query results/form view.

**Comment by grantfitzsimmons** [comment]
<img width="785" alt="image" src="https://user-images.githubusercontent.com/37256050/192422548-d4eef632-7806-462d-ae42-bc653f120a4b.png">

You can now click on a taxon tile to automatically create and run a query for all CO records associated with a taxon
