### ISSUE TITLE
Saving a WB mapping gives an unsaved warning

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1781]
<img width="1461" alt="Screen Shot 2022-06-29 at 11 16 37 AM" src="https://user-images.githubusercontent.com/37256050/176485743-23ef598b-cc47-4a8d-a340-a722f7ed6e3a.png">

<img width="713" alt="image" src="https://user-images.githubusercontent.com/37256050/176485890-47ad7020-49d5-450f-889c-4aa5776da7dc.png">

After assigning an existing mapping to a new import, the WorkBench planner begins to save then shows a warning as if it is not saved. After clicking Leave, it is actually saved.

**Comment by maxxxxxdlp** [comment]
Unable to replicate. Can you post a video recording of this bug happening?

**Comment by maxxxxxdlp** [comment]
Also, even if it did happen in the past, it might not happen anymore on `testability` as the routing system has been rewritten

**Comment by grantfitzsimmons** [comment]
Cannot recreate on `edge` nor `testability`.
