### ISSUE TITLE
Broken form definition gives spinner

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1784]
![msedge_zao0BDhdkh](https://user-images.githubusercontent.com/37256050/176721177-af309d59-5da8-42c6-addb-ceeaa7528127.gif)

If the form definition is broken, it should autogenerate a form based on unhidden fields.

[Broken form definition is available here](https://drive.google.com/open?id=18C60TWCyHHf8MzmvugU3MALEQOIQSgCX&authuser=grant%40specifysoftware.org&usp=drive_fs)

Was on db: `newmexico_july22` but this is in active development

**Comment by maxxxxxdlp** [comment]
Same error message as #1779. Same cause. Closing as duplicate
