### ISSUE TITLE
Adding too much text in a field description gives an error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1785]
<img width="748" alt="image" src="https://user-images.githubusercontent.com/37256050/176734708-8670a7df-298d-4241-a3bd-8ea5dcd1d9f7.png">

I added too much text- no warning or character limit was displayed.

**Comment by maxxxxxdlp** [comment]
Fixed. The database limit is 255, and the front-end would enforce that now.

Increasing that limit would require a schema change, and would be very expensive in terms of storage as there are thousands of records in that table (one for each table/field name/description in every language)

The field usage notes aren't really supposed to be that long anyway. If you need something longer, you can put it as text on the form.
