### ISSUE TITLE
Attempting to create a new user causes an error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1786]
![image](https://user-images.githubusercontent.com/37256050/176780802-adbe3426-b4b4-4118-ba0f-bde89d9ce688.png)

![image](https://user-images.githubusercontent.com/37256050/176780842-3925709e-250b-4dc6-b81b-00590162713d.png)

db: `kufish`
user: `abentley`
browser: `Edge`

**Comment by maxxxxxdlp** [comment]
Same issue as #1779.
Closing as duplicate
