### ISSUE TITLE
Should be taken to top of new form when clicking Add Another or Clone

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1790]
After you've saved a record, when you click Add Another or Clone, a new record is created according to what you clicked, but it stays wherever you were on the screen (if you were at the bottom when you clicked add another, you are still at the bottom when the new record opens)
It should take you to the top of the form as soon as the new form is created.

**Comment by chanulee1** [comment]
Still stays wherever you were on the screen in the record before adding or cloning. Does not take you to the top of the screen.

**Comment by chanulee1** [comment]
Sorry, did not move this to "To Do".

**Comment by maxxxxxdlp** [comment]
Fixed in e239da5a9b501ce26d28016e93b850627343e1b3

**Comment by chanulee1** [comment]
Looks good.
db: `freshfish`, `willemcatno`
