### ISSUE TITLE
Synchronize user preferences between browser tabs

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1792]
Updates to user preferences or browser cache in one tab should propagate to all other Specify tabs

**Comment by maxxxxxdlp** [comment]
Fixed in acee096f and 9d633754

https://user-images.githubusercontent.com/40512816/177055039-ba4264f7-6a90-4a11-b51b-726864b78c73.mov


https://user-images.githubusercontent.com/40512816/177055044-aa4e9e0e-4fbf-4fe9-972d-4759873ab120.mov

**Comment by grantfitzsimmons** [comment]
I am not seeing that behavior reflected on `a11y`

**Comment by maxxxxxdlp** [comment]
This is not a11y. It will be part of `7.8.0` (as seen by the milestone)

**Comment by maxxxxxdlp** [comment]
`testability`

Please don't focus on testing this until `7.7.0` is out.

**Comment by grantfitzsimmons** [comment]
I will not even look at it. Thanks Max!

**Comment by grantfitzsimmons** [comment]
Looks to be working fine. Open a new issue if you encounter a problem with this functionality including specific details
