### ISSUE TITLE
Automapper assigning problematic mappings

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1797]
`a11y`:
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/37256050/177408254-bdc9ac7c-199c-4a4f-b1a7-30459c6848c7.png">

`edge`:
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/37256050/177408279-ae633191-b53b-4dbd-86d8-8b83d1715bfe.png">

db: `purdueherbaria`
user: `spadmin`
data set: `LichenData`

**Comment by maxxxxxdlp** [comment]
Good catch. It's a bug. Introduced in `a11y`.

Fixed
