### ISSUE TITLE
7 does not have the functionality to set Preferences for Locality 

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1801]
> In S6 you have the functionality to set Preferences default settings for Locality, there is no option to do this in Specify 7. Our researchers may need to un-tick the "Default to Latitude North" and "Default to Longitude West" as majority of the locations will be in the southern hemisphere. 

![image](https://user-images.githubusercontent.com/37256050/177610336-37dd4cbe-887b-4586-b7f0-ad752b4f3f83.png)

**Requested By:** Don Balmaceda at CSIRO

**Comment by maxxxxxdlp** [comment]
Duplicate of #159
