### ISSUE TITLE
Lat/Long not parsing decimal values into Degrees and seconds

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1802]
> When a decimal value is added in the Latitude and Longitude source field in Locality, the Parsed data is being incorrectly displayed. 
Example screenshot below displays Source Latitude -35.2168000000 and Source Longitude 149.0312000000 and the Parsed data as 35.2168° S, 149.0312°E 
This should be converted to 35° 13' 0.48'' S and 149° 1' 52.32'' E
> There is also an issue where Lat and Long accuracy is not converting correctly in Geolocate. Screenshot attached of Latitude and Longitude inaccuracies when clicking Geolocate

<img width="794" alt="image" src="https://user-images.githubusercontent.com/37256050/177610991-8bde5d81-5e29-4333-b07b-24859082d666.png">

![image](https://user-images.githubusercontent.com/37256050/177610944-100b1dcb-a000-42bf-b034-a8ef373bc475.png)
![image](https://user-images.githubusercontent.com/37256050/177610959-dc9416a7-6cdf-4416-8612-d7dd923a307c.png)

**Reported By:** Don Balmaceda at CSIRO

**Comment by maxxxxxdlp** [comment]
> Example screenshot below displays Source Latitude -35.2168000000 and Source Longitude 149.0312000000 and the Parsed data as 35.2168° S, 149.0312°E
This should be converted to 35° 13' 0.48'' S and 149° 1' 52.32'' E

This looks like correct behavior to me. Is the issue the fact that the formatter coordinate uses decimal degrees instead of the degrees and decimal minutes format?

In that case, implementing #159 should fix that.

**Comment by maxxxxxdlp** [comment]
> There is also an issue where Lat and Long accuracy is not converting correctly in Geolocate

Can you also elaborate more on this? The value appears correctly in meters on the form and in GeoLocate

![Screen Shot 2022-07-26 at 22 30 48](https://user-images.githubusercontent.com/40512816/181154669-a93bfc0a-9f9a-456d-bf8d-ec8a097443a8.png)

**Comment by grantfitzsimmons** [comment]
**From M Wallace:**
>No more comment to made here, I think this is a simple case of the stored decimal degrees value not being displayed in HHMMSS format
