### ISSUE TITLE
Improve Attachment previews

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1803]
<img width="657" alt="image" src="https://user-images.githubusercontent.com/37256050/177614896-a9f1a420-8bc2-49bc-a6b4-db3003b1d469.png">

![C_ Users abentley Desktop Large pictures_For Andy 40276](https://user-images.githubusercontent.com/37256050/177614958-ef586092-fbf8-49e9-b2bb-3daab1a312cc.JPG)

**Comment by maxxxxxdlp** [comment]
Fixed in d475a6be3

**Comment by grantfitzsimmons** [comment]
This still needs to be improved upon. Attachments need to be better on the CO form! Thumbnail size needs to be customizable- the current tiny images aren't cutting it nowadays.

@sorovi requests that there should be the ability to show a default icon instead of the title of the document.

I think better file preview would be a great addition. Attachments become more important every day.

**Comment by grantfitzsimmons** [comment]
Fixed by @CarolineDenis's improvements to the attachment viewer that can be embedded on the form
