### ISSUE TITLE
Disable "Select All" button if no preparations available

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1805]
<img width="701" alt="Screen Shot 2022-07-07 at 11 51 47 AM" src="https://user-images.githubusercontent.com/37256050/177828129-a68bf321-ab29-4883-8a3e-f6b7247ce262.png">

When creating a Gift from a Record Set, the **Select All** button in the Preparations view has no function.

db: `cleanfish`
**Browser:** Safari

**Comment by grantfitzsimmons** [comment]
My loan in another tab already made them unavailable. My bad!

**Comment by maxxxxxdlp** [comment]
This is a UX issue. Need to disable the "Select All "button in these cases

**Comment by chanulee1** [comment]
Works! "Select All" button is disabled and unclickable when the record set is on loan.

db: `freshfish`
Browser: Chrome
