### ISSUE TITLE
rows= attribute being ignored

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1807]
![image](https://user-images.githubusercontent.com/37256050/177858275-87272755-767b-4550-b5e2-13ae89ddbb2e.png)

`rows="1"` is being ignored.

```
				<row>
                    <cell type="label" labelfor="datecomments"/>
                    <cell type="field" id="datecomments" name="text3" rows="1" colspan="10" uitype="textareabrief"/>
				</row>
```

db: `wv_6_28_2022`

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/177858504-737a6f45-becf-4c7a-8edb-44abd1c40808.png)

Being respected in `edge`

**Comment by tlammer** [comment]
It's also there for spacing and appearance.  It makes the form look neater, more organized if it is larger, in some cases
