### ISSUE TITLE
Institution Admin can't add or remove IA privileges to other users

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1808]
Discovered in KUBirds on the test server.
I added IA privileges to a user then logged in as that user and went into Security and Accounts.  I looked at the permissions for other users and tried to remove IA from one user unsuccessfully and add IA to another user, also unsuccessfully.
The first user I tried to edit was the first user created in the database, so I thought that might play a role, but i also couldn't modify other users.

**Comment by maxxxxxdlp** [comment]
@benanhalt Despite being an IA, the `/context/user.json` endpoint returns `{isadmin: false}`

Replicated on a newly created user

**Comment by maxxxxxdlp** [comment]
Confirmed fixed
