### ISSUE TITLE
Primary search not checking for permissions

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1811]
A user with no read permissions to any table is still able to receive primary express search results:

<img width="1800" alt="Screen Shot 2022-07-07 at 20 13 20" src="https://user-images.githubusercontent.com/40512816/177896773-a9871d79-e40e-4f5f-97cb-d97ea5fb92a7.png">

Secondary search is failing with a proper permission error

**Comment by benanhalt** [comment]
fixed by 75cab1e75

**Comment by maxxxxxdlp** [comment]
Confirmed fixed
