### ISSUE TITLE
Add a global pref for attachments preview size

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1812]
Current size is 123px and is too small in some cases.

Changing the preview size for existing attachments server would lead to thumbnails being regenerated, which would cause short-term performance issues.

But, there should be an option to change the thumbnail size for usage with clean attachment servers.

**Comment by grantfitzsimmons** [comment]
Do I need to establish something like this in global prefs?

`attachment.preview_size = 1000`

**Comment by maxxxxxdlp** [comment]
Yes!
Sorry, I should have put a comment here documenting that change

**Comment by grantfitzsimmons** [comment]
I haven't been able to make this work. Have you tested this?

**Comment by grantfitzsimmons** [comment]
This is not working for me

**Comment by maxxxxxdlp** [comment]
Looks like remote prefs parsing was failing because you had a space before the `=` sign.

Fixed. I was able to get it working:
1. Add `attachment.preview_size = 1000` to remote prefs
2. Clean cache
3. Try opening Attachments tab or uploading a new attachment
