### ISSUE TITLE
The Collection Access checkbox should be checked automatically for all collections if user is IA

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1813]
Currently, if a user is made an IA, the Collection Access checkbox is only checked for the collection they were in when made an IA.  The box should get checked automatically for all existing collections and any future collections

**Comment by maxxxxxdlp** [comment]
Fixed:
The collection access is now hidden for IAs as it is not applicable for them
The agent field is always marked as required for all collection as IA has access to all collections
The roles list is hidden as there is no need for an IA to be a member of any role
