### ISSUE TITLE
Make customizing splash screen image more user friendly

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1815]
The splash screen customization user preference has a link to the documentation. Need to modify the documentation to make it more user-friendly.

Need to add an option to upload an attachment to have it be used as an image

Need to add an option to pick existing attachment

Could add a preview of selected attachment/image

**Comment by grantfitzsimmons** [comment]
Going to close this in favor of pursuing https://github.com/specify/specify7/issues/997
