### ISSUE TITLE
Number spinners showing up for lat and long fields in queries

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1827]
**Describe the bug**
Spinners are illogical for latitude and longitude fields in queries and should be removed if possible

**To Reproduce**
1. Go to any query that contains lat and long fields
2. See error

**Expected behavior**
These should just show as regular fields

**Screenshots**
![Capture2](https://user-images.githubusercontent.com/7501989/178804530-0ea812d2-1eb1-459b-86c4-ae9bab0178b4.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
There are a few reasons to keep them:
- Reduces software complexity by not adding exceptions and special behaviors (which are bad)
- The spinners tell user that the input expects a coordinate as a number, rather than a string (i.e, not `12 W`)
- The spinner is useful for accessibility purposes
