### ISSUE TITLE
Aggregated/Formatted fields still showing ANY operator in queries

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1828]
**Describe the bug**
Given that this is the only option and it has no functionality for these fields, could we remove it?  There is no operator for these fields in Specify 6

**To Reproduce**
1. Go to query builder
2. Click on any query that has an aggregated or formatted field
3. See error

**Expected behavior**
These should be removed if possible

**Screenshots**
![Capture3](https://user-images.githubusercontent.com/7501989/178804936-31788d37-a84f-49a9-ae2e-9782e4793d96.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Good idea.

Doesn't seem critical. Will be fixed in next release
