### ISSUE TITLE
Aggregation in queries can result in values that get truncated by MySQL

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#183]
E.g.

When doing the following query: Agent -> Collectors -> (aggregated)
You get this error:
Warning at /stored_query/ephemeral/
Row 45 was cut by GROUP_CONCAT()

**Comment by benanhalt** [comment]
See: http://dev.mysql.com/doc/refman/5.5/en/server-system-variables.html#sysvar_group_concat_max_len

**Comment by garrettgirard** [comment]
The issue appears to be fixed, as there is no longer any error when executing the query. However, and I'm not sure if this is a bug or anything, but the several of the results I noticed have the same Collector name duplicated over and over again.

**Comment by benanhalt** [comment]
The repeated name is due to formatter for collectors just being the agent name. This is a very contrived query that just happens to exhibit the bug but otherwise produces useless results.

**Comment by garrettgirard** [comment]
In that case I don't see anything wrong with the issue, looks fixed to me.
