### ISSUE TITLE
Leave the page message shows on top of other dialogs

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1830]
![chrome_9f0tCVKixG](https://user-images.githubusercontent.com/37256050/178816077-320ae659-3015-46e9-85d6-eaac9ac3de51.gif)

This dialog should appear after!

**Comment by maxxxxxdlp** [comment]
Good idea.

Doesn't seem critical. Will be fixed in next release

**Comment by maxxxxxdlp** [comment]
This might be fixed already on `testability`

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp It looks like this has been solved on `testability`. I'll keep my eye out when we start testing it more aggresively.
