### ISSUE TITLE
Security Panel does not always prevent duplicate policies

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#1832]
I have policies for 3 tables:

<img width="782" alt="Screen Shot 2022-07-13 at 22 58 13" src="https://user-images.githubusercontent.com/40512816/178895271-77297a35-2d67-4597-9af1-6d11b5bfe91e.png">

The pick list for each line does not list other tables as disabled:

<img width="782" alt="Screen Shot 2022-07-13 at 22 58 24" src="https://user-images.githubusercontent.com/40512816/178895304-28c9d43e-d02b-4d5c-989d-f7064e0e8480.png">

Adding a new line makes those lines disabled:

<img width="782" alt="Screen Shot 2022-07-13 at 22 58 34" src="https://user-images.githubusercontent.com/40512816/178895327-efbddf44-5706-4bac-8be0-d6863328850e.png">

It seems like the "whether line is disabled" status is not updated when pick list value is changed

**Comment by emenslin** [comment]
Fixed
