### ISSUE TITLE
Workbench validation throwing error

### ISSUE THREAD

**Issue by realVinayak** [specify/specify7#1833]
**Describe the bug**
Workbench validation in edge and a11y is throwing an error. Grant also had the same issue when he tried the validation.

**To Reproduce**
1. Log into edge and a11y specify versions using `spbirdadmin` username, and use the `Ornithology` discipline and `KUBirds (6.8.01)` database.
2. Import the WBVoucherdata.csv to the workbench 
3. Click on 'Validate'

**Expected behavior**
The cells should be validated instead of throwing errors.

**Screenshots**
The left image is of the error in a11y version, and the right image is of the same error in edge version.

![worbench_validate_bug](https://user-images.githubusercontent.com/61122018/178999008-57b3d928-fac4-404c-b7e0-87be31451b24.PNG)

**Comment by grantfitzsimmons** [comment]
Issue was related to the test panel. Cannot reproduce. Open if this happens again!
