### ISSUE TITLE
Table name and field name appearing as invalid

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1834]
![image](https://user-images.githubusercontent.com/37256050/179046120-d2bb949c-3c74-4e54-960c-210df44f1466.png)

When viewing the RefrenceWorkType pick list, the Table Name and Field Name are displaying as invalid.

db: `newmexico_july22`
user: spadmin

https://a11y-2-2.test.specifysystems.org/specify/view/picklist/14/

**Comment by maxxxxxdlp** [comment]
Those fields should probably be hidden when not applicable.

We have https://github.com/specify/specify7/issues/364 open for that

**Comment by grantfitzsimmons** [comment]
I had not changed the type. This is a pick list that was assigned to a field by default and has had no modifications

**Comment by maxxxxxdlp** [comment]
Was it there by default after database got created?
If so, our default pick lists are a bit invalid

**Comment by grantfitzsimmons** [comment]
Yes. I believe it is the default, unmodified ReferenceWorkType pick list assigned to Reference Work -> referenceWorkType

**Comment by maxxxxxdlp** [comment]
Okay. It's not an issue, because they would just be ignored.

Hiding portions of the form depending on pick list type would hide the fields that don't apply and make this less confusing
