### ISSUE TITLE
WB does not handle errors arising from pick list values that exceed field length

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1837]
Having a value that is over the field length limit produces this not user-friendly error:

![image](https://user-images.githubusercontent.com/40512816/179144660-55777fb2-05ac-4994-a867-9f65d29f3ed5.png)

See also #1365

**Comment by benanhalt** [comment]
Next time this happens include the data set and mapping. The backend is checking lengths when there is a max length given by the data model. It would help to know the exact field and value that is getting through the check.

**Comment by grantfitzsimmons** [comment]
I caused that failure by assigning a field (text1 in this instance) with a 50-character limit a picklist that had items that exceeded that limit.

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/179850449-14056a6f-72e4-4fe6-bb66-bb47a89f3eb7.png)

text1 is under the Collection Object Property table.

**Comment by grantfitzsimmons** [comment]
<img width="571" alt="image" src="https://user-images.githubusercontent.com/37256050/180249876-2d049b58-cb45-4806-8405-220129e9b90a.png">
