### ISSUE TITLE
Allow all attachment links to be a panel

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1838]
Requested by New Brunswick

Currently, only Collection Object Attachments can be a panel.  The others have to be a button.  They would like other attachment links to be panels as well

**Comment by grantfitzsimmons** [comment]
It seems this is already possible. I had to add the panel coldef but I had no problem getting this to work for Locality.

`
                    <cell type="panel" id="LoAttachment" name="outerPanel" coldef="p,2px,p:g,5px,p:g" rowdef="p,4px,p,4px,p,4px,p,4px,p,4px,p" colspan="5"/>`
