### ISSUE TITLE
Make creating a record set of records uploaded by the WB optional

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1848]
Requested by Auburn

They commented that they would like Specify 6 batch editing to NOT create a record set every time they use the feature.
It would be nice if when we add the feature to Specify 7, there be a checkbox in the batch edit screen that says to either automatically create a record set or not to do so.

**Comment by maxxxxxdlp** [comment]
@benanhalt can you create an endpoint for creating a record set out of a specific table among the records created in an upload of a specific data set?

Then, front-end can conditionally call that endpoint post-upload based on user preferences.

It will also allow front-end to create record set from any table. I.e, in a CO upload, you would be able to create a record set of all created localities.

Additionally, it will introduce a workaround for https://github.com/specify/specify7/issues/1203

**Comment by benanhalt** [comment]
This issue originally was about batch editing, which doesn't exist in 7, yet. So it got changed to a WB issue. I'm going to add a new issue to track the batch edit request so the idea isn't lost.

**Comment by benanhalt** [comment]
Ben votes yes
Jim votes no
Theresa votes yes
Grant wants a user pref. Or maybe  prompt at end of upload?

**Comment by maxxxxxdlp** [comment]
This would probably also improve upload/rollback performance.
Creating a record set on upload and deleting it on rollback may take some time (@benanhalt would it also create audit log entries?)

**Comment by benanhalt** [comment]
I don't think it would make much difference to upload/rollback performance. The uploads and rollbacks do generate log entries for the records themselves, but that is a separate matter. The creation and deletion of the record set items are not recorded in the audit log however.

**Comment by benanhalt** [comment]
The linked PR adds the API to generate the RS from a prior upload and removes the automatic creation of same. NB the API only produces a RS of the base records. Next steps would be adding the UI. Presumably a button that opens a dialog to name the resulting RS.

The meeting didn't seem to fully resolve whether to move forward with this. @maxxxxxdlp would you care to offer any opinion?

**Comment by maxxxxxdlp** [comment]
My take on it:

While the `Uploading` dialog is in progress, a checkbox would be displayed:

`[ ] Create a record set from uploaded records`

The value of the checkbox is remembered between sessions in browser storage.

If it is checked, and upload completed successfully, the front-end opens a dialog to enter the record set name, and afterward sends the corresponding request to the back-end and shows a `Creating Record Set` loading dialog.

Once this functionally is expanded to all tables, the user would also be able to create a record set by clicking on any table name in the `Results` dialog.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-5-release-announcement/1023/1
