### ISSUE TITLE
Collection Object Properties does not appear

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1850]
Collection Object Properties does not appear in the QB when unhidden in the schema.

Might be a duplicate of https://github.com/specify/specify7/issues/1845. If so, please close.

This is recreated on both the `newmexico_july22` and `wv_6_28_22` databases.

**Comment by maxxxxxdlp** [comment]
It is a duplicate.

See my comment for a full list of affected fields: https://github.com/specify/specify7/issues/1845#issuecomment-1188500324

**Comment by maxxxxxdlp** [comment]
Basically, every table whose name ends with one of the following is affected:

```
  Authorization
  Variant
  Def
  Item
  Property
```

**Comment by grantfitzsimmons** [comment]
I do not see collectionobjectproperty or collectionobjectproperties in that list, therefore I posted this. Sorry if I missed it!

**Comment by maxxxxxdlp** [comment]
Ah, sorry. I wasn't clear enough. The file also defines matches against table names that end with a particular string
