### ISSUE TITLE
Cancel button missing from pick list editor

### ISSUE THREAD

**Issue by kuivwebadmin** [specify/specify7#1851]
**Describe the bug**
The pick list editor lacks a Cancel button. You have to use Back to exit the form.

**To Reproduce**
In Schema config, select a field which has a pick list, and edit the pick list.

**Expected behavior**
A way to make a clean exit from the form.

**Screenshots**
![image](https://user-images.githubusercontent.com/79189768/179709819-269207ea-ac9b-449a-b4ce-3a5a6f8b0589.png)

**Desktop (please complete the following information):**
 - Ubuntu 20
 - Firefox
 - Specify 7.7

**Reported By**
Gothenburg museum of natural history

**Comment by maxxxxxdlp** [comment]
The `Cancel` button is missing from all forms.

To cancel, you can close the browser tab, press the browser back arrow, or go to any other page though the top menu
