### ISSUE TITLE
[testability] Text editor expansion button invisible in full screen 

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1852]
<img width="900" alt="image" src="https://user-images.githubusercontent.com/37256050/179759684-17879bda-ba69-414b-9b91-853a94cbd810.png">

**Browser:** Chrome

It is visible in dark mode.

_Aside, what is the purpose of the "Text Editor" button? It does not seem to initiate any action._

**Comment by maxxxxxdlp** [comment]
The `Text Editor` is a tab. Eventually, there would also be a `Visual Editor` tab for all files.

I suppose we can hide the tab name if it is the only one.

Currently, the visual editor is only implemented for the `UserPreferences` and the `DefaultUserPreferences` files.

Eventually, there would be an editor for weblinks, formatters, express search and etc

**Comment by maxxxxxdlp** [comment]
Fixed in 4bdffe069
