### ISSUE TITLE
[testability] Error: Value is not defined on attachment upload

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1853]
https://user-images.githubusercontent.com/37256050/179760618-17cec455-4a06-4391-ac26-81af85f33a4e.mov

**Steps to Reproduce:**
1. Create a new collection object record
2. Attempt to add an attachment (In this case, an XML document)
3. See error

branch: `testability`
browser: chrome

**Comment by maxxxxxdlp** [comment]
Unable to reproduce. But, it's been more than a month since this has been reported. This might have been fixed since then.

@grantfitzsimmons can you try this again?
