### ISSUE TITLE
[testability] Field options not loading in schema config

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1856]
![image](https://user-images.githubusercontent.com/37256050/179799724-9fba6504-4c89-4cae-a652-2d464d909e25.png)

browser: Chrome

**Comment by maxxxxxdlp** [comment]
Should be fixed in f96ef8056

**Comment by grantfitzsimmons** [comment]
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/37256050/186744568-e4e12361-7022-47d5-85f4-9d0a9d0570ad.png">

After selecitng another field in the table, the error returns

**Comment by maxxxxxdlp** [comment]
Which database does this happen in?

**Comment by grantfitzsimmons** [comment]
`KU_Fish`

**Comment by grantfitzsimmons** [comment]
still a :lady_beetle: :smile:

**Comment by maxxxxxdlp** [comment]
Probably an easy fix. Sorry, didn't have much time for the `testability` bugs, but this one sounds like a high priority one

**Comment by maxxxxxdlp** [comment]
Fixed
