### ISSUE TITLE
WorkBench mapper not saving assigned determination number

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1858]
![chrome_88Us8P2sTu](https://user-images.githubusercontent.com/37256050/179844939-bd7787c8-bee0-4047-8aa5-8890ba0c38ad.gif)

In my data set, I mapped the field text8 to the #3 Determination and it automatically reset to the #2 Determination after saving.

version: 7.7.0
browser: Chrome

There were 3 mapped determinations that included other fields.

Both the mapping and data set are here:
[WVA 0-10000 (7-18 Export).zip](https://github.com/specify/specify7/files/9144601/WVA.0-10000.7-18.Export.zip)

**Comment by grantfitzsimmons** [comment]
Rather concerning bug that we should revisit soon.

@bronwyncombs @carlosmbe If either of you have the time, please try to recreate this and check back.

**Comment by bronwyncombs** [comment]
Still in `v7.9-dev`


https://github.com/specify/specify7/assets/135047322/a8b4e0a1-a6d8-4f37-ae32-2c9a75baac3c

This is me editing an existing data set in `coldfish` 
(https://coldfish-v79-dev.test.specifysystems.org/specify/workbench/27/) 

The same is true for new data sets.

**Comment by emenslin** [comment]
Can recreate in xml and edge. 

https://github.com/specify/specify7/assets/150940840/efcef3d6-2a93-4a2d-9342-000bfdde86d4


https://github.com/specify/specify7/assets/150940840/bc035e0d-c783-462f-9d70-cb4b0ce0da9d

**Comment by emenslin** [comment]
Can recreate in edge (7.9.6)

**Comment by CarolineDenis** [comment]
NOTES: 

There is also an issue with the line header that do not update on field changes

**Comment by maxpatiiuk** [comment]
> In my data set, I mapped the field text8 to the https://github.com/specify/specify7/issues/3 Determination and it automatically reset to the https://github.com/specify/specify7/issues/2 Determination after saving.

**Comment by maxpatiiuk** [comment]
> In my data set, I mapped the field text8 to the https://github.com/specify/specify7/issues/3 Determination and it automatically reset to the https://github.com/specify/specify7/issues/2 Determination after saving.

the logic was supposed to be that you are not allowed to skip a number (it will get normalized once you save)
maybe it's misbehaving...
 
and the number you see in the UI is kind of virtual - it's not explicitly written in the upload plan, other than by positional index in an array

**Comment by maxpatiiuk** [comment]
Hmm, I looked at this, and it seems that the present behavior is correct. See:

If there is nothing mapped to `#2`, then mappings to `#3` get collapsed:

before saving:

![Screenshot 2024-07-25 at 18 56 06](https://github.com/user-attachments/assets/2975d251-9104-40d3-9458-5363e8b9a18b)

after saving:

![Screenshot 2024-07-25 at 18 56 11](https://github.com/user-attachments/assets/2a646f34-59d0-43f6-98f6-7dd228d407a3)

The numbers `#2` and `#3` are purely virtual - they are just to mark relative position, not some sort of absolute ID. There is nothing in the upload plan that tells whether you mapped to `#2` or `#3` - it's all just saved as an array

**Comment by maxpatiiuk** [comment]
If do I have at least one thing mapped to `#2`, then `#3` does not get collapsed, so all is good too:

![Screenshot 2024-07-25 at 18 55 45](https://github.com/user-attachments/assets/b2093f38-c738-40fa-99ec-ec44d9fe55e7)
