### ISSUE TITLE
[testability] Cannot handle missing picklist on form

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1862]
![image](https://user-images.githubusercontent.com/37256050/179852223-0dcbfc84-a7dd-465f-8f98-d963cc260ab5.png)

left is `7.7.0`, right is `testability`

db: `SAIAB`
collection: `BRUV Fish`
user: `collection`

`/specify/view/collectionobject/258078/?recordsetid=581`

**Comment by grantfitzsimmons** [comment]
https://saiab20211125-testability.test.specifysystems.org/specify/view/collectionobject/258078/?recordsetid=581

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/37256050/192844908-f153b8c8-65c4-48f1-b309-2d8ab9214b0e.png">

**Comment by maxxxxxdlp** [comment]
The statusText issue is separate (and is fixed now) - https://github.com/specify/specify7/issues/2230#issuecomment-1262559902

**Comment by chanulee1** [comment]
Setting default picklist in form definition to a picklist that does not exist causes field to break.
Field used: "Stage" (text3) in the "Length Cont." (collectionobjectattribute) subview of the collection object form
db: `willemcatno`
col: `BRUV Fish`

![image](https://user-images.githubusercontent.com/103299204/195473414-7e70a960-6759-45e6-8e8d-f6c1ed08db80.png)

**Comment by chanulee1** [comment]
Pick list field disabled when assigned to non-existent picklist in the form definition.
db: `willemcatno`
user: `collection`
