### ISSUE TITLE
[testability] Sorting arrows are reversed from 7.7

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1863]
![image](https://user-images.githubusercontent.com/37256050/179853243-95da95cc-08e8-479d-abb0-f280f4595422.png)

**Comment by maxxxxxdlp** [comment]
Wow, good catch!

Can you also check the record sets and reports dialogs?

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/179853651-c325f823-f807-4715-ada1-7cb2309e8372.png)

**Comment by grantfitzsimmons** [comment]
Robots can't test that! I guess I'm not going anywhere after all!

**Comment by grantfitzsimmons** [comment]
**
![image](https://user-images.githubusercontent.com/37256050/179853801-85536223-38fd-4ba0-bb46-8f2b4bad79e5.png)
**

**Comment by grantfitzsimmons** [comment]
I guess I can retire at 21 😵‍💫. Looking forward to the advanced testing soon!

**Comment by maxxxxxdlp** [comment]
Hmm, looking at this again, I think it is debatable whether the new or the old behavior is correct.

> ![image](https://user-images.githubusercontent.com/37256050/179853243-95da95cc-08e8-479d-abb0-f280f4595422.png)

When it sorts by date, on the left, it sorts by how long ago something has been (a relative date,  5 min ago > 2 min ago). On the right, it sorts by absolute date (2012 > 2022)

**Comment by grantfitzsimmons** [comment]
Here is how Excel behaves:

**Ascending:**
<img width="161" alt="image" src="https://user-images.githubusercontent.com/37256050/186745314-ada1f719-a2a4-42ec-a8d5-13ccae872530.png">

**Descending:**
<img width="162" alt="image" src="https://user-images.githubusercontent.com/37256050/186745332-92288272-0a7b-4cc9-8405-8c357453e648.png">

By this logic, the `testability` behavior is logical.

**Comment by grantfitzsimmons** [comment]
Reopen if you believe we should revert this behavior!
