### ISSUE TITLE
Add "Generate Invoice" button to forms 

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1864]
**Requested By:** RBGE

> We are finding users are wanting to generate invoices, without actually having changed any data in a form. 
> Is there a way to add a “Generate” invoice” button to a form, instead of the current generate on save tickbox, so that users don’t have to make a change to generate an invoice?  - similar to what can already be done with labels?

Modifying a record should not be required to generate an invoice.

Adding a "Generate Invoice" button would be great for those who do not wish to modify a record but would like to print a since label or report. This would be useful on Collection Objects, Loans, and potentially Borrow (see https://github.com/specify/specify7/issues/519).

**Comment by maxxxxxdlp** [comment]
?

<img width="2560" alt="Screen Shot 2022-07-20 at 09 16 58" src="https://user-images.githubusercontent.com/40512816/180005176-a7d1b62c-d089-4ded-a73e-927e2449c2a2.png">

**Comment by grantfitzsimmons** [comment]
I was not seeing it- had it hidden in the form definition. Seemed like it was missing in this release since I had the checkbox but everything works. Thanks Max!

**Comment by grantfitzsimmons** [comment]
I think that would be a good idea. I checked `Testability` and was hoping it would be in that menu but I only saw generate on save.
