### ISSUE TITLE
[testability] Can't traverse into a collection using dot notation

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1865]
![image](https://user-images.githubusercontent.com/37256050/180010092-cc7e51ae-9e6e-46c4-9390-24181e6ec7bc.png)

![image](https://user-images.githubusercontent.com/37256050/180010374-d6730673-b9ea-4f1e-a3ba-dec0bfa1c8e4.png)

**Steps:**
1. Go to `/specify/view/collectionobject/60955/?recordsetid=81` on `kufish`
2. Click on the pencil icon next to Field No: Locality's QCBX
3. See error

db: `kufish`
browser: Chrome

**Comment by maxxxxxdlp** [comment]
Duplicate of #1969
