### ISSUE TITLE
[sp7.7] Current determinations should appear first by default

### ISSUE THREAD

**Issue by benritchie** [specify/specify7#1872]
In specify 7.6, the Dets were always sorted such that the current name was at the top of the list.  This is no longer true in 7.7.  As the current name is generally the one that users will want ot view first, it would be better to put it back at the top.  

Screenshots:
7;6:
![image](https://user-images.githubusercontent.com/8005676/180183474-e3934e7b-5253-4b83-89a3-0acc0bc3b9ab.png)

7.7:
![image](https://user-images.githubusercontent.com/8005676/180183519-d926fcab-59e5-4c5b-9bdf-d96399a9824b.png)

**Reported By**
RBGE

**Comment by maxxxxxdlp** [comment]
I believe the sort order was by timestamp created in most cases.

In the new release, you have the ability to explicitly change the sort order:
- Either add a `sortField` attribute to your form definition to explicitly set the sort field and direction - https://github.com/specify/specify7/wiki/Form-System#:~:text=sortField%20(string%2C%20optional%2C%20case%2Dinsensitive)
- Or, click on one of the column headers to change the sort order in real time (however, this sort order won't persist after the form is closed)

**Comment by benritchie** [comment]
SortField sounds a great fix to this.  unfortunately its not working...
Here's my XML config for embedding the dets subform - I've added the sortField parameter.  
                    <cell type="subview" viewname="Determination" id="6" name="determinations" defaulttype="table" colspan="13" rows="5" sortField="isCurrent"/>

Here's the UI that results - it seems to have ignored the sortfield.  
![image](https://user-images.githubusercontent.com/8005676/180417248-54ea578b-c590-4ba1-81ad-b153cd6948a3.png)

**Comment by benritchie** [comment]
does sortField not work with booleans or something?  
(note, we've relabelled isCurrent to Filed As in the schema.  I'm assuming we should be using field names, not labels here though? - I've tried both, and neither works).  
Thanks.

**Comment by maxxxxxdlp** [comment]
It looks like you forgot to attach your XML snippet. Make sure you specified sortField inside an `initialize` attribute:

```xml
<cell colspan="12" defaulttype="table" id="8" initialize="sortField=isCurrent" name="determinations" rows="3" type="subview" viewname="Preparation" />
```

**Comment by benritchie** [comment]
umm.  the sortField workaround still isn't working for me.  If I put in a non reverse sort, I can get the current det at the bottom of the list:

                    <cell type="subview" viewname="Determination" id="6" name="determinations" defaulttype="table" colspan="13" rows="5" initialize="sortField=isCurrent"/>
![image](https://user-images.githubusercontent.com/8005676/181575504-6b3173b0-9cb3-4bf1-a855-2277d3ea39e3.png)


If I put in a reverse sort, it seems to ignore it, and go back to a default sort:
                    <cell type="subview" viewname="Determination" id="6" initialize="sortField=-isCurrent" name="determinations" defaulttype="table" colspan="13" rows="5" />

![image](https://user-images.githubusercontent.com/8005676/181570278-280d8ed5-f90f-4f2e-8dca-916d7aea5cdc.png)

**Comment by benritchie** [comment]
interestingly, the "sort symbol doesn't appear in the second case.  
I'm copying that reverse sort scemantics from the docs.  is there something else needed?

**Comment by grantfitzsimmons** [comment]
@benritchie This is now fixed in the newest `edge` release of 7. I tested this on one of your database backups and I am having no issue.

`
                    <cell type="subview" viewname="Determination" id="6" name="determinations" defaulttype="table" initialize="sortField=-isCurrent" colspan="13" rows="5"/>
`
