### ISSUE TITLE
[sp7.7] setting a data to default to a relative date does not work.  

### ISSUE THREAD

**Issue by benritchie** [specify/specify7#1874]
**Describe the bug**
following https://github.com/specify/specify7/wiki/Form-System#text - I should be able to default a data field to e.g. 1 year in the future.  
this isn't working though - date field stays set to todays date.  
Desire is that current due date is 1 year in the future.  in reality for a newly created record I see:
![image](https://user-images.githubusercontent.com/8005676/180199224-ba262969-fc44-49c9-8388-c077cf79ad73.png)

form config is:
<cell type="label" labelfor="currentDueDate"/>
<cell type="field" id="currentDueDate" name="currentDueDate" uitype="formattedtext" uifieldformatter="Date" default="today + 1 year"/>

**To Reproduce**
feel free to use RBGE sandbox.  just create a new loan, and you'll see.  

**Reported By**
RBGE

**Comment by maxxxxxdlp** [comment]
@benritchie Hi. This issue has been fixed.
Change the specify version from `7.7.0` to `edge` in your `docker-compose.yml` to get the newest bug fixes.
https://hub.docker.com/r/specifyconsortium/specify7-service/tags?page=1&name=edge
