### ISSUE TITLE
Can't Save Collection Update Because of Date Format Issue

### ISSUE THREAD

**Issue by mf795** [specify/specify7#1875]
**Describe the bug**
With the new version, my Specify switched my date format to MM/DD/YYYY and I've been trying to find a way to change it to DD/MM/YYYY without switching my computer's settings. From what I did, the blank date box shows that I can put a date in as DD/MM/YYYY, but it won't let me save the collection object unless I change the date to MM/DD/YYYY format. In other words, when I have 20/01/1970 in my date, I can't save, but when I change it to 01/20/1970 I'm given the option to save.

**To Reproduce**
1. Click username to open settings.
2. Click preferences
3. Unselect 'Use accessible full date picker'
4. Start a new collection object
5. Blank date box should read 'DD/MM/YYYY'
6. Add a collection object as normal with dd/mm/yyyy date format and save button will be red and unusable.

**Expected behavior**
I was hoping that by unselecting 'Use accessible full date picker' I would be able to have the dd/mm/yyyy format for my Specify without changing my computer's settings.

**Screenshots**
I have the date in dd/mm/yyyy format and the save button is red
![image](https://user-images.githubusercontent.com/109741034/180221496-72adff6e-9ff9-4462-b2da-142a6ee15123.png)
Changed to mm/dd/yyyy format even though the blank box says I should use dd/mm/yyyy format and save button is orange and clickable.
![image](https://user-images.githubusercontent.com/109741034/180221791-5a231cf6-1532-4d22-9a82-d9131b84cfe8.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Specify 7 Version: 7.7.0 (I believe, but I'm not sure how to check)
 
**Reported By**
Cornell University

Thank you for your help!

**Comment by maxxxxxdlp** [comment]
Thanks for reporting this bug. I was able to reproduce it.

Yes, you are on Specify 7.7.0. But for future reference, to check your version, click on your user name in the top menu, and select "About Specify 7"

For future reference: bug occurred in the day.js library. Present in the newest version of day.js. Added an ugly workaround. Need to consider migrating to date-fns or wait for day.js 2.0

**Comment by maxxxxxdlp** [comment]
@mf795 Hi. This issue has been fixed.
Change the specify version from 7.7.0 to edge in your docker-compose.yml to get the newest bug fixes.
https://hub.docker.com/r/specifyconsortium/specify7-service/tags?page=1&name=edge
