### ISSUE TITLE
Schema language not respected across browsers

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1877]
If you set your schema language and log into another browser you will see it has not been applied. To fix this, you need to go into user preferences, change the language, then change it back to your desired language.

**Comment by maxxxxxdlp** [comment]
Can you replicate this again, but instead of changing the language and back in the second browser, simply refresh the page?

If that fixes it, then this is the cause:
> User preferences are cached in the browser.
>
> This is useful so that user preferences can be applied quicker (i.e, make the app use dark mode on the loading screen, rather than blind you with white while your preference for dark mode is being fetched from the back-end).
>
> It is also useful so that your user preferences are applied even when you are not signed in (the login page would use dark mode if the last logged-in user had dark mode on)
>
> When Specify loads, it fetches the most up-to-date user preferences to refresh it's cache.
>
> Schema localization and user preferences are fetched in parallel. Thus, if user preferences changed in one browser, and another browser has an outdated cached version, it can fetch schema localization for the previous language.
>
> Should be fixable by refreshing the page.
>
> Can be permanently fixed by delaying fetching schema localization until user preferences are fetched, but that would be a terrible idea, as users are unlikely to change schema language and then hop on to another browser.  Additionally, everything in specify depends on schema localization, so fetching it only after user preferences are fetched would make specify take longer to load

**Comment by grantfitzsimmons** [comment]
Refreshing the page fixed it. It was really that simple! Can I set a default schema localization for all users?

**Comment by maxxxxxdlp** [comment]
You can

In 7.7.0: https://github.com/specify/specify7/wiki/Setting-default-user-preferences
In 7.8.0:
1. Create a new app resource
2. Select "Default User Preferences" as a template
3. Change schema language
4. Save
