### ISSUE TITLE
Cannot disambiguate record, "Value is not defined" error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1878]
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/37256050/180297771-8181cff4-9bf9-4d12-82d2-fa7753e5d06b.png">

db: `newmexico_july22`
data set:` /specify/workbench/41/`

https://edge-2-2-2.test.specifysystems.org/specify/workbench/41/ (user: spadmin)

**Comment by grantfitzsimmons** [comment]
Data set is no longer useful

**Comment by maxxxxxdlp** [comment]
Fixed. Happened whenever the base table is a tree and you are trying to disambiguate a tree rank name


By the way, you have some duplicates in your tree:

<img width="1800" alt="Screen Shot 2022-07-22 at 19 28 44" src="https://user-images.githubusercontent.com/40512816/180583173-81891466-7bfa-4969-ba85-da6b8ae5ecfb.png">

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp There are 326 duplicate ranks due to the nodes having _slightly_ different authors. Very annoying... maybe we need an interface to merge these sometime down the line

**Comment by maxxxxxdlp** [comment]
https://github.com/specify/specify7/issues/1030
