### ISSUE TITLE
Data exporter for Specify Web Portal

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1881]
Specify 7 should have an exporter for the web portal feature (or a Specify 7 web portal built-in to the database)

**Comment by grantfitzsimmons** [comment]
Is the current way to export a CSV of a query? Can we put a UI for this

**Comment by maxxxxxdlp** [comment]
There is a way to export a CSV:
Run a query
Press "Export to CSV"

We also have a separate ticket for Web Portal exports - https://github.com/specify/specify7/issues/786
