### ISSUE TITLE
[Sp7.7] isCurrent is showing up as a hidden field in query builder, when it is not hidden

### ISSUE THREAD

**Issue by benritchie** [specify/specify7#1894]
**Describe the bug**
In Sp7.6. we could build queries using isCurrent (in our instance, this is renamed to filingname).  
on upgrade to 7.7, isCurrent has become hidden in the query builder:
(as evidenced by its presence in the hidden list below, and the gray background it gets in the builder)    
![image](https://user-images.githubusercontent.com/8005676/180814516-db07188f-3fa7-4ed0-97c3-ed5c2f7eb9f5.png)

However, in the schema, it is not hidden:
![image](https://user-images.githubusercontent.com/8005676/180814639-1117307e-1650-4fe4-bf0b-834f14c7cbf2.png)

Bug here is that it shouldn't be hidden.  why is it?

Additionally - there's a new- super useful looking field been added to the query builder: "Current Determination".  
![image](https://user-images.githubusercontent.com/8005676/180814887-10c969b6-5962-4d49-86aa-f75ec819d2e4.png)
However, its hidden by default, which will mean that few people find it... - and I cna't see any way to unhide it.  
is there a way?  can we get it un hidden by default if not?

Thanks

**Reported By**
RBGE

**Comment by benritchie** [comment]
Just spotted this issue also effects Createdby / modifiedBy / last modified etc.  
will this fix cover them also?
Thanks.

**Comment by grantfitzsimmons** [comment]
@benritchie This fix also covers those fields!

**Comment by benritchie** [comment]
thanks.

**Comment by benritchie** [comment]
Great, thanks 😊
