### ISSUE TITLE
Restore "Abandon Changes" in the query builder

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1902]
The **Abandon Changes** button was removed in Specify 7.7. It is really handy since it gave a user-friendly option rather than having the user exit and re-launch.

![image](https://user-images.githubusercontent.com/37256050/181063041-b32c62cf-9d42-4afc-8f58-2320061d3bc2.png)

Several users have requested it back since its removal, including FWRI.

**Comment by maxxxxxdlp** [comment]
Is this a really useful feature or just a matter of getting used to different behavior?
I especially don't like the idea of adding "Abandon Changes" to all tools
Plus, it takes more valuable toolbar space
