### ISSUE TITLE
UI not rounding trailing zeros

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1909]
Need to make UI round all floats like 3.7000000 to 3.7 when displaying on the form.
This is most useful for the lat/long fields, but probably others too
It won't affect what's stored in the database.

See also #1208

**Comment by benanhalt** [comment]
Decimal fields only. Not floats. I think the coordinate fields are the only ones currently.

**Comment by benanhalt** [comment]
I mean it would probably be okay for floats, but it wouldn't always work because powers of ten != powers of two.

**Comment by bronwyncombs** [comment]
Fedor from NHM Denmark inquired about this on the forum regarding coordinate fields in a locality format: https://discourse.specifysoftware.org/t/formatter-for-locality-wont-round-numeric-values/3413
