### ISSUE TITLE
Restore ability to copy dates

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1910]
<img width="357" alt="image" src="https://user-images.githubusercontent.com/37256050/181368417-96e10c2f-85d3-41b6-ad95-21831796611f.png">

There should be a way to copy the entire date easily.

**Requested By:** Barry with the Minnesota Dragonfly Society

**Comment by maxxxxxdlp** [comment]
The modern date inputs don't support that. It's a limitation imposed by browsers.

You can revert back to old date inputs in user preferences.

We could also intercept Ctrl+C/Cmd+C and to manually handle the date copying, but that is likely to be complicated and buggy.

Probably, this would be the best solution:
Add a user pref for allowing to double click the date input field to flip back to the old style date picker, which has the ctrl+c support
