### ISSUE TITLE
Collection Relationship search using QB should not restrict results to collection

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1911]
Specify 7.7 added ability to search for related record using query builder.

This is used when adding a collection relationship and in other places

However, unlike the old search dialog, search using query builder restricts search results to the correct collection.

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/186167010-f44a7cda-ec20-49d9-8c7e-4db3cfae6fdc.png)


> **[S7: Collection Object relationship plugin tool searches against the wrong collection when query button used](https://app.asana.com/0/1201972579963460/1202845156918508/f)**
> When you add a link to a collection object from another collection and click on the "Query Builder" button you ending up searching in the collection you are currently in, rather than the collection you are trying to link to. 
> In the attached image we have an example for our specimen collection - the top line is a collection object from the genetic samples collection (added using the catalog number searcher) but the other two are collection objects from the specimen collection itself:

**Reported By:** CSIRO

**Comment by grantfitzsimmons** [comment]
This looks to be solved in 7.7.4. CoR is established from Terrestrial Vertebrates to Genetic Samples and it is searching the correct collection!
