### ISSUE TITLE
Make autocomplete search algorithm configurable

### ISSUE THREAD

**Issue by benritchie** [specify/specify7#1921]
**Describe the bug**
In Specify 7.6, if i select a picklist, and I type the complete name of a picklist entry, it will be reliably selected.  
This is really useful, when selecting entries from long picklists.  
Our use case is that we have a long list of herbarium's, identified by their Herbarium codes.  the biggest Herbaria have single letter codes - e.g. Kew is K, and Edinburgh is E, so you can just type in "E", or "K", and select the relevant herbaria.  
In the latest version, select appears to be done based on a full text search, and ordered alphabetically, so if you type in "E", you get a first match for "ACHE".  

ask is to in some way restore the old behaviour, where if you type in an exact match in a picklist, that entry is selected.  

screenshot below:
![image](https://user-images.githubusercontent.com/8005676/182113310-c7712660-e829-48d1-aeaf-abdd131682ed.png)

**Comment by benanhalt** [comment]
Jim votes for the old way.
Ben votes for the old way.
Grant votes for user preference with the old way as the default.
Theresa votes for the old way. Adding a pref adds undue complexity.

**Comment by benanhalt** [comment]
@maxxxxxdlp to please look into restoring the previous behavior.

**Comment by maxxxxxdlp** [comment]
Fixed. Old bebavior is now the default.

Added a `Forms -> Auto Complete -> Search Algorithm` user preference for pick lists and other places where auto-complete occurs (font selection in user prefs)

Also, keep in mind that there already is a separate user pref for query combo box: `Forms -> Query Combo Box -> Search Algorithm`

**Comment by benritchie** [comment]
quick check - we've spotted a second part of this.  wanted to check if this is also fixed by the change? 
It isn't only that the relevant part isn't selected (due to the change in algorithm - which I see you've resolved, thanks!)
its also that the picklists aren't behaving like picklists - they are behaving more like querycbx's.  in a pick list - If I'd typed in some text, and that text was the only match (by whatever algorithm was being used) I'd expect that value to have been selected, and that tabbing on to the next field would leave it selected.  - or that if there was multiple matches, the first would be selected.  
that's not what I see.  If I start typing in a picklist,, and then click tab to move to next field, then the picklist stays blank.  Even if I click enter, the picklist still stays blank.  I need to click down then enter.  I'd have expected a picklist always to have a value selected...
![image](https://user-images.githubusercontent.com/8005676/182635891-56c72bfd-412c-4c5a-bd6c-7f97153fbce9.png)

thanks.

**Comment by benritchie** [comment]
the incentive behind the above request is that for rapid use, Specify forms should be efficently navigate able by keyboard and mouse.  in most cases, that's got better in latest upgrade (thanks!) - but this bit feels like a step back.

**Comment by maxxxxxdlp** [comment]
@benritchie Fixed the keyboard navigation issue. See #1978
