### ISSUE TITLE
[Sp7.7 Suggestion] - renaming add another to add new

### ISSUE THREAD

**Issue by benritchie** [specify/specify7#1922]
Suggestion only - not a bug report.  
the new "Add another" button has caused a little confusion - users not quite sure what its going to do.  
had you considered an alternative naming for this - "Add New" - which might be more intuitive for what it does?

Thanks.

**Comment by beach53** [comment]
This is a regression.  Add Another although not perfect is marginally more precise as it implies the context of the current form the user is looking at.  The semantics of "Add New" provides slightly less context.
