### ISSUE TITLE
ColObjRelationship built-in search does not work with differing catalogNumber formatting

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1923]
<img width="753" alt="image" src="https://user-images.githubusercontent.com/37256050/182189662-7052e2f4-3123-46ea-b4af-c1655843abd6.png">

I cannot search on the catalog number due to it conforming to the catalog number formatting in the current collection.

Can use the Query Builder with a "Contains" filter instead of "Equal" to circumvent (as catalog number formatter is disabled for "Contains")

**Comment by maxxxxxdlp** [comment]
Fixed when fixing #1283
