### ISSUE TITLE
Cannot remove value from non-read only pick lists

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1924]
![chrome_6HsClGQBVB](https://user-images.githubusercontent.com/37256050/182203875-d997597e-b6de-4136-bf5a-683fe8ebac78.gif)

Similar to the issue with read-only pick lists.

On Determination form

db: `keherbariumvascular`
version: `edge`

**Comment by maxxxxxdlp** [comment]
Happens only when the selected pick list item is one character long
