### ISSUE TITLE
Simplify error message rendering logic in WBView

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#1925]
Handsontable has the ability to render comments for cells.
Those are used in the workbench exclusively for validation errors.
When error message is spawned for the last viewport column, the message caused the container to overflow.
This was fixed with an ugly hack.
This is no longer required as of Handsontable v12.1.0
See https://github.com/handsontable/handsontable/issues/4785#issuecomment-1168369616

**Comment by sharadsw** [comment]
fixed in #4611
