### ISSUE TITLE
Data Entry Forms/Icons Stalling on Mac (Firefox/Chrome)

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#193]
Found in KUFish - master branch

For some reason certain things that are stalled after being cached when you delete forms in Data Entry. For example, if you open up an agent form, save it, and delete it, attempting to open up the agent form again will result in it being stalled and it will take a while to open up. You can also run into the issue by deleting a different form, such as the Taxon form, then attempting to open up the Agent form. This has also been seen with the Collecting Event form (only after deleting the Collecting Event form) and the Collection Object Icon (when items are cached in a different order). This doesn't seem to be an issue on systems other than the Mac, or on Safari on the Mac. It is only a problem on Firefox and Chrome on Mac. This has also been found in both the KUFish database as well as the KUHerps database.

**Comment by benanhalt** [comment]
It seems like any http GET after a DELETE is hanging for some reason. Looking at the server logs, the response does not seem delayed (at least not in most cases), so the stalling is apparently client side. Googling the obvious keywords has not turned up known issues. Next test is probably to construct a minimal JS page that does a DELETE followed by a GET to see if it replicates outside the larger application.

**Comment by maxxxxxdlp** [comment]
This was not reported again so probably already fixed by the browsers.

Closing this as stale
