### ISSUE TITLE
Unable to open a data set since WB cannot find locality components

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1932]
![image](https://user-images.githubusercontent.com/37256050/182645443-3b60ef13-d09e-470c-bb24-7009f990c7fd.png)

![image](https://user-images.githubusercontent.com/37256050/182645467-41985aaa-cfd1-4bec-9827-9e3c1a591cb1.png)

**Max:**

That's where the error happens

![image](https://user-images.githubusercontent.com/37256050/182645274-3ee928c8-87e5-47cd-a3f1-0afbe431d0b7.png)

The error is because workbench can't find GeoMap, GeoLocate or Coordinae Converter Buttons

This might happen because user doesn't have sufficient permissions for those actions (i.e, no access to the Locality table)

**Reported By:** Lucas for the KU Mammals collection

**Comment by grantfitzsimmons** [comment]
[Specify 7 Crash Report - 2022-08-03T15_52_52.003Z (1)[43].txt](https://github.com/specify/specify7/files/9253149/Specify.7.Crash.Report.-.2022-08-03T15_52_52.003Z.1.43.txt)

**Comment by maxxxxxdlp** [comment]
Until this is fixed, a good short term workaround would be to give user the "Workbench -> Dataset > update" policy
