### ISSUE TITLE
[Sp7.7] - on upgrade, filters for some picklists disappear from queries in the UI.  

### ISSUE THREAD

**Issue by benritchie** [specify/specify7#1934]
Scenario:
we setup some queries in Specify 6, or 7.6 (not sure which they were created through).  
these queries were for loans, and included filtering on the LoanAgent field.  
Like this:  
![image](https://user-images.githubusercontent.com/8005676/182818196-8d80677f-91bd-49f2-9e2c-2960bd14e1e9.png)

However, when I view the same query in Specify 7.7, the Herbarium picklist bit isn't there:
![image](https://user-images.githubusercontent.com/8005676/182818382-471aba0b-8e50-4a86-98f1-9fa8074efa4b.png)

I can select Herbarium from the dropdown, but it should be set already, and isn't.  
![image](https://user-images.githubusercontent.com/8005676/182818722-1df0e582-aacc-4cd2-a1e4-898a13cf3e51.png)

interestingly, Herbarium does seem to be being applied in the search - so this is a query builder UI glitch, not a underlying query engine glitch I think.  

If I then set the AgentType to be herbarium through the 7.7 query builder, and hit save, then it does remember it.  therefore I assume that what is happening is that the way that 7.7, and 6 / 7.6 is storing queries that include picklists is slightly different, and there's an incompatibility there?

thanks.

**Comment by benritchie** [comment]
Update - this affects in both directions.  
After I fixed the query in Specify 7, this query clause now no longer appears in specify 6...
Looks like this:
![image](https://user-images.githubusercontent.com/8005676/182819422-65e66996-ff2f-4364-a030-e327f4383401.png)

**Comment by maxxxxxdlp** [comment]
@benanhalt Looks like Sp6 stores query field filter using `PickListItem.title`, where as new Sp7 by `PickListItem.name`

Should I change Sp7 to use `PickListItem.title`? Or should I make it use `PickListItem.name`, but fallback to `PickListItem.title` if a pick list item with the given `PickListItem.name` does not exist?

**Comment by maxxxxxdlp** [comment]
https://user-images.githubusercontent.com/40512816/184926584-90ff9457-adbe-4ab4-9bdd-6f2efff8015b.mp4

**Comment by benanhalt** [comment]
You mean picklistitem.value, right? There is no picklistitem.name. In regular forms when you select a picklistitem it stores the value in the field, right? Not the title? The idea being that the database representation can be different than the UI. That would militate for storing the value and not the title in the queries as well.

**Comment by maxxxxxdlp** [comment]
Oh right, `value`, not `name`.

Correct, it stores `value` in the forms. That's what Sp7.7 Query Builder does, but it is not consistent with Sp6 Query Builder

**Comment by benanhalt** [comment]
I think we should consider this a bug in the Sp6 query builder.

**Comment by benritchie** [comment]
My 2 cents:
Whichever its a bug in, I think its important its fixed relatively soon - given that currently, using just the Sp7 query builder isn't an option (as it doesn't work for reports).  

Additionally, there's a second related issue I've spotted.  If the "always" tick box is ticked in specify 6 next to a clause in the query, and then the report is edited in specify 7 - Always becomes unticked.  (presumably this occurs because 7 doesn't have a concept of always in queries?)
- also important for Reports, as Reports generally rely on Always being ticked for some parts of the query...

**Comment by grantfitzsimmons** [comment]
> @maxxxxxdlp 
To test:
Create a query with Agent -> Agent Type pick list in Sp6
Open it in Sp7
The pick list item should still be selected
Chose a different pick list item
Open query in sp6
The pick list item is not selected (because sp6 is doing pick lists wrong!)

6 still cannot interpret 7's picklist choice
