### ISSUE TITLE
Cannot remove record from a record set with correct permissions

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1937]
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/37256050/182908835-ebaa942d-197c-4375-a154-7e7b9451a781.png">

<img width="258" alt="image" src="https://user-images.githubusercontent.com/37256050/182909163-9db7a9e1-3f24-4614-8093-390e0f3eb842.png">

user: `demouser`
db: `KU_Fish`

**Comment by maxxxxxdlp** [comment]
It's a bug. Happens if you don't have delete permission to the record you are looking at
