### ISSUE TITLE
Reference Work relationships cannot return taxon names from other collection items

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1938]
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/37256050/182931140-6f00f22a-fd7e-43df-8b41-31caf080371f.png">

The relationship is as follows:

![image](https://user-images.githubusercontent.com/37256050/182931209-13575cc9-a260-43cc-b2a1-c6344d58b5ab.png)

For whatever reason, the taxon names from other collection object records outside of the current collection does not appear when running a query or label/report. This should be solved going forward.

db: `uopd`

`/specify/query/52/`

**Comment by emenslin** [comment]
Fixed
