### ISSUE TITLE
Shouldn't be able to type letters other than Direction Characters into Lat/Long Coord boxes

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#194]
If you go to the Locality form, in the Lat/Long Coords boxes, you can type any letter. As far as I can tell, typing random letters doesn't really do anything other than produce questionmarks in the "Parsed" section, as if nothing was typed in the box at all. You should only be able to type 'N' or 'S' in the Lat box and 'E' or 'W' in the Long box.

**Comment by garrettgirard** [comment]
Also, since there aren't different versions of the boxes (Degree vs. Degree Minute Decimal, etc.), I believe the correct method for showing different notation is just putting a space between each number. However, you can type in any special character or even apostrophes after each number, allowing for crazy formats in the actual data entry, yet somewhat normal parsing. So, you might end up with something like this "5f e 5' 5' abc" and it will parse as "5(degree) 5' 5" E". But you can also type something like "5 5 5 5", which has one too many digits, causing the Parsing to result as "???". And yet another weird bug is if you type a number with a decimal (e.g. 4.5), any numbers you type after it with a space between (e.g. 4.5 5) will Parse as "???".

**Comment by garrettgirard** [comment]
This is also a problem for the Quantity field in the Borrow Materials table and the Gift Preps/Loan Preps tables. You shouldn't be able to enter anything other than numbers.

**Comment by yvonneekanim** [comment]
Similarly, invalid lat/long values can be saved (i.e values greater than +/- 90 for latitudes and +/-180 for longitudes.) It only shows question marks in the parsed section when invalid numbers are put in the lat/long fields.

**Comment by grantfitzsimmons** [comment]
@specify/ux-testing Let's go over this to make sure this is resolved. Once it has been tested, let's close this issue.

**Comment by maxxxxxdlp** [comment]
There are a lot of tests for the lat long parsing so it should be more stable than many other parts.

Also, here is the breakdown of which characters are now allowed in the input:
- A whitespace character (tab, space)
- A digit
- Any of the following: `"'\-.:ensw°` (case-insensitive)
