### ISSUE TITLE
Show warning in the WorkBench if coordinates do not match localities

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1940]
This would be really helpful when uploading data to the WorkBench to validate that the imported coordinates are correct. This should not block uploading, but rather give a warning of some kind.

*Locality name, as determined by GeoMap or GeoLocate

**Comment by maxxxxxdlp** [comment]
Complicated

**Comment by grantfitzsimmons** [comment]
Closed in favor of #3720
