### ISSUE TITLE
Saving Accession Forms with specific Acc. # formats causes error

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#195]
Found in KUHerps - master branch

In KUHerps, or any other database that uses a specific format for Accession #, the format is pre-entered when you open a new form (e.g. YEAR-AA-###). If you save without entering an actual Accession # in the correct format, you get an error.

Error:
IntegrityError at /api/specify/accession/
(1048, "Column 'AccessionNumber' cannot be null")

**Comment by benanhalt** [comment]
This was caused by the autonumber logic trying to pre-save the record with a null value for the field so that all the business rules can clear before it has to lock the table.
