### ISSUE TITLE
Cannot export distinct query results to CSV

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1956]
In Specify 6, the ability to export the results of a query with "Distinct" checked is available.

In Specify 7, this function is hidden. It seems potentially related to #1464, but as it works in 6, it can be implemented.

**Reported By:** Corinna at CSIRO

**Comment by benanhalt** [comment]
There shouldn't be anything on the back end that prevents this from working. I think it was available pre 7.7
