### ISSUE TITLE
It's possible to save Accession/Loan/Gift agents without roles

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#196]
In the accession, loan, and gift forms, you can add an agent's name, but then save the form without selecting a "role". This shouldn't be possible, as "Role" is a required field.

**Comment by timo11** [comment]
This no longer seems to be possible. Maybe another fix or improvement eliminated this problem? It seems that as long there elements in the role picklist, which there pretty much always should be, it is impossible to not have a role.

**Comment by garrettgirard** [comment]
As Tim mentioned above, this is no longer an issue. It was likely fixed by another bug fix.
