### ISSUE TITLE
Unhide Data Set Mapping export button

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1962]
This would be helpful for me. There are users who have issues with this that would benefit as well.

This can be a preference but I don't see how it hurts (if it is moved under the Tools menu).

**Comment by maxxxxxdlp** [comment]
Upon further discussion, we decided to add `Import` and `Export` buttons in the mapper, rather than expose the JSON object to the user

**Comment by maxxxxxdlp** [comment]
Closing this in favor of #1363
