### ISSUE TITLE
Create data collection form from Data Set Mapping

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1963]
Collections often need to create custom spreadsheets for bringing data into their database. It would be nice to take a created data set mapping and quickly made a data import form for Specify that can be used with the established mapping.

**Comment by maxxxxxdlp** [comment]
Is this a duplicate of https://github.com/specify/specify7/issues/2004 or https://github.com/specify/specify7/issues/1363?

If not, can you explain how is it different?

**Comment by grantfitzsimmons** [comment]
Duplicate of #2004
