### ISSUE TITLE
Can have Quantity Returned/Quantity Resolved larger than actual Quantity

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#197]
In tables that have the "Quantity" field, in Quantity Returned and Quantity Resolved you can enter numbers that exceed the number in the quantity field. For example you can have Quantity = 2, Quantity Returned = 24, Quantity Resolved = 26

**Comment by yvonneekanim** [comment]
This no longer happens; quantity returned/resolved cannot exceed quantity unresolved.
