### ISSUE TITLE
Error message missing a space.

### ISSUE THREAD

**Issue by mc0822** [specify/specify7#1970]
**Describe the bug**
The error text is missing a space.

**To Reproduce**
1. Go to collection object form.
2. On Field No. Locality box, click edit pencil.
3. See error.

**Expected behavior**
There should be a space here.
**Screenshots**
![image](https://user-images.githubusercontent.com/111374878/184929170-190e1e94-0266-45d8-8dee-9512465dd2b3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, macOS
 - Browser: Chrome, Edge
 - Specify 7 Version: testability

**Reported By**

**Additional context**

**Comment by grantfitzsimmons** [comment]
database: `KU_Fish`
