### ISSUE TITLE
Bust cached app resource on changes

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#1977]
If a user edited an app resource, need to tell the browser to bust the cached app resource.

If this is done on the front-end, it can be done for the current user only. If it is done on the back-end (though `ETag` or some other solution), this would clear the cache for all users

---

From @grantfitzsimmons:

> When updating the schema configuration, it automatically clears your cache. 
>
> The same behavior should happen when updating a views file! Bonus points if it can also preserve the current URL.

**Comment by maxxxxxdlp** [comment]
From @grantfitzsimmons:

> Matthew Cruz at UMich also submitted a question about this today. Logging in and out to see your form changes is cumbersome.. especially when the [cache buster often breaks](https://github.com/specify/specify7/issues/2102) making logging in and out faster.

**Comment by maxxxxxdlp** [comment]
Fixed in c00bd8176

Keep in mind, it only clears cache for the browser in which the app resource edit was performed

**Comment by chanulee1** [comment]
Automatically filled cataloger field is not immediately updated with new format. Is this an issue?


https://user-images.githubusercontent.com/103299204/226441408-966a3a4f-8095-44fa-b9ac-1b228849b75e.mp4

**Comment by maxxxxxdlp** [comment]
You could open a separate feature request for that.
For now a page reload is still required
The intention behind the change was to remove the need to manually clean the cache (since if old app resource is cached, even reloading the page won't help)

**Comment by maxxxxxdlp** [comment]
This fix was initially just for app resources.
However, since then a visual form editor has been added.
If you make changes to a form definition using the "Visual Editor" (rather than "XML editor"), every form that you modify will have it's cache cleared

**Comment by maxpatiiuk** [comment]
Note, I discovered a bug with the cache busting in the visual form editor, which might be what @chanulee1 was encountering
Fixed in https://github.com/specify/specify7/pull/4290
