### ISSUE TITLE
Add ability to choose the dataObjFormatter to use for displaying related collection object using the collection relationship plugin.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#1981]
The current plugin represents the related collection object with its catalog number. Since multiple formatters can be defined for a table, it should be possible to define one for use in the plugin. The collectionRelType table should be augmented with two columns "leftSideFormatter" and "rightSideFormater" that would contain the formatter name to use when presenting the related collection object from the other side of the relationship. If the formatter name is null it would default to using the catalog number for continuity with existing behavior.

**Comment by maxxxxxdlp** [comment]
Alternatively, we can extend the plugin definition XML to specify the formatter name

**Comment by benanhalt** [comment]
The UI for configuring the relationships would let the user choose the formatters to use.

**Comment by maxxxxxdlp** [comment]
Yes, but storing that in the database would require a schema change.

As far as UI, this can be handled in the future either in relationship configuration menu (if stored in the database) or the form editor (if stored in the form)

The form definition is already used for specifying uiformatter for some fields:

```xml
<cell type="field" id="10" name="text1" uitype="label" readonly="true"  uifieldformatter="Agent"/>
```

**Comment by maxxxxxdlp** [comment]
Or, do you feel that we should rely less on form definition?

**Comment by benanhalt** [comment]
I'm not sure yet. The formatter to use with a collection relationship seems like a property of the collection relationship and not of the form.

**Comment by grantfitzsimmons** [comment]
Dan from CSIRO:

> Is this ticket suggesting being able to change the fields that are displayed in the relationship plugin to show more than just the catalog number? That is something we would like to see added i.e. the collector, collection date, current determination etc.
