### ISSUE TITLE
Improve pick list fetching performance

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1987]
In Specify 7.7, all pick lists are fetched every time the app opens.

This can take up to 10 seconds to complete if the database is busy, or there are a lot of pick lists.

RGBE experienced performance issues after the update, which in part can be attributed to this.

Need to fix this by returning back to loading pick lists dynamically.

----

For future reference:
Reasons why Specify 7.7 is loading all pick lists on app load, rather than on demand:
- I did it this way just because it was simpler (I fetch all pick lists together so that places that deal with pick lists don't have to deal with async code)
- The other reason is that not fetching things on demand makes UI feel faster, at a cost of slower initial page load time. I did that trade-off because I assumed specify would be opened once and used for several hours.
- Also, this request is not part of the initial context, so it does not block the UI from rendering.

About the only place that really needs to fetch all pick lists is the schema editor.

**Comment by benritchie** [comment]
Picklists still seem relatively slow for us following this change.  
I think this change has helped - previously there was a pause of 10 - 20 seconds when any form loaded.  
now the pause seems longer for more complex forms, which suggests that the change to load on demand has worked.  however, for a complex form, e.g. Taxa or Collection object, it can still easily take 10 seconds.  (quite variable though - maybe depending on DB busyness?)

This is for RBHE hosted database.

**Comment by benanhalt** [comment]
This fix is shipped in the production "edge" build and will go out with in 7.7.2 on Monday. We have your hosted instances pinned to the current stable build 7.7.1 so you aren't seeing the benefit yet, I'm afraid.
