### ISSUE TITLE
Required Fields should not be required when matching

### ISSUE THREAD

**Issue by mc0822** [specify/specify7#1989]
**Describe the bug**
In kufish (6.8.01) DB, edge version.  When mapping WBVoucherdata (3) (Collection Object), mapped to Collection Object Citation > Reference Work > Title, intending to match existing reference work.  When I saved mapping, got an error about missing required fields.

**To Reproduce**
1. Create Collection Object data set.
2. Map a field to Collection Object Citation > Reference Work > Title.
3. Save mapping.
4. Error pops up.

**Expected behavior**
All required fields in a table should not be required by workbench, unless creating a new record.

**Screenshots**
![image](https://user-images.githubusercontent.com/111374878/185248463-9643af8f-d90d-4118-bfd4-a2a214661423.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Edge
 - Specify 7 Version: Edge

**Comment by maxxxxxdlp** [comment]
If you intend to match existing reference works, then set it as a "Must Match" table, and the error will disappear

(all fields in "Must Match" tables are marked as optional)

**Comment by grantfitzsimmons** [comment]
@mc0822 If you are referring to something like a WorkBench data set, you will need to include the username in addition to the database information.

This goes for queries, record sets, or any user-specific resources. :smile:
