### ISSUE TITLE
Agent Last Name should be required field

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#199]
Otherwise you can save without anything in the agent field, which means you can do things like saving a Collection Object form with a blank agent in the Cataloger field. Go to CO form, click + next to Cataloger, don't type or select anything and save, then save CO form.

**Comment by benanhalt** [comment]
Lastname should be required.

**Comment by maxxxxxdlp** [comment]
Form definition can be edited to make that field required - no schema change is required
The question is whether it should be required on the default form definition

**Comment by grantfitzsimmons** [comment]
`lastName` should be a required field in the default form definition & in the default schema config.

**Comment by grantfitzsimmons** [comment]
Now records that have a blank format display like this:
<img width="272" alt="image" src="https://github.com/specify/specify7/assets/37256050/200f85a1-fea5-45b1-9568-d5a8cebc1d56">

This prevents the issue of a 'blank' cataloger from being linked to a collection object as described by @garrettgirard.
Not sure this is a necessary change, but you can reopen if you disagree team!
