### ISSUE TITLE
Grid view collapse button should extend to the full height of the item

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1993]
<img width="390" alt="image" src="https://user-images.githubusercontent.com/37256050/185274835-a92dd0e6-0b02-4f5c-a084-252577370686.png">

When there is a very long form once a grid item is expanded (such as preparations or determinations), it can be difficult to find the button to collapse it. It would be nice if this was clearly a button that extended the height of the item.

**Comment by chanulee1** [comment]
Grid view collapse button extends to full height of item.
db: `freshfish`, `wiillemcatno`
