### ISSUE TITLE
[testability] Include "Generate Invoice" button in the FormPreferences menu

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1996]
> By the way, would it be appropriate to also include that button in the FormPreferences menu?
>
> This way you would be able to create an invoice out of any record, even without adding this button to the form.

_Originally posted by @maxxxxxdlp in https://github.com/specify/specify7/issues/1864#issuecomment-1190357099_

**Comment by grantfitzsimmons** [comment]
<img width="496" alt="image" src="https://user-images.githubusercontent.com/37256050/192677083-240fad4c-1f3e-4289-a9e1-94480fdd7504.png">

For reference
