### ISSUE TITLE
Limit logins based on divisions.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#200]
The first iteration could just reject logins to collections that are not in a division the user has access to. Ideally, the user would not even be given disallowed collections as options, but that would require make the login process two steps, I think... Maybe ajax could be used to adjust the collections list dynamically when the username is entered. Not sure if that is a good idea.

**Comment by johntorgersen** [comment]
Perhaps the login could follow the Specify 6 steps; user would enter credentials, and once authenticated, a modal window would pop-up showing the authorized collections, from which the user could choose.

**Comment by benanhalt** [comment]
There will also have to be a permissions check when following links that involve switching collections.

**Comment by benanhalt** [comment]
Also added UI to add/remove access to collections to user management view.

**Comment by garrettgirard** [comment]
Tested by logging in as guest user with only permission to 2 of the 3 collections in KU Fish. User could only log into the tissue and voucher collections, and when logged in could only switch between the two collections. I was also able to choose which collections each user had permissions to log into (done as testuser/administrator).
