### ISSUE TITLE
Allow downloading empty data set

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2004]
There currently is an option to download a data set with all rows.

It would be useful to be able to download a spreadsheet with column headers, but without any data.

This feature is already present in Specify 6

Requested by @grantfitzsimmons and CSIRO

**Comment by grantfitzsimmons** [comment]
Specify 7 already supports this, there should be a button or UI to automate this process however. 

**Steps to accomplish this:**

_This assumes you already have the WB mapping assigned to an existing upload._

1. Create a new data set with no content
2. Click "Choose Existing Plan"
3. Save the mapping
4. Go to grid editing mode
5. Export data set

Now you have a data set mapping with only the column headers. You can reupload this and use the mapping after collecting information!

**Comment by melton-jason** [comment]
What would be the preferred workflow for such a button, and what should it do? 
Would it just be a button to export the column headers (thus the mapping) for a WorkBench dataset, regardless of the data in the rows?

**Comment by grantfitzsimmons** [comment]
Well– as I described in August, this already exists. I don't know if there needs to be a button. Maybe we could move the "Export" button from under the "Tools" submenu to the main grid view? It's really already supported.

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp Please reopen if you think this needs to be improved/changed, or if you have a better idea!
