### ISSUE TITLE
Adding addressOfRecord to Borrow breaks the form

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2006]
> I’ve been having some issues with the Borrow form in S7 and I think I have narrowed it down to the addressOfRecord subform.
> 
> The below xml code to add the addressOfRecord subform as a button works fine in the Loans. The Borrow form with this snippet opens in S6, however, in S7 I get an error message (see attached). I also get an error when converting it to a ‘normal’ subform. When I edit out the subform altogether, the Borrow form opens in S7 as well.

`<cell type="subview" id="aor" name="addressOfRecord" viewname="AddressOfRecord" initialize="btn=true"/>`
 

Error message:
```
Cannot read properties of undefined (reading 'model')
 
Stack:
 
TypeError: Cannot read properties of undefined (reading 'model')
    at d (http://anwc.specify-dev.csiro.au/static/js/main.2378b38b2f21141133e8.bundle.js:2:25863)
    at AddressOfRecordDependentCollection.initialize (http://anwc.specify-dev.csiro.au/static/js/main.2378b38b2f21141133e8.bundle.js:2:26218)
    at n.Collection (http://anwc.specify-dev.csiro.au/static/js/main.2378b38b2f21141133e8.bundle.js:2:345732)
    at AddressOfRecordDependentCollection.CollectionBase [as constructor] (eval at c (http://anwc.specify-dev.csiro.au/static/js/main.2378b38b2f21141133e8.bundle.js:2:17494), <anonymous>:6:17)
    at AddressOfRecordDependentCollection.constructor (http://anwc.specify-dev.csiro.au/static/js/main.2378b38b2f21141133e8.bundle.js:2:26116)
    at AddressOfRecordDependentCollection.DependentCollectionBase [as constructor] (eval at c (http://anwc.specify-dev.csiro.au/static/js/main.2378b38b2f21141133e8.bundle.js:2:17494), <anonymous>:6:17)
    at new AddressOfRecordDependentCollection (eval at c (http://anwc.specify-dev.csiro.au/static/js/main.2378b38b2f21141133e8.bundle.js:2:17494), <anonymous>:6:17)
    at http://anwc.specify-dev.csiro.au/static/js/185.fc70b8fffe6ae0eb5b94.bundle.js:1:178701
```
 
 **Reported By:** Corinna at CSIRO

**Comment by maxxxxxdlp** [comment]
@benanhalt I have a question on what would be the best solution to this issue 

It occurs because when SubView tries to create a DependentCollection for the Borrow -> addressOfRecord relationship, it needs the reverse relationship (required by the DependentCollection constructor).
But, the reverse relationship does not exist

Should I modify the collectionApi.js to support cases like this, or is this already supposed to be supported and I am just using it wrong?

**Comment by benanhalt** [comment]
What do you mean the reverse relationship doesn't exist? Which direction is the foreign key?

**Comment by maxxxxxdlp** [comment]
There is a `Borrow -> addressOfRecord` relationship:

![Screen Shot 2022-09-13 at 10 29 49](https://user-images.githubusercontent.com/40512816/189943463-d1ad2831-a39c-4b5c-beb5-ec9f5ba6f699.png)

But there is no `AddressOfRecord -> Borrow` relationship. The reverse relationship is required by the constructor of the collectionapi. My questions is whether we need to modify the constructor of collectionapi

References:
https://github.com/specify/specify7/blob/929bb5bff25f8faa06235798bc87afa0ad760f71/specifyweb/frontend/js_src/lib/resourceapi.js#L300
https://github.com/specify/specify7/blob/d9776d60818d6a0b2e79dc56c79736fbfadc5140/specifyweb/frontend/js_src/lib/components/subview.tsx#L59
https://github.com/specify/specify7/blob/7fd134e3c8368fbc3adf243499fb768807d574ec/specifyweb/frontend/js_src/lib/collectionapi.js#L56

**Comment by benanhalt** [comment]
I think it is just missing the "other side name"? Sometimes those aren't defined in the Sp6 schema. I would add it in https://github.com/specify/specify7/blob/929bb5bff25f8faa06235798bc87afa0ad760f71/specifyweb/frontend/js_src/lib/schemaextras.ts

**Comment by maxxxxxdlp** [comment]
I am nore sure if that would make a difference. The `field.getReverse()` returns the reverse field, not just reverse field name 

https://github.com/specify/specify7/blob/d9776d60818d6a0b2e79dc56c79736fbfadc5140/specifyweb/frontend/js_src/lib/specifyfield.ts#L294-L297

Since the reverse field does not exist, it will return undefined, just like it does right now.

**Comment by benanhalt** [comment]
I'm going change this relationship to not be dependent. Then it can be a query combo box instead of a subview.

**Comment by maxxxxxdlp** [comment]
See https://github.com/specify/specify7/pull/2155#issuecomment-1251365484 for the resolution

**Comment by specifysoftware** [comment]
This pull request has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-7-3-release-announcement/774/1

**Comment by specifysoftware** [comment]
This pull request has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-7-4-release-announcement/807/1
