### ISSUE TITLE
Importing a query does not save query automatically

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2010]
[Screen Recording 2022-08-19 at 6.11.13 PM.webm](https://user-images.githubusercontent.com/37256050/185718173-4b130b82-ac78-44a2-a10c-a8f55caa39fd.webm)

After importing a query from a JSON file, I need to click Save As to finish the import. It believes that the current imported query already exists, but after removing the unnecessary (2) from the title, it saves properly.

**Comment by maxxxxxdlp** [comment]
Appears fixed
Likely fixed as part of https://github.com/specify/specify7/pull/3055 or https://github.com/specify/specify7/pull/3029
