### ISSUE TITLE
Zooming into the taxon tree causes the view to disappear

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2011]
[Screen Recording 2022-08-19 at 6.21.56 PM.webm](https://user-images.githubusercontent.com/37256050/185718756-72fdc8b1-bba6-4873-9f8d-439e463287e2.webm)

Using a trackpad in Google Chrome, I cannot zoom in to read an item in the taxon tree.

db: `newmexico-july22`
user: `zrogers`
browser: Google Chrome
OS: macOS Monterey

**Comment by maxxxxxdlp** [comment]
Superseded by #2775
