### ISSUE TITLE
[testability] Return app resource and view resource filters to the menu

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2012]
It would be nice to be able to select the default filters by clicking "view" or "app" before loading the resources

**Comment by maxxxxxdlp** [comment]
Isn't it like 2 clicks?
Open the filter menu, and press the checkbox next to "View Sets" or "App Resources"

**Comment by grantfitzsimmons** [comment]
I would argue it is 2 clicks too many-- I will often be doing this action many times a day! When testability is working for me (currently cannot log in with `KU_Fish`) I'll give it another shot
