### ISSUE TITLE
Query Comboboxes no longer respecting criteria set in query combobox editor

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#2014]
Discovered by Calvert Marine Museum (hosted by us in Cloud)

They reported that their paleo context query combobox was no longer searching for paleo context records based on lithostrat.fullName, which they were able to do a few weeks ago.

I checked their database in 7.6.1 and 7.7 and confirmed that in 7.6.1, they could search on the term "calvert" and results would populate in the drop down list, but in 7.7, no results were returned.

https://user-images.githubusercontent.com/12532430/185995209-624771d9-6d1d-4cd8-a9f4-2b284231d7ef.mp4

**Comment by grantfitzsimmons** [comment]
> It appears the bug is not fully resolved. Now a drop down menu comes down but we’re not able to find and select the proper value. The Search function doesn’t work either.
> 
> Any chance at getting Litho Strat and Chrono Stray separated again?

**Reported By: John at Calvert**

**Comment by maxxxxxdlp** [comment]
> but we’re not able to find and select the proper value. The Search function doesn’t work either.

The user report is very ambiguous.

The query combo box returns lots of duplicate and empty values, but that's because there a lot of duplicates in their database.

![image](https://user-images.githubusercontent.com/40512816/192002593-9e48a34d-4c8e-48fb-99d1-b46c7bde210d.png)

@grantfitzsimmons  will ask for more information

**Comment by grantfitzsimmons** [comment]
Before I request more information, this behavior should be fixed:

>![image](https://user-images.githubusercontent.com/37256050/192005857-714d4e70-0d9a-4c9f-a3e4-45923609f349.png)
>
>![image](https://user-images.githubusercontent.com/37256050/192005867-a75ab65b-4e20-41f7-9365-9fcf5e09982a.png)
> They search by the “formation” which is part of the LithoStrat full name
> 
> Because it is at a random place in the Paleo context full name rather than at the start, it is not being prioritized
> 
> Try to search Aquia Formation in their QCBX and you’ll see an issue
> 
> It’s clear to me now that they want to type “calvert” and get all results with a lithostrat full name containing “Calvert Foundation”
>![image](https://user-images.githubusercontent.com/37256050/192005976-fdb893c4-f4a6-41db-8cbb-7830b5c94677.png)

**Comment by maxxxxxdlp** [comment]
Ah, looks like query combo box filtering was not working at all because of a different bug -  https://github.com/specify/specify7/issues/2038

I will close this issue in favor of that one as the original bug here has been resolved.

I will work on fixing #2038 right now
