### ISSUE TITLE
Unable to change collection name

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2025]
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/37256050/186298015-99173cac-9336-41cd-a071-8f1d7a032cc5.png">

db: `newmexico_august22`

`(1205, 'Lock wait timeout exceeded; try restarting transaction')
`--

**Comment by beach53** [comment]
That is a great error message dialog.
![image](https://user-images.githubusercontent.com/10891506/186451564-f5296f64-0653-440d-b104-4253e102b47c.png)

**Comment by maxxxxxdlp** [comment]
Well, you wrote it, so yeah, it is great 😄

**Comment by emenslin** [comment]
Fixed
