### ISSUE TITLE
Customize error message based on error type

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2028]
The `Invalid response code 504. Expected  200. Response: ...` error message is not very helpful to a non-technical user.

It would be helpful to display a brief description of a problem and possible solutions (in this case, 504, Gateway Time-out, occurs because server is overloaded, and did not respond to a front-end requests within 60 seconds)

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons says that 500 error is very common and that more should be done to explain the potential causes in the error message

**Comment by grantfitzsimmons** [comment]
Any `Error: Value is not defined` needs to do better. It is possibly the least helpful thing for a user possible

**Comment by maxxxxxdlp** [comment]
The `Value is not defined` error message should never happen again

The unexpected response code error would now have a message explaining the likely cause and possible solutions.

![Screen Shot 2022-09-14 at 10 15 07](https://user-images.githubusercontent.com/40512816/190194542-9321d985-2238-4202-994f-1a508f4e7cbc.png)

For testing purposes, you can open the `/specify/command/test-error` page in Specify to trigger an error

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons here is the file that defines the error message for each Http response code - https://github.com/specify/specify7/blob/4b93058a678ea80d9c31ba8baac2f30be33cb574/specifyweb/frontend/js_src/lib/utils/ajax/definitions.ts

Feel free to edit that file to provide more details or improve the error messages
