### ISSUE TITLE
Paleo Trees showing Root as preferred value when not synonymized

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#2029]
Discovered in PRIPaleo (because they added preferred chronostrat and preferred lithostrat to their forms) in the edge version.
When viewing a lithostrat or chronostrat record for a value that is not synonymized, the Preferred Lithostrat or Preferred Chronostrat value is Root.
When the value is synonymized, the preferred value is displayed in that field.

This did not happen in 6.7.1.  It left the field blank when there was no synonymized value.

**Comment by emenslin** [comment]
Fixed
