### ISSUE TITLE
Show that activity is occurring when find & replace is happening

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2033]
The WorkBench should show that activity is occurring when find & replace is happening.

**Reported By:** RBGE

**Comment by maxxxxxdlp** [comment]
How long does find & replace take?

It should be quite instantenous for all but the largest data sets

**Comment by grantfitzsimmons** [comment]
I haven't had an issue with this operation taking much time.

**Comment by maxxxxxdlp** [comment]
Not high priority, but @grantfitzsimmons can you ask RGBE what they meant by this?
