### ISSUE TITLE
Store carry forward and auto numbering preferences in user prefs

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2037]
They are currently stored in local storage (in browser)

@grantfitzsimmons suggests it would be better to store them in user prefs to have them preserved

**Comment by maxxxxxdlp** [comment]
Fixed. All form preferences are now stored in user preferences, and thus will be synced between computers. Scoped to user and collection

**Comment by chanulee1** [comment]
Form prefs configs remain after clearing browser cache.
db: `willemcatno`
col: `BRUV Fish`
user: `collection`
