### ISSUE TITLE
[testability] Resource editor should have shrink icon

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2039]
Currently when you full screen an app resource, the full screen button icon remains the same when the action is now to shrink. Something like this:

<img width="200" alt="image" src="https://user-images.githubusercontent.com/37256050/186744296-065ac31a-a233-4a42-afed-84b498ff8d0a.png">

<img width="1275" alt="Screen Shot 2022-08-25 at 1 43 40 PM" src="https://user-images.githubusercontent.com/37256050/186743860-e409b30b-5703-400b-a145-8957cbac11ef.png">

**Comment by chanulee1** [comment]
Full screen icon when minimized, shrink icon when maximized.
db: `willemcatno`
