### ISSUE TITLE
Lost Field Title

### ISSUE THREAD

**Issue by jobdiogenes** [specify/specify7#204]
Some notes:
I am using the last version get from github.
ThickVersion , latest using Portuguese.

But, when make a search lost some column titles and in form lost all (attached screen) !

Thanks

![captura de tela de 2015-11-23 18 23 25](https://cloud.githubusercontent.com/assets/1182381/11348716/506e25fc-920f-11e5-9bce-dff03ff22815.png)

**Comment by tlammer** [comment]
Job,
I forwarded your email onto our programmer who works on Specify 7.  He or I will be in contact with you about the issue.
Theresa

**Comment by benanhalt** [comment]
Job, if you 'git pull' on the master branch and add 
```
SCHEMA_LANGUAGE = 'pt'
```
to your `local_specify_settings.py` file, I believe your form labels with appear.

**Comment by tlammer** [comment]
Job,
Please let us know if Ben's fix works for you or if you are still having issues with the captions.
Theresa

**Comment by jobdiogenes** [comment]
Theresa,

Yes, its working now. Great!

Thanks very much.

Job Diógenes
Em 24/11/2015 20:37, "Theresa Miller" <notifications@github.com> escreveu:

**Comment by jobdiogenes** [comment]
Hi Ben,

Yes its working, thanks.

Ben,
I am wondering  about reports in Specify7, and find that already has some
code inside, like  toolbarreport.js.
Since I really want reports soon, I would like to help , making tests and
code also (I play with Django some years ago).
There are some branch which Reports Menu are Working?

Thanks

Job Diogenes


2015-11-24 19:34 GMT-02:00 Ben Anhalt <notifications@github.com>:

**Comment by benanhalt** [comment]
The report system already exists but requires a separate server process. This is here: https://github.com/specify/report-runner-service

**Comment by jobdiogenes** [comment]
Hi Ben,

I follow the instructions, make changes in configurations, compile at end
call "mvn jetty:run".
Well, the server starts, but, did not appear in specifyweb, I restart
apache/specify, but still didn't appear.
Another question, how can I make this a process, since mvn jetty:run, is a
hand call.

Thanks

Job




2015-11-25 16:00 GMT-02:00 Ben Anhalt <notifications@github.com>:

**Comment by jobdiogenes** [comment]
Hi Ben,

Discard last email, I thinh that are a cache problem, now are working.

Thanks!

Job

2015-11-25 17:05 GMT-02:00 Job <jobdrb@gmail.com>:

**Comment by benanhalt** [comment]
I added a section to the readme for the report runner service including the Ubuntu upstart script I use to start it.

**Comment by jobdiogenes** [comment]
Hi Ben,

Great, I make the start script, and start ok.

I test using my config local_..., jetty.xml (localhost, and port 9090) and

- did not show when using Google Chrome.

- I get "500 error" in one report.
- I get the following error in a report with picture.

[image: Imagem inline 1]:


Thanks all,


Job Diogenes



2015-11-25 17:20 GMT-02:00 Ben Anhalt <notifications@github.com>:

**Comment by benanhalt** [comment]
Job,

The linked image doesn't appear for me. Can you email us directly at specify@ku.edu? Probably there is something in your reports that Specify 7 doesn't understand, yet. If you could export the report definitions and email them to us, I can try to see what it is.
