### ISSUE TITLE
[testability] Query becomes unusable after modifying

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2040]
https://user-images.githubusercontent.com/37256050/186749292-3ea4849c-d5df-4eae-8743-0db3acf97b8f.mov

**Recreate:**
1. Open an existing query
2. Delete an item from the query
3. Try to run query

db: `KU_Fish`
query: [this one](https://kufish-testability.test.specifysystems.org/specify/query/3/)

**Comment by grantfitzsimmons** [comment]
Not fixed as far as I can tell.

**Comment by maxxxxxdlp** [comment]
Pushed the fix. Should be fixed now

**Comment by chanulee1** [comment]
Looks good.
Tested:
db:`KU_Fish`, user:`spfishadmin`
