### ISSUE TITLE
[testability] Pick list values can be changed in read-only mode

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2041]
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/37256050/186753308-ea1f9bbd-39a8-4302-9344-b2adf52cbab1.png">

db: `KU_Fish`

**Comment by maxxxxxdlp** [comment]
Unable to replicate it. Probably fixed by https://github.com/specify/specify7/pull/1986
