### ISSUE TITLE
[testability] Unable to view gifts associated with a preparation

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2042]
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/37256050/186753772-445484bb-b7f0-448f-a562-c9d33e669342.png">

I'm in read-only mode in this instance, but I went to [this record](https://kufish-testability.test.specifysystems.org/specify/view/collectionobject/43653/) as `abentley` in the `KU_Fish` database.

**Comment by chanulee1** [comment]
Can view gifts associated with a preparation.
db: `KU_Fish`
col: `KU Fish Tissue Collection`
users: `abentley`, `spfishadmin`
