### ISSUE TITLE
Forms should have a 'close/exit' button

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2048]
> All forms should have a ‘Close/Exit’ button and re-direct to the S7 main-screen where applicable. Feedback from one of our UAT sessions: “When wanting to close a window or if wanting to get out of an object (‘exit’), is there a ‘close button’ or do we just go back with the back arrow – in new collection object, only options are clone, add another, save?”

**Requested By:** **[CSIRO](https://app.asana.com/0/1201972579963460/1202844554923815/f)**

**Comment by maxxxxxdlp** [comment]
We can mention during our webinars, that like in most web applications, you can exit the current page by clicking on the page logo, or by pressing the "x" button in the browser tab bar to close the tab.

An explicit close button is currently provided for dialogs only.
