### ISSUE TITLE
Trees should have 'collapse/expand all' buttons

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2050]
**Requested By:** **[CSIRO](https://app.asana.com/0/1201972579963460/1202844554923815/f)**

**Comment by maxxxxxdlp** [comment]
We can add a "Collapse all" button

"Expand all" won't  be hard to implement, except that it will choke the web server

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-5-release-announcement/1023/1
