### ISSUE TITLE
Add the ability to only show tree nodes applicable to the selected collection

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2051]
> Add the ability to only show tree nodes applicable to the selected collection

**Requested By:** **[CSIRO](https://app.asana.com/0/1201972579963460/1202844554923815/f)**

**Comment by maxxxxxdlp** [comment]
How do you define "nodes applicable to the selected collection"?

Tree nodes are not scoped to a collection

**Comment by danb213** [comment]
What we would like is to have a tick box to be able to remove any node where the count of records under it is zero. We have instances where some collections have taxons that don't appear in other collections, so we'd like to just see the relevant info when we look at the tree in those collections. It can be confusing to our users when they open up a tree branch when browsing a particular collection to find that there are actually zero records.

In the example below we have no records in our terrestrial vertebrate collection for any Arthropoda so we'd want that to not appear (all the insects are referenced in our Sounds collection). In this case the tree could be tided right up to the Phylum rank.

![image](https://user-images.githubusercontent.com/110948439/187343857-6744b34e-1a39-4100-a40f-8e64893a4b72.png)
