### ISSUE TITLE
Ability to bulk associate collection object relationships from the form

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2052]
It would also be great if we could add these links between two existing collection objects in bulk at a later time.

**Fixed:**

_> On a typical field trip ~300 specimens may be collected, each of which will have ~10 tissue samples. We upload the specimens into one collection and the tissue samples into another and use the collection relationship tables to link them. This has worked well for the data migrated into Specify but doesn’t seem to be possible to do in bulk – I haven’t been able to produce a mapping scheme in the workbench to cover this and the plugin on the collection object form only lets you add one link at a time (even though your query can bring back many rows). It would be great if we could have a column in the workbench that let us reference the catalogue number of either an existing collection object, or one that is included in the same workbench upload file._ 

**Requested By:** **[CSIRO](https://app.asana.com/0/1201972579963460/1202851937227962/f)**

**Comment by maxxxxxdlp** [comment]
This might be fixed by https://github.com/specify/specify7/pull/2043

@grantfitzsimmons Can you try this on that branch?

**Comment by grantfitzsimmons** [comment]
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/37256050/187497407-5bd1166d-476e-4d23-895b-6aa8633fd4c7.png">

CoR component still only lets you add one at a time.

**Comment by grantfitzsimmons** [comment]
This is not fixed by #2043

**Comment by grantfitzsimmons** [comment]
Updated issue to include only the not fixed component

**Comment by maxxxxxdlp** [comment]
Seems to be fixed now. Please test again

**Comment by chanulee1** [comment]
Error occurs.
<img alt="image" width="500px" src="https://user-images.githubusercontent.com/103299204/197671051-870a1f71-cd61-4af8-9fee-0d3ffeb85ab1.png"/>

Link: https://kufish-testability-2.test.specifysystems.org/specify/view/collectionobject/new/

**Comment by maxxxxxdlp** [comment]
The error is unrelated to this issue.

The error happens because the formatter for CollectionObject  includes a -to-many relationship (determinations), which is not supported at present:

<img width="1800" alt="Screen Shot 2022-10-24 at 22 17 43" src="https://user-images.githubusercontent.com/40512816/197674278-5280f9e7-ac3f-4dcc-bd5d-5118bc697251.png">

(I am not sure if that is supported in sp6)

I removed it and it is working now. Can you try testing again?

**Comment by chanulee1** [comment]
I see. The error still seems to occur...

**Comment by chanulee1** [comment]
Sorry. Did not test the right branch.

**Comment by maxxxxxdlp** [comment]
Can you try it again in an incognito browser tab? Your browser probably just cached the older version of that file

**Comment by chanulee1** [comment]
I see. It seems to work!
db: `KU_Fish`
