### ISSUE TITLE
all column headers must be unique error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2055]
<img width="1485" alt="Screen Shot 2022-08-26 at 9 16 40 AM" src="https://user-images.githubusercontent.com/37256050/186924274-98f0aae5-20f5-4bfa-ba90-93567fdeada8.png">

[Spreadsheet](https://docs.google.com/spreadsheets/d/1Ao3Vu2gXXCKe5VvQF8enrKDec3j67r-1?rtpof=true&authuser=grant%40specifysoftware.org&usp=drive_fs)

**Comment by maxxxxxdlp** [comment]
It's a bug. It was already fixed on `testability`, thus just have to merge that branch

Happens whenever there are 3 or more headers with the same name.

In this spreadsheet it is `Text 1`, `Text 2`, `Text 3`, and `--`
