### ISSUE TITLE
Resizing text box causes stuttering

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2060]
https://user-images.githubusercontent.com/37256050/187321030-8ec11ce0-e115-423c-a7dc-d371bfe9655d.mov

db: `newmexico_august22`
browser: Chrome
OS: macOS Monterey

**Comment by maxxxxxdlp** [comment]
I'm surprised this isn't Safari 😄

**Comment by emenslin** [comment]
Could not reproduce
