### ISSUE TITLE
Specify 7.7.1 reports version as "edge"

### ISSUE THREAD

**Issue by benritchie** [specify/specify7#2067]
**Describe the bug**
Specify 7.7.1 reports version as "edge" rather than 7.7.1

Just been upgraded.  Here's the about box info:
![image](https://user-images.githubusercontent.com/8005676/187481976-51afb8ba-98e8-4f25-9714-598f2ce37488.png)

**Comment by benritchie** [comment]
Git SHA is correct by the look of it, so I think we are running the right version, just its versioned wrong.  
This is a hosted system.

**Comment by maxxxxxdlp** [comment]
Your SpCloud instance is running the `edge` build, which includes 7.7.1, and all new bugs that we fixed since the last tagged release. (`edge` build is tracking the `production` git branch)
