### ISSUE TITLE
Inconsistent behavior between running a report from record set or query

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2068]
When running a report from a record set, the query is ignored and the report pulls the necessary fields from the records. When running from a query, the report is built based on the results returned from only those fields in the query.

> We’re noticing that when we run labels through the Report Query that the taxon name come up as ‘null’ but when label reports are made through a record set (as we most frequently do) the taxa are populated as expected.

e.g.,  “Reports” -> Small labels -> Query ->”13241” (catalog number)->
![image](https://user-images.githubusercontent.com/37256050/187490371-c1f8df68-700e-4f6d-9c7e-76a7b0e971e6.png)

“Reports” -> “Small Labels” -> Record set with #13241 ->
![image](https://user-images.githubusercontent.com/37256050/187490379-49f5a599-a3a8-4a51-871e-2d54ca29e6c5.png)

To solve this, you can add the missing field specified in Jaspersoft Studio to the query:
Determinations -> Taxon -> (any rank) -> Preferred Taxon -> (any rank) -> Full Name -> Any

Should this behavior be made consistent? Should the query be run on the records contained in the record set?

**Reported By:** Paul Larson at FWRI

**Comment by grantfitzsimmons** [comment]
Paul Larson reported this as an issue

> I have a weird issue with labels: If I generate labels using the report query, the taxon comes back as “null”
> 
> ![image](https://github.com/specify/specify7/assets/37256050/0b35a5c5-922f-4b3a-bdd1-2af9da4cf684)
> 
> But when I go to the record directly and click on ‘generate label’ then the taxon is properly populated  (genus only, in this case)
> 
> ![image](https://github.com/specify/specify7/assets/37256050/44686daa-1622-4a17-add9-7bf6bbad484c)
> 
> This doesn’t seem to affect my small or large labels, only the “mini” size. Do you have any insight on this?

**Comment by grantfitzsimmons** [comment]
This same issue was reported again by Paul with the Mini labels.

**Comment by melton-jason** [comment]
I believe this might have the same cause as #3570 and/or #3141. 
We don't have to close one as a duplicate or merge these issues just yet, but it is something to consider

**Comment by grantfitzsimmons** [comment]
I was thinking that as well. We need to investigate!

**Comment by grantfitzsimmons** [comment]
This was reported again today by Paul:

> Hi there, I’ve just come across a strange issue – not sure if it’s a known bug or not, so I’m emailing first rather than adding a bug to the github list.
> 
>  
> 
> I have a label type that uses the ‘Full_Name’ field and that field populates only in certain circumstances. If I generate the label directly from the collection object form, or as part of a record set everything is fine, but if I paste a comma-separated list of catalog numbers into the label query, that field comes back as null.  I have mainly been printing labels from record sets in the past so I’m not sure if this is new behavior or not, but other folks just alerted me to this.
> 
>  
> 
> Another odd thing is that sometimes the spacing of the fields changes so that the same generated label will have two fields overlapping one time, but the next time I generate it they don’t overlap. But I haven’t been able to figure out the circumstances of that, so may be harder to pin down.

**Comment by grantfitzsimmons** [comment]
I believe this is the same as https://github.com/specify/specify7/issues/3570 and https://github.com/specify/specify7/issues/3141

**Comment by melton-jason** [comment]
> I believe this is the same as #3570 and #3141

I think that assumption is correct. 
This can be tested in #4299. 
Even if not immediately resolved by the PR, I would argue the fix for this issue be included: it would be very similar to  #3570 and #3141
