### ISSUE TITLE
Icon in separator does not appear

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2074]
<img width="770" alt="image" src="https://user-images.githubusercontent.com/37256050/187717955-18ec0f36-78a9-4dac-bd4e-d9da60ecf132.png">

It appears like this with the following lines:

```
<cell type="separator" label="Collection Object" icon="sgr" colspan="14"/>
```

```
<cell type="separator" label="Collection Object" icon="sgr.png" colspan="14"/>
```

<img width="813" alt="image" src="https://user-images.githubusercontent.com/37256050/187717540-05458588-93b6-4ee1-8387-85398299e748.png">

Also had no luck establishing an icon when using the `forClass` attribute with the table name. It autogenerated a CO rather than using the icon.

https://github.com/specify/specify7/wiki/Form-System#separator

Please let me know if i have this configured incorrectly.

browser: Chrome & Safari
version: 7.7.1

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-4-announcement/999/1
