### ISSUE TITLE
Allow customizing the delimiter on data set import

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2076]
A file with `.csv` extension may be tab delimited.

WorkBench fails on that right now.

**Comment by grantfitzsimmons** [comment]
When I change the extension to TSV, the same issue occurs. Excel and Numbers can properly interpret the file while the WorkBench fails

**Comment by maxxxxxdlp** [comment]
Fixed by allowing to customize the delimiter during the import process

**Comment by grantfitzsimmons** [comment]
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/37256050/188719085-ff39a666-2029-4983-92ee-d33dd1412258.png">

**Comment by grantfitzsimmons** [comment]
Really awesome feature.
