### ISSUE TITLE
Exsiccata and Exsiccataitem hidden in the WorkBench

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2077]
> I can no longer find the tables Exsiccata or Exsiccataitem to map on. However, they were both available in Sp7.7.0’s WB.

I was able to recreate this.

1. Unhide ExsiccataItem from the CO table
2. See you can map to it in the query builder
3. Try to map in the WB (not possible)

**Reported By: Iñigo at CSIC** ([Forum post](https://discourse.specifysoftware.org/t/still-a-low-limit-on-dataset-size-when-uploading-with-sp7-7-1-worbench/635))

version: `edge` and `7.7.1`
browser: chrome
db: `KU_Fish`

**Comment by maxxxxxdlp** [comment]
Requested by Biodiversity Informatics Unit (UTIB). Real Jardín Botánico - CSIC. Spain

**Comment by maxxxxxdlp** [comment]
It's a bug.

All tables that ended with `Item` were removed from the WorkBench.
When I wrote that rule, I had `TaxonTreeDefItem`, `GeographyTreeDefItem` and other tree def item tables in mind.
I did not think about `ExsiccataItem`

Fixed
