### ISSUE TITLE
Custom display aggregation causing an error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2079]
<img width="2559" alt="image" src="https://user-images.githubusercontent.com/37256050/187933801-257f1ae5-a8f0-4169-a07e-ba6181c68de3.png">

**(formatted) display in query:** Just E of Laguna Indian Reservation boundary in Blue Water Canyon, ca. 13 air miles SSE of Acoma Pueblo.; United States, New Mexico, Cibola County; 34.7185235000, -107.5273120000 , 34°43.11141' , 34°43.11141', , -107°31.63872'

**Display in QCBX on form:** Just E of Laguna Indian Reservation boundary in Blue Water Canyon, ca. 13 air miles SSE of Acoma Pueblo.

I'm sure that the error is related to the formatting configuration I have established. Of course, the error is not helpful at all in discovering this.

db: `newmexico_august22`
https://newmexicoaugust22-match-arbitrary-agent.test.specifysystems.org/specify/view/locality/42936/

**Comment by maxxxxxdlp** [comment]
Unfortunately, I am not able to replicate the exception anymore.

The error is because you used an unknown field or misspelled a field name in your formatter definition

The "Value is not defined` error won't happen on `testability` anymore. It would provide a more helpful message instead.

Also, this kind of error would be prevented completely once we have a formatter editor

**Comment by grantfitzsimmons** [comment]
This was because I had the Locality details field in the display aggregation. This was all done using the UI in Specify 6, no custom configuration otherwise

**Comment by maxxxxxdlp** [comment]
Unable to replicate with the locality details field in the locality DataObjFormatter
Can you try to replicate this again and then send me the DataObjFormatter app resource?

**Comment by grantfitzsimmons** [comment]
I had this miconfigured. I don't have the exact details anymore. I'm kicking myself for not including the DataObjFormatter file.
