### ISSUE TITLE
Allows importing non-supported file types (.xls, etc)

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#208]
After selecting a spreadsheet (import file) for importing into the workbench, you are taken to the mapping interface screen. Here, if you try to create a new mapping and then click "Create" and then click "Done", or if you try to use an existing mapping and click "Import", you run into the following error and must reload or go to the previous page.

Error Message:
Error at /api/workbench/import/
line contains NULL byte

Request Method: POST
Request URL: http://db2.biwebdbtest.nhm.ku.edu/api/workbench/import/
Django Version: 1.5
Python Executable: /usr/bin/python
Python Version: 2.7.3
Python Path: ['/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/anhalt/specify7-master']
Server time: Tue, 2 Feb 2016 15:17:44 -0600
Installed Applications:
('django.contrib.sessions',
 'django.contrib.staticfiles',
 'specifyweb.specify',
 'specifyweb.stored_queries',
 'specifyweb.businessrules',
 'specifyweb.express_search',
 'specifyweb.context',
 'specifyweb.attachment_gw',
 'specifyweb.frontend',
 'specifyweb.barvis',
 'specifyweb.report_runner',
 'specifyweb.interactions',
 'specifyweb.workbench',
 'raven.contrib.django.raven_compat')
Installed Middleware:
('django.middleware.gzip.GZipMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'specifyweb.context.middleware.ContextMiddleware')

**Comment by garrettgirard** [comment]
UPDATE: So the reason this actually was happening is because I was trying to import a .xls file which is NOT supported by workbench in Specify 7 (as should be noted by users in the fine print: "Import Dataset from CSV"). This was a silly mistake, but one that undoubtedly several users will make, as this is the file type they are used to importing.

So, instead of Specify throwing and error, the user should be given a warning when trying to import files that aren't supported, and maybe instructing them to use the suggested .csv file type.

**Comment by benanhalt** [comment]
Most browsers should now default to showing *.csv files in the file chooser.

**Comment by garrettgirard** [comment]
Verified in AMNH Invp database.
