### ISSUE TITLE
`guid` field is not populated for Taxon records on save

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#2081]
As seen by the API response

Reported by @grantfitzsimmons

**Comment by grantfitzsimmons** [comment]
Also for the Geography tree. This was intentionally decided, but maybe we should consider that the generated GUIDs can be overwritten in the future if so desired anyway.

I think it would be nice if we could use any field as a GUID. Maybe any string field could have GUID generated in it if the form definition specified it? Is that possible?

**Comment by emenslin** [comment]
Closed in favor of #4243
