### ISSUE TITLE
Replace Specify logo with SVG

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2082]
I have remastered the Specify logos as SVGs. I think it is a good idea to replace the logo with an SVG.

> In short, as you can see there are a lot of advantages of SVG: scalability, SEO friendly, editing ability, and resolution independence. The SVG format of font and icons is especially advantageous; we should implement them in daily web design.

**Source:** https://www.appnovation.com/blog/benefits-scalable-vector-graphics-svg

**Comment by maxxxxxdlp** [comment]
Could also make logo hue customizable to match user's preferred color

**Comment by grantfitzsimmons** [comment]
Jim says he likes the rainbow too

**Comment by maxxxxxdlp** [comment]
Fixed by @grantfitzsimmons  in fed487003 and 7c31c8c67

The logo hue does not yet follow the user's accent color yet. Maybe for future release

**Comment by grantfitzsimmons** [comment]
I can't wait for an accent color logo option.
