### ISSUE TITLE
Can save dataset after deleting it

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#209]
I'm not completely sure what the problem is here, but it's likely related to the steps I took up until I got the error. First, I imported a spreadsheet successfully. Next, I deleted the newly created dataset, while still viewing this dataset in Workbench. Finally, I saved and then got the error. You can see how this is problematic, considering I just deleted the dataset before saving it. After reloading the page, you get a 404 error as this dataset no longer exists.

Error Message:
AssertionError at /api/workbench/rows/15/
([], [13884, u'Bu-0094c', u'Simone', u'Sheridan', u'00/00/2002', u'Asia', u'Myanmar', u'Kachin', u'Myitkyina', u'Amber mines, Hukawng Valley', u'Mesozoic', u'Cenomanian', u'', u'', u'Leeward Capitol Corp.', u'01/01/1999', u'31/12/1999', u'1999', u'Animalia', u'Arthropoda', u'Arachnida', u'', u'', u'Araneae', u'', u'', u'', u'', u'', u'', u'', u'', u'', u'', u'', u'', u'Amber', u'1'])

Request Method: PUT
Request URL: http://db3.biwebdbtest.nhm.ku.edu/api/workbench/rows/15/
Django Version: 1.5
Python Executable: /usr/bin/python
Python Version: 2.7.3
Python Path: ['/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/anhalt/specify7-master']
Server time: Tue, 2 Feb 2016 16:16:06 -0600
Installed Applications:
('django.contrib.sessions',
 'django.contrib.staticfiles',
 'specifyweb.specify',
 'specifyweb.stored_queries',
 'specifyweb.businessrules',
 'specifyweb.express_search',
 'specifyweb.context',
 'specifyweb.attachment_gw',
 'specifyweb.frontend',
 'specifyweb.barvis',
 'specifyweb.report_runner',
 'specifyweb.interactions',
 'specifyweb.workbench',
 'raven.contrib.django.raven_compat')
Installed Middleware:
('django.middleware.gzip.GZipMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'specifyweb.context.middleware.ContextMiddleware')

**Comment by benanhalt** [comment]
If you open a dataset in multiple tabs or computers, delete it on one of them and try to save/upload/validate/delete it from a tab where it is still showing, then there will be a "Dataset deleted by another session." message instead of errors.

**Comment by garrettgirard** [comment]
Verified in KU Birds database. Deleted recordset in one tab, saved in another, received message "Dataset deleted by another session", no error.
