### ISSUE TITLE
Allow importing multiple preps (or any one-to-many rels) as multiple rows

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2090]
As the number of preparations increases (maybe 120+ preps for one CO), importing through the WorkBench with 1000 columns is not the best solution.

There should be some way to associate all these preps using mutliple rows

|Catalog Number|Prep Type|Count|
|--|--|--|
|100|Sheet|30|
|100|Packet|35|
|100|Packet|12|

**Comment by maxxxxxdlp** [comment]
Do these mappings work?
![image](https://user-images.githubusercontent.com/40512816/188951964-357bd51d-53f4-4727-9019-932539c3d375.png)


Or, alternatively:
![image](https://user-images.githubusercontent.com/40512816/188951995-98ffb40c-f556-4dab-ac51-2b5b3d1fca11.png)
This way, a new preparation will be created for each row, even if all values are the same

> So the CO info must be identical in every row that contains a preparation
yes, or you could do "Ignore when blank" for all CO columns except for "Cat #" and then leave those columns blank in all but first occurrence of that CO

**Comment by grantfitzsimmons** [comment]
Workaround available, but maybe a better solution exists. Let's not take this entirely out of the discussion.

**Comment by danb213** [comment]
Hi @maxxxxxdlp, hi @grantfitzsimmons I tried your two suggestions and I'm still not able to get this to work - the validate section of of the workflow always tells me that I cannot have a duplicate cat #

The image below has my Excel file, my mapping, and the results of the validate - am I missing something here?

![image](https://user-images.githubusercontent.com/110948439/190949044-13da7d3d-9305-4732-af9b-be27eb0151f4.png)

**Comment by maxxxxxdlp** [comment]
@danb213 Looks like the 2nd screenshot in my comment (https://github.com/specify/specify7/issues/2090#issuecomment-1239735068) was wrong.

WorkBench assumes that each spreadsheet record represents a unique database record. This assumption applies to records from the base table only.

Since your base-table is Collection Object, WorkBench tries to create another Collection Object on row 2 of your spreadsheet, but discoveres that the catalog number is already taken.

The solution is to change the base table to anything other than Collection Object. I used Preparation in my 1st screenshot (https://github.com/specify/specify7/issues/2090#issuecomment-1239735068), though Determination or Collecting Event might work too

**Comment by danb213** [comment]
Hi @maxxxxxdlp,
I had another play and you are correct, I was able to create new collection objects and multiple preparations for each if I used the Preparation table as the base table. However if I try to add to tables other than the collection object and preparation (in this case the determination) I get the error about the catalog number needing to be unique:
![image](https://user-images.githubusercontent.com/110948439/192948715-6aeaad5e-fb7d-4963-8e70-cb925df2752b.png)
It was the same error whether I left the genus/species rows blank and ticked the "ignore when blank" option for the second rows. Is this a bug or a feature?

From what I can work out for our case we would need one upload to create the collection objects with their relevant collecting events/collecting trips/determinations etc. and then do a second upload that just had the preparations.

**Comment by benanhalt** [comment]
Yes. I think the best way to approach this would be to upload the Collection Objects first (with collection object as the base table) and then the preparations (with preparation as the base table) as two separate uploads. To upload the preparations you would only map the preparation fields and the catalog number.
