### ISSUE TITLE
Ability to set button colors

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2091]
Being able to set the color of buttons specifically would be very advantageous. 

This could be for all buttons, but even better, being able to give them color in the form definition.

**Comment by grantfitzsimmons** [comment]
This should include the different action buttons in dialogs

**Comment by grantfitzsimmons** [comment]
> **Save button colour**
> If not, would it be possible to add an option to change the colours of the Save button? The difference between ‘something is wrong, you can’t save this’ (dark red) and ‘you are good to go’ (dark orange) isn’t very obvious. A red/green option out of the box (or red/blue for colour-blind mode?) or the ability to define colours ourselves would be great.
>
**Requested By:** CSIRO

**Comment by maxxxxxdlp** [comment]
@CarolineDenis take a look at how accent color customization works right now.

See if we can extend that to allow customizing all of the buttons we use at the moment (Button.Blue, Link.Blue, Submit.Blue, Button.Green, ...)

At very least, customization of save button color would be useful

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-12-release-announcement/1202/1
