### ISSUE TITLE
Make Taxon GUIDs uploadable though the WB

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2097]
Currently the field is not available in the mapper

**Comment by beach53** [comment]
just curious, what was the use case for this?  Who?

**Comment by maxxxxxdlp** [comment]
`GUID` fiels are not currently populated for the `Taxon` records on save (https://github.com/specify/specify7/issues/2081).

Some users are using `GUID` fields for storing their own external taxa identifier. They needed a way to upload that though the WorkBench.

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons do you remember who this was for? If it was external, can you add credits to the `CHANGELOG.md` file?

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp This was internal for Mandi & me uploading taxon trees.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-7-3-release-announcement/774/1
