### ISSUE TITLE
"Invalid utf8 character string" when importing spreadsheet

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#210]
When trying to import a dataset, you sometimes get the error below. This has happened for me with the following spreadsheets which can be found in the Sp7 Testing Data/Spreadsheets directory: 8000recordsOhioState PaleoCopy of EditedOrt Mus Type Coll - Copy.csv, 5000recordsAMNHInvPDoneDR db copy.csv, and 8000recordsinSpanish INPA Arachnida - Araneae.csv

Warning at /api/workbench/import/
Invalid utf8 character string: 'F66D'

Request Method: POST
Request URL: http://db1.biwebdbtest.nhm.ku.edu/api/workbench/import/
Django Version: 1.5
Python Executable: /usr/bin/python
Python Version: 2.7.3
Python Path: ['/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/anhalt/specify7-master']
Server time: Fri, 5 Feb 2016 13:42:39 -0600
Installed Applications:
('django.contrib.sessions',
 'django.contrib.staticfiles',
 'specifyweb.specify',
 'specifyweb.stored_queries',
 'specifyweb.businessrules',
 'specifyweb.express_search',
 'specifyweb.context',
 'specifyweb.attachment_gw',
 'specifyweb.frontend',
 'specifyweb.barvis',
 'specifyweb.report_runner',
 'specifyweb.interactions',
 'specifyweb.workbench',
 'raven.contrib.django.raven_compat')
Installed Middleware:
('django.middleware.gzip.GZipMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'specifyweb.context.middleware.ContextMiddleware')****

**Comment by benanhalt** [comment]
As of 3363c48103d3dcfd7f4ca5b71c81bc9db8c5d34f it is possible to select the character encoding of the imported file. The files mentioned in the issue use *latin1*.

**Comment by garrettgirard** [comment]
Verified with datasets mentioned above.
