### ISSUE TITLE
Ability to have institution logo in navigation menu

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2100]
It would be nice to have an institution logo in the navigation menu. This has been requested several times over the past year by many institutions. Both Specify 7 and the institution logo should be maintained per Jim.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-12-release-announcement/1202/1
