### ISSUE TITLE
Taxon relationship is recursive

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2101]
On a CO query:
<img width="2556" alt="Screen Shot 2022-09-06 at 12 53 07 PM" src="https://user-images.githubusercontent.com/37256050/188705380-eea2fbba-bda5-4102-bda5-7cf6d9ef0022.png">

db: `fwri`

**Comment by maxxxxxdlp** [comment]
Can a preferred taxon have another preferred taxon? If so, this is valid
