### ISSUE TITLE
Cell that have subviews should not be vertically centered

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2108]
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/37256050/189165571-3a7cb5ca-9487-41fb-aa80-8addfa7aa85e.png">

db: `newmexico_august22`
CO form

**Comment by maxxxxxdlp** [comment]
Fixed in 5d569cad8 on `testability`

**Comment by maxxxxxdlp** [comment]
Related to #2129
