### ISSUE TITLE
Add the ability to update the Specify Network Cache

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2113]
In Specify 7, there is no way to push an update to the Specify Network cache.

**Comment by maxxxxxdlp** [comment]
Specify Network cache likely won't be used in Specify 7

Specify Network page is in a process of being embedded into Specify 7 (https://github.com/specify/specify7/pull/3065)

For collection-wide computations, Aimee is looking into getting data from GBIF
