### ISSUE TITLE
Add calculated Deaccession fields to Specify 7

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2114]
Deaccessions are the removal of a biological object (specimen, observation, or preparation type) from the collection. Deaccessions may include loans to other collections that are subsequently given to the borrower, lost specimens, and specimens that are destroyed.

https://docs.google.com/document/d/1FHmHHJqew_Q_iyqfqLzkNektaRYLyLxa4mOyeTVsZBA/edit?usp=sharing

---

The fields are `totalPreps` and `totalItems`.

Total Preps (Sum of all associated disposal, gift, and exchange out preparations)
Total Items (Sum of all associated collection object preparations)

---

## Deaccessions in Specify 7

As of April 15, 2024.

From @bronwyncombs:

- can be added to interactions menu with pencil icon
- Deaccessions can be added to disposals, gifts, and EOs; will display preps and number/date of interaction record on disposal form

![image](https://github.com/specify/specify7/assets/37256050/ad78070e-1eda-4bf2-ab0c-2bd9480e4418)

- total preps and total items fields not functioning on deaccession or EO form

![image](https://github.com/specify/specify7/assets/37256050/7d555355-ed18-428e-90b5-296b559f2e08)

- Deaccession agents can be added
- Deaccession agents are a hidden field in QB, and only <aggregated> is unhidden for that table

### Gifts
* count change reflected in actualCountAmt field of Prep form
* count affected in choose preps dialog

### Disposals
* count change reflected in actualCountAmt field on Prep form
* count affected in choose preps dialog

### Exchange Out
* EO preparations are read only and thus count information can’t be tested
* Attempted to remove `defaulttype=“table'` from view xml but behavior persisted

**Comment by maxxxxxdlp** [comment]
Per our discussion today, the deaccession form is already available in Specify 7.
Paired with https://github.com/specify/specify7/issues/2860 different deaccession types can be facilitated.
The big difficulty are the business rules, as deaccessions would make interaction counts even more complicated than they are already

**Comment by grantfitzsimmons** [comment]
University of Michigan is looking for this functionality as well

**Comment by acwhite211** [comment]
Here are some code sections I found in Specify 6 related to deaccession and the actual count:
- https://github.com/specify/specify6/blob/945d28f00288d2d64979848fb2fb63fda34bdd1b/src/edu/ku/brc/specify/datamodel/Preparation.java#L648-L687
- https://github.com/specify/specify6/blob/945d28f00288d2d64979848fb2fb63fda34bdd1b/src/edu/ku/brc/specify/datamodel/CollectionObject.java#L1228-L1235
- https://github.com/specify/specify6/blob/945d28f00288d2d64979848fb2fb63fda34bdd1b/src/edu/ku/brc/specify/datamodel/Accession.java#L787-L808
- https://github.com/specify/specify6/blob/945d28f00288d2d64979848fb2fb63fda34bdd1b/src/edu/ku/brc/specify/datamodel/Preparation.java#L1424C29-L1439

**Comment by grantfitzsimmons** [comment]
Closed in favor of https://github.com/specify/specify7/issues/2521
