### ISSUE TITLE
"In" Query operator doesn't work with integer fields

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2115]
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/37256050/189192338-6d11247a-7ae4-47f1-89f5-fddc6d5318b1.png">

It only allows the entry of one value. This is the same as equals.

**Comment by grantfitzsimmons** [comment]
Somehow I keep running into this issue.

I want to query on the following IDs:

`93760, 93769, 94026, 49072, 93975, 93976, 94017, 93991, 93770, 93963, 94019, 93962, 93992, 94034, 93980, 52247, 93965, 46494, 51928, 48644, 47233, 46994, 46058, 46831, 46297, 48695, 48300, 50646, 48964, 51966, 51480, 48341, 47689, 49913, 51735, 48619, 48239, 51941, 51861, 51852, 51800, 51559, 51230, 50852, 50825, 50757, 50688, 50654, 50536, 50478, 50466, 50450, 49635, 49325, 48896, 48548, 48490, 48271, 47480, 47038, 46751, 46254, 45980, 93961, 93998, 93969, 1, 93777, 93782, 93757, 93774, 93783, 93771, 93755, 93775, 93762, 93772, 93785, 93779, 93765, 93759, 93761, 93789, 93787, 93758, 93756, 93781, 93780, 93786, 93754, 93764, 93788, 93773, 93784, 93790, 93776, 93763, 93778, 93947, 93993, 93970, 94021, 94035, 93968, 94003, 93971, 94027, 93994, 93966, 94033, 93964, 93960, 94020, 94018, 93997, 94004, 94037, 94036, 93990, 93989, 93988, 93967, 52724, 52719, 52734, 52729, 50215, 49028, 47461, 51796, 52395, 47459, 50216, 52646, 51797, 47871, 50217, 47867, 52736, 49540, 52710, 52737, 52709, 52396, 47870, 52739, 52738, 50982, 50981, 52727, 49807, 49089, 48715, 48128, 50728, 47989, 47985, 93979, 50832, 93791, 93767, 93768, 93766`

**Comment by maxxxxxdlp** [comment]
Ok. Changed this to urgent priority. WIll fix it right after 2038

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-7-3-release-announcement/774/1

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-7-4-release-announcement/807/1
