### ISSUE TITLE
[testability] Step in-between user tool action

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2122]
https://user-images.githubusercontent.com/37256050/189445312-137ffd14-bf0b-4ad3-9d97-fb9bc526b0f0.mov

Sorry for the terrible title. The idea is that when you use a function from the User Tools menu, such as Create DwC Archive or Update RSS Feed, clicking the back button returns you to the current page and clicking back again sends you to the User Tools menu.

This can be recreated in Chrome on macOS.

https://freshfish-testability.test.specifysystems.org/specify/overlay/user-tools/

**Comment by chanulee1** [comment]
Selecting function from User Tools menu and clicking back button returns you to the User Tools menu, back again returns you to current page.
db: `freshfish`
OS: Windows 10
Browser: Chrome
