### ISSUE TITLE
[testability] Carry forward shows all hidden fields by default

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2124]
<img width="520" alt="image" src="https://user-images.githubusercontent.com/37256050/189445553-1b8d11c0-65f2-4c17-a96b-a25733267507.png">

By default, hidden fields are shown when opening the carry forward menu.

`freshfish`

Chrome on macOS

**Comment by chanulee1** [comment]
Cannot see hidden fields unless select "Reveal Hidden Form Fields".
db: `freshfish`, `willemcatno`
