### ISSUE TITLE
[testability] Show all unhidden fields from all visible relationships in the carry forward configuration tool

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2125]
<img width="528" alt="image" src="https://user-images.githubusercontent.com/37256050/189445728-f494d1e7-75c8-42c5-90c4-e329435fc694.png">

> When configuring carry forward, you should not need to configure each subview's carry forward fields individually. In Specify 6, you could choose fields for visible relationships.

**Requested By:** @tlammer

**Comment by chanulee1** [comment]
Relationships can be seen in carry forward config tool, and can be used to configure each subview's carry forward config.
