### ISSUE TITLE
[testability] Can not close "Add Resource" window in App Resources

### ISSUE THREAD

**Issue by melton-jason** [specify/specify7#2128]
**Bug Description**
After clicking on any `Add Resource` button in the App Resources window, the `Cancel` button does nothing. 

Note that this problem persists throughout all of the windows through the process of  making a new resource. 
_Except trying to create a Form Definition, which creates the Error Message window in Specify (This is probably a separate issue)_

After inspecting the page, an Error is raised and goes unhandled everytime the `Cancel` button is clicked. Not sure how useful the stack trace is, but I'll include it nonetheless.

**Notes**
As fun as clicking the `Cancel` button a million times is, it does get boring after a while 

**Screenshots**

https://user-images.githubusercontent.com/64045831/189448151-883b7974-99b6-4c14-837a-6fe7578e18ac.mp4

-Reproduction video

![issue_2128_uncaught_error](https://user-images.githubusercontent.com/64045831/189449526-68db5498-6b76-48b5-923e-f45f8ffbfdaa.png)

-The stack trace for the Uncaught Error

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Specify 7 Version: [testability]

Observed in `botany` and `invert-paleo` databases

**Comment by maxxxxxdlp** [comment]
What a great error message! Fixed the bug and improved the error message
