### ISSUE TITLE
Allow to customizable vertical cell alignment

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2129]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/37256050/189557853-bb237cea-3044-4dc5-ac7a-d01e2329fa6f.png">

**NMC** has requested that the collectors subview be aligned at the top of its view, not centered vertically.

**Comment by maxxxxxdlp** [comment]
Related to #2108

**Comment by grantfitzsimmons** [comment]
I think this really is just a duplicate of #2108. Nobody really needs to customize this, right?

**Comment by maxxxxxdlp** [comment]
I don't think this is a duplicate (Though we could fix them both in a single PR)
#2108 is about setting a smarter default rather than assuming that centering works in all cases
#2129 (this issue) is about being able to customize that default

**Comment by grantfitzsimmons** [comment]
Was this not fixed by https://github.com/specify/specify7/pull/3640?
