### ISSUE TITLE
Relationships can be made into pick lists

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2130]
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/37256050/189560833-45d91634-d8b4-4560-9437-ed544a1ed5ec.png">

Is this intended? Is this for display purposes or for PrepType situations?

`edge`, `KU_Fish`

**Comment by maxxxxxdlp** [comment]
Yes, this was intentional.

Let's say you want to restrict the Determinator field to 4 specific agents. This allows you to do that

**Comment by grantfitzsimmons** [comment]
Interesting. Have you tested that before?

**Comment by maxxxxxdlp** [comment]
No, but it should work™
