### ISSUE TITLE
Query results export to XLSX

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2131]
Specify 6 supports export to CSV and XLSX
Specify 7 only supports XLSX

I don't think anyone explicitly asked for this feature, but it is something that Specify 7 is missing

**Comment by grantfitzsimmons** [comment]
Closing until a user requests this ability. I like the non-proprietary approach whenever possible.

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons I belive my original issue description is wrong

> Specify 7 only supports XLSX

sp7 supports CSV, not XLSX, right?

if so, can you please edit the description?

**Comment by grantfitzsimmons** [comment]
You are correct. I have updated the description
