### ISSUE TITLE
Collection Date Day field just called Collection Date

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#214]
In Emory's database, in their Herbarium Query, their are Collection Date fields for Day, Month and Year. While Month and Year are called "Collection Date (Month)" and "Collection Date (Year)", Day is just called "Collection Date".

**Comment by benanhalt** [comment]
Just checked and this is present for all queries, not just Emory Herbarium Query.

**Comment by garrettgirard** [comment]
Verified in KU Birds. Made new query that included Col Date Day, and it displayed as "Collection Date (Day)", instead of just "Collection Date".
