### ISSUE TITLE
[testability] Unsaved changes are lost when opening a new page/no warning is given

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2143]
**Steps to recreate:**
1. Add information to a CO record
2. Click **Queries**

https://user-images.githubusercontent.com/37256050/189956038-72ba6b03-4f2c-417d-b83e-5b829c0cec32.mov

3. Create a new query from any table
4. See data was lost

db: `ohiomollusks`
browser: Chrome
branch: `testability`

**Comment by maxxxxxdlp** [comment]
The video recording does not show the bug. Can you upload the video again?

**Comment by chanulee1** [comment]
Warning is given when opening new page after making changes to current form or query.
db: `willemcatno`, `KUVascPlant`
