### ISSUE TITLE
List of tables pick list not working on form load

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2146]
List of tables pick list not working on form load

It shows `(current, invalid value)` and is disabled

<img width="1800" alt="Screen Shot 2022-09-13 at 13 07 58" src="https://user-images.githubusercontent.com/40512816/189977783-ef654216-26e0-43be-89be-4df2ef2147b0.png">

Changing the picklist type and reverting it back fixes the issue

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-7-3-release-announcement/774/1
