### ISSUE TITLE
Barcodes with Numbers generate incorrectly

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#215]
In Emory, if you try to generate their Barcode label, the barcodes will generate fine except they won't have any numbers under them. I think this could be a formatting issue with the pdf that Sp7 makes.

**Comment by benanhalt** [comment]
The problem is with the report runner service. See: https://github.com/specify/report-runner-service/commit/9ebb84eb2a153c15c078ab33ede4b1d8d8467942#diff-04c6e90faac2675aa89e2176d2eec7d8R57

It has been fixed there.

**Comment by garrettgirard** [comment]
Verified in Emory. Generating the same Barcode label, the numbers are now present under the barcode.
