### ISSUE TITLE
[testability] Delimiter parsing is not working in all cases

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2150]
The CSV includes 7000 rows (correctly). Testability used the “Tab” option to separate the data (tested twice) and broke the upload document. You’ll want to see the workbench data set- the delimiter process just stopped at some point at row 653. Excel handles this parsing correctly.

![image](https://user-images.githubusercontent.com/37256050/190198491-1fd33477-d3ab-4d37-934c-470df391aa59.png)

**File:** [tree_6.csv](https://github.com/specify/specify7/files/9567759/tree_6.csv)
**DB:** `ohiomollusks`
**User:** spadmin
**WB Data Set:** https://ohiomollusks-testability-2.test.specifysystems.org/specify/workbench/20/

**Comment by maxxxxxdlp** [comment]
There is a value `"Pease" Tryon, 1887"` on row 653.

`"` is used as an escape character in CSV files (but only if it is the first value in that cell, which it is in this case)

Importing the file as an `.xlsx` would fix the issue.

We use a `papaparse` library for parsing CSV. The bug appears to be present even in the most recent version. There also are a lot of outstanding issues in that library. I will try migrating to `csv-parse`, which is more popular and has fewer outstanding issues.

**Comment by grantfitzsimmons** [comment]
Trying to import the CSV attached in the initial post causes an error.

<img width="889" alt="image" src="https://user-images.githubusercontent.com/37256050/192678374-eeccb593-0db1-4183-81c6-990da4e357db.png">

[Specify 7 Crash Report - 2022-09-28T03_06_57.051Z.txt](https://github.com/specify/specify7/files/9661102/Specify.7.Crash.Report.-.2022-09-28T03_06_57.051Z.txt)

https://freshfish-testability.test.specifysystems.org/specify/workbench/import/

**Comment by maxxxxxdlp** [comment]
I belive this is fixed now. Can someone test it again?

**Comment by chanulee1** [comment]
Appears to be parsing correctly.
db: `freshfish`
user: `spfishadmin`
