### ISSUE TITLE
Repository Agreement subview is behaving incorrectly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2152]
When creating a new accession record in Specify 6, the Repository Agreement subview under the Accession table is working correctly.

<img width="1210" alt="Screen Shot 2022-09-15 at 9 21 45 AM" src="https://user-images.githubusercontent.com/37256050/190428702-6d21380b-c35f-4765-83bc-0d9b876953c4.png">

When creating a record in Specify 7, there is no way to add a Repository Agreement to an Accession record. The **+** icon is disabled.

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/37256050/190428761-a212d442-3edc-4b8e-ae20-ff03ac43edf2.png">

This is in the same database with the same forms.

The behavior begins to complicate after saving the Accession record:

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/37256050/190429550-8246a687-37ed-4c60-b8d4-14cbddbe9970.png">

**Now a Repository Agreement is randomly assigned. I created a single repository agreement in this database and it immediately selected it. There is no way to remove this relationship or modify it.**

When viewing the same record in Specify 6, it shows there is no Repository Agreement assigned.

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/37256050/190430520-e90f6c46-b358-47fa-9b28-da174339a0be.png">

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/37256050/190431206-dd4a42e5-fb67-43ea-9d44-0ef5ad4b5db6.png">

**Database:** `pripaleo`
**User:** `kmiller`
 
https://pripaleo-edge.test.specifysystems.org/specify/view/collectionobject/70641/

[paleo.views.xml](https://drive.google.com/file/d/1CoIqz4DyTtaoOuJFYpW_R4qYM5y_LIwx/view?usp=sharing)

**Reported By:** Matthew Cruz at The University of Michigan

**Comment by maxxxxxdlp** [comment]
Same cause as https://github.com/specify/specify7/issues/725#issuecomment-1244821213

It affects all subviews to non-dependent relationships. We need to figure out why that limitation was put in place. Once we do, removing it is easy.

I will close this as a duplicate.
