### ISSUE TITLE
deaccessionPreparations is a phantom field

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2153]
Preparation -> deaccessionPreparations is a relationship that is present in the Schema Config tools in both Specify 6 and 7. 

When viewing Preparation in the schema viewer in 7, you'll notice that that field does not exist. At the database and data model level, it is not present.

---

**Additional Details:**

Under the Preparation form for the default vertpaleo.views.xml, the following row exists (Lines 658-660):

```
<row>
   <cell type="subview" viewname="DeaccessionPreparation2" id="deaccprep" name="deaccessionPreparations" colspan="12"/>
</row>
```

This indicates that there is a subview referencing deaccessionPreparations. This is non-functional in Specify 7, as Deaccessions are not in 7 (https://github.com/specify/specify7/issues/2114). 

_What is this field and how is it implmented in 6?_

**Comment by emenslin** [comment]
Can recreate in edge (7.9.6)
