### ISSUE TITLE
[testability] Cannot create new view resource 

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2156]
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/37256050/190493063-e6b10406-bc28-4360-9d75-26e39c6aa39e.png">

db: `ohiomollusks`
os: macOS
browser: Chrome

**Comment by chanulee1** [comment]
Able to create new view resources.
db: `freshfish`, `UOregonPaleo`
os: Windows 10
browser: Chrome
