### ISSUE TITLE
Error when navigating to another collection from a record set

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2159]
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/37256050/190689247-5fbeece1-c349-480f-bfa4-de543dffbc2d.png">

Try from the Voucher Collection

https://freshfish-issue-1981.test.specifysystems.org/specify/recordset/96/

ver: `issue-1981`
browser: Chrome, macOS

**Comment by grantfitzsimmons** [comment]
Can't recreate.

**Comment by maxxxxxdlp** [comment]
What likely happened is that the test server restarted after you opened this page, thus all requests to the back-end were failing
