### ISSUE TITLE
Queries including taxon author fields return no results.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#216]
From Theresa's email:
> Emory is having the issue that when they do a query (Label Query1) in their Specify 6 version with the Genus = Iris, they get back 22 records.  I get the same in the copy she sent us.  When she does the same query in Specify 7, she gets back no results.

Removing all Taxon [LEVEL] Author fields from the query allows it to work.

**Comment by benanhalt** [comment]
Hotfixed on release branch. Existing queries now return correct result, but it is not yet possible to add fields including Taxon Author to queries using the query builder in Sp7.

**Comment by garrettgirard** [comment]
Verified, Taxon Author fields are no longer available in the query builder for the time being, and therefore can no longer cause the no results issue.
