### ISSUE TITLE
Support count attribute in aggregators

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2161]
<img width="1641" alt="image" src="https://user-images.githubusercontent.com/37256050/190705864-c56a802b-9d7d-46c0-8c88-73b3a3eb6622.png">

Specify 7 currently ignores the count="" attribute for aggregators in the DataObjFormatters document.

This prevents the ability to specify a count of 1 in situations like Determinations for instance. In Specify 6, you can show only the current determination where in 7 you see all determinations.

**Comment by maxxxxxdlp** [comment]
https://github.com/specify/specify7/issues/1144#issuecomment-1015887568

**Comment by maxxxxxdlp** [comment]
Closing this as a duplicate of #1144
