### ISSUE TITLE
Referencing a field in a -to-many table in table aggregation in a ColObjRel formatter causes view to disappear

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2163]
![image](https://user-images.githubusercontent.com/37256050/190725847-f3d76fe5-0a03-4c9b-a384-8f52ad05efab.png)

I imagine this kind of issue is rooted in the fact that there is a to-many relationship from Collection Object to Determination. I tried to make a switch statement display the `catalogNumber: determinations.taxon.fullName` only when `isCurrent` = `true`.

Check it out:

**DataObjFormatters:**
```
    <format
        name="CoRF"
        title="CoRF"
        class="edu.ku.brc.specify.datamodel.CollectionObject"
        default="true"
        >
        <switch single="false" field="isCurrent">
        	<!-- Current is true -->
            <fields value="true">
                <field uifieldformatter="CatalogNumber">catalogNumber</field>
                <field sep=": ">determinations.taxon.fullName</field>
            </fields>
            <!-- Current is false -->
            <fields value="false">
            	<field sep=""></field>
            </fields>
        </switch>
    </format>
```

**Views:**
```
                <row>
                    <cell type="label" label="Tissues:" initialize="align=left;"/>
                    <cell type="field" id="colrel" uitype="plugin" name="this" initialize="name=CollectionRelOneToManyPlugin;relname=Has Tissue;" formatting="CoRF" colspan="9"/>
                </row>
```

https://kufish-issue-1981.test.specifysystems.org/specify/

[CoRDataObjFormatters.zip](https://github.com/specify/specify7/files/9587023/CoRFormatIssue.zip)
[views.xml.zip](https://github.com/specify/specify7/files/9587027/views.xml.zip)

db: `KU_Fish`
user: abentley
browser: Chrome
OS: macOS

---
**Requested By:** Grant & Andy

**Comment by maxxxxxdlp** [comment]
Should be fixed on the `xml-editor` branch. Can someone try it?

**Comment by chanulee1** [comment]
Getting this error when attempting to insert the formatter into the xml file. Is there another way to include this formatter?

![image](https://user-images.githubusercontent.com/103299204/226445294-a423aa59-8792-4c8f-bd9d-39d2a7dafd6c.png)

**Comment by maxxxxxdlp** [comment]
The fact that it was showing the error under `<formatters>` rather than `<switch>` line was a bug - fixed. 

<img width="488" alt="Screenshot 2023-03-21 at 21 40 00" src="https://user-images.githubusercontent.com/40512816/226787888-d52c2ba0-2bbe-4010-8411-fd537c8090dd.png">

@grantfitzsimmons the field disappeared because `isCurrent` field does not exist in `CollectionObject`. Perharps what you want is an aggregator that aggregates all Determinations, and when aggregating, uses a formatter that outputs taxon.fullName if isCurrent, and else empty string

**Comment by grantfitzsimmons** [comment]
> @grantfitzsimmons the field disappeared because `isCurrent` field does not exist in `CollectionObject`. Perharps what you want is an aggregator that aggregates all Determinations, and when aggregating, uses a formatter that outputs taxon.fullName if isCurrent, and else empty string

It's funny how obvious this is in hindsight. I didn't catch this last September– d'oh

**Comment by maxxxxxdlp** [comment]
No worries. That's what the visual editor and XML validation is for!

If not for XML validation, it would have taken me some time to see what's going on here

Super excited for the form editor

**Comment by chanulee1** [comment]
Error highlighting appears to be fixed on `xml-editor`. Can this issue be closed?
