### ISSUE TITLE
Popup box doesn't disappear after adding unassociated item in New Loan form

### ISSUE THREAD

**Issue by mc0822** [specify/specify7#2164]
**Describe the bug**
In New Loan form, you can add an unassociated item, but the popup box doesn't disappear after adding it.

**Expected behavior**
Popup box should disappear after adding item.

**Screenshots**
(https://anfc-v772.test.specifysystems.org/specify/view/loan/new/)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Specify 7.7.2

**Database Name:** If applicable
Specimens

**Reported By**
Theresa at Specify

**Comment by CarolineDenis** [comment]
@tlammer is this still happening to you?

**Comment by maxxxxxdlp** [comment]
@CarolineDenis still happens

https://sp7demofish.specifycloud.org/specify/view/loan/new/

https://user-images.githubusercontent.com/40512816/233138650-d2938be2-bddd-4197-93e2-7cf0e708c7c6.mov

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-11-release-announcement/1174/1
