### ISSUE TITLE
Cannot add funding agent to New Collecting Trip form

### ISSUE THREAD

**Issue by mc0822** [specify/specify7#2167]
*Describe the bug*
In New Collecting Trip form, you cannot add a funding agent record.

*Expected behavior*
You should be able to add a funding agent record.

https://anfc-v772.test.specifysystems.org/specify/view/collectingevent/new/

*Desktop:*
OS: Windows 10
Browser: Chrome
Specify 7.7.2

*Reported By*
CSIRO

**Comment by mc0822** [comment]
We can add a funding agent to the form, but can't associate a funding agent record.  Hope that helps, if not let me know. Thank you.

**Comment by maxxxxxdlp** [comment]
So you want to link the existing funding agent to the collection object record?

Can you add a query combo box to the form?

**Comment by mc0822** [comment]
1. Opened New Collecting Trip form.
2. Added funding agent.
3. When clicked "save," got error message.

[Specify 7 Crash Report - 2022-09-19T18_11_19.904Z (1).txt](https://github.com/specify/specify7/files/9601307/Specify.7.Crash.Report.-.2022-09-19T18_11_19.904Z.1.txt)

**Comment by maxxxxxdlp** [comment]
Looks like we already have a ticket for this issue: #715

I will close this one in favor of that one.
