### ISSUE TITLE
Updates to taxon.fullname not working

### ISSUE THREAD

**Issue by ianengelbrecht** [specify/specify7#2168]
**Describe the bug**
Moving a species to a new genus does not update fullname.

**To Reproduce**
In the taxon tree, move a species to a different genus. Genus name in the fullname still reflects the original genus. 

**Expected behavior**
The fullname should update to reflect the new genus. 

**Screenshots**
![image](https://user-images.githubusercontent.com/9418787/190980389-20044c47-f34c-48bc-ae29-0c514f7b97a0.png)

Here the new genus name is Chameleon, with an 'n', previously Chameleo, no 'n'.
**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Specify 7 Version: 7.7.2

**Database Name:** If applicable

**Reported By**
Natural Science Collections Facility South Africa, on behalf of Ditsong National Museum of Natural History

**Additional context**
Possibly related to #388

**Comment by benanhalt** [comment]
I'm not seeing this using a copy of KU Fish on my dev system. Can someone try and replicate it on the test server with some other dbs?

**Comment by ianengelbrecht** [comment]
Is there an error log somewhere that I could look at to try and trace the problem?

**Comment by grantfitzsimmons** [comment]
## **Kansas:**

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/37256050/191829651-5a759154-cfe7-41d1-87fe-924f9e885dde.png">

<img width="1794" alt="image" src="https://user-images.githubusercontent.com/37256050/191829746-6b8a39a2-deae-4051-9a9b-1bfd93dd1254.png">

## **Florida:**

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/37256050/191830336-e9638799-1c5e-4d99-8208-14d2e505073d.png">

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/37256050/191830450-0c20005d-125f-4548-b80d-c46499476b89.png">

## GREE:

<img width="1798" alt="image" src="https://user-images.githubusercontent.com/37256050/191830982-82374a86-463d-4948-abb3-8858e52008bc.png">

<img width="1799" alt="image" src="https://user-images.githubusercontent.com/37256050/191831076-b5419b40-fb58-4a01-a069-6fceae8af03b.png">

## **Edinburgh:**

Could not recreate either.

--

I had the same experience as you @benanhalt 

Looks like this was an anomaly? Does this happen consistently @ianengelbrecht ?

**Comment by grantfitzsimmons** [comment]
I believe the issue here is that taxon nodes that are not preferred or are now a synonym will not have their full names updated. @ianengelbrecht Let me know if you have this issue again with more details!
