### ISSUE TITLE
[testability] App resource sidebar shows duplicate resource (on save?)

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2174]

**Comment by chanulee1** [comment]
Still duplicates.

https://user-images.githubusercontent.com/103299204/193332332-a1dd1203-2868-466f-b538-a71882198c8c.mp4

**Comment by chanulee1** [comment]
Sorry didn't move this to "To Do"

**Comment by chanulee1** [comment]
Seems to work!
db: `freshfish`, `herbrbge`
