### ISSUE TITLE
[testability] Creating a record set does not update the URL

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2175]

**Comment by maxxxxxdlp** [comment]
Fixed

To test:
1. Create a new Collection Object record set
2. Should open the Collection Object form with a URL like `/specify/view/collectionobject/new/?recordsetid=<recordSetId>`
3. Create the Collection Object.
4. Should update the URL to be like `/specify/view/collectionobject/<collectionObjectId>/?recordsetid=<recordSetId>`

**Comment by chanulee1** [comment]
@maxxxxxdlp This is for adding a new collection object to an existing record set right?

**Comment by maxxxxxdlp** [comment]
Correct

**Comment by chanulee1** [comment]
URL updates correctly when add a new collection object to a record set.
db: `freshfish`
