### ISSUE TITLE
[testability] User Preference links not working correctly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2180]
**To Reproduce**
1. Go to User Prefs
2. Click on **Reports**
3. See **WorkBench is highlighted**

Same issue with GeoMap and App Resources.

Chrome, macOS

**Comment by maxxxxxdlp** [comment]
Clicking on a category scrolls that category to the top.
The active category is determined based on which category is in the middle.
Thus, clicking on a category might not make it active.
Added a hack that temporary makes the clicked category active, until the user starts to scroll away
