### ISSUE TITLE
[testability] Adding 2 accession agents causes an error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2182]
**To Reproduce**

https://freshfish-testability.test.specifysystems.org/specify/view/accession/new/

1. Go to the Accession form
2. Add an Accession Agent
3. Add another Accession Agent

`TypeError: Cannot read properties of null (reading 'id')`

**Expected behavior**
It should work properly. On `edge` there is no error.

https://user-images.githubusercontent.com/37256050/191052913-b1f2236d-7485-4bdb-86d6-7bd0de3d7fda.mov

**Comment by maxxxxxdlp** [comment]
Unable to replicate it.

Tried on https://kufish-testability.test.specifysystems.org/specify/view/accession/new/

Maybe it was fixed since then.

Can you try this again?

**Comment by grantfitzsimmons** [comment]
Seems to be fixed since then. Can't recreate on either `freshfish` or `KU_Fish`
