### ISSUE TITLE
Invalid query search parameters should not prevent running query

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2185]
Query builder's search filters may be considered invalid because of a bug, a limitation of the validation system or because user is looking for invalid data. (see #1283 for an example)

Searching with invalid fields does not corrupt data (unlike saving records with invalid data), thus the validation system should not prevent running a query that has invalid filters

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-7-4-release-announcement/807/1
