### ISSUE TITLE
Better way to visualize all agents (tree-like interface)

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2198]
> For future versions of Specify, it seems like the addition of an Agent tree design/interface would be a good way to visualize agents and combine variants.

**Requested By:** Zachary Rogers at the New Mexico State Herbarium

**Comment by maxxxxxdlp** [comment]
Do they need something like an orgchart?

**Comment by grantfitzsimmons** [comment]
Not sure. I think just a better way to visualize agents. Maybe this is part of the agent-merging tool that we need to address

**Comment by grantfitzsimmons** [comment]
Closing until more information or requests come in
