### ISSUE TITLE
Add 10 additional text fields to the Collection Object Attributes table

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2205]
>Would it be possible to ask for 10 additional text fields for the collectionobjectattributes table? We have an open issue at the moment with labels for our traits being stored in the collectionobjectproperties table - we can't get iReport to print those traits individually - but moving those to the other table would sort that out. We can change our migration mapping but we need more free fields (apparently there are a lot of different ways to measure a bird!)

**Requested By:** Dan at CSIRO

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-6-8-02-and-schema-2-10-release-notes/830/1

**Comment by grantfitzsimmons** [comment]
These new fields were added in [Schema 2.10](https://discourse.specifysoftware.org/t/specify-6-8-02-and-schema-2-10-updates-release-notes/830)
