### ISSUE TITLE
Send Email button should not be on the form as Specify 7 does not support that action

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2211]
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/37256050/191997986-f0f42bc8-9b10-4172-81a8-d2c723a27692.png">

On the Information Request form, there is an option to "Send Email on Save" that doesn't function in Specify 7. This should be hidden as it has no function.

**Comment by CarolineDenis** [comment]
@grantfitzsimmons is this fixed?

**Comment by grantfitzsimmons** [comment]
No 🥲

**Comment by CarolineDenis** [comment]
@grantfitzsimmons I tried on the xml-editor branch. When you have time could you confirm me that it happens there too?

**Comment by maxxxxxdlp** [comment]
I think they are ignorred by the form editor validation, but not by rendering
Unfortunately, viewSpec.ts (the syncer library) is only used at the moment in the form editor, but not during form rendering, so this bug would still be present

**Comment by grantfitzsimmons** [comment]
Somehow this has been resolved? It's not showing up for me in `v7.8.13`.
