### ISSUE TITLE
Color picker not working in Safari

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2215]
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/37256050/192071034-2dae5b45-d14a-494a-b4e3-ba359347ddbd.png">

Color picker in user preferences is not working in Safari on macOS Monterey

**Comment by CarolineDenis** [comment]
Cannot reproduce the bug on macOs Ventura. 
@grantfitzsimmons could you give me more details about this issue?

**Comment by grantfitzsimmons** [comment]
https://user-images.githubusercontent.com/37256050/220774891-5a030a99-41ec-49cb-ae47-08a6c2874dc7.mov

Funny enough, it works now, just shows the color picker in the bottom left of my screen. 

<img width="407" alt="image" src="https://user-images.githubusercontent.com/37256050/220775018-fac1008f-565e-437c-917e-57350ad3b225.png">

See how it should be implemented by clicking on the color under "Or Use HTML5"

https://www.w3schools.com/colors/colors_picker.asp

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-8-release-announcement/1108/1
