### ISSUE TITLE
QCBX displays "Add" even when no permission to add

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2216]
Query Combo Box disables the "Add" button when adding is not allowed,
However, putting a nonexistent value into the autocomplete box, makes autocomplete show the "Add" line.

That line should not be visible if user has no permission to create new records, or Query Combo Box is to a table that should not have new records created (TaxonTreeDefItem, Division, Institution, Collection)

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-7-3-release-announcement/774/1

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-7-4-release-announcement/807/1
