### ISSUE TITLE
[testability] Buttons in query results should be the same height

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2220]
https://user-images.githubusercontent.com/37256050/192418962-fc8524c9-cf5d-4e57-a59f-878b66affd49.mov

**Steps to Recreate:**
1. Resize the window to be more narrow (half the display in this instance)
2. Run the query
3. Select a record from the list
4. See button size issue

https://freshfish-testability.test.specifysystems.org/specify/query/123/

user: `abentley`
db: `freshfish`

**Comment by chanulee1** [comment]
Button size issue occurs even without selecting a record.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/103299204/192853415-b5593d2d-3902-4ed4-ba46-783fe93ea622.png">

db: `freshfish`
user:`abentley`

**Comment by chanulee1** [comment]
Buttons all same height.
db: `freshfish`
user: `abentley`
