### ISSUE TITLE
[testability] GeoMap radius configuration in the query builder does not work properly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2221]
**Describe the bug**
The longitude and latitude geomap radius feature does not work

https://user-images.githubusercontent.com/37256050/192420031-6d27f3b2-085e-402e-a22f-dac2ab599bf8.mp4

**To Reproduce**
1. Go to this query: [https://freshfish-testability.test.specifysystems.org/specify/query/124/](https://freshfish-testability.test.specifysystems.org/specify/query/124/)
2. Click on the 📍 icon and verify the selected region
3. See that results are outside of that radius

https://freshfish-testability.test.specifysystems.org/specify/query/124/

user: `abentley`
db: `freshfish`

**Comment by maxxxxxdlp** [comment]
Fixed

**Comment by chanulee1** [comment]
Works.
Tested:
db:`freshfish`, user:`abentley`
db:`KU_Fish`, user:`spfishadmin`
