### ISSUE TITLE
[testability] Query builder in CoR dialog does not preserve fields when query is run

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2224]
https://user-images.githubusercontent.com/37256050/192421995-cc427840-737c-47b2-8d0e-3cf75b83c5a5.mov

1. Add an entry to the CoR view
2. Click **Query Builder**
3. Add fields to the query
4. See no results returned because no fields are visible

https://freshfish-testability.test.specifysystems.org/specify/view/collectionobject/29492/?recordsetid=72

user: `abentley`
db: `freshfish`

**Comment by maxxxxxdlp** [comment]
Unable to replicate on testability in Chrome and Safari. Could you test this issue again?

It could be that this issue was just a side-effect of #2040
