### ISSUE TITLE
Dates in CE are not saving as precise

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2228]
Data entered in Specify 6 has a `StartDatePrecision` of 1 while data entetered in Specify 7.7 and `testability` have a `StartDatePrecision` of `NULL`.

Specify 6 is not returning the parsed collection date when running a query or running a label:

![image](https://user-images.githubusercontent.com/37256050/192623521-156dfc74-eadc-4ffb-98d2-68d77b135d0e.png)

<img width="647" alt="image" src="https://user-images.githubusercontent.com/37256050/192623882-2cd0ff78-37ab-4992-bcb8-f328e4eec8d3.png">

<img width="633" alt="image" src="https://user-images.githubusercontent.com/37256050/192623837-616d7c62-613f-49c7-96c3-dfd498f0896f.png">

---

<img width="713" alt="image" src="https://user-images.githubusercontent.com/37256050/192624199-ea4e2cb7-d350-4445-98e0-a40d0e304788.png">

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/37256050/192624237-7f22741d-d1b6-4882-bf7f-909d552bb985.png">

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/37256050/192624278-88ba2a76-f45b-4147-90d4-3d69a9960553.png">

---

```
select CollectingEventID, StartDate, StartDatePrecision, StartDateVerbatim, TimestampCreated, TimestampModified from collectingevent WHERE CollectingEventID IN (23119, 22101,23213,23214);
```

Here are the items in the database:

|CollectingEventID|StartDate|StartDatePrecision|StartDateVerbatim|TimestampCreated|TimestampModified|
|-----------------|---------|------------------|-----------------|----------------|-----------------|
|22101|2020-07-22|1||2021-03-01 12:21:16.000|2022-08-03 16:04:23.000|
|23119|2022-05-12|||2022-08-01 16:11:50.000|2022-08-03 16:08:13.000|
|23213|2000-11-19|||2022-09-27 19:43:44.000|2022-09-27 19:43:44.000|
|23214|2000-11-19|1||2022-09-27 14:46:14.000|2022-09-27 14:46:14.000|

Specify 7 does not have a problem interpreting this, and does not have the issue 6 does. The issue here is that she needs to run the labels through Specify 6 due to unsupported scriptlet in the label:

[Query that shows these fields in 7:](https://emoryherbarium-testability.test.specifysystems.org/specify/query/51/)

<img width="2504" alt="image" src="https://user-images.githubusercontent.com/37256050/192623003-1d449099-2f02-43de-8c8a-466b98f650b0.png">

**Database:** `emoryherbarium`
**User:** `spadmin`

https://emoryherbarium-testability.test.specifysystems.org/specify/

**Comment by grantfitzsimmons** [comment]
**Reported By:** Tharanga at Emory University Herbarium

**Comment by grantfitzsimmons** [comment]
CE ID 23213 was entered in Specify 7
CE ID 23214 was entered in Specify 6

**Comment by maxxxxxdlp** [comment]
I think the actual bug here is that Specify 7 is not setting the precision field. It seems like it sets the value only when you change precision.

Fixed so that it always sets the precision.

@grantfitzsimmons please test the new behavior
