### ISSUE TITLE
Implement ColRelTypePlugin

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#223]
As seen in the KU Fish Tissue collection object form.

**Comment by timo11** [comment]
UI still needs work.

**Comment by yvonneekanim** [comment]
The plugin works correctly. We noticed that when trying to view the voucher or tissue in the relationship, Specify switches collections in the same tab making it impossible to view the information side-by-side. Having the CO information show up in a new tab should solve the problem.

**Comment by yvonneekanim** [comment]
UPDATE: A user can't log into two collections in the same database at the same time. See issue #426
