### ISSUE TITLE
Pick list is being displayed as an API link

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2230]
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/37256050/192625374-17f27b7c-2cac-41ef-813c-5c227d5a8a6f.png">

<img width="2551" alt="image" src="https://user-images.githubusercontent.com/37256050/192625514-da570154-77bc-4a98-b928-0a433fe0ee9e.png">

https://emoryherbarium-testability.test.specifysystems.org/specify/view/collectionobject/23110/?recordsetid=878

When saving a preparation with a valid value in the picklist, the following error occurs:

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/37256050/192625778-f26e6b81-a742-427b-9594-01ccfbf1a04b.png">

[Specify 7 Crash Report - 2022-09-22T21 46 11.929Z.txt](https://github.com/specify/specify7/files/9659301/Specify.7.Crash.Report.-.2022-09-22T21.46.11.929Z.txt)

User: `spadmin`
Database: `emoryherbarium`

**Comment by grantfitzsimmons** [comment]
**Reported By:** Tharanga at Emory University Herbarium

**Comment by maxxxxxdlp** [comment]
The `Response: Invalid statusText` error is a separate bug. Fixed. (was happening on any invalid server response / server error)

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons Can you check if this pick list worked in their database in 7.6.0?

The pick list is defined incorrectly. I am not sure if they need to fix it, or if 7.7.0 should support that incorrect format

Pick list is defined like this:
![Screen Shot 2022-09-29 at 12 09 32](https://user-images.githubusercontent.com/40512816/193095387-bd6bab52-a1ba-4ada-b9c0-78a2ec9fa791.png)

The `value` of `5` is the preptype ID. Specify 7 currently expects that value to be formatted as `/api/specify/picklist/5/`.

FYI, here is another way to define this picklist:
![Screen Shot 2022-09-29 at 12 11 00](https://user-images.githubusercontent.com/40512816/193096126-0f67662c-52ad-4cf4-bb1e-38f82bad17af.png)

**Comment by grantfitzsimmons** [comment]
<img width="450" alt="image" src="https://user-images.githubusercontent.com/37256050/193115094-f403d466-8547-4a71-a2ec-b20cadda2dbc.png">

<img width="410" alt="image" src="https://user-images.githubusercontent.com/37256050/193115257-5accbc28-db6e-4b0b-8d2a-4b4a21ac5606.png">

7.6.1 works correctly.

**Comment by grantfitzsimmons** [comment]
SAIAB is reporting the same issue. It appears to have been introduced in `v7.7.3`. This is definitely an urgent issue

**Comment by maxxxxxdlp** [comment]
This was probably introduced before `7.7.3` because it was replicated on `testability`, which does not yet have changes from `7.7.3`

Even though this was discovered on `testability`, please test this on `issue-2230` (will be merged into production)

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-7-4-release-announcement/807/1
