### ISSUE TITLE
[testability] Opening record sets after doing a simple search causes an error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2236]
https://user-images.githubusercontent.com/37256050/192673007-3449d04b-72fd-49fe-aa8e-faa42e1cb676.mov

<img width="898" alt="image" src="https://user-images.githubusercontent.com/37256050/192673053-adcaa1c8-b8f0-4180-9448-bb047417ef97.png">

```
Response:

{
  "q": [
    "This field is required."
  ]
}
```

https://freshfish-testability.test.specifysystems.org/specify/

**Comment by chanulee1** [comment]
Able to open record set after doing a simple search.
db: `freshfish`
user: `abentley`
