### ISSUE TITLE
[testability] Add hint to report bugs in Specify to the forum

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2237]
To make reporting issues easier, we could update the message:

```
This error is likely caused by a bug in Specify. Please report it.
```

to include a link to the community forum for members to report issues or at least include a link to the email.

I could put together instructions for sending us a bug report. Might be worth opening another feature request for automating bug reporting to us.

---

> Here is the file that defines the error message for each Http response code - https://github.com/specify/specify7/blob/4b93058a678ea80d9c31ba8baac2f30be33cb574/specifyweb/frontend/js_src/lib/utils/ajax/definitions.ts
> 
> Feel free to edit that file to provide more details or improve the error messages

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons Can you send me a modified version of this message that includes a reference to discourse (i.e, Member institutions can search for solved issues on our forum - {discourseLink})

```
If this issue persists, please contact your IT support or if this is a Specify Cloud database, contact support@specifysoftware.org
```

**Comment by grantfitzsimmons** [comment]
If this issue persists, please contact your IT support. If this is a Specify Cloud database, please contact [support@specifysoftware.org](mailto:support@specifysoftware.org).

Users from [member institutions](https://www.specifysoftware.org/members/#:~:text=Members%20can%20contact%20support%40specifysoftware.org%20for%20assistance%20updating.) can search for answered questions and ask for help on our [Community Forum](https://discourse.specifysoftware.org/).
