### ISSUE TITLE
[testability] Saving a schema change gives a 404

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2239]
https://user-images.githubusercontent.com/37256050/192676196-5c4b14bf-0ed0-4414-92cd-954d8d798035.mov

https://freshfish-testability.test.specifysystems.org/specify/task/schema-config/?rawlanguage=en

browser: Chrome on macOS
database: `freshfish`
user: `abentley`

**Comment by chanulee1** [comment]
Saving schema changes works normally.
db: `freshfish`
user: `abentley`
