### ISSUE TITLE
[testability] Fields and Relationships are not bold in schema config

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2240]
<img width="541" alt="image" src="https://user-images.githubusercontent.com/37256050/192676650-91a1c405-eec7-4e03-b867-640689d8aee1.png">

These two are bold on `edge`, Chrome on macOS

**Comment by maxxxxxdlp** [comment]
This might be browser specific, rather than something specify did. Can you test it in both Chrme and Firefox?

Specify can not control the styling of those

**Comment by grantfitzsimmons** [comment]
This is appearing correctly on Chrome in `edge`

**Comment by maxxxxxdlp** [comment]
Wow good catch! I had no idea that font-weight for group lable was customizable
The issue was caused by an update to our styling library

**Comment by chanulee1** [comment]
Fields and Relationships bold in schema config.
db: `freshfish`, `UOregonPaleo`
