### ISSUE TITLE
[testability] Cannot read properties of undefined when opening a data set

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2243]
<img width="896" alt="image" src="https://user-images.githubusercontent.com/37256050/192678551-01de9aff-f48f-4b06-b79a-dda8336dab06.png">

When trying to view this workbench data set, I am encountering this error:

https://freshfish-testability.test.specifysystems.org/specify/workbench/2/

user: `abentley`
browser: chrome on macOS

**Comment by maxxxxxdlp** [comment]
I was able to replicate this. Seems to happen when you have one dataset open and try to open another one

**Comment by chanulee1** [comment]
To test should I just try to open another dataset with one already open?

**Comment by maxxxxxdlp** [comment]
Yes
Specifically, the data editing screen should be open (the spreadsheet), not the data mapper

**Comment by chanulee1** [comment]
Able to open another dataset with a dataset already open with no issues.
db: `freshfish`
user: `abentley`
