### ISSUE TITLE
[testability] Navigating to another collection reloads infinitely

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2248]
https://user-images.githubusercontent.com/37256050/192845279-50b8834b-1138-4862-901d-45daa82ce60d.mov

https://freshfish-testability.test.specifysystems.org/specify/command/switch-collection/32768/

**Comment by chanulee1** [comment]
Able to switch collections without reload error.
db: `freshfish`, `willemcatno`
