### ISSUE TITLE
[testability] Screen Shake with Google Translate

### ISSUE THREAD

**Issue by melton-jason** [specify/specify7#2249]
**Describe the bug**
While viewing Specify on Google Chrome in Russian (language code `ru-ru`), and then using Google Translate to translate the site, Specify "shakes" (Video attached below).

This problem seemingly occurs on every page in Specify as long as the page remains translated to English. I am not sure if this is chrome's fault, but it may be. 
I am unable to test the `English -> Russian` side of this scenario, so I don't know if the same problem occurs there as well.

When viewing the Schema Configuration in another language, I am unable to translate the page back to English and thus can not test that either.

**To Reproduce**
1. On the Specify Login page, change the language to `pусский (ru-ru)`. 
2.  Once logged in, use Google Translate to translate the page to English
3. Observe screen shake (as seen in videa)

**Media**

https://user-images.githubusercontent.com/64045831/192891814-995d0b78-c2a2-4cf6-b8e6-4d000536ae15.mp4

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Specify 7 Version: testability

**Comment by grantfitzsimmons** [comment]
![chrome_iHW5hen7Rb](https://user-images.githubusercontent.com/37256050/193032729-89512a07-52e7-47a4-b98c-74bbe021438c.gif)

https://botany-testability.test.specifysystems.org/specify/

un: `testuser`

Same experience here, except even more jittering!

**Comment by grantfitzsimmons** [comment]
![chrome_qmHQFTnC9n](https://user-images.githubusercontent.com/37256050/193033398-866dd33d-e1fb-487f-b560-dba171e176e4.gif)

If I remove the border-width class it stops. This also breaks everything else.

**Comment by grantfitzsimmons** [comment]
Cannot recreate
