### ISSUE TITLE
Taxon Full Name does not update in Specify 7

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#225]
If you change the name of a parent or have the database configured to display text before or after a taxon, it will not be reflected in the Taxon full name field until/unless you log into the Specify 6 instance of the database (or export it out of Specify 7, make the change in Specify 6, and reimport it into Specify 7) and run the Tree Update function there.  
Once the tree has been updated, all of the full name data displays correctly; parent names are updated to reflect changes and text that is supposed to display before or after the taxon will display in the full name field.
This should be tested in the other trees as well.

**Comment by benanhalt** [comment]
Need to check the before and after text.

**Comment by yvonneekanim** [comment]
Tested in taxon and geography trees, changes made are reflected in the full name
