### ISSUE TITLE
When using GeoMap with query results all possible records should be plotted

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2251]
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/37256050/193044925-2fa50ae6-713a-4ad7-9e24-b095cc041006.png">

Currently the GeoMap function maps all loaded records (not every result, just the ones loaded on the page or from the form browser). This is good for the first release, but in the future it would be good to have all records that can be loaded from the query plotted.

This can be implemented as an option or as the default behavior. Potential issues arise from query results with a large number of coordinates.

**Comment by maxxxxxdlp** [comment]
This was fixed in 7.8.1 or 7.8.0
