### ISSUE TITLE
[testability] Creating a new user clears fields and gives warnings, user is created anyway

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2252]
https://user-images.githubusercontent.com/37256050/193047086-be81523a-c4aa-4af6-b75c-62d00cdf6c59.mp4

**Steps to Recreate:**
1. Go to a collection
2. Click **Create** to create a new user
3. Fill out the required fields
4. Click **Save**
5. See fields are cleared
6. Return to collection page, see user

https://freshfish-testability.test.specifysystems.org/specify/security/collection/4/

user: `abentley`
db: `freshfish`

**Comment by maxxxxxdlp** [comment]
Unable to replicate. Seems to be fixed now

**Comment by chanulee1** [comment]
Fields do not clear when save new user.
db: `freshfish`
user: `abentley`
