### ISSUE TITLE
[testability] Show how many records out of the total are plotted

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2253]
<img width="988" alt="image" src="https://user-images.githubusercontent.com/37256050/193048100-6a9acdda-353e-4ffe-9cc7-dc910000279b.png">

With the GeoMap feature in the query builder, there is no way to tell how many records have been mapped out of the total number returned by the query.

**Comment by chanulee1** [comment]
@maxxxxxdlp Where can I see this value in the query builder? Also, is this value different from the "Plotted 354 records out of 49800" in the GeoMap window shown above?

**Comment by maxxxxxdlp** [comment]
The one you see on the screenshot above is the one you should check for.
It wasn't there initially. Grant photoshopped the screenshot to help imagine how it might look like. This fix actually implements that feature

**Comment by chanulee1** [comment]
I see. Number of records plotted out of total records returned is shown.
db: `freshfish`, `willemcatno`
