### ISSUE TITLE
The "Choose Dataset Template" dialog offers templates belonging to all users.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#226]
Click *Workbench* in toolbar, select *New* button, and the resulting "Choose Dataset Template" lists all workbench templates in the database. It should only list those belonging to the logged in user.

**Comment by garrettgirard** [comment]
Verified in KU Birds. When logged in as a user who hasn't created workbench templates, you can't see the workbench templates that were created by other users in the same database.
