### ISSUE TITLE
Cannot save after changing agent associated with a user

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2262]
**Describe the bug**
Cannot save after changing the agent associated with a user.

**To Reproduce**
1. Go to Security and Accounts
2. Go to a collection
3. Go to a user in the collection
4. Change the agent associated with the user
5. Cannot save

**Expected behavior**
Expected to be able to save change to the agent

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Specify 7 Version: 7.7.3

**Database Name:** `freshfish`

**Reported By**
Name of your institution

**Additional context**
Database name or any other context about the problem here.

**Comment by melton-jason** [comment]
The fix worked! Marking this as closed. Reopen if other issues arise.

(Tested on `KUBirds` and `willemcatno`)
