### ISSUE TITLE
[testability] Locality coordinates appear in query results but not in record itself

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2264]
**Describe the bug**
The coordinates of a locality record appear in the results of a query, but do not appear in the record itself.

**To Reproduce**
1. Create a locality query
2. Query for a locality record -- include "Latitude1" and "Longitude1" fields
3. See that latitude and longitude appear
4. Open the record
5. See that latitude and longitude values are not in the record

**Expected behavior**
Expected latitude and longitude values to be in the locality record.

**Screenshots**

https://user-images.githubusercontent.com/103299204/193339199-edb56da4-cab4-4d7a-9c59-ab2065a59bc7.mp4

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Specify 7 Version: `testability`

**Database Name:** `freshfish`

**Reported By**
Name of your institution

**Additional context**
Database name or any other context about the problem here.

**Comment by melton-jason** [comment]
I was able to recreate this issue on the `willemcatno` database in `testability`

**Comment by melton-jason** [comment]
Latitude and Longitude now correctly display in the form view. Nice fix!
Tested on `willemcatno`
