### ISSUE TITLE
[testability] No dialog prompt for setting password during user creation

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2267]
**Describe the bug**
There is no dialog warning to set a password when a new user is created and saved. User cannot login without setting password.

**To Reproduce**
1. Go to Security and Accounts
2. Create a new user without setting a password
3. Save
4. No dialog prompt to set password
5. User cannot login without password

**Expected behavior**
Expected a dialog prompt to appear to warn that no password had been set.

**Screenshots**

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Specify 7 Version: `testability`

**Database Name:** `freshfish`

**Comment by maxxxxxdlp** [comment]
What user were you signed in as? If your user does not have the permission to set a password, the dialog won't appear

**Comment by chanulee1** [comment]
I see, I should have included that. This user had the ability to set a password.
User: `spfishadmin`
Database: `freshfish`

**Comment by melton-jason** [comment]
Issue is fixed! Nice work.
