### ISSUE TITLE
[testability] Username is too big for the button

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2268]
<img width="438" alt="image" src="https://user-images.githubusercontent.com/37256050/193351696-ebd032e5-2e9c-4484-b1f0-a50fd4515b8c.png">

https://emoryherbarium-testability.test.specifysystems.org/specify/

**Comment by maxxxxxdlp** [comment]
Could be fixed by #1640

**Comment by grantfitzsimmons** [comment]
<img width="238" alt="image" src="https://user-images.githubusercontent.com/37256050/211838628-0e6486de-b676-48d4-ba48-8104d73ac507.png">

Maybe #2725 will solve this

**Comment by chanulee1** [comment]
Fixed.
