### ISSUE TITLE
[testability] Collectors grid format not displaying correctly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2277]
<img width="2553" alt="image" src="https://user-images.githubusercontent.com/37256050/193708663-886e0ada-9818-40ee-b8b2-8519d77219d1.png">

After expanding the Collector item in the grid, the proper QCBX displays.

<img width="517" alt="image" src="https://user-images.githubusercontent.com/37256050/193708750-d94066cc-b308-49c1-8588-bbe2947707f3.png">

You can see that the field label is not visible in the columns. This is the same DB!

Left: `testability` - [Link](https://herbrbge-testability.test.specifysystems.org/specify/view/collectionobject/349648/?recordsetid=178)
Right: `v773` - [Link](https://herbrbge-v773.test.specifysystems.org/specify/view/collectionobject/349648/?recordsetid=178)

DB: `herb_rbge`
User: `britchie`

**Comment by chanulee1** [comment]
Collectors grid format displaying correctly.
db: `herbrgbe`

**Comment by chanulee1** [comment]
I was mistaken! QCBX does not display when grid item is expanded.
<img alt="image" width="700px" src="https://user-images.githubusercontent.com/103299204/201829861-e687d86d-785b-4e90-b1a0-f6f76dedf50c.png"/>

https://herbrbge-testability.test.specifysystems.org/specify/view/collectionobject/349648/?recordsetid=178

**Comment by chanulee1** [comment]
In `kufishnotests`:


https://user-images.githubusercontent.com/103299204/201830586-dc804f66-04cb-40d7-b793-e61b291e1565.mp4

https://kufishnotests-testability-2.test.specifysystems.org/specify/view/collectionobject/61115/?recordsetid=44

**Comment by chanulee1** [comment]
Never mind, new issues documented in #2412.
