### ISSUE TITLE
[testability] Child nodes for Geography form showing the 20th item rather than the first

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2278]
https://user-images.githubusercontent.com/37256050/193708976-d6d41dd4-22a8-448c-9f26-ea7e24a9256c.mov

Very interesting descrepency between `v773` and `testability`. 

1) Go to Locality and click on the :pencil2:
2) Go to Geography and click on the :pencil2:
3) See the Child Node number in the paginator

Left: `testability` - [Link](https://herbrbge-testability.test.specifysystems.org/specify/view/collectionobject/349648/?recordsetid=178)
Right: `v773` - [Link](https://herbrbge-v773.test.specifysystems.org/specify/view/collectionobject/349648/?recordsetid=178)

**Comment by chanulee1** [comment]
First record opened by default.
db: `freshfish`, `herbrgbe`
