### ISSUE TITLE
Scrollbar seems to get 'pushed down' following a validation

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#228]
In most datasets that have enough columns that a scrollbar is required at the bottom of the screen, validating cause the scroll bar to be pushed down varying amounts depending on your machine. The scrollbar should probably have a static position on the page, so it would need to adjust with the screen after a validation (which adds more formatting and text at the top of the page) so that it doesn't go so low that you can't see it anymore.

**Comment by benanhalt** [comment]
Does this still happen?

**Comment by yvonneekanim** [comment]
This no longer happens; cursor remains in the same position even after validation.
