### ISSUE TITLE
Unable to create a loan from a set of catalog numbers after entering invalid cat #s

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2280]
https://user-images.githubusercontent.com/37256050/193710054-f2bbe566-79da-4690-b3e2-ed117b08a47d.mov

1. Click on **Interactions**
2. Click **Loan**
3. Enter a catalog number not matching the collection format
5. Try to enter valid catalog numbers in the collection
6. See you are unable to create a loan

db: `herb_rbge`
user: `britchie`

**Comment by maxxxxxdlp** [comment]
Do you need to return a loanned collection object from another collection?

**Comment by grantfitzsimmons** [comment]
That's not the issue, rather once you enter catalog number(s) that do not conform to the collection's formatter, you have to close the dialog and reopen it to enter the correct catalog numbers
