### ISSUE TITLE
[testability] Generate Invoice button takes up full form width

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2283]
![image](https://user-images.githubusercontent.com/37256050/193714873-cceccf44-1478-422e-b75b-1ef7504df0ac.png)

https://herbrbge-testability.test.specifysystems.org/specify/view/gift/new/

https://herbrbge-v773.test.specifysystems.org/specify/view/gift/new/

**Comment by maxxxxxdlp** [comment]
The one in v7.7.3 is incorrect. Caused by a bug (fixed in 5d569cad8. the bug where max width of a subview was limited as a side effect from me wanting to limit the field max-width in the security page for the user)
