### ISSUE TITLE
Sp7 uses wrong PickList if same there is picklist with same name in multiple collections

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2285]
Need to add `&domainfilter=true` when requesting picklists to only return results for current collection.

To Test:
Create picklist with the same name in 2 collections
Assign that pick list to a field in the schema config
Make sure each collection uses the pick list items from the pick list for that collection

**Comment by grantfitzsimmons** [comment]
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/37256050/193926842-b43f383e-b1ee-4004-ac4d-1e5a7df7be93.png">

All pick lists are broken (https://willemcatno-issue-2285.test.specifysystems.org/specify/view/collectionobject/326739/?recordsetid=1187)

<img width="587" alt="image" src="https://user-images.githubusercontent.com/37256050/193927269-fd9b0cfa-4e28-4889-8136-59548adb2ed4.png">

Broken (https://emoryherbarium-issue-2285.test.specifysystems.org/specify/view/collectionobject/4500/?recordsetid=865)

ver: `issue-2285`

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-7-4-release-announcement/807/1
