### ISSUE TITLE
[testability] Running Specify Network from associated Collection Objects in an Accession does not work

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2287]
https://user-images.githubusercontent.com/37256050/193926346-726b7720-8083-44ea-b898-fb2a8f828dfe.mov

Running Specify Network from the associated Collection Object view does not work.

https://willemcatno-testability.test.specifysystems.org/specify/view/accession/2/

user: `collection`

**Comment by maxxxxxdlp** [comment]
I think specify network was just down at that moment (btw, it is down now too, though for a different reason)
