### ISSUE TITLE
[testability] Error Message Dialog Downloads Two Crash Reports 

### ISSUE THREAD

**Issue by melton-jason** [specify/specify7#2288]
**Bug Description**
When the download crash report button is clicked in the error message dialog, two crash reports are downloaded, one being a duplicate of the other. This bug occurs for every press of the download crash report button.

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Specify 7 Version: testability

**Database Name:** If applicable
`willem-catno`

**Comment by chanulee1** [comment]
Also happens when exporting a data set through workbench.
os: Windows 11
Browser: Chrome
Specify 7 Version: `testability`

**Comment by maxxxxxdlp** [comment]
Interesting. I am not able to replicate this. Tried in Chrome on Windows 10
Does this happen in `v7.7.5` too?

**Comment by melton-jason** [comment]
> Interesting. I am not able to replicate this. Tried in Chrome on Windows 10 Does this happen in `v7.7.5` too? Does it happen in other browsers too?

I am not sure about other browser, but yes this issue also occurs in 7.7.5 in Chrome and Edge

**Comment by maxxxxxdlp** [comment]
Duplicate of #2638
