### ISSUE TITLE
Some front-end requests are not properly scoped to current collection

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#2292]
I.e, the `http://localhost/specify/bycatalog/KUIT/000005083/?recordsetid=78` URL will ask for the `000005083` collection object, but does not scope the results to KUIT collection, thus could display a record from a different collection

There are probably other cases like this. Need to audit them

**Comment by maxxxxxdlp** [comment]
From @grantfitzsimmons:

> <img alt="image" width="680" src="https://user-images.githubusercontent.com/37256050/211232825-5ec5376e-ec61-40bf-9e0f-175ad359f121.png">

**Comment by maxxxxxdlp** [comment]
This is a bit more tricky because the scoping system in sp6 and sp7 is messed up badly. See https://github.com/specify/specify7/issues/2912#issuecomment-1406828873 for more info

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp Is this "urgent"?

**Comment by maxxxxxdlp** [comment]
Two biggest bug this fixes:
- Attachment counts are not scoped (even though displayed attachments are)
- Pick lists from table/field are not scoped
- a long with many smaller bugs

Feels big, but no one complained so feel free to delay till 7.9
