### ISSUE TITLE
Loan Invoice not working in Specify 7

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2293]
Loan Number `2022-024`

DB: `cornell_birds`
User: `cdillman`

---
## Specify 6

<img width="785" alt="image" src="https://user-images.githubusercontent.com/37256050/194122753-a512b681-e0ab-4a92-85c5-e774656a0b62.png">

<img width="1785" alt="image" src="https://user-images.githubusercontent.com/37256050/194122689-26911a1f-7c24-4d28-8cb0-1d48cb9cd66a.png">

---
## Specify 7

https://cornellbirds-v773.test.specifysystems.org/specify/task/report/

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/37256050/194122874-166281c3-4cde-4344-b8b2-69f286f57bc5.png">

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/37256050/194122983-2fe95b95-b077-4e14-93b3-c8937255a9ec.png">

**Comment by grantfitzsimmons** [comment]
[Link to XML for the fish loan invoice](https://drive.google.com/open?id=1qKJOsSgSqJnrZenOb_0wBfOKq8Rz3h8Z&authuser=grant%40specifysoftware.org&usp=drive_fs)

**Comment by maxxxxxdlp** [comment]
There were two issues here.
Clothing this as those two issues already have separate bugs: https://github.com/specify/specify7/pull/1999#issuecomment-1219636138 and https://github.com/specify/specify7/pull/1999#issuecomment-1219636138
