### ISSUE TITLE
Sp6 vs 7 pick lists in query compatibility is causing issues

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2296]
See this for background information:
https://github.com/specify/specify7/pull/1999#issuecomment-1219636138

The UI is now able to resolve picklist title to picklist title, but if you run a query it still uses the picklist title, unless you manually change picklist item to another value and then bring it back.

**Comment by maxxxxxdlp** [comment]
To test:
1. Find a pick list where picklist item value is not the same as title (i.e, Agent Type or Permit Type)
2. Create a query in sp6 that includes an `Equals` filter on a filed that is assigned to a pick list from step 1 (i.e, Agent -> Agent Type or Permit -> Type)
3. Run the exact same query in sp7 (not by recreating the same query, but by exporting the database from sp6 and importing into sp7, or by making sp7 use the same database as sp6). Query should return the same results

Also, try doing the same, but using an `In` or `Between` filter instead of `Equals`

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons you should probably be the one to test this one, as it will take you the least time as you have  SSH access to the test server (I tested it locally too and appears to be working, but want you to check it too)

**Comment by grantfitzsimmons** [comment]
Fixed to the best of our abilities -Max
