### ISSUE TITLE
Non-public images should not be readable if you are not logged in

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2298]
![image](https://user-images.githubusercontent.com/37256050/194340606-81618c2f-cd62-40d3-9b0b-2f3d2b7574c9.png)

https://ichthyology.specify.ku.edu/specify/attachments/

**Comment by grantfitzsimmons** [comment]
It's for exporting purposes, meaning that public documents should be publicly viewable. This should be fixed as part of record level permissions then.

**Comment by maxxxxxdlp** [comment]
Does sp6 really look at that attribute?

**Comment by acbentley** [comment]
Depends what you mean by non-public images.  If you mean that they have the "Make public" checkbox unchecked then no.  There is no logic behind that field and it is mainly used for publishing data to aggregators although even then it doesn't work well.

Andy
    A  :             A  :             A  :
 }<(((_°>.,.,.,.}<(((_°>.,.,.,.}<)))_°>
    V                V                V
Andy Bentley
Ichthyology Collection Manager
University of Kansas
Biodiversity Institute
Dyche Hall
1345 Jayhawk Boulevard<x-apple-data-detectors://9/>
Lawrence, KS, 66045-7561<x-apple-data-detectors://9/>
USA<x-apple-data-detectors://9/>

Tel: (785) 864-3863<tel:%28785%29%20864-3863>
Fax: (785) 864-5335<tel:%28785%29%20864-5335>
Email: ***@***.******@***.***>
ORCID: https://orcid.org/0000-0002-3093-1258
http://ichthyology.biodiversity.ku.edu<http://ichthyology.biodiversity.ku.edu/>
    A  :             A  :             A  :
 }<(((_°>.,.,.,.}<(((_°>.,.,.,.}<)))_°>
    V                V                V

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp @acbentley 

For future reference, `isPublic` determines if an image can be seen from within the Specify Web Portal 2.0. This is not documented anywhere from what I can tell but that seems to be the only place it is used.

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons should this issue be closed or the title changed?

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp I still think images that don't have `isPublic` checked should not appear for guest users. What do you think?

**Comment by maxxxxxdlp** [comment]
What is a guest user?
Sp7 is supposed to not look at sp6's user types anymore
Or are you speaking about a permission? In that case, this is in the realm of the record-level permission system (https://github.com/specify/specify7/issues/1957)

**Comment by grantfitzsimmons** [comment]
A "guest" user is one that is configured to be used by anyone with the URL when anonymous access is configured

See [guide on the forum](https://discourse.specifysoftware.org/t/enable-anonymous-guest-access-in-specify-7/992)

```py
# To allow anonymous use, set ANONYMOUS_USER to a Specify username
# to use for anonymous access.
ANONYMOUS_USER = "guest"
```

This user should not see images that are not marked for the public to see

**Comment by grantfitzsimmons** [comment]
I yield, this is not important until someone requests this ability. It should be covered by #1957 if we build it out enough.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/improving-user-permissions-in-specify-7-community-feedback-requested/2893/1
