### ISSUE TITLE
`Attachment.tableID` is nullable in the database, but not in datamodel

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2299]
The `Attachment.tableID` is marked as required, yet it is nullable in the database, which caused a bug with front-end failing for unassociated attachments

**Comment by benanhalt** [comment]
I'll investigate making the field not required by the datamodel.

**Comment by benanhalt** [comment]
I'm not sure what is going on with this field. It seems to be not nullable in most databases which is consistent with the datamodel definition in 6. For some reason it is nullable in the KU Fish database though. Or at least the databases derived from it that I commonly use such as Sp7demofish.

**Comment by maxxxxxdlp** [comment]
Interesting. Could it be that someone changed the data model to make that field required, but did not add a schema migration to update the field in the existing databases?

Either way, this is not a big problem for the front-end as front-end is now always treating that field as nullable (
af9f955). Though, I would be worried if there are other impostor fields like this in the database as they would be just bugs waiting to happen.

**Comment by grantfitzsimmons** [comment]
Looks like this was solved in the Schema 2.10 update. Please reopen if that is not the case.
