### ISSUE TITLE
repeated Cat # not shown as invalid cells

### ISSUE THREAD

**Issue by Oleniacz** [specify/specify7#230]
I entered the same cat# in the same spreadsheet twice. The duplicated cat #'s are Rows 6 & 35, and another set of duplicated numbers are in Rows 13 & 14. While the validation process failed when it came to the first row that had a repeated number (picture 1). The two cells were not presented as invalid (picture 2), and I saw no mention of the duplicated cat # in the the details (picture 3). While, a user can extrapolate that the error is in the row where the validation process stopped, they will not be directed to the error and may be unaware that any duplication could exist. I ran the test again, with just one duplication, Rows 6 & 35. Again, the validation ended at the row with the duplicated cat#, but didn't mention why the validation failed and make no indication that duplicated cat # is the problem.
 
![samecat verficationfailed](https://cloud.githubusercontent.com/assets/17576913/13506669/d3a59372-e144-11e5-8756-7be25e51c982.png)

![samecat verficationfailednoinvalidcells](https://cloud.githubusercontent.com/assets/17576913/13506694/f15b90ba-e144-11e5-8219-1ed6eb0d509e.png)

![samecat verficationfaileddetails](https://cloud.githubusercontent.com/assets/17576913/13506699/f6619cf8-e144-11e5-893f-3085e198a9b3.png)

**Comment by benanhalt** [comment]
I made a change that should cause more information to be included in the details. Can you retry this and verify that there is now some indication in the log of what the problem is. I think this will also capture the error in #231. Once it is verified that the errors are showing up in the details, I can use those as guides to extracting the information to display on the relevant cells.

**Comment by Oleniacz** [comment]
Yep!! I'll do that now

-----Original Message-----

**Comment by Oleniacz** [comment]
This is what appeared in the details/validation log

pid = 23611
2016-03-03T20:58:23Z: Validating only. Will not commit.
2016-03-03T20:58:23Z: starting with args [Suppressed]...
2016-03-03T20:58:24Z: Got master
2016-03-03T20:58:24Z: logged in
2016-03-03T20:58:24Z: Versions OK
2016-03-03T20:58:24Z: good user
2016-03-03T20:58:24Z: got collection name
2016-03-03T20:58:27Z: context established
2016-03-03T20:58:28Z: UploadCmdLine.LoadedWB
uploading row 0
uploading row 1
uploading row 2
uploading row 3
uploading row 4
uploading row 5
2016-03-03T20:58:32Z: UploadCmdLine.UploadFailed
2016-03-03T20:58:32Z: ...exiting UN-successfully.
14:58:28 ERROR wb.wbuploader.MissingDataResolver:497 - unable to meet requirement: Collector.IsPrimary
14:58:29 ERROR datamodel.busrules.LocalityBusRules:293 - The PC null was null or the Locality edu.ku.brc.specify.datamodel.Locality@4f22fd5d : 2016-03-03 14:58:29.418 was null
14:58:29 ERROR datamodel.busrules.CollectingEventBusRules:131 - The PC null was null or the CE edu.ku.brc.specify.datamodel.CollectingEvent@f9cd1e6 : 2016-03-03 14:58:29.426 was null
14:58:30 ERROR datamodel.busrules.CollectionObjectBusRules:731 - The CE null was null or the CO 123456777 was null
14:58:30 ERROR datamodel.busrules.CollectionObjectBusRules:765 - The PC null was null or the CO 123456777 was null
14:58:30 ERROR datamodel.busrules.LocalityBusRules:293 - The PC null was null or the Locality edu.ku.brc.specify.datamodel.Locality@7e366c6f : 2016-03-03 14:58:30.554 was null
14:58:30 ERROR datamodel.busrules.CollectingEventBusRules:131 - The PC null was null or the CE edu.ku.brc.specify.datamodel.CollectingEvent@7fb02606 : 2016-03-03 14:58:30.556 was null
14:58:30 ERROR datamodel.busrules.CollectionObjectBusRules:731 - The CE null was null or the CO 658744558 was null
14:58:30 ERROR datamodel.busrules.CollectionObjectBusRules:765 - The PC null was null or the CO 658744558 was null
14:58:30 ERROR datamodel.busrules.LocalityBusRules:293 - The PC null was null or the Locality edu.ku.brc.specify.datamodel.Locality@62cb977a : 2016-03-03 14:58:30.713 was null
14:58:30 ERROR datamodel.busrules.CollectingEventBusRules:131 - The PC null was null or the CE edu.ku.brc.specify.datamodel.CollectingEvent@61c0fb12 : 2016-03-03 14:58:30.718 was null
14:58:30 ERROR datamodel.busrules.CollectionObjectBusRules:731 - The CE null was null or the CO 120356585 was null
14:58:30 ERROR datamodel.busrules.CollectionObjectBusRules:765 - The PC null was null or the CO 120356585 was null
14:58:30 ERROR datamodel.busrules.LocalityBusRules:293 - The PC null was null or the Locality edu.ku.brc.specify.datamodel.Locality@50331591 : 2016-03-03 14:58:30.916 was null
14:58:30 ERROR datamodel.busrules.CollectingEventBusRules:131 - The PC null was null or the CE edu.ku.brc.specify.datamodel.CollectingEvent@c950fd : 2016-03-03 14:58:30.921 was null
14:58:30 ERROR datamodel.busrules.CollectionObjectBusRules:731 - The CE null was null or the CO 123456792 was null
14:58:30 ERROR datamodel.busrules.CollectionObjectBusRules:765 - The PC null was null or the CO 123456792 was null
14:58:31 ERROR datamodel.busrules.LocalityBusRules:293 - The PC null was null or the Locality edu.ku.brc.specify.datamodel.Locality@21553c3a : 2016-03-03 14:58:31.008 was null
14:58:31 ERROR datamodel.busrules.CollectingEventBusRules:131 - The PC null was null or the CE edu.ku.brc.specify.datamodel.CollectingEvent@6a90b5e8 : 2016-03-03 14:58:31.009 was null
14:58:31 ERROR datamodel.busrules.CollectionObjectBusRules:731 - The CE null was null or the CO 123456793 was null
14:58:31 ERROR datamodel.busrules.CollectionObjectBusRules:765 - The PC null was null or the CO 123456793 was null
14:58:31 ERROR datamodel.busrules.LocalityBusRules:293 - The PC null was null or the Locality edu.ku.brc.specify.datamodel.Locality@26ab3c1b : 2016-03-03 14:58:31.098 was null
14:58:31 ERROR datamodel.busrules.CollectingEventBusRules:131 - The PC null was null or the CE edu.ku.brc.specify.datamodel.CollectingEvent@6f823df7 : 2016-03-03 14:58:31.1 was null
14:58:31 ERROR datamodel.busrules.CollectionObjectBusRules:731 - The CE null was null or the CO 123456777 was null
14:58:31 ERROR datamodel.busrules.CollectionObjectBusRules:765 - The PC null was null or the CO 123456777 was null
14:58:31 ERROR hibernate.util.JDBCExceptionReporter:78 - Duplicate entry '4-123456777' for key 'CollectionID'
14:58:31 ERROR org.hibernate.AssertionFailure:22 - an assertion failure occured (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session)

**Comment by benanhalt** [comment]
Perfect. Can you do the same thing for #231 and see what comes back for that one?

**Comment by Oleniacz** [comment]
This is what I got for #231 
pid = 23640
2016-03-03T20:59:50Z: Validating only. Will not commit.
2016-03-03T20:59:51Z: starting with args [Suppressed]...
2016-03-03T20:59:51Z: Got master
2016-03-03T20:59:52Z: logged in
2016-03-03T20:59:52Z: Versions OK
2016-03-03T20:59:52Z: good user
2016-03-03T20:59:52Z: got collection name
2016-03-03T20:59:55Z: context established
2016-03-03T20:59:55Z: UploadCmdLine.LoadedWB
uploading row 0
uploading row 1
uploading row 2
uploading row 3
2016-03-03T21:00:00Z: UploadCmdLine.UploadFailed
2016-03-03T21:00:00Z: ...exiting UN-successfully.
14:59:56 ERROR wb.wbuploader.MissingDataResolver:497 - unable to meet requirement: Collector.IsPrimary
14:59:57 ERROR datamodel.busrules.LocalityBusRules:293 - The PC null was null or the Locality edu.ku.brc.specify.datamodel.Locality@21ab919c : 2016-03-03 14:59:57.327 was null
14:59:57 ERROR datamodel.busrules.CollectingEventBusRules:131 - The PC null was null or the CE edu.ku.brc.specify.datamodel.CollectingEvent@5ebfe7fa : 2016-03-03 14:59:57.35 was null
14:59:57 ERROR datamodel.busrules.CollectionObjectBusRules:731 - The CE null was null or the CO 444444444 was null
14:59:57 ERROR datamodel.busrules.CollectionObjectBusRules:765 - The PC null was null or the CO 444444444 was null
14:59:58 ERROR datamodel.busrules.LocalityBusRules:293 - The PC null was null or the Locality edu.ku.brc.specify.datamodel.Locality@245dbd09 : 2016-03-03 14:59:58.585 was null
14:59:58 ERROR datamodel.busrules.CollectingEventBusRules:131 - The PC null was null or the CE edu.ku.brc.specify.datamodel.CollectingEvent@1f235a0a : 2016-03-03 14:59:58.6 was null
14:59:58 ERROR datamodel.busrules.CollectionObjectBusRules:731 - The CE null was null or the CO 658744558 was null
14:59:58 ERROR datamodel.busrules.CollectionObjectBusRules:765 - The PC null was null or the CO 658744558 was null
14:59:58 ERROR datamodel.busrules.LocalityBusRules:293 - The PC null was null or the Locality edu.ku.brc.specify.datamodel.Locality@40696fc6 : 2016-03-03 14:59:58.816 was null
14:59:58 ERROR datamodel.busrules.CollectingEventBusRules:131 - The PC null was null or the CE edu.ku.brc.specify.datamodel.CollectingEvent@530bd77b : 2016-03-03 14:59:58.828 was null
14:59:58 ERROR datamodel.busrules.CollectionObjectBusRules:731 - The CE null was null or the CO 120356585 was null
14:59:58 ERROR datamodel.busrules.CollectionObjectBusRules:765 - The PC null was null or the CO 120356585 was null
14:59:58 ERROR datamodel.busrules.LocalityBusRules:293 - The PC null was null or the Locality edu.ku.brc.specify.datamodel.Locality@28d728f1 : 2016-03-03 14:59:58.946 was null
14:59:58 ERROR datamodel.busrules.CollectingEventBusRules:131 - The PC null was null or the CE edu.ku.brc.specify.datamodel.CollectingEvent@1f3310fc : 2016-03-03 14:59:58.963 was null
14:59:59 ERROR hibernate.util.JDBCExceptionReporter:78 - Duplicate entry '1068-130195' for key 'AgentID'
14:59:59 ERROR org.hibernate.AssertionFailure:22 - an assertion failure occured (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session)

**Comment by benanhalt** [comment]
The row on which the problem occurred will now be highlighted and an error tooltip created. The message will be a bit cryptic, but it is the best that can be done with the info that is returned from the Sp6 uploader.

**Comment by garrettgirard** [comment]
Verified in KU Fish. This is now working as Ben said in his last comment. Same goes for Bug #231
