### ISSUE TITLE
Query Results fetcher is not detecting scroll bar correctly

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2301]
Query Builder had a code responsible for fetching records recursively until a scroll bar appears. Amusingly, it was checking for the presence of a horizontal scroll bar rather than a vertical scroll bar

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-7-4-release-announcement/807/1
