### ISSUE TITLE
Adding Geography (any rank) to a report or label causes a time out error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2304]
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/37256050/194618935-476055ad-2f12-4cad-8ff9-82018d8177f3.png">

After running **Test Report**, you can safely assume that the report runner will fail before it can throw an error. I experience a time out issue each time.

<img width="462" alt="image" src="https://user-images.githubusercontent.com/37256050/194619249-38dcfc98-d0c3-489f-a93a-d7ed5918e6ad.png">

Attached are the problematic labels:
[ProblematicLabels.zip](https://github.com/specify/specify7/files/9736114/ProblematicLabels.zip)

The associated query is available here:
[Label Query.json.zip](https://github.com/specify/specify7/files/9736129/Label.Query.json.zip)

https://unitec-edge.test.specifysystems.org/specify/

Username: `spadmin`

This needs to be solved for Unitec's reports and labels to be functional. Not sure where the issue is happening. @maxpatiiuk has taken a look and it seems the query breaks something.

**Comment by grantfitzsimmons** [comment]
Jaspersoft Studio compiles these correctly:
<img width="984" alt="image" src="https://user-images.githubusercontent.com/37256050/194619671-fe9c2d8e-9c40-4c51-9967-cb9e4a83ab9b.png">

Seems to be a Specify issue.

**Comment by grantfitzsimmons** [comment]
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/37256050/194619824-c1b88f42-12e5-44bb-8312-8f6f4ed04308.png">

Eventually you just get kicked out.

**Comment by emenslin** [comment]
Fixed
