### ISSUE TITLE
Backspacing in autocomplete box triggers autocomplete

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2307]
https://github.com/specify/specify7/pull/2203 almost fixed https://github.com/specify/specify7/issues/2169, but not completely, as we run out of time to get the fix into the release window. Thus, a partial fix went out.

This issue is about fixing the bug completely. See comments in https://github.com/specify/specify7/issues/2169 for more info

**Comment by chanulee1** [comment]
Backspacing does not trigger autocomplete.
db: `freshfish`, `willemcatno`
