### ISSUE TITLE
Collector 1 & 2 are same agent

### ISSUE THREAD

**Issue by Oleniacz** [specify/specify7#231]
I entered the same agent as collector 1 and collector 2 for the same collection object (Row 4). The validation process failed when it came to the 4th row that had the same agent as collector 1 and 2, but the cells containing the duplication of the agent were not shown as invalid (picture 2), and I saw no mention of the duplication of the agent as collector 1 and collector 2 in the the details (picture 3). While, a user can extrapolate that the error is in the row where the validation process stopped, they will not be directed to the error and may be unaware that they entered the same person for collector 1 and collector 2. 
![samecollector1 2validationfailed](https://cloud.githubusercontent.com/assets/17576913/13508406/7ca940ac-e14c-11e5-9d92-636a60a298d8.png)
![samecollector1 2noshownasinvalid](https://cloud.githubusercontent.com/assets/17576913/13508408/7d9a24e0-e14c-11e5-8ca0-f2a169716df9.png)
![samecollector1 2details](https://cloud.githubusercontent.com/assets/17576913/13508415/80487048-e14c-11e5-97ab-68de8e0a87ac.png)

**Comment by benanhalt** [comment]
Duplicates #230

**Comment by garrettgirard** [comment]
Verified in KU Fish. This is now working as Ben said in his last comment. Same goes for Bug #230
