### ISSUE TITLE
FishBase weblink does not work

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2311]
Replicated in Andy's database: https://ichthyology.specify.ku.edu/specify/view/collectionobject/46076/

The link does not get populated with the species and genus fields

**Comment by maxxxxxdlp** [comment]
There was special in Specify 7 code just for that web link
I removed it because it wasn't working, and because that action can be accomplished without that code thanks to improvements on `xml-editor` branch - in particular, you can use a formatter in a weblink, and a formatter could be made to recursively climb the tree to get to `species` or `genus` nodes and get their names.

We would have to change the default web link to include that feature.
Until then, the behavior for this web link on the `xml-editor` branch would be equivalent to that in specify 6 - it will open a dialog prompting user to enter values for `Genus` and `Species`

**Comment by grantfitzsimmons** [comment]
This is something we are not going to fix, but in the future we should not ship this web link by default.
