### ISSUE TITLE
Editing tree - crash reports

### ISSUE THREAD

**Issue by benritchie** [specify/specify7#2312]
Folks

we are still seeing a lot of errors / failures in the tree view when trying to move / merge items.

see examples below:
Making a couple of changes in the higher level taxonomy - Merging Plasmodial slime molds with Mycetozoa
Crash report

[Specify.7.Crash.Report.-.2022-10-11T08_20_00.267Z.txt](https://github.com/specify/specify7/files/9753834/Specify.7.Crash.Report.-.2022-10-11T08_20_00.267Z.txt)

Tried moving one of the children instead and got this crash report
[Specify.7.Crash.Report.-.2022-10-11T08_27_31.416Z.txt](https://github.com/specify/specify7/files/9753837/Specify.7.Crash.Report.-.2022-10-11T08_27_31.416Z.txt)

Tried moving Plasmodial slime mold into Protozoa
Got this crash report
[Specify.7.Crash.Report.-.2022-10-11T08_29_26.363Z.1.txt](https://github.com/specify/specify7/files/9753840/Specify.7.Crash.Report.-.2022-10-11T08_29_26.363Z.1.txt)

**Comment by maxxxxxdlp** [comment]
The error code is `504 (Gateway Timeout)`. Likely caused by the server responding to requests too slowly.

Need to upgrade the server or fix tree performance issues

**Comment by benritchie** [comment]
Server is hosted by you - RBGE-herb
Thanks

**Comment by grantfitzsimmons** [comment]
These reports are unfortunately too ambiguous to give us enough to try and recreate. We have since stepped up error reporting and handling. In addition, we have dramatically improved the hosted instance servers and added many checks for uptime.

In the future, any new tree errors will be logged as individual issues (as we have done for the past several months already).

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons I belive the attached errors were caused by node renumbering and full name regeneration - things we are working on fixing right now
