### ISSUE TITLE
[testability] Form Configuration for Data Entry not behaving correctly

### ISSUE THREAD

**Issue by melton-jason** [specify/specify7#2317]
**Describe the bug**
In the Form Configuration options in Data Entry, there are 2 interactables which behave unexpectedly: the `use localized field labels` checkbox in `Form Definition` options, and the `Enable Read Only Mode` button.

**Localized Field Labels Checkbox**
1. Go to any form from Data Entry
2. Click on the settings icon and then on Form Definition 
3. Check/Uncheck `Use localized field lables`
4. Specify will reload the page, with `Use localized field lables` checked and the expected field labels being shown 
5. User can now not uncheck `Use localized field lables`, as it will reload the page every time with the checkbox checked 
6. (Can be fixed by clicking on `Enable Read Only Mode` button. See below.)

**Enable Read Only Mode Button**
1. Go to any form from Data Entry
2. Click on the settings icon
3. Click on the `Enable Read Only Mode` button
4. Specify will redirect the user to the home page and reset the form configuration options

Possible cause:
This may be caused due to the fact that whenever a page is loaded, in the console Specify throws a 404 as it can not find `app.resource?name=DefaultUserPreferences`

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Specify 7 Version: testability

**Database**
tested on willemcatno and Invertpaleo

**Comment by chanulee1** [comment]
`Use localized field labels` and `Enable read-only mode` seem to work as expected.
db: `freshfish`, `herbrbge`
