### ISSUE TITLE
[testability] Read-Only button does not preserve url

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2319]
**Describe the bug**
Clicking the Read-Only button takes user back to home screen

**To Reproduce**
1. Go to a data entry from
2. Click on form prefs (gear icon)
3. Click on "Enable Read-Only Mode"
4. Return to home page

**Expected behavior**
Expected to remain on the data entry form.

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Specify 7 Version: `testability`

**Database Name:** `willemcatno`

**Comment by melton-jason** [comment]
This behavior is already mentioned in #2317. Maybe we can close one in favor for the other?

**Comment by chanulee1** [comment]
Ah, I see. I will close this issue.
