### ISSUE TITLE
Can upload Agent with just first or middle name

### ISSUE THREAD

**Issue by Oleniacz** [specify/specify7#232]
While testing collection object spreadsheets I noticed you can add collectors by just their first or middle name, without their last name. These aren't caught in the validation process and can be uploaded. 

Entering Agent Data only, I was able to upload an agent with just a first name and another with just a middle name.

**Comment by benanhalt** [comment]
@timo11 @tlammer Is this supposed to be possible?

**Comment by timo11** [comment]
It is possible.

There are no constraints or business rules that prevent it, so the 
uploader allows it.
Hopefully if LastName was marked as required in the schema, it wouldn't 
be allowed.

**Comment by tlammer** [comment]
I thought it wasn't supposed to be possible so I told the testers to test for it specifically

**Comment by timo11** [comment]
It's possible if LastName is not required in the schema config.

**Comment by benanhalt** [comment]
Again, last name really should probably be required it the schema config.
