### ISSUE TITLE
[testability] Read-Only button may break data entry menu

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2320]
**Describe the bug**
Kind of hard to reproduce, but sometimes enabling "Read-Only Mode" seems to cause the items in the data entry menu to disappear.

**To Reproduce**
1. Go to a data entry form
2. Click on form prefs (gear icon)
3. Click on "Enable Read-Only Mode"
4. Click on "Data Entry"
5. See that data entry menu is empty and cannot select type of form

This bug seemed to happen after repeating these steps for a couple of times.

**Expected behavior**
Expected the data entry menu to not be empty.

**Screenshots**
<img alt="image" width="600px" src="https://user-images.githubusercontent.com/103299204/195394427-acf4fb43-a4c8-4e9c-9626-e633898d7c44.png"/>

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Specify 7 Version: `testability`

**Database Name:** `willemcatno`
col: `Amphibian Collection`, `Alga Collection`

**Comment by maxxxxxdlp** [comment]
That's the point of the read-only mode, isn't it?
In read-only mode you can't create records, delete records, modify records, thus it wouldn't make sense to display some items in the Data Entry Menu.
I will make it hide that menu item entirely when read-only.

**Comment by chanulee1** [comment]
"Data Entry" menu item hidden when read-only mode is enabled
db: `freshfish`, `willemcatno`
