### ISSUE TITLE
[testability] Cannot open a record set

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2321]
**Describe the bug**
Error message appears when trying to open a record set in the `saiab_2021_11_25` database

**To Reproduce**
1. Go to "Record Sets"
2. Click on a record set
3. See error message: 
[Specify 7 Crash Report - 2022-10-12T18_19_18.691Z (1).txt](https://github.com/specify/specify7/files/9767691/Specify.7.Crash.Report.-.2022-10-12T18_19_18.691Z.1.txt)

**Expected behavior**
Expected to be able to view record set.

**Screenshots**
![image](https://user-images.githubusercontent.com/103299204/195418704-f0200077-c9ef-432a-a7db-1fd9c5895b99.png)

<a href="https://user-images.githubusercontent.com/103299204/195419196-e67769a7-29d7-46e0-a7ad-c50bbd85c23a.png">Console</a>

Record set: https://saiab20211125-testability.test.specifysystems.org/specify/view/collectionobject/245518/?recordsetid=1088

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Specify 7 Version: `testability`

**Database Name:** `saiab_2021_11_25`
col: `BRUV Fish`
user: `collection`

**Comment by benanhalt** [comment]
Looks like the database dump didn't get fully loaded on the test server. You can tell by doing a 'show tables;' in mysql. If the database was fully restored the last tables in the list will be the workbench ones.

**Comment by maxxxxxdlp** [comment]
@chanulee1 if you need that database to work, you should delete it from the test server and upload it again from the back-up
