### ISSUE TITLE
Color options for subview buttons

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2326]
> It often not so obvious for the buttons for attachments, DNA, or a linked table that they are active. The small number in the box right to it is easily overlooked.
> It would be helpful if the buttons change from greyscale to colour once a link is established

**Requested By:** Schuchert on the [Specify Community Forum](https://discourse.specifysoftware.org/t/form-views-buttons-for-attachments-dna-and-other-change-from-greyscale-to-colour/811/1)

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/form-views-buttons-for-attachments-dna-and-other-change-from-greyscale-to-colour/811/2
