### ISSUE TITLE
Unable to delete user

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2327]
**Describe the bug**
When try to delete a user in the `willemcatno` database, error message occurs.

**To Reproduce**
1. Go to Security and Accounts
2. Click on a user
3. Delete the user
[Specify 7 Crash Report - 2022-10-14T16_48_31.040Z (1).txt](https://github.com/specify/specify7/files/9788944/Specify.7.Crash.Report.-.2022-10-14T16_48_31.040Z.1.txt)

**Expected behavior**
Expected to be able to delete user.

**Screenshots**
![image](https://user-images.githubusercontent.com/103299204/195921723-3372223f-aec5-4580-af77-bd579601dc57.png)

<a href="https://user-images.githubusercontent.com/103299204/195916508-c6d92986-c2ab-4fa3-aa58-b06ce9fa05f1.png">Console</a>

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Specify 7 Version: 7.7.4.1

**Database Name:** `willemcatno`
user: `collection`

**Comment by maxxxxxdlp** [comment]
Duplicate of https://github.com/specify/specify7/issues/1069
