### ISSUE TITLE
[testability] Need to press enter twice to initiate search in Express Search

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2328]
**Describe the bug**
After an initial search, clearing the search bar and initiating a new search requires pressing "enter" twice.

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Specify 7 Version: `testability`

**Comment by melton-jason** [comment]
As an additional comment, the first "enter" press redirects the user to a new url, but still displays the content of the previous search. It isn't until "enter" is pressed again that the correct search results are displayed.

**Comment by maxxxxxdlp** [comment]
Can this be clarified. Is this for the express search, or the query builder?
Does it still happen in the newer release? we made changes to the express search with the introduction of side menu

**Comment by chanulee1** [comment]
@maxxxxxdlp This was for express search, but I am not able to replicate it on `edge`. I believe this issue can be closed. Tested: `coldFish`.
