### ISSUE TITLE
Wonky Validation - Keeps failing with different spreadsheet

### ISSUE THREAD

**Issue by Oleniacz** [specify/specify7#233]
In the Invp DB I have been trying to test lithostrat, geog, and taxon only spreadsheet and I don't think Sp7 likes them. I keep getting the same validation failed message. Both speadsheets stopped at row 38. I couldn't see anything wrong with any of the data and I remapped them several times. I don't know if I'm doing something wrong or if it is an actual issue at this point. 

![validationfailedgeog](https://cloud.githubusercontent.com/assets/17576913/13542376/e9f3fbee-e227-11e5-9fa9-ae9d62419bd2.png)
![validationfailedlithostrat](https://cloud.githubusercontent.com/assets/17576913/13542377/e9fc2f08-e227-11e5-9298-6762a25b09b3.png)

**Comment by Oleniacz** [comment]
This is what I got in the validation log after the geography only spreadsheet failed validation. 

pid = 28837
2016-03-04T22:28:19Z: Validating only. Will not commit.
2016-03-04T22:28:19Z: starting with args [Suppressed]...
2016-03-04T22:28:20Z: Got master
2016-03-04T22:28:20Z: logged in
2016-03-04T22:28:20Z: Versions OK
2016-03-04T22:28:20Z: good user
2016-03-04T22:28:20Z: got collection name
2016-03-04T22:28:24Z: context established
2016-03-04T22:28:24Z: UploadCmdLine.LoadedWB
uploading row 0
uploading row 1
uploading row 2
uploading row 3
uploading row 4
uploading row 5
uploading row 6
uploading row 7
uploading row 8
uploading row 9
uploading row 10
uploading row 11
uploading row 12
uploading row 13
uploading row 14
uploading row 15
uploading row 16
uploading row 17
uploading row 18
uploading row 19
uploading row 20
uploading row 21
uploading row 22
uploading row 23
uploading row 24
uploading row 25
uploading row 26
uploading row 27
uploading row 28
uploading row 29
uploading row 30
uploading row 31
uploading row 32
uploading row 33
uploading row 34
uploading row 35
uploading row 36
uploading row 37
uploading row 38
uploading row 39
uploading row 40
uploading row 41
uploading row 42
uploading row 43
uploading row 44
uploading row 45
uploading row 46
uploading row 47
uploading row 48
uploading row 49
uploading row 50
uploading row 51
uploading row 52
uploading row 53
uploading row 54
uploading row 55
uploading row 56
uploading row 57
uploading row 58
uploading row 59
uploading row 60
uploading row 61
uploading row 62
uploading row 63
uploading row 64
uploading row 65
uploading row 66
uploading row 67
uploading row 68
uploading row 69
uploading row 70
uploading row 71
uploading row 72
uploading row 73
uploading row 74
uploading row 75
uploading row 76
uploading row 77
uploading row 78
uploading row 79
uploading row 80
uploading row 81
uploading row 82
uploading row 83
uploading row 84
uploading row 85
uploading row 86
uploading row 87
uploading row 88
uploading row 89
uploading row 90
uploading row 91
uploading row 92
uploading row 93
uploading row 94
uploading row 95
uploading row 96
uploading row 97
uploading row 98
uploading row 99
uploading row 100
uploading row 101
uploading row 102
uploading row 103
uploading row 104
uploading row 105
uploading row 106
uploading row 107
uploading row 108
uploading row 109
uploading row 110
uploading row 111
uploading row 112
uploading row 113
uploading row 114
uploading row 115
uploading row 116
uploading row 117
uploading row 118
uploading row 119
uploading row 120
uploading row 121
uploading row 122
uploading row 123
uploading row 124
uploading row 125
uploading row 126
uploading row 127
uploading row 128
uploading row 129
uploading row 130
uploading row 131
uploading row 132
uploading row 133
uploading row 134
uploading row 135
uploading row 136
uploading row 137
uploading row 138
uploading row 139
uploading row 140
uploading row 141
uploading row 142
uploading row 143
uploading row 144
uploading row 145
uploading row 146
uploading row 147
uploading row 148
uploading row 149
uploading row 150
uploading row 151
uploading row 152
uploading row 153
uploading row 154
uploading row 155
uploading row 156
uploading row 157
uploading row 158
uploading row 159
uploading row 160
uploading row 161
uploading row 162
uploading row 163
uploading row 164
uploading row 165
uploading row 166
uploading row 167
uploading row 168
uploading row 169
uploading row 170
uploading row 171
uploading row 172
uploading row 173
uploading row 174
uploading row 175
uploading row 176
uploading row 177
uploading row 178
uploading row 179
uploading row 180
uploading row 181
uploading row 182
uploading row 183
uploading row 184
uploading row 185
uploading row 186
uploading row 187
uploading row 188
uploading row 189
uploading row 190
uploading row 191
uploading row 192
uploading row 193
uploading row 194
uploading row 195
uploading row 196
uploading row 197
uploading row 198
uploading row 199
uploading row 200
uploading row 201
uploading row 202
uploading row 203
uploading row 204
success
2016-03-04T22:28:26Z: UploadCmdLine.Uploaded
2016-03-04T22:28:26Z: ...exiting successfully.
16:28:24 ERROR specify.config.SpecifySchemaI18NService:168 - Couldn't find field[relationships] for table [collectionreltype]
16:28:24 ERROR specify.config.SpecifySchemaI18NService:168 - Couldn't find field[dnaSequencingRun] for table [dnasequenceattachment]
16:28:24 ERROR specify.config.SpecifySchemaI18NService:168 - Couldn't find field[collectionMemberId] for table [paleocontext]
16:28:24 ERROR specify.config.SpecifySchemaI18NService:244 - Couldn't find field[relationships] for table [collectionreltype]
16:28:24 ERROR specify.config.SpecifySchemaI18NService:244 - Couldn't find field[dnaSequencingRun] for table [dnasequenceattachment]
16:28:24 ERROR specify.config.SpecifySchemaI18NService:244 - Couldn't find field[collectionMemberId] for table [paleocontext]

**Comment by Oleniacz** [comment]
This is what i got after the lithostrat failed validation. I left out some of the uploading rows because there is over 3000.

pid = 28868
2016-03-04T22:30:57Z: Validating only. Will not commit.
2016-03-04T22:30:58Z: starting with args [Suppressed]...
2016-03-04T22:30:58Z: Got master
2016-03-04T22:30:59Z: logged in
2016-03-04T22:30:59Z: Versions OK
2016-03-04T22:30:59Z: good user
2016-03-04T22:30:59Z: got collection name
2016-03-04T22:31:02Z: context established
2016-03-04T22:31:07Z: UploadCmdLine.LoadedWB
uploading row 0
uploading row 1
uploading row 2
uploading row 3
uploading row 4
uploading row 5
uploading row 6
uploading row 7
uploading row 8
...
uploading row 3056
uploading row 3057
success
2016-03-04T22:33:28Z: UploadCmdLine.Uploaded
2016-03-04T22:33:28Z: ...exiting successfully.
16:31:02 ERROR specify.config.SpecifySchemaI18NService:168 - Couldn't find field[relationships] for table [collectionreltype]
16:31:02 ERROR specify.config.SpecifySchemaI18NService:168 - Couldn't find field[dnaSequencingRun] for table [dnasequenceattachment]
16:31:02 ERROR specify.config.SpecifySchemaI18NService:168 - Couldn't find field[collectionMemberId] for table [paleocontext]
16:31:02 ERROR specify.config.SpecifySchemaI18NService:244 - Couldn't find field[relationships] for table [collectionreltype]
16:31:02 ERROR specify.config.SpecifySchemaI18NService:244 - Couldn't find field[dnaSequencingRun] for table [dnasequenceattachment]
16:31:02 ERROR specify.config.SpecifySchemaI18NService:244 - Couldn't find field[collectionMemberId] for table [paleocontext]

**Comment by benanhalt** [comment]
Pretty sure this is because of the spurious 'ERROR' messages after the 'success' message. I think it looks for the 'exiting successfully' message on the last line. I'll make it more flexible.

**Comment by garrettgirard** [comment]
Verified using the same db, KU INVP, as well as some of the same spreadsheets that Brittney used in testing. These all now pass the validation without the errors above.
