### ISSUE TITLE
[testability] App resource viewer not displaying all resources at the correct level

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2330]
When viewing the sidebar, you can see that resources **under the collections are not being displayed.** The collection resources are being placed under the user who created them (presumably) rather than the collection itself. These should be scoped to the collection, not the user.

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/37256050/196216774-3abb4df2-d764-428f-890a-cd00402acbd4.png">

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/37256050/196216984-f843c691-67c6-468e-8e53-15ae51dfac5e.png">

db: `freshfish`

`edge` (7.7.5) and `testability`

**Comment by chanulee1** [comment]
App resources seem to be displaying at the correct level.
However, the "Add resource" option is missing.
<img alt="image" width="500px" src="https://user-images.githubusercontent.com/103299204/197851773-3af24be8-8985-4bb9-ad15-cfe3c80a63bb.png"/>
Link: https://freshfish-testability.test.specifysystems.org/specify/resources/

**Comment by maxxxxxdlp** [comment]
Unable to reproduce:

![Screen Shot 2022-10-25 at 15 53 01](https://user-images.githubusercontent.com/40512816/197879750-92505754-b8e4-4db2-8c82-73d69d51089c.png)

@chanulee1 Did you happen to have read-only mode enabled? In read-only mode the "Add" button would be missing

**Comment by chanulee1** [comment]
Sorry. Yes, that was the issue. Resources seem to be displaying at the correct level.
db: `freshfish`, `herbrbge`
compared: `testability`, `edge`
