### ISSUE TITLE
RelatedObjectDoesNotExist ('Groupperson has no member.') when validating

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2332]
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/37256050/196219203-c7559023-c7e5-4889-b0cc-c3fac6b22bc0.png">

https://suriname-edge.test.specifysystems.org/specify/workbench/2/

user: `spadmin`

They’re trying to establish a group agent in the WB (without any value in the primary agent they are using as a base) from what I can tell. This error should probably be caught during validation

**Reported By:** Suriname Zoology

**Comment by emenslin** [comment]
Fixed
