### ISSUE TITLE
[testability] Query Combo Box Starts With (Case Sensitive) Algorithm behaving oddly

### ISSUE THREAD

**Issue by melton-jason** [specify/specify7#2334]
**Describe the bug**
There seem to be 2 main issues regarding the Starts With (Case Sensitive) Query Combo Box algorithm. For screenshot/testing purposes, I used an Accession QCBX in willemcatno's Collection Object Form, although I have observed this behavior in other query combo boxes as well.

1.  The algorithm is searching by Ends With, and not Starts With
2. The algorithm  is not case sensitive

**Screenshots**
![Screenshot 2022-10-17 153954](https://user-images.githubusercontent.com/64045831/196286402-59364a74-52ee-4807-b05d-c49edfd7d10f.png)
---

![Screenshot 2022-10-17 154144](https://user-images.githubusercontent.com/64045831/196286420-5e27ad90-c0f0-4600-8137-8575839fc269.png)
---

![Screenshot 2022-10-17 154608](https://user-images.githubusercontent.com/64045831/196286468-d6a72c89-103f-44fe-bf54-12dde80b1bb5.png)
---

![Screenshot 2022-10-17 154823](https://user-images.githubusercontent.com/64045831/196286508-38e85fec-9bc0-4ea9-aecc-7641a1b1cf0a.png)

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Specify 7 Version: testability

**Database Name:** 
willemcatno

**Comment by maxxxxxdlp** [comment]
Ah, year, it searching as ends with instead of starts with is a bug.
Also, I thought it was case-sensitive, but apparently, it isn't. Thus I will remove this user preferences option

**Comment by chanulee1** [comment]
"Starts With (case sensitive)" algorithm removed from qcbx search algorithm options. However, it seems that the "Contains (case sensitive)" qcbx algorithm is not case sensitive either.
<img alt="image" width="500px" src="https://user-images.githubusercontent.com/103299204/197854716-49d1a576-9020-4f45-b2c3-fbbe7e149a69.png"/>
https://willemcatno-testability.test.specifysystems.org/specify/view/collectionobject/new/

**Comment by chanulee1** [comment]
Description for "contains" search algorithm updated.
db: `freshfish`, `willemcatno`
