### ISSUE TITLE
[testability] Specify throws error at duplicate user name

### ISSUE THREAD

**Issue by melton-jason** [specify/specify7#2336]
To Reproduce:
1. Go to Security and Accounts
2. Create a user with a name that already exists in the database
3. See Error

While this is expected, it may be better on a UX stance to validate the user name before saving, checking if the name already exists and have a warning or message that tells the user the issue (Like the fix for #2267) without throwing an error and forcing them to the home page.

Database- `botany`
OS- Windows 11
Browser- Chrome
Specify Version- testability

**Comment by maxxxxxdlp** [comment]
Duplicate of https://github.com/specify/specify7/issues/2260
