### ISSUE TITLE
Customizing tree accent color does not work quite right

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2339]
As discovered during a webinar
Customizing the accent color sometimes leads to tree still using the old accent color.
Or sometimes customizing the accent color for one tree also applies to another tree.
Seems like the code that checks which tree to use the accent color for is a bit broken

**Comment by CarolineDenis** [comment]
The underlying issue seems to cause this as well: https://github.com/specify/specify7/issues/3500

**Comment by maxxxxxdlp** [comment]
I think this might have actually been caused by the same issue as https://github.com/specify/specify7/issues/3578.

Could someone check if https://github.com/specify/specify7/pull/3586 fixes this issue?
