### ISSUE TITLE
Deleting lots of data from big dataset takes a while, and sometimes makes page crash

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#234]
If you import a dataset with a large number of rows (I used one with over 8,000 rows), and try to delete an entire column of data (assuming the data isn't empty in the majority of the rows), you will have to wait a really long time for it to finish deleting. Sometimes this will cause the webpage to crash and you might get a message like "Page is unresponsive, would you like to kill it or wait" or something along those lines.

**Comment by maxxxxxdlp** [comment]
Fixed in 7.6.00

**Comment by maxxxxxdlp** [comment]
From my quick test it takes about a second to delete values from 84,000 cells. The page does not crash
