### ISSUE TITLE
Ability to query based on relative date

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2345]
The ability to run a query using a relative date would be great.
Particularly useful in stats queries where you want to see stats for the last x days, without having to adjust the dates manually every time.

**Comment by maxxxxxdlp** [comment]
From @grantfitzsimmons:
> Requested By: Dan at CSIRO

**Comment by realVinayak** [comment]
Resolved in statspage branch

**Comment by maxxxxxdlp** [comment]
> Resolved in statspage branch

@realVinayak in such cases, you should either link the issue to a pull request so that testers are aware that this is fixed when reviewing the pull request and so that the issue get closed automatically when the pull request is merged

You could also make github link them automatically by mentioning `Fixes #issueNumber` in any pull request comment
