### ISSUE TITLE
Error message when query for formatted records

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2347]
**Describe the bug**
When make a query for the formatted records of a table, an error message occurs.

**To Reproduce**
1. Go to query builder
2. Click on any table
3. Click "formatted"
4. Run query
5. See error:
[Specify 7 Crash Report - 2022-10-24T04_14_09.507Z.txt](https://github.com/specify/specify7/files/9848705/Specify.7.Crash.Report.-.2022-10-24T04_14_09.507Z.txt)

Link: https://kufish-testability.test.specifysystems.org/specify/query/new/author/

**Expected behavior**
Expected to be able to query for formatted records of a table.

**Screenshots**
<img alt="image" width="500px" src="https://user-images.githubusercontent.com/103299204/197447426-31389271-71b1-414b-a0c8-6afdc000c51b.png"/>

<a href="https://user-images.githubusercontent.com/103299204/197447609-12ae36ef-600f-4af9-b19a-011ac004fae6.png">Console</a>

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Specify 7 Version: `testability`

**Database Name:** `kufish`, `freshfish`, `willemcatno`

**Comment by chanulee1** [comment]
Related?
<img alt="image" width="500px" src="https://user-images.githubusercontent.com/103299204/197449210-35696995-716a-4af1-8c63-6f8159915f5c.png"/>

**Comment by maxxxxxdlp** [comment]
Fixed in 92b8ad872

The `<Formatter not defined>` is unrelated (that's because this database does not have a DataObjFormatter defined for Taxon table)

**Comment by chanulee1** [comment]
Works!
db: `freshfish`, `herbrbge`
