### ISSUE TITLE
Invalid Cell Message Remains on screen

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#235]
Sometimes, although I haven't figured out exactly how this happens, after making changes to invalid cells and revalidating them in the Workbench, the validation error message will stay on the screen. There is no way to get rid of it by scrolling the mouse over it, and even when scrolling up and down the message follows the screen up and down. Again, I'm not sure how this happens, but it seems to happen after doing several changes to invalid cells, saving, and revalidating. Attached is an image with several instances in one dataset at one time.
![error text remains](https://cloud.githubusercontent.com/assets/12533028/13716258/9f1ec4d2-e79f-11e5-8c52-ca0815944ddd.png)

**Comment by Oleniacz** [comment]
Try clicking the cell and pressing the tab button. Sometimes that works.

-----Original Message-----

**Comment by garrettgirard** [comment]
Hm. Doesn't seem to do anything for me. 

    On Friday, March 11, 2016 3:44 PM, Oleniacz <notifications@github.com> wrote:
 

 Try clicking the cell and pressing the tab button. Sometimes that works.

-----Original Message-----

**Comment by benanhalt** [comment]
I can't seem to get it to happen. The messages appear when you mouse over. Do they just not fade when you move the mouse, then? Or do they reappear spontaneously when revalidating?

**Comment by garrettgirard** [comment]
I'm not sure exactly how to get it to happen, all I know is that it does happen every once in a while, and it tends to happen more with databases that have more validation errors. But what happens usually is that the message just doesn't fade after scrolling over it with the mouse. So you may not have to revalidate for this issue to occur.

**Comment by yvonneekanim** [comment]
I can't get this to happen. Invalid cells do not get highlighted and no validation error messages appear.
