### ISSUE TITLE
Render Collection Relationships plugin as a FormTable

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2356]
CSIRO and others asked for extending the functionality of the Collection Relationships plugin.

They asked for features like sorting the columns and displaying more than one column at once.

Thus, rendering the collection relationship plugin as a FormTable would make sense (as it included all of these features)

See also https://github.com/specify/specify7/issues/1981

**Comment by grantfitzsimmons** [comment]
This can already be done by creating a custom form definition for the Col Rel table.
