### ISSUE TITLE
Taxon uploads in the WorkBench do not have isAccepted set by default

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2361]
Any taxon records uploaded through the WorkBench in Specify 7 do not have `isAccepted` set by default.

This can be seen in `newmexico2` currently, but that is subject to change. This has caused issues in cases where the full name display format is modified as the full name is not built for non-preferred taxon records.

**Comment by grantfitzsimmons** [comment]
This is pretty urgent– so if a new dev wants to take a look, please do!!!

**Comment by grantfitzsimmons** [comment]
Still pretty urgent. Can another dev take a look at this? @melton-jason When you get a second of course...

**Comment by grantfitzsimmons** [comment]
Chanu has an open PR #3157

**Comment by carlosmbe** [comment]
Could not recreate issue in `NHMD` and `sdnhmpaleo` on Edge as of 8 January 2024 and 7.9

**Comment by carlosmbe** [comment]
Also tested uploading new Taxon as Determininations of a Collection Object. Worked fine. Tested in 7.9 on `morpaleo`. 

If you want to test in future, I recommend MOR Paleo as it's practically empty and thus has quick workbench uploads
