### ISSUE TITLE
Table grid has too much contrast

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2363]
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/37256050/198400627-80317935-288c-4fd2-b09e-484e1ce036b0.png">

In light mode.

**Comment by melton-jason** [comment]
Can someone confirm this? When comparing `edge` vs `testability`, There seems to be less contrast for Dark Mode, but even more for Light Mode. 

## Light Mode
Edge:
![dbschema_edge_light](https://user-images.githubusercontent.com/64045831/203822798-64f95de2-c7ef-4dd0-8cee-fa3eb387c686.png)

Testability:
![dbschema_testability_light](https://user-images.githubusercontent.com/64045831/203822802-39cfad60-bd03-496b-9ac4-84a96137ef5f.png)


## Dark Mode
Edge:
![dbschema_edge_dark](https://user-images.githubusercontent.com/64045831/203822801-8d1174ea-1690-441f-93f0-bfbf2b8c4c75.png)

Testability:
![dbschema_testability_dark](https://user-images.githubusercontent.com/64045831/203822803-6a372d21-b924-468b-bafd-3b6ddad90afb.png)

**Comment by maxxxxxdlp** [comment]
The light mode contrast is higher than in edge, but still lower than it was before this change.
The dark more is also lower contrast, so that it is a bit easier on the eyes - all good
