### ISSUE TITLE
[testability] Navigation menu not centered perfectly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2365]
<img width="2075" alt="image" src="https://user-images.githubusercontent.com/37256050/198907106-20ce4695-db27-4a1d-ad8b-6df33a364f84.png">

The information on the right is wider than the logo.

**Comment by maxxxxxdlp** [comment]
This would be fixed by https://github.com/specify/specify7/issues/1640 as that would make the header buttons take less space.

Not urgent for 7.8 as the issue has been present in 7.7. Will be fixed in an incremental release

**Comment by maxxxxxdlp** [comment]
This is a non-fix as we are replacing the top menu with a side menu
