### ISSUE TITLE
[testability] Viewing a form in grid mode and expanding it shows all unhidden fields/autogenerated form

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2366]
https://user-images.githubusercontent.com/37256050/198908207-592320f5-d459-43fd-bf0e-ad4fd758f3cc.mov

Rather than limiting the view to the fields set in the subform view definition, it shows all unhidden fields.

This should expand to show the subform view definition already in the database unless I specify in the form config options to show the autogenerated form.

https://kufishnotests-testability.test.specifysystems.org/specify/view/collectionobject/26043/?recordsetid=97

https://kufishnotests-edge.test.specifysystems.org/specify/view/collectionobject/26043/?recordsetid=97

**Comment by chanulee1** [comment]
Grid mode of form displays as is defined in view definitions.
db: `kufishnotests`, `willemcatno`
