### ISSUE TITLE
[testability] Edit form definition button not routing correctly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2367]
**Steps to Recreate:**
1. Open the following URL: https://kufishnotests-testability.test.specifysystems.org/specify/view/agent/1097/ 
2. Click on the form configuration button :gear:
3. Click Form Definition
4. Click **Edit Form Definition**
5. See error

The URL generated after clicking **Edit Form Definition** in the form configuration. menu on the agent form:
`https://kufishnotests-testability.test.specifysystems.org/specify/resources/view-set/4/viewsets/4/`

Notice the `/view-set/4/viewsets/4/` section. It seems that this piece is being added twice.

**Comment by chanulee1** [comment]
Form definition routes correctly.
db: `kufishnotests`, `willemcatno`
