### ISSUE TITLE
New table icons for Specify 7

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2368]
Specify 7 still relies on the Specify 6 table icons that are stored at an extremely low resolution. Ideally, Specify 7 should store table icons in the front end for every table in better resolution.

**Comment by maxxxxxdlp** [comment]
Sp7 has the mechanism for generating icons on the fly. Probably could just improve it to use consistent colors for related tables

**Comment by maxxxxxdlp** [comment]
For future reference:
@grantfitzsimmons created sample svg icons. They are in https://drive.google.com/drive/u/2/folders/18arm41Hq5pZZYK3acD7Gu8FsNX3lXRu5

Can generate SVG for icons on the fly based on them

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-5-release-announcement/1023/1
