### ISSUE TITLE
Notifications are not being read

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2369]
https://user-images.githubusercontent.com/37256050/198910835-83ac0528-a173-4f9b-8054-b739285c6310.mov

Experiencing this on `edge` and `testability`

**Comment by maxxxxxdlp** [comment]
Broken since 7.7.0 because. Happened because of https://github.com/specify/specify7/commit/f72ea1c39c7383fc45fc578822a7e8fae67001ee. Happens only when there is more than one notification. Then, all but the oldest notification would remain unread

**Comment by chanulee1** [comment]
@maxxxxxdlp What is the expected behavior?

**Comment by grantfitzsimmons** [comment]
@chanulee1 Should be marked as read when you open the notifications. Notifications should still be present until dismissed.

**Comment by maxxxxxdlp** [comment]
> Notifications should still be present until dismissed

*unless two weeks has passed
** two weeks is the default time out after which notifications are auto removed. that time out can be changed in back-end config

**Comment by chanulee1** [comment]
@grantfitzsimmons So if a notification is "read", it is just missing the "now" status? Would these notifications be "read"?
<img alt="image" width="700px" src="https://user-images.githubusercontent.com/103299204/201820656-b1b47751-64f8-466f-945a-f6456228ed2d.png"/>

https://kufishnotests-testability-2.test.specifysystems.org/specify/

**Comment by maxxxxxdlp** [comment]
Unread notifications would have a blue dot next to the date when they were created.

A notification can be several days long and yet still be unread (if user didn't open the notifications menu yet)

To test this, you can always trigger a new notification (e.g, by exporting query results to csv)
