### ISSUE TITLE
WorkBench import limits number of columns that can be in spreadsheet

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#237]
We tried to import a spreadsheet with about 70 columns and after mapping the columns, when trying to actually import, an error popped up saying: "An unexpected error has occurred during communication with the server."  You can reload or go to the previous page.  The data set gets added to the list of data sets but when you open it, a blank page opens saying "500 internal server error"

**Comment by tlammer** [comment]
The error message:
DatabaseError at /api/workbench/rows/30/
(1116, 'Too many tables; MySQL can only use 61 tables in a join')

**Comment by tlammer** [comment]
I should mention, since it doesn't really get added, only kind of, you can't delete the data set.  You can't open it so the delete button never appears

**Comment by garrettgirard** [comment]
Verified using a dataset with over 60 columns/fields. Although it took a little while to import the spreadsheet, this was the intended effect, and no error was thrown.
