### ISSUE TITLE
[testability] Creating a DwCA export does not dismiss window

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2370]
https://user-images.githubusercontent.com/37256050/198910965-7bba3e3b-ab2c-4afb-a3e5-561368db19b9.mov

https://kufishnotests-testability.test.specifysystems.org/

macOS, Chrome

**Comment by grantfitzsimmons** [comment]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/37256050/198911168-7426511f-c183-4873-ba89-462ef5f1a388.png">

Lots of weird behavior with this. Some fail, some don't. Not sure what's happening.

**Comment by maxxxxxdlp** [comment]
What does the error message says for the failed ones? (click on the `Exception` button)

**Comment by grantfitzsimmons** [comment]
[download (1).txt](https://github.com/specify/specify7/files/9903912/download.1.txt)

**Comment by maxxxxxdlp** [comment]
@benanhalt 

```
"traceback":"Traceback (most recent call last):\n  File \"/opt/specify7/specifyweb/export/views.py\", line 133, in do_export\n    make_dwca(collection, user, definition, path, eml=eml)\n  File \"/opt/specify7/specifyweb/export/dwca.py\", line 197, in make_dwca\n    write_eml(eml, os.path.join(output_dir, 'eml.xml'))\n  File \"/opt/specify7/specifyweb/export/dwca.py\", line 247, in write_eml\n    for e in dataset.findall('pubDate'):\nAttributeError: 'NoneType' object has no attribute 'findall'\n"}
```

**Comment by benanhalt** [comment]
The exception seem to occur when you try and create a DwCA for a collection other than the one you're logged into. That's because the backend tries to get the resource based on the name and the logged in collection.

There is also the separate problem of the dialog not going away. Seems to be independent of whether the export works correctly.

**Comment by chanulee1** [comment]
DwCA dialog closes after creation.
db: `kufishnotest`, `willemcatno`
