### ISSUE TITLE
[testability] Carry forward carrying the determination relationship even when unselected

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2376]
https://user-images.githubusercontent.com/37256050/199105812-e95fad81-1e2c-4bb5-a25d-848b7567eeaa.mov

<img width="570" alt="image" src="https://user-images.githubusercontent.com/37256050/199105862-4a5cdd8a-7cf0-497e-b6d4-432e176bb688.png">

https://kufishnotests-testability.test.specifysystems.org/specify/view/collectionobject/61080/?recordsetid=97

macOS, Chrome

**Comment by chanulee1** [comment]
Other relationships carry forward even when unselected as well, such as "Col Obj Attribute" and "Collection Object Attachments".
https://kufishnotests-testability.test.specifysystems.org/specify/view/collectionobject/new/

**Comment by grantfitzsimmons** [comment]
Major issue- needs to be resolved before release.

**Comment by maxxxxxdlp** [comment]
Fixed. Turns out the issue was with case sensitivity: fields were in camel case in one place but in lower case in a different place. that's why it didn't affect one word fields like `determination`, but affected `collectionObjectAttr`

**Comment by chanulee1** [comment]
Carry forward appears to work as expected for regular fields and relationship fields as far as I can tell.
db: `kufishnotests`, `herbrbge`
