### ISSUE TITLE
Implement a "Create Accession" dialog

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#2377]
Similar to the one for "Create Loan" (or like creating accessions in sp6)

Suggested by @grantfitzsimmons

**Comment by grantfitzsimmons** [comment]
**Requested by:** UMich

**Comment by grantfitzsimmons** [comment]
You should be able to make an accession from a record set!

The current workflow is going to each collection object... one... by... one......

**Requested By:** RBGE

**Comment by grantfitzsimmons** [comment]
Discussed again in today's meeting

**Comment by CarolineDenis** [comment]
@grantfitzsimmons Any memory of what has been discussed during that meeting concerning this issue? 
Any point that we should be aware of?

**Comment by maxxxxxdlp** [comment]
@CarolineDenis

1. When creating a Loan, there is a dialog asking you to enter catalog numbers. The same dialog needs to be implemented for Accession.

2. Besides that, on the Loan form, when you click on the `+` button in the Loan Preparations subview, it opens a dialog prompting you to enter catalog numbers to link to the Loan. Similar should be implemented for Accessions - except that is blocked by #114

**Comment by grantfitzsimmons** [comment]
Exactly what @maxxxxxdlp said!

**Comment by grantfitzsimmons** [comment]
>Besides that, on the Loan form, when you click on the + button in the Loan Preparations subview, it opens a dialog prompting you to enter catalog numbers to link to the Loan. Similar should be implemented for Accessions - except that is blocked by https://github.com/specify/specify7/issues/114

Once #114 is fixed, this will be added.

**Comment by mcruz-umich** [comment]
Hi team! It looks like https://github.com/specify/specify7/issues/114 has been resolved, so now is this one unblocked to be worked on?
