### ISSUE TITLE
[testability] Spatial query with a lot of results ends up crashing Specify

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2378]
https://kufishnotests-testability.test.specifysystems.org/specify/view/collectionobject/26043/?recordsetid=97

Run this query and click **GeoMap** after it completes.

https://user-images.githubusercontent.com/37256050/199308077-9ac3a3d4-c2f9-4582-9115-3500686e4639.mp4

**Comment by maxxxxxdlp** [comment]
@benanhalt Can you add support on the back-end to provide the filter arguments to `/api/specify/<table>/` (like `id_in=`) using a body rather than query string?

Or should I split request into several requests? Or should I use the query builder endpoint instead?

**Comment by benanhalt** [comment]
It's generally considered a bad idea to use a body in a GET request. See for instance: https://stackoverflow.com/a/983458/1920273

What are you doing with the results?

**Comment by maxxxxxdlp** [comment]
I need to fetch a lot of localities by specific IDs.
Query Builder endpoint would work for this, but would require a bit of code rewriting. Don't know if it is easier to solve this on the front-end or back-end

**Comment by chanulee1** [comment]
How do I test this? Run a query with a lot of results?

**Comment by grantfitzsimmons** [comment]
@chanulee1 

Use GeoMap on a query with 1000+ results

**Comment by grantfitzsimmons** [comment]
I loaded over 8000 items and was able to have them plotted successfully- albeit my browser became incredibly slow and unresponsive.

**Comment by chanulee1** [comment]
Successfully plotted 10,188 items; my browser also became slow and unresponsive (about 10-15 mins to complete).

**Comment by maxxxxxdlp** [comment]
There is no theoretical limit anymore. In practice, depends heavily on the browser, hardware and even on the performance of the back-end.
In the documentation can mention that around 1k items can be plotted optimally.

The performance issues you are talking about would be resolved by this fix: https://github.com/specify/specify7/issues/1761
