### ISSUE TITLE
App Resource endpoint returns `None` for empty app resources

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#2379]
1. Create an empty app resource
2. Try to fetch it (https://kufishnotests-testability.test.specifysystems.org/context/app.resource?name=DefaultUserPreferences)
3. Returns `None`. Expected empty response

<img width="1800" alt="Screenshot 2022-11-01 at 13 35 17" src="https://user-images.githubusercontent.com/40512816/199311455-9c656dc3-7c92-4043-94d5-c337ce9b3186.png">

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp Still something to solve?

**Comment by maxxxxxdlp** [comment]
yes. it's a bug
but, it's an easy fix
would be worth going over other endpoints to see if they have a similar bug (i.e the view.sets endpoint, and /context/* endpoints)

**Comment by emenslin** [comment]
Fixed
