### ISSUE TITLE
Same field can be mapped repeatedly in the same mapping

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#238]
Collection Date gets automatically assigned to all date fields when spreadsheets are imported.  In one mapping (FishCollectioObjectOnlyOneDetermination), it was reused 4 times.  You should not be able to use the same field more than once.

**Comment by garrettgirard** [comment]
Verified using the same imported spreadsheet (FishCollectionObject...) and creating a new mapping. In the Workbench Template Mappings there are no longer fields (particularly date fields) being automatically mapped to multiple columns.
