### ISSUE TITLE
Scrolling in a UserPreference app resource brings the box with you

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2382]
https://user-images.githubusercontent.com/37256050/199319623-c0bab69b-3d8a-464c-893f-61bd2d3aa5c9.mov

<img width="305" alt="image" src="https://user-images.githubusercontent.com/37256050/199319690-b40ffbe3-b377-47a6-a701-9abb32fc98a8.png">

**Comment by chanulee1** [comment]
Box does not move while scrolling in User Preference app resources.
db: `willemcatno`, `kufishnotest`
