### ISSUE TITLE
Find and replace value erased after making a change

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2386]
https://user-images.githubusercontent.com/37256050/199336269-60460161-e8ac-4966-b139-15c8e11e68b1.mov

**Comment by maxxxxxdlp** [comment]
Seems to be a bug in the `react-codemirror` library. Opened an issue: https://github.com/uiwjs/react-codemirror/issues/404

**Comment by maxxxxxdlp** [comment]
a great and simple workaround has been suggested on the issue I opened - https://github.com/uiwjs/react-codemirror/issues/404#issuecomment-1809447795
