### ISSUE TITLE
WorkBench throws error when file name too long

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#239]
When you import a spreadsheet and the name is too long, after creating the mapping, Specify throws an error saying "An unexpected error has occurred during communication with the server".  the behind the scenes error is: 
Warning at /api/specify/workbench/
Data truncated for column 'Name' at row 1

I'm not sure what the character limit is.  Specify doesn't restrict how many characters can be entered.

**Comment by garrettgirard** [comment]
Verified. The error is no longer being thrown and the size of the dataset name is being limited and truncated.
