### ISSUE TITLE
Image Window support in Specify 7

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2390]
[Documentation for Image Window in Specify 6](https://discourse.specifysoftware.org/t/image-window/258)

> The Image Window in Specify 6 is an important feature that has not yet been made available in Specify 7. Having specimen and label images linked in Workbench enables transcription from the images.
> 
> We have tried using shared folders in file sharing utilities like Google Drive and Dropbox for hosting images for transcription. This works, but lacks many of the features that are supported in the Specify 6 Workbench. Record transcription into a spreadsheet lacks the data validation tools available in Workbench, increasing the probability of errors and the need for data quality control before uploading. The Image Window in Specify 6 conveniently and automatically moves between linked images when the user changes rows in the Workbench dataset. This is a really useful feature for label transcription, decreasing the probability of errors where users inadvertently enter data into an incorrect row. Transcription in temporary spreadsheets and shared folders outside of Specify requires also more coordination by transcriptionists and collection managers.

**Requested By:** [@gholman](https://discourse.specifysoftware.org/u/gholman/summary) on the [Specify Community Forum](https://discourse.specifysoftware.org/t/support-image-window-in-specify-7-workbench/839)

on behalf of the University of Michigan

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/support-image-window-in-specify-7-workbench/839/2

**Comment by maxxxxxdlp** [comment]
Related to #764

**Comment by grantfitzsimmons** [comment]
Duplicate of https://github.com/specify/specify7/issues/764
