### ISSUE TITLE
Creating an app resource under a user does not populate the sidebar

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2392]
When I am creating a new view set resource under `abentley` under the `KU Fish Voucher Collection` in the `KU_FISH_NO_TESTS` database, I am encountering an issue with the fact that the resource does not seem to be listed at all in the sidebar. It exists at the database level, but I am similarly not seeing the view definition applied

<img width="829" alt="Screenshot 2022-11-03 at 8 00 16 AM" src="https://user-images.githubusercontent.com/37256050/199726995-a4c457cf-51f7-488f-837d-1621c53b0011.png">

https://kufishnotests-testability.test.specifysystems.org/specify/resources/view-set/10/

**Comment by grantfitzsimmons** [comment]
To add to this-

!! View sets do not appear **at all** under users. !!

**Comment by chanulee1** [comment]
View set does not seem to appear under user in sidebar. Created view set "Test" under `abentley`.
![image](https://user-images.githubusercontent.com/103299204/202038399-c72b9fbe-0320-4208-8428-c7d2103ad001.png)
https://kufishnotests-testability.test.specifysystems.org/specify/resources/view-set/15/

**Comment by maxxxxxdlp** [comment]
Fixed. The bug affected resources created for Users and User Types in cases when there are multiple collections (it was saving them to the correct user, but in a wrong collection)

**Comment by chanulee1** [comment]
Creating an app resource populates sidebar in correct directory.
db: `kufishnotests`, `willemcatno`
