### ISSUE TITLE
Carry forward not cloning cataloger correctly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2397]
https://user-images.githubusercontent.com/37256050/199817974-25455785-2cf4-488e-b2e0-6d2c1b2c5a8b.mov

The current user is overriding this carry over behavior

https://kufishnotests-testability.test.specifysystems.org/specify/view/collectionobject/new/?recordsetid=97

**Comment by maxxxxxdlp** [comment]
Fixed. This also affected `LoanReturnPreparation.receivedBy`

**Comment by chanulee1** [comment]
@maxxxxxdlp Carry over for cataloger seems to work. How do I test the field in LoanReturnPreparation since carry-over can't be used on loan forms?

**Comment by maxxxxxdlp** [comment]
You could open any blank form, and then replace the table name in the url with `LoanReturnPreparation`. Then save the record, and that way you get the "Add" button.

**Comment by chanulee1** [comment]
Carry over for LoanReturnPreparation.receivedBy works.
db: `kufishnotests`
