### ISSUE TITLE
Swagger "try it" function broken.  

### ISSUE THREAD

**Issue by benritchie** [specify/specify7#2399]
Hey Folks

I’ve just been trying to write a simple API to specify.  

To start out, I thought I’d try to use the embedded swagger API docs, which include a really handy “try it out” function to try out the different API endpoints.  Ufortunately, it looks like these don’t actually work.  – maybe some mis-configuration in the swagger setup?

What I did was select the “POST” operation on the permits table, hit the try it out button, and left parameters at defaults.  (wasn’t expecting this to work fully – would expect to need to tweak a parameters, but was expecting it to at least pass authorization.  

What happened instead was I got a 403 – details below.  - key line is "<p>CSRF verification failed. Request aborted.</p>"

Is the swagger try it function meant to work?  
Thanks.  

![image](https://user-images.githubusercontent.com/8005676/200019208-52ddfc56-2a22-4fe3-9a36-f5c1ebb1e345.png)

seen on RBGE sandboc hosted instance, running 7.7.5

**Comment by benritchie** [comment]
Interesting
I've tried a few more.  
* Get's consistently work.  
* POST's consistently fail (e.g. for CollectionObject also)
I'm using Edge.  

I'm signed in as a institution admin, using SSO.  

Thanks.

**Comment by maxxxxxdlp** [comment]
Thanks for the additional information.
I was able to reproduce the issue.
The error happens because non-GET requests require an additional header to be set (`X-CSRFToken`, with the value taken from the "csrftoken" cookie), which the swagger UI page does not do.

There are several ways to modify the swagger page to send the header - https://stackoverflow.com/questions/41180615/how-to-send-custom-headers-with-requests-in-swagger-ui

Needs research to determine the best way to fix this

**Comment by cdamyx** [comment]
Hi All!

I've been banging my head on the wall on this issue for a few days, so I figured I'd reach out. Based on [posts like this](https://stackoverflow.com/questions/61956227/csrf-support-in-springdoc-openapi-swagger-ui), I thought that something like the below would work (although, there may be some reason you don't want to manually grab the CSRF token...)

```
<script>
      SwaggerUIBundle({
        url: "{{ open_api_schema_endpoint }}",
        dom_id: "#swagger-ui",
        requestInterceptor: (req) => {
          req.headers['X-CSRFToken'] = {{csrf_token}};
          return req;
        }
      });
</script>
```

However, when I have that code in swagger-ui.html and I try to navigate to localhost/documentation/api/tables/ I receive an error that the token is not defined in /api/specify_schema/openapi.json. Any suggestions on what I could try, or should I not be using this manual method in the first place?

**Comment by maxxxxxdlp** [comment]
That looks like a good solution. One small change:

Since `{{csrf_token}}` resolves to a value like `8oGgUyhzcaus1mFMUtAzvgRA5dFPDf5xc5IZlqINUaUb2ICdooA9R6Aq6dvbdSq0`, you need to enclose it in quotes for it to be valid JavaScript.

Replacing `{{csrf_token}}` with `'{{csrf_token}}'` should do it

**Comment by cdamyx** [comment]
@maxxxxxdlp I forgot to say thanks for the assist here. Thanks!
