### ISSUE TITLE
New Validation Error in KU Birds db

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#240]
For some reason validations stopped working in the workbench in the KU Birds database. They all fail and in the details it says "No X11 DISPLAY variable was set, but this program performed an operation which requires it." near the bottom. This might not be a bug, but it's keeping me from doing much else in workbench at the time in this database at least. I'm not sure what may have changed to cause this, but the database wasn't having these issues before.

**Comment by benanhalt** [comment]
I think it is because I was connected to that database with Specify 6 and had the uploader open.

**Comment by garrettgirard** [comment]
Yeah that seems to have been the problem.
