### ISSUE TITLE
You can save a user preferences resource with no JSON value

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2401]
<img width="1703" alt="image" src="https://user-images.githubusercontent.com/37256050/200035666-3a08d846-4795-4eab-9c4c-70a01b42f4a0.png">

If you make no changes to a user preferences file and save, you will end up with a blank JSON file. This leads to errors in Specify:

<img width="477" alt="image" src="https://user-images.githubusercontent.com/37256050/200035781-e0b1b3c4-bfbf-41d5-bfe9-b7fdbfd91f20.png">

**Comment by maxxxxxdlp** [comment]
This error has been fixed somewhere between 7.8.0 and 7.8.4. Empty user preferences resources are now handled without an error
