### ISSUE TITLE
Column headers are opaque in grid view

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2402]
<img width="513" alt="image" src="https://user-images.githubusercontent.com/37256050/200040335-a3056505-c0ca-4390-85bd-62c582b1030a.png">

https://eawagfishec-edge.test.specifysystems.org/specify/view/collectingevent/132/

**Comment by maxxxxxdlp** [comment]
This is needed because headers are sticky and you don't want to see content behind them when scrolling

The only way to fix this is to disable form gradient.

I will close this as a wontfix since it's not very important, yet hard to fix
