### ISSUE TITLE
Full Name Direction missing on the form for tree definitions

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2403]
<img width="1982" alt="image" src="https://user-images.githubusercontent.com/37256050/200041887-b3704609-c3e8-473d-9114-57695a33c765.png">

I am not sure if this was an intentional decision because it introduced issues or was non functional.

**Comment by grantfitzsimmons** [comment]
<img width="1692" alt="image" src="https://user-images.githubusercontent.com/37256050/200042383-ef606fa7-3278-4d41-b608-fad47c73a0db.png">

https://eawagfishec-testability.test.specifysystems.org/specify/view/taxontreedef/1/

https://eawagfishec-edge.test.specifysystems.org/specify/view/taxontreedef/1/

**Comment by maxxxxxdlp** [comment]
This was an intentional change in 2162e3215

Changing full name generation rules would require regenerating existing full names, which Specify 7 does not do yet.

This will be fixed by https://github.com/specify/specify7/issues/598
