### ISSUE TITLE
Mail button missing in Authors

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2404]
<img width="2160" alt="image" src="https://user-images.githubusercontent.com/37256050/200042757-42018db1-79e4-4da5-aa7a-d590c0694562.png">

Left: `edge`
Right: `testability`

https://eawagfishec-edge.test.specifysystems.org/specify/view/referencework/24/
https://eawagfishec-testability.test.specifysystems.org/specify/view/referencework/24/

**Comment by maxxxxxdlp** [comment]
The `MailTo` weblink used by that button does not exist in their database:

![Screenshot 2022-11-15 at 10 17 45](https://user-images.githubusercontent.com/40512816/201970899-26e201cf-f3c4-4d03-805f-9564f52fbadf.png)

On edge, it would render the weblink anyway, but the link would just link back to current page - which is useless.
On testability, it doesn't render the link, and logs in the console that it is unable to find weblink definition
