### ISSUE TITLE
When choosing a base table, the dialog for no upload plan does not disappear

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2407]
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/37256050/200049665-884a8ca0-4c7a-4a7d-8330-e8d2c687894a.png">

left `edge`, right `testability`

https://willemcatno-testability.test.specifysystems.org/specify/workbench/plan/129/

**Comment by melton-jason** [comment]
Seems fixed as of e113949
