### ISSUE TITLE
"Next" Invalid Cell Button doesn't always work quite right

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#241]
In the Test Taxon only in INVP2 spreadsheet, when you import it as a dataset into workbench it will have some invalid cells. When you validate it the invalid cells will be highlighted, and from there you can click the "next" button to go straight to the next invalid cell. However, when you do this, the cell is just barely visible at the bottom of the screen. This is mostly just annoying as you can't see what's in the cell until you scroll down a bit. This doesn't happen with every dataset, but it appears to be an issue with some, including this one. This spreadsheet can be found under Y:\Specify6\Tester Documentation\Specify 7 Testing Data\Spreadsheets.

**Comment by benanhalt** [comment]
Let's see if anyone complains about this.

**Comment by maxxxxxdlp** [comment]
Fixed in 7.6.00
