### ISSUE TITLE
Table names not displaying on the form header

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2410]
<img width="1874" alt="image" src="https://user-images.githubusercontent.com/37256050/200052610-a5ff2a56-4b26-4631-a052-d406cb317efb.png">

It is enabled in the user preferences but only the icon is displaying. This seems to be restricted to this database.

https://willemcatno-testability.test.specifysystems.org/specify/view/geography/new/

macOS, Chrome

**Comment by maxxxxxdlp** [comment]
I thought this was a bug, but then I realized that user preferences are just confusing.

The "Include table name in the page title" preference refers to including table name in browser tab title

To include table name, you have to set "Form header format" to `Table Name` or `Icon and Table Name`

![Screenshot 2022-11-18 at 14 39 03](https://user-images.githubusercontent.com/40512816/202798264-82b93c3f-2132-4373-808a-6c707bca9f3a.png)

I will improve the pref label to `Include table name in the browser page title` to make it less ambiguous

**Comment by chanulee1** [comment]
Preference label less ambiguous.
