### ISSUE TITLE
Form repeadedly believes it is edited after a change

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2415]
https://user-images.githubusercontent.com/37256050/200190150-ccb6b264-08bd-4bb5-9937-b2be114fefa4.mp4

**Steps to Recreate:**

1. Run a query on the CO table
2. Open a record in the form view
3. Make a change to a field
4. Click save
5. See that you can save infinitely

Not reproducible on `edge`. user is `peteniel`

https://gothenberg-testability.test.specifysystems.org/specify/query/1/

browser: chrome on macOS

**Comment by maxxxxxdlp** [comment]
Caused by a bug where the date picker overwrites a read-only field (timestamp modified). It overwrites it because back-end saves date in a different format than the front-end

To test: check that the bug does not happen anymore in this particular case

**Comment by chanulee1** [comment]
Seems to have been fixed.
db: `gothenberg`, `kufishnotests`
