### ISSUE TITLE
Make user tools menu accessible for anonymous users

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2418]
User tools has a "Documentation" and "Development" sections that would be useful even for anonymous users (especially if they are no affiliated with the institution whose collection they are accessing and want to learn more about Specify 7)

The permission system will hide access to all tools that are not appropriate for an anonymous user (data export, editing schema/permissions)

**Comment by grantfitzsimmons** [comment]
Might be worth considering separating user tools from the user name
