### ISSUE TITLE
On the "show interactions" dialog, table names should be localised

### ISSUE THREAD

**Issue by benritchie** [specify/specify7#2420]
Show interactions dialog currently uses the system table names.  It should use localised names.  

This is an issue for institutes that have renamed their tables, e.g. to use them for a slightly ifferent purpose (e.g. at RBGE we use the gift table to track destructive sampling.  )

screenshot showing non localised names - the Gift table is localised in our DB:
![image](https://user-images.githubusercontent.com/8005676/200550309-d3f79ecb-2dc8-42f9-81cb-4ab79d993fdd.png)

**Comment by benritchie** [comment]
umm.  I think its better to have the correct label (e.g. localised) even if the grammar is slightly off, rather than write the wrong thing in the correct grammar...
- so my vote would be to fix this, (and any other instances where a similar thing has been done) even if that means we have to make the grammer slightly odd / have singulars where plurals should be.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-4-announcement/999/1

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-5-release-announcement/1023/1
