### ISSUE TITLE
"Show interactions" - exchanges stuck on loading...

### ISSUE THREAD

**Issue by benritchie** [specify/specify7#2421]
When I open a collection object and click show interactions, in some cases (not all) Exhanges is stuck on "loading..."
Screenshot below:
![image](https://user-images.githubusercontent.com/8005676/200550660-0bc5057a-d89d-4274-b777-0cd7c2569860.png)

This Preparation has (AFAIK) 1 interaction associated with it - a (closed) Gift.  Exchanges is stuck on loading for some reason.  
Feel free to take a look if oyu'd like - its RBGE hosted DB, here's the link: https://herb-rbge.specifycloud.org/specify/view/collectionobject/677859/ and its the second prep in the CO (Barcode 1711:32)

Thanks.

**Comment by maxxxxxdlp** [comment]
Will be fixed in 7.8 (e42b7b0e3)
