### ISSUE TITLE
Plot all query results

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2424]
#1714 added ability to plot query results. However, only results that have been fetched so far would be plotted.
#2253 added a way to see how many have been fetched.
The next step is to make the map incrementally fetch more records until it plotted all of them

**Comment by melton-jason** [comment]
Results are now fetched incrementally when GeoMapping query results

For an example, see:

https://user-images.githubusercontent.com/64045831/203840619-f9ebaac1-6092-41e7-9eed-9409a8bd75e3.mp4
