### ISSUE TITLE
Autofil the Record set name using query name

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2426]
Autofil the Record set name using query name when when creating a record set from query results
Currently, it just shows an empty field requiring user to type the name in manually

**Comment by chanulee1** [comment]
@melton-jason Is this expected behavior? When select a few records from query results to create record set, does not autofill.

https://user-images.githubusercontent.com/103299204/204706639-9556da2b-790d-4aa2-b6f6-3cac4f64ebbe.mp4

**Comment by maxxxxxdlp** [comment]
It's a bug

**Comment by chanulee1** [comment]
Is this fix ready to test? It appears to be working.
Tested: `willemcatno`

**Comment by maxxxxxdlp** [comment]
Yup. This should be fixed now.
Since it's working for you, I will close this as comleted
