### ISSUE TITLE
Modified By date not displaying on the form

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2428]
![image](https://user-images.githubusercontent.com/37256050/201134960-87cf757a-c777-4609-a3c1-ffd4e4a100c8.png)

left: `testability`
right: `edge`

https://umich-testability.test.specifysystems.org/specify/view/collectionobject/579/
https://umich-edge.test.specifysystems.org/specify/view/collectionobject/579/

**Comment by grantfitzsimmons** [comment]
<img width="2508" alt="image" src="https://user-images.githubusercontent.com/37256050/201966492-b8f070c6-479f-4086-b2a0-448de0e19f20.png">

Still an issue

**Comment by melton-jason** [comment]
I'm pretty sure this is the same underlying issue as #2438. I will close this in favor of #2438 as #2438 covers more use cases.
Reopen if the issue turns out to be separate
