### ISSUE TITLE
Preferences need to be uniquely identified by name

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2430]
<img width="309" alt="image" src="https://user-images.githubusercontent.com/37256050/201185622-cbc5a79f-0e8a-461d-ac96-010a22a55e16.png">

I know we have discussed this several times before, but I could not find an issue for this.

**Requested By:** @acbentley and myself

_Even if a UI is on the way, can this be resolved sooner? It is impossible to tell the difference until they are opened._

**Comment by maxxxxxdlp** [comment]
Looks like those app resources can be discriminated between using the `SpAppResourceDir.userType`field

![Screenshot 2022-11-10 at 13 44 12](https://user-images.githubusercontent.com/40512816/201191272-ff2a8062-c290-4fc2-baaf-cb976b58ecf4.png)
![Screenshot 2022-11-10 at 13 44 17](https://user-images.githubusercontent.com/40512816/201191273-24af7c92-1f13-47b8-b16f-d93c5062c5df.png)

**Comment by maxxxxxdlp** [comment]
Fixed:

<img width="1800" alt="Screenshot 2023-01-03 at 11 10 51" src="https://user-images.githubusercontent.com/40512816/210406342-44f9ec93-10fe-44a3-8e7d-ed2cddd640e2.png">
