### ISSUE TITLE
Save button enabled without any changes made in schema config

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2434]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/37256050/201424424-9810867b-8e37-4481-9e4b-5bd5f7cb5958.png">

`testability`

https://freshfish-testability.test.specifysystems.org/specify/schema-config/en/Workbench/

**Comment by maxxxxxdlp** [comment]
Wrong screenshot?
Is this also reproducable on edge?

**Comment by grantfitzsimmons** [comment]
not reproducable on `edge`.

**Comment by maxxxxxdlp** [comment]
Unable to reproduce (link: https://freshfish-testability.test.specifysystems.org/specify/schema-config/en/Workbench/)

![Screenshot 2022-11-22 at 10 50 47](https://user-images.githubusercontent.com/40512816/203373602-a8600782-5206-4e9e-a03b-b94808bcd186.png)

Tried in KU_FISH_NO_TESTS too.
Tried other tables too.

Did this happen for other tables or just this one?
Are you able to reproduce this again?
Are there any errors in the console?

**Comment by grantfitzsimmons** [comment]
I was able to recreate this across a couple of databases and multiple tables at the time. I can't recreate across several deployments, so I will close this unless I or someone discover it to be a problem again.
