### ISSUE TITLE
BorrowMaterial table text1 field description is Текст1

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2435]
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/37256050/201426628-0689c4be-dce9-47d0-8f65-f4b86f5447e4.png">

`Текст1` should be `Text1`.

**Comment by maxxxxxdlp** [comment]
Which database is this in?

**Comment by maxxxxxdlp** [comment]
Replicated in freshfish

**Comment by grantfitzsimmons** [comment]
Will open if I can find the database
