### ISSUE TITLE
Importing query causes TypeError

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2436]
When trying to import the following query in `testability` I get an error:

[Collection Object using _Non-vascular Land Plants_.json.zip](https://github.com/specify/specify7/files/9993088/Collection.Object.using._Non-vascular.Land.Plants_.json.zip)

<img width="1202" alt="Screenshot 2022-11-11 at 2 37 38 PM" src="https://user-images.githubusercontent.com/37256050/201427273-5b92f093-b6a4-42a5-9c95-107c855cc651.png">

[Specify 7 Crash Report - 2022-11-11T20_37_40.859Z.txt](https://github.com/specify/specify7/files/9993093/Specify.7.Crash.Report.-.2022-11-11T20_37_40.859Z.txt)

In `edge` it imports and auto-increments the (x) correctly.

```
TypeError at /api/specify/spquery/
int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

https://unitecnov22-testability.test.specifysystems.org/specify/overlay/queries/new/

user: `spadmin`

**Comment by chanulee1** [comment]
Query import works.
db: `unitecnov22`
