### ISSUE TITLE
[testability] CO form subviews automatically populated with data

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2437]
**Describe the bug**
"Field No: Locality", "Collecting Event Attribute", "Collectors", "Collection Objects" subviews on the CO form are automatically populated with data after saving in the `kufishnotests` database, `KU Fish Voucher Collection` collection. Occurs when saving both new COs and clones.

https://kufishnotests-testability.test.specifysystems.org/specify/view/collectionobject/new/
Before save:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/103299204/201427069-d953fa33-7131-42b0-8d5b-1afdd25406fb.png"/>

After save:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/103299204/201427242-2e66f1a2-4108-4584-91f1-bb147694ff5d.png">

**Comment by chanulee1** [comment]
Unable to add collecting event before saving; it is automatically populated after save.

**Comment by chanulee1** [comment]
Related? Also get error when trying to save a CO record without an associated "collection" record. "Collection" seems to be a required field in the CO record. Not sure how to change its required state.

<img alt="image" width="700px" src="https://user-images.githubusercontent.com/103299204/201833144-95555a4a-fc84-46c1-b728-eadfe5a621b6.png"/>

[Specify 7 Crash Report - 2022-11-15T05_11_58.796Z.txt](https://github.com/specify/specify7/files/10009550/Specify.7.Crash.Report.-.2022-11-15T05_11_58.796Z.txt)

https://kufishnotests-testability-2.test.specifysystems.org/specify/view/collectionobject/new/?recordsetid=44

**Comment by chanulee1** [comment]
`collection` field in CO table is marked as required in `testability`, and not in `edge`. Same for `discipline` field in CE table. Results in error messages when trying to save records without these fields. 

`edge`:
<img alt="image" width="700px" src="https://user-images.githubusercontent.com/103299204/202000194-2069d742-6672-4ea2-823d-83cac00a89dd.png"/>

`testability`:
<img alt="image" width="700px" src="https://user-images.githubusercontent.com/103299204/202000577-d8325890-5b2e-46e1-ace6-9334ee33f752.png"/>

`edge`:
<img alt="image" width="700px" src="https://user-images.githubusercontent.com/103299204/202000805-02f84076-0715-42b6-88c4-acd87da8e984.png"/>

`testability`:
<img alt="image" width="700px" src="https://user-images.githubusercontent.com/103299204/202000922-688b5f41-f14b-465c-8651-600ed1fccbcf.png"/>

**Comment by maxxxxxdlp** [comment]
Fixed.
Please do general testing of subviews for different tables as part of testing this, as fixing this bug required changing critical code

**Comment by melton-jason** [comment]
@maxxxxxdlp It seems like https://github.com/specify/specify7/commit/e76cbe61a83e8b8d728d8363ea694081627dcac8 may have caused #2488. 
I can not immediately find other cases besides Collecting Event on Collection Object form where this occurs, but it _does_ only happen when Collecting Event is a subview. Query Combo Boxes behave as normal.

**Comment by maxxxxxdlp** [comment]
@melton-jason no, they appear to be unrelated. For more info, see https://github.com/specify/specify7/issues/2488#issuecomment-1327745504

**Comment by melton-jason** [comment]
@maxxxxxdlp  Yes, I saw that! Thank you for the clarification. I will of course use another database in addition for testing to hopefully avoid any such confusion again. (I have seen too much KU and willemcatno anyways. Need to spread the love to some other databases)

**Comment by melton-jason** [comment]
Seems fixed! Tested in `KUFishNoTests`,  `willemcatno`, and on a local instance of Specify 7.
