### ISSUE TITLE
[testability] Date fields do not show date in Read-Only Mode

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2438]
**Describe the bug**
Date fields do not display their values when a form is in Read-Only Mode.

https://kufishnotests-testability.test.specifysystems.org/specify/view/collectionobject/6/?recordsetid=44
Original:
<img width="700" height="700" alt="image" src="https://user-images.githubusercontent.com/103299204/201430981-ae8b2e92-1813-4947-b87d-8062361b5968.png">

Read-Only Mode:
<img width="700" height="700" alt="image" src="https://user-images.githubusercontent.com/103299204/201431112-2058b511-ca25-42b3-8ee3-e4febef12d97.png">

Subview also not displaying date correctly:

CE subview on CO form:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/103299204/201431459-d8c60dee-1c3b-46a1-ae89-02844704bfe8.png">

CE form:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/103299204/201431619-236c99db-4443-49a6-a7e3-8be59b609ec9.png">

**Comment by maxxxxxdlp** [comment]
When testing this fix, please also test https://github.com/specify/specify7/issues/2415

**Comment by melton-jason** [comment]
See https://github.com/specify/specify7/pull/2478#pullrequestreview-1190865279 for resolution
