### ISSUE TITLE
[testability] Query Builder page is blank

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2445]
`kufishnotests`:
<img alt="image" width="700px" src="https://user-images.githubusercontent.com/103299204/201819887-5e28ac6f-df27-44a9-867e-a07005452240.png"/>

https://kufishnotests-testability-2.test.specifysystems.org/specify/query/new/collectionobject/

`willemcatno`:
<img alt="image" width="700px" src="https://user-images.githubusercontent.com/103299204/201820066-13676591-a0a2-495a-8aab-44b973b611d3.png"/>

https://willemcatno-testability.test.specifysystems.org/specify/query/new/collectionobject/

**Comment by maxxxxxdlp** [comment]
Temporary fix: click on the `Show Map Explorer` button

@melton-jason Looks like a bug in the recent code that was added. You need to set map explorer to be visible by default, when no local storage state is set (you can do that by either clearing your local storage or opening specify in an incognito browser tab)

**Comment by grantfitzsimmons** [comment]
Looks good to me since Jason pushed https://github.com/specify/specify7/commit/70257c6b3fffc0dfa1e260903f6a89522762f9d6
