### ISSUE TITLE
Allow collection object records to not have catalog numbers

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2448]
There are use cases where this is necessary.

Somewhat releated to the carry forward behavior

**Requested By:** @acbentley as well as other collections who have CO records without catalog numbers

**Comment by maxxxxxdlp** [comment]
This is strange. I am sure I have seen the "Duplicate catalog number" error when I try to create a second co with blank catalog number, but I am unable to replicate it again.
Maybe it is dependent on the formatter. I will reopen this if manage to get error to happen again
