### ISSUE TITLE
Carry forward should not allow customizing independent relationships

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2450]
Carry forward should not allow customizing independent relationships

Such as Accession

**Comment by maxxxxxdlp** [comment]
Fixed in 37b1b4d86

**Comment by chanulee1** [comment]
Independent relationships are not customizable, as far as I can tell.
db: `freshfish`

**Comment by grantfitzsimmons** [comment]
I can verify this has been fixed
