### ISSUE TITLE
Move Enabled Read-Only Mode to User Tools

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2452]
It is confusing in the form definition

**Comment by maxxxxxdlp** [comment]
How about this:
The button still remain in the Form Meta menu, but if read only menu is enabled, this big blue button appears in the user tools menu:

<img width="1800" alt="Screenshot 2022-11-15 at 20 17 05" src="https://user-images.githubusercontent.com/40512816/202067321-aab1d18f-2ac8-4e0a-8aab-d559f60b4fc0.png">

This way it is easy to find this option, even if you didn't know it is there

**Comment by melton-jason** [comment]
Does there need to be a discussion about this (or has there been already)? 

I am happy with Max's fix: it is intuitive to also include the option to disable Read-Only Mode in User Tools. There are no apparent issues after testing.  

I will go ahead and close this issue. If someone disagrees, feel free to reopen.
