### ISSUE TITLE
Pick lists in the "History of edits" dialog not appearing correctly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2455]
<img width="991" alt="image" src="https://user-images.githubusercontent.com/37256050/202013908-4ad230f5-f7f4-4d35-8b18-e19a5e9f3840.png">

See that the arrows are not indiciating these are pick lists

**Comment by chanulee1** [comment]
<img alt="image" width="600px" src="https://user-images.githubusercontent.com/103299204/202249736-57216f75-485c-47a8-a328-882efc8567d8.png"/>

db: `freshfish`
https://freshfish-testability.test.specifysystems.org/specify/view/collectionobject/6847/

**Comment by maxxxxxdlp** [comment]
I believe the test panel just hasn't updated yet. To trigger an updated, need to a change to any deployment (or make a change to this particular deployment and then revert back the configuration change). This is needed until the test panel bug is fixed
