### ISSUE TITLE
Rename actions in the audit log pick list

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2456]
![image](https://user-images.githubusercontent.com/37256050/202014052-e3318462-4df1-41ad-8929-438cf708b0b5.png)

**Comment by grantfitzsimmons** [comment]
@beach53 Please reply with the improved names for these actions

- Insert
- Update
- Delete
- Tree Merge
- Tree Move
- Tree Synonymize
- Tree Unsynonymize

**Comment by grantfitzsimmons** [comment]
@acbentley:

**Insert** should become **Create**

**Comment by chanulee1** [comment]
"Insert" renamed to "Create" in audit log pick list.

**Comment by melton-jason** [comment]
Unsynonimize action now called 'Tree Desynonymize' in SpAuditLog table.
Reopen if another action needs renaming
