### ISSUE TITLE
Change Audit Log query results order

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2457]
Move Timestamp, Parent Record ID, Parent Table Num to the right side of the query

Move Old Value, New Value, and Field Name to the 3rd or 4th column instead

**Comment by grantfitzsimmons** [comment]
Remove Parent Record ID, Parent Table Num entirely to improve performance

**Comment by maxxxxxdlp** [comment]
Fixed in 20b0eac47, e063f89c7, e0e36525a

**Comment by melton-jason** [comment]
An example History of edits for a Collection Object:

![issue_2457](https://user-images.githubusercontent.com/64045831/204056127-c6831b4b-87cd-476b-aed1-7af745914977.png)
