### ISSUE TITLE
History of edits seems to load records continously

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2458]
Observed in Max's demo today, just a note. Dialog slowed dramatically as it remained open when returning tens of thousands of records

**Comment by chanulee1** [comment]
How to test?

**Comment by maxxxxxdlp** [comment]
Click on the search button next to any query combo box
In the dialog, click on "Query Builder"
Make sure the query returns more than 80 records. If it doesn't, use a different query combo box
Take a look at the scroll bar in the results table. The scroll bar should not be continuously shrinking if you are not scrolling. Another way to check this is to open the "Network" tab in the browser's DevTools panel, and make sure the are no requests sent to `/stored_query/ephemeral` while you are not scrolling and not doing anythin.

**Comment by chanulee1** [comment]
Fixed!
db: `freshfish`
