### ISSUE TITLE
Too many buttons 

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2461]
<img width="1920" alt="Screenshot 2022-11-15 at 2 54 01 PM" src="https://user-images.githubusercontent.com/37256050/202025743-2724929a-5b62-4323-923d-8299935ad6ee.png">

There are a lot of blue buttons. There should probably be some reduction in these, per the meeting

**Comment by maxxxxxdlp** [comment]
Fixed by making the filter buttons at the top less prominent when a given category is filtered out
