### ISSUE TITLE
App resources/form definitions should be sorted by type, then alphabetically

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2462]
<img width="887" alt="Screenshot 2022-11-15 at 2 42 24 PM" src="https://user-images.githubusercontent.com/37256050/202025931-56b0affc-bdd8-43cf-adc0-772500df8e35.png">

@beach53 believes there should also be headings that indicate which kind of resource each group is. This would clarify the currently confusing app resource viewer.

**Comment by maxxxxxdlp** [comment]
Headings would add too much visual clutter, but I can add a tooltip telling you the resource type, when you hover of the icon
