### ISSUE TITLE
Links should go to the collection object record, not the locality

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2464]
<img width="482" alt="Screenshot 2022-11-15 at 2 30 07 PM" src="https://user-images.githubusercontent.com/37256050/202026231-eaebda74-df37-4ec1-8597-05fc1cc86d08.png">

In the GeoMap spatial query viewer when querying on collection objects

**Comment by maxxxxxdlp** [comment]
Fixed, the link now goes to whatever is the base table.
Also, fixe the new tab indicator not being on the same line as the link
