### ISSUE TITLE
Polygon artifacts visible in GeoMap after plotting query results

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2465]
<img width="674" alt="Screenshot 2022-11-15 at 2 24 42 PM" src="https://user-images.githubusercontent.com/37256050/202026481-96e71f0f-a804-4f5b-9797-c8ab30bca1ab.png">

![image](https://user-images.githubusercontent.com/37256050/202026642-725e56f5-6135-4ee0-a2f6-f2196661e36e.png)

https://freshfish-testability.test.specifysystems.org/specify/query/130/

Blue lines are being shown (potentially artifacts) when polygons are shown. Can recreate using the above query.

**Comment by maxxxxxdlp** [comment]
That's data quality issues that the map helps expose:

![Screenshot 2022-11-16 at 14 31 03](https://user-images.githubusercontent.com/40512816/202287801-15f7ffd9-d706-4937-af2b-28839439ec29.png)

**Comment by grantfitzsimmons** [comment]
How do I discover that from this presentation?

**Comment by maxxxxxdlp** [comment]
Click on any of the "artifacts" and then "View Record"
