### ISSUE TITLE
Cannot see the state of the app resources or form definitions button clearly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2466]
<img width="1098" alt="Screenshot 2022-11-15 at 2 32 33 PM" src="https://user-images.githubusercontent.com/37256050/202026813-2d41985f-f169-4c95-93ea-9ecba2fb550f.png">

Once selected/deslected, the shade of blue is only marginally different. For us color blind, it is difficult to see the difference.

**Comment by maxxxxxdlp** [comment]
Fixed in c22968e75

**Comment by melton-jason** [comment]
From https://github.com/specify/specify7/issues/2467#issuecomment-1326575248 

> App resource and view definition buttons can now easily be distinguished between enabled/disabled modes
