### ISSUE TITLE
Remove the app resources and view definitions buttons

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2467]
<img width="1098" alt="Screenshot 2022-11-15 at 2 32 33 PM" src="https://user-images.githubusercontent.com/37256050/202026918-e1735f71-a81c-421e-98f1-e1568bab2b37.png">

_Let it be known that I disagree. I believe that these buttons should just be made less prominent (maybe only show the icon?)_

**Requested By:** @acbentley and @tlammer

**Comment by melton-jason** [comment]
App resource and view definition buttons can now easily be distinguished between enabled/disabled modes
