### ISSUE TITLE
Form Definitions and App Resources buttons should automatically hide the other

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2468]
_Assuming you ignore/dismiss https://github.com/specify/specify7/issues/2467_...

I would prefer that these buttons automatically were made visible when pressed and hid the other type (form def or app resource) entirely.

**Comment by melton-jason** [comment]
Solved by not hiding the buttons and rather changing color when enabled/disabled. 
Additionally see related issue #2466. 

An example of implementation:

https://user-images.githubusercontent.com/64045831/204057890-e5d6f32b-2464-4203-8b73-93311bb6c981.mp4
