### ISSUE TITLE
Won't validate in Sp7 after Sp6 upload

### ISSUE THREAD

**Issue by Oleniacz** [specify/specify7#247]
I validated the dataset. It passed. Then Garrett uploads a dataset in Sp6 in the same collection. I am unable to validate while the dataset is uploading. After uploading in Sp6 is complete, I try to revalidate as is, or make small changes and then save and revalidate. It fails. The following is the given details after validation fails: 

pid = 8920
2016-03-25T20:16:28Z: Validating only. Will not commit.
2016-03-25T20:16:28Z: starting with args [Suppressed]...
2016-03-25T20:16:29Z: Got master
2016-03-25T20:16:29Z: logged in
2016-03-25T20:16:29Z: Versions OK
2016-03-25T20:16:29Z: good user
2016-03-25T20:16:29Z: got collection name
2016-03-25T20:16:35Z: context established
2016-03-25T20:16:35Z: UploadCmdLine.LoadedWB
uploading row 0
uploading row 1
2016-03-25T20:16:39Z: UploadCmdLine.UploadFailed
2016-03-25T20:16:39Z: ...exiting UN-successfully.
15:16:35 ERROR specify.config.SpecifySchemaI18NService:168 - Couldn't find field[collectionMemberId] for table [paleocontext]
15:16:35 ERROR specify.config.SpecifySchemaI18NService:244 - Couldn't find field[collectionMemberId] for table [paleocontext]
15:16:35 ERROR wb.wbuploader.MissingDataResolver:497 - unable to meet requirement: Collector.IsPrimary
15:16:37 ERROR datamodel.busrules.LocalityBusRules:293 - The PC null was null or the Locality edu.ku.brc.specify.datamodel.Locality@3bf01a01 : 2016-03-25 15:16:37.802 was null
15:16:37 ERROR datamodel.busrules.CollectingEventBusRules:131 - The PC null was null or the CE edu.ku.brc.specify.datamodel.CollectingEvent@68f2363 : 2016-03-25 15:16:37.883 was null
15:16:39 ERROR datamodel.busrules.LocalityBusRules:293 - The PC null was null or the Locality edu.ku.brc.specify.datamodel.Locality@3fa50a24 : 2016-03-25 15:16:39.157 was null
15:16:39 ERROR datamodel.busrules.CollectingEventBusRules:131 - The PC null was null or the CE edu.ku.brc.specify.datamodel.CollectingEvent@7272914b : 2016-03-25 15:16:39.174 was null
15:16:39 ERROR hibernate.util.JDBCExceptionReporter:78 - Cannot add or update a child row: a foreign key constraint fails (`DemoData`.`collectingevent`, CONSTRAINT `FKFEB30F22A666A5C4` FOREIGN KEY (`LocalityID`) REFERENCES `locality` (`LocalityID`))
15:16:39 ERROR org.hibernate.AssertionFailure:22 - an assertion failure occured (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session)  

In addition, we tried to replicate, but I was unable to validate in Sp7 before Garrett started uploading in Sp6. I tried to validate during Sp6 upload and was unable to, and when the upload was complete, I tried to validate the dateset only to have it fail and I received the same message in details box.

**Comment by benanhalt** [comment]
Two more:
```
pid = 10151
2016-03-25T21:55:05Z: starting with args [Suppressed]...
2016-03-25T21:55:06Z: Got master
2016-03-25T21:55:06Z: logged in
2016-03-25T21:55:06Z: Versions OK
2016-03-25T21:55:06Z: good user
2016-03-25T21:55:06Z: got collection name
2016-03-25T21:55:10Z: context established
2016-03-25T21:55:10Z: UploadCmdLine.LoadedWB
uploading row 0
uploading row 1
2016-03-25T21:55:12Z: UploadCmdLine.UploadFailed
2016-03-25T21:55:12Z: ...exiting UN-successfully.
16:55:10 ERROR specify.config.SpecifySchemaI18NService:168 - Couldn't find field[collectionMemberId] for table [paleocontext]
16:55:10 ERROR specify.config.SpecifySchemaI18NService:244 - Couldn't find field[collectionMemberId] for table [paleocontext]
16:55:11 ERROR wb.wbuploader.MissingDataResolver:497 - unable to meet requirement: Collector.IsPrimary
16:55:12 ERROR datamodel.busrules.LocalityBusRules:293 - The PC null was null or the Locality edu.ku.brc.specify.datamodel.Locality@59014efe : 2016-03-25 16:55:12.673 was null
edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderMatchSkipException: Row 1: Not uploaded due to multiple matches (Collector1 First Name = T, Collector1 Last Name = Adam, )
16:55:12 ERROR hibernate.util.JDBCExceptionReporter:78 - Cannot add or update a child row: a foreign key constraint fails (`DemoData`.`geography`, CONSTRAINT `FK496A777C83AAF47E` FOREIGN KEY (`ParentID`) REFERENCES `geography` (`GeographyID`))
edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderException: org.hibernate.exception.ConstraintViolationException: could not insert: [edu.ku.brc.specify.datamodel.Geography]
16:55:12 ERROR org.hibernate.AssertionFailure:22 - an assertion failure occured (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session)
edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderException: edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderException: org.hibernate.AssertionFailure: null id in edu.ku.brc.specify.datamodel.Geography entry (don't flush the Session after an exception occurs)
Caused by: edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderException: org.hibernate.AssertionFailure: null id in edu.ku.brc.specify.datamodel.Geography entry (don't flush the Session after an exception occurs)
```

```
pid = 10525
2016-03-25T22:27:58Z: starting with args [Suppressed]...
2016-03-25T22:27:58Z: Got master
2016-03-25T22:27:59Z: logged in
2016-03-25T22:27:59Z: Versions OK
2016-03-25T22:27:59Z: good user
2016-03-25T22:27:59Z: got collection name
2016-03-25T22:28:03Z: context established
2016-03-25T22:28:03Z: UploadCmdLine.LoadedWB
uploading row 0
uploading row 1
2016-03-25T22:28:04Z: UploadCmdLine.UploadFailed
2016-03-25T22:28:04Z: ...exiting UN-successfully.
17:28:03 ERROR specify.config.SpecifySchemaI18NService:168 - Couldn't find field[collectionMemberId] for table [paleocontext]
17:28:03 ERROR specify.config.SpecifySchemaI18NService:244 - Couldn't find field[collectionMemberId] for table [paleocontext]
17:28:04 ERROR datamodel.busrules.CollectingEventBusRules:131 - The PC null was null or the CE edu.ku.brc.specify.datamodel.CollectingEvent@68f776e : 2016-03-25 17:28:04.532 was null
edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderMatchSkipException: Row 1: Not uploaded due to multiple matches (Cataloger First Name = Ben, Cataloger Last Name = Miller)
17:28:04 ERROR datamodel.busrules.CollectingEventBusRules:131 - The PC null was null or the CE edu.ku.brc.specify.datamodel.CollectingEvent@277bc3a : 2016-03-25 17:28:04.679 was null
17:28:04 ERROR datamodel.busrules.CollectionObjectBusRules:731 - The CE null was null or the CO 400002 was null
17:28:04 ERROR datamodel.busrules.CollectionObjectBusRules:765 - The PC null was null or the CO 400002 was null
17:28:04 ERROR hibernate.util.JDBCExceptionReporter:78 - Cannot add or update a child row: a foreign key constraint fails (KUHerps.collectionobject, CONSTRAINT FKC1D4635DB237E2BC FOREIGN KEY (CollectingEventID) REFERENCES collectingevent (CollectingEventID))
edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderException: org.hibernate.exception.ConstraintViolationException: could not insert: [edu.ku.brc.specify.datamodel.CollectionObject]
17:28:04 ERROR org.hibernate.AssertionFailure:22 - an assertion failure occured (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session)
edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderException: edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderException: org.hibernate.AssertionFailure: null id in edu.ku.brc.specify.datamodel.CollectionObject entry (don't flush the Session after an exception occurs)
Caused by: edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderException: org.hibernate.AssertionFailure: null id in edu.ku.brc.specify.datamodel.CollectionObject entry (don't flush the Session after an exception occurs)
```

**Comment by yvonneekanim** [comment]
I'm unable to replicate this issue.

**Comment by yvonneekanim** [comment]
I replicated this issue and I didn't encounter any problems. After validation in Specify 7 passed, I uploaded data into the same collection in Specify 6. I tried re-validating in 7 while the 6 upload was going and I got a "validator busy" message. After upload was completed in Specify 6, validation in Specify 7 passed and data uploaded successfully.
