### ISSUE TITLE
Switching to copy and paste view reloads the current page in the error dialog

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2476]
Video did not capture the first
![image](https://user-images.githubusercontent.com/37256050/202723038-ed9259d9-4e45-4761-bcb1-0c9cd3fd214c.png)

https://user-images.githubusercontent.com/37256050/202722753-7a722a46-cc2b-4bcd-8057-fe0dd1bc7ac4.mov

https://willemcatno-edge.test.specifysystems.org/specify/view/collectingtrip/1057/

Edit the latitude, then save. See error.

`edge`, un: `collection`

**Comment by grantfitzsimmons** [comment]
Should be fixed by the changes Jason made

**Comment by maxxxxxdlp** [comment]
I'm currious to know how ths was fixed.
Was it fixed by disabling the interactive Djanog error page and replacing it with the unreadable single line error message?

**Comment by grantfitzsimmons** [comment]
Now it is the single unreadable line, but I prefer it :smile:

Need to fix that...
