### ISSUE TITLE
Using Workbench Data Editing Tools doesn't work correctly in Sp6 for datasets created in Sp7

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#248]
When you create record sets in Specify 7 and then edit the record sets in Specify 6, many of the data editing tools won't work correctly. For example, if you select an entire column and click the yellow pencil to clear the cells, it only clears the top cell. If you select an entire column and right-click and select the "Clear cell(s)" option, it also only clears the first cell. There are probably some other data tools that have issues, but these are the only ones I can think of at the moment. If I find anymore I'll add them in the comments.

**Comment by benanhalt** [comment]
The fix only affects datasets imported post hoc. Previously imported datasets will continue to exhibit the described behavior.

**Comment by tlammer** [comment]
tested it in kuherps was able to use fill down and fill up and copy/paste, fill down and increment, and clear cells
