### ISSUE TITLE
Creating a record set from query results should only give the option to name it

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2481]
`testability`:

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/37256050/203421146-d9da46ef-452f-42e3-bfb8-2b3b21ad926f.png">

`edge`:
<img width="822" alt="image" src="https://user-images.githubusercontent.com/37256050/203422411-387924e2-3507-4230-a3ee-ef50cd8ab9d6.png">

https://willemcatno-edge.test.specifysystems.org/specify/query/new/collectionobject/

**Comment by chanulee1** [comment]
Only name and remarks shown when creating record set from query results.
db: `willemcatno`, `freshfish`
