### ISSUE TITLE
Edits to date fields only register after clicking on page

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2482]
Edits to date fields do not seem to register until an arbitrary location on the page is clicked.

https://user-images.githubusercontent.com/103299204/203439355-9faf7cd1-4bd8-430c-b1b6-45f6924689b1.mp4

db: `kufishnotests`
v: `edge`

**Comment by maxxxxxdlp** [comment]
Not exclusive to `testability`, thus not for this release.

It's correct, we only detect changes and run full validation once the field loses focus. Perhaps that can be improved, but have to be careful about performance (should be careful not to do heavy validation while the user is still typing in the field)

**Comment by grantfitzsimmons** [comment]
Going to close this unless it becomes an issue
