### ISSUE TITLE
[testability] Unexpected save warning dialog when navigating between unsaved records

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2483]
Unexpected save warning dialog appears when navigating to an unsaved record in a records set.

`testability`:

https://user-images.githubusercontent.com/103299204/203478725-8753fdaf-a0e5-4ec5-974f-9c0d556c5943.mp4

https://kufishnotests-testability.test.specifysystems.org/specify/view/collectionobject/6/?recordsetid=44

`edge`:

https://user-images.githubusercontent.com/103299204/203479087-8edcc9ed-2e8d-4f9a-8962-892e88a11c81.mp4

https://kufishnotests-edge.test.specifysystems.org/specify/view/collectionobject/4/?recordsetid=44

**Comment by maxxxxxdlp** [comment]
Fixed. In the process, I refactored a lot of code to fix other record set bugs and simplify the code.

When testing this please also do serious Record Set testing:
- Adding new records to record set
- Creating new record in a record set
- Trying to add duplicate records to a record set
- Navigating in a LARGE record set (10k+) - go to next, previous, first, last, and directly arbitrary index into the number field
- Adding new items to empty record set
- Deleting last record from a record set
- Creating a new record set record, but canceling it before saving (by pressing the back arrow)
- Using browser back and forward arrows for navigating in a record set

Also, do light testing of the "View in forms" button in query results and a SubView on a form for a -to-many relationship

**Comment by melton-jason** [comment]
Record Set Testing Results:
- New record successfully added to record set
- Already existing record successfully added to record set
- Specify gives appropriate error when trying to add a record already in the set
- Navigation: (tested on record set with 15k records):
  - Front, next, first, and last navigation works correctly
  - Direct index entry _does_ work, but navigates user to record on index entry (key press). For example, if the user wanted to navigate to record 436, specify loads record 4, then 43, then 436. This is not a major issue, but can be annoying waiting a second for Specify to load record 43 when you really want to navigate to 436 directly.
- New record successfully added to empty record set
- Already existing record successfully added to empty record set
- Last record successfully deleted in record set
- When in new record set with no records and back button is pressed, Specify navigates user to Record Set dialog 
  - (with new record set saved) 
- Browser back and forward buttons can used to revisit records in record set
  - When user is on first record in record set, back button keeps them on first record in record set

**Comment by melton-jason** [comment]
@maxxxxxdlp 
This can be closed if that is all intended behavior
