### ISSUE TITLE
Add an option to receive quiet response from back-end

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2484]
Need to add support for a `quiet` flag for the app resource and view.json endpoints. Example calls:

`/context/app.resource?name=leaflet-layers&quiet`
`/context/view.json?name=SomeUnknownViewName&quiet`

If the corresponding app resource is not found, these endpoints return 404. This is not ideal, as 404 is logged in the console as an error (which confuses sys admins into thinking there is an error), and it prevents browsers from caching the response (because django tells brosers to not cache errors).

This is where `&quiet` flat would be useful - instead of returning 404, they would make the endpoint return a 204 response.

Also, please add the OpenAPI schema for these endpoints to document the new `quiet` query string parameter

**Comment by melton-jason** [comment]
There seems to be an issue with the construction of the url to the view.json endpoint. More specifically, when constructing a Record Set from a Query, the following error is shown

![recordset_from_query](https://user-images.githubusercontent.com/64045831/203837047-bd15a8b9-0eea-4b72-bc67-999fb4f5b671.png)

As shown in the error, the front end is trying to access the following endpoint `/context/view.json name=_RecordSet_name&quiet=`, which returns the invalid JSON response. Is this how the front-end normally accesses the endpoint in this case?

I am unsure about the `/context/app.resource` endpoint, or other use cases for the `/context/view.json` endpoint.

**Video**

https://user-images.githubusercontent.com/64045831/203836786-e04f3e98-7ffe-41d7-a547-b798f1983822.mp4

**Comment by chanulee1** [comment]
Is this related?

![image](https://user-images.githubusercontent.com/103299204/204066848-01bbcd33-75a4-41d8-bacf-997b3651a4b6.png)

Happens whenever I clear the browser cache.
https://kufishnotests-testability.test.specifysystems.org/specify/command/clear-cache/

**Comment by maxxxxxdlp** [comment]
Different bug, same cause. Good catch!

Fixed in d7f40a722

---


P.S: It's nice how the dialog on the screenshot says "This error is likely caused by a bug in Specify. Please report it."

**Comment by maxxxxxdlp** [comment]
To test:
- Make sure the are no errors in the browser console when opening the welcome page
- Make sure form definitions are loaded correctly when opening a form

**Comment by chanulee1** [comment]
Appears to working.
db: `kufishnotests`, `freshfish`
