### ISSUE TITLE
Broken Validation for OtherResource type in AppResources

### ISSUE THREAD

**Issue by melton-jason** [specify/specify7#2485]
**Describe the bug**
In `testability`, there is validation in place for the `OtherResource` type in AppResources, which prevents the user from creating/saving a new 'Other Resource' regardless of the content within that file. 

**To Reproduce**
1. Go to 'UserTools'
2. Click on 'AppResources'
3. Create a new 'OtherResource' App Resource
4. Try to save the new file with any content

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Specify 7 Version: testability

**Comment by maxxxxxdlp** [comment]
To test:
Try to create a new app resource of type "Other App Resource"
Without putting any content in the editor, try to save the app resource.
No error should happen and resource should be saved

**Comment by chanulee1** [comment]
Fixed.
db: `kufishnotests1
