### ISSUE TITLE
[testability] "Theme" in User Prefs app resource does not update with new value

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2486]
Selecting a new value from picklist in the "Theme" option of a user prefs app resource does not change the value in the box. Can only replicate in `willemcatno`.

https://user-images.githubusercontent.com/103299204/203639010-f2238a49-fe29-45b2-a311-6d1c256344d6.mp4

https://willemcatno-testability.test.specifysystems.org/specify/resources/app-resource/895/

**Comment by maxxxxxdlp** [comment]
Unable to replicate for that resource anymore. But I believe that this is a real bug.
Can you check again to see if it still happens for you?
Also, are there any error messages in the console?

**Comment by chanulee1** [comment]
@maxxxxxdlp It still seems to happen for me.
Console:
<img alt="image" width="500px" src="https://user-images.githubusercontent.com/103299204/204041900-dc74b5ce-dda8-4688-81c3-5bcf855580e9.png"/>

**Comment by maxxxxxdlp** [comment]
Hmm, nothing interesting in the logs.
Still not able to replicate the issue though...
Could you sign in as a different user, in a different collection, a different browser and edit user preferences for a different user?

You mentioned this only happens for this database, but I am not sure why. The theme chooser is not much different from all the other pick lists in user preferences.


https://user-images.githubusercontent.com/40512816/204065949-ca3b661c-b002-4f61-9a1b-35077ed72e88.mov

**Comment by chanulee1** [comment]
@maxxxxxdlp You're right, it seems to only happen when logged in as the user `bafo` while in the collection `BRUV Fish`. Unsure of why; other users with the same permissions and roles seemed to be unaffected by this bug. Changing `bafo`'s roles and permissions seemed to have no effect on this bug.

**Comment by maxxxxxdlp** [comment]
Now I am able to replicate it!

It happened for this user only as they are the only ones that had a DefaultUserPreferences set that override the default value for the ui theme.

The bug was in that it did not update the UI with the new value if default value was overridden for this user by DefaultUserPreferences

**Comment by chanulee1** [comment]
Fixed!
