### ISSUE TITLE
[testability] Cannot associate CE with CO

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2488]
Cannot associate a collecting event with a collection object in `kufishnotests`

![image](https://user-images.githubusercontent.com/103299204/203660666-3b455c98-fea4-490d-9ecf-df66fd6f1948.png)

https://kufishnotests-testability.test.specifysystems.org/specify/view/collectionobject/new/

**Comment by melton-jason** [comment]
This may be related to the fix (e76cbe6) for #2437

**Comment by maxxxxxdlp** [comment]
`Field No: Locality` is a collecting event relationship in this collection.

Collecting event is not set as embedded in this collection, thus you can not embed it in a subview and have to use a query combo box instead.

You can change whether it is embedded by opening the collection form for current collection (https://kufishnotests-testability.test.specifysystems.org/specify/view/collection/4/) and checking the "Is Embedded Collecting Event" checkbox (it's labeled as `Add Collecting Event Automatically` in this collection, but the hover over message has correct name)

Checking that checkbox and reloading the page fixes `Field No: Locality` being disabled
