### ISSUE TITLE
[testability] User Prefs side menu flickering

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2489]
Reproduction of this bug is inconsistent. Seems to happen when clicking on the very bottom section of the side menu and then placing the cursor on and off of it.

https://user-images.githubusercontent.com/103299204/203865838-3e4b5f10-4f0f-48b8-8b42-a47b2e539383.mp4

https://freshfish-testability.test.specifysystems.org/specify/user-preferences/#preferences-0-appResources

**Comment by maxxxxxdlp** [comment]
Weird. I am unable to replicate it. Does this still happen for you?

 Which browser are you using? I tried in Chrome, Firefox and Safari

**Comment by chanulee1** [comment]
@maxxxxxdlp Yes, this still happens for me. I am using Chrome. Not sure if this is relevant (console):
![image](https://user-images.githubusercontent.com/103299204/204049696-a1eba56f-6f7e-4691-915b-6a1e7e3667e3.png)

**Comment by CarolineDenis** [comment]
@chanulee1 when you have time, can you let me know if this still happens in the latest version?
