### ISSUE TITLE
[testability] Bottom of User Prefs side menu is cut off

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2490]
<img alt="image" width="600px" src="https://user-images.githubusercontent.com/103299204/203866226-95b18c74-8bf3-43c1-bc1b-bbf9e69783e5.png"/>

https://freshfish-testability.test.specifysystems.org/specify/user-preferences/#preferences-0-appResources

**Comment by melton-jason** [comment]
Seems fixed! 
I could not find any other issues when testing this.
