### ISSUE TITLE
Incorrect date in "Date Edited" field

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2493]
The "Date Edited" field on the CO form is populated with tomorrow's date. Current date at time of writing this issue: 8:37 pm 11/24/2022 CST.

https://user-images.githubusercontent.com/103299204/203888983-fa30572c-8922-4735-a7b5-553fad3f2653.mp4

https://freshfish-edge.test.specifysystems.org/specify/view/collectionobject/new/

**Comment by maxxxxxdlp** [comment]
Caused by https://github.com/specify/specify7/issues/641
Will repost your comment there
