### ISSUE TITLE
Formatted column titles show table name twice

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2496]
![image](https://user-images.githubusercontent.com/37256050/204043483-7cf7e141-d19b-4da2-ae8f-fde6169f30bf.png)

https://herbrbge-testability.test.specifysystems.org/specify/query/156/
https://herbrbge-edge.test.specifysystems.org/specify/query/156/

See the Taxon Taxon rather than Taxon (formatted).

**Comment by maxxxxxdlp** [comment]
Caused by 593418e27

**Comment by chanulee1** [comment]
@maxxxxxdlp Should the formatted column title be "Taxon (formatted)" or "Taxon"? In `edge`, it is "Taxon (formatted)", in `testability`, it is "Taxon".

**Comment by maxxxxxdlp** [comment]
Used to be `"Taxon (formatted)"`, but I changed it to `"Taxon"`, as `(formatted)` was redundant - it is clear from the context

**Comment by chanulee1** [comment]
Fixed.
