### ISSUE TITLE
Generate Label on Save is ignored

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2497]
![chrome_g1TAZNekse](https://user-images.githubusercontent.com/37256050/204051275-b28cacc9-c034-4108-b4c1-f1c27db9bf10.gif)

It is checked on both forms, but ignored on `testability`.

![image](https://user-images.githubusercontent.com/37256050/204051325-3147930a-fd32-460d-b872-29a5d7a4bc4c.png)

Likely due to the meta menu not having it checked.

https://purdueherbaria-edge.test.specifysystems.org/specify/view/collectionobject/new/
https://purdueherbaria-testability.test.specifysystems.org/specify/view/collectionobject/new/

**Comment by maxxxxxdlp** [comment]
Fixed.

To test:
Test with forms where defaultValue for the checkbox on the form is true and unset (or false)
Between each test, either switch user, or go into `UserPreferences` app resource, empty it, and reload the page

**Comment by grantfitzsimmons** [comment]
```XML
<cell type="field" id="13" uitype="checkbox" name="generateInvoice" label="Generate Invoice on Save" ignore="true" default="true" initialize="vis=false"/>
```

Even though the definition says `default="true"` it is not checked on `testability` (in incognito, on separate browsers). This indicates to me that the form is now being ingored in `testability`. `v7.7.5` is not affected by this problem.

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp You can recreate here:

https://kufishnotests-v775.test.specifysystems.org/specify/view/collectionobject/new/
https://kufishnotests-testability.test.specifysystems.org/specify/view/collectionobject/new/

**Comment by grantfitzsimmons** [comment]
Even after clearing user prefs using the JSON editor, I was not able to make `abentley` recognize this.

However, after creating a new user, it worked properly. I am going to close this issue as it seems this was just an anomoly...
