### ISSUE TITLE
Taxonomic Rank is already red when creating a child

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2498]
![chrome_Ep2lBF1YQ9](https://user-images.githubusercontent.com/37256050/204051609-34498597-8d9d-4e7e-9750-1237d7118e3a.gif)

Left is `edge`, right is `testability`

Go to the tree viewer, add a child, and see that taxonomic rank is already red!

This is on `purdueherbaria`.

https://purdueherbaria-testability.test.specifysystems.org/specify/tree/taxon/?conformation=%7E%7E5941%7E5942%7E45869-%7E5943%7E5944%7E5945%7E7299%7E7324--------

**Comment by melton-jason** [comment]
Issue seems to be fixed!
