### ISSUE TITLE
Attempting to delete an attachment through the blocker dialog throws an AssertionError

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2499]
![chrome_kSxIg3TNQX](https://user-images.githubusercontent.com/37256050/204051949-8e167984-c435-4146-8574-6280ec136ddb.gif)

https://purdueherbaria-testability.test.specifysystems.org/specify/attachments/

Try to delete an attachment from the form. First try to delete the attachment, then delete the {table} attachment, then see the error!

```
AssertionError at /api/specify/agentattachment/8/
attempt to add object with null id to audit log
```

[Specify 7 Crash Report - 2022-11-25T20_20_41.048Z.txt](https://github.com/specify/specify7/files/10094950/Specify.7.Crash.Report.-.2022-11-25T20_20_41.048Z.txt)

**Comment by emenslin** [comment]
cannot repoduce
