### ISSUE TITLE
Specify user form looks like you can modify the password

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2501]
![chrome_upOXQni5m9](https://user-images.githubusercontent.com/37256050/204052190-f99bf880-e5d6-48b7-a9ec-ce40e9bbddc2.gif)

It should not allow users to enter in the password field. Maybe more importantly, specify user links should probably bring you to the security panel rather than the record.

**Comment by maxxxxxdlp** [comment]
Fixed in 3c8651ae7 by making that field hidden

**Comment by chanulee1** [comment]
Field is hidden, but can be viewed using the auto generated form. Is this ok?
https://kufishnotests-testability.test.specifysystems.org/specify/view/specifyuser/1/

**Comment by chanulee1** [comment]
How do I test this?

**Comment by maxxxxxdlp** [comment]
The autogenerated form should not include the password field anymore
