### ISSUE TITLE
Opening query results in the form viewer navigates to the last record

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2502]
![chrome_LofQXNZR1a](https://user-images.githubusercontent.com/37256050/204057257-82be2655-cfff-41a2-a9a0-91b09b02ae7d.gif)

`edge` on left, `testability` on right

https://umich-testability.test.specifysystems.org/specify/query/117/

When opening in forms, I am already looking at the last item returned in the query!

Chrome, Windows 11

**Comment by chanulee1** [comment]
Fixed.
