### ISSUE TITLE
[testability] Sorting for History of Edits Query Builder not Working

### ISSUE THREAD

**Issue by melton-jason** [specify/specify7#2505]
**Describe the bug**
The sorting functionality for columns within the history of edit query builder seems to be broken. For each column within the Query Builder, once it is sorted from its initial state, it stays sorted in that way.  
This seems to be the only instance of the Query Builder with this issue. 

(Note: Both of the videos below start from the initial state of the History of Edits screen)

Actions example:

https://user-images.githubusercontent.com/64045831/204059321-7296bb56-a0b4-44fa-b412-ccfab26b61b9.mp4

Timestamp Example:

https://user-images.githubusercontent.com/64045831/204059392-de4d2bfe-82cf-468b-9f30-85c582a35df0.mp4

**Desktop:**
Chrome, Windows 11
`willemcatno` database

https://willemcatno-testability.test.specifysystems.org/specify/view/collectionobject/171381/

**Comment by maxxxxxdlp** [comment]
Fixed. Please do good testing for this as the code for this is a bit complicated (the query on audit log table adds some fields on the fly)

Also, try constructing a new audit log query (not though edit history dialog), and testing sorting for different columns there

Also, try running a query on collection object, that has a field from the locality table in any column other than the last one - test sorting for columns to the left of the locality column, for the locality column, and for the columns after the locality column
