### ISSUE TITLE
Support nested switch statements in DataObjFormatters

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#2507]
Requested by CSIRO:

> We currently have our format for the determination table differ based on the isCurrent field (see image) but I was wondering if there was a way to check multiple fields? In our fish collection we have the isCurrent field but also another boolean field called "Label". We'd like to have four different table formats:
isCurrent=true & Label=true | prefferedTaxon.fullName (current) (label)
isCurrent=true & Label=false| prefferedTaxon.fullName (current)
isCurrent=false & Label=true | prefferedTaxon.fullName (label)
isCurrent=false & Label=false | prefferedTaxon.fullName

> Is this possible? I can see that the UI in Specify6 only lets us pick one dependent field but I can see that the code is written into the DataObjFormatters app resource - can I change the code here to achieve the example above? Our current code is below for reference.

```xml
<format
        name="Determination"
        title="Determination"
        class="edu.ku.brc.specify.datamodel.Determination"
        >
        <switch single="false" field="isCurrent">
            <fields value="true">
                <field>preferredTaxon.fullName</field>
                <field type="boolean" format=" " sep=" (current)">isCurrent</field>
                <field type="boolean" sep=" - (label)">yesNo1</field>
            </fields>
            <fields value="false">
                <field>taxon.fullName</field>
            </fields>
        </switch>
    </format>
```

**Comment by grantfitzsimmons** [comment]
This would be nice.

**Comment by maxxxxxdlp** [comment]
Optional TODO here:
Check if sp6 includes support for this in the code (but not in the UI)
Because I remember Ben opened an issue at one point saying to add this feature (at least 5 years ago), which gives me an impression this might be implemented behind the scenes in sp6
