### ISSUE TITLE
Opening overlay causes record set context loss

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2508]
> Also, opening dialogs opens the form of the record that the user is currently on in the record set, outside of the record set. Opening another takes the user back to the correct record in the record set.

> https://user-images.githubusercontent.com/103299204/204045292-5341b5d9-8522-4bdf-9ad5-ab5767ccbb30.mp4

_Originally posted by @chanulee1 in https://github.com/specify/specify7/issues/2487#issuecomment-1327831252_

**Comment by chanulee1** [comment]
Fixed.
