### ISSUE TITLE
[testability] Opening new data entry form while at end of a record set adds record to record set

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2510]
Navigating to end of record set and attempting to open a new data entry form opens the record in the record set. In some record sets, saving this record seems to place a random?, pre-existing record at the end of the record set that is from the same table as the record set.

https://kufishnotests-testability.test.specifysystems.org/specify/view/collectionobject/61115/?recordsetid=44

https://user-images.githubusercontent.com/103299204/204641382-52b6db26-1639-4b23-857f-e7a8cbb5ed25.mp4

In other record sets, saving this record replaces other records in record set with records from same table as this record. Reopening record set and navigating to this record results in 404 "Not Found" page when navigating to it at the end of record set.

https://kufishnotests-testability.test.specifysystems.org/specify/view/collectingevent/1/?recordsetid=104

https://user-images.githubusercontent.com/103299204/204644270-60b07bae-bc35-430a-a0f1-c96a337ead97.mp4

**Comment by maxxxxxdlp** [comment]
Caused by 9a90347d6
Fixed in 69e5ea2c7

**Comment by chanulee1** [comment]
Fixed. db: `kufishnotests`
