### ISSUE TITLE
Count button not working in a query

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2513]
![image](https://user-images.githubusercontent.com/37256050/204690872-9081cc40-b2a3-4546-b8fb-b07b3f94f66a.png)

`edge` on left, `testability` on right

You cannot click "Count"

https://cuicnov29-edge.test.specifysystems.org/specify/query/3/
https://cuicnov29-testability.test.specifysystems.org/specify/query/3/

**Comment by maxxxxxdlp** [comment]
Good catch!
It's been broken for 3 months now (since 0a8bcfa177)

**Comment by chanulee1** [comment]
Fixed.
