### ISSUE TITLE
[testability] Cannot immediately navigate away from 404 error page

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2515]
Only the second input navigates away to the desired page.

https://user-images.githubusercontent.com/103299204/204714963-f7abaa54-d998-4873-8fa6-df4e82a4911d.mp4

https://kufishnotests-testability.test.specifysystems.org/specify/view/collectingevent/61167/?recordsetid=98

**Comment by melton-jason** [comment]
This does not seem to happen on all 404 pages.  This problem does not occur for a url like: 
https://kufishnotests-testability.test.specifysystems.org/specify/view/collectingevent/someevent

_Some additional context_: 
When you click on one of the Header items from the buggy 404 page, Specify still navigates you to the overlay url, yet does not show the dialog. So, if you click on another Header item, it _does_ bring you to the correct url and show the correct dialog, but if that dialog is closed, Specify brings you to the page you were on previously--- which was the previous overlay. 

**Video**

https://user-images.githubusercontent.com/64045831/205097543-8f5490d4-c703-4744-9e7d-f961ed5ad3e3.mp4

**Comment by maxxxxxdlp** [comment]
Happens only for 404 errors that occur when in a record set

**Comment by chanulee1** [comment]
Appears to be fixed.
db: `kufishnotests`
