### ISSUE TITLE
Geography records trigger unsaved warning when no change has been made

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2517]
https://user-images.githubusercontent.com/37256050/204844550-003e5ad4-ada3-4d5b-ba48-e6a39376604d.mov

`edge` is on left, `testability` on right

https://keherbariumvascular-edge.test.specifysystems.org/specify/view/locality/39919/?recordsetid=3

https://keherbariumvascular-testability.test.specifysystems.org/specify/view/locality/39919/?recordsetid=3

**Comment by maxxxxxdlp** [comment]
FYI: these are localities, not geographies

**Comment by chanulee1** [comment]
Appears to be fixed.
