### ISSUE TITLE
Add calculated fields for Exchange Out, Disposal, Gift, and Deaccession

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2521]
Exchange Out calculated fields currently are unsupported
- Total Preps (Sum of all associated exchange out preparations)
- Total Items (Sum of all associated collection object preparations)

Disposal calculated fields currently are unsupported
- Total Preps (Sum of all associated disposal preparations)
- Total Items (Sum of all associated collection object preparations)

Gift calculated fields currently are unsupported
- Total Preps (Sum of all associated gift preparations)
- Total Items (Sum of all associated collection object preparations)

Deaccession’s calculated fields currently are unsupported ([#2114](https://github.com/specify/specify7/issues/2114))
- Total Preps (Sum of all associated disposal, gift, and exchange out preparations)
- Total Items (Sum of all associated collection object preparations)

**Requested By:** RBGE, Pioneer Trails Regional Museum, University of Michigan

**Comment by grantfitzsimmons** [comment]
Reported by Jordi at MCNB

![image](https://github.com/specify/specify7/assets/37256050/0162432f-e30f-4f0c-8c8f-3fbaf24cb6b2)

**Comment by grantfitzsimmons** [comment]
From @acwhite211 [here](https://github.com/specify/specify7/issues/2114#issuecomment-2032440679):

> Here are some code sections I found in Specify 6 related to deaccession and the actual count:
> - https://github.com/specify/specify6/blob/945d28f00288d2d64979848fb2fb63fda34bdd1b/src/edu/ku/brc/specify/datamodel/Preparation.java#L648-L687
> - https://github.com/specify/specify6/blob/945d28f00288d2d64979848fb2fb63fda34bdd1b/src/edu/ku/brc/specify/datamodel/CollectionObject.java#L1228-L1235
> - https://github.com/specify/specify6/blob/945d28f00288d2d64979848fb2fb63fda34bdd1b/src/edu/ku/brc/specify/datamodel/Accession.java#L787-L808
> - https://github.com/specify/specify6/blob/945d28f00288d2d64979848fb2fb63fda34bdd1b/src/edu/ku/brc/specify/datamodel/Preparation.java#L1424C29-L1439

**Comment by acwhite211** [comment]
https://github.com/specify/specify7/pull/4824#issuecomment-2075411792
> I found the file https://github.com/specify/specify7/blob/production/specifyweb/specify/calculated_fields.py where many of the already implemented virtual calculated fields are coded. I think it will be good to extend this file, instead of using business rules. Although this file uses manually created sql code, so it would be ideal to use the Django ORM in this file where possible.
