### ISSUE TITLE
Query builder shows results from the previous query

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2524]
1. Run new query on the taxon table
2. Open the query builder for the Audit Log table
3. Run the query
4. After 4 seconds, the audit log results are replaced with the old taxon results:

<img width="1800" alt="Screen Shot 2022-10-26 at 10 58 55" src="https://user-images.githubusercontent.com/40512816/205312761-7295e5b0-5b16-462c-95ba-459f8b5f9bcb.png">

Same can be seen in reverse (open new audit log query, run it, open new taxon query, run it, see audit log results)

**Comment by maxxxxxdlp** [comment]
Likely present on edge. Have to delay till next release

**Comment by CarolineDenis** [comment]
@maxxxxxdlp are you still experiencing this issue?

**Comment by maxxxxxdlp** [comment]
No, doesn't seem to happen anymore.
At a time I didn't have time to investigate the cause, but maybe some other change fixed this since then.
Will reopen if it happens again
