### ISSUE TITLE
When an Exchange Out Attachment is present, `TypeError` occurs

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2525]
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/37256050/205312615-ebf0cd13-1aa5-4720-b13d-e78df4077692.png">

[Specify 7 Crash Report - 2022-12-02T14_18_16.236Z.txt](https://github.com/specify/specify7/files/10141779/Specify.7.Crash.Report.-.2022-12-02T14_18_16.236Z.txt)

```
TypeError at /api/specify/exchangeout/
cannot unpack non-iterable NoneType object
```

> I’m not sure if this issue is linked to the other errors we have had around saving records.
> 
> I added attachments to Exchange Out yesterday. This morning we tried to attach a pdf to one of the records. The file attached OK, but when trying to save the record we got an error.
> 
> I have attached the crash report.

Internal (debug) crash report:
[Specify 7 Crash Report - 2022-12-02T14_18_16.236Z.txt](https://github.com/specify/specify7/files/10141786/Specify.7.Crash.Report.-.2022-12-02T14_18_16.236Z.txt)

RBGE crash report:
[Specify 7 Crash Report - 2022-12-02T09 08 01.231Z (2).txt](https://github.com/specify/specify7/files/10141788/Specify.7.Crash.Report.-.2022-12-02T09.08.01.231Z.2.txt)

`edge` and `v775`

**Comment by grantfitzsimmons** [comment]
Very similiar to this issue-
https://github.com/specify/specify7/issues/2477

and this RBGE issue as well-
https://github.com/specify/specify7/issues/2409

**Comment by grantfitzsimmons** [comment]
Not unexpected, but same issue in `testability`

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/37256050/205314693-a2ee6ab0-d4b1-4b0f-8ad9-b631ae472b9d.png">

[Uploading Specify 7 Crash Report - 2022-12-02T14_25_21.358Z.txt…]()

**Comment by grantfitzsimmons** [comment]
Same issue when saving an attachment with Disposal:

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/37256050/205687581-f74c0d56-6495-4dd4-8e93-0a03e26abfa6.png">
[Uploading Specify 7 Crash Report - 2022-12-05T16_19_49.438Z.txt…]()

on `testability` and `edge`

**Comment by benritchie** [comment]
Update - this seems to still be broken in 7.8
Any update on getting this issue fixed?  
Thanks
