### ISSUE TITLE
Can duplicate data set name

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#253]
I created a data set called "test7" a while ago then a bit later created another data set, both through Specify 7, with the same name.

**Comment by benanhalt** [comment]
Should I just remove the naming step and generate a new name that the user can then change on the WB screen?

**Comment by tlammer** [comment]
?Is there a way to just check if the name already exists and say they can't use a name if it is there already?  I thought you had done that already, but couldn't find the existing bug.

________________________________

**Comment by benanhalt** [comment]
Yeah, I can do that. It just occurred to me that maybe we don't really need that intervening step since there is already a way to set the name.

**Comment by tlammer** [comment]
it adds the (1) to data set names even when the data set no longer exists.

**Comment by tlammer** [comment]
verified 
adds (1) to duplicate names and not to data set names that are not duplicates
