### ISSUE TITLE
Page deletion should not be stored in category editing session

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2535]
- Page deletion should not be stored in category editing session

**Comment by maxxxxxdlp** [comment]
Not quite sure what this is about.
@realVinayak close this if it it completed. if not, ask Grant for more information

**Comment by realVinayak** [comment]
Right now all layout changes are done behind a single Edit session. Trivial to make page edits and category edits separate, but I'd vote for this to be in the next release. What do you think @grantfitzsimmons?

**Comment by grantfitzsimmons** [comment]
Next release!

**Comment by grantfitzsimmons** [comment]
Closing unless we decide to add this at a later date.
