### ISSUE TITLE
Formatted column title for base table not showing table icon

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2536]
Querying for formatted records of the base table in query builder displays the formatted column title for these records without the table icon of the base table.

![image](https://user-images.githubusercontent.com/103299204/205356211-12db2f4c-5d51-4baa-9969-4e2456d2e604.png)

branch: `edge`

**Comment by maxxxxxdlp** [comment]
Is this reproducable on `testability`?

**Comment by chanulee1** [comment]
> Is this reproducable on `testability`?

Yes, it is.
