### ISSUE TITLE
[testability] Error when attempting to delete certain Agent record with delete blocker

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2538]
Attempting to delete agent `User, Test C` with delete blocker results in error message.

https://user-images.githubusercontent.com/103299204/205371700-5fb121c4-6b41-4211-898a-9a80a88d09a1.mp4

https://kufishnotests-testability.test.specifysystems.org/specify/view/agent/3/?recordsetid=114

[Specify 7 Crash Report - 2022-12-02T19_38_06.885Z.txt](https://github.com/specify/specify7/files/10143808/Specify.7.Crash.Report.-.2022-12-02T19_38_06.885Z.txt)

Console:
<img alt="img" width="500px" src="https://user-images.githubusercontent.com/103299204/205373028-91bb3cb1-eb34-47b1-911d-edaf96a18e19.png"/>

**Comment by maxxxxxdlp** [comment]
Fixed front-end failing when fetching SpPrincipal resource
    
That tables is for storing sp6 permissions

Front-end doesn't really use it, but it caused issues when rendering the display blockers because that table has a weird field, that can be a relationship to any scoping table

**Comment by maxxxxxdlp** [comment]
Fixed.

Unfortunately, this could happen in a lot of places. There is a way to solve this issue everywhere, but I don't want to make such a drastic change before release. For now, only this place is fixed
