### ISSUE TITLE
[testability] Saving changes to a user clears password

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2539]
Making changes to a user and saving them clears the user's password. A new password must be made for them to be able to log in.

https://user-images.githubusercontent.com/103299204/205376967-a361a90c-0ca6-4fd4-8198-8f990325d734.mp4

After save:
![image](https://user-images.githubusercontent.com/103299204/205377210-fb01c4fc-6bd5-450d-945f-b34dbc11a615.png)

https://kufishnotests-testability.test.specifysystems.org/specify/security/user/1/

**Comment by chanulee1** [comment]
Making changes to a user does not clear password. Is there anything else that needs to be tested for this issue?

**Comment by maxxxxxdlp** [comment]
General testing of the user editing page would always be nice, but it's not required as part of testing this bug.
Thanks for finding this bug!
