### ISSUE TITLE
Add ability to customize the buttons in the meta menu

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2540]
<img width="763" alt="image" src="https://user-images.githubusercontent.com/37256050/205377653-dbbe0ef7-75f6-4665-acd8-97e91a7ffeed.png">

Per our conversation, there should be a potential of 4 buttons total.

**By default, the buttons Clone, Add, and Save should be present as in 7.7.5.**

You should be able to toggle if **Carry Forward**, **Clone**, and **Add** are visible on the form in the meta menu.

**Comment by maxxxxxdlp** [comment]
Fixed in 41d328a51 and 06496e454
