### ISSUE TITLE
[testability] Changing "Hide Table" option in schema config results in error

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2541]
Checking/unchecking the "Hide Table" checkbox in the schema config results in an error.

https://user-images.githubusercontent.com/103299204/205386197-c016679e-6359-45f8-9722-7aba9828b621.mp4

https://kufishnotests-testability.test.specifysystems.org/specify/schema-config/en/Accession/

[Specify 7 Crash Report - 2022-12-02T21_07_48.690Z.txt](https://github.com/specify/specify7/files/10144334/Specify.7.Crash.Report.-.2022-12-02T21_07_48.690Z.txt)

Console:
![image](https://user-images.githubusercontent.com/103299204/205386335-fd994fe1-c09d-4e50-b2ad-c73effb0ec1e.png)

**Comment by grantfitzsimmons** [comment]
Maybe I just need to refresh the instance - https://github.com/specify/specify7/issues/2547

**Comment by chanulee1** [comment]
Table descriptions are not loaded. Changes to table label and description are not kept after saving.

![image](https://user-images.githubusercontent.com/103299204/206035282-f210a4e2-9ad0-419a-b15d-fefd35af3e83.png)

https://kufishnotests-testability.test.specifysystems.org/specify/schema-config/en/Accession/

**Comment by chanulee1** [comment]
Table descriptions still seem to be not loaded.
![image](https://user-images.githubusercontent.com/103299204/206302623-4cf1ca8d-0cb7-4f7a-a2e4-1395fc1d7a40.png)
