### ISSUE TITLE
`MissingAgentForAccessibleCollection` when adding policies to role

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2545]
https://user-images.githubusercontent.com/37256050/205684733-9334715b-8ec7-4081-8522-1b0ccdd99a82.mov

**Steps:**

1. Go to "herbarium" collection
2. Scroll down and check all boxes for the the WorkBench policies
3. Save

[Specify 7 Crash Report - 2022-12-05T16_08_03.921Z.txt](https://github.com/specify/specify7/files/10155819/Specify.7.Crash.Report.-.2022-12-05T16_08_03.921Z.txt)

Can recreate in `edge` and `testability` when following the steps detailed above.

**Comment by maxxxxxdlp** [comment]
I think this is both front-end's and back-end's fault:
1. If the check for whether users have agents assigned in all accessible collections fails, back-end should include user id in the response
2. Front-end should use the user id to display a dialog prompting user to assign missing agents (like the dialog used on the user editing page)

**Comment by emenslin** [comment]
Fixed
