### ISSUE TITLE
Cannot edit table description 

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2547]
https://user-images.githubusercontent.com/37256050/205725599-9e04e887-7f51-4884-8420-cae647ce5e85.mp4

There's even a discrepency between `edge` (left) showing the proper description and the `testability` (right) description of "Collection Object"

<img width="1711" alt="image" src="https://user-images.githubusercontent.com/37256050/205725682-5dbeaf4d-d460-49a0-8d6a-e4067f5bba4e.png">

**Comment by grantfitzsimmons** [comment]
https://umich-testability.test.specifysystems.org/specify/schema-config/en/CollectionObject/

https://umich-edge.test.specifysystems.org/specify/task/schema-config/?language=en&table=collectionobject

**Comment by grantfitzsimmons** [comment]
Not fixed after restarting the instance.

**Comment by maxxxxxdlp** [comment]
Fixed in bd287a013

**Comment by maxxxxxdlp** [comment]
Closing this as it was tested as part of testing https://github.com/specify/specify7/issues/2541

**Comment by chanulee1** [comment]
Sorry, only tested the "Hide Table" option in #2541. The table caption and description still seem to be uneditable.
https://kufishnotests-testability.test.specifysystems.org/specify/schema-config/en/Accession/
