### ISSUE TITLE
Carry forward options should not appear when a form is a subview

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2548]
<img width="849" alt="image" src="https://user-images.githubusercontent.com/37256050/205731698-da4d77e6-56f5-470c-9654-011665e4086d.png">

It has no impact as there is not a Carry Forward or Clone button on a subview. Close if I am incorrect, but I cannot find a use.

**Comment by maxxxxxdlp** [comment]
There is a use:
If you configure carry forward settings for a Collection Object Attributes table, and then press "Carry Forward" on the Collection Object form, the carry forward settings for Collection Object Attributes would be respected when clonning that resource.
Of course, now that the Carry Forward dialog also includes a way to edit the carry over for dependent relationships, this is a bit redundant.

Thus, should I hide the carry forward config for subviews? Should I also hide the Generate Label on Save, Generate Label, Show Add Button, Show Clone Button options?

**Comment by grantfitzsimmons** [comment]
I find it redundant & confusing personally since this can be configured from the main form's meta menu. I imagine that other users would feel the same way, as the behavior can be customized without a clear ability to use the function itself. It is inconsistent with the whole form behavior.

Generate Label on Save would not function as one would expect, but Generate Label for a subview's record could have a use case potentially. I cannot think of one of the top of my head, but there are situations in which someone may wish to print a collecting event or preparation as a report/label... maybe.

Configuring the buttons when they do not appear would also be confusing & unnecessary in my opinion. Sharing the record is not a bad option, but I don't know if it will be used.

This is my opinion based on my experience, so I welcome any other thoughts on this!

**Comment by maxxxxxdlp** [comment]
Fixed
