### ISSUE TITLE
Allow setting default quantity of preps when selecting all preps

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2549]
> For many of our loans we will have multiple loan preparations that we have to add (>30) but when you add the list of preparations (from a record set) it defaults to choosing the highest quantity for all preps (image 1). In our case we'd like the default quantity to be 1, can we change that anywhere?

![image](https://user-images.githubusercontent.com/37256050/205810711-7ace1e5d-de5e-4825-80b5-8f6012c5870a.png)

**Requested By:** Dan Baker at CSIRO on [Asana](https://app.asana.com/0/1201972579963460/1203424280039616/f)

**Comment by cdamyx** [comment]
Hi @grantfitzsimmons,

Is the ask here for the default quantity to be set to "1" for the "Selected" column?

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons or do they want a separate input field at the top in which they can type the count, and it would select that many from each preparation (or less if that many aren't available)?

**Comment by danb213** [comment]
Hi @maxxxxxdlp that would be great to be able to bulk update the count amount for all preparations to be any number (as you said selecting only what is available if the count goes above what is available

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-9-release-announcement/1131/1
