### ISSUE TITLE
Cannot use "Count" feature in a query

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2551]
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/37256050/205945657-eb6aad52-cf66-40e9-bc00-74f453426893.png">

```
TypeError: Cannot read properties of undefined (reading 'length')
    at https://herbrbge6802-testability.test.specifysystems.org/static/js/7377.067cb8cd9ba92c043133.bundle.js:1:175003
    at async https://herbrbge6802-testability.test.specifysystems.org/static/js/7377.067cb8cd9ba92c043133.bundle.js:1:223558
```

[Specify 7 Crash Report - 2022-12-06T14_55_51.923Z.txt](https://github.com/specify/specify7/files/10167518/Specify.7.Crash.Report.-.2022-12-06T14_55_51.923Z.txt)

https://herbrbge6802-testability.test.specifysystems.org/specify/query/155/

Works fine in `edge`, not `testability`

**Comment by maxxxxxdlp** [comment]
Fixed. For testing, use that particular user as this did not happen for a different user for some reason.

When testing, please also do general testing of the query builder in the "Count" mode and the regular "Query" mode. The "Count" mode was a bit neglected (there was a bug where "Create CSV" and other buttons would be visible, even if you are in the "Count" mode - that should be fixed now but needs testing)

**Comment by grantfitzsimmons** [comment]
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/37256050/207161381-e0fb9f90-d474-4d2a-9bfa-6250b5518df7.png">

https://coldfish-testability.test.specifysystems.org/specify/query/70/

user: `abentley`, `KU Fish Tissue Collection`
