### ISSUE TITLE
Clone button uses Carry-Forward options

### ISSUE THREAD

**Issue by melton-jason** [specify/specify7#2552]
**Describe the bug**
See #2540 
It appears the clone button uses the functionality of the Carry Forward options when creating a new record. By default, shouldn't Clone copy over every available field (create a "Full Copy" of the current record)? 

https://user-images.githubusercontent.com/64045831/205957175-7ae15b89-4cde-4968-b696-60e9e980512b.mp4

https://user-images.githubusercontent.com/64045831/205957183-0a05ab68-896e-4bca-a42a-1a6d49c65588.mp4

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Specify 7 Version: testability

**Comment by chanulee1** [comment]
Clone and carry-forward have expected functionality.
Tested: `kufishnotests`
