### ISSUE TITLE
Carry forward should not include most one-to-manys

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2553]
<img width="904" alt="Screenshot 2022-12-06 at 2 34 56 PM" src="https://user-images.githubusercontent.com/37256050/206020090-e74bc5a9-408c-4a14-8225-7a67e3aa97ac.png">

taxons, collectionObjects, etc.

**Comment by maxxxxxdlp** [comment]
To check
1. Is new behavior different from `edge`?
2. Are those relationships actually being carried over, or is it just UI showing them falsly

**Comment by maxxxxxdlp** [comment]
Confirmed, this is just a UI bug. Independent -to-manys aren't actually getting cloned.
Fixed

**Comment by grantfitzsimmons** [comment]
Meant to mention I can confirm it is a UI bug myself.

**Comment by grantfitzsimmons** [comment]
We can close this as long as it's fixed in the UI
