### ISSUE TITLE
Handle links to deleted records better

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2558]
If the link refers to an existing record, but a non-existent record (i.e, because the record set was deleted), the form shows a 404 error.

http://localhost/specify/view/agent/3/?recordsetid=114

A better behavior would be to redirect the user out of the context of a record set.

**Comment by maxxxxxdlp** [comment]
Steps to reproduce the issue:
1. Create a record set
2. Create a record in a record set
3. Copy the URL of the page
4. Delete the record set (without deleting the record itself)
5. Paste the copied URL
6. It shows 404 page because record set does not exist. Instead, since the record still exists, it should redirect to the URL for viewing that resource outside of the record set

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-9-release-announcement/1131/1
