### ISSUE TITLE
Error when adding additional preparation to an existing collection object

### ISSUE THREAD

**Issue by mc0822** [specify/specify7#2561]
RBGE reports being unable to save when adding additional preparation to an existing collection object.

(https://herbrbge6802-edge.test.specifysystems.org/specify/view/collectionobject/151675/)

Steps:
Add an additional preparation to an existing collection object.  It adds the preparation.  When click save, get the error message (below). 

**Expected behavior**
User should be able to save when adding additional preparation to an existing collection object.

**Screenshots**
![120722 snip rbge](https://user-images.githubusercontent.com/111374878/206277840-c14a9b35-7c6a-460c-8db0-c061933ce75e.PNG)

**Desktop:**
 - OS: Windows 10
 - Browser: Safari
 - Specify 7 Version: edge

**Database Name:**
herb_rbge_6802 (6.8.02)
britchie
Herbarium

**Reported By**
Robyn Drinkwater, RBGE

**Additional context**
[Specify 7 Crash Report - 2022-12-07T19_18_21.559Z.txt](https://github.com/specify/specify7/files/10179369/Specify.7.Crash.Report.-.2022-12-07T19_18_21.559Z.txt)

**Comment by beach53** [comment]
Safari for Windows?  Curious. Last update from Apple was 2012 for Windows versions.

"Before installing this version of Safari on Windows 11 or 10, remember that it’s an outdated version and lacks many of the security features present in the latest version of Safari. We recommend using the latest version of Chrome, Edge, or Firefox for peace of mind."

**Comment by grantfitzsimmons** [comment]
@beach53  Based on the screenshot, that is Microsoft Edge

**Comment by grantfitzsimmons** [comment]
I am entirely unable to recreate your issue on my end using `edge` with the link shared here. Is there some particular behavior necessary to recreate?

I have added values to every field in the preparation subview, but no success.

Interestingly, I was able to get another error when I entered just a barcode as she described in her email.

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/37256050/206347457-5beaddc0-36f6-40ae-aee9-4083fee387f9.png">

[Specify 7 Crash Report - 2022-12-08T03_16_55.589Z.txt](https://github.com/specify/specify7/files/10181769/Specify.7.Crash.Report.-.2022-12-08T03_16_55.589Z.txt)

This issue occured with a duplicate barcode.

**Comment by mc0822** [comment]
I meant to list Edge, I'll need to edit github issue, sorry for the confusion.  Safari was listed in the template, and I forgot to change it.

Thank you,

Mandi Chace
Specify Technical Support Manager / Research Informatics Developer
KU Biodiversity Institute
1345 Jayhawk Blvd., Rm. 606
Lawrence, KS 66045
Desk: (785) 864-4400
***@***.******@***.***>
https://biodiversity.ku.edu/informatics

**Comment by maxxxxxdlp** [comment]
This error usually indicates mysql was overloaded, or it was being restarted. And yet, DB usage was quite low.

Are they able to replicate this issue consistently? Maybe it was just a fluke
