### ISSUE TITLE
Django error on duplicate CO.uniqueIdentifier

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2568]
Trying to create a record with duplicate Collection Object uniqueIdentifier causes this rather unhelpful error:

![Screenshot 2022-12-08 at 14 45 02](https://user-images.githubusercontent.com/40512816/206563768-0af282de-08cc-4906-9043-bcdf16602adc.png)

[Specify 7 Crash Report - 2022-12-08T20_44_44.582Z.txt](https://github.com/specify/specify7/files/10189321/Specify.7.Crash.Report.-.2022-12-08T20_44_44.582Z.txt)

**Comment by melton-jason** [comment]
This is because CO.uniqueIdentifier (and other uniqueIdentifier fields in CollectingEvent/Locality) were not uniqueness rules on either the frontend or backend. 
Fixed/Added on the `refactorBusrules` branch in 047b17a

**Comment by grantfitzsimmons** [comment]
Fixed in https://github.com/specify/specify7/pull/2965
