### ISSUE TITLE
Add tool to import/export form definitions.

### ISSUE THREAD

**Issue by jobdiogenes** [specify/specify7#257]
I couldn't find a way to setup/change fields to show in form/edit.

**Comment by benanhalt** [comment]
The forms are defined by XML documents stored in the database. There is a tool in Specify 6 to import and export the XML, but it is not in Specify 7 yet. If you can connect to your database with Specify 6, that is probably the easiest way to access them.

Most of our users are not comfortable editing the XML themselves, so they usually send us their databases to customize. Let me ask @tlammer if there is any documentation for customizing the forms.

**Comment by tlammer** [comment]
There is a document on how to modify the forms.  We can also help with it if you would like.  I am attaching the document.  If you have questions about the content, let me know at support@specifysoftware.org.
[Editing Forms in Specify 6.docx](https://github.com/specify/specify7/files/217576/Editing.Forms.in.Specify.6.docx)
