### ISSUE TITLE
[testability] Root nodes of trees can be cloned

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2575]
Mouse cursor is disabled for the clone and carry forward buttons of the root nodes of trees, but these nodes can be cloned anyways.

Geography tree:

https://user-images.githubusercontent.com/103299204/206766581-45df2015-2aaf-46ce-a9e2-b2844e950724.mp4

Taxon tree:

https://user-images.githubusercontent.com/103299204/206766751-e2513af6-cc86-437c-88f4-ee4c7a47c907.mp4

https://kufishnotests-testability.test.specifysystems.org/specify/tree/geography/?conformation=%7E-

**Comment by chanulee1** [comment]
Records cloned from the root display an api link in the rank field once a parent is selected.

https://user-images.githubusercontent.com/103299204/206767271-e19905e8-9b4c-430a-8e38-6a70896f5daf.mp4

**Comment by maxxxxxdlp** [comment]
Disabled most tree actions for root tree nodes
