### ISSUE TITLE
Taxon tree items repeatedly cycled through

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2577]
Unsure of what triggers this, but it happened twice while navigating through the taxon tree. Was unable to recreate the conditions for it. Happened on `testability` but am not sure if it is specific to it.
db: `UOregonPaleo`

https://user-images.githubusercontent.com/103299204/206811785-23399b83-ffbc-455a-b281-a2704d13dea4.mp4

https://uoregonpaleo-testability.test.specifysystems.org/specify/tree/taxon/?conformation=%7E-

**Comment by maxxxxxdlp** [comment]
Happens in 7.7 too

**Comment by chanulee1** [comment]
https://user-images.githubusercontent.com/103299204/214460076-aaccd5e5-c1da-4d94-9590-bfdf40efe478.mp4

db: `aafc_aac_dao`
col: `DAO Herbarium`
branch: `edge`

**Comment by maxxxxxdlp** [comment]
Can you test if this is still happening?
This could have been the same bug as https://github.com/specify/specify7/issues/2955

**Comment by grantfitzsimmons** [comment]
Should be fixed by https://github.com/specify/specify7/pull/2796. Reopen if 7.9 does not fix this issue.

>Caused by local storage syncing between tabs. Need to research more what is the best way to fix this, while still preserving localstorage sync (i.e, maybe adding a 10ms throttle)

**Comment by CarolineDenis** [comment]
@specify/ux-testing could you test this on xml-editor branch please?
