### ISSUE TITLE
[testability] Deleting a saved query from inside of it does not navigate away immediately

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2580]
https://user-images.githubusercontent.com/103299204/206831560-6d655ede-14b6-48f1-86bf-8858272e7ff9.mp4

**Comment by grantfitzsimmons** [comment]
@mc0822 recreated this issue again today.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-9-release-announcement/1131/1
