### ISSUE TITLE
Change Attachment icon to a paperclip

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2583]
> The attachment icon we use currently in the tlm in 7, is more commonly used to indicate a linkout, the paperclip icon is a more universally used and recognized attachment symbol.

![image](https://user-images.githubusercontent.com/37256050/206885400-ff0b1eb4-123f-446b-b489-92ef6b457fee.png)

**Requested By:** @beach53

**Comment by maxxxxxdlp** [comment]
Fixed in 6c2a5272b
