### ISSUE TITLE
Add code coverage reports

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#2595]
Modify the GitHub action that runs tests to generate a coverage report if the github action is run as part of a pull request.

Then, the generated coverage report should be attached to a pull request as a comment/table/webpage

Next step would be to add metrics for code coverage and have a blocker for when code falls below a certain test coverage percentage.

**Comment by maxxxxxdlp** [comment]
There might be other tools for this, but I used https://github.com/marketplace/actions/jest-coverage-report in the past
