### ISSUE TITLE
Query Builder's "+" button does not have background when in light mode

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2611]
The background of the"+" and negate buttons for the selected query builder field clash with the selected field background:

<img width="826" alt="Screenshot 2022-12-12 at 19 42 23" src="https://user-images.githubusercontent.com/40512816/207205350-4e4c2e53-5654-46d6-b48b-aa71fa1af76a.png">

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-6-release-announcement/1064/1
