### ISSUE TITLE
Evaluate "Accessibility Insights" checker for accessibility testing

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2616]
https://accessibilityinsights.io/downloads

**Comment by CarolineDenis** [comment]
@maxxxxxdlp related to: 
https://github.com/orgs/specify/projects/5/views/3?pane=issue&itemId=10299800
https://github.com/orgs/specify/projects/5/views/3?pane=issue&itemId=10299910
?

**Comment by maxxxxxdlp** [comment]
- Axe ([#966](https://github.com/specify/specify7/issues/966)) is a separate tool from https://accessibilityinsights.io

- Issues related to [#982](https://github.com/specify/specify7/issues/982) likely can't be detected automatically and need to be verified manually (or wait for chatgpt 4 ❤️ )

You would notice that there are several issues for analysing pages with accessiblity checker tools. The intention is to try several tools, see what works best and create a workflow where we regularly use a given set of tools (either add them as automated checkers in the `test.yml` or set a calendar reminder to do manual check once a month)
