### ISSUE TITLE
Add `[intert]` attr to `#root` when in modal

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2618]
New HTML attribute has been added for modal dialogs:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inert

It should be added to the `#root` element when in modal dialog.

Besides the improvements for screen readers, it would also reduce the need for focus management and (in some browsers), make `Cmd+F` ignore the content behind the dialog

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-12-release-announcement/1202/1
