### ISSUE TITLE
Test nested dialogs for accessibility compliance

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2619]
1. Open a modal dialog
2. From inside the modal dialog, click on a button that opens another dialog

Test cases where the 2nd dialog is modal and where 2nd dialog is nonmodal.

**Comment by CarolineDenis** [comment]
Tested all modal dialogs and nested modal/non-modal dialogs. 
=> no issue found 

@maxxxxxdlp we might close this one

**Comment by maxxxxxdlp** [comment]
Can confirm there are no issues (at least none that are detected by automated tools - there could be some issues that are detectable by using a screen reader only)
There are however some issues detected with forms. @CarolineDenis feel free to look into them if interested (https://github.com/specify/specify7/issues/966). I.e, the <QueryComboBox> does not properly set id attribute, thus the field is not linked to an associated label
