### ISSUE TITLE
Locality record without any changes is not saved 

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2623]
https://user-images.githubusercontent.com/37256050/207207705-d41a71a4-78d0-466c-b394-3c22406ba519.mov

Left is `edge`, right is `testability`.

May be a duplicate, only replicated on `testability`.

https://coldfish-testability.test.specifysystems.org/specify/view/locality/10578/

https://coldfish-edge.test.specifysystems.org/specify/view/locality/10578/

**Comment by maxxxxxdlp** [comment]
Duplicate of #2592 - same symptom caused by same bug
