### ISSUE TITLE
Importing jrxml file makes App Resource lose mime type

### ISSUE THREAD

**Issue by melton-jason** [specify/specify7#2639]
**Bug Description**

Importing a jrxml file into any App Resource (Form Definition files not affected) through the Load File button and subsequently saving makes the file lose its mimetype. The mimetype would have to then be manually set again through the edit button on the App Resource. 

While the resource does not have a mimetype, on a database level it appears to be an empty string. 
(In the example below, `CO Query` is the affected app resource)

![mimetype_issue](https://user-images.githubusercontent.com/64045831/207395968-cb9f990c-1463-4643-bdb6-0427d0c325d3.png)

Only occurs in testability (7.8.0). Did not occur in edge. 

**Environment Info**
OS: Windows 11
Browser: Chrome
Specify Version: testability

**Comment by grantfitzsimmons** [comment]
Similar to https://github.com/specify/specify7/issues/1947

**Comment by grantfitzsimmons** [comment]
Can verify, same behavior when I tried it

**Comment by melton-jason** [comment]
Some additional context: on `edge`, the mimetype was preserved to what the file type was previously before the import. 
(I can not verify this on a database level. This is simply what the UI shows).

**Comment by maxxxxxdlp** [comment]
https://github.com/specify/specify7/issues/1947 fixed this when importing an .xml file

This bug happens when uploading a file with .jrxml extension. Happens because Chrome doesn't know the mime type for files with this extension, and so it resets it - fixed

**Comment by melton-jason** [comment]
Fixed!
