### ISSUE TITLE
Fallback to default dataObjectFormatter not working correctly.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#264]
This presents as the following bug in Cornell Herps:

On Mon, Apr 25, 2016 at 3:57 PM Theresa Miller <support@specifysoftware.org> wrote:
It looks like the Locality search is set up to display something different in 7 than in 6.  In Specify 6, when you click the magnifying glass next to locality and do a search, the results come back with columns for the locality name, latitude1, and longitude1.  In Specify 7, all the results come back with "null".  When there are no results, it says, "No Results" or something to that effect, but when there are results, it comes back as null.

![image](https://cloud.githubusercontent.com/assets/287254/14895152/d73f96d0-0d3c-11e6-8c87-39b0f72dd065.png)

**Comment by garrettgirard** [comment]
Searching with the magnifying glass comes back with either "no hits" or the actual search results if there are hits.
