### ISSUE TITLE
Long URL in user prefs causes layout overflow

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2640]
Entering a long URL in user preferences causes the layout to overflow:

![Screenshot 2022-12-13 at 11 12 46](https://user-images.githubusercontent.com/40512816/207399241-19658ab6-3a85-4b21-b3ed-1103d19f25b0.png)

Instead, should force the text to wrap

**Comment by chanulee1** [comment]
Fixed.
