### ISSUE TITLE
Sp7 does not properly handle cases when lat1str is not set

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#2641]
See @melton-jason's comment in https://github.com/specify/specify7/issues/2592:

> The issue mostly pops up again when a new record is added to a record set and then deleted.
> 
> To (Consitently) Reproduce:
> 
> * Add and save a new locality to [recordset_123](https://coldfish-testability.test.specifysystems.org/specify/view/locality/82/?recordsetid=123)
> * Delete the new locality
> * Records that now suffer from the bug:
>   
>   * https://coldfish-testability.test.specifysystems.org/specify/view/locality/81/?recordsetid=123
>   * https://coldfish-testability.test.specifysystems.org/specify/view/locality/62/?recordsetid=123
>   * https://coldfish-testability.test.specifysystems.org/specify/view/locality/51/?recordsetid=123
>   * https://coldfish-testability.test.specifysystems.org/specify/view/locality/47/?recordsetid=123
>   * ... and others
> 
> NOTE:
> 
> * The method above _always_ seems to reproduce this bug. Otherwise, it was very inconsistent as to whether the bug would affect the records or not.
> * When navigating to the record set through a direct link, the bug _never_ occurred until new record was added and deleted, but rarely did when navigating though the `Record Sets` header.
> * When the record set is completely navigated away from and then reopened, the bug (sometimes) no longer affects the records.
> 
> I could not reproduce this bug on any other databases.

Looking at the code, here is the locality:

(note how `lat2text` is null, but `latitude2` is not)

```json
{
  "id": 81,
  "datum": "WGS84",
  "elevationaccuracy": null,
  "elevationmethod": "Marine",
  "gml": null,
  "guid": "9c988cb5-9d69-4cad-800c-3c14939fb068",
  "lat1text": "32.9216995° N",
  "lat2text": null,
  "latlongaccuracy": "0E-10",
  "latlongmethod": "GEOLocate",
  "latlongtype": "Line",
  "latitude1": "32.9216995000",
  "latitude2": "32.9059982300",
  "localityname": "Slope water, off southern California",
  "long1text": "117.2750015° W",
  "long2text": null,
  "longitude1": "-117.2750015000",
  "longitude2": "-117.2696990967",
  "maxelevation": null,
  "minelevation": null,
  "namedplace": null,
  "originalelevationunit": null,
  "originallatlongunit": 0,
  "relationtonamedplace": null,
  "remarks": null,
  "sgrstatus": null,
  "shortname": null,
  "srclatlongunit": 0,
  "text1": null,
  "text2": null,
  "text3": null,
  "text4": null,
  "text5": null,
  "timestampcreated": "1999-10-22T04:35:15",
  "timestampmodified": "2019-08-08T10:33:11",
  "uniqueidentifier": null,
  "verbatimelevation": null,
  "verbatimlatitude": null,
  "verbatimlongitude": null,
  "version": 3,
  "visibility": null,
  "yesno1": null,
  "yesno2": null,
  "yesno3": null,
  "yesno4": null,
  "yesno5": null,
  "createdbyagent": "/api/specify/agent/1986/",
  "discipline": "/api/specify/discipline/3/",
  "geography": "/api/specify/geography/1478/",
  "modifiedbyagent": "/api/specify/agent/1514/",
  "paleocontext": null,
  "visibilitysetby": null,
  "collectingevents": "/api/specify/collectingevent/?locality=81",
  "geocoorddetails": [],
  "latlonpolygons": [],
  "localityattachments": [],
  "localitycitations": [],
  "localitydetails": [],
  "localitynamealiass": [],
  "resource_uri": "/api/specify/locality/81/"
}
```

**Comment by emenslin** [comment]
Fixed
