### ISSUE TITLE
CollectionObject remarks not able to query

### ISSUE THREAD

**Issue by besi** [specify/specify7#265]
I am storing a lot of extra information in the "remarks" field of `collection object`. So it is crucial for me to be able to make queries like this (pseudo query language):

```
collection_object.remarks CONTAINS 'xyz'
```

However, when I query for that field, it is not shown. Is there a way to display that field for new queries?
![screen shot 2016-05-12 at 14 09 23](https://cloud.githubusercontent.com/assets/160412/15214122/93771b2a-184b-11e6-9a89-f00ecc02630e.png)

**Comment by benanhalt** [comment]
@besi, the *Remarks* field is probably "hidden" in the schema configuration. If you can connect to that database with Specify 6, there is a *Schema Configuration* tool under the *System* menu item. In there you can select the *collectionobject* table and *remarks* field and uncheck "Hide Field".

It is also possible to change it directly using SQL, if you don't have Specify 6 set up. If you need instructions for that, let me know.

**Comment by besi** [comment]
@benanhalt Thanks for your prompt reply. I did this and now it shows up in Specify6. However, in the web client it is not shown (see screenshot)

![screen shot 2016-05-12 at 21 19 09](https://cloud.githubusercontent.com/assets/160412/15227508/da68306e-1887-11e6-8cb3-a79ba0e17d79.png)

**Comment by tlammer** [comment]
?I believe that is the Determination Remarks field.  If you click to add a determination, does the field appear then?

________________________________

**Comment by benanhalt** [comment]
@besi The fields which appear on the forms are controlled by a separate mechanism, generally, the form XML definitions themselves. Is the remarks field appearing now in the query builder?

Also, some of the schema and view resources are cached by the browser for a short time. It may be necessary to bypass the browser cache when changing those. 

https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache

**Comment by besi** [comment]
The remarks do show up in the query builder but not on the collection object detail view. So now I can successfully query the remarks like I desired and I do see the matching remarks in the query result list. This is brilliant.

So if I understand correctly in order to edit the remarks I would have to update this XML configuration.

**Comment by benanhalt** [comment]
Yeah, I think if the remarks field is not appearing on the form, it probably needs to be added to the form definition. I hesitate a bit because I'm not sure how you are getting data into that field if it is not on the form... the forms in Specify 7 and Specify 6 should have the same fields (for a given user). As @tlammer pointed out, the remarks field in the screenshot appears to be the determinations remarks.
