### ISSUE TITLE
Support static values in query builder

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2665]
This would be extremely useful for reports and exports

Requested by CSIRO and many others

**Comment by maxxxxxdlp** [comment]
Potentially a duplicate of #1145

**Comment by grantfitzsimmons** [comment]
> So, just found a use case for static fields in queries.  In mapping our data model to the new GBIF unified model, there are a number of static fields that are not accommodated in our data model that it would be nice to be able to include in a query as static fields.  Any idea when this will be implemented?

From @acbentley

**Comment by grantfitzsimmons** [comment]
Looks like a duplicate of https://github.com/specify/specify7/issues/1145
