### ISSUE TITLE
Form errors should be reported as console errors rather than crashes

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2666]
This led to an issue where the forms for Madrid were inaccessible due to the `showLoansBtn` being present on the Collection Object form rather than the Preparations form.

**Comment by maxxxxxdlp** [comment]
To fix this: go though all the files in the `components/Form*` folders. In each place where you see `throw new Error()` or `crash()` or `error()`, replace with `softFail` or `console.error` unless it is a critical error.

Eventually, all of these errors would be presented in the UI (in the form editor)

**Comment by maxxxxxdlp** [comment]
Not yet ready for testing. But here is the testing protocol for this:

Putting plugins on unsupported forms
Putting commands on unsupported forms
Invalid weblink names
Invalid field names
Invalid formatter names
Any other weird forms you seen. @grantfitzsimmons you are probably an expert on this)

In general, error dialogs should not appear (unless you made a syntax error in XML - not much we can do about that). If you manage to trigger an error dialog, post a screenshot here.

Once the form editor is implemented, it will show all of these errors in a nice UI. For now, you have to look for them in the console.

Other nice changes:
- Even if specify can figure it out, it will emit a warning. Warnings would help you detect typos, or align with sp6 form behavior
- Errors and warnings now tell you which cell they came from
- Errors and warnings should not be duplicated as much anymore. I.e, a single instance of a mistake should result in a single warning. If you find cases where it's not the case, feel free to report them here.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-6-release-announcement/1064/1
