### ISSUE TITLE
Report limited exceptions in production

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2668]
Server errors are not reported at all. Back-end just says "500 error occurred"

The reasoning was that the error overlay when in debug mode includes variable values, and thus could include plaintext passwords

Still, a better compromise would be to display the exception itself but not the variable values. This would be of insane help when debugging errors submitted by users

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-4-announcement/999/1
