### ISSUE TITLE
Warn before leaving page with unsaved changes.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#267]

**Comment by benanhalt** [comment]
This applies to the workbench, forms and the query builder. This interacts with the browser history function (back and forward buttons), and that functionality should be tested.

**Comment by garrettgirard** [comment]
Most of the former actions that would cause a problem here seem to work now. However, if you click the Workbench button, then click "New", it's possible to create a new workbench, and in doing so leave the current workbench page without a warning and then losing any unsaved data that was entered.

**Comment by benanhalt** [comment]
The problem is that the new dataset dialog opens a form to name the dataset. When the form is saved, it clears the unload protect global. The Right Thing is probably to upgrade the unload protect global to a list of outstanding blockers.

**Comment by benanhalt** [comment]
For testing, please check that changes in forms, queries and workbench all produce warning before leaving the page, and that saving all changes removes the warning.

**Comment by garrettgirard** [comment]
You can leave the page without a warning when entering something new in the url in Chrome. This could also be an issue in other browsers, but I have yet to test anything other than Chrome and Firefox.

**Comment by tlammer** [comment]
The issue about being able to leave a page by modifying the url appears to be a focus issue, if you don't click out of the field to save, Specify doesn't think there is anything to save if you don't click out of the field
