### ISSUE TITLE
Have admin-level statistics for all collections

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2670]
This would show the total count of records in any table

Requested By: New Brunswick

**Comment by maxxxxxdlp** [comment]
@realVinayak is what you have already what is being asked for here or was more requested?

**Comment by realVinayak** [comment]
What they mean is all rows in a table from all collection for admins. Query Builder scopes it to collection, so it will have to be a backend statistic. Just for admins, it can be done. For normal users, there are edge cases that should be resolved - if user doesn't have access to a collection, should we skip the count from that collection?
