### ISSUE TITLE
Tree ranks not displaying after scroll until hover

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2689]
https://user-images.githubusercontent.com/37256050/208450421-67c804e3-68c8-4119-a44f-25e00be6d5a7.mov

https://montreal-edge.test.specifysystems.org/specify/tree/taxon/?conformation=%7E%7E1%7E2---

`spadmin` is the account

Browser: Chrome
OS: macOS Ventura

**Comment by maxxxxxdlp** [comment]
This is likely related to all the other tree viewer bugs in Chrome.
Duplicate of #2775
