### ISSUE TITLE
Pictures in Reports

### ISSUE THREAD

**Issue by jobdiogenes** [specify/specify7#269]
I my Reports to print pictures I use the following expression:

Ex:  new java.net.URL("http://specifyx.specifysoftware.org/wp-content/themes/specifytheme/images/logo2.png") 

In Specify6, works ok. But, in Specify7, I get errors. 

What I missed? 

Thanks

**Comment by benanhalt** [comment]
@jobdiogenes If you are using the develop branch, you can pull this fix. It should also apply cleanly to the master branch (only one line added), if you want to cherrypick it.

Thanks!

**Comment by benanhalt** [comment]
@garrettgirard You can verify this by editing an existing report that includes an image (I think one of the KU invoice reports has one), and replace the image expression with `new java.net.URL("http://specifyx.specifysoftware.org/wp-content/themes/specifytheme/images/logo2.png")`

**Comment by garrettgirard** [comment]
I edited KU Fish's loan invoice and replaced the image expression with the above expression, and it successfully generated with the Specify logo and no errors.
