### ISSUE TITLE
Record Merging overlay should have it's own URL

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2691]
It does not have a URL right now

**Comment by maxxxxxdlp** [comment]
This one is more tricky than it seems, so please test:
- Dismissing records from merging updates the URL
- When merging one by one, the URL updates
- In query builder:
  - Deleting a resource (from the "Preview" button) deletes it from the URL and query results
  - After dismissing all but one, the dialog closes
- In "Form Meta" menu ("Merge Records" button) on the Agent form:
  - Deleting a resource (from the "Preview" button) deletes it from the URL
  - After dismissing all but one, the dialog closes and you are redirected to the resource the remaining resource

**Comment by chanulee1** [comment]
- URL updated from dismissing records
- URL updates when merging one by one

Query builder:
- URL and query results updated from deleting record from "Preview" button
- Dialog closes after dismissing all but one record

"Form Meta" menu:
- Deleting resource from "Preview" button deletes it from URL
- Dismissing all but one redirects to remaining record
