### ISSUE TITLE
Make preview of merged record editable

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2692]
In Agent merging, when you open a preview of the final merged record, the preview is read-only.

**Comment by chanulee1** [comment]
Preview appears to be editable.


https://user-images.githubusercontent.com/103299204/216509683-5860698f-2856-4326-aa5e-3f04b44da59c.mp4

https://coldfish-agent-merging.test.specifysystems.org/specify/query/128/

**Comment by maxxxxxdlp** [comment]
Preview should be editable - works like expected
