### ISSUE TITLE
Creating a new form definition shows "New View Set Object"

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2694]
https://user-images.githubusercontent.com/37256050/208531935-9a3ba953-fd27-448b-8d86-df516407c8ca.mov

This should say "New form definition"

**Comment by maxxxxxdlp** [comment]
It's coming from the Schema Configuration

**Comment by grantfitzsimmons** [comment]
Either we can force rename that table or we can obscure it with a localized title for the dialog right?

**Comment by maxxxxxdlp** [comment]
Yes, we can change the dialog title
