### ISSUE TITLE
collectionrelonetoone plugin throws exception when there is no related object

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#27]
Can be seen in KU Fish Tissue on new collection object view:

Uncaught Error: can't fetch collection related to unpersisted resource collectionapi.js:160collectionapi.ToOne.collectionapi.Lazy.extend.fetch collectionapi.js:160UIPlugin.extend.gotRels collectionrelonetomanyplugin.js:48jQuery.Callbacks.fire jquery-1.7.2.js:1075jQuery.Callbacks.self.add jquery-1.7.2.js:1110UIPlugin.extend.gotRelType collectionrelonetomanyplugin.js:42jQuery.Callbacks.fire jquery-1.7.2.js:1075jQuery.Callbacks.self.fireWith jquery-1.7.2.js:1193jQuery.Callbacks.self.fire jquery-1.7.2.js:1200jQuery.Callbacks.fire jquery-1.7.2.js:1075jQuery.Callbacks.self.add jquery-1.7.2.js:1110jQuery.extend.Deferred.promise.then jquery-1.7.2.js:1244(anonymous function) jquery-1.7.2.js:1265jQuery.Callbacks.fire jquery-1.7.2.js:1075jQuery.Callbacks.self.fireWith jquery-1.7.2.js:1193(anonymous function) jquery-1.7.2.js:1267jQuery.Callbacks.fire jquery-1.7.2.js:1075jQuery.Callbacks.self.fireWith jquery-1.7.2.js:1193done jquery-1.7.2.js:7538jQuery.ajaxTransport.send.callback

**Comment by maxxxxxdlp** [comment]
Fixed in ef116336
