### ISSUE TITLE
Make GEOLocate plugin store uncertainty values.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#270]
In Sp6, the uncertainty goes into geocoorddetail.MaxUncertaintyEst. The polygon goes into geocoorddetail.errorpolygon.

**Comment by benanhalt** [comment]
Investigate what GEOLocate does with points sent with the request as described in the "complex params" portion of the docs: http://www.museum.tulane.edu/geolocate/images/webgeoreflight.png

**Comment by benanhalt** [comment]
Note: This fix does not create a Geo Cord Details instance if the Locality does not already have one.

**Comment by garrettgirard** [comment]
Values from GEOLocate were stored in the Geo Cord Details in Locality.
