### ISSUE TITLE
Loan Return Preparation Quantity Resolved doubling the Quantity Returned

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2701]
> Is it possible that there is strange behaviour when returning all items in a loan? We’re using version 7.7.5.
> 
> We have found that about 100 records have a number in QuantityResolved that is exactly double the number in QuantityReturned or in CountAmt.

I was able to recreate the issue exactly.

https://willemcatno-edge.test.specifysystems.org/specify/view/loan/2143588616/

<img width="892" alt="image" src="https://user-images.githubusercontent.com/37256050/209173102-2a044a89-cbc8-4fc9-9ea1-716ab3696f60.png">

1. I clicked on the **Return Loan** button then returned the entire number of preps associated with Catalogue Number `000206418`. 
2. When viewing the form, you can see that the Quantity Resolved is 16. When clicking on the **LrP** button, the Loan Return Preparations form shows Quantity Resolved to be 32.
3. I repeated the same process for Catalogue Number `000186470`. The Quantity Returned is 14 while Quantity Resolved is 28 in the **LrP** form.

It seems to literally double the number!

**Reported by:** Willem at SAIAB

**Comment by CarolineDenis** [comment]
@grantfitzsimmons , is this still an issue?

**Comment by emenslin** [comment]
Fixed
