### ISSUE TITLE
Cannot assign agent to user in new collection

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2705]
https://user-images.githubusercontent.com/37256050/209359049-56a6e28a-fba1-413c-868f-5c93449865ba.mov

I am unable to set even an agent I created in the Fish Voucher Collection on the `nbm_mnb` database on the Canadian cloud.

The save button reloads the page but the agent is not assigned.

**Comment by maxxxxxdlp** [comment]
@chanulee1 can you test if this has been fixed?

**Comment by chanulee1** [comment]
@maxxxxxdlp I was able to recreate this in `nbm_mnb_2_24_23` on branch `edge`.


https://user-images.githubusercontent.com/103299204/227647317-75823c85-8d69-4560-a42d-7381685028e8.mp4

**Comment by bronwyncombs** [comment]
@grantfitzsimmons it does appear to be fixed in `v7.9-dev`


https://github.com/specify/specify7/assets/135047322/b34ccb6b-c156-4636-83ae-637a77025f56
