### ISSUE TITLE
Home and End keys should jump to the first and last position in a field

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2708]
> Home and end keys do not work in QCBX's.  Trying to navigate to the beginning or end of a string using these keys does nothing.  You also cannot use them to highlight text.

In Specify 6, this is supported when working in a field. This is not a universally expected behavior to be fair, but it has been requested by @acbentley. 

In most browsers, it scrolls to the bottom or top of the page by default. Something to consider.

**Comment by maxxxxxdlp** [comment]
In browsers, this is done using up/down arrow keys, not home/end.
Also, consider that most keyboards today don't have home/end keys.
Reopen if further changes are needed
