### ISSUE TITLE
Add a indicator if user is offline

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2711]
If user temporary looses internet connection, any action in the UI that makes a network request would fail. It would be good to display a small banner or etc to tell the user that network is down.

Example code:
https://levelup.gitconnected.com/detecting-online-offline-in-javascript-1963c4fb81e1

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-6-release-announcement/1064/1
