### ISSUE TITLE
Show current geo ref point (if any) in GEOLocate plugin.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#272]
From Diego Barroso,U of M Herbarium, Great Lakes Invasives TCN via John Torgersen:

>  ...it would be convenient to be able to "push" the stored data (latitude, longitude, uncertainty radius, and ideally, polygon) to GEOLocate via the plug-in, in order to be able to use GEOLocate for viewing, verification and editing purposes. For example, if I were working within Specify, and I wanted to view or verify the georeferencing for a certain record, it would be great to have the GEOLocate plug-in display what is currently stored in the corresponding database fields (latitude, longitude, uncertainty radius, and polygon, where available). In this manner, I could ideally also be able to edit the georeferencing (for example, to make corrections) "on the fly" (live), and save the corrections again, without having to restartthe georeferencing process from scratch. If this "push" were not available, then I would have to manually copy and paste the fields into a different tool -- such as Google Earth -- to see what the georeferencing actually looks like on a satellite image, slowing down the workflow significantly.

**Comment by benanhalt** [comment]
GEOLocate plugin now shows the current georeferenced point, if any, from the Specify form. The current point will be last on the list of "possible locations found". The uncertainty value from the `GeoCoordDetails.maxUncertaintyEst` field is also supplied, if available, and presumed to be in meters. There is a `maxUncertaintyEstUnit` field, but I don't know if it is controlled, so doing unit conversions seems unwise. Also, values received from GEOLocate will be in meters and thus consistent between uses of the plugin. Any error polygon value in Specify is NOT relayed back to GEOLocate as the GEOLocate API doesn't allow for it.

**Comment by garrettgirard** [comment]
These fields are shown in the GEOLocate plugin, as well as the current georeferenced point and other possible locations.
