### ISSUE TITLE
Add a warning when clicking Delete All in `statspage`

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2731]
Add a warning when clicking Delete All in `statspage`

**Comment by realVinayak** [comment]
Fixed a while ago

**Comment by bronwyncombs** [comment]
Hi, could you add a warning or some kind of "Are you sure?" message to the `Delete Category` button please? It deletes immediately at this time

https://github.com/specify/specify7/assets/135047322/14230d05-c7e1-4c3d-88df-37473e6bf6cb

**Comment by realVinayak** [comment]
We had that dialog pop up before but it was voted to not have that at the end, so I removed it. Maybe discuss this with team again before reimplementing.

**Comment by grantfitzsimmons** [comment]
Add it back

**Comment by grantfitzsimmons** [comment]
Add it back
