### ISSUE TITLE
Sort by hidden/unhidden fields in schema config

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2738]
When editing the schema config, there are occassionally situations where I need to see all unhidden fields first. Having an option in the schema config menu to display those at the top would be nice. 

This would also make it easy to hide fields you don't want to be visible.

**Comment by CarolineDenis** [comment]
Addressed in PR #3516

**Comment by CarolineDenis** [comment]
Fixed and merged with PR https://github.com/specify/specify7/pull/3516
