### ISSUE TITLE
Print icon has a dark background in GeoMap

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2749]
<img width="80" alt="image" src="https://user-images.githubusercontent.com/37256050/210648658-325465df-1388-4f70-80cb-c398ae7907b7.png">

This is in the Workbench GeoMap feature!

https://herbrbge6802-statspage.test.specifysystems.org/specify/workbench/12/

**Comment by Rishav1707** [comment]
Which background colour do you want? @grantfitzsimmons

**Comment by grantfitzsimmons** [comment]
Hi @Rishav1707,
I imagine it should have the same background color as the full screen button and the zoom controls.

**Comment by Rishav1707** [comment]
> Hi @Rishav1707, I imagine it should have the same background color as the full screen button and the zoom controls.

Can you please help me to find where this file is? @grantfitzsimmons

**Comment by Rishav1707** [comment]
> Hi @Rishav1707, I imagine it should have the same background color as the full screen button and the zoom controls.

I will change it...

**Comment by maxxxxxdlp** [comment]
@Rishav1707 here is it: https://github.com/specify/specify7/blob/1f87bd8d0ac17e592e6c057060b4567519c5b4cc/specifyweb/frontend/js_src/lib/components/Leaflet/extend.ts#L79-L87

You can use the tailwind's `dark:` prefix to apply certain styles in dark mode only.

Feel free to open a branch, make the changes and open a pull request
