### ISSUE TITLE
Attachments scroll detection does not work correctly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2751]
When using a large screen (zoomed out) Specify messes up 

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/37256050/210653931-4bfea131-10b0-4a82-b81a-3ddcddfcafae.png">

**Comment by grantfitzsimmons** [comment]
Context:

> If you were zoomed out too much, it caused an issue where the scroll detection was not triggered so instead of loading more images it just loading infinitely

**Comment by maxxxxxdlp** [comment]
I did not fix it. It could be that we did not correctly interpret the cause of the bug
