### ISSUE TITLE
Introduce visual "PrepType" editor 

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2754]
In Specify 7, the best way to modify prep type options is to create a query on the `preptype` table, create a record set, then modify the options within the record set.

There should be an automatic way of doing this, potentially automatically creating an invisible record set of all `preptype` records and allowing the user to use this interface to modify the available options.

<img width="555" alt="image" src="https://user-images.githubusercontent.com/37256050/210919396-9a6bfd7c-06cb-4d93-a8db-19eb6c560ece.png">

**Comment by maxxxxxdlp** [comment]
Solving https://github.com/specify/specify7/issues/511#issuecomment-1478756653 would make solving this easy

**Comment by CarolineDenis** [comment]
@grantfitzsimmons 
Could you review this behavior? We are creating a simple quick query on prep type and then allow the user to browse and edit in forms without having to create a record set. 


https://user-images.githubusercontent.com/108160931/235948933-fd50e6ed-4738-494a-b379-1c6eacc550c9.mov

**Comment by grantfitzsimmons** [comment]
See my comment above. We should really solve this in the future. #3441 did improve the process, but it still is not intuitive for the average user (granted, it is now better than Specify 6).

**Comment by grantfitzsimmons** [comment]
> If the feature in readOnly is satisfying we can merge this PR.
> The add/edit feature will be implemented with https://github.com/specify/specify7/pull/3125

May be completely solved by #3125

**Comment by CarolineDenis** [comment]
> See my comment above. We should really solve this in the future. #3441 did improve the process, but it still is not intuitive for the average user (granted, it is now better than Specify 6).

this issue has been open after closing this one: https://github.com/specify/specify7/issues/3528

Do we need both? @grantfitzsimmons
