### ISSUE TITLE
Viewing record requires create permissions

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2757]
> I am trying to give someone guest access to collection objects in my collection (https://ichthyology.specify.ku.edu/specify/bycatalog/KUI/40318/) which previously used to work just fine but now they are getting the following error.  Any ideas?  Does this have to do with changes in the security?
> 
> ![image](https://user-images.githubusercontent.com/37256050/211108814-966a1b43-aaae-4d85-ba95-9abebee3c17d.png)
> 
> The bycatalog links were previously set up as a guest access permission
> In my guest access I am seeing that they have read access to all tables so why can they not see this?
> Why is this error saying they don't have permission to Create?
> I don't want them to create - just view

Can recreate. Can view records by building a query and viewing in forms from there.

**Reported By:** @acbentley 

Version: `v7.8.1`

**Comment by maxxxxxdlp** [comment]
This was fixed in 7.8.2 - https://github.com/specify/specify7/commit/4c833d3e7

Please confirm and close the issue
