### ISSUE TITLE
Exporting to CSV while querying within a record set exports full collection query output

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2761]
## CSIRO Reported:

> One of our users discovered that the csv export after querying a record set returns incorrect data. I tested this in two different instances and it appears that even though a record-set was used for the query, on csv export the entire database is queried and the corresponding result returned in the csv export file.
> 
> For example, I have a record set of 69 records which I limited to Contains ‘A 16’ in the catalognumber field – this results in 8 records. When I export this to csv, I get a file with 223 records – all of them having ‘A 16’ in the catalognumber field. Which is the same number of records I get when I run the query on the full dataset.

**Reported By:** Corinna P at CSIRO ([Asana Link](https://app.asana.com/0/1201972579963460/1203659671915887/f))

---

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/37256050/211231430-97a4c88b-4d76-4008-8aa5-be2f149f0936.png">

_I created a record set from the original output of [the query](https://sp7demofish.specifycloud.org/specify/query/56/) then ran the query on the newly created record set with "Kansas" changed to "River"._

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/37256050/211231368-6ac12c61-ce38-4f90-a528-a02aa87381d5.png">

Even though the query returned 274 results, after exporting the results to CSV, it exported the results as if I queried the entire database rather than the record set.

[query_results_2023-01-09T02_11_55.082573 (1).csv](https://github.com/specify/specify7/files/10369994/query_results_2023-01-09T02_11_55.082573.1.csv)

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-4-announcement/999/1
