### ISSUE TITLE
Maintain cell height for large text fields in grid view

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2765]
It looks inconsistent and unappealing compared to a standardized height in grid view.

Current behavior:
<img width="1328" alt="Screenshot 2023-01-08 at 11 59 24 PM" src="https://user-images.githubusercontent.com/37256050/211248469-2f1da146-9a43-45f3-abf3-729d6cce06b5.png">

Desired behavior:
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/37256050/211248446-74a61fb3-533c-4ea2-8135-db610c09859c.png">

**Comment by maxxxxxdlp** [comment]
I made it that way intentionally to utilize the screen estate most effectively, but you are right, it doesn't look as nice

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-5-release-announcement/1023/1
