### ISSUE TITLE
Record Sets allow deleting items in read-only mode

### ISSUE THREAD

**Issue by realVinayak** [specify/specify7#2768]
**Describe the bug**
In the record sets, the user is able to delete the items even if the page says the user is in read-only mode, this is a consequence of   #2767, and page not reloading

**To Reproduce**
1. Open a record set and form in different tabs and go into read-only mode from the form.
2. The record set says 'read-only' but since the page didn't reload, I'm able to delete items from the record set.

**Expected behavior**
The page should've been reloaded if I went into read-only mode from another tab. Having the page reload will fix this issue and issue #2767.

**Comment by maxxxxxdlp** [comment]
This is a consequence of a bug, not a separate bug. I.e, this could happen for anything, not just record sets (deleting queries, data sets, creating records, etc)
