### ISSUE TITLE
Use dark scrollbars in dark mode

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2772]
<img width="1543" alt="image" src="https://user-images.githubusercontent.com/37256050/211451552-4c206696-82f1-4cda-b1a6-c6017ac699f3.png">

https://stackoverflow.com/questions/65940522/how-do-i-switch-to-chromes-dark-scrollbar-like-github-does

**Comment by maxxxxxdlp** [comment]
Need to add `color-scheme: dark only;` to <body> when in dark mode
