### ISSUE TITLE
New Record Set form should only show name

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2782]
<img width="625" alt="image" src="https://user-images.githubusercontent.com/37256050/211838962-ec8881d6-dbc6-4e50-adc3-86060ac7af2a.png">

I know it is based on which fields are hidden/unhidden, but this should _only_ ever show the **Name**. There isn't really a valid use case in the "new" dialog for anything else to display.

Maybe when navigating directly to the record set form this can display, but not in the new dialog

https://kuvertpaleo11123-edge.test.specifysystems.org/specify/overlay/record-sets/

**Comment by maxxxxxdlp** [comment]
@melton-jason or @CarolineDenis whoever gets to this issue first.

Take a look at how this problem was solved in the dialog for creating new App Resources and do the same here

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-9-release-announcement/1131/1
