### ISSUE TITLE
`ProtectedError` when deleting a resource through the deletion blocker when deleting a user

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2783]
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/37256050/211844347-2222542e-d75b-403c-a7b4-b23111957d3f.png">

**Steps:**

1. Go to this user account:
    https://kuvertpaleo11123-edge.test.specifysystems.org/specify/security/user/10/
2. Go to **Delete**
3. See that the deletion is blocked. Click on the associated record.
     <img width="670" alt="image" src="https://user-images.githubusercontent.com/37256050/211844512-eb74fe52-802e-4e1b-93a8-7b6ccf60e2e8.png">
4. Click on **Delete** again
    <img width="547" alt="image" src="https://user-images.githubusercontent.com/37256050/211844578-4bf3a0a8-e7fe-435c-a0d0-66a5bfede44c.png">
5. See error.
     <img width="1443" alt="image" src="https://user-images.githubusercontent.com/37256050/211844646-177bdfa1-a8d1-4cba-b933-94d8985312f2.png">

```
ProtectedError at /api/specify/specifyuser/10/
("Cannot delete some instances of model 'Specifyuser' because they are referenced through a protected foreign key: 'Spquery.specifyuser'", <QuerySet [<Spquery: Spquery object (39)>]>)
```

[Specify 7 Crash Report - 2023-01-11T15_21_25.799Z.txt](https://github.com/specify/specify7/files/10393717/Specify.7.Crash.Report.-.2023-01-11T15_21_25.799Z.txt)

**Comment by grantfitzsimmons** [comment]
So there were some layers to this issue–

When deleting a record that was blocking deletion, it would allow you to delete the record, and once that was done, it would immediately ask you whether you want to delete the user.

If you tried to delete the user and there was _another_ deletion blocker that was not visible initially, it would throw a 500 error.

Once you carefully deleted all blocking records and canceled the user delete in the subsequent dialog, you could try to delete the user once and for all.

Of course, once the blockers were removed, there is a new error:
https://github.com/specify/specify7/issues/2784

**Comment by emenslin** [comment]
Fixed
