### ISSUE TITLE
Saving a blank CO record gives 500 error (in debug)

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2786]
https://kuvertpaleo11123-edge.test.specifysystems.org/specify/view/collectionobject/new/

Trying to save a blank CO record gives a 500 error.

User: `s753m969`

> Invalid response code 500. Expected one of 200, 201, and 409.
> 
> This error may indicate a misconfiguration or a bug in Specify. Please double check your configuration and report this issue.

**Comment by maxxxxxdlp** [comment]
Is this because auto-numbering is off?
or because auto numbering doesn't work for catalog numbers with alpha characters in them

as in fresh fish you can save a blank record without issues (numeric catalog number format)

**Comment by grantfitzsimmons** [comment]
> Same database and user, but it becomes clear that the catalog number C-##### is not unique.

Same issue here today.

<img width="1233" alt="image" src="https://github.com/specify/specify7/assets/37256050/0c8e50fc-44d1-4db8-b96d-08be4b5d4551">


[Specify 7 Crash Report - 2023-08-08T01 26 32.625Z.txt](https://github.com/specify/specify7/files/12286304/Specify.7.Crash.Report.-.2023-08-08T01.26.32.625Z.txt)

**Comment by grantfitzsimmons** [comment]
Here's the format:

```xml
  <format system="false" name="castFormat" class="edu.ku.brc.specify.datamodel.CollectionObject" fieldname="altCatalogNumber">
  <autonumber>edu.ku.brc.af.core.db.AutoNumberGeneric</autonumber>
    <field type="constant" size="1" value="C"/>
    <field type="separator" size="1" value="-"/>
    <field type="numeric" size="5" inc="true"/>
  </format>
  ```

It is not incrementing correctly. When I save a new CO record after removing the last CO with a `catalogNumber` of `C-#####`, it does not auto-increment. This is rather odd.

**Comment by grantfitzsimmons** [comment]
I had to assign the correct format in the schema config and at the collection table, but no luck.

**Comment by grantfitzsimmons** [comment]
Going to close this as an anomaly as there is no user reporting this issue. If this is rediscovered, please reopen and see the additional details I have provided above.
