### ISSUE TITLE
Attachments should show in a dialog preview 

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2787]
Clicking on an Attachment should open up a shadowbox with the attachment in a preview:
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/37256050/211894243-a35c3793-a05d-4fee-9447-1731663b059f.png">

Like this:

<img width="668" alt="image" src="https://user-images.githubusercontent.com/37256050/211894176-d80f38b5-5f20-4577-99f2-9f3e7663a3a5.png">

**Comment by chanulee1** [comment]
Opening the preview of some attachments leads to this effect. Unsure of what causes this.


https://user-images.githubusercontent.com/103299204/220202222-c86afd7a-b6ca-4b5c-a086-07a7de3ddf09.mp4


https://coldfish-issue-2787.test.specifysystems.org/specify/attachments/

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-7-release-announcement/1079/1
