### ISSUE TITLE
Hide loading dialog in crash report visualization

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2789]
<img width="2258" alt="image" src="https://user-images.githubusercontent.com/37256050/211955241-f96782c6-b542-463e-af5d-bba06033ad07.png">

[Specify 7 Crash Report - 2023-01-12T01 37 17.183Z.txt](https://github.com/specify/specify7/files/10397349/Specify.7.Crash.Report.-.2023-01-12T01.37.17.183Z.txt)

Often when we receive an error report since 7.8 we have been stuck looking at a loading screen rather than the error dialog they received.

Paste the contents into jsonviewer.stack.hu

**Comment by maxxxxxdlp** [comment]
You created the screenshot based on the crash report or did they send it to us?

From the crash report, I can recreate the following screenshot of the page:

<img width="1003" alt="Screenshot 2023-01-11 at 19 54 49" src="https://user-images.githubusercontent.com/40512816/211957288-a5ac5152-a5ce-4054-8ae2-5e6ce7684743.png">

**Comment by grantfitzsimmons** [comment]
I created this crash report, but @mc0822 and I have been receiving other crash reports with the same useless loading dialog in front of the content that is helpful for troubleshooting

**Comment by maxxxxxdlp** [comment]
For future reference, steps to recreate a screenshot:

1. Open any html webpage
2. Delete <head>
3. In the DevTools console pase `temp1 = ...` where `...` should be replaced with the contents of the crash report file.
4. Run `document.documentElement.outerHTML = temp1.pageHtml` in the console

**Comment by maxxxxxdlp** [comment]
Looks like business rule exception occurred, but was not handled well

@grantfitzsimmons if the error showed the loading page, how did you get a crash report?

```json
{
  "exception": "BusinessRuleException",
  "message": "Collectionobject must have unique catalognumber in collection",
  "data": {
    "table": "Collectionobject",
    "type": "UNIQUENESS",
    "fieldName": "catalognumber",
    "fieldData": [
      "catalognumber",
      "C-#####"
    ],
    "within": [
      "collection",
      6
    ],
    "conflicting": [
      134579
    ]
  },
  "traceback": "Traceback (most recent call last):\n  File \"/opt/specify7/ve/lib/python3.8/site-packages/django/core/handlers/base.py\", line 113, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/opt/specify7/specifyweb/specify/views.py\", line 30, in wrapped\n    return view(request, *args, **kwargs)\n  File \"/opt/specify7/ve/lib/python3.8/site-packages/django/views/decorators/cache.py\", line 31, in _cache_controlled\n    response = viewfunc(request, *args, **kw)\n  File \"/opt/specify7/specifyweb/specify/views.py\", line 63, in view\n    return dispatch_func(request, *args, **kwargs)\n  File \"/opt/specify7/specifyweb/specify/api.py\", line 206, in collection_dispatch\n    obj = post_resource(request.specify_collection,\n  File \"/usr/lib/python3.8/contextlib.py\", line 75, in inner\n    return func(*args, **kwds)\n  File \"/opt/specify7/specifyweb/specify/api.py\", line 304, in post_resource\n    obj = create_obj(collection, agent, name, data)\n  File \"/opt/specify7/specifyweb/specify/api.py\", line 387, in create_obj\n    autonumber_and_save(collection, agent.specifyuser, obj)\n  File \"/opt/specify7/specifyweb/specify/autonumbering.py\", line 28, in autonumber_and_save\n    obj.save()\n  File \"/opt/specify7/specifyweb/specify/build_models.py\", line 55, in save\n    return super(model, self).save(*args, **kwargs)\n  File \"/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/base.py\", line 740, in save\n    self.save_base(using=using, force_insert=force_insert,\n  File \"/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/base.py\", line 764, in save_base\n    pre_save.send(\n  File \"/opt/specify7/ve/lib/python3.8/site-packages/django/dispatch/dispatcher.py\", line 173, in send\n    return [\n  File \"/opt/specify7/ve/lib/python3.8/site-packages/django/dispatch/dispatcher.py\", line 174, in <listcomp>\n    (receiver, receiver(signal=self, sender=sender, **named))\n  File \"/opt/specify7/specifyweb/businessrules/orm_signal_handler.py\", line 15, in handler\n    rule(kwargs['instance'])\n  File \"/opt/specify7/specifyweb/businessrules/uniqueness_rules.py\", line 43, in check_unique\n    raise BusinessRuleException(\nspecifyweb.businessrules.exceptions.BusinessRuleException: ('Collectionobject must have unique catalognumber in collection', {'table': 'Collectionobject', 'type': 'UNIQUENESS', 'fieldName': 'catalognumber', 'fieldData': ('catalognumber', 'C-#####'), 'within': ('collection', 6), 'conflicting': [134579]})\n"
}
```

**Comment by grantfitzsimmons** [comment]
That's the trick– I downloaded the error message and it still shows the loading screen (which was not visible to me at the time I downloaded the message)

**Comment by grantfitzsimmons** [comment]
Maybe it ignores the current dialog and a loading dialog was hidden beneath the error

**Comment by maxxxxxdlp** [comment]
So if I understand correctly, the problem is that once you dismiss the error dialog, the loading dialog does not go away?

**Comment by grantfitzsimmons** [comment]
The loading dialog is never visible _within_ Specify itself. When someone shares an crash report with us it always obscures the snapshot with a loading dialog when we visualize the JSON file.

Interestingly, in the application, the loading dialog is not visible since it is likely behind the crash dialog. The crashes happen often when an action is taken, which typically causes a loading dialog to appear.

**Comment by grantfitzsimmons** [comment]
Ideally a crash report would download a JSON file with no loading dialogs present

**Comment by maxxxxxdlp** [comment]
Ah, I finally see what you mean. Sorry for being slow.

Can you just open the dev tools Elements tab and remove the dialog?

If this is about convenience, then I can try hiding all loading dialogs for a moment when taking a snapshot of the page.

**Comment by grantfitzsimmons** [comment]
It's convenience- Mandi is having trouble viewing the JSON output using the above tool since it now obscures many of the crucial pieces of info. I can walk her through using the browser console instead which might be the best path.

**Comment by maxxxxxdlp** [comment]
This would fall into a broader conversation about making crash reports more friendly to work with for QA people.
One possibility is to create a tool (either in specify 7 or external), that would format the crash report. That tool can then also handle the loading dialogs. If taken a step further, it can also point to possible causes of the issue (i.e, point you at errors in the logs.

**Comment by maxxxxxdlp** [comment]
Found an issue for it: #2183

**Comment by grantfitzsimmons** [comment]
Closing this as it is not too difficult for me to work around this. This was meant to be convenient for Mandi, but it is not a problem now.
