### ISSUE TITLE
Implement batch editing in query results interface

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#2792]

**Comment by maxxxxxdlp** [comment]
Also, review the Batch Editing github project for some use cases - https://github.com/specify/specify7/projects/15#card-87570424

Also, take a look at Specify 6 batch editor (we are aiming for something much better and a bit different here, but still good to be aware of prior art)

**Comment by maxxxxxdlp** [comment]
As a preliminary step, @melton-jason will take a look at the workbench code to see if it can be modified to enable (at least) limited batch editing capability by lifting the restriction on records from base table always being new records

This would likely accompany UI changes were user can enable an "Upload mode" or an "Editing mode" and maybe even how they want to resolve ambiguities related to edits made (i.e, delete, update reference, update source)

**Comment by grantfitzsimmons** [comment]
>However, are there also plans to have the option to “undo” “rollback” the batch editing?  (P.S. you can do this in Symbiota).

We need to make sure we include the ability to "undo" a batch edit in the interface

**Comment by grantfitzsimmons** [comment]
Closed in favor of https://github.com/specify/specify7/issues/3136 based on direction
