### ISSUE TITLE
Import / export reports as jrxml.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#280]

**Comment by benanhalt** [comment]
When logged in as an admin user, clicking the pencil icon to the right of a report/label name opens a dialog with the report's JRXML definition. The XML can be copypastaed between the dialog and Jasper Report Studio or edited in place by the brave.

**Comment by garrettgirard** [comment]
This seems to work very well. I tried editing Emory's herbarium jar label using Jaspersoft Studio and added a couple features that are available in Jaspersoft Studio but not iReport. After doing so, I copied the source XML and pasted it into the report's JRXML definition dialogue in Sp7. The new features appeared as expected, as well as the other changes I made to the report.
