### ISSUE TITLE
Make it clear that you are granting permissions to the shared pages rather than the personal user statistics

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2800]
Currently the role says Preferences -> Statistics, but it means _shared_ statistics, so clarify that detail.

**Comment by maxxxxxdlp** [comment]
Looks like it is now renamed to `Edit Shared` - https://github.com/specify/specify7/pull/2247/files#diff-c886c3f183627a2cf7b5709565483bc6ced9efd6765256cc955faa33c689c770R95
