### ISSUE TITLE
Fields often have black bars within the text area (Firefox)

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2804]
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/37256050/212184330-90ec6899-443a-4b51-84ea-49a2e53a684d.png">

It disappears after the field is selected. It shows up at random– it may be a Firefox bug but I have yet to encounter this in any other application.

**Comment by grantfitzsimmons** [comment]
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/37256050/212189574-a4f7389f-3587-4d9b-9f50-c3cbb2bee71a.png">

This artifacting is very common

**Comment by grantfitzsimmons** [comment]
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/37256050/224737615-74e3497a-66cd-46b5-a12f-fe22d6fe26b7.png">

Every day

**Comment by grantfitzsimmons** [comment]
Have not encountered this recently with Firefox. Looks to be resolved 😊

**Comment by maxxxxxdlp** [comment]
browser bugs!
