### ISSUE TITLE
Pick list not allowing the selection of other items with the same first character

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2805]
https://user-images.githubusercontent.com/37256050/212190227-a39e1b78-7523-4ada-9701-aec381234542.mov

https://herbrbge6802-xml-validation.test.specifysystems.org/specify/view/collectionobject/1178963/

_This can be recreated in `edge`_

See the "Filing Region" (`text4`) pick list in the Collecting Event table.

When you select an item such as `6E - New Guinea` and try to select another item that starts with `6`, you will be unable to select it. You need to first select an item without a 6 at the start and then select the item you wish to choose.

**Reported By:** Robyn at RBGE

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-5-release-announcement/1023/1
