### ISSUE TITLE
Serialize Django QuerySet for error responses

### ISSUE THREAD

**Issue by melton-jason** [specify/specify7#2808]
> > Trying to delete a schema mapping field results in this error:
> > ```
> > Object of type QuerySet is not JSON serializable
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="1210" src="https://user-images.githubusercontent.com/37256050/211956975-1e27dcb1-260d-4b8f-adc9-c7fc16dbbcb0.png">
> > _Just an observation. Not tremendously helpful or informative, just reporting._
> 
> There are some cases where something in the original error is not Json Serializable and thus can not be directly sent as a Json response. To get around this, I manually catch the error that is thrown when trying to serialize the object and serialize that instead to json and sent it to the frontend. Based on the traceback, I still know you were trying to delete something.
> 
> I can try and include more information for these errors specifically if we need, but regardless the information we send will probably be limited.
> 
> Actually, I can write up our own way of serializing specifically django's QuerySet. We can not anticipate every object, but QuerySet might appear often so it may be worth the effort

- https://github.com/specify/specify7/pull/2702#issuecomment-1379720672

Currently, when the backend encounters something in an Exception that can not be serialized to json, it catches the thrown TypeError and sends that instead. While this is still better than a `500 error`,  it is far from helpful to any user who does not know how to read the traceback. 

While we can not anticipate every object that is not json serializable, having a representation for Django's representation of a query ([QuerySet](https://docs.djangoproject.com/en/2.2/ref/models/querysets/#django.db.models.query.QuerySet)), would be helpful.

**Comment by maxxxxxdlp** [comment]
A quick question, if I click on "Download Error Message", did you test how the error that has undergone formatting gets included?

Is it included as formatted HTML, or as raw response, or as some sort of JSON structure?

**Comment by melton-jason** [comment]
I have not tried building the error message in the vizualizer, but it stores the whole backend response in the JSON structure it sends to the frontend

**Comment by melton-jason** [comment]
Here is an example crash report, using the same error (pictured below) as in https://github.com/specify/specify7/issues/2810#issue-1531681746

> ![spTreeError](https://user-images.githubusercontent.com/64045831/212233963-03c1b3d6-c760-4984-a2ed-148e4792ff57.png)


[Specify 7 Crash Report - 2023-01-13T05_09_02.748Z.txt](https://github.com/specify/specify7/files/10408370/Specify.7.Crash.Report.-.2023-01-13T05_09_02.748Z.txt)

**Comment by melton-jason** [comment]
At a lower priority (i.e. after this issue is complete), objects representing the Specify datamodel could be serialized as well. I am not sure how often these errors would come up, but it would be nice to ensure we _could_ handle them; just in case. 

(Note: this screenshot is with debug mode on)
![typeErrprStorage](https://user-images.githubusercontent.com/64045831/212408170-3fd3d9c7-5f47-4058-9b03-1985087976c8.png)

**Comment by melton-jason** [comment]
> ![image](https://user-images.githubusercontent.com/37256050/166522900-d5964426-d528-4721-87df-5becc6510735.png)

- From https://github.com/specify/specify7/issues/1385#issue-1224492744

This would be exceptionally useful for common Django errors, such as the attached Protected Error 

For future reference, see the [Django documentation](https://docs.djangoproject.com/en/2.2/ref/exceptions/#database-exceptions) for a list of possible Database Exceptions
