### ISSUE TITLE
Create new reports from queries.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#281]

**Comment by benanhalt** [comment]
It is in the branch https://github.com/specify/specify7/tree/appresource-improvements

**Comment by maxxxxxdlp** [comment]
I am able to create reports and labels from a query, but while query returns some results, there are no records shown on the label or report

https://user-images.githubusercontent.com/40512816/125761473-1a82d0e3-f172-4d63-bcdd-47bb5d8a5850.mp4

**Comment by benanhalt** [comment]
It doesn't generate anything because the report actually has to be defined using Jasper studio. The idea is to download this template XML and import it in Jasper Studio to design the report, and then load it back into Specify 7.
