### ISSUE TITLE
Support WorldWind in the browser

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2812]
This is a plugin supported in Specify 6 but they have a web version available:
https://worldwind.arc.nasa.gov/web/
https://worldwind.arc.nasa.gov/web/docs/

We'll need to see if they are hosting and and we can use their API. If not, supporting this seems not feasible.

This looks to be the version used in Specify 6:
https://worldwind.arc.nasa.gov/java/

**Comment by maxxxxxdlp** [comment]
According to Jim this is a low priority unless integrating with WorldWind is going to be as easy as embedding an iframe

**Comment by grantfitzsimmons** [comment]
Closing unless a user requests this ability. There are more important integrations to consider, such as #3559
