### ISSUE TITLE
Printing only allows printing first page

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2820]
For any page that has a scroll bar (forms, data model viewer), when you press `Cmd+P` to print it, the print dialog only presents the first page - everything below the scroll bar is hidden.

Need to change the layout of the page when printing to use the <body> scroll bar.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-6-release-announcement/1064/1
