### ISSUE TITLE
Going to the overlay from a new CO form causes the URL bar to flicker

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2824]
https://user-images.githubusercontent.com/37256050/212752633-fe6c8742-06b3-4036-9273-7c8513b59c43.mov

**Comment by maxxxxxdlp** [comment]
This is caused by unload protect.
Will be fixed once react-router officially supports it (will be fixed on the `xml-validation` branch first and eventually on others once merged)
