### ISSUE TITLE
Creating a new country in the Geography tree fails

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2828]
Creating a new country in the Geography tree fails:

<img width="950" alt="Screenshot 2023-01-16 at 18 51 35" src="https://user-images.githubusercontent.com/40512816/212786618-92b9131c-e964-480b-9eac-da0f2cf5b5eb.png">

[Specify 7 Crash Report - 2023-01-17T00_51_40.769Z.txt](https://github.com/specify/specify7/files/10430188/Specify.7.Crash.Report.-.2023-01-17T00_51_40.769Z.txt)

Not able to replicate on https://sp7demofish.specifycloud.org/
Able to replicate consistently in a local copy of VIMS database (Invertebrate Collection) on the `issue-1848` branch

Does not happen for the Taxon tree. Happens for Geography.

Request:

```js
fetch("http://localhost/api/specify/geography/", {
  "headers": {
    "accept": "application/json",
    "accept-language": "en-US,en;q=0.9,uk;q=0.8",
    "content-type": "application/json",
    "sec-ch-ua": "\"Chromium\";v=\"110\", \"Not A(Brand\";v=\"24\", \"Google Chrome\";v=\"110\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "x-csrftoken": "HQIFxw0iYRKPvPyaSoMwNX8n8mqCsteMwIfYrKNp3B5vMk4IOcInX8j5acaCeoUg"
  },
  "referrer": "http://localhost/specify/tree/geography/?conformation=%7E%7E1-%7E42664%7E42667---",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"isaccepted\":true,\"parent\":\"/api/specify/geography/42667/\",\"remarks\":null,\"geographycode\":null,\"name\":\"Test\",\"definitionitem\":\"/api/specify/geographytreedefitem/13/\",\"fullname\":\"Test\"}",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});
```

**Comment by grantfitzsimmons** [comment]
> <img width="1147" alt="image" src="https://user-images.githubusercontent.com/37256050/212953597-1ca1d19e-ce16-4a40-aac9-e8e6896dacdc.png">
> 
> For disambiguating the agent that failed above, I had success & no issues.
> 
> https://herbrbge6802-issue-1848.test.specifysystems.org/specify/workbench/41/
> 
> For disambiguating a tree item, also no problems, until I attempted to upload. This might be beyond the scope of this PR, but the API to create a RS is triggered even when the upload failed
> 
> https://user-images.githubusercontent.com/37256050/212956800-25afdc6d-5fa7-4d8d-99bd-83848b726beb.mp4
> 
> This seems to be a somewhat major issue. The error was particularly not useful, seeing as it reported the following:
> 
> ```
> OperationalError(1065, 'Query was empty')"
> ```

**Comment by grantfitzsimmons** [comment]
[specify7-log.txt](https://github.com/specify/specify7/files/10440860/specify7-log.txt)

Can consistently recreate this on `edge` but cannot recreate in `v7.8.3` on `vimsfish` and `herb_rbge_6802`. This applies to all tree records from what I can tell.

**Comment by grantfitzsimmons** [comment]
I discovered that when line 527 in `tree_extras.py` was removed, this issue no longer occurred.

`and t.acceptedid is null” if table == ‘taxon’ else “”`

![image](https://user-images.githubusercontent.com/37256050/213059644-264a7999-d297-4973-962a-03c025424134.png)

> That 'fix' was to ignore synoymized nodes when doing tree checks. If every other tree has acceptedid in their table, you can just remove the if table == taxon else ""part
