### ISSUE TITLE
Inconsistent ordering of collections without a collection type

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2831]
When ordering collections by collection type, a collection without a collection type (KU Fish Teaching Collection) seems to be arbitrarily slotted into the middle of the collection list. When the order is reversed, this collection is at the top of the list.

Normal
![image](https://user-images.githubusercontent.com/103299204/212817976-e7bfd4d4-d1af-439d-a79f-6e4ded681072.png)

Reverse
![image](https://user-images.githubusercontent.com/103299204/212818562-4ec761ee-f363-40d5-81b5-7b1dbded2cb7.png)

https://kufishnotests-edge.test.specifysystems.org/specify/query/129/

**Comment by maxxxxxdlp** [comment]
Can be fixed by adding a secondary sorrt by collection name

**Comment by maxxxxxdlp** [comment]
Should replace usages of `sortFunction` with `multiSortFunction` in the code to facilitate fixing this

**Comment by emenslin** [comment]
Fixed
