### ISSUE TITLE
Changes made in user prefs are saved without clicking 'save'

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2832]
Changes made in user prefs are saved regardless of whether the save button is pressed.

https://user-images.githubusercontent.com/103299204/212819720-bccce5a7-f065-4bd7-abc8-b9d7f14ae32f.mp4

https://kufishnotests-edge.test.specifysystems.org/specify/user-preferences/#preferences-1-general

**Comment by maxxxxxdlp** [comment]
That's intentional. All settings are saved automatically within 5 seconds of making them.
Is there a problem with this?
The save button is there mostly for emotional purposes 😄

**Comment by melton-jason** [comment]
An emotional support button... Maybe we need more of those in Specify

**Comment by chanulee1** [comment]
My mistake! I wasn't aware of its emotional support function. Closing this issue.
