### ISSUE TITLE
`side-menu`: Better tooltips on collapsed navigation items

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2838]
<img width="891" alt="image" src="https://user-images.githubusercontent.com/37256050/213210336-36757979-aabc-40b1-890e-91fea3d30cfe.png">

https://flowbite.com/docs/components/tooltips/#placement

This could potentially eliminate the need for an expanded sidebar.

**Comment by maxxxxxdlp** [comment]
Note, the above library has poor accessibility.
Doesn't mean we can find and similar alternative (https://www.npmjs.com/package/react-accessible-tooltip)

Though really, I was just waiting for browsers to support this natively.

**Comment by maxxxxxdlp** [comment]
Do you want to use this tooltip library in all places or only in some places?
I.e, do we need ti when hovering over field label on the form?

**Comment by grantfitzsimmons** [comment]
I think we should use this everywhere!
