### ISSUE TITLE
`side-menu`: Dialog for collection switcher

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2839]
Rather than expanding the side menu, it should show a dialog with all collections to choose from.

**Comment by maxxxxxdlp** [comment]
so a dialog would only be triggerable when the menu is collapsed?

**Comment by grantfitzsimmons** [comment]
The more I think about it I'm not sure we need an expanded and collapsed option. If we make the collapsed menu easy to use and simple to learn, should we even engineer both options?

**Comment by maxxxxxdlp** [comment]
One benefit is that when menu is expanded, the content of the page does not begin at the very edge of the screen, but is a bit closer to the center - not sure how important that is though

**Comment by chanulee1** [comment]
Separate dialog for collection switcher.
