### ISSUE TITLE
`side-menu`: Simple search should be opened in a dialog in collapsed view

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2840]
Simple search should be opened in a dialog rather than occupying the entire screen in the collapsed view

**Comment by maxxxxxdlp** [comment]
and also display the results in a dialog?

**Comment by grantfitzsimmons** [comment]
I think so. Do you have any concerns about usability?

**Comment by maxxxxxdlp** [comment]
I have concerns about priorities 😄

**Comment by grantfitzsimmons** [comment]
Don't prioritize based on my issue recency 😂

**Comment by maxxxxxdlp** [comment]
Do you think this would look better as a dialog?

<img width="1800" alt="Screenshot 2023-02-02 at 19 39 33" src="https://user-images.githubusercontent.com/40512816/216490795-51f211d1-1c4b-4c3a-b16e-55e3f9314d11.png">

So far we have only been using dialogs when there is little content, or we don't want to remove the page the user was one when they open a new action (i.e, a user tools dialog).

The search results page has a lot of content (with each results section potentially having it's own scroll bar), and does not have a particular need to retain the content the user was on before they went to express search

**Comment by maxxxxxdlp** [comment]
Fixed in a8899a906 by moving the search query into a dialog

**Comment by chanulee1** [comment]
Simple search in a separate dialog. Should there be different behavior when the side menu is expanded vs collapsed?

**Comment by chanulee1** [comment]
Also, there can be a discrepancy between the dialog search bar and the search bar in the results page. Problem?

https://user-images.githubusercontent.com/103299204/216748233-77d20edb-941a-4c79-91d9-025f4e5c3112.mp4

**Comment by maxxxxxdlp** [comment]
> Simple search in a separate dialog. Should there be different behavior when the side menu is expanded vs collapsed?

We decided at the end to display a dialog in both cases, but only show the search field in the dialog, not the search results.

> Also, there can be a discrepancy between the dialog search bar and the search bar in the results page. Problem?

Good catch! Fixed. The bug is only reproducible when you are already on the search results page, and open the search dialog to do another search (rather than using the search field at the top of the page)

**Comment by chanulee1** [comment]
Fixed.
