### ISSUE TITLE
Migrate to HeroIcons v2

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2842]
We are currently on v1 solid.
v2 has come out.

Need to migrate to v2 20px (or 24px) solid
See changelog: https://github.com/tailwindlabs/heroicons/releases/tag/v2.0.0

List of icons - https://heroicons.dev/?iconset=v2-24-solid&size=24

No rush, but new icons would only be added to the `v2` version

**Comment by grantfitzsimmons** [comment]
It was decided it looks worse in #3100. Hopefully V3 is better.

**Comment by maxpatiiuk** [comment]
Not exactly a v3, but there is now a set of icons available in even lower level of detail - https://tailwindcss.com/blog/heroicons-micro?utm_source=tldrdesign (16x16)

Those may look nice
For reference, under default font settings, icons in specify are displayed as 24px x 24px
