### ISSUE TITLE
Ability to customize query export delimiter

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2849]
See https://discourse.specifysoftware.org/t/export-as-csv-with-alternative-delimiter-e-g-semicolon/1003

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/export-as-csv-with-alternative-delimiter-e-g-semicolon/1003/15

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-7-release-announcement/1079/1
