### ISSUE TITLE
Improve the delete taxon node confirmation dialog

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2854]
> **UX FEATURE REQUEST:** Improve messaging in the "Delete a taxon node confirmation dialog":
> 
> It might improve the UX to list in the confirmation dialog the name of the Taxon node that is about to be deleted so the user can identify they did not click delete on the wrong node.
> The only indicator in the image below is that "test (0)" has an outline. I believe it is possible that this dialog might overlap other nodes, so the user would have to move the dialog around just to see. Putting the name in the dialog box would be a clearer way to confirm.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37256050/213612826-02c5203a-3fbc-48cd-ab61-a87c15a8f0f5.png">

Moving the dialog box around:

<img width="1552" alt="image2" src="https://user-images.githubusercontent.com/37256050/213612856-351a0ed1-07ef-4331-b4fa-3d2e54eb1b58.png">

**Requested By:** Matthew Cruz at The University of Michigan

**Comment by maxxxxxdlp** [comment]
Can add a formatted string of current resource to this dialog.

Though note that this is a generic resource delete dialog that is used all over specify so this change would affect all such dialogs (which is probably fine)

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-6-release-announcement/1064/1
