### ISSUE TITLE
Enhance the data model viewer

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2855]
- [x] https://github.com/specify/specify7/issues/1831
- [x] #2080
- [x] Add an explicit way to see which table a resource is scoped to (maybe allow to filter on these)
- [x] Better differentiate dependent and independent resources (maybe allow to filter on these)
- [x] Ability to sort fields/relationships by clicking on the table header
- [ ] For child tables, add a link to the parent table. This must be done on the `agent-merging` branch as that added the logic for finding parent tables - in `./components/Merging/Usages.tsx` -> `parentTables()`

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-5-release-announcement/1023/1

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-6-release-announcement/1064/1
