### ISSUE TITLE
Dark mode not working for fields in Firefox

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2856]
<img width="1643" alt="Screenshot 2023-01-20 at 8 09 04 AM" src="https://user-images.githubusercontent.com/37256050/213727071-74df2e87-229d-4c04-944d-d8ac09abd90a.png">

**Comment by maxxxxxdlp** [comment]
Can you replicate this on the `issue-2368` branch?

**Comment by grantfitzsimmons** [comment]
It is not. Is it solved by #2368?

**Comment by grantfitzsimmons** [comment]
Seems to be solved.

**Comment by maxxxxxdlp** [comment]
Is there a commit that fixed the issue? Or did the issue resole by itself?

**Comment by grantfitzsimmons** [comment]
I tried it on #2368 and didn't have an issue. Now I can't recreate the problem – who knows!
