### ISSUE TITLE
Allow conditionally rendering form fields

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2860]
`<panel>` element should be extended to allow rendering form conditionally (display some fields based on the value in a different field)

[@melton-jason](https://github.com/melton-jason) Can you double-check what the form system in sp6 does if it encounters a panel cell with more than one <rows> tag?
Example of a panel cell: https://github.com/specify/specify7/wiki/Form-System#panel
Looking at the code, it looks like it would take the first one, but would be good to double-check.

**Comment by maxxxxxdlp** [comment]
@melton-jason Can you double-check what the form system in sp6 does if it encounters a panel cell with more than one `<rows>` tag?

Example of a panel cell: https://github.com/specify/specify7/wiki/Form-System#panel

Looking at the code, it looks like it would take the first one, but would be good to double-check.

**Comment by melton-jason** [comment]
@maxxxxxdlp 
Yes, it looks like it should always take the first`<rows>`. 
I could only find two instances in the code where Specify 6 uses panels like this. 

[ViewLoader.java#L1001-L1019](https://github.com/specify/specify6/blob/8c853f91b76ff7633c8318aff5008e1822ca10a0/src/edu/ku/brc/af/ui/forms/persist/ViewLoader.java#L1001-L1019) which loads the data from the xml and constructs Specify-Java objects called [ViewSet](https://github.com/specify/specify6/blob/master/src/edu/ku/brc/af/ui/forms/persist/ViewSet.java).


[ViewFactory.java#L2065-L2107](https://github.com/specify/specify6/blob/8c853f91b76ff7633c8318aff5008e1822ca10a0/src/edu/ku/brc/af/ui/forms/ViewFactory.java#L2065-L2107) which is in charge of taking constructed ViewSets and turning them into UI components (from the Jgoodies library). 

In both cases, it looks like it will always return the first `<rows>` element. ViewLoader uses the [selectSingleNode](https://dom4j.github.io/javadoc/2.0.1/org/dom4j/Node.html#selectSingleNode-java.lang.String-) method which does not have great documentation, but seems like it should only return the topmost xml attribute with a given name.

**Comment by maxxxxxdlp** [comment]
Closing this as completed as per https://github.com/specify/specify7/pull/2863#pullrequestreview-1376561064
