### ISSUE TITLE
Subviews not displaying correctly in 'subform' view

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2861]
Similar to #2412 but in 'subform' view instead of 'grid' view. Happens for all cases documented in #2412.

Examples:

`collections`:
![image](https://user-images.githubusercontent.com/103299204/213811485-832c5549-2769-47b2-875a-2bd67cae9d46.png)

https://coldfish-edge.test.specifysystems.org/specify/view/division/2/

`collectors`:
![image](https://user-images.githubusercontent.com/103299204/213811551-8ae05833-9858-4614-a912-d0c85772c2a9.png)

https://coldfish-edge.test.specifysystems.org/specify/view/collectingevent/1/

branch: `edge`

**Comment by emenslin** [comment]
Fixed
