### ISSUE TITLE
Old table icons are used in the WorkBench

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2864]
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/37256050/213843770-51d0a127-68ea-4f55-ab78-9113a6895de8.png">

**Comment by maxxxxxdlp** [comment]
Workbench is in a difference century

**Comment by CarolineDenis** [comment]
This will be fixed once workbench component is refactored with React.

**Comment by maxxxxxdlp** [comment]
Context:
It can be fixed now, but it would be buggy. Easier to fix it once WB is using React (while it is not in React, it's hard to use react components in it)

**Comment by emenslin** [comment]
Can recreate in edge (7.9.6)
