### ISSUE TITLE
`origFilename` not displaying in 7

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2873]
> Just noticed a discrepancy in the way Specify 7 and Specify 6 are displaying attachment info.  Note the top field.  Is this intentional or a bug?

![image](https://user-images.githubusercontent.com/37256050/214329622-a6b46f19-447d-49aa-bad3-0d76e1024824.png)

![image](https://user-images.githubusercontent.com/37256050/214329638-4725904d-a73d-4965-94a7-4d0635bd7865.png)

**Comment by maxxxxxdlp** [comment]
Looks like sp6 might have special treatment for the "file" input type. In sp7, it just renders the input as disabled - we will need to investigate it deeper to see what sp6 does.

Alternatively, this might be caused by https://github.com/specify/specify7/issues/415

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/214396757-c32ccd17-42c8-49c2-b268-9c8c31c3a14c.png)
![image](https://user-images.githubusercontent.com/37256050/214396762-508ee0ac-c00b-4288-a98b-4390cbe1f01c.png)

**Reported By:** Gothenburg

**Comment by grantfitzsimmons** [comment]
Ideally we would solve this with the PR #2961
