### ISSUE TITLE
Non-conflicting fields that are hidden are not merged

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2879]
<img width="1651" alt="image" src="https://user-images.githubusercontent.com/37256050/214610937-fb6a9b77-85e9-4aae-a8f2-0d70b98a7f62.png">

The name is not being displayed correctly because the Last Name is not in conflict

https://coldfish-agent-merging.test.specifysystems.org/specify/query/125/

*Do not merge*

**Comment by grantfitzsimmons** [comment]
<img width="1663" alt="image" src="https://user-images.githubusercontent.com/37256050/214611325-597f5672-4251-4de4-a43d-ee988894d81a.png">

More major bug– the last names do not conflict but do not appear in the new record

**Comment by maxxxxxdlp** [comment]
Unable to replicate:

![Screenshot 2023-01-25 at 09 55 45](https://user-images.githubusercontent.com/40512816/214611396-4fc40998-2094-49cb-9024-bc409357f15a.png)


Regarding, "because the Last Name is not in conflict", that should not have effect on formatted record generation

**Comment by grantfitzsimmons** [comment]
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/37256050/214611840-129c4e50-7cd8-407d-8fda-59af3dd97fe5.png">

>Regarding, "because the Last Name is not in conflict", that should not have effect on formatted record generation

I had to change the issue once I realized this is a lot more major than it looked

**Comment by maxxxxxdlp** [comment]
If you click on "Show conflicting fields only", do you see blanks for the non-conflicting fields?

**Comment by grantfitzsimmons** [comment]
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/37256050/214612076-4d8f8a96-869c-47f0-a236-c7ed3d476e83.png">

The default display

**Comment by grantfitzsimmons** [comment]
<img width="1614" alt="image" src="https://user-images.githubusercontent.com/37256050/214612170-68ba1261-f181-4d64-bab1-d09da29d56ba.png">

Showing all fields

**Comment by chanulee1** [comment]
Appears to be fixed. Hidden, non-conflicting fields were merged.

![image](https://user-images.githubusercontent.com/103299204/216529500-91c2a661-bccc-4c08-a96f-d5ceb016b4e0.png)

![image](https://user-images.githubusercontent.com/103299204/216529660-f71e9249-1ab7-48b6-bfff-3b97fa59c669.png)
