### ISSUE TITLE
Improve the "Create New Loan" dialog

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2881]
> ## New Loan Dialogue
> 
> In Specify 7, When creating a new Loan, the following steps are taken.
> 
> Interactions > Loan > Create Loan popup with opens to choose recordset of enter Catalog Numbers.
> 
> <img width="372" alt="image" src="https://user-images.githubusercontent.com/37256050/214618581-ea447bb3-4b49-4485-bdd5-459c68d7bbbc.png">
> 
> If Catalog Numbers are added.
> <img width="372" alt="image" src="https://user-images.githubusercontent.com/37256050/214618631-17941151-212c-453a-9eb4-ddf17f8b2458.png">
> 
> And then ‘**Next**’ is selected, the following result appears.
> <img width="370" alt="image" src="https://user-images.githubusercontent.com/37256050/214618671-bb960387-513a-46bd-ae57-d085d7b29d8d.png">
> 
> From the text following ‘**Next**’, there is a statement ‘There are problems with the entry:’ and then on the following line, ‘_Missing_:’
> This statement seems to imply that the Catalog Numbers themselves are missing, which is misleading.
> The following statement, that ‘_No preparations were found_’ is much more informative in this case.
> 
> From the previous popup, if ‘**Next**’ is selected, nothing happens. If ‘**Ignore**’ is selected, the following popup appears:
> 
> <img width="382" alt="image" src="https://user-images.githubusercontent.com/37256050/214618809-37c7af1e-e710-4b0c-9a08-afe42c5694cc.png">
> 
> In this case, there are no preparations to select from, so this popup is a deadend. The only functional option from this popup is ‘Cancel’.
> 
> # Suggested Improvement
> 
> If no preparations are found, it would be helpful to replace the ‘Missing:’ text with ‘No preparations were found:’ for the following Catalog Numbers, and omit the ‘Ignore’ option. 

**Requested By:** Garth at The University of Michigan

Please let me know if you have any questions so I can pass them along.

**Comment by CarolineDenis** [comment]
Fixed in https://github.com/specify/specify7/pull/3370

**Comment by melton-jason** [comment]
@grantfitzsimmons 
Is Caroline's change sufficent enough to close this issue?
Or is there more than can be done to further this feature request's end goals?

**Comment by grantfitzsimmons** [comment]
![image](https://github.com/specify/specify7/assets/37256050/3bcd16b8-26fd-4f2e-aaca-cc7bc6ffe47a)

@CarolineDenis has already made most of the improvements to this process. 
When you enter a list of catalog numbers without preparations, it should warn you that there are no preparations associated with the objects and it should make the user confirm they want to create the loan or cancel.

**Comment by CarolineDenis** [comment]
Create new loan: When there is no prep for a cat#, we arrive at a dialog with a table containing columns such as taxon, object, type, etc., and all rows are empty. The desired behavior should be as follows:
If there is no preparation, a dialog should open with the message, "None of these objects have preparations. Would you like to continue?" (See button labeled "Without Preparations" in the create loan dialog)
