### ISSUE TITLE
Record merging does not respect name and deletes address

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2883]
https://user-images.githubusercontent.com/37256050/214670546-a96f63de-0824-44f3-95bb-6b24317ac0f4.mp4

See that 4 records should exist in the address relationship, name should be Benjamin, neither are respected after the merge

**Comment by maxxxxxdlp** [comment]
Happened when an error occurred merging one of the records.
Bug:
- "Auto merge" was called again, which overwritten previous changes to the merged records
- The error message that caused merging to fail wasn't shown

Both should be fixed now. Needs testing

**Comment by chanulee1** [comment]
Name appears to be respected. Address is not deleted. Address duplication is separate bug #2713. Is any further testing needed?

https://user-images.githubusercontent.com/103299204/217307792-1fdc4e2f-a6e8-4a5b-b0c1-4eeb10bd9f90.mp4
