### ISSUE TITLE
`Object of type Agent is not JSON serializable` after deleting and re-adding agents

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2884]
![image](https://user-images.githubusercontent.com/37256050/214695191-8454cb40-2799-409e-90ba-df3c1f0184f1.png)

> I was editing the collectors in a record.
> 
> They were in the wrong order, so I deleted, them, and put them back, when I hit save, I got this error. Maybe I should have saved after I deleted???

**Reported by:** Heather Cole at AAFC

[Specify 7 Crash Report - 2023-01-25T21_17_54.774Z.txt](https://github.com/specify/specify7/files/10503867/Specify.7.Crash.Report.-.2023-01-25T21_17_54.774Z.txt)

**Comment by melton-jason** [comment]
I have looked through the traceback and identified the root cause of the issue.
It appears that a uniqueness rule was violated. More specifically, it appears that a `Collector` has the same Agent when trying to save a `Collecting Event`. 

Here is where that occurs in the code:

https://github.com/specify/specify7/blob/5ef989cc36a76efa7d94f1f9f334e117ed241483/specifyweb/businessrules/uniqueness_rules.py#L43-L52

Here is the raised Exception as it appears in the traceback
``` 
BusinessRuleException: ('Collector must have unique agent in collectingevent', {'table': 'Collector', 'localizationKey': 'childFieldNotUnique', 'fieldName': 'agent', 'fieldData': ('agent', <Agent: Agent object (98274)>), 'parentField': 'collectingevent', 'parentData': 'collectingevent: id=69536', 'conflicting': [86849]})

**Comment by melton-jason** [comment]
> There are some cases where something in the original error is not Json Serializable and thus can not be directly sent as a Json response. To get around this, I manually catch the error that is thrown when trying to serialize the object and serialize that instead to json and sent it to the frontend. Based on the traceback, I still know you were trying to delete something.

From https://github.com/specify/specify7/pull/2702#issuecomment-1379720672

Here is another use case in which implementing #2808 would be useful. 
While this case is not directly a Query Set, these cases should be serialized as well. (Handling these model cases first would pave the way for serializing Query Sets)

**Comment by grantfitzsimmons** [comment]
On #2929:

<img width="891" alt="image" src="https://user-images.githubusercontent.com/37256050/218490722-8f07f47f-278f-42b0-95cc-5c5e60c9679e.png">

_Definitely a big improvement!_

**Comment by grantfitzsimmons** [comment]
Spun this off into another issue for the actual problem, this issue will track the `is not JSON serializable` problem
