### ISSUE TITLE
`agent-merging`: Query result row should update after merging

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2887]

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons some edge cases. are the proposed solutions acceptable?
1. If after merging, the record no longer matches the query filters, should it be excluded from the query results, or should be included in the query despite not matching (this is actually harder than it might sound because of -to-manys)
2. If after a merge, the query now return this record as multiple rows (because of -to-manys), is it okay to display to manys as separate rows in query results (even if it was just one row before the merge)?

**Comment by grantfitzsimmons** [comment]
> If after merging, the record no longer matches the query filters, should it be excluded from the query results, or should be included in the query despite not matching (this is actually harder than it might sound because of -to-manys)

If it no longer matches the query output, it should logically no longer be returned.

> If after a merge, the query now return this record as multiple rows (because of -to-manys), is it okay to display to manys as separate rows in query results (even if it was just one row before the merge)?

The query should return the results accurately just as if it was run after the merge took place in my opinion.

**Comment by maxxxxxdlp** [comment]
Additional concern:
The merged record may be in a different position in the query after merging (if results are sorted by a field that was changed).

Solutions:
- Re-run the query after merging - simplest and most consistent. But, the user looses their position in query results.
- Re-run the query for the merged record only to fetch the updated fields, and replace the old results row with the new one, even if it no longer should be there according to sorting - this is more complicated, and I can definitely see bugs with it (i.e, if you had 80 records fetched, and before merging the record was at position 50 but after merging it is at 85, then once you start scrolling though results, and it fetches the next 40 records, the merged record would be included again - we can add detection for this but I would rather not as it adds a lot of complexity and possibly other bugs I didn't think of.

**Comment by grantfitzsimmons** [comment]
> Re-run the query after merging - simplest and most consistent. But, the user looses their position in query results.

I still think this is the most logical path forward for this initial release. Once we have a standalone tool as discussed, we should develop a better way of batch merging agents without the user losing their place. It is not worth introducing many bugs and delaying the release if we can spend time creating a proper tool for matching agents based on some criteria for merging.

**Comment by chanulee1** [comment]
Query re-run after merging.
