### ISSUE TITLE
Null values in picklists are broken.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#289]
Seen in the sex collection object attribute of Cornell mammals database.

**Comment by benanhalt** [comment]
@garrettgirard This can be tested with any database that includes a picklist that includes `null` as one of the values. The Cornell mammals database is the one where I discovered the bug. Theresa might know of other databases that have picklists with `null`s.

**Comment by garrettgirard** [comment]
I ended up testing this with Cornell Fish, using the same picklist. In the sex COA picklist, instead of nothing showing up, there is a value "<no data>" in the picklist.
