### ISSUE TITLE
`agent-merging`: Change the style of the "Auto-Merge" button to differentiate them

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2895]
> - Making the   "auto merge" button a different color or different style. Because   it looks the same as the "merge" button, it gives me the impression   that it will do the auto part and then immediately save without giving me the   chance to check over the work.

**Requested By:** Rebecca Hawkins

**Comment by chanulee1** [comment]
"Auto-Merge" now "Auto-Populate" and its style seems easily differentiable from the merge button.
