### ISSUE TITLE
`agent-merging`: Date ranges of collecting should be displayed

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2897]
> Being date ranges of  collecting would be great

**Requested By:** Brad Ruhfel

**Comment by maxxxxxdlp** [comment]
Would it be like a query that finds a determination with the oldest startDate and the one with the newest startDate where the current agent was either determiner or determiners.agent and then shows the two dates as an row below the references section?

**Comment by grantfitzsimmons** [comment]
This request is specific to Collecting Event records.

When an agent is used as a collector, there is an associated Collecting Event. If there is a date or date range, Brad would like it to display in the merging dialog so you can presumably see the years that agent was active and collecting

**Comment by maxxxxxdlp** [comment]
And an agent may have more than one Collector record
So I need to find the min and max start date among all Collecting Events where this agent is a Collector?
And you don't think that this would be useful for other tables too? (Determiner/Accession/...)

**Comment by maxxxxxdlp** [comment]
Added:

![Screenshot 2023-02-02 at 13 25 53](https://user-images.githubusercontent.com/40512816/216430126-9756db67-e892-41ad-b18a-97694aeccaa0.png)

Open to formatting suggestions regarding making it look better.

Date ranges are displayed for the following fields:

```json
    {
      "Address": [
        "endDate",
        "startDate",
      ],
      "Appraisal": [
        "appraisalDate",
      ],
      "Borrow": [
        "borrowDate",
      ],
      "CollectingEvent": [
        "startDate",
        "endDate",
      ],
      "CollectingTrip": [
        "endDate",
        "startDate",
      ],
      "CollectionObject": [
        "catalogedDate",
      ],
      "Deaccession": [
        "deaccessionDate",
      ],
      "Determination": [
        "determinedDate",
      ],
      "Disposal": [
        "disposalDate",
      ],
      "ExchangeIn": [
        "exchangeDate",
      ],
      "ExchangeOut": [
        "exchangeDate",
      ],
      "FieldNotebook": [
        "endDate",
        "startDate",
      ],
      "FieldNotebookPageSet": [
        "endDate",
        "startDate",
      ],
      "Gift": [
        "giftDate",
      ],
      "Loan": [
        "loanDate",
      ],
      "Permit": [
        "endDate",
        "startDate",
      ],
      "Preparation": [
        "preparedDate",
      ],
      "Project": [
        "endDate",
        "startDate",
      ],
      "RepositoryAgreement": [
        "endDate",
        "startDate",
      ],
      "Shipment": [
        "shipmentDate",
      ],
    }
```

(note, most of them are determined dynamically so the list would get updated automatically on schema updates)

**Comment by maxxxxxdlp** [comment]
Please test performance impact. It has to make quite a few queries:
find the smallest start date, the largest start date, the smallest end date and the largest end date (that is not null) in the case of Determination. each of these queries has to sort the entire table to find the desired date
It looks for largest start date just in case some databases only ever use start date and never use end date. Fetching smallest end date for same reason - in case records don't contain start date.

**Comment by chanulee1** [comment]
False precision for collecting event date. Collecting event date is precise to the year, but date range displays with day, month, year.

Start date of collecting event range for agent `Fike, A Byron` is `12/31/1943`
![image](https://user-images.githubusercontent.com/103299204/217667849-9ad4b4d4-9c29-404a-aa5d-ebee5cc2c304.png)

Earliest collecting event date is `1944`
![image](https://user-images.githubusercontent.com/103299204/217668158-8c40ff74-f312-437c-b51b-ba59af61a062.png)
https://coldfish-agent-merging.test.specifysystems.org/specify/query/132/

**Comment by chanulee1** [comment]
Date range seems to display correctly for `day/month/year` and `year` but not for `day/month`.


https://user-images.githubusercontent.com/103299204/226986289-1d6f0186-dae1-45ab-bbb9-9bbf55b9347e.mp4

https://coldfish-agent-merging.test.specifysystems.org/specify/query/202/

**Comment by grantfitzsimmons** [comment]
Added in #2579
