### ISSUE TITLE
Can't link to a specific data model table or user prefs category

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2898]
A URL like this: https://sp7demofish.specifycloud.org/specify/data-model/#journal or https://sp7demofish.specifycloud.org/specify/data-model/journal/
does not scroll down to Journal table

Looks like we have the same bug for user preferences https://sp7demofish.specifycloud.org/specify/user-preferences/#form

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-9-release-announcement/1131/1
