### ISSUE TITLE
Cannot create reports/labels based on query with a (formatted) field

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2899]
**Instructions on how to test:** https://github.com/specify/specify7/issues/2899#issuecomment-1896616281

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/37256050/214915451-7bdfeda2-6981-459c-ae71-a035b239caaa.png">

[Specify 7 Crash Report - 2023-01-26T18 09 25.652Z.txt](https://github.com/specify/specify7/files/10512190/Specify.7.Crash.Report.-.2023-01-26T18.09.25.652Z.txt)

https://user-images.githubusercontent.com/37256050/214915816-54872a87-acd2-4225-a685-0ff7e9de1265.mp4

https://sp7demofish.specifycloud.org/specify/overlay/queries/

**Comment by melton-jason** [comment]
I have encountered a similar issue, which I think has the same underlying cause.

@grantfitzsimmons do you know if the underlying query has a `(formatted)` field? 

I was not able to create a Report or Label if the query contained the `(formatted)` field. If the formatted field is not included in the query, then I am able to make the report/label.

**Comment by grantfitzsimmons** [comment]
Still having this issue

**Comment by grantfitzsimmons** [comment]
This was reported again on the UBC database.

https://hujinnhc.specifycloud.org/specify/query/3/

<img width="950" alt="image" src="https://github.com/specify/specify7/assets/37256050/551bec0e-c1d5-4883-8d9f-486e637a9b56">

```
AttributeError
'NoneType' object has no attribute 'type'
```

[Specify 7 Crash Report - 2023-08-24T01 40 23.028Z.txt](https://github.com/specify/specify7/files/12424531/Specify.7.Crash.Report.-.2023-08-24T01.40.23.028Z.txt)

**Comment by grantfitzsimmons** [comment]
The issue is resolved when you remove the **(formatted)** field for the base table!

**Comment by grantfitzsimmons** [comment]
> Fortunately, this field can be manually added to the JRXML (report definition file) after creation, but it must be done manually.
> You can [follow this guide to add new fields to an existing report or label](https://discourse.specifysoftware.org/t/adding-new-fields-to-a-report-or-label-in-specify-7/629)

**Comment by grantfitzsimmons** [comment]
This was reported again by Eyal at HUJ. This needs to be looked into further.

[Specify 7 Crash Report - 2023-09-11T10_17_06.874Z.txt](https://github.com/specify/specify7/files/12576874/Specify.7.Crash.Report.-.2023-09-11T10_17_06.874Z.txt)

**Comment by grantfitzsimmons** [comment]
Reported again by Paul Larson at FWRI. +1 agian!

[Specify 7 Crash Report - 2023-10-27T18_44_29.985Z (1).txt](https://github.com/specify/specify7/files/13192862/Specify.7.Crash.Report.-.2023-10-27T18_44_29.985Z.1.txt)

**Comment by grantfitzsimmons** [comment]
Reported again by Chris at Gothenburg museum of natural history.

[Specify 7 Crash Report - 2023-11-03T13_23_17.175Z.txt](https://github.com/specify/specify7/files/13250852/Specify.7.Crash.Report.-.2023-11-03T13_23_17.175Z.txt)

**Comment by grantfitzsimmons** [comment]
Reported again by Eitan at Oranim College of Education

[t1.txt](https://github.com/specify/specify7/files/13329429/t1.txt)

**Comment by grantfitzsimmons** [comment]
**Steps to Recreate:**
1. Create a new query (for example, on the Collection Object table)
2. Add the `(formatted)` 'field' to the query
3. Save the query
4. Click on the pencil next to the query name
5. Click on 'Define report based on query' or 'Define label based on query'
6. Give the new report/label a name
7. See crash

**Screen Recording:**
[Specify 7 Crash Report - 2024-01-17T20_12_27.264Z.txt](https://github.com/specify/specify7/files/13968301/Specify.7.Crash.Report.-.2024-01-17T20_12_27.264Z.txt)

**Comment by CarolineDenis** [comment]
NOTES: 
https://github.com/specify/specify7/blob/1886a444e5c64bcda5d8e26764c1ac04b3b38c05/specifyweb/report_runner/views.py#L161-L164
`get_field `is not defined
