### ISSUE TITLE
Some fields are not showing the proper field caption in query builder results

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2901]
## Report

> In the screenshot of 7 below the first, 6th and 9th columns have incorrect captions in grod view (not in form view), but the sp6 grid has correct captions.
> 
> I don’t understand why there seems to be a prefix ‘Collection Object’ in front of those captions.
> 
> 
> <img width="2247" alt="image" src="https://user-images.githubusercontent.com/37256050/214953978-0843f559-5ee2-4d04-b6fe-694dbd8a7650.png">
> <img width="1254" alt="image" src="https://user-images.githubusercontent.com/37256050/214954004-993c7bdb-be5c-4fb0-89dd-8b4c06631e36.png">

---

## Bug

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/37256050/214952485-d0c8b500-341e-403e-aa66-6bca7c337fe8.png">

`name` field has the caption "Other ID"

<img width="879" alt="image" src="https://user-images.githubusercontent.com/37256050/214952652-074c2428-e348-4447-9cd0-c1492cdc35ca.png">

Yet, when running a query, the column heading is "Collection Object"

<img width="873" alt="image" src="https://user-images.githubusercontent.com/37256050/214952701-90c57b84-3849-46a9-bcfd-fb774a036069.png">

In the above screenshots, it is running `v7.7.5`

On our test instance running `edge`, the same issue occurs.

<img width="898" alt="image" src="https://user-images.githubusercontent.com/37256050/214952841-f8470ef4-152e-48eb-b33e-99812aa4bf1c.png">

[Link to the above query on the test instance](https://sanbibiobank-edge.test.specifysystems.org/specify/query/183/)

---

### Potential Bugs

`fieldNumber` is named "Pathology" in the schema yet the column heading is "Collection Object Pathology":

<img width="895" alt="image" src="https://user-images.githubusercontent.com/37256050/214953228-7d2d8ded-7b71-41e8-b16a-776db55924cd.png">

On `edge`, this is not reproducible when selecting `fieldNumber`:

<img width="894" alt="image" src="https://user-images.githubusercontent.com/37256050/214953189-58d61188-b02e-4a21-b901-92c12e744cf2.png">

---

`catalogedDateVerbatim` is displaying as "Collection Object Markings" instead of "Markings":

<img width="897" alt="image" src="https://user-images.githubusercontent.com/37256050/214953619-5e77ad25-9465-4e69-83c7-c6723737112d.png">

Cannot recreate in `edge`:

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/37256050/214953509-efc0916f-b372-4699-8cd6-99ad21ff1f5d.png">

---

[Test Deployment](https://sanbibiobank-edge.test.specifysystems.org/specify/query/183/)

**Reported By:** Willem at SAIAB

**Comment by grantfitzsimmons** [comment]
> ![image](https://user-images.githubusercontent.com/37256050/214954879-08451572-8ce1-4db0-815b-95b5e27bb77e.png)
>
> This appears in Collection Object Attributes too

**Comment by maxxxxxdlp** [comment]
Could be caused by the fix for https://github.com/specify/specify7/issues/2536. @CarolineDenis could you please take a look?

**Comment by grantfitzsimmons** [comment]
SAIAB is using `v7.7.5` so it is improved in the newest release but still not resolved

**Comment by maxxxxxdlp** [comment]
I see. Than this should be tested on the latest release and closed if it appears to be fixed

**Comment by maxxxxxdlp** [comment]
Another thing I noticed during the webinar:

Agent -> Address -> (formatted) has wrong column label:

<img width="683" alt="Screenshot 2023-01-26 at 09 08 22" src="https://user-images.githubusercontent.com/40512816/215184248-8bd4cb25-2c9f-4723-a959-8721d76412dd.png">

(should be `Address`)

**Comment by chanulee1** [comment]
The bug seems to be present on `edge`:
![image](https://user-images.githubusercontent.com/103299204/216397173-1704f0dd-bace-4fa1-be9e-b05e656d7ca8.png)

Unlocalized:
![image](https://user-images.githubusercontent.com/103299204/216398001-9e016bf8-2749-4f7c-8e3e-89c4727833aa.png)

Agent table:
![image](https://user-images.githubusercontent.com/103299204/216398589-a36599ba-444d-45ae-9f39-1fd40ff5293a.png)

CollectionObjectAttribtute table:
![image](https://user-images.githubusercontent.com/103299204/216398946-ed98e798-88b7-4326-837b-de8ac3868c07.png)
