### ISSUE TITLE
`agent-merging`: Automatically make merged agents variants

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2908]

**Comment by maxxxxxdlp** [comment]
Agent variants would now be automatically created (using the duplicate agents converted to a string using the default formatter)

The code also makes sure to keep the list of variants unique, not include any variants that are already present and to not include empty variants.

Does not yet detect typos. See #2913 for that.

@grantfitzsimmons
Do we need an indicator of some sort that new variants were automatically created?
Also, do we want to create a pref for disabling/controlling this behavior (that would be simple)

**Comment by grantfitzsimmons** [comment]
> Also, do we want to create a pref for disabling/controlling this behavior (that would be simple)

Yes, I think that's a good idea. Especially since so many agents in bulk uploads are typos or slight duplicates

**Comment by chanulee1** [comment]
How to test?

**Comment by maxxxxxdlp** [comment]
Try to merge 4 agents with different last names.

The merged record should automatically have 4 `Agent Variants` records created for each of the last names.

Also, in user preferences, under `Record Merging`, there is an option to disable automatic agent variant creation

**Comment by chanulee1** [comment]
![image](https://user-images.githubusercontent.com/103299204/216521730-3f8cb195-343e-4bda-8835-3c094a1e7de3.png)

![image](https://user-images.githubusercontent.com/103299204/216523164-9947b6ba-ad63-4bfb-955b-42d817216045.png)

(Also tested)
List of variants kept unique, does not include variants that are already present, does not include empty variants. Option to disable agent variant creation works.
