### ISSUE TITLE
Highlighted rows in workbench stuttering

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2918]
https://user-images.githubusercontent.com/103299204/215586994-67d55873-e13a-4df5-aeb6-349fae2ee745.mp4

browser: Chrome
os: Windows 10

**Comment by maxxxxxdlp** [comment]
Did this happen before? Or in a different browser? What branch is this on?

**Comment by chanulee1** [comment]
Yes, this is present even on `v7`. The branch I found it on is `edge`. It appears to be present in both Chrome and Firefox.

**Comment by maxxxxxdlp** [comment]
`v7` is a synonym for the most recently released version (currently `v7.8.4`).
Can you please test this in `7.8.1` or `7.7.1`?

**Comment by chanulee1** [comment]
Ah, I see. Was able to recreate in `edge`, `7.8.1`, and `7.7.1`. Also tested on a different Windows system (Also Windows 10) in both Chrome and Firefox and was able to recreate it. Maybe a problem with the OS?

`7.7.1`:

https://user-images.githubusercontent.com/103299204/216129937-d577a716-8d66-4876-ac4b-f4bc3596c787.mp4

**Comment by grantfitzsimmons** [comment]
Do you think it might have something to do with the lighting you have in your browser or extensions?

**Comment by emenslin** [comment]
Fixed
