### ISSUE TITLE
`issue-2860` Names of view sets and app resources not displayed

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2922]
![image](https://user-images.githubusercontent.com/103299204/215606281-812d30cc-b8f2-4d34-b3e0-991f73b845fe.png)

![image](https://user-images.githubusercontent.com/103299204/215606425-3346dd6b-41d7-48f9-b494-ee2ee9e215fa.png)

**Comment by maxxxxxdlp** [comment]
Unable to reproduce on the URL you linked. This could have been fixed since than as I did a lot of changes on xml-editor since (and issue-2860 was updated with recent changes from xml-editor).
Could you please try this again, but on an xml-editor branch?

**Comment by chanulee1** [comment]
Unable to replicate on `xml-editor`. Closing this issue.
