### ISSUE TITLE
`issue-2860` Table format and aggregation displaying as invalid

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2923]
Does not display as invalid on `edge`.

https://coldfish-issue-2860.test.specifysystems.org/specify/schema-config/en/CollectionObject/

![image](https://user-images.githubusercontent.com/103299204/215609799-6d06469c-a247-41b6-b13a-5e95c180d52a.png)

**Comment by maxxxxxdlp** [comment]
Fixed. This was caused by changes on the `xml-editor` branch - merging those fixed this

**Comment by chanulee1** [comment]
Format and Aggregation do not display as invalid.
