### ISSUE TITLE
`issue-2860` Panel not displaying in form

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2925]
Added this panel cell to the end of the collection object form:

```
<cell type="panel" coldef="100px,2px,76px" colspan="4">
    <rows>
        <row>
            <cell type="label" labelfor="fieldNumber"/>
            <cell type="field" id="fieldNumber" name="fieldNumber" uitype="text" readonly="true"/>
        </row>
    </rows>
</cell>
```
Does not display in `issue-2860`:

![image](https://user-images.githubusercontent.com/103299204/215611753-2d60596a-c168-438c-becf-bee87867f142.png)

Displays in `edge`:

![image](https://user-images.githubusercontent.com/103299204/215612382-dd803c67-2a2a-4c69-8c4e-8dd336c434ad.png)

https://coldfish-issue-2860.test.specifysystems.org/specify/resources/view-set/4/

**Comment by maxxxxxdlp** [comment]
Unable to replicate.
This might have been an issue due to cache (you need to clean the cache after form changes)
Or maybe this was broken on `xml-editor` branch, and now that this branch received newer changes from that branch it's working again.

Please try to reproduce this again

**Comment by chanulee1** [comment]
Was not able to reproduce. Panel displays on `issue-2860`. Issue can be closed.
