### ISSUE TITLE
`issue-2027` Some invalid dates are not detected

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2926]
Not sure if this is expected behavior. `1111` is not detected as an invalid date. Remote pref set to `ui.formatting.scrdateformat=MM/dd/yyyy`.

![image](https://user-images.githubusercontent.com/103299204/215617375-615fd5eb-b8b8-4846-8d79-910bcff10cdb.png)

[date.format.testing.1.xlsx](https://github.com/specify/specify7/files/10540772/date.format.testing.1.xlsx)

**Comment by maxxxxxdlp** [comment]
I belive it is parsed as a partial date (with just the year)
You can verify it by doing an upload and seeing how the uploaded record looks like
