### ISSUE TITLE
Add Babel polyfill for IE.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#293]
This might get IE working.

**Comment by garrettgirard** [comment]
I just tried to get on Sp7 on IE again. I don't think this fixed the issue. Seems to be the same as before.

**Comment by benanhalt** [comment]
Can you check the document mode as described in this SO answer?
http://stackoverflow.com/questions/27712715/issues-with-developer-tools-ie-11-error-object-doesnt-support-property-or

**Comment by garrettgirard** [comment]
The document mode is currently "Edge (Default)".

**Comment by garrettgirard** [comment]
Nevermind, I.E. started working this morning. It was probably some caching issue. But it's good now!
