### ISSUE TITLE
Make attachment form display alongside image when attaching

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2936]
Currently, there is no way to correctly set defaults for fields in the attachment table when an attachment is created.

This could be remedied by displaying the form immediately when uploading an image and requiring the user to click **Save** so that defaults set in the form definition (`isPublic`, `license`, etc.) are applied upon attachment record creation.

**Requested on behalf of:** Gothenburg museum of natural history

**Comment by grantfitzsimmons** [comment]
Includes https://github.com/specify/specify7/issues/2787

**Comment by maxxxxxdlp** [comment]
This was fixed in https://github.com/specify/specify7/pull/2961
