### ISSUE TITLE
Rearrange crash report fields

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2939]
Grant suggested moving user name, collection name, specify the version, and other important fields to the top of the crash report screen

**Comment by CarolineDenis** [comment]
@maxxxxxdlp where is the order defined in the code? I see that FormatError receives the error object and formats it but I cannot find the origin.

**Comment by maxxxxxdlp** [comment]
I belive the order is determined when crash report is created, not when crash report is visualized.
