### ISSUE TITLE
Reports won't generate when using scriptlets that pull fields from aggregated fields

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#294]
The problem is that the getFirstCollector and getSecondaryCollector scriplet methods don't work for Specify 7 because they require post hoc database access. The workaround is to pull apart the aggregated collectors field which is already included in the query. I can add a scriptlet method to do that, or it might be possible to do it directly in a field expression.

This is an issue because several collections use this scriptlet or one like it on their reports/labels. So currently that means many users on Sp7 won't be able to generate the report. Also, currently there isn't another way to pull individual fields from aggregated ones as far as I'm aware, so keeping the scriptlet in place is the only option I know that will work for the reports.

**Comment by benanhalt** [comment]
I have added two Scriptlet methods, `deaggregateFirst(aggregatedValue, separator)` and `deaggregateSecondary(...)`. These will replace `getFirstCollector(catalogNumber)` and `getSecondaryCollectors(catalogNumber)` by including **collectors (aggregated)** in the query (if it is not already included) and using `deaggregateFirst(collectors, ";")` and `deaggregateSecondary(collectors, ";")` in place of the *getCollector* expressions, assuming the aggregation uses ";" as the separator.

**Comment by garrettgirard** [comment]
I updated the the Emory herbarium label with those scriptlets and they appear to work great! Now they only need to be added to Specify 6 at some point so that users can use scriptlets compatible with both versions on the same label.
