### ISSUE TITLE
Add username to the user tools menu

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2941]
<img width="652" alt="image" src="https://user-images.githubusercontent.com/37256050/216732950-bb11e2f2-3de0-4caf-84e9-58a09ff80c29.png">

Since it will not be shown when the navigation menu is collapsed, it should be visible when the user icon is clicked on

**Comment by maxxxxxdlp** [comment]
In the dialog heading like `User Tools (spadmin)` or as a line below the header?

Also, what to do with current collection indicator?

**Comment by grantfitzsimmons** [comment]
I think so!
