### ISSUE TITLE
Return Loan button on Loan form doesn't do anything

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#295]

**Comment by benanhalt** [comment]
For future reference, `prepdialog.js` is calling schema.getModel at module load time. Previously, the Specify datamodel was loaded as a module using *requirejs* meaning modules depending on the schema would not load until it was available. That is no longer the case after moving away from *requirejs*.

**Comment by garrettgirard** [comment]
The loan return dialog box opens up after pressing the button now. However, from here it is pretty buggy and it still doesn't seem possible to complete the loan return. Here are little things within the loan return dialog box that I found to be buggy:
1) Hitting "Select All" selects all of the preparations, however it doesn't change the number returned and resolved to the maximum number for each prep, as it does in Specify 6.
2) If you click "Select All", then click "Deselect All", it deselects the loan preps. However, if you then click "Select All" again, the check boxes remain unchecked, and the only thing that indicates that the preps are being selected is it shows an icon for opening remarks.
3) When the prep is not selected (i.e. check box is not checked), if you raise the number resolved, you can't raise the number returned. And if the number returned is anything but 0, it goes back down to 0 upon changing the number resolved.
4) If you change the number returned to anything other than 0, clicking "OK" will do nothing (it technically returns the prep if the number returned is the same as the number resolved, but you can't save as explained below), and you will get an exception:
prepreturndialog.js:206 Uncaught TypeError: Cannot read property 'Resource' of undefined(anonymous function) @ prepreturndialog.js:206_.each._.forEach @ underscore.js:153updateModelItems @ prepreturndialog.js:199returnSelections @ prepreturndialog.js:243props.click @ jquery-ui.js:10036dispatch @ jquery.js?27d9:5227elemData.handle @ jquery.js?27d9:4879
5) If you do successfully return preps (there is no indication, as clicking the OK button doesn't tell you any preps were returned [although it does tell you when 0 preps were returned], and it doesn't close the dialog box), saving the loan results in an error, and the loan isn't saved upon reloading the page:
jquery.js?27d9:10243 PUT http://db3.biwebdbtest.nhm.ku.edu/api/specify/loan/21081140/ 500 (INTERNAL SERVER ERROR)send @ jquery.js?27d9:10243ajax @ jquery.js?27d9:9732Backbone.ajax @ backbone.js:1448Backbone.sync @ backbone.js:1441sync @ resourceapi.js:520save @ backbone.js:470save @ resourceapi.js:438doSave @ savebutton.js:99_fulfilled @ q.js:834self.promiseDispatch.done @ q.js:863Promise.promise.promiseDispatch @ q.js:796(anonymous function) @ q.js:556runSingle @ q.js:137flush @ q.js:125onNextTick @ main.js:64Item.run @ browser.js?6f0e*:64drainQueue @ browser.js?6f0e*:34
startapp.js:44 [j…y.Event, Object, Object, "INTERNAL SERVER ERROR"]

Because there are several things going on here, some of these might need to be separated into different bugs. But for now I'm going to keep them all together under this issue.

**Comment by garrettgirard** [comment]
1) Fixed - works same way as Sp6 now
2) Fixed - no longer a problem no matter how many times you click select all or deselect all
3) Fixed - this doesn't happen anymore
4) Fixed - preps are now returned and there is no exception
5) Fixed - no more error

Everything seems to be fixed and parallel to Specify 6 as far as workability!
