### ISSUE TITLE
`agent-merging` "Merge records" option on Agent form allows self-merging

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2951]
Query in "Merge" records on Agent form can return record itself and allow attempt to merge a record with itself.

https://user-images.githubusercontent.com/103299204/217319559-1b87b900-ffbc-474b-aec5-2ce129fb3fd6.mp4

[Specify 7 Crash Report - 2023-02-07T17_24_48.340Z (1).txt](https://github.com/specify/specify7/files/10677819/Specify.7.Crash.Report.-.2023-02-07T17_24_48.340Z.1.txt)

**Comment by chanulee1** [comment]
https://user-images.githubusercontent.com/103299204/217325944-ff91d57a-1339-4d62-920f-f9b49d4b46cc.mp4

**Comment by maxxxxxdlp** [comment]
I had code to prevent this, but it did not catch this case because of a bug. Fixed.

**Comment by melton-jason** [comment]
If this issue is fixed on the Agent Merging branch , can it be closed? 
If it has not been tested in a while, perhaps this can be tested again? 
If we are not closing this, then at the very least can this then mentioned in the pull request?

**Comment by grantfitzsimmons** [comment]
Should be fixed, but https://github.com/specify/specify7/pull/3842 removed it from the meta menu anyway.
