### ISSUE TITLE
Clicking and holding on the attachment size slider leads to an infinite loop

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2955]
https://user-images.githubusercontent.com/37256050/217329319-e3c3c581-4507-44e2-b51b-b58132935716.mp4

`Firefox`

**Comment by grantfitzsimmons** [comment]
Could not recreate on chrome or firefox

**Comment by maxxxxxdlp** [comment]
Replicated by @chanulee1:

> Dragging scale slider can result in this (not present in edge):
>
> https://user-images.githubusercontent.com/103299204/220204876-5d0a6640-59c4-4462-a3c2-516a20f9ef53.mp4

**Comment by maxxxxxdlp** [comment]
Reproduced when two attachment viewers were open:

https://user-images.githubusercontent.com/40512816/220518862-6d05b00e-f24d-42d5-bed2-9e3eb09af1b4.mov

**Comment by maxxxxxdlp** [comment]
Caused by local storage syncing between tabs. Need to research more what is the best way to fix this, while still preserving localstorage sync (i.e, maybe adding a 10ms throttle)

**Comment by maxxxxxdlp** [comment]
FYI: this appears to be even easier to replicate if you have 3 tabs of the same page open.
Replicated in app resource editor too (fold/unfold the side bar)

Fixed on `xml-editor` branch

**Comment by grantfitzsimmons** [comment]
https://github.com/user-attachments/assets/f41d3851-4b51-4e1d-91c4-0b1dec7b106d

This is still possible on `v7.12.0.6` and no changes have been made to address it since as far as I know. Encountered today on https://sp7demofish.specifycloud.org/specify/attachments/
