### ISSUE TITLE
Creating a new preparation shows required field as red before any action is taken

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2958]
<img width="1620" alt="image" src="https://user-images.githubusercontent.com/37256050/217636739-ca720104-41d2-4447-be04-9f697e90f3cf.png">

https://coldfish-edge.test.specifysystems.org/specify/view/collectionobject/61572/

**Comment by maxxxxxdlp** [comment]
Unable to replicate

**Comment by grantfitzsimmons** [comment]
Cannot duplicate now, but I could consistently at this time.

**Comment by melton-jason** [comment]
I believe this was caused because somehow it was detecting field changes when the resource was being initialized/ loading, which may be (tangentially) related to 9e7e3ce, f48aed6, and/or 9268cac.

**Comment by maxxxxxdlp** [comment]
The red for invalid fields is only visible after focus loss or form submission.
One way to easily replicate this issue is to have 1 invalid field, try to submit, after that any other invalid field would be visible immediately
I am just hoping that that's the only way
