### ISSUE TITLE
Add UTF-8 BOM to CSV exports for Excel users

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2959]
Excel seems to not use UTF-8 by default and requires major system changes to work

https://answers.microsoft.com/en-us/msoffice/forum/all/excel-read-csv-set-utf-8-as-default-for-all-csv/62eb4068-fc70-4f9b-9bd7-c904713beaf0

https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8

> Any idea why I am seeing degree symbols like this when exporting lat1text and long1text from Specify 7 via a query?  I presume it has something to do with UTF8 incompatibility.  Any idea how I can correct it post-process?  Is this a bug?

![image](https://user-images.githubusercontent.com/37256050/217848614-00917cd7-547f-449c-a617-285d0b8fbdf0.png)

**Requested By:** Many users

**Comment by grantfitzsimmons** [comment]
This could be another export button or option so that Excel users can know that the data will appear in the correct format

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/export-as-csv-with-alternative-delimiter-e-g-semicolon/1003/19

**Comment by FedorSteeman** [comment]
What is the status of this feature?

**Comment by grantfitzsimmons** [comment]
@FedorSteeman This has not yet been implemented, so data still must be imported into Excel using the 'Get Data' functions to import CSVs with the appropriate encoding. 

The initial controversy surrounding the use of a Byte Order Mark (BOM) for UTF-8 encoding was due to the fact that it is "[not required nor recommended](https://www.unicode.org/versions/Unicode5.0.0/ch02.pdf#G19273)" by the Unicode standard. However, Microsoft Excel requires a BOM to correctly identify a CSV file as UTF-8 instead of the local compatibility locale (i.e., ANSI).

Either we will need to release an update that provides the option to add BOM to CSV exports (my preferred approach) or we will need to wait for Microsoft to improve the mechanism Excel uses when opening CSV files as other spreadsheet applications have (Apple Numbers, Google Sheets, LibreOffice Calc, etc.). I will raise this issue again with the developers, but our timeline for the remainder of the year is quite full. As a result, development on a solution is unlikely to begin until early next year if our team does start work on this feature.

Thank you for your message!

**Comment by FedorSteeman** [comment]
I cannot stress enough how large of a stumbling block this is for getting users comfortable with using Specify7 over Specify6. Since the latter can directly export to M$ Excel format, end users perceive this as a major shortcoming of the web-based version.

**Comment by grantfitzsimmons** [comment]
@FedorSteeman We have a new PR opened to resolve this now: #5204
