### ISSUE TITLE
Updating RSS feed does not send notification until page refresh

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2962]
https://user-images.githubusercontent.com/37256050/217978179-32b55066-13be-4d71-93c6-35ef729508b4.mov

I ran several RSS feed exports and never saw a notification. Had to reload and was greeted with several.

https://coldfish-edge.test.specifysystems.org/specify/resources/app-resource/118/

**Comment by maxxxxxdlp** [comment]
This is weird, but I don't think it would be specific to RSS feed. Can you reproduce this again?

**Comment by emenslin** [comment]
Fixed
