### ISSUE TITLE
Aggregators that do not define an orderby field ignore the separator value.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#297]
Can be seen in the KU Fish database. The catalog numbers in the query results should be separated by ";" in the screen shot.

![image](https://cloud.githubusercontent.com/assets/287254/18147120/d7de363c-6f98-11e6-81cd-c6ac4549e202.png)

**Comment by garrettgirard** [comment]
Separators are no longer ignored for these aggregators.
