### ISSUE TITLE
Shadow on paginator number

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2971]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/37256050/218168490-69a246b4-8052-434b-a1d7-85e248f1fdda.png">

**Comment by grantfitzsimmons** [comment]
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/37256050/218170776-dc5a8879-4aec-48dd-9fbd-3aee67569e64.png">

Is this confusing? I know that white is the background for disabled fields but I want to somehow indicate this is a number field without making the background the same as the button.

**Comment by maxxxxxdlp** [comment]
Hmm, looks like a bug.
There should have been at least a border or background. Thanks for the fix
