### ISSUE TITLE
Collectors are sorted by `collectorID`, not `orderNumber` in grid view

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2981]
<img width="1538" alt="image" src="https://user-images.githubusercontent.com/37256050/218499020-7b0328d1-cfef-440f-a201-232559b39a5b.png">

The order is the default ordering by `collectorID`. It should be by `orderNumber`, as this is the intended use of that field.

```SQL
select c.CollectorID, c.CollectingEventID, c.OrderNumber, a.LastName, a.FirstName 
from collector c 
join agent a ON c.AgentID = a.AgentID
where c.CollectingEventID = 260;
```

<img width="1489" alt="image" src="https://user-images.githubusercontent.com/37256050/218499582-ae1d32fe-b05c-4605-8726-cf6cfefc734a.png">

This conflicts with Specify 6's behavior

<img width="1476" alt="image" src="https://user-images.githubusercontent.com/37256050/218501370-e4e847ec-69ea-4806-af15-39049c7f3bad.png">

https://coldfish-edge.test.specifysystems.org/specify/view/collectingevent/260/

**Comment by grantfitzsimmons** [comment]
`orderNumber` increments properly, it just does not display properly.

**Comment by maxxxxxdlp** [comment]
So we just have to make sub views in sp7 use orderNumber instead of id for tables that have orderNumber?

**Comment by grantfitzsimmons** [comment]
Form view in 7 correctly order by `orderNumber`.
Grid view in 7 does **not** order based on `orderNumber`.

Both should use `orderNumber` to determine priority.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-7-release-announcement/1079/1
