### ISSUE TITLE
`CollectionRelOneToManyPlugin` allows for adding duplicate relationships

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2987]
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/37256050/218770413-d6e0ba20-a8e4-42fc-9040-c895805ebd26.png">

> **Specify 7 is able to add related collection object that is already linked and also link it multiple times.** 
>
> Specify 7.7.5 and 7.8.5 appear to be able to add related collection objects even though that collection object is already linked, I can also add the same related collection object multiple times. 

**Reported By:** Don Balmaceda at CSIRO ([Asana](https://app.asana.com/0/1201972579963460/1203963512989542/f))

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-6-release-announcement/1064/1
