### ISSUE TITLE
Datamodel viewer not printing properly

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2988]
Printing preview shows that tables are cut off.

![image](https://user-images.githubusercontent.com/103299204/218815039-2598fce7-d105-4ab6-9061-bc860cd1b039.png)

https://coldfish-edge.test.specifysystems.org/specify/data-model/
branch: `edge`

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-7-release-announcement/1079/1
