### ISSUE TITLE
Reduce loading dialogs in favor of skeleton loaders

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2998]
They provide much better UX and can disappear incrementally as parts of content get loaded.

Example:

![image](https://cdn.dribbble.com/users/1415337/screenshots/5460452/media/623ce9ff10d83e20372a51f55e70c673.gif)

FYI: there are libraries that provide skeletons (some of them even work with tailwind). But even without them, it shouldnt' be hard to create reusable skeleton elements (I,e circles, lines and rectangles that are pulsing synchronously)

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-12-release-announcement/1202/1
