### ISSUE TITLE
Implement an attachment picker

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2999]
Would be useful in user preferences when user wants to use some attachment as welcome page image (currently they have to put the URL)

Can also be used in the future to allow people to set a profile picture.

The attachment picker should still allow putting an arbitrary URL, while also allowing searching/filtering of attachments and ability to upload a new attachment

**Comment by realVinayak** [comment]
I don't think 'Pick an attachment' is a good title for this dialog as it also includes other image selection options.
![image](https://user-images.githubusercontent.com/61122018/228354032-645be722-617f-4c57-9f2e-e9f0a92ab831.png)

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-11-release-announcement/1174/1
