### ISSUE TITLE
Reports and labels icon should be next to category name

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3003]
This is a response to the change made in #2880 

<img width="648" alt="image" src="https://user-images.githubusercontent.com/37256050/219370936-4a6394d5-dac6-4e1c-80a4-bbfc801193b8.png">

The Reports and Labels subheadings should have an icon for the category to make them distinct from each other.

**Example:**

<img width="673" alt="image" src="https://user-images.githubusercontent.com/37256050/219371195-adb49cb9-c661-4971-83a5-d6762c222155.png">

**Comment by maxxxxxdlp** [comment]
Sorry, it was added by Caroline but I removed them because I thought they were added accidentally.
I removed them because the interface looks less cluttered without them, and I though no one is actually looking at the `Reports` labels in favor of the reports themself. Can bring the icons back

**Comment by grantfitzsimmons** [comment]
>Additional reason was that I wanted to minimize usage of old sp6 icons, at least until Grant send me updated variants of them

Good point. I have it on my to-do list... one of these weeks. I apologize for the delay– there are just so many projects to do. Hopefully, when we bring on another couple of students I'll get the time.

**Comment by grantfitzsimmons** [comment]
I think it's good for now.
