### ISSUE TITLE
Cannot select navigation menu items with keyboard

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3004]
https://user-images.githubusercontent.com/37256050/219374695-5ebcd475-6e5b-409c-8077-7944cdef0efd.mov

I am not super familiar with accessibility tools, but I can not select the nav items with my keyboard.

**Comment by maxxxxxdlp** [comment]
How interesting. Seems to affect Firefox only. Can be replicated both with the old menu, the new menu and the tooltips

**Comment by CarolineDenis** [comment]
With the new Mac updates the ability to navigate between links on Firefox has been disabled. 

To enable it: 

1) On your Mac, choose Apple menu > System Settings, then click Keyboard  in the sidebar
2) Turn on "Keyboard navigation"
3) Restart Firefox 

![Screenshot 2023-02-20 at 10 58 04 AM](https://user-images.githubusercontent.com/108160931/220182049-5ee0bec5-8b55-44bd-9b2b-7819bc3c2c55.png)

**Comment by maxxxxxdlp** [comment]
@CarolineDenis thanks for looking into this
@grantfitzsimmons do you want to post on discourse a short blurb regarding this issue affecting mac&firefox people and a solution (i.e, something like https://support.thinkific.com/hc/en-us/articles/360060878334-Why-can-t-I-use-my-keyboard-to-move-between-links-in-Firefox-for-MacOS-)?
