### ISSUE TITLE
Cannot add geography information to a query

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3005]
https://user-images.githubusercontent.com/37256050/219381954-4c5baacf-0756-4e42-9fc6-293d955a5b0a.mov

This is a **pretty major bug**. I cannot add geography items to the query since I receive this error

```
AttributeError at /stored_query/ephemeral/ 'Discipline' object has no attribute 'localitytreedef' Request Method: POST Request URL: http://newdemofish-edge.test.specifysystems.org/stored_query/ephemeral/ Django Version: 3.2.15 Python Executable: /opt/specify7/ve/bin/python3.8 Python Version: 3.8.0 Python Path: ['/opt/specify7', '/opt/specify7', '/opt/specify7/ve/bin', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/opt/specify7/ve/lib/python3.8/site-packages', '/opt/specify7'] Server time: Thu, 16 Feb 2023 13:47:20 -0600 Installed Applications: ('django.contrib.sessions', 'django.contrib.staticfiles', 'django.contrib.contenttypes', 'django.contrib.auth', 'specifyweb.specify', 'specifyweb.permissions', 'specifyweb.accounts', 'specifyweb.stored_queries', 'specifyweb.businessrules', 'specifyweb.express_search', 'specifyweb.context', 'specifyweb.attachment_gw', 'specifyweb.frontend', 'specifyweb.barvis', 'specifyweb.report_runner', 
```

[Specify 7 Crash Report - 2023-02-16T13 47 49.865Z.txt](https://github.com/specify/specify7/files/10756610/Specify.7.Crash.Report.-.2023-02-16T13.47.49.865Z.txt)

https://newdemofish-edge.test.specifysystems.org/specify/query/155/

`edge` on `Firefox` on `macOS`

**Comment by grantfitzsimmons** [comment]
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/37256050/219382569-433b977f-df08-49f4-8340-899d4eb6442a.png">

Disappointingly, this is also the case on production.

**Comment by melton-jason** [comment]
This issue occurs when adding a formatted rank (excluding AnyRank) to a query which has a Base Table other than the expected Tree (in this case, Geography). 
In fact, this issue occurs for _every_ tree except Storage.

**Comment by melton-jason** [comment]
I have a local copy of `testability`, and this bug occurs there as well. 

This has likely been a bug since 2017, when the associated code was introduced.

**Comment by maxxxxxdlp** [comment]
Interesting. I would have assumed it is a recent bug, and likely caused on the front-end

**Comment by melton-jason** [comment]
This bug was introduced in `7.8.0`, as the individual ranks for trees could not be formatted in a quey in `7.7`. 

There is a strange behavior to note however.
Consider the following query:

![geoQuery](https://user-images.githubusercontent.com/64045831/219716480-7ac13710-d4f0-4ed5-b1a5-1389883c84bd.png)

Here are the `fieldname` and `stringid`  sent to the backend for each of the Query Fields:

- Geography -> (any rank) -> (formatted)
  - geography
  - 2,3.geography.geography

-  Geography -> Continent -> (formatted)
  - Continent geography
  - 2,3.geography.Continent geography
  
- Geography -> Country-> Full Name
  - Country
  - 2,3.geography.Country

**Comment by maxxxxxdlp** [comment]
`Continent geography` is wrong, right?

**Comment by grantfitzsimmons** [comment]
> S7 BUG: Formatted Geography causes crash on CO query
> 
> In version 7.8.5 and also in v7.8.10
> 
> ![image](https://user-images.githubusercontent.com/37256050/235683391-c8454455-dbc0-4b78-8008-7c01052cd0e5.png)
> ![image](https://user-images.githubusercontent.com/37256050/235683438-be2d7d18-6c22-4d50-8768-c8e985857925.png)
> ![image](https://user-images.githubusercontent.com/37256050/235683450-7139328c-7bd7-4e23-9eb3-7c6471ab9904.png)

**Reported By:** Matthew Cruz at UMich

**Comment by grantfitzsimmons** [comment]
@melton-jason Can we finish the PR #3026 to resolve this?
