### ISSUE TITLE
Adding loan preparations from recordset is quirky

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#301]
This is similar to the issue before with the return loan interface (return loan button), #295 

Preps are only selected if you click the checkbox or if you click "select all". Changing the # selected doesn't do anything. Also, even if you manually check the checkbox or click "select all", changing the # selected to the desired number still won't do anything. After clicking OK, the loan pops up with all of the selected preps, the count being the total number you could possibly select for each prep.

**Comment by timo11** [comment]
All the problems mentioned seem to be fixed, however, all items are still not selected by default.

**Comment by garrettgirard** [comment]
Adding preps from a recordset still doesn't seem to work. When I add the preps, they don't show up on the loan form, yet it is not possible to add them again, so Specify thinks that the preps were in fact added. Furthermore, I get an error when trying to add them:

Uncaught TypeError: Cannot read property 'getRelatedModel' of undefined
    at schema.Model.getField (specifymodel.js:69)
    at schema.Model.getField (specifymodel.js:69)
    at schema.Model.getField (specifymodel.js:69)
    at HTMLTableCellElement.fillinLabel (localizeform.js:45)
    at Function.each (jquery.js?27d9:370)
    at jQuery.fn.init.each (jquery.js?27d9:137)
    at module.exports (localizeform.js:52)
    at FormTableInteractionItemView.populateForm (populateform.js:89)
    at FormTableInteractionItemView.<anonymous> (formtable.js:127)
    at underscore.js:73
getField @ specifymodel.js:69
getField @ specifymodel.js:69
getField @ specifymodel.js:69
fillinLabel @ localizeform.js:45
each @ jquery.js?27d9:370
each @ jquery.js?27d9:137
module.exports @ localizeform.js:52
populateForm @ populateform.js:89
(anonymous) @ formtable.js:127
(anonymous) @ underscore.js:73
_.each._.forEach @ underscore.js:153
Collection.(anonymous function) @ backbone.js:913
_render @ formtable.js:126
reRender @ formtable.js:107
triggerEvents @ backbone.js:100
trigger @ backbone.js:187
_onModelEvent @ backbone.js:887
triggerEvents @ backbone.js:102
trigger @ backbone.js:188
add @ backbone.js:643
makeInteraction @ prepselectdialog.js:325
props.click @ jquery-ui.js:10036
dispatch @ jquery.js?27d9:5227
elemData.handle @ jquery.js?27d9:4879

**Comment by timo11** [comment]
Everything seems to work for me when I use the cornell birds db.

**Comment by timo11** [comment]
I think it is a feature of the loanpreps form that is giving 7 problems.
Loan preps don't display for any existing loans in the Florida VP db.
The problem could be that the Loan preps form includes the taxon.fullname of the items on loan, we recently made it possible to do this in 6.

**Comment by timo11** [comment]
see bug #385

**Comment by timo11** [comment]
Finally able to get it to get quirky for me. Working on it...

**Comment by timo11** [comment]
Ok.

The checkbox in the first column: Checking it sets the number in the Selected column to the number in the Available column. Unchecking it sets Selected to 0.

Selected column: Clicking on the arrows, pressing up/down arrow buttons, and entering text  should only allow numeric values between 0 and the number Available. Changing the value to 0 unchecks the checkbox, changing the value from 0 checks the checkbox. (Backspace key doesn't do anything, need to select text with mouse to replace.)

**Comment by yvonneekanim** [comment]
Tested this in a test db; loan prep can be added from recordsets and works as described above.
