### ISSUE TITLE
`tooltips`: Can hover over tooltip intermittently

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3016]
https://user-images.githubusercontent.com/37256050/219830696-38222543-482a-4b70-9657-5cec0ba186af.mov

Hovering over the tooltip is problematic, it is inconsistent (see video)

>**Max:**
> it was supposed to not dismiss the tooltip if you cursor is in the gap between the tooltip and the element

**Comment by maxxxxxdlp** [comment]
This is actually same cause as #3014
Please test
