### ISSUE TITLE
Author field being populated based on entry in preferred taxon QCBX

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3018]
When entering data in the Preferred Taxon QCBX and clicking add, you see the value populates the Author field.

`aafc-aac` database copy

https://user-images.githubusercontent.com/37256050/220161201-6ccb2bbe-fb30-4801-98cd-1bb3cde780b8.mov

**Reported By:** Heather at AAFC-AAC [on the forum](https://discourse.specifysoftware.org/t/taxon-text-incorrectly-auto-entered-in-author-field/1057)

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/taxon-text-incorrectly-auto-entered-in-author-field/1057/2

**Comment by maxxxxxdlp** [comment]
Short-term work around: edit `searchFields` attributes in the TypeSearches to put name before author
Longer term solution: make "main field" detection smarter
