### ISSUE TITLE
Merging tree nodes into nodes with synonymized children with the same names causes error.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#302]

**Comment by benanhalt** [comment]
There will now be a message explaining why the action cannot be completed.

**Comment by garrettgirard** [comment]
The error has been replaced with a box message that reads: 

"The operation could not be completed due to the following:
Merging node 'Acipenses Acipenser sp.transmontanus" with synonymized node "Acipenser sp.transmontanus'."
