### ISSUE TITLE
Importing a query from different user in the same database imports in that user too

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3020]
When importing a query from a different user in the same database, the query is imported to the queries of the user that the query is from as well.

Steps to recreate:
1. Export a query from a user
2. Import the query to a different user in the same database
3. Log back in as the original user and see that the query is imported there as well

https://coldfish-edge.test.specifysystems.org/specify/overlay/queries/

branch: `edge`

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-7-release-announcement/1079/1
