### ISSUE TITLE
`attachment-preview` Error after using side arrows to navigate through attachments

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3023]
Get an error after using side arrows to navigate through attachments. Seems to happen after navigating through around 30 to 40 records?

https://user-images.githubusercontent.com/103299204/220206806-6f1ef885-41c5-4d57-9f6e-ed6422e2a6ca.mp4

https://coldfish-issue-2787.test.specifysystems.org/specify/attachments/

[Specify 7 Crash Report - 2023-02-20T22_10_32.527Z.txt](https://github.com/specify/specify7/files/10788112/Specify.7.Crash.Report.-.2023-02-20T22_10_32.527Z.txt)

**Comment by maxxxxxdlp** [comment]
Happens if the next resource is not loaded before you click on next button.
Usually happens after 30-40 clicks.
Fixed by displaying a loading screen while loading (instead of crashing)
