### ISSUE TITLE
`attachment-preview` "Download" and "Open in new tab" buttons have same effect

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3024]
The "download" and "Open in new tab" buttons both open the attachment in a new tab.

https://user-images.githubusercontent.com/103299204/220209013-06003321-8fdf-4ea0-afe0-5a24044ab14b.mp4

https://coldfish-issue-2787.test.specifysystems.org/specify/attachments/

**Comment by maxxxxxdlp** [comment]
Looks like a browser peculiarity: https://stackoverflow.com/a/51863661/8584605

Seems like the simplest solution would be to remove the button for PDFs (and other applicable resources)
Similarly, for resources that can't be opened by the browser (`.zip`), the `Open in new tab` button should be removed (it currently acts as `Download` for them)

Still, I think this is low enough priority to let be for the first release
