### ISSUE TITLE
`attachment-preview` PDF file format does not have preview displayed

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3025]
Image, video, audio file formats have preview displayed but not for (newly created?) pdf file format attachments. Existing attachments with pdf file format do have a preview displayed.

Newly created attachment:

https://user-images.githubusercontent.com/103299204/220210150-0a85e920-e3ae-4ab5-8556-d917983f18c4.mp4

Original attachment:

https://user-images.githubusercontent.com/103299204/220210220-07ff347d-1dd0-4995-94ab-3cbbbb15b50e.mp4

https://coldfish-issue-2787.test.specifysystems.org/specify/attachments/

**Comment by maxxxxxdlp** [comment]
I belie that's an existing issue. See https://github.com/specify/web-asset-server/issues/9
In the default configuration, web asset server is not correctly configured to generate pdf thumbnails.
This pull request is only about the attachment viewer dialog improvements. That is unaffected by this bug, right?
