### ISSUE TITLE
WorkBench validation throwing `Out of memory` error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3027]
<img width="857" alt="image" src="https://user-images.githubusercontent.com/37256050/220387830-bc04c765-236a-4fe1-9df6-8fbeedfb4e5f.png">

This is a large data set, and this happened at the _very end_ of the validation process.

Number of rows: 3,656
Number of columns: 224

Happened in production with private data so I cannot share it externally. See SCC Vault links below:

[TSV file](https://drive.google.com/open?id=1CpXegql-HTZ_Qkag6jT0S6wUTay_4ifx&authuser=grant%40specifysoftware.org&usp=drive_fs) – [WB_Mapping.txt](https://drive.google.com/open?id=1Cr-MMW2kbJtgFI7Y-yfxlyBAiE8LG1Zp&authuser=grant%40specifysoftware.org&usp=drive_fs) 

This occurred on the `nbm-mnb` database on the CA Specify Cloud. Can try to recreate in the Fish Voucher Collection from a backup using the `spadmin` account.

`/specify/workbench/10/`

```
{
  "uploaderstatus": {
    "operation": "validating",
    "taskid": "112d37c9-e3fc-459b-ac62-0d9086e07e69"
  },
  "taskstatus": "FAILURE",
  "taskinfo": "InternalError(5, 'Out of memory (Needed 143769648 bytes)')"
}
```

**Comment by maxxxxxdlp** [comment]
Looks like the database on the CA server does not have enough RAM.
Probably something to fix when we do the cloud migration
