### ISSUE TITLE
`SyntaxError` regarding regular expression catalog number

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3028]
```
SyntaxError: invalid identity escape in regular expression

Me@https://mcnb22123-edge.test.specifysystems.org/static/js/main.321a0fa8e9d1c6ede8e6.bundle.js:2:492489
B@https://mcnb22123-edge.test.specifysystems.org/static/js/main.321a0fa8e9d1c6ede8e6.bundle.js:2:508822
N@https://mcnb22123-edge.test.specifysystems.org/static/js/main.321a0fa8e9d1c6ede8e6.bundle.js:2:509307
m@https://mcnb22123-edge.test.specifysystems.org/static/js/main.321a0fa8e9d1c6ede8e6.bundle.js:2:429987
T@https://mcnb22123-edge.test.specifysystems.org/static/js/main.321a0fa8e9d1c6ede8e6.bundle.js:2:509136
Suspense
```

You cannot even create a new Collection Object:

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/37256050/220389844-1b440fe5-5d0c-45ef-9a6a-96dc3b1a3110.png">

https://mcnb22123-edge.test.specifysystems.org/specify/view/collectionobject/new/

<img width="452" alt="image" src="https://user-images.githubusercontent.com/37256050/220389955-238bc71f-a28a-4221-845e-a6049787904b.png">

The field does not even display.

`spadmin`

---

The catalog number field uses a regular expression:
`MZB (\d{2}|\d{4})\-\d{4}(-[A-Z])?`

This pattern matches a string that starts with "MZB ", followed by either two or four digits, then a hyphen, then four digits, and optionally a hyphen followed by a single uppercase letter.

This pattern would match strings such as "MZB 12-3456", "MZB 1234-5678", and "MZB 12-3456-A".

---

I can recreate this error consistently when I navigate to https://mcnb22123-edge.test.specifysystems.org/specify/query/26/

[Specify 7 Crash Report - 2023-02-21T15 27 28.055Z.txt](https://github.com/specify/specify7/files/10794951/Specify.7.Crash.Report.-.2023-02-21T15.27.28.055Z.txt)

**Comment by grantfitzsimmons** [comment]
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/37256050/220390445-7bce8e4f-10c1-4a70-98b6-4cf99c54b4fc.png">

This is in `v7.8.0`

**Comment by grantfitzsimmons** [comment]
Still works in `v7.7.3`

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/37256050/220392250-963963de-a30d-4bd5-9c3d-4cb053a439b2.png">

**Comment by grantfitzsimmons** [comment]
and in `v7.7.5`. It looks like this bug was introduced in 7.8.0.

**Comment by melton-jason** [comment]
The error occurs when translating the regex to unicode. More specifically, it happens at this line:

https://github.com/specify/specify7/blob/1ed0fe752106c0daa657af561e58efaa51856ab5/specifyweb/frontend/js_src/lib/utils/parser/definitions.ts#L322

Here `regExpString` is `^(MZB (\d{2}|\d{4})\-\d{4}(-[A-Z])?)$`. 

This regular expression string is is an invalid unicode regular expression (as shown in the screenshot below).

![issue_3028](https://user-images.githubusercontent.com/64045831/220767399-df017ce7-5a01-44eb-ace2-88cccbf5c9fb.png)

Prior to 6 months ago, the regex expression was given no flags (`new RegExp(regExpString)`), but was changed in 
https://github.com/specify/specify7/commit/f9f4419a12d5f058b88bae9c44997010518a46a6#diff-d9d07d608f11065935b48bae2c01a9acbaa3211a814c8262b474142938aaee7d
The regex is valid when not flagged as unicode. 

@maxxxxxdlp 
Do you know why regular expressions were made to be flagged as unicode?

**Comment by maxxxxxdlp** [comment]
`u` flag is not just for Unicode, it's also a strict mode for regex
But that's a good discovery - we should probably not enforce strict mode for regexes that are coming from the user

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp @melton-jason 

In any case, we need to push a fix so that they can _use Specify at all_ again. To make things worse, this regex was created by Ben and done for them.

**Comment by melton-jason** [comment]
If they need a change immediately, they can remove the invalid escape character from the expression. 
A valid regex would be `MZB (\d{2}|\d{4})-\d{4}(-[A-Z])?`

I have updated the uiformatters on https://mcnb22123-edge.test.specifysystems.org/specify/ to use this regex if you want to verify it works correctly.
