### ISSUE TITLE
`tooltips` Hovering over another element counts towards the required hover time

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3030]
https://user-images.githubusercontent.com/37256050/220407786-8ac4f0ee-a1d2-441c-b90b-cb1648a5d747.mov

https://coldfish-tooltips.test.specifysystems.org/specify/view/collectionobject/37441/?recordsetid=103

This is in Firefox and Chrome

**Comment by maxxxxxdlp** [comment]
Fixed. Ready for testing
