### ISSUE TITLE
Adding a record to an empty record set is buggy

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#3033]
1. Open empty record set
2. It opens a new resource form
3. Save it
4. Should replace the `new` in the URL with the id of the resource, while still having `?recordsetid=someNumber` in the URL
5. In the records slider, current index should be shown as `1`, not `0`

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons can you please try to replicate this bug on the `issue-3033` branch?
The bug happens on Caroline's computer and is very concerning, but I can't replicate on my machine.

**Comment by grantfitzsimmons** [comment]
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/37256050/221653711-0d4222a7-acbb-4ec1-ba1d-491d063ec456.png">

I can't replicate on `sp7demofish`, do you want me to try this on my local machine?

https://sp7demofish.specifycloud.org/specify/view/collectionobject/51748/?recordsetid=21

**Comment by maxxxxxdlp** [comment]
I suspect that this might have something to do with the performance of the client computer

**Comment by maxxxxxdlp** [comment]
This happens for Caroline consistently.
@CarolineDenis can you check if there are any errros in the logs when this bug happens or any failed network requests?

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-8-release-announcement/1108/1
