### ISSUE TITLE
Year in date field accepts 6 digits, throws error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3035]
<img width="1483" alt="image" src="https://user-images.githubusercontent.com/37256050/220434248-66377703-b1a0-4d1e-a626-b0d0e282d835.png">

https://sp7demofish.specifycloud.org/specify/view/collectionobject/51591/?recordsetid=14

[Specify 7 Crash Report - 2023-02-21T18_56_05.774Z (1).txt](https://github.com/specify/specify7/files/10796686/Specify.7.Crash.Report.-.2023-02-21T18_56_05.774Z.1.txt)

This causes a particular issue for users who have year first in their date format:

![image](https://user-images.githubusercontent.com/37256050/220434051-29c75c98-dd0e-44c6-a1a8-d96794b2f30e.png)

> Same day, different question, I have switched a little bit to filling in some dates, one of the things I really liked about S6, was that when entering dates, it would automatically moved you through the year/month/date field structure when entering the date components, so that you didn’t have to manually tab or mouse between them.
>
>However, when using the ‘browse in forms’ to edit collection objects, the system waits until I have entered 6 digits for year (instead of 4) before ‘moving’ over to the month section.

**Reported By:** Heather Cole at AAFC/AAC

**Comment by maxxxxxdlp** [comment]
Looks like this is fixed by adding max="9999-12-31" to the input field
