### ISSUE TITLE
Taxon Tree search only returns 20 results and hides all others

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3053]
_Edit: See [this comment](https://github.com/specify/specify7/issues/3053#issuecomment-2140938307) for conclusion of what the issue is._

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/37256050/221575428-1ea48bfb-cc09-4dd6-8e2b-fba6acb0206c.png">

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/37256050/221575695-620446bd-72c6-4e8f-aef9-99e04adf6cf3.png">

>Thanks for taking a look. We are finding that synonyms are coming up when we search in the taxon tree e.g. Allania insignis is in the tree
>
>But when searching on just the species epithet, we are not seeing it in the search results

**Expected Behavior:**

<img width="874" alt="image" src="https://user-images.githubusercontent.com/37256050/221576119-ca5be867-bb9c-4770-b9eb-1a760735ef6d.png">

Just as you can search for synonymized Genus records, you should be able to search for synonymized Species

**Reported By:** Robyn at RBGE

Use a copy of the RBGE database with the following tree location:

```
/specify/tree/taxon/?conformation=%7E%7E1%7E309038-%7E6%7E87-%7E309042%7E1355%7E8043%7E208193--%7E16844%7E100816--%7E9689%7E64193--%7E12594--%7E1596%7E20415--%7E1668%7E10855%7E153340--%7E21596--%7E1684%7E13290----%7E2%7E18-%7E82-%7E34%7E346%7E679%7E6808%7E258876-----%7E38-%7E13-%7E306361-%7E65-%7E70-%7E74%7E1736%7E2897----%7E5%7E35%7E305318%7E138%7E1063-------
```

**Comment by CarolineDenis** [comment]
During my trial to reproduce, I discovered the following:

- Insignis from Allania insignis cannot be found using the search function.

- Insignis from Allania insignis cannot be found in the database using the queries.

- We cannot search for nodes that are synonyms and are not present in the database.

- Searching for species names that have been synonymized and are present in the database is functioning properly.

**Comment by CarolineDenis** [comment]
on v7.9 I can search on Genus Synonyms and on Species Synonyms. @bronwyncombs @carlosmbe 
Can you confirm?

**Comment by grantfitzsimmons** [comment]
I can still recreate this

<img width="995" alt="image" src="https://github.com/specify/specify7/assets/37256050/9f5a5271-7993-49db-8598-1037bef26581">

See that `Allania insignis` is not returned when searching for `insignis`:

- Onobrychis insignis
- Buellia insignis
- Cardamine insignis
- Russula insignis
- Hoffmannia insignis
- Berkheya insignis
- Kutchubaea insignis
- Cheilymenia insignis
- Tacsonia insignis
- Melianthus insignis
- Monophyllaea insignis
- Maesa insignis
- Sorbus insignis
- Fimbristylis insignis
- Pteris insignis
- Cardamine insignis
- Thouinia insignis
- Diplasiolejeunea insignis
- Simaba insignis
- Cruddasia insignis

_No Allania insignis 🥲_

https://herb32124-edge.test.specifysystems.org/specify/tree/taxon/?conformation=~~1~5~35~305318~138~1063~2763--------

**Comment by combs-a** [comment]
Adding on the results of my investigation of this issue 🔍 :

Importable query for searching taxon with a preferred taxon: [SynonymizedTaxa.json](https://github.com/user-attachments/files/15506137/SynonymizedTaxa.json)

**TL:DR;** This may not actually be an issue with synonymized nodes, but rather, the _amount of results being shown._ There is a cutoff of 20 in the search as far as I can tell, and they're organized alphabetically after looking for the string you search with.

There are 156 taxon with the species name insignis in `herb_rbge`, searching them up via doing any rank -> Full Name -> contains insignis, we get this list:

![image](https://github.com/specify/specify7/assets/71564869/1cd40fc1-4835-4e67-a16e-6955a2410051)

The first 20 results are what Grant had on his list! 

Here's some other nodes that have this issue in `herb_rbge`, neither are synonymized:

![image](https://github.com/specify/specify7/assets/71564869/a1af2f8f-a746-4622-9a8d-220338771b18)

Add to end of link for the species (Bionia cocchinea):
```
/specify/tree/taxon/?conformation=%7E%7E1%7E309038-%7E6%7E87-%7E309042%7E1355%7E8043%7E208193--%7E16844%7E100816--%7E9689%7E64193--%7E12594--%7E1596%7E20415--%7E1668%7E10855%7E153340--%7E21596--%7E1684%7E13290----%7E2%7E18-%7E82-%7E34%7E346%7E679%7E6808%7E258876-----%7E38-%7E13-%7E306361-%7E65-%7E70-%7E74%7E1736%7E2897----%7E5%7E35%7E305318%7E138%7E1881%7E333932--%7E1063%7E2690-%7E23304-%7E23173-%7E3122-%7E3129%7E111802--%7E24127-%7E3883-%7E2763%7E251724--%7E3668%7E157408--%7E4541-%7E4612-%7E4746-%7E24807-%7E5037-%7E5089-%7E5148-%7E25333-%7E25200-%7E4440%7E176896---------
```

Same with this species (Arquita trichocarpa):
```
/specify/tree/taxon/?conformation=%7E%7E1%7E309038-%7E6%7E87-%7E309042%7E1355%7E8043%7E208193--%7E16844%7E100816--%7E9689%7E64193--%7E12594--%7E1596%7E20415--%7E1668%7E10855%7E153340--%7E21596--%7E1684%7E13290----%7E2%7E18-%7E82-%7E34%7E346%7E679%7E6808%7E258876-----%7E38-%7E13-%7E306361-%7E65-%7E70-%7E74%7E1736%7E2897----%7E5%7E35%7E305318%7E138%7E1881%7E333932--%7E1063%7E2690-%7E23304-%7E23173-%7E3122-%7E3129%7E111802--%7E24127-%7E3883-%7E2763%7E251724--%7E4541-%7E4612-%7E4746-%7E24807-%7E5037-%7E5089-%7E5148-%7E25333-%7E25200-%7E4440%7E176896--%7E3668--------
```

I didn't run into this issue too much on `KUBirds_8_25_23`, however, I did find a few records that could not be searched.

Xiphorhynchus superciliaris:
![image](https://github.com/specify/specify7/assets/71564869/5fa07141-846c-4c06-b5f2-eb8af52da349)

And Philydor rufum rufus:
![image](https://github.com/specify/specify7/assets/71564869/0390e252-6864-4857-9696-c7bbd78c8235)

You can search the other synonymized node under Philydor just fine (erythropterus), but rufum rufus is not fine. But, also, with erythropterus--it does not appear in the search results until you get to the p or t in it, and then it appears. With rufum rufus, there are too many results that have rufus in it--therefore it doesn't appear.

I think this conclusion makes sense, considering other nodes are also affected by this. Synonymized nodes are also more likely to have names that match with other nodes, from what I can tell.

**Comment by emenslin** [comment]
Can recreate in edge (7.9.6)
