### ISSUE TITLE
Extra determinations being created upon clone

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3054]
https://user-images.githubusercontent.com/37256050/221578289-ed98dfbd-3a2c-4775-b282-3c6ac5ef4b68.mp4

> Attached is a video perform on our Specify Cloud instance showing the problems in action:
> 
> 1: clone/carry forward problem (generates two extra empty determinations, in this case generates 4 instead the only 2 the original record have)

**Reported By:** CSIC

**Comment by grantfitzsimmons** [comment]
A copy is available under `rjb_madrid_2_27_23` on the test panel

**Comment by grantfitzsimmons** [comment]
@melton-jason is this related to the preps being cloned?

**Comment by melton-jason** [comment]
@specify/ux-testing 

Can this be verified? 

It was likely fixed in https://github.com/specify/specify7/pull/4160

**Comment by emenslin** [comment]
Fixed
