### ISSUE TITLE
Changing the base table does not work in the WorkBench mapper

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3059]
https://user-images.githubusercontent.com/37256050/221699843-13b5e566-8547-42f1-a37a-c7a3924f808b.mov

Trying to save after switching tables also leads to:

```
Tried to get unknown relationship field: collectionObject

Stack:

r@https://nbmfishcollectionimport-edge.test.specifysystems.org/static/js/main.aab3282ad1a59f87fc66.bundle.js:2:1018440
strictGetRelationship@https://nbmfishcollectionimport-edge.test.specifysystems.org/static/js/main.aab3282ad1a59f87fc66.bundle.js:2:142613
63218/v/<.toOne<@https://nbmfishcollectionimport-edge.test.specifysystems.org/static/js/main.aab3282ad1a59f87fc66.bundle.js:2:677651
v@https://nbmfishcollectionimport-edge.test.specifysystems.org/static/js/main.aab3282ad1a59f87fc66.bundle.js:2:677616
b@https://nbmfishcollectionimport-edge.test.specifysystems.org/static/js/main.aab3282ad1a59f87fc66.bundle.js:2:678046
63218/w/h<@https://nbmfishcol
```

[Specify 7 Crash Report - 2023-02-27T22 25 24.888Z.txt](https://github.com/specify/specify7/files/10844824/Specify.7.Crash.Report.-.2023-02-27T22.25.24.888Z.txt)

**Comment by maxxxxxdlp** [comment]
I belive this is caused by the auto mapper, not base table changing.

I also had a "NONE SELECTED" show up in suggested mappings:
![Screenshot 2023-02-22 at 10 34 34](https://user-images.githubusercontent.com/40512816/221719698-379729ff-9017-4718-a4ef-7e1be2056325.png)

**Comment by maxxxxxdlp** [comment]
Actually, the screenshot I linked above is an unrelated bug. Opened #3213

**Comment by CarolineDenis** [comment]
@grantfitzsimmons could you give me more info about this? I tried to reproduce, here is the behavior I am having

https://github.com/specify/specify7/assets/108160931/3d88b27c-9ed3-429a-aa0e-4746b024759e

**Comment by CarolineDenis** [comment]
@grantfitzsimmons will verify if still an issue

**Comment by grantfitzsimmons** [comment]
Cannot recreate
