### ISSUE TITLE
`Aggregator not found` for `determiners`, results in destructive error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3062]
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/37256050/221882326-f93dc430-30f1-496f-927b-660dc1bff420.png">

```
Aggregator not found

Stack:

w@https://sp7demofish.specifycloud.org/static/js/main.dd9fda1ab5e00ee21a11.bundle.js:2:98805
```

[Specify 7 Crash Report - 2023-02-28T14 25 01.993Z.txt](https://github.com/specify/specify7/files/10851216/Specify.7.Crash.Report.-.2023-02-28T14.25.01.993Z.txt)

This happened after putting `determiners` as a field on the Determination form

> That seems to crash S7... I'm getting an error messages saying "Error: Aggregator not found". Tried to add an aggregation in S6 but no fields are available.
>
> ![image](https://user-images.githubusercontent.com/37256050/221883402-f0e08d01-5c1d-43c4-afbe-c233c31de6f6.png)

**Reported By:** CSIRO

**Comment by maxxxxxdlp** [comment]
If you have opportunity, can you please try this on the `xml-editor` branch?

**Comment by emenslin** [comment]
Fixed
