### ISSUE TITLE
Give previews a link to its record

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3072]
Would be nice if the formatter/aggregator previews had links to the records they are previewing for validating/sanity checks.

![image](https://user-images.githubusercontent.com/103299204/222283436-c416069e-bbde-4336-911e-b862dd984ed0.png)

**Comment by maxxxxxdlp** [comment]
Great idea!
Fixed

**Comment by chanulee1** [comment]
Works great! Very helpful for validation.
