### ISSUE TITLE
"Year" in date picker non-functional in 7.8.7

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3075]
https://user-images.githubusercontent.com/37256050/222444898-a54ad7be-ef08-46ef-bd6a-0723cd626931.mov

https://sp7demofish.specifycloud.org/specify/view/collectionobject/1112/?recordsetid=20

This applies to **all deployments** using 7.8.7

![image](https://user-images.githubusercontent.com/37256050/222445303-2e1fdffc-4913-46bc-91b8-166c41545bc7.png)

In summary, this needs to be fixed ASAP

**Comment by grantfitzsimmons** [comment]
This is a display bug only, the year is the only data that is preserved

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-7-1-release-announcement/1079/1
