### ISSUE TITLE
All plugin components are non-functional in 7.8.7

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3076]
In `v7.8.7`:

<img width="365" alt="image" src="https://user-images.githubusercontent.com/37256050/222449933-1e90ee09-bf87-42b8-97ab-250e38d9f444.png">

In `v7.8.6`:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/37256050/222449735-4db283e6-df12-440d-9064-c30bc8dd003c.png">

https://purdueherbaria11023-edge.test.specifysystems.org/specify/view/collectionobject/new/
Arthur Fungarium collection

```xml
                   <cell type="label" label="Host Plant"/>
                   <cell type="field" id="55" uitype="plugin" name="this" initialize="name=HostTaxonPlugin;relname=HostPlant"/>
```

**Comment by grantfitzsimmons** [comment]
https://purdueherbaria11023-edge.test.specifysystems.org/specify/view/collectionreltype/1/

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/37256050/222451441-7914b528-0c56-46e7-997b-75852c5b2639.png">

Using some custom forms, I can see that this rel is properly established

**Comment by grantfitzsimmons** [comment]
This looks like the bug is deeper than that. All plugins are read-only

https://purdueherbaria11023-edge.test.specifysystems.org/specify/view/locality/new/

**Comment by grantfitzsimmons** [comment]
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/37256050/222471512-70a1d9fd-d4f8-4334-911e-0e5f5b42cc7b.png">

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-7-1-release-announcement/1079/1
