### ISSUE TITLE
Cannot add Host Taxon

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3078]
> I am still unable to add host taxa.
> 
> **Steps to Recreate:**
> 
>     Entering new object, I found that the host wasn’t in the current list.
>     Tried to add a new host, but did not save it after having second thoughts.
>     Opened a new tab in my browser and navigated to our “Host” tree to see if I could add a host from there, but didn’t do anything after looking at it, thinking it may cause further problems.
>     Came back to the initial object, finished entering all of the info, but then got the error message when I tried to save.
>     I’ve seen this happen before, so I added everything but the host info, and everything else saved fine. But I’ve still been unable to save any host info without an error message.
> 
> Another thing I discovered today, when trying to return a loan, was an error message when I tried to resolve all items in the loan. That error message is attached.
> 
> [Specify 7 Crash Report - 2023-03-02T00_25_38.314Z.txt](https://github.com/specify/specify7/files/10872245/Specify.7.Crash.Report.-.2023-03-02T00_25_38.314Z.txt)
> 
> I have received error messages from hosts and loan returns before, but it seems that they may still be an issue, or I’m doing the same thing wrong. If there is some behavior that I should be avoiding, please let me know so that I can advise other Herbaria workers. 

On `v7.8.6` on Specify Cloud

**Reported By:** Rabern at Purdue Herbaria

**Comment by melton-jason** [comment]
I can not seem to replicate the Host Taxon issue on the test panel on Specify `v7.8.6` (https://purdueherbaria11023-v786.test.specifysystems.org/specify/).
Could you please provide a video or screenshot recreating the error? 

It looks like the attached crash report is regarding the loan return issue. 
Does the same error`"IntegrityError(1048, "Column 'DisciplineID' cannot be null")` occur for the Host Taxon issue?

**Comment by melton-jason** [comment]
Is this able to be recreated?

**Comment by grantfitzsimmons** [comment]
Closing until it can be recreated
