### ISSUE TITLE
Changing a user's collection access removes the user's admin status.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#308]
If a user is an admin, changing which collections they have access to through the "manage users" tool, will cause them to no longer be an admin.

This is mainly a problem if an admin user changes their own accessible collections causing them to lose admin status and thus unable to revert the change.

I'm going to make this a low priority bug, since I can't imagine a situation where an admin would be changing their own collection access which would ordinarily be all collections.

**Comment by benanhalt** [comment]
Not that inconceivable after all.

**Comment by maxxxxxdlp** [comment]
Superseded by https://github.com/specify/specify7/issues/833
