### ISSUE TITLE
Export to KML does not work

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3088]
Export a Locality query with coordinates to KML and see that it does not work.

Version 7.8.5 and 7.8.6 have been tested and it's not working.

**Reported By:** CSIRO

> Hey Grant, I've noticed potentially a big bug and I can't see a github for it - the KML export button seems to be broken? I just tested it on your demo site: https://sp7demofish.specifycloud.org/specify/query/61/

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-8-release-announcement/1108/1
