### ISSUE TITLE
Uploading Collection Object Rels not working in the WorkBench

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3089]
> A big bug I may have found is to do with using the workbench to add collection relationships - before we went live last year I tested this and all I had to do was map the left and right catalog numbers:
> image.png
>  
> ![image](https://user-images.githubusercontent.com/37256050/222730121-140cc2cb-488e-4437-a6b6-eaf8156612a1.png)
> 
> However now this doesn't work at all - if I do this from our specimen collection its is creating the right-side catalog number as a new CO in the specimen collection rather than just creating a link between. Has this behaviour changed in the recent upgrades?
> 
> This is a bit of a serious issue because Corinna is travelling to Hobart to get the fish collection voyage data uploaded into the production system

**Reported By:** Dan at CSIRO

**Comment by grantfitzsimmons** [comment]
I was able to recreate this on the `demofish` instance. This was working in an earlier update and there is no clear indication when this behavior changed. 

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/37256050/222731989-3dc37b3a-fc39-4805-b0cd-c290781371ec.png">

Instead of matching it to the right side collection's object, it either **creates a new record** in the current logged in collection or **matches it** to a record in the current logged in collection.

**Expected Behavior:**
It should link to the other collection's record based on the catalog number.

[https://sp7demofish.specifycloud.org/specify/workbench/21/](https://sp7demofish.specifycloud.org/specify/workbench/21/)

**Comment by melton-jason** [comment]
> <img alt="image" width="478" src="https://user-images.githubusercontent.com/37256050/222734326-786df394-ceb3-4f57-9ae6-0a17c8e64bbb.png">
> 
> It falsely reports that both are in the KUFishtissue collection while the links are to two distinct records in two collections.

The Collection Object with Catalog Number `000010408` _is_ in the KUFishtissue collection. 

When the record is viewed in the Autogenerated form, it becomes clear that it is using the Left Side Rel relationship. 

![issue_3089](https://user-images.githubusercontent.com/64045831/222807116-f6aa820b-5f23-4363-80ef-98515aaca822.png)

Currently, only the `Left Side` Collection Object is being displayed in the normal form view, but the `Right Side` Collection Object is being linked.  Is this correct?

**Comment by danb213** [comment]
As part of this problem we also saw that it was using the regex formatting for the left-side collection as part of the validation check on the right-side catalog number which would be another issue for us since our collections have different rules!

**Comment by melton-jason** [comment]
I can confirm the issue is _only_ effecting CollectionRelationships uploaded through the workbench. CollectionRelationships manually added work as intended.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-12-release-announcement/1202/1
