### ISSUE TITLE
when you edit a data record then create a new record set without saving, you are not warned your changes to the data record will be lost until you save the mapping

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#309]
Click workbench and create a new data set.  Create your mapping and click Done.  A prompt will appear asking you to name it.  Give it a name, then click Save.  Another prompt appears saying "Leave Page? This form has not been saved."

**Comment by tlammer** [comment]
Just kidding.  Ignore.

**Comment by tlammer** [comment]
So the beginning of that first comment should be:
Either create a new record or open an existing record and edit it.  Do not save, then 
Click workbench and create a new data set. Create your mapping and click Done. A prompt will appear asking you to name it. Give it a name, then click Save. Another prompt appears saying "Leave Page? This form has not been saved."
There should be a warning a bit earlier.

**Comment by benanhalt** [comment]
Probably should make defining a new mapping be a new page which would trigger the leaving page mechanism.

**Comment by maxxxxxdlp** [comment]
Fixed in 7.6.00
