### ISSUE TITLE
Deleting agent leads to a null id error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3092]
https://user-images.githubusercontent.com/37256050/222790736-e1338fb3-1540-44cd-b6b3-136038a91a5a.mov

https://purdueherbaria11023-edge.test.specifysystems.org/specify/view/loan/54/

My crash report (debug):
[Specify 7 Crash Report - 2023-03-03T17 41 21.160Z.txt](https://github.com/specify/specify7/files/10885468/Specify.7.Crash.Report.-.2023-03-03T17.41.21.160Z.txt)

DisciplineID appears to be missing

Rabern's crash report:
[Specify.7.Crash.Report.-.2023-03-02T00_25_38.314Z.txt](https://github.com/specify/specify7/files/10885469/Specify.7.Crash.Report.-.2023-03-02T00_25_38.314Z.txt)

```
responseText": "Field 'id' expected a number but got 'null'."
```

`Arthur Fungarium` collection

**Steps to Recreate:**

Delete `Koch, Rachel A` from the Loan Agent field
See that it immediately crashes

**Reported By:** Rabern at Purdue Herbaria

**Comment by maxxxxxdlp** [comment]
Caused by business rules

**Comment by grantfitzsimmons** [comment]
@melton-jason is this a duplicate?

**Comment by emenslin** [comment]
Fixed
