### ISSUE TITLE
Aggregator Editor: Unexpected "Default" formatter/aggregator behavior

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3097]
Creating a formatter or aggregator sets it as default if a default has not been set, but not for subsequent creations of formatters/aggregators. Maybe enforce a rule for there to be a default formatter/aggregator at all times to prevent this?

https://user-images.githubusercontent.com/103299204/223208856-ab7f75f3-93c3-482b-b81d-e21801e39c5a.mp4

**Comment by maxxxxxdlp** [comment]
Fixed by not making a newly added Formatter "Default" if there is any other formatter already and adding an error message 

if there is no default formatter, an error message is displayed

**Comment by chanulee1** [comment]
Fixed.
