### ISSUE TITLE
Aggregator Editor: Commenting out entire formatter/aggregator definition causes issues

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3098]
Commenting out an entire formatter/aggregator definition can create multiple references to the same definition in the visual editor.

1. Comment out an entire formatter/aggregator definition in the text editor and save
2. Create a new formatter/aggregator in the visual editor for the same table and save
3. Uncomment the formatter/aggregator and save
4. See that both formatter/aggregators refer to the original definition that was commented out

(Errors when creating new formatter is separate issue #3096)

https://user-images.githubusercontent.com/103299204/223231298-4a52c331-ad13-4072-9fe1-306195618212.mp4

**Comment by maxxxxxdlp** [comment]
This actually happens any time you have two formatters with the same name.
I am going to add an error message for this case

**Comment by chanulee1** [comment]
Appears to be fixed. Error message shows when there is two formatters with the same name.
