### ISSUE TITLE
Paginator is not aligned on the right in dialogs

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3101]
<img width="2283" alt="image" src="https://user-images.githubusercontent.com/37256050/223297712-a16ed0c4-cfe4-4a64-8313-02449270efa5.png">

It should be aligned on the right side.

`v7.8.7.1`

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-9-release-announcement/1131/1
