### ISSUE TITLE
Adding a child to a synonymized node returns an error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3102]
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/37256050/223462425-bafa49a1-16ba-425a-9332-4d00e528ad96.png">

https://unitec3623-edge.test.specifysystems.org/specify/tree/taxon/?conformation=%7E%7E1%7E14437%7E14438%7E14439%7E14440%7E14674%7E14685%7E14686---------

The Taxon form allows adding a child to a synonymized node when the trees explicitly prevent this.

```
TreeBusinessRuleException at /api/specify/taxon/
```
```
('Adding node "Max" to synonymized parent "Bacidiaceae"', {'tree': 'Taxon', 'localizationKey': 'nodeOperationToSynonymizedParent', 'operaton': 'Adding', 'node': {'id': None, 'rankid': 220, 'fullName': 'Max', 'parentid': 14692, 'children': []}, 'parent': {'id': 14692, 'rankid': 140, 'fullName': 'Bacidiaceae', 'parentid': 14686, 'children': [{'id': 6018, 'fullname': 'Bacidia'}]}})
```

This happens in `v7.7.5`, `v7.8.5`, and `v7.8.7.1`

[Specify 7 Crash Report - 2023-03-07T15 09 15.947Z.txt](https://github.com/specify/specify7/files/10910853/Specify.7.Crash.Report.-.2023-03-07T15.09.15.947Z.txt)

**Reported By:** Unitec Herbarium

**Comment by emenslin** [comment]
Fixed
