### ISSUE TITLE
Header overflow in app resources

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#3103]
note the buttons in the header

<img width="1015" alt="Screenshot 2023-03-07 at 09 37 53" src="https://user-images.githubusercontent.com/40512816/223471002-5805038f-e357-4925-ab39-77bcc8623b00.png">

Version 7.8.7.1

**Comment by maxxxxxdlp** [comment]
Can be fixed by adding `flex-wrap` to `<header>`:

<img width="1101" alt="Screenshot 2023-03-07 at 09 52 35" src="https://user-images.githubusercontent.com/40512816/223475192-3f81f33d-6cb3-447f-918b-02b31f91fbe7.png">

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-8-release-announcement/1108/1
