### ISSUE TITLE
Not all resources are displaying in the sidebar

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3104]
<img width="947" alt="image" src="https://user-images.githubusercontent.com/37256050/223474268-bcf99049-e988-40ba-af5b-e0c25ccd5552.png">

Saw on the `unitec` Specify Cloud deployment, can be recreated on the test panel.

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/37256050/223474445-03b88e05-11b9-4885-940c-c7f06bce51fe.png">

See that Global Prefs is not displaying in the app resources sidebar, this is on my local machine

**Comment by maxxxxxdlp** [comment]
Is this on the statspage branch?

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-8-release-announcement/1108/1
