### ISSUE TITLE
Combobox not being rendered on the form

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3107]
```xml
        <viewdef name="Shipment"
            type="form"
            class="edu.ku.brc.specify.datamodel.Shipment"
            gettable="edu.ku.brc.af.ui.forms.DataGetterForObj"
            settable="edu.ku.brc.af.ui.forms.DataSetterForObj">
            <desc><![CDATA[Shipment form.]]></desc>
            
            <columnDef>105px,2px,140px,5px,123px,2px,140px,5px,113px,2px,195px,0px,p:g</columnDef> 
            <columnDef os="lnx">115px,2px,150px,5px,118px,2px,168px,5px,126px,2px,230px,0px,p:g</columnDef> 
            <columnDef os="mac">130px,2px,195px,5px,136px,2px,195px,5px,120px,2px,240px,0px,p:g</columnDef>
            <columnDef os="exp">p,2px,p:g(2),5px:g,p,2px,p:g(2),5px:g,p,2px,p:g,0px</columnDef> 
            <rowDef auto="true" cell="p" sep="2dlu"/>
            <rows>
                <row>
                    <cell type="label" labelfor="2"/>
                    <cell type="field" id="2" name="shipmentNumber" uitype="text"/>
                    <cell type="label" labelfor="t1"/>
                    <cell type="field" id="t1" name="text1" uitype="text"/>
                    <cell type="label" labelfor="3"/>
                    <cell type="field" id="3" name="shipmentMethod"  uitype="combobox"/>
                </row>
                <row>
                    <cell type="label" labelfor="1"/>
                    <cell type="field" id="1" name="shipmentDate" uitype="formattedtext" uifieldformatter="Date" default="today"/>
                    <cell type="label" labelfor="4"/>
                    <cell type="field" id="4" name="numberOfPackages" uitype="text" default="1"/>
                </row>
            </rows>
        </viewdef>
```

Most importantly, 
```xml
 <cell type="field" id="3" name="shipmentMethod"  uitype="combobox"/>
```

But when I am on the Shipment form (https://workshop.specifycloud.org/specify/view/loan/new/):

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/37256050/223488455-5d896410-2262-4b2d-8f05-330ecddd2811.png">

It is displayed as a text box.

This is not the case on the test deployment (with the same schema and forms) (https://uwfcdonttouch13123reprise-v785.test.specifysystems.org/specify/view/loan/new/):

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/37256050/223488772-8026003b-67d0-4487-960d-5493e66aeb18.png">

I even made it into an actual pick list but it did not resolve the issue.

**Console Errors:**
<img width="506" alt="image" src="https://user-images.githubusercontent.com/37256050/223488671-8103db52-8f0c-4c0e-b2b8-f1555b9f93b9.png">

---

`v7.8.7.1`

**Comment by maxxxxxdlp** [comment]
Open the meta menu for Shipment subview, click on "Form Definition", and then on "Edit form definition"

You will see that the form definition is coming from a different file:

<img width="1800" alt="Screenshot 2023-03-07 at 12 42 47" src="https://user-images.githubusercontent.com/40512816/223519313-712b1e1a-190a-4bde-9c70-96d14acf38f9.png">
