### ISSUE TITLE
Merging a synonymized node with a non-synonymized node (or previously synonymized node) throws an error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3109]
**Steps to Recreate:**
1. Synonymize two nodes together
2. Attempt to merge, see error
3. Unsynonymize the two nodes
4. Attempt to merge, see error

https://sp7demofish.specifycloud.org/specify/tree/taxon/?conformation=%7E%7E1%7E15797%7E17025%7E3%7E10%7E250%7E3505-%7E4489----%7E15789%7E15809%7E15581%7E5194%7E12939-%7E12614---------

```
Cannot delete some instances of model 'Taxon' because they are referenced through protected foreign keys: 'Determination.preferredtaxon', 'Determination.taxon'
```

​It looks like a synonym or a once-synonymized node is not able to be merged because the preferred taxon still references the un synonymized node. 

```
AttributeError
'NoneType' object has no attribute 'groups'
Content

"None"

Show Traceback

Traceback (most recent call last):
  File "/opt/specify7/specifyweb/specify/tree_extras.py", line 284, in merge
    node.delete()
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/base.py", line 966, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/deletion.py", line 302, in collect
    raise ProtectedError(
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'Taxon' because they are referenced through protected foreign keys: 'Determination.taxon'.", {<Determination: Determination object (23351)>})

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/specify7/specifyweb/specify/views.py", line 29, in wrapped
    return view(request, *args, **kwargs)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
```

[Specify 7 Crash Report - 2023-03-07T17 19 27.388Z.txt](https://github.com/specify/specify7/files/10912099/Specify.7.Crash.Report.-.2023-03-07T17.19.27.388Z.txt)

**Reported By:** AAFC (Heather Cole)

**Comment by melton-jason** [comment]
> ```
> Cannot delete some instances of model 'Taxon' because they are referenced through protected foreign keys: 'Determination.preferredtaxon', 'Determination.taxon'
> ```
> 
> ​It looks like a synonym or a once-synonymized node is not able to be merged because the preferred taxon still references the un synonymized node.

The code is built to handle this:

https://github.com/specify/specify7/blob/f4bb46a084791c9662e53cc56c487652ac537ee0/specifyweb/specify/tree_extras.py#L282-L293

The issue is in the line:  `related_model_name, field_name = re.search(r"'(\w+)\.(\w+)'$", e.args[0]).groups() `
It looks like `re.search(r"'(\w+)\.(\w+)'$", e.args[0])` is returning `None`

From the [python docs on re.search()](https://docs.python.org/3/library/re.html#re.search) :
``` 
Return None if no position in the string matches the pattern
```
From the code, it looks like we are _always_ expecting a match for the regex.

**Comment by maxxxxxdlp** [comment]
This could have stopped working due to python update

**Comment by grantfitzsimmons** [comment]
@melton-jason Heather cannot keep working with her tree until this is solved.

**Comment by grantfitzsimmons** [comment]
> Following your feedback, I moved to the Brassicaceae family, it is still messy, and I have mostly been ignoring that branch of the tree (in the past weeks), as most records are in the BrassCan collection. I don’t think I have done much synonomy of nodes in there, and certainly not anytime recently (I don’t think?)
> 
>  
> 
> I am wondering if the tree cleanup had some unintended consequences to part of the tree? Or if the crashes are blocking something? I haven’t been able to complete any merges successfully since I first sent the crash report.
> 
>  
> 
> In this case, I tried to merge
> 
> https://aafc-aac.specifycloud.org/specify/view/taxon/197254/
> 
> into
> 
> https://aafc-aac.specifycloud.org/specify/view/taxon/201616/
> 
> and received the error message (log attached; ending in 518Z)
> 
>  
> 
> I tried another node; at the time of the error message was displayed, the URL of the Tree page I was working on was
> https://aafc-aac.specifycloud.org/specify/tree/taxon/?conformation=%7E%7E1%7E181107%7E4690%7E5977%7E197387-%7E5986------
> 
> This time I was trying to merge
> 
> https://aafc-aac.specifycloud.org/specify/view/taxon/197387/
> 
> into
> 
> https://aafc-aac.specifycloud.org/specify/view/taxon/5986/
> 
> (crash report ending in 634Z)
> 
>  
> 
> Tree URL before I tried the merge:[ https://aafc-aac.specifycloud.org/specify/tree/taxon/?conformation=%7E%7E1%7E181107%7E4690%7E4915%7E172053-%7E201664------](https://aafc-aac.specifycloud.org/specify/tree/taxon/?conformation=%7E%7E1%7E181107%7E4690%7E4915%7E172053-%7E201664------)
> 
> URL when I got the error message;[ https://aafc-aac.specifycloud.org/specify/tree/taxon/?conformation=%7E%7E1%7E181107%7E4690%7E4915%7E201664-%7E172053------](https://aafc-aac.specifycloud.org/specify/tree/taxon/?conformation=%7E%7E1%7E181107%7E4690%7E4915%7E201664-%7E172053------)
> 
> (crash report ending in 215Z)
> 
> https://aafc-aac.specifycloud.org/specify/view/taxon/201664/
> 
> into
> 
> https://aafc-aac.specifycloud.org/specify/view/taxon/172053/
> 
>  
> 
> Last try, trying to go somewhere entirely different….
> 
> Pre-merge effort URL: https://aafc-aac.specifycloud.org/specify/tree/taxon/?conformation=%7E%7E1%7E181107%7E9287%7E9832-%7E9579%7E190039-%7E188168------
> 
> After (with error): https://aafc-aac.specifycloud.org/specify/tree/taxon/?conformation=%7E%7E1%7E181107%7E9287%7E9832-%7E9579%7E190039-%7E188168------
> 
> Trying to merge this: https://aafc-aac.specifycloud.org/specify/view/taxon/190039/
> 
> Into this: https://aafc-aac.specifycloud.org/specify/view/taxon/188168/
> 
> (Crash report 556Z)
