### ISSUE TITLE
Searching for a specific name does not return the name alone

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3110]
<img width="823" alt="image" src="https://user-images.githubusercontent.com/37256050/223500603-a99aae39-12bd-433d-a3cb-b0db6d0958a6.png">

When searching for "Astragalus" in the `aafc_aac` database, you cannot just return the name of the Genus.

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/37256050/223500892-26d46d8c-b8f5-4ea6-887b-1d93b82b6d3e.png">

Even though this record exists, the QCBX cannot search on it when trying to select it as the parent.

**Reported By:** Heather Cole at AAFC

**Comment by maxxxxxdlp** [comment]
Unable to replicate on the `aafc_aac_DAO` database on the test server:

<img width="1800" alt="Screenshot 2023-03-07 at 12 10 35" src="https://user-images.githubusercontent.com/40512816/223511560-d496e2cf-3178-4267-8415-f07bd943cb75.png">

**Comment by maxxxxxdlp** [comment]
Can we get a newer back up on the test panel?
Either that genus was deleted, or TypeSearches app resource was modified

**Comment by CarolineDenis** [comment]
@grantfitzsimmons is this still an issue?

**Comment by CarolineDenis** [comment]
cannot replicate.
