### ISSUE TITLE
Cannot create new record sets from scratch

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3124]
This is in the `osuorton_3_8_23` database on the test panel.

You can also experience the joy of https://github.com/specify/specify7/issues/2782 in the video!

https://user-images.githubusercontent.com/37256050/223844621-5da8fd55-0beb-4549-853d-3adfd129740b.mp4

**Steps to Recreate:**
1. Create a new empty record set
2. Add a recod
3. See that the record now exists in the database (but not in the record set)

**Intended Behavior:**
It should add the new record to the newly created record set.

**Reported By:** The Ohio State University

**Comment by grantfitzsimmons** [comment]
I couldn't replicate on most other databases, but I could on `osuorton`

**Comment by maxxxxxdlp** [comment]
Hmm, doesn't happen for me!

**Comment by CarolineDenis** [comment]
I cannot replicate it on the new Mac Book. The problem might be related to performance then

**Comment by grantfitzsimmons** [comment]
I can consistently replicate it on Firefox, M1 Pro, and so can they

**Comment by grantfitzsimmons** [comment]
I can replicate again on Firefox, M1 Pro

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-9-release-announcement/1131/1
