### ISSUE TITLE
Auto-generated query title has only 1 quote

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3126]
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/37256050/223848450-7acdc7ab-a1a4-45a9-bb51-10b4aadf0471.png">

```
Query: Collection Object using "Myxinidae
```

Should have another quote at the end

https://sp7demofish.specifycloud.org/specify/query/fromtree/taxon/250/

**Comment by melton-jason** [comment]
Has this issue been fixed?

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-12-release-announcement/1202/1
