### ISSUE TITLE
Interpret all independent subviews as buttons

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3127]
## When #3125 is added

We will need to have Specify 7 interpret independent subviews defined as things other than a button as a button automatically for backward compatibility with our existing forms.

This would allow all form definitions in the wild to take advantage of the ability to use independent subviews.

**Comment by maxxxxxdlp** [comment]
Does it make sense to have a pref for disabling this behavior?
Or should we only disable this behavior if sub view is rendered as read only for reasons unrelated to relationship being independent? (i.e, the view definition says the view should be read-only, or lack of edit permissions)?

**Comment by grantfitzsimmons** [comment]
We should disable this behavior only when it is read-only or no permissions
