### ISSUE TITLE
Default values set in the WorkBench for preparation type do not link correctly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3129]
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/37256050/223852223-337d38b8-27ed-4ff1-bfa8-708c41ddabef.png">

<img width="379" alt="image" src="https://user-images.githubusercontent.com/37256050/223852246-5f3d35c2-dd70-436b-9c4e-9a7524a0cede.png">

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/37256050/223852323-48c3faf3-9597-4147-bddb-a06eace37369.png">

https://nbmfishcollectionimport-edge.test.specifysystems.org/specify/workbench/17/

It requires the prep type to be disambiguated. If you just type "N/A" (for this database) into the import document, this is not a problem

**Comment by emenslin** [comment]
Fixed
