### ISSUE TITLE
When creating new gift, choosing ship-to agent without an address gives a validation error and adding an address does not remove the error.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#313]
E.g. choose "User, Test" for the ship-to agent. The field turns red because the agent has no address. Clicking the edit icon (pencil) allows an address to be added. Save the agent. The ship-to field stays red and will only be accepted if the field is cleared before re-selecting the "User, Test" value.

**Comment by maxxxxxdlp** [comment]
Unable to replicate. I don't get validation errors when attaching a "Ship To" agent that does not have an address
