### ISSUE TITLE
Aggregator Editor: Improve button/page distinction

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3137]
Currently, it is a little hard to tell which buttons are toggled on or off. This makes it difficult to tell whether one is on the aggregator or formatter page. Would be nice if either the buttons were changed or something was added to better distinguish them.

https://user-images.githubusercontent.com/103299204/224102536-1bd637f4-f076-440f-be1c-708302125e38.mp4

**Comment by maxxxxxdlp** [comment]
Fixed by increasing contrast for active buttons

Please test both in light mode and dark mode

**Comment by chanulee1** [comment]
Contrast increased, easier to distinguish in both light and dark mode.
