### ISSUE TITLE
Aggregator Editor: Creating formatter files in different collections causes error

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3138]
The new editing restriction causes parsing errors when formatter files are created in collections other than the one the user is currently logged in to.

https://user-images.githubusercontent.com/103299204/224108887-34436fa5-437f-46b0-959e-163a29e10a53.mp4

[Specify 7 Crash Report - 2023-03-09T17_35_41.605Z (1).txt](https://github.com/specify/specify7/files/10934400/Specify.7.Crash.Report.-.2023-03-09T17_35_41.605Z.1.txt)

**Comment by maxxxxxdlp** [comment]
Fixed in b59a89ead and f158c391a
Bug was happening even if creating a formatter resource in the same collection (i.e, at a User Type level)

**Comment by chanulee1** [comment]
Fixed. Able to create formatter resources in different collections, user types, user accounts.
