### ISSUE TITLE
Query results not being filtered correctly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3139]
https://user-images.githubusercontent.com/37256050/224109025-9a5fb5db-358c-4edc-a31b-119d31a61009.mp4

https://coldfish-edge.test.specifysystems.org/specify/query/195/

This same query, without any changes, does not return any results if you set the catalog number equal to `177`.

This makes no sense, since without any catalog number value, it _returns_ 177.

**Comment by grantfitzsimmons** [comment]
This is concerning 🤨

**Comment by emenslin** [comment]
Fixed
