### ISSUE TITLE
Overflow in security panel

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3140]
https://user-images.githubusercontent.com/103299204/224111847-bb12b49a-8696-491f-a64d-8f826487927a.mp4

https://coldfish-edge.test.specifysystems.org/specify/security/institution

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-8-release-announcement/1108/1
