### ISSUE TITLE
Label showing author as `null`

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3141]
## **Problem:**

The author is not displaying (displaying as `null`) on CSIRO's labels in Specify 7 whereas it does display correctly in Specify 6 and in query results. It looks like there is a bug in the way 7 handles reports.

#### The problem:

Works in 6, not in 7

![image](https://user-images.githubusercontent.com/37256050/224113114-4c13212e-1b59-4269-9892-714a834722d4.png)

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/37256050/224111304-cfcc6297-8daa-49fa-bc78-ffe9965ec65b.png">

<img width="603" alt="image" src="https://user-images.githubusercontent.com/37256050/224112330-281ef557-495a-419c-8df1-6eaa86a179e3.png">

## **Links:**

The report and query are available on the test panel's `coldfish` database.

https://coldfish-edge.test.specifysystems.org/specify/resources/app-resource/173/ <- Here is the JRXML definition

Here's the specific snippet:

```xml
<textFieldExpression   class="java.lang.String"><![CDATA[$F{1,9-determinations,4.taxon.author}]]></textFieldExpression>
```

Expression in iReport:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/37256050/224111959-46c8b7b1-c90b-4ef5-b159-18ed720ccd2e.png">

It is displayed correctly in the query results:

<img width="2211" alt="image" src="https://user-images.githubusercontent.com/37256050/224111873-3d8f6c7d-412a-4e2f-ace0-d21b8631e0e7.png">

**Associated Query:**
https://coldfish-edge.test.specifysystems.org/specify/query/195/
[Report_Adult Label TYPE.json.zip](https://github.com/specify/specify7/files/10934565/Report_Adult.Label.TYPE.json.zip)

**SCC Vault:** [Specify 6 Report Export](https://drive.google.com/open?id=1DVAtd-6aO1x9filFKxiOPeub8fXhL5qA&authuser=grant%40specifysoftware.org&usp=drive_fs)

---

**Report Runner Output:**

[Sp7_Output.pdf](https://github.com/specify/specify7/files/10934532/Sp7_Output.pdf)
[Sp6_Output.pdf](https://github.com/specify/specify7/files/10934531/Sp6_Output.pdf)

---

**Reported By:** Corinna P at CSIRO ([Asana](https://app.asana.com/0/1201972579963460/1204133778858353/f))

> We’ve been tidying up some of our reports and I came across an issue with the taxon.author field. I have added the field to a label report. Values for it show up just fine in the underlying query in S6 and S7, however, the value is only displayed in the S6 report. When I run the report in S7 the field is blank (or shows null when the ‘Blank when null’ is not ticked). See screenshots for details.
>
> ![image](https://user-images.githubusercontent.com/37256050/224113900-37e39f20-7d8a-409c-9ff9-404eebb854da.png)

**Comment by grantfitzsimmons** [comment]
> In Specify 7, when I print labels from a record set or generate a label from the Collection Object form everything is fine, but when I do ‘Run report’ directly on a query, the authorship of the taxon name is missing. 
>
>I have a rather involved expression to format the taxon name string on our labels, as we include identification qualifiers (and in the ABCD way, not according to the Specify data model), but I do not see how that explains the problem. 
>
> It is the same for all labels, but you can try the ‘Standard sheet label  - 4 per page’ one.

**Steps to Recreate:**
1. Log into the `melisr_4_26_23` database on the test panel as `nklazenga`
2. Use collection `National Herbarium of Victoria`
3. Print ‘Standard sheet label  - 4 per page’ for any record in a variety of ways. [Record set for convenience](https://melisr42623-v7810-prerelease.test.specifysystems.org/specify/view/collectionobject/971174/?recordsetid=28988).
4. See that when you print labels based on a record set or from the form, all information is included.
5. See that when you print labels by following these steps, authorship is not included.
    i. Go to **Reports** -> **Standard sheet label - 4 per page** -> **Query**
    ii. Enter set `Catalogue no.` = `2403806`, then click **Run Report**
    iii. See authorship is missing next to the determined taxon name

# **Report Results:**

**Left**: Result when run from the Reports dialog, then `2403806` is entered as the catalog number manually.
**Right**: Result when run from the button on the form or from a record set containing `2403806`.

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/37256050/236239703-0059eb55-34d5-4ca4-99e1-37022f3bd51f.png">

Missing authorship:

![image](https://user-images.githubusercontent.com/37256050/236241466-77180d93-3f7c-49a6-92bf-4aec2a684fc8.png)

**Reported By:** Niels Klazenga at RBGV

**Comment by grantfitzsimmons** [comment]
**Reported By:** Siyabonga at KwaZulu-Natal Museum

**Comment by maxxxxxdlp** [comment]
Seems like a big bug that affects a founding member. This issue requires more attention

**Comment by grantfitzsimmons** [comment]
Max is right. Need to really bump this in priority.

**Comment by grantfitzsimmons** [comment]
Once again, need to bump this! Reported again by NMC

**Comment by grantfitzsimmons** [comment]
![image](https://github.com/specify/specify7/assets/37256050/b42d7dca-8aad-4cb3-b8a8-23bad08abf3e)

**Comment by realVinayak** [comment]
Forgot to document this, but changing author to Author fixed it

**Comment by CarolineDenis** [comment]
Fixed by https://github.com/specify/specify7/pull/4299
