### ISSUE TITLE
Create new specify user page missing "name" field

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3161]
`7.8.6`:
![image](https://user-images.githubusercontent.com/103299204/224777330-3890e7ee-8066-4a54-903f-c86283e51447.png)

`edge`:
![image](https://user-images.githubusercontent.com/103299204/224777466-dcf12ce6-73da-4d2c-9c8a-45924a45af87.png)

Cannot create new users because of this.

**Comment by maxxxxxdlp** [comment]
I'm able to reproduce #3164, but not this one just yet
@chanulee1  Does this issue happen in any database or a specific database?
