### ISSUE TITLE
Schema Config has redundant scroll bars 

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#3167]
(under my user agent style sheet scroll bars are visible as 1px white strips, but the bug is reproducable even without that)

Notice the white line in bottom and right corner
Also, notice the text being cut of in first column if you scroll right

<img width="1800" alt="Screenshot 2023-03-13 at 19 48 21" src="https://user-images.githubusercontent.com/40512816/224863993-09a13acd-b423-4cc6-89d9-6a2c75bb45b9.png">

Caused by this change:

https://github.com/specify/specify7/commit/1a7d7e568#diff-8bf9d9d2b07370b0ab9e7e9e68f3798b5a9b6542c065cc90c177c9a049993c53

@CarolineDenis do you remember why that was made?

Reverting that or removing `overflow-hidden` fixes this issue (but causes other?)

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-9-release-announcement/1131/1
