### ISSUE TITLE
Query comboboxes require at least 3 characters to search

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#317]
Query comboboxes, such as agent or collecting event linking fields, require at least 3 characters before the user can click the down arrow.  However, some last names and some station field numbers are only two characters long, meaning they can't hit the down arrow.
They can still click the magnifying glass to search for records, but it is a bit of a pain.

**Comment by yvonneekanim** [comment]
Tested in UTAustinpaleo and testinvp. Query comboboxes allow single character search.
