### ISSUE TITLE
Add a way to always use query builder for query combo box search

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#3171]
Add a way to always use query builder for query combo box search instead of using Specify 6's search dialogs

Edit:
added a Form -> Query Combo Box - >Always use Query Builder prop to disable search dialogs entirely as their usefulness is questionable.

See also #3173

**Comment by maxxxxxdlp** [comment]
It's a bug.
The behavior for when that pref is off should not have changed.

**Comment by chanulee1** [comment]
Appears to still happen.

![image](https://user-images.githubusercontent.com/103299204/226686457-b2b3ba73-f185-49ea-87e7-05700cb7454b.png)

**Comment by maxxxxxdlp** [comment]
> Appears to still happen.

@chanulee1 
This is the standard agent search form. If there is no other problem, this issue can be closed

**Comment by chanulee1** [comment]
Looks good on `xml-editor`. Option for using query builder in query combo box search seems to work.
