### ISSUE TITLE
Stop using "DialogDefs" app resource

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#3173]
To break away from sp6

It was only used by sp7 to get the search view name.

For every table except for GeologicTimePeriod, the search view name is `<tableName>Search`.

Thus, not need for an app resource.

If users wish to customize this, added a `searchView` prop to the `initialize=""` attribute of the query combo box - see docs

Also added a Form -> Query Combo Box - >Always use Query Builder prop to disable search dialogs entirely as their usefulness is questionable.

**Comment by maxxxxxdlp** [comment]
Fixed in https://github.com/specify/specify7/commit/9fb300803ed36080308eb049f65759e2a5ccfa4c and [9576e4829](https://github.com/specify/specify7/commit/9576e4829)

**Comment by chanulee1** [comment]
How do I test this?

**Comment by maxxxxxdlp** [comment]
1. Rename the `DialogDefs` app resource
2. Clean cache
3. Check that the search button in query combo boxes still opens the same search form as it did before this change

**Comment by chanulee1** [comment]
Search form appears to be the same whether `DialogDefs` is used or not.
