### ISSUE TITLE
Add UI for editing WebLinks

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#3176]
- [x] Add UI for editing WebLinks
- [x] Allow using relationships in web links
- [x] Allow editing WebLinks that are not scoped to a table
- [x] Allow using formatters in web links
- [x] Add support for "prompt" fields

**Comment by chanulee1** [comment]
Cannot add new weblinks through the editor.


https://user-images.githubusercontent.com/103299204/230684277-6a3bea22-2516-40b9-9506-2d1fe27d459d.mp4


Cannot close editor dialog.

https://user-images.githubusercontent.com/103299204/230684799-f49356d9-e834-4082-bf42-5759059f4a52.mp4

https://coldfish-xml-editor.test.specifysystems.org/specify/schema-config/en/Agent/

**Comment by chanulee1** [comment]
Appears to be problems with weblinks containing the "prompt field" component. Cannot close the dialog, and cannot go to website specified by url. Weblink works properly when using the "this field" component instead.

https://user-images.githubusercontent.com/103299204/231574916-89b66e2c-7307-4390-b7bc-0a2d239408c3.mp4

https://coldfish-xml-editor.test.specifysystems.org/specify/view/collectionobject/162/
<br>
Weblink definition:
<img width="50%" height="50%" src="https://user-images.githubusercontent.com/103299204/231575081-c18c8991-14e6-46c8-9775-f60083745e91.png"/>

https://coldfish-xml-editor.test.specifysystems.org/specify/resources/app-resource/210/web-link/6

**Comment by maxxxxxdlp** [comment]
> Would these issues be fixed by merging agent-merging?

Yes. Also, Grant already opened a separate issue for this where the fix for this will be tracked https://github.com/specify/specify7/issues/3192

**Comment by chanulee1** [comment]
Sorry. Did not mean to close.

**Comment by chanulee1** [comment]
Weblink containing field from table inserts "list" into url when the field is empty.


https://user-images.githubusercontent.com/103299204/232595668-51e6ed6c-0967-4819-81cb-2bfb44be9ab4.mp4

https://coldfish-xml-editor.test.specifysystems.org/specify/resources/app-resource/210/web-link/12

**Comment by maxxxxxdlp** [comment]
> Weblink containing field from table inserts "list" into url when the field is empty.

That's not specify doing this. It's a redirect by behindthename

I.e, try going to https://behindthename.com/name in the browser and see the same behavior
