### ISSUE TITLE
`xml-editor`: Use space as separator by default

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3185]
<img width="331" alt="image" src="https://user-images.githubusercontent.com/37256050/225667877-4a394aec-81ff-4b34-9a4d-ffb3fbdfe19d.png">

While this system makes sense for a technical user, it seems unintuitive to need to put a separator manually after adding a field

**Comment by maxxxxxdlp** [comment]
Fixed.
Also changed default separator for aggregators to `;` as `,` is commonly used in formatters

**Comment by chanulee1** [comment]
Space is default delimiter for formatters, semicolon used as default for aggregators.
