### ISSUE TITLE
`xml-editor`: Add tooltips to explain what each section means

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3186]
<img width="889" alt="image" src="https://user-images.githubusercontent.com/37256050/225668412-6cd5eeb1-19a0-4c08-91ff-7509e05c7596.png">

For instance, to a user, 

> 
> What does "Condition Field" mean? What do I type in "Condition"?
> 
> Why are there now two sections?

These are somewhat easy to explain, but there should be some tip to indicate what this does and examples of how it works. Documentation is necessary as well

**Comment by grantfitzsimmons** [comment]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/37256050/225700084-d9ea9cd8-3b5b-4234-857c-c42344036286.png">

Same for the difference between a formatted and an aggregator

**Comment by maxxxxxdlp** [comment]
Added the following description for the Condition field:

> This formatter will be used only if the condition field value is equal to this condition

Please adjust for clarity if needed
Please tell if you prefer to show that as a tooltip instead

Asked ChatGPT for a user friendly description for formatters/aggregators 😂 :
> Formatters are like chefs who prepare individual ingredients by cutting and seasoning them, while aggregators are like servers who arrange these ingredients on a plate, creating a visually appealing and delicious meal.

My mistake was saying to make it non-technical.

A better result with a better prompt:

> Formatters: These are tools that help transform individual database resources into readable text by selecting specific fields and applying a designated separator between them.

And after manual human editing:

> Formatter determines how to transform a database resource into a text string by selecting specific fields and joining them with a separator.
