### ISSUE TITLE
`xml-editor`: Preserve white space in XML

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3187]
<img width="1811" alt="image" src="https://user-images.githubusercontent.com/37256050/225699805-7c071a4a-33a2-4c17-a122-1bf5f84ae4f6.png">

This may not be feasible, but the XML is converted into a format that is impossible to work with for a human after being used with the visual editor.

**Comment by maxxxxxdlp** [comment]
Fixed. Please do good testing for this:
Very long lines
Elements with nested elements
Elements with comments
Short lines (should not be wrapped)
Lines with a lot of indents before them
Indentation added by reformatting should match what's set in user preferences

**Comment by maxxxxxdlp** [comment]
> Also, the "line wrap" option in user prefs does not seem to have effect on line wrapping. Line wrapping happens after editing in visual editor even when the option is off.

That option affects whether the editor should wrap long lines or have a horizontal scroll bar. It does not affect how the resulting XML get's formatted (in this case, the formatting splits long lines into multiple lines)

**Comment by maxxxxxdlp** [comment]
> Top level comments deleted after editing in visual editor. Issue?

Good discovery. However, this is not allowed according to the XML standard so we can't accommodate preserving them (the DOMParser API I am using for parsing XML in JavaScript does not even provide a way to access content outside the root element)

For more info see https://softwareengineering.stackexchange.com/questions/143393/xml-multiple-roots-text-content-outside-the-root-does-anyone-do-it

**Comment by chanulee1** [comment]
Looks good. Line wrapping working as expected.
