### ISSUE TITLE
`xml-editor`: Make the visual editor the most prominent by default

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3188]
<img width="438" alt="image" src="https://user-images.githubusercontent.com/37256050/225700145-6eb83263-b516-4586-8705-1920458a617e.png">

The JSON editor and XML editor should not be as large or visible as the visual editor. Ideally, nobody would ever need to use those two options.

**Comment by maxxxxxdlp** [comment]
Removed JSON editor in https://github.com/specify/specify7/commit/e057d131e0a46b3dbb9e6fc8b6aaacaca55987a8
Replaced big blue buttons with a small combo box

**Comment by chanulee1** [comment]
Looks good. Is this satisfactory?

![image](https://user-images.githubusercontent.com/103299204/232617543-233e147b-318a-41a0-8770-9de53c4b5698.png)
