### ISSUE TITLE
App resources corners are not rounded symmetrically 

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3189]
<img width="454" alt="image" src="https://user-images.githubusercontent.com/37256050/225700789-a3b1789c-fc11-4b34-af11-91d791a6ad84.png">

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/37256050/225700847-043dd0b1-dd22-424b-b8a7-594590215a80.png">

**Comment by maxxxxxdlp** [comment]
This is a firefox-specific issue.

Turns out firefox does not round the corners that have a scroll bar.

This is likely a wontfix

**Comment by grantfitzsimmons** [comment]
If you change

`.\[scrollbar-gutter\:stable\]` to `scrollbar-gutter:auto` it looks great. Are we sure that doesn't fulfill out purpose?

**Comment by maxxxxxdlp** [comment]
Ah, I didn't know about `scrollbar-gutter`

Need to research whether we can add that style globally, or it has to be added to just container

**Comment by grantfitzsimmons** [comment]
Will be solved in `v7.9.1`
