### ISSUE TITLE
`xml-editor`: When viewing the dialog alone, switching editors shows a ⚠️ in the top left

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3191]
https://user-images.githubusercontent.com/37256050/225703305-2111ae3a-e2fb-4ed8-b6fd-6eaef0f91dc4.mov

https://herbrbge31323-xml-editor.test.specifysystems.org/specify/overlay/resources/app-resource/24/formatter/

**Comment by maxxxxxdlp** [comment]
Fixed.

As part of this change, the save button will be using `Brand Color 300` rather than always be orange

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons do you see problems with using brand color 300 instead of accent color for save button?

That will allow people to fix the issue were default color is not accessible and gives them a way to customize it

**Comment by grantfitzsimmons** [comment]
No, and I like that idea. Theoretically, they could make it illegible if they wanted to, but that is the nature of allowing customization. Can we have the text be either white or black depending on the background color of the button?

**Comment by maxxxxxdlp** [comment]
There is a css feature coming soon that will make browsers automatically pick the text color that provides a sufficient contrast for any background - https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-contrast
