### ISSUE TITLE
`xml-editor`: Opening table format from the Schema Config does not operate correctly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3192]
https://user-images.githubusercontent.com/37256050/225703704-3f5e3405-90b7-452f-89a3-ec9b51be25b5.mov

https://herbrbge31323-xml-editor.test.specifysystems.org/specify/schema-config/en/Agent/

Clicking on the pencil next to the selected Table Format redirects to the following URL:
https://herbrbge31323-xml-editor.test.specifysystems.org/specify/overlay/resources/app-resource/24/formatter/Agent/4/

The **Close** button does not operate correctly. There is no save option. After clicking **Close** several times, it sends me to a 404 at the following URL:
https://herbrbge31323-xml-editor.test.specifysystems.org/specify/overlay/resources/app-resource/

**Comment by maxxxxxdlp** [comment]
See also https://github.com/specify/specify7/issues/3176#issuecomment-1500689125

**Comment by maxxxxxdlp** [comment]
From @chanulee1:

> Closing the editor does not go back to the schema config.
> 
> https://user-images.githubusercontent.com/103299204/224397598-25026a07-afa8-421b-9a6c-2f1561b6a37d.mp4

Response: https://github.com/specify/specify7/issues/3146#issuecomment-1465082652

**Comment by maxxxxxdlp** [comment]
Once agent merging gotten merged into xml editor, this bug should have gotten fixed. Needs testing

For programmers, take a look at the `FIXME` statements in the codebase to see related remaining things

**Comment by CarolineDenis** [comment]
*close button does not bring back to schema config as of today, it brings us to App Resource Dialog with list of tables that we cannot close

**Comment by CarolineDenis** [comment]
@maxxxxxdlp, How with the current code could we add the save button in the XmlEditorShell Dialog?
