### ISSUE TITLE
`xml-editor`: Using the Preview "Search" option shows entire form

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3193]
https://user-images.githubusercontent.com/37256050/225704593-3f02105e-adb2-4287-a42d-51ea57866cd8.mov

This should either show the query builder a simple search form.

https://herbrbge31323-xml-editor.test.specifysystems.org/specify/overlay/resources/app-resource/24/formatter/CollectionObject/16/

**Comment by maxxxxxdlp** [comment]
Duplicate of https://github.com/specify/specify7/issues/3171#issuecomment-1472386901
