### ISSUE TITLE
`xml-editor`: Formatters are deleted when using the visual editor

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3194]
To clarify, making **any** change and saving results in this issue.

## **Before the edit made using the visual editor:**

```xml
    <format
        name="Address"
        title="Address"
        class="edu.ku.brc.specify.datamodel.Address"
        default="true"
        >
        <switch single="true">
            <fields>
                <field>address</field>
                <field sep=" ">address2</field>
                <field sep=", ">city</field>
                <field sep=", ">state</field>
                <field sep=" ">postalCode</field>
            </fields>
        </switch>
    </format>
```

<img width="719" alt="image" src="https://user-images.githubusercontent.com/37256050/225705665-015ca6b5-af37-4ab6-9aec-2cb9810fb5d8.png">

## **After the edit made using the visual editor:**

```xml
	<format name="Address" title="Address" class="edu.ku.brc.specify.datamodel.Address" default="true"/>
```

<img width="794" alt="image" src="https://user-images.githubusercontent.com/37256050/225705420-8bde57ea-8713-492b-b024-652895a7b35a.png">

It completely deleted the fields and switch statement.

---

[BeforeAndAfter.zip](https://github.com/specify/specify7/files/10993954/BeforeAndAfter.zip)

**Comment by maxxxxxdlp** [comment]
Fixed

Can confirm that this got broken yesterday

Can also confirm that my test case caught this bug, except I didn't look at the tests as I was rushing to get this out - human error

**Comment by chanulee1** [comment]
Fixed. Making changes in visual editor does not delete formatters.
