### ISSUE TITLE
Moving a tree node results in a bogus message that the action could not be completed.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#320]
This bug was introduced by fix for #302

**Comment by garrettgirard** [comment]
I am still getting the bogus message with the new fix after attempting to move taxon tree nodes.

**Comment by benanhalt** [comment]
OK. It should be fixed now. I had the wrong branch checked out on the test server.

**Comment by garrettgirard** [comment]
I didn't get the message after moving a node in the trees in KU VP database. The move worked just fine.
