### ISSUE TITLE
`statspage` 10 - Invalid queries on stats page

### ISSUE THREAD

**Issue by realVinayak** [specify/specify7#3205]
The stats page currently runs all stats which aren't fetched. If the query has an error, it will automatically run it which could throw an exception. In that case, user won't be able to modify that stat and fix the query. Thus, I've added a system to handle backend exceptions. If backend raises any error, the stats items show 'Error' - except permission errors which are handled differently. The user can modify the stat and save it, which will cause stats page to run it again, and print 'Error' if necessary.

To test this,
1. Add an invalid query. Don't run it from query builder, instead save it to stats page. It will run automatically and catch the error. If you fix the invalid query and save it again, it will run the query in correct way. 
2. If user wants to see entire exception, they can run the query from query builder, either from within stats page (by clicking on 'query' in query builder dialog) or from the actual query builder

**Comment by carlosmbe** [comment]
Found an issue while testing this #3311

**Comment by carlosmbe** [comment]
https://github.com/specify/specify7/issues/3666
