### ISSUE TITLE
`statspage` 12 - Setting Refresh Time

### ISSUE THREAD

**Issue by realVinayak** [specify/specify7#3207]
Currently, stats page will refresh every 24 hours. The code can support arbitrary time. However, this is currently stored as a collection preference so users will need to modify collection preference JSON if they want any other time.

To test:
1. Go to CollectionPreferences in App Resources for the collection you want to set refresh rate for
2. Add `”refreshRate”:time`. Note that `time` is assumed to be in hours. So, put 0.05 if you want it to refresh every 3 minutes. Put 0 to refresh every time.
![image](https://user-images.githubusercontent.com/61122018/225738588-83b9484c-7ff6-415b-a1d4-74a4e0a503fd.png)

**Comment by realVinayak** [comment]
Need to be set to 0

**Comment by grantfitzsimmons** [comment]
Not sure this is worth doing.
