### ISSUE TITLE
Insufficient contrast for selection option in WorkBench mapper

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#3212]
1. Use Dark mode
2. Open WorkBench mapper
3. Select any required field
4. See that the contrast is insufficient (hard to read the text - need to use a different color for the text)

<img width="196" alt="Screenshot 2023-02-11 at 20 55 04" src="https://user-images.githubusercontent.com/40512816/225953028-7d81811a-b29b-4828-8497-cff15fba0e28.png">

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-9-release-announcement/1131/1
