### ISSUE TITLE
Fix automapper suggestions not working for nested -to-manys

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#3213]
1. Open WorkBench mapper in a data set that has a field whose name exactly matches the catalog number field label
1. Choose Collection Object as the base table
2. Map the field to `Accession`
3. Open the 2nd box, and see the suggested mappings.

This is how it looks with the bug:

![image](https://user-images.githubusercontent.com/40512816/226021868-d0c64db5-1288-464d-a7e0-24aa13a257d0.png)

This is how it should look:

![Screenshot 2023-03-17 at 15 07 27](https://user-images.githubusercontent.com/40512816/226022392-9c468e18-67f6-4ca1-a4ba-b92118f3a6bb.png)

**Comment by grantfitzsimmons** [comment]
Should be solved by https://github.com/specify/specify7/pull/3214

**Comment by CarolineDenis** [comment]
@maxpatiiuk, since we closed the PR related to this. Can we close the issue?

**Comment by maxpatiiuk** [comment]
good point - thanks for reminder

for future reference: closing as per https://github.com/specify/specify7/pull/3214#issuecomment-1890172207
