### ISSUE TITLE
Stop centering text when it overflows

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3227]
<img width="173" alt="image" src="https://user-images.githubusercontent.com/37256050/226612747-7fdc9de0-7bbb-46a0-9157-d1dbddecb805.png">

I am not a fan of centered text in general, but especially in menus that have a bunch of left-aligned text. This change was introduced recently (likely related to the changes for 400% zoom) and it has perturbed me every time it happens. It should remain left-aligned even on overfill.

**Comment by maxxxxxdlp** [comment]
@CarolineDenis could you confirm/disconfirm that this change was made recently, see what specific line change caused this and check if we can undo it?

**Comment by maxxxxxdlp** [comment]
Try reproducing in firefox

**Comment by CarolineDenis** [comment]
Couldn't replicate in Firefox

**Comment by grantfitzsimmons** [comment]
This happens a lot (including during demos at our meetings)

**Comment by grantfitzsimmons** [comment]
<img width="210" alt="image" src="https://user-images.githubusercontent.com/37256050/232607526-19d379d2-9d9c-4272-b105-2f6aef5d829b.png">

**Comment by grantfitzsimmons** [comment]
Not a huge deal, but not a big fan

**Comment by maxxxxxdlp** [comment]
Fixed in https://github.com/specify/specify7/commit/fc00e2b34feb46d3f5c5dcbd56a0d279c2a7d0f9 and https://github.com/specify/specify7/commit/e9d2d2ea9d2b20ba2437887bac32c2ca553b0bc9 on agent-merging branch
