### ISSUE TITLE
Auto Numbering starts at 0 instead of 1

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#324]
Set up a database to have Loan Number format yyyy-###, auto incrementing.  All of the Cornell databases will have this format.  When we create a loan that should be the first for that year, it numbers it with 2016-000 when creating it in Specify 7.  In Specify 6, it numbers it with 2016-001.

**Comment by garrettgirard** [comment]
Tested in AutoNumber test db, loan numbers with the format yyyy-### and auto-incrementing now start with 1 instead of 0.
