### ISSUE TITLE
Polygon not mapped in GEOLocate after save

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3242]
After creating a polygon in GEOLocate, I save it to the form. When I use GEOLocate again, it is not mapped.

https://user-images.githubusercontent.com/37256050/227006388-5986e02f-c1e4-4195-b2dc-5efe78b2212e.mp4

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/creating-polygons-for-regions/1105/2

**Comment by grantfitzsimmons** [comment]
Denmark has an issue on their repository about this problem. We should look into fixing this when we get some time to discuss upcoming issues!

**Comment by emenslin** [comment]
Can recreate in edge (7.9.6)

**Comment by emenslin** [comment]
Duplicate of #3957
