### ISSUE TITLE
`DataObjFormatters` should be populated with the default XML upon creation

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3244]
Because databases used exclusively in Specify 7 (more specifically, databases that never customized their formatters or aggregation in 6) do not have a `DataObjFormatters` file, they will not be able to use the `xml-editor` to customize aggregation or formatting.

We need to
1. Implement a mechanism that creates a new `DataObjFormatters` file in the database as the discipline level when the pencil is clicked next to a format/aggregation in the schema config menu
2. Use the Specify 6 default `DataObjFormatters` file as the base whenever a new `DataObjFormatters` resource is created.

Alternatively, it could be blank, but there would need to be a global `DataObjFormatters` file that can be customized and any resource created below would be used if present or cascade to the globally defined resource.

**Comment by maxxxxxdlp** [comment]
When creating the following resources, they will be automatically pre-populated with the contents of the nearest app resource by that name in the current scope:
DefaultUserPreferences
leaflet-layers
ExportFeed
ExpressSearchConfig
TypeSearches
WebLinks
UIFormatters
DataObjFormatters
DataEntryTaskInit
InteractionsTaskInit

Basically every app resource recognized by sp7 that has a hardcoded name (i.e, not a label or form definition) with exception of `UserPreferences`

**Comment by chanulee1** [comment]
If a `DataObjFormatters` file exists at the discipline level, newly created `DataObjFormatters` files at any other level are based off of that file, even at the global resource level. Same behavior for `DefaultUserPreferences`, `RSS Export Feed`, `TypeSearches`, `Weblinks`, `UIFormatters`, and `InteractionsTaskInit`. Expected?

https://user-images.githubusercontent.com/103299204/231558177-98b4327a-71a5-48e2-99a2-0b2447f35428.mp4

\
`ExpressSearchConfig` files do not seem to be pre-populated with the nearest file in scope. All files seem to be pre-populated with a set, default definition. Same for `DataEntryTaskInit`.

https://user-images.githubusercontent.com/103299204/231567632-0dea4cda-dd25-4054-81bb-ddf1d5ffbc8d.mp4

\
https://coldfish-xml-editor.test.specifysystems.org/specify/resources/app-resource/190/formatter/

**Comment by maxxxxxdlp** [comment]
> If a DataObjFormatters file exists at the discipline level, newly created DataObjFormatters files at any other level are based off of that file, even at the global resource level. Same behavior for DefaultUserPreferences, RSS Export Feed, TypeSearches, Weblinks, UIFormatters, and InteractionsTaskInit. Expected?

At the moment, instead of always using the system default file, it uses whichever file is the closest to current user

> ExpressSearchConfig files do not seem to be pre-populated with the nearest file in scope. All files seem to be pre-populated with a set, default definition. Same for DataEntryTaskInit.

In this case, the resource is based on ExpressSearchConfig that current user owns (spafishadmin), not the global ExpressSearchConfig:

![Screenshot 2023-04-14 at 11 11 24](https://user-images.githubusercontent.com/40512816/232098675-27fcf1fa-4924-4203-b91b-74871af722fe.png)

It always gets the one that is the closest in scope to current user

@grantfitzsimmons since you requested this feature, I need your feedback on the implementation:
1. Should it always base new files on system default or on what's the closest file in scope (current behavior)
2. Or should it explicitly allow user to choose which file to base it on (like with form definitions)

**Comment by maxxxxxdlp** [comment]
Closed this as completed as the initial feature is implemented.

For allowing to pick a destination, we already have a feature request: https://github.com/specify/specify7/issues/3413
