### ISSUE TITLE
Incomplete documentation make it impossible to install specify7

### ISSUE THREAD

**Issue by capsloth** [specify/specify7#325]
The first configuration option at _specify7/specifyweb/settings/specify_settings.py_ talks about a **thick client** that is never talked about anywhere else. What is this? How can I get it? What are the installation steps?

**Comment by benanhalt** [comment]
Sorry for the confusion. The *thick client* refers to a copy of a Specify 6 installation. You can either install it on the server using the [linux installer](http://specifyx.specifysoftware.org/download/) or copy an existing installation onto the server.
