### ISSUE TITLE
Width of subview determined before elements fully load

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3254]
https://user-images.githubusercontent.com/37256050/228018508-54dcb0d4-5589-483c-bba7-1dc90f3e33e3.mov

This leads to the issue where the pick lists are now too wide, adding a horizontal scrollbar.

https://specify.saiab.ac.za/specify/view/collectionobject/181134/

If you want to test, try this on a development copy of the `saiab` database in the Tissue Collection

**Comment by maxxxxxdlp** [comment]
I don't think it's related to loading.
I believe this is a consequence of the front-end changes for enforcing min-width for fields.
@CarolineDenis could you take a look at it (deploy this database on test test panel and use dev tools to see where's the width for the pick lists coming from)

**Comment by grantfitzsimmons** [comment]
Seems to be that the width is too small
