### ISSUE TITLE
Specify 7 uses the value of the pick list rather than the title in reports & labels

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3257]
<img width="540" alt="image" src="https://user-images.githubusercontent.com/37256050/228024801-9ea989ea-e4b7-4d83-9605-53c13db4ed06.png">

This should be using the title. This is on the `UWFC` label in the `uwfc` database.

```java
($F{1,9-determinations.determination.typeStatusName}==null?"":$F{1,9-determinations.determination.typeStatusName})
```

<img width="494" alt="image" src="https://user-images.githubusercontent.com/37256050/228024882-d7b03059-eea6-4225-ba01-ef2902836fd5.png">

**Comment by maxxxxxdlp** [comment]
Yet another result of #2814 

Closing this as duplicate (will add your comment there)
