### ISSUE TITLE
Query duplicating fields after each run

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3268]
<img width="1658" alt="Screenshot 2023-03-28 at 2 52 30 PM" src="https://user-images.githubusercontent.com/37256050/228535673-e3cfb473-8250-4f6a-9e75-79b623919b9d.png">
<img width="1914" alt="Screenshot 2023-03-28 at 2 53 21 PM" src="https://user-images.githubusercontent.com/37256050/228535684-535869aa-9f54-441f-9f1d-c9affe4a1204.png">
<img width="2032" alt="Screenshot 2023-03-28 at 2 54 10 PM" src="https://user-images.githubusercontent.com/37256050/228535700-9315c010-abd3-4a9d-a4d1-cac76fbd7e02.png">

This makes it impossible to modify the query

**Comment by CarolineDenis** [comment]
@grantfitzsimmons, 
Would this issue be fixed in this PR? https://github.com/specify/specify7/pull/3272
