### ISSUE TITLE
Accessing Security & Accounts as a guest throws an error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3275]
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/37256050/228700081-2fb22567-aba4-4a6f-b384-4322842477be.png">

```
Error occurred fetching from https://sp7demofish.specifycloud.org/accounts/login/?next=/permissions/library_roles/

Failed parsing JSON response:
```

[Specify 7 Crash Report - 2023-03-30T00 52 11.441Z.txt](https://github.com/specify/specify7/files/11106726/Specify.7.Crash.Report.-.2023-03-30T00.52.11.441Z.txt)

https://sp7demofish.specifycloud.org/specify/security/

**Comment by maxxxxxdlp** [comment]
It's a back-end bug. Front-end request receives a redirect to the login page:

![Screenshot 2023-03-30 at 13 14 51](https://user-images.githubusercontent.com/40512816/228927382-75e9a33f-0db7-4a26-8182-0d0a35dee76f.png)

Looking at the code, this particular endpoint is defined differently that back-end endpoints are normally defined (no `@login_maybe_required` decorator) which might be the cause

**Comment by emenslin** [comment]
Fixed
