### ISSUE TITLE
Draggable query lines are displayed behind the dialog

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#3279]
See https://github.com/specify/specify7/pull/3272#issuecomment-1491986486
See https://github.com/specify/specify7/pull/3272#issuecomment-1491994486

it is a z-index problem
and it's a bad bug
but we can't fix it in this release because we are supposed to have it released early next week, where as we haven't even merged anything yet
there is trickiness to this:
you need to use z-index higher than a dialog when inside a dialog
you need to use z-index lower than a dialog when outside a dialog, but a dialog is rendered on top (i.e, opened a notifications dialog, and have query builder in the background)
you need to have z-index in between when you have two dialogs
z-index of a dialog increases every time you click on it:

https://user-images.githubusercontent.com/40512816/229149070-c538fdc3-ecd3-4e6d-a97c-d22cad18bcb9.mov

**Comment by maxxxxxdlp** [comment]
perfect fix would be hard
might be best to read the z-index of the closes container when you start drag, and assign that z-index to the query line

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-11-release-announcement/1174/1
