### ISSUE TITLE
Form width not controlled by user preferences

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3281]
<img width="1912" alt="Screenshot 2023-03-31 at 11 32 08 AM" src="https://user-images.githubusercontent.com/37256050/229178140-5f6d265d-b930-4351-bf0a-9c0449bd1dcc.png">
<img width="1912" alt="Screenshot 2023-03-31 at 11 32 07 AM" src="https://user-images.githubusercontent.com/37256050/229178151-f454a7d3-db73-4d3d-bfce-81865fcdf218.png">

I set the form width to 1600px in user prefs, but it is not being applied. 

User `lscott`
https://herbrbge33123-edge.test.specifysystems.org/specify/

**Comment by maxxxxxdlp** [comment]
Unable to replicate:

https://user-images.githubusercontent.com/40512816/229179573-c134ec79-e267-4dab-a297-a080175d7bce.mov

Could you check in devtools like I did in the video what the form width is? (check the CSS variable)

**Comment by grantfitzsimmons** [comment]
Log in with `lscott`

**Comment by maxxxxxdlp** [comment]
Good to know a solution was found. Closing this as a non-bug
