### ISSUE TITLE
Show interactions button not working

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3291]
Clicking show interactions button leads to error message. Present on `edge`.

https://user-images.githubusercontent.com/103299204/229635876-493efa30-b652-4ec3-96da-11e4554ad06b.mp4

[Specify 7 Crash Report - 2023-04-03T21_53_16.092Z.txt](https://github.com/specify/specify7/files/11142778/Specify.7.Crash.Report.-.2023-04-03T21_53_16.092Z.txt)

https://fwri-edge.test.specifysystems.org/specify/view/collectionobject/354185/

**Comment by grantfitzsimmons** [comment]
This should be resolved before release

**Comment by grantfitzsimmons** [comment]
After further investigation, this has been a bug for some time, at least since `v7.8.7.1`, and likely even earlier.

```
ValidationError at /api/specify/loanpreparation/ ['“true” value must be either True or False.'] Request Method: GET Request URL: http://fwri-v788.test.specifysystems.org/api/specify/loanpreparation/?isresolved=true&limit=20&preparation=376264 Django Version: 3.2.15 Python Executable: /opt/specify7/ve/bin/python3.8 Python Version: 3.8.0 Python Path: ['/opt/specify7', '/opt/specify7', '/opt/specify7/ve/bin', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/opt/specify7/ve/lib/python3.8/site-packages', '/opt/specify7'] Server time: Tue, 04 Apr 2023 00:32:39 -0500 Installed Applications: 
```

**Comment by grantfitzsimmons** [comment]
To do:
- [ ] Write an automated test to make sure this works in the future
