### ISSUE TITLE
Undefined ColRelTypePlugin field perpetually displays `Loading...`

### ISSUE THREAD

**Issue by melton-jason** [specify/specify7#3294]
**Describe the bug**
If there is no data for a `ColRelTypePlugin` field, it will always display as `Loading...`. 
This is an issue because it implies that the field is in an ambiguous state and fetching data from the backend, and that the user simply has to wait for the state to be resolved. However, the state will _never_ be resolved. 

In previous versions (like `v7.8.0`, as pictured below), the ColRelTypePlugin fields that did not have any data displayed nothing. 

`v7.8.9. Prerelease`
https://willemcatno-v789-prerelease.test.specifysystems.org/specify/view/collectionobject/195670/?recordsetid=70
![col_rels_7-8-9](https://user-images.githubusercontent.com/64045831/229830878-e6fc82b1-450a-468a-a723-22683878e087.png)

`v7.8.0`
https://willemcatno-v789-prerelease.test.specifysystems.org/specify/view/collectionobject/195670/?recordsetid=70
![col_rels_7-8](https://user-images.githubusercontent.com/64045831/229830958-e10ffb82-235e-4ff3-bf70-e46a52876506.png)

This does not happen for records which are created but have not yet been saved. 

- - - 

**Notes**
At first glance, this issue seems related to the changes made in #3099. 

I have checked to make sure the issue resolved by that pull request (https://github.com/specify/specify7/pull/3099#issuecomment-1458486409) does not happen
![locality_geo_7-8-9](https://user-images.githubusercontent.com/64045831/229832467-2d986499-3ec5-41f4-9c42-b2a7b7b30691.png)

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Specify 7 Version: 7.8.9 prerelease

**Database Name:**
`willemcatno`

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-11-release-announcement/1174/1
