### ISSUE TITLE
Truncate extra precision in Float values for UI presentation.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#330]
E.g. _weight_ should appear as "24.2" in the image below.

![image](https://cloud.githubusercontent.com/assets/287254/19742056/f9724e98-9b88-11e6-8075-db4370540aec.png)

The values are stored in the database with greater precision than java.lang.Float, which representation they receive in Sp6. In Sp7 they seem to be passed through the backend as double precision values and are represented in JS as Number instances which are double precision. Thus, they are never truncated to single precision as happens in Sp6.

Something like `Number(value.toPrecision(7))` might do the trick since single precision is roughly 7 decimal digits.

**Comment by benanhalt** [comment]
`Math.fround()` might also be of use...

**Comment by maxxxxxdlp** [comment]
Fixed by adding a `step` attribute to numeric fields and latlongui plugin
Documentation: https://github.com/specify/specify7/wiki/Form-System#:~:text=be%20set%20to.-,step%20(positive%20floating%2Dpoint%20number%2C%20optional),-If%20the%20field
