### ISSUE TITLE
Properly handle business rule errors in agent merging

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#3308]
From @chanulee1:

> Able to merge agents with respective addresses without address duplication on `agent-merging`. However, I cannot merge agents with respective member records. Is this within the scope of this PR? Also, for one of the agents, the member relationship is not displayed in the merging dialog (Test1).
>
> https://user-images.githubusercontent.com/103299204/226975501-c6ea3eab-831d-47eb-859c-60cce08766b4.mp4
>
> [Specify 7 Crash Report - 2023-03-22T16_09_47.228Z.txt](https://github.com/specify/specify7/files/11042507/Specify.7.Crash.Report.-.2023-03-22T16_09_47.228Z.txt)
>
> Agent "Test1":  https://coldfish-agent-merging.test.specifysystems.org/specify/view/agent/20789/

Hoping that merging `agent-merging` with #2965 will get us close to resolving this issue

**Comment by melton-jason** [comment]
> From @chanulee1:
> 
> > Able to merge agents with respective addresses without address duplication on `agent-merging`. However, I cannot merge agents with respective member records. Is this within the scope of this PR? Also, for one of the agents, the member relationship is not displayed in the merging dialog (Test1).
> > 
> > 
> >   
> > [Specify 7 Crash Report - 2023-03-22T16_09_47.228Z.txt](https://github.com/specify/specify7/files/11042507/Specify.7.Crash.Report.-.2023-03-22T16_09_47.228Z.txt)
> > Agent "Test1":  https://coldfish-agent-merging.test.specifysystems.org/specify/view/agent/20789/
> 
> Hoping that merging `agent-merging` with #2965 will get us close to resolving this issue

For the issue in the attached video, here is some additional context. 
The OrderNumber key in the GroupPerson table ensures that for every GroupPerson: OrderNumber and GroupID are unique (see https://github.com/specify/specify7/issues/2924#issuecomment-1440638103 for a list of all unique keys)

Thus, when the merge is taking place, it must be trying to create a GroupPerson with the same OrderNumber and GroupID as the record it is trying to merge. 

(i.e., this issue occurs if the Agent Merging process creates a new GroupPerson with the same OrderNumber and GroupID before removing/modifying/etc. the previous GroupPersion which contains the information)

**Comment by melton-jason** [comment]
Also see #2713 for another Business Rule to be addressed

**Comment by emenslin** [comment]
Fixed
