### ISSUE TITLE
`issue-2860` Error upon login

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3310]
Getting this error whenever logging in or clearing the browser cache.

https://user-images.githubusercontent.com/103299204/230216411-da5d4aae-561f-45b3-aceb-e0f6e272de55.mp4

[Specify 7 Crash Report - 2023-04-05T21_30_59.417Z.txt](https://github.com/specify/specify7/files/11163289/Specify.7.Crash.Report.-.2023-04-05T21_30_59.417Z.txt)

https://coldfish-issue-2860.test.specifysystems.org/specify/

**Comment by maxxxxxdlp** [comment]
This has been since fixed. Please try again on `xml-editor` branch

**Comment by chanulee1** [comment]
Fixed on `xml-editor`.
