### ISSUE TITLE
`MultipleObjectsReturned`  when trying to base a report on a query

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3314]
https://nbm-mnb.specifycloud.org/specify/overlay/queries/

`v7.8.9`

https://user-images.githubusercontent.com/37256050/230482384-fc597918-f140-4f3e-82be-43fb961ce013.mov

[Specify 7 Crash Report - 2023-04-06T20_02_04.950Z.txt](https://github.com/specify/specify7/files/11174078/Specify.7.Crash.Report.-.2023-04-06T20_02_04.950Z.txt)

```
MultipleObjectsReturned
get() returned more than one Spappresourcedir -- it returned 2!
Content
"None"
```

**Comment by grantfitzsimmons** [comment]
[Basic Report Example.json.zip](https://github.com/specify/specify7/files/11174094/Basic.Report.Example.json.zip)

**Comment by maxxxxxdlp** [comment]
Sp7 back-end should be able to handle the assumption that there could be more than one spappresourcedir for the same level (front-end handles that)

But if you need a quick workaround, delete one of the two spappresourcedir records that don't have collection null, discipline null, specifyUser null, isPersonal false (delete the one that is not userType common) and make sure to check for usages in spappresource and spviewset tables

**Comment by melton-jason** [comment]
https://github.com/specify/specify7/blob/6afad809754b90ca6d4d48b8a7589d3018e414a2/specifyweb/report_runner/views.py#L132-L135
It looks like the backend only filters `Spappresourcedir` objects (when creating a report) on discipline id and if the collection id is null. 

The backend currently handles if there is no `Spappresourcedir` (It will create a new one), but doesn't handle if more than one `Spappresourcedir` is returned from the query (hence this issue).

**Comment by carlosmbe** [comment]
Similar issue found today on `NHMD Vascular Plants` logged in as `petrifiedroadkill` on statspage branch

Screenshots and Error Report Below
[Specify 7 Crash Report - 2023-04-07T21_15_58.007Z (1).txt](https://github.com/specify/specify7/files/11181609/Specify.7.Crash.Report.-.2023-04-07T21_15_58.007Z.1.txt)
![Screenshot 2023-04-07 at 4 16 27 PM](https://user-images.githubusercontent.com/53784701/230680034-f6cfa94b-ef90-4b6b-b2ec-a4c0e9b18b2d.png)

**Comment by melton-jason** [comment]
Can this issue be closed? 
Or does this issue have some additional context/issue that is still not resolved?
