### ISSUE TITLE
Count & results discrepency from query when field is visible or invisible

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3319]
This is one of the default statistics, "Collection Objects with attachments". 

When I make the Collection Object ID = `1148558`, I see interesting results.

This Collection Object has three attachments. Distinct is checked in the query.

## When Attachment ID is not visible:
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/37256050/230959018-0c6a5146-4dbb-4ca5-aba1-4a684f5888c0.png">
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/37256050/230959038-d4d0764f-a4d4-4e77-a437-80ae2ed26111.png">

## When Attachment ID is visible:
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/37256050/230959076-11d992e7-8a83-4cfa-ac2b-611346107ad2.png">
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/37256050/230959105-b508a005-b2d5-48c2-9b28-8327a2111ed1.png">

**User:** petrifiedroadkill
**Collection:** NHMD Vascular Plants
**URL:** https://nhmdtest030823-edge.test.specifysystems.org/specify/stats

**Comment by maxxxxxdlp** [comment]
When attachment id is not visible, it does not create 3 separate rows for the same collection object - that's the whole point of using the not visible feature

**Comment by maxxxxxdlp** [comment]
Interestingly, https://github.com/specify/specify7/issues/1450 is about the opposite problem.
@grantfitzsimmons can you take a look at the behavior in that issue?

**Comment by grantfitzsimmons** [comment]
I will make my case later

**Comment by grantfitzsimmons** [comment]
Nevermind, I fold
