### ISSUE TITLE
Using Tree search dialogue produces error

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#332]
If you search for a node within any tree using the Search Box, and you click on the name of that node you get the following error (likely a result of the fix for bug #320 ):

GET http://db2.biwebdbtest.nhm.ku.edu/api/specify_tree/geography/1121/path/ 500 (Internal Server Error)
send @ jquery.js?27d9:10243
ajax @ jquery.js?27d9:9732
jQuery.(anonymous function) @ jquery.js?27d9:9884
getJSON @ jquery.js?27d9:9865
search @ treeview.js:115
dispatch @ jquery.js?27d9:5227
elemData.handle @ jquery.js?27d9:4879
trigger @ jquery.js?27d9:5131
(anonymous) @ jquery.js?27d9:5861
each @ jquery.js?27d9:370
each @ jquery.js?27d9:137
trigger @ jquery.js?27d9:5860
_trigger @ jquery-ui.js:785
menuselect @ jquery-ui.js:6882
handlerProxy @ jquery-ui.js:704
dispatch @ jquery.js?27d9:5227
elemData.handle @ jquery.js?27d9:4879
trigger @ jquery.js?27d9:5131
(anonymous) @ jquery.js?27d9:5861
each @ jquery.js?27d9:370
each @ jquery.js?27d9:137
trigger @ jquery.js?27d9:5860
_trigger @ jquery-ui.js:785
select @ jquery-ui.js:12023
(anonymous) @ jquery-ui.js:403
click .ui-menu-item:has(a) @ jquery-ui.js:11486
handlerProxy @ jquery-ui.js:704
dispatch @ jquery.js?27d9:5227
elemData.handle @ jquery.js?27d9:4879

**Comment by benanhalt** [comment]
fixed in ca7640efba52566a0d8c4eb7eba6fcd9985f0b4b

https://github.com/specify/specify7/commit/ca7640efba52566a0d8c4eb7eba6fcd9985f0b4b#diff-d7b2e1c5dc64730e6ae6bf7a852ded49L199

**Comment by garrettgirard** [comment]
Searching for nodes in the Tree search dialogue and clicking on them no longer produces an error.
