### ISSUE TITLE
Make relative date switch icon "time machine"

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3324]
<img width="291" alt="image" src="https://user-images.githubusercontent.com/37256050/231035526-8e48feb7-0a7c-469f-a81d-941e65b8bfab.png">

Something like the Apple Time Machine logo would be perfect.

<img width="449" alt="Screenshot 2023-04-10 at 1 18 56 PM" src="https://user-images.githubusercontent.com/37256050/231035570-eac8b816-8835-4ee2-8e07-5eb20d60f703.png">

Also the "switch" tooltip needs to be changed to "Switch to Relative Date" or "Switch to Static Date"

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/231035705-de27adcf-7c0c-4aa3-9146-065a133b6fdf.png)

Also make it more prominent by making it a button next to the date format.

**Comment by realVinayak** [comment]
This was fixed in use-dynamic-stats branch. 
![Screenshot (130)](https://user-images.githubusercontent.com/61122018/234109266-04632bf8-2daf-4d6e-9e47-4a1812ce68cc.png)
![Screenshot (131)](https://user-images.githubusercontent.com/61122018/234109477-46a5d9bc-266d-4088-8cf9-3dea60d52424.png)
