### ISSUE TITLE
Remove "Future" option in relative dates

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3325]
**Requested By:** @beach53 

<img width="730" alt="Screenshot 2023-04-10 at 1 21 52 PM" src="https://user-images.githubusercontent.com/37256050/231035881-30719599-b143-436a-829b-209bebac4619.png">

**Comment by maxxxxxdlp** [comment]
After further discussion we decided not to remove it as it is useful for querying on due dates of loans
