### ISSUE TITLE
`ValidationError` when modifying loan record

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3331]
**Context:**
> We went in to create a loan and had several issues. My assistant was unable to edit or add information to the loan and was given the attached message. I was able to edit and add information, but when I went to save (and generate an invoice) I received the following error. This is for loan # 647. Sometimes it saved the info, and sometimes it didn’t. 
>
> I just tried it with a different browser, it didn't help. Can you just add the specimens 57177 and 57178 (it didn't like that I wanted to add them to the record set and make that a loan) to the loan and send me the paperwork and labels to print out? I have no idea why this is happening. 
>
> I made the 647 loan for Meachen, but Specify is buggy and wont let me edit, view, or finish it. I am going to read the forum and see if this is a common issue. I will try to have it resolved by Thursday when I pack the loan. Here is the error, have you seen this before?

I cannot recreate. Here's my message to them:

> I can view and generate labels and reports for both of the following URLs using Google Chrome 112:
> 
> Loan 647:
> https://uw-geo-collections.specifycloud.org/specify/view/loan/383/
> 
> Record Set with items for Loan 647:
> https://uw-geo-collections.specifycloud.org/specify/view/collectionobject/50668/?recordsetid=251
> This is the URL that the crash report says the issue occurred at.
> 
> I logged in as `wworrell` in a temporary copy of the database, navigated to both records, and I could not create an issue from general testing.
> 
> Can you what specifically was being edited at the time of the crash? Could you describe what actions to take so I can recreate?

I will close this issue if we can rule out the cause.

```
  "responseText": "{\"exception\": \"ValidationError\", \"message\": \"\\u201c%(value)s\\u201d value must be either True or False.\", \"data\": \"invalid\", \"traceback\": \"Traceback (most recent call last):\\n  File \\\"/opt/specify7/ve/lib/python3.8/site-packages/django/core/handlers/base.py\\\", line 181, in _get_response\\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\\n  File \\\"/opt/specify7/specifyweb/specify/views.py\\\", line 29, in wrapped\\n    return view(request, *args, **kwargs)\\n  File \\\"/opt/specify7/ve/lib/python3.8/site-packages/django/views/decorators/cache.py\\\", line 31, in _cache_controlled\\n    response = viewfunc(request, *args, **kw)\\n  File \\\"/opt/specify7/specifyweb/specify/views.py\\\", line 62, in view\\n    return dispatch_func(request, *args, **kwargs)\\n  File \\\"/opt/specify7/specifyweb/specify/api.py\\\", line 198, in collection_dispatch\\n    data = get_collection(request.specify_collection, model, checker,\\n  File \\\"/opt/specify7/specifyweb/specify/api.py\\\", line 758, in get_collection\\n    objs = apply_filters(logged_in_collection, params, model, control_params)\\n  File \\\"/opt/specify7/specifyweb/specify/api.py\\\", line 782, in apply_filters\\n    objs = model.objects.filter(**filters)\\n  File \\\"/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/manager.py\\\", line 85, in manager_method\\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\\n  File \\\"/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/query.py\\\", line 941, in filter\\n    return self._filter_or_exclude(False, args, kwargs)\\n  File \\\"/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/query.py\\\", line 961, in _filter_or_exclude\\n    clone._filter_or_exclude_inplace(negate, args, kwargs)\\n  File \\\"/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/query.py\\\", line 968, in _filter_or_exclude_inplace\\n    self._query.add_q(Q(*args, **kwargs))\\n  File \\\"/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/sql/query.py\\\", line 1416, in add_q\\n    clause, _ = self._add_q(q_object, self.used_aliases)\\n  File \\\"/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/sql/query.py\\\", line 1435, in _add_q\\n    child_clause, needed_inner = self.build_filter(\\n  File \\\"/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/sql/query.py\\\", line 1370, in build_filter\\n    condition = self.build_lookup(lookups, col, value)\\n  File \\\"/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/sql/query.py\\\", line 1216, in build_lookup\\n    lookup = lookup_class(lhs, rhs)\\n  File \\\"/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/lookups.py\\\", line 25, in __init__\\n    self.rhs = self.get_prep_lookup()\\n  File \\\"/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/lookups.py\\\", line 77, in get_prep_lookup\\n    return self.lhs.output_field.get_prep_value(self.rhs)\\n  File \\\"/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/fields/__init__.py\\\", line 986, in get_prep_value\\n    return self.to_python(value)\\n  File \\\"/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/fields/__init__.py\\\", line 976, in to_python\\n    raise exceptions.ValidationError(\\ndjango.core.exceptions.ValidationError: ['\\u201cfalse\\u201d value must be either True or False.']\\n\"}"

```

[Specify 7 Crash Report - 2023-04-05T16_25_24.987Z.txt](https://github.com/specify/specify7/files/11202606/Specify.7.Crash.Report.-.2023-04-05T16_25_24.987Z.txt)

https://uwgeocollections41123-edge.test.specifysystems.org/specify/view/collectionobject/50668/?recordsetid=251

**🤖 ChatGPT answer:**
> This error appears to be a server-side error generated by a Django web application. The error message indicates that there was a validation error related to a field with a value of "false" that must be either "True" or "False". The error occurred during the processing of a request, and the traceback shows the sequence of function calls that led to the error.
> 
> The error likely occurred in the specify/views.py file, specifically in the view function, which was decorated with cache_controlled from django/views/decorators/cache.py. The error was triggered while processing a get_collection function call with a model parameter, which resulted in a filter call on a queryset (model.objects.filter(**filters)), and the filters dictionary likely contained a key-value pair with the key "false" and an invalid value.
> 
> To resolve this error, you may need to review the code in the specify/views.py file and check the validation logic for the field with the "false" value. Make sure that the validation allows only "True" or "False" values for that field. Additionally, you may need to review the get_collection function in the specify/api.py file to ensure that the filters being applied are valid and do not contain any invalid values.

**Comment by maxxxxxdlp** [comment]
The issue is that front-end made a request like:
`https://uw-geo-collections.specifycloud.org/api/specify/loanpreparation/?isresolved=false&limit=20&preparation=101711`

but should have made:
`https://uw-geo-collections.specifycloud.org/api/specify/loanpreparation/?isresolved=False&limit=20&preparation=101711`

This is same issue as https://github.com/specify/specify7/issues/3291, and since that one was fixed, this is too.

@grantfitzsimmons can you notify them that the issue is resolved?
