### ISSUE TITLE
Cannot save changes to user pref app resources

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3338]
https://user-images.githubusercontent.com/103299204/231547303-9bc2a56c-888a-4154-b568-a9132c7c7456.mp4

branch: `edge`
https://coldfish-edge.test.specifysystems.org/specify/resources/app-resource/194/

**Comment by realVinayak** [comment]
A bug which got introduced in refactoring preferences. Should be fixed on `use-dynamic-ranks` branch.

**Comment by melton-jason** [comment]
Duplicate of #3411
