### ISSUE TITLE
Formatters containing aggregators split into different results in querybuilder

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3341]
`Discipline` formatter containing `Collection` aggregator is split into different results in the querybuilder, one for each collection. Queried  for formatted discipline records.

https://user-images.githubusercontent.com/103299204/231821923-f2bba9c2-b2ce-42c3-a429-9d8f76b2fae9.mp4

https://coldfish-xml-editor.test.specifysystems.org/specify/query/209/

**Comment by maxxxxxdlp** [comment]
Looks like aggregator does not get called when it should
Not sure if this was intentional or not.
@chanulee1 can this be replicated on production?
@realVinayak could you please take a look at this (since it's about query results, it's related to back-end)

**Comment by chanulee1** [comment]
Yes, I was able to replicate this on production.

https://coldfish-edge.test.specifysystems.org/specify/query/209/

**Comment by maxxxxxdlp** [comment]
It's very important to fix this issue before stats page release.
This bug resulted in query on collection object returning 3 billion records!

**Comment by realVinayak** [comment]
Fixed on use-dynamic-ranks
