### ISSUE TITLE
Space characters cannot be typed in LatLonUI at the end

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3354]
Our official documentation claims the following:

> The only characters that are allowed in the input field for coordinate fields are:
> 
> - A whitespace character (tab, space)
> - A digit
> - Any of the following: "'-.:ensw° (case-insensitive)

This was demonstrably true some time ago (and @maxxxxxdlp made changes to what was accepted the last time I tested it), but now spaces are not enterable at the end of the line.

https://user-images.githubusercontent.com/37256050/232167722-1323a8a2-8967-46c4-9c0d-5b1ebdb8e958.mov

In this video, I tried typing `30 30 30 N`, but I could only go back to add space characters.

https://sp7demofish.specifycloud.org/specify/view/locality/new/

**Comment by grantfitzsimmons** [comment]
>Finally, on the Locality form when entering in coordinates as DMS (Degree Minute Second), the field does not allow the entering of spaces! So for example, if I wish to enter 30 30 30 N as a latitude, I can only enter 303030N and then once that has been completed, I can use the mouse or the arrows to work my way back and add the spaces in (e.g. 303030 N è 3030 30 N è 30 30 30 N) at which point the form will recognize the value. There is simply no way to type a space at the end of the string.

**Reported By:** Tomislav at The University of Texas at Austin

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-11-release-announcement/1174/1
