### ISSUE TITLE
Editing weblinks through Visual Editor results in error

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3356]
https://user-images.githubusercontent.com/103299204/232570546-b7963293-c2a8-4076-b575-5f4f547e2f5b.mp4

[Specify 7 Crash Report - 2023-04-17T17_56_53.319Z.txt](https://github.com/specify/specify7/files/11253983/Specify.7.Crash.Report.-.2023-04-17T17_56_53.319Z.txt)

https://coldfish-xml-editor.test.specifysystems.org/specify/resources/app-resource/210/web-link/

**Comment by CarolineDenis** [comment]
I cannot reproduce. @carlosmbe  @bronwyncombs can you confirm?

**Comment by pashiav** [comment]
Tested on `nbm_mnb_5_5_23` and could not reproduce error. Web Links can be added and edited as expected.

Tried to test this on `coldfish` but errors occur when I try to just open App Resources.

https://github.com/specify/specify7/assets/118556884/bcb59cdc-e901-4c31-b58e-10a7da6d8372

**Comment by carlosmbe** [comment]
Can not reproduce error on `xml-editor` and `xml-editor-backend-fixes` with Cold Fish and the same field that Chanu is using in the video.
