### ISSUE TITLE
"Clone" for app resources with Visual Editors not working correctly

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3358]
Cloning an app resource with a Visual Editor such as `DataObjFormatters` or `Weblinks` creates an app resource without Visual Editor capabilities.

https://user-images.githubusercontent.com/103299204/232573989-044fe0b4-3688-458d-a863-a45c72d4eb7a.mp4

https://coldfish-xml-editor.test.specifysystems.org/specify/resources/app-resource/219/

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons I need your feedback on this

A resource is considered a web link definitions file only if its name is "WebLinks"
If the user decides to clone a resource, if we rename the resource to "WebLinks 2" or anything like that then the visual editor won't be available anymore. If we don't rename the resource, then there is a duplicate resource name on the same level - undefined behavior

One simple solution: for resources whose name can be arbitrary (view sets, reports, labels), the name will be made unique, but for things like `DataObjFormatters`, name won't be changed, unless the user changed it.

But probably the best solution would be to implement https://github.com/specify/specify7/issues/3413 to explicitly ask user for destination and don't allow cloning unique resources (i.e, `WebLinks`) to the same directory (or force the user to rename them in that case)

**Comment by maxxxxxdlp** [comment]
In that case I will close this in favor of #3413
