### ISSUE TITLE
Aggregator preview showing multiple rows, displaying "Loading..."

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3360]
Before this, the preview showed a single row of aggregated records.

https://user-images.githubusercontent.com/103299204/232579146-2d08d6c0-471a-4403-82cf-96dc5b0531d1.mp4

https://coldfish-xml-editor.test.specifysystems.org/specify/resources/app-resource/190/aggregator/Agent/4

**Comment by maxxxxxdlp** [comment]
Fixed. It should only display one preview, not 4 (as 4 records are aggregated together into one line)

**Comment by CarolineDenis** [comment]
Fixed in xml-editor branch
