### ISSUE TITLE
Add column for contents of condition field for record previews

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3361]
It would be nice if the previews section in the Visual Editor for record formatters included a column that displayed the contents of the condition field for the record preview. It would make it faster to confirm that the correct formatter is being used for each record, especially for condition fields on distantly related tables.

**Comment by maxxxxxdlp** [comment]
Fixed. Also, if formatter includes tabs or new lines or multiple spaces, those are now correctly displayed in the formatter preview
