### ISSUE TITLE
Cannot run a query as "distinct" with only an aggregated field

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3362]
```
(MySQLdb.OperationalError) (3065, "Expression #1 of ORDER BY clause is not in SELECT list, references column 'nbm_mnb.collectionobject.CollectionObjectID' which is not in SELECT list; this is incompatible with DISTINCT")
```

[Specify 7 Crash Report - 2023-04-17T20_41_40.088Z.txt](https://github.com/specify/specify7/files/11255589/Specify.7.Crash.Report.-.2023-04-17T20_41_40.088Z.txt)

[Aggregated.json.zip](https://github.com/specify/specify7/files/11255625/Aggregated.json.zip)

**Comment by maxxxxxdlp** [comment]
Potentially same issue as #3341

**Comment by realVinayak** [comment]
hard to solve.

**Comment by maxxxxxdlp** [comment]
You mean you can't replicate this with any formatter and need a specific formatter to replicate the bug?
Also, for the bug itself, there must be clean solutions, but even if there aren't creating a super-query on top of the current sub-query that just adds `DISTINCT` should do the job

**Comment by emenslin** [comment]
Fixed
