### ISSUE TITLE
Formatter record previews using wrong formatter

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3366]
Agent `T, Martin` has agent type `1` but is using formatter for agent type `0` in the preview. The correct formatter is used when displayed in query builder results and qcbx in forms.

https://user-images.githubusercontent.com/103299204/232857922-9c7f2df9-98db-4865-a605-aecdfaed44a0.mp4

https://coldfish-xml-editor.test.specifysystems.org/specify/resources/app-resource/190/formatter/Agent/4

**Comment by maxxxxxdlp** [comment]
It's a bug. The condition field didn't work for numeric fields. Fixed
Please also test with boolean fields

**Comment by CarolineDenis** [comment]
Fixed in xml-editor
