### ISSUE TITLE
Forbidden (403) CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by jobdiogenes** [specify/specify7#337]
After trying to run a Report I receive the following message:

PS: using developing trunk. 

Help
Reason given for failure:
    CSRF token missing or incorrect.
    
In general, this can occur when there is a genuine Cross Site Request Forgery, or when Django's CSRF mechanism has not been used correctly. For POST forms, you need to ensure:
Your browser is accepting cookies.
The view function passes a request to the template's render method.
In the template, there is a {% csrf_token %} template tag inside each POST form that targets an internal URL.
If you are not using CsrfViewMiddleware, then you must use csrf_protect on any views that use the csrf_token template tag, as well as those that accept the POST data.
The form has a valid CSRF token. After logging in in another browser tab or hitting the back button after a login, you may need to reload the page with the form, because the token is rotated after a login.
You're seeing the help section of this page because you have DEBUG = True in your Django settings file. Change that to False, and only the initial error message will be displayed.
You can customize this page using the CSRF_FAILURE_VIEW setting.

**Comment by garrettgirard** [comment]
Haven't gotten this error on any reports I've generated. Seems to be resolved.

**Comment by garrettgirard** [comment]
VIMS Fish (we're hosting) is still having this issue.

**Comment by benanhalt** [comment]
Has this happened at all in the past year to anyone's knowledge?

**Comment by yvonneekanim** [comment]
I'm not getting the exact error but I haven't been able to run any invoices (loan,gift,borrow). Labels run just fine

**Comment by benanhalt** [comment]
This is also being caused by #482. I think the fact that is working for labels indicates the original issues has not reemerged.
