### ISSUE TITLE
* Wildcard Support in Specify 7 Query

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3372]
**Describe the bug**
Some queries from Specify 6 contain a * which represents wildcard and returns all matches. However, in Specify 7 this isn't the same. I would assume that 7 treats * as its own unique character.

https://pripaleo-v7810-prerelease.test.specifysystems.org/specify/query/7/  

**To Reproduce**
1. Go to Pripaloe's Saved Queries 
2. Click on All Loans
3. Run Query 
4. See nothing returned 

**Expected behavior**
All items returned. Which is the behavior found in specify 6.
![Screenshot 2023-04-19 at 11 07 56 AM](https://user-images.githubusercontent.com/53784701/233135943-c4e588e5-5153-4140-8974-f02c6819a3ae.png)
![Screenshot 2023-04-19 at 11 08 01 AM](https://user-images.githubusercontent.com/53784701/233135948-fcd4fc7e-396c-40b5-9154-1fe95d3307b3.png)

**Screenshots**
![Screen Shot 2023-04-19 at 11 11 20 AM](https://user-images.githubusercontent.com/53784701/233136094-21777018-9a0a-4486-a257-f0f0c807f0e5.png)

**Desktop:**
OS: Mac OSx Monterey
Browser: Chrome
Specify 7 Version: 7.8.10-prerelease

**Database Name:** pripaleo

**Reported By**
Carlos @carlosmbe

**Comment by melton-jason** [comment]
We'll need to look into what wildcards are supported by what operators in Specify 7, as it seems inconsistent at the moment. 
I know that the LIKE operator supports `%` as a wildcard.

**Comment by maxxxxxdlp** [comment]
Looks like it's calling django ORM's contains, where as sp6 is using LIKE, but auto adding `*` to make it behave like CONTAINS (at least that's what I think is happening without looking at sp6 code)

 https://github.com/specify/specify7/blob/9d5cbf70e1f3873c1e8743d5eda8f738ea19012d/specifyweb/stored_queries/query_ops.py#L87

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp @melton-jason Should this stay open?

**Comment by melton-jason** [comment]
We support the two SQL WildCards when using the `LIKE` operator: 
- `%`: which matches zero or more characters 
- `_` which matches a single character

A tooltip displays this information when LIKE is hovered, and we have more extensive documentaiton [on the Speciforum](https://discourse.specifysoftware.org/t/specify-7-query-builder/289)

> You can insert one of two wildcard characters (% or _) anywhere in a field to narrow a search using character substitution.
> 
> % represents zero or more characters. For example, d%t will find any word that begins with d and ends with t (dot, dust, dealt, etc.). Tes% will find any word that starts with Tes.
> _ represents a single character. It differs from ‘%’ in that is only ever a single character. c_t will only find words that start with c, contain one of any other character, and end in t (cat, cot). sp____y will find any word that starts with sp, has 4 of any other character, and end in y (specify).
> 
> The wildcards can be used in conjunction. For example, to find all words that must be at least 3 characters in length: ___%
> To find all words that start with C and must have at least two following characters, and end with any single character followed by el (such as Caramel): C__%_el

**Comment by grantfitzsimmons** [comment]
You are a real one for updating that doc. Closing the issue since we understand and have documented the behavior

**Comment by maxxxxxdlp** [comment]
Too late, but there is also a somewhat related issue: https://github.com/specify/specify7/issues/1209

**Comment by melton-jason** [comment]
If we need to cover support for custom wildcards (i..e, our own query operators) Django supports implementing 'custom lookups'. 
https://docs.djangoproject.com/en/3.2/howto/custom-lookups/

A similar functionality exists in sqlalchemy. 
See the documentation:
https://docs.sqlalchemy.org/en/20/core/compiler.html
https://docs.sqlalchemy.org/en/20/core/sqlelement.html
