### ISSUE TITLE
TreatmentEvent queries return no results.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#338]
![image](https://cloud.githubusercontent.com/assets/287254/22159690/bb4ee1b8-df07-11e6-99c5-d8bd9b134247.png)
![image](https://cloud.githubusercontent.com/assets/287254/22159707/d2ca9166-df07-11e6-8dcd-28b176a90bf8.png)

**Comment by benanhalt** [comment]
The problem is because TreatmentEvent has a relationship to division which causes Specify 7 to assume it is scoped to that level. Specify 6 only filters queries at the division level for particular tables even if they have a division relationship. TreatmentEvent is not one of those tables. I'm changing Specify 7 to do the same.

**Comment by garrettgirard** [comment]
Results now pop up in Treatment event queries when there data exists for the fields searched.
