### ISSUE TITLE
Record set causing a flurry of crashes and slowdown

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3394]
**Steps to Recreate:**
1. Log into `herb_rbge_3_31_23` as `hplaisier`
2. Navigate to the following record set: https://herbrbge33123-edge.test.specifysystems.org/specify/record-set/463/
3. Go back and forth between items in the record set until you see a crash. This can take several tries.

Using Chrome, macOS – reported by user on Chrome on Windows

https://user-images.githubusercontent.com/37256050/233665303-70d6c751-5756-46c1-8dde-2ca478e6fe15.mp4

On https://herbrbge33123-edge.test.specifysystems.org/specify/view/gift/2844/?recordsetid=463:

><img width="894" alt="image" src="https://user-images.githubusercontent.com/37256050/233664344-cc581017-38fa-413e-92f4-b7a9149a5d1e.png">
> `Error occurred fetching from /api/specify/agent/205/`
> [Specify 7 Crash Report - 2023-04-21T14_38_56.164Z.txt](https://github.com/specify/specify7/files/11296727/Specify.7.Crash.Report.-.2023-04-21T14_38_56.164Z.txt)

**Reported By:**
RBGE– this is accompanied by 502 Bad Gateway errors often as well

**Comment by grantfitzsimmons** [comment]
> Following yesterday's discussion about multiple crashes when using record sets, I’ve attached the reports I was sent. These were all from one user, over the course of one day.
> 
> The files ending 351Z and 471Z were when clicking through pages of a record set. The file ending 802Z was after the user had reopened a recordset and moved to the third record following the crash below.
> 
> Looking back through the emails the file ending 944Z was when the user was trying to upload an attachment to a gift record.
> 
> The user has experienced crashes when working with record sets previously, but hadn’t saved the crash reports from these. The record sets were working ok between the crash reports.
> 
> The user was using Chrome.

[Specify 7 Crash Report - 2023-04-19T11_33_42.944Z.txt](https://github.com/specify/specify7/files/11296872/Specify.7.Crash.Report.-.2023-04-19T11_33_42.944Z.txt)
[Specify 7 Crash Report - 2023-04-19T11_38_18.802Z.txt](https://github.com/specify/specify7/files/11296873/Specify.7.Crash.Report.-.2023-04-19T11_38_18.802Z.txt)
[Specify 7 Crash Report - 2023-04-19T16_00_50.471Z.txt](https://github.com/specify/specify7/files/11296874/Specify.7.Crash.Report.-.2023-04-19T16_00_50.471Z.txt)
[Specify 7 Crash Report - 2023-04-19T16_01_53.351Z.txt](https://github.com/specify/specify7/files/11296875/Specify.7.Crash.Report.-.2023-04-19T16_01_53.351Z.txt)
[Specify 7 Crash Report - 2023-04-19T16_06_39.485Z.txt](https://github.com/specify/specify7/files/11296876/Specify.7.Crash.Report.-.2023-04-19T16_06_39.485Z.txt)

**Comment by melton-jason** [comment]
@grantfitzsimmons 
As far as you know is this issue still reproducible? There have most likely been a plethora of changes to Record Sets since this issue was opened. 

This may be difficult to reproduce consistently on the test panel because of a known bug when it is rebuilding its containers. 
Preferably, those that have a local copy of Specify 7 test this issue.

**Comment by CarolineDenis** [comment]
@specify/ux-testing , could you test this with latest versions?

**Comment by grantfitzsimmons** [comment]
Let's verify this one. I imagine this will still be a problem...

**Comment by pashiav** [comment]
Could not reproduce on `edge`. Tested for about 2 minutes and it just seemed to load quicker the more that I went back and forth between items.


https://github.com/specify/specify7/assets/118556884/80bd24dc-7ce4-4c4c-a2da-5ade55c42ddd

**Comment by CarolineDenis** [comment]
@bronwyncombs @grantfitzsimmons, same couldn't reproduce. 

Can we close?
