### ISSUE TITLE
Crash when creating new collection object and setting determination taxon

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3396]
**Describe the bug**
Title

**To Reproduce**
1. Go to `Data Entry`
2. Click on `Collection Object`
3. Scroll down to Determinations
4. Add a taxon
5. See error

**Expected behavior**
Not a crash

**Screen Recording, Links to objects and error reports**

https://pripaleo-v7810-prerelease.test.specifysystems.org/specify/view/collectionobject/new/

[Specify 7 Crash Report - 2023-04-21T16_16_52.164Z (1).txt](https://github.com/specify/specify7/files/11297553/Specify.7.Crash.Report.-.2023-04-21T16_16_52.164Z.1.txt)
[Specify 7 Crash Report - 2023-04-21T16_16_52.164Z.txt](https://github.com/specify/specify7/files/11297554/Specify.7.Crash.Report.-.2023-04-21T16_16_52.164Z.txt)
[Specify 7 Crash Report - 2023-04-21T16_16_46.603Z (1).txt](https://github.com/specify/specify7/files/11297555/Specify.7.Crash.Report.-.2023-04-21T16_16_46.603Z.1.txt)
[Specify 7 Crash Report - 2023-04-21T16_16_46.603Z.txt](https://github.com/specify/specify7/files/11297556/Specify.7.Crash.Report.-.2023-04-21T16_16_46.603Z.txt)

https://user-images.githubusercontent.com/53784701/233686517-465f48a6-0dae-4661-a114-ea943502062d.mov

Desktop:
OS: Mac OSx Monterey
Browser: Chrome
Specify 7 Version: 7.8.10-prerelease

Database Name: `pripaleo`

Reported By
Carlos @carlosmbe

**Comment by melton-jason** [comment]
This issue is most likely caused by whatever is causing #3395. 

This issue's error: 
`"OperationalError at /api/specify/taxon/48331/\n(1054, \"Unknown column 'taxoncitation.figurenumber' in 'field list'\")`

The error in #3395:
`"OperationalError at /api/specify/collectionobject/112/\n(1054, \"Unknown column 'determinationcitation.figurenumber' in 'field list'\")`

However, for now we can tentatively keep both issues open until we know for certain what is causing both.

**Comment by carlosmbe** [comment]
@melton-jason 
Your assumption was correct.
I made a copy of the database(orginally 6.8.01) and updated it's schema via the latest version of specify 6 (6.8.03)
Afterwards, both the crashes 3395 and this one stopped occurring.

**Comment by melton-jason** [comment]
Specify 6.8.01 should be on schema version 2.9. 
In the 2.9 schema ([schema 2.9 changelog](https://www.specifysoftware.org/wp-content/uploads/2021/09/Specify-Schema-Update-v2.9-15-Sep-2021.pdf)), we added `determinationcitation.figurenumber` and `taxoncitation.figurenumber`, so they _should_ be supported in Specify 6.8.01. 
I wonder if the original update to Specify 6.8.01 for this database encountered some issues and could not update the database completely. 

Regardless, feel free to close either this issue or #3395 as a duplicate.
