### ISSUE TITLE
Add the ability to import/export pick lists

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3403]
![image](https://user-images.githubusercontent.com/37256050/234077720-61a48226-d4d3-431b-825d-e0d4239baace.png)

https://discourse.specifysoftware.org/t/importing-and-exporting-a-pick-list/285

**Comment by maxxxxxdlp** [comment]
Even though this was a separate feature from https://github.com/specify/specify7/issues/3404 in sp6, there is no reason why it has to be implemented twice in the code. I would suggest sp7 adds import/export tool, that supports several tables at once.
