### ISSUE TITLE
Statistics page button still in the defaults for the navigation menu

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3405]
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/37256050/234083815-15663616-e121-439a-a283-965ba19ceef3.png">

It is throws a 404 message whenever you click on it, as expected.

**Comment by maxxxxxdlp** [comment]
This was caused by an incomplete fix in 41aaef8ff
Properly fixed in 5e786a9ad

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons if you have a chance, please try out the fix on `v7.8.10-prerelease` branch

**Comment by grantfitzsimmons** [comment]
Working correctly! Thank you!
