### ISSUE TITLE
Visual Editor Can Not Save 

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3411]
**Describe the bug**
Save Button in visual editor is not allowing me to save. Works fine in text editor though.

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in as `testuser`
2. Go to the Visual Editor in any App Resource. In this case, I was in PriPaleo-Schema Updated.
3. Make some changes 

**Expected behaviour**
I should be able to save

**Screenshots**
Save button the same both before and after

**Before**
<img width="1167" alt="Screenshot 2023-04-25 at 3 04 27 PM" src="https://user-images.githubusercontent.com/53784701/234390771-c4981fbf-b4d3-485a-8a4e-22e38e8596ef.png">

**After**
<img width="1166" alt="Screenshot 2023-04-25 at 3 05 04 PM" src="https://user-images.githubusercontent.com/53784701/234390824-279a772d-687a-4dbb-b422-e9e2e6c04c65.png">

**Desktop:**
OS: Mac OSx Ventura
Browser: Chrome
Specify 7 Version: 7.8.10-prerelease

**Database Name**: Updated pripaleo

**Reported By**
Carlos @carlosmbe

**Comment by realVinayak** [comment]
Present till stats release

**Comment by realVinayak** [comment]
Also this is an isolated problem to visual user preferences editor and not app resources in general

**Comment by grantfitzsimmons** [comment]
Should be fixed in #2796
