### ISSUE TITLE
Not Saving When Creating New App Resource: DefaultUserPreferences

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3412]
**Describe the bug**
Related to #3411, as using text editor in creation process leads to it working properly.

Despite the save button being visible in the visual editor. It does not save the changes. Rather the App Resource is created but none of the preferences are stored.

Moreover, it briefly flashes a 404 Error during after pressing save 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to App Resources -> Global Resources -> Add Resource -> App Resource -> DefaultUserPreferences
2. Make some changes in the **Visual Editor**
3. Click Save

**Expected behaviour**
New DefaultUserPreferences with the our preferences saved

**SCREEN RECORDING**

https://user-images.githubusercontent.com/53784701/234396787-20521868-5f89-40d1-9842-99fa71d45769.mp4

Desktop:
OS: Mac OSx Ventura
Browser: Chrome
Specify 7 Version: 7.8.10-prerelease

Database Name: ANY - Recreated behaviour in both Updated Paleo and NHMD Test

Reported By
Carlos @carlosmbe

**Comment by maxxxxxdlp** [comment]
Yes, this is same issue as #3411. I will merge them
