### ISSUE TITLE
Allow choosing destination for app resource clone/add

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3413]
### Updated

Clone and add button in app resources clone to current app resource directory - thus they are of limited use. Instead need to prompt the user for destination directory for cloned app resource

### Original (outdated)

**Describe the bug**
According to fellow team member these buttons are not supposed to be here.

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in as `testuser`
2. Go to https://carlospripaleoschemaupdatedcm202304211540-v7810-prerelease.test.specifysystems.org/specify/resources/app-resource/134/
3. See error

**Screenshots**
<img width="1791" alt="Screenshot 2023-04-25 at 3 50 33 PM" src="https://user-images.githubusercontent.com/53784701/234400554-a647a96f-a7fa-458e-8fc5-c3adec318445.png">

Desktop:
OS: Mac OSx Ventura
Browser: Chrome
Specify 7 Version: 7.8.10-prerelease

Database Name: ANY

Reported By
Carlos @carlosmbe

**Comment by maxxxxxdlp** [comment]
so we have to add exceptions in the code for some app resource names just because we can't come up with use cases for a feature that is already there? the mistake sp6 did many times

**Comment by maxxxxxdlp** [comment]
we could theoretically remove those buttons for all app resources because it's unlikely you want to create two app resources of the same type with similar contents at the same level (i.e, remoteprefs, typesearches, etc) - but I'm sure someone somewhere would find that useful so I don't know why would we go out of our way to remove a working feature
@grantfitzsimmons what do you think?

**Comment by grantfitzsimmons** [comment]
Not necessary to resolve in my opinion. Yes, we could, but I don't think people would try to clone or add these at this point anyway. Maybe if the clone option allowed copying into another directory, but until then, let's leave this alone.

**Comment by maxxxxxdlp** [comment]
> Maybe if the clone option allowed copying into another directory, but until then, let's leave this alone.

While that seems useful, that feature is less useful as you can just download an app resource and import it at a different place

**Comment by grantfitzsimmons** [comment]
> While that seems useful, that feature is less useful as you can just download an app resource and import it at a different place

This does the job fine, and people don't really clone resources often anyway. This is a completely manageable solution, and we've got much bigger fish to fry!

**Comment by maxxxxxdlp** [comment]
See https://github.com/specify/specify7/issues/3358#issuecomment-1531686847 for more relevant information

**Comment by grantfitzsimmons** [comment]
Closing as this feature is unnecessary. Please reopen if a user requests this ability.
