### ISSUE TITLE
Add Button Does Not Work in App Resources 

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3414]
**Describe the bug**
404 Error whenever Add Button is clicked in App Resources.

**To Reproduce**
1. Log in as `testuser`
2. Click on https://carlospripaleoschemaupdatedcm202304211540-v7810-prerelease.test.specifysystems.org/specify/resources/app-resource/134/
3. Click `Add`

**Expected behavior**
Not a 404

**Screenshots**
<img width="1778" alt="Screenshot 2023-04-25 at 3 53 34 PM" src="https://user-images.githubusercontent.com/53784701/234401147-10531ef5-7ebd-4e5d-9264-9563f29254e9.png">

Desktop:
OS: Mac OSx Ventura
Browser: Chrome
Specify 7 Version: 7.8.10-prerelease

Database Name: Any

Reported By
Carlos @carlosmbe

**Comment by grantfitzsimmons** [comment]
Cannot recreate this error on Chrome.

**Comment by grantfitzsimmons** [comment]
To clarify, the resource linked does not exist, but I can create new ones without any problem.

**Comment by maxxxxxdlp** [comment]
Can you please try this out on the `xml-editor` branch?
For any app resource related bug in the next month or so, please verify that it's not already fixed on the `xml-editor` branch

**Comment by carlosmbe** [comment]
Can confirm that this issue is resolved in the `xml-editor` branch
