### ISSUE TITLE
Deleting Current User Preferences Resets Them

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3416]
**Describe the bug**
After deleting the current logged in user's preferences. I would assume that it would use the collection or global preferences. However, Specify automatically recreates it using the default settings.

**To Reproduce**
1. Log in as `LJensen` 
2. Go to App Resources -> Discipline Resources -> Paleontological Research Institution -> User Accounts -> LJensen -> UserPreferences
3. Delete it and refresh the browser afterwards

**Screenshots**

https://user-images.githubusercontent.com/53784701/234634135-4b2aa389-70bd-409e-be35-ec63bc0c9b4a.mov

**User Defaults**
![Screen Shot 2023-04-26 at 11 01 02 AM](https://user-images.githubusercontent.com/53784701/234634204-b115ad35-ca2c-4b82-a444-66266f9e4e20.png)

**Desktop:**
OS: Mac OSx Ventura
Browser: Chrome
Specify 7 Version: 7.8.10-prerelease

**Database Name:** Updated Pripaleo

**Reported By:**
Carlos @carlosmbe

**Comment by maxxxxxdlp** [comment]
This looks to me like expected behavior.
Any user preference that is not explicitly customized is using the default value.
