### ISSUE TITLE
Sorting on a column can duplicate it in the query builder

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3417]
https://user-images.githubusercontent.com/37256050/234698735-d30001d5-ec89-4bd8-a879-ea5ddd252987.mp4

https://sp7demofish.specifycloud.org/specify/query/124/

This can be recreated on the demo instance. This took place on `v7.8.9` and `edge` from my testing.

Sort the column heading Preparations -> Text 4 to see the issue!

**Comment by grantfitzsimmons** [comment]
[Basic Report Query (1).json.zip](https://github.com/specify/specify7/files/11337103/Basic.Report.Query.1.json.zip)

**Comment by maxxxxxdlp** [comment]
Might be fixed on `specify-netwrok-integration` branch as relevant code was refactored there

**Comment by grantfitzsimmons** [comment]
Looks to be fixed!
