### ISSUE TITLE
Overflow problems with attachment viewer when scaled down

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3418]
Attachment elements overlap, obscuring attachment names.

https://user-images.githubusercontent.com/103299204/234702328-d95ca899-b18d-4e9d-8098-e298a4be558a.mp4

https://coldfish-edge.test.specifysystems.org/specify/attachments/

**Comment by maxxxxxdlp** [comment]
The actual attachment images do not overlap.
What overlaps is the fallback text for failed attachments.
Under real-world conditions, there should not be failing attachments (or if there that's a separate bigger issue), thus this is likely a wont fix
