### ISSUE TITLE
Preference Reset Button Not Working After Changing Font Scaling

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3420]
**Describe the bug**
Title

**To Reproduce**
1. Go to `Gothenburg-`> Log In as `evaan89` -> Collection is `GNM Turbellaria`
2. Go to Customisation-> Preferences 
3. See error

Was created after change font size to 1009

https://gothenberg-v7810-prerelease.test.specifysystems.org/specify/user-preferences/

**Expected behavior**
All Preferences Reset 

**Screenshots**

<img width="1770" alt="Screenshot 2023-04-26 at 5 07 38 PM" src="https://user-images.githubusercontent.com/53784701/234713673-8855350a-272c-4b24-9107-3cf181179d95.png">

Desktop:
OS: Mac OSx Ventura
Browser: Chrome
Specify 7 Version: 7.8.10-prerelease

Database Name: gothenberg

Reported By
@carlosmbe

**Comment by maxxxxxdlp** [comment]
This is because you are clicking on a wrong `Reset` button (there are several in user preferences)

https://user-images.githubusercontent.com/40512816/234942850-f77c7519-1a33-403a-8fed-b5247d3c6c49.mov

**Comment by grantfitzsimmons** [comment]
I can verify this is an unexpected behavior. The user does not have permission to edit app resources, but they should be able to "edit" their own preferences. When you change the font size, it does not trigger the save button. 

https://gothenberg-v7810-prerelease.test.specifysystems.org/specify/

`evaan89` is the user, GNM Turbellaria is the collection. Navigate to user preferences and you will see the problem.

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons 

> The user does not have permission to edit app resources, but they should be able to "edit" their own preferences

That's what user preferences user tool is for. If they don't have access to edit app resources, they should not be editing though app resources

> When you change the font size, it does not trigger the save button.

Known issue. Separate from this issue. https://github.com/specify/specify7/issues/3411

@carlosmbe 

> Opened the link to follow up on the issue and without any action on my end ( I don't know if someone else did something) the scaling is very very different and off throughout the entire GNM Turbellaria when logged in as evaan89

From the original screenshot, it looks like you changed the font size for the form, not for the entire UI (those are separate) that's why results are different
