### ISSUE TITLE
Deleting Lithostrat item results in perpetual loading

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3425]
Happened after cloning the `"Bear River Beds" of Haller` item and attempting to delete the clone. Lithostrat forms also not rendering after attempted delete. Cannot replicate in `7.8.9`.

https://user-images.githubusercontent.com/103299204/234945393-32131030-17a7-44d8-a183-3b8927255a1e.mp4

https://sdnhmpaleo33123-v7810-prerelease-2.test.specifysystems.org/specify/tree/lithostrat/?conformation=%7E%7E1%7E829-%7E830-%7E2-%7E831-%7E29---

**Comment by grantfitzsimmons** [comment]
@realVinayak We will not release without this.

**Comment by realVinayak** [comment]
not an internal bug. On 7.8.9
![Screenshot (134)](https://user-images.githubusercontent.com/61122018/235068163-a0c84a14-066d-40c4-a673-308d31a852e5.png)
![Screenshot (135)](https://user-images.githubusercontent.com/61122018/235068202-b8115a4f-d977-4864-a5d8-1f38ef2de120.png)
Backend seems hung on that - requests are pending.

**Comment by realVinayak** [comment]
a bad bug - props to @chanulee1 for finding this

**Comment by grantfitzsimmons** [comment]
@realVinayak We should probably address this, no?

**Comment by CarolineDenis** [comment]
@realVinayak, were you able to replicate this bug on 7.9?

**Comment by realVinayak** [comment]
I'm fairly certain that this happened for tree stat counts queries, and the backend was hung up on those queries. Can still replicate this bug in v7.9 and production.

Related to https://github.com/specify/specify7/issues/3821

Will be fixed by https://github.com/specify/specify7/pull/3613 once it supports litho tree

**Comment by emenslin** [comment]
Fixed
