### ISSUE TITLE
Check Email Format Before Opening Mail In Agents 

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3428]
**Is your feature request related to a problem? Please describe.**
Having Specify able to prompt your mailing app is cool and all. But it would be better if it made a check that the field actually contained an email address and not some other combination of characters. IE: A phone number, a text message or a [foreign language (No Roman Characters, like Chinese, Korean or Japanese)](https://shkspr.mobi/blog/2016/09/why-cant-you-send-email-to-a-chinese-address/)

**Describe the solution you'd like**
A check that it conforms to the standard [example@domain.com](mailto:example@domain.com) like [richardhendricks@piedpiper.com](mailto:richardhendricks@piedpiper.com)

**Describe alternatives you've considered**
Just denying anything that is not part of ASCII. This would include Foreign Characters and emojis.

**This would prevent the screen shot below from being created.**
<img width="1190" alt="Screenshot 2023-04-27 at 4 05 29 PM" src="https://user-images.githubusercontent.com/53784701/234996200-39ad8177-e770-473e-948b-2fda8e85d03f.png">
<img width="885" alt="Screenshot 2023-04-27 at 4 05 39 PM" src="https://user-images.githubusercontent.com/53784701/234996201-484c3b47-6500-41ef-817a-ab24eee6b699.png">

**Comment by maxxxxxdlp** [comment]
Quite related to #600, though #600 is more generic, not just specific to email weblinks.
What is more, Specify 6 already supports this feature (there is a way to say in the form definition that the web link should be disabled if a certain field is blank, but that does not give sufficient flexibility)
The solution for this particular issue is to make email be a formatted field, and make it use an email formatter

**Comment by grantfitzsimmons** [comment]
Closing in favor of #600
