### ISSUE TITLE
Prolonged fetching of large trees, prevents you from using other parts of Specify 

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3433]
**Describe the bug**
In Pripaleo, if you fully expand the Chronos Stratigraphy tree and leave. 
i.e log out or do something else like work with app resources. 

The next time you open the tree. The entire app will not let you do something else until it reopens all the ranks to their prior state. Which is takes quite some time( > 5 minutes) or until the test panel resets it and causes Specify to throw a `Type Error: Can Not Fetch`. However, sometimes it throws a `ChunkLoadError: Loading chunk failed.`  but I can not constantly recreate but it has happened on 3 separate occasions during this loading state.

**To Reproduce**
1. Go to `Pripaleo` or the updated schema version `Carlos Pripaleo` 
2. Fully expand `Chronos Stratigraphy` tree (Or just use[ this link](https://carlospripaleoschemaupdatedcm202304211540-v7810-prerelease-2.test.specifysystems.org/specify/tree/geologictimeperiod/?conformation=%7E%7E1%7E381-%7E386-%7E367%7E372-%7E376-%7E368--%7E219%7E220%7E15%7E413-%7E414-%7E150-%7E415--%7E19%7E238-%7E428-%7E116-%7E243--%7E419%7E420--%7E221%7E222-%7E223%7E225-%7E224%7E392-----%7E247%7E248%7E249-%7E256--%7E263%7E273-%7E268-%7E264--%7E278%7E286-%7E283-%7E279---%7E289%7E352%7E353-%7E357-%7E361-%7E364--%7E303%7E304-%7E307-%7E309--%7E311%7E316-%7E314-%7E312--%7E318%7E325-%7E322-%7E319--%7E341%7E349-%7E342-%7E346--%7E290%7E298-%7E291-%7E294--%7E329%7E337-%7E331-%7E334------))
4. Enter another part of specify or log out
5. Go to the tree and then try entering a different part of Specify.
6. See error

**Expected behavior**
It would be great if I could abandon the request or just have it be asynchronous in the background.

**Screenshots**
**`Main Loading Issue`**
<img width="1792" alt="Screenshot 2023-05-01 at 11 48 30 AM" src="https://user-images.githubusercontent.com/53784701/235490904-14dfdc7c-5725-4e1b-98f3-d7c4c41b44c4.png">

**`ChunkLoadError: Loading chunk failed`**
The number is different each time I experience it
![Screen Shot 2023-05-01 at 11 38 21 AM](https://user-images.githubusercontent.com/53784701/235491541-04e5f9cc-769f-4bc6-a77a-330dd29c1e52.png)
[Specify 7 Crash Report - 2023-05-01T16_38_10.029Z (1).txt](https://github.com/specify/specify7/files/11366703/Specify.7.Crash.Report.-.2023-05-01T16_38_10.029Z.1.txt)
[Specify 7 Crash Report - 2023-05-01T16_38_10.029Z.txt](https://github.com/specify/specify7/files/11366704/Specify.7.Crash.Report.-.2023-05-01T16_38_10.029Z.txt)

**Desktop:**
OS: Mac OSx Ventura
Browser: Chrome
Specify 7 Version: 7.8.10-prerelease

**Database Name:** Pripaleo and Updated Pri Paleo 

**Reported By**
Carlos @carlosmbe

**Comment by maxxxxxdlp** [comment]
`ChunkLoadError: Loading chunk failed` happens when front-end has been rebuilt since the last time you loaded the page. This happens in development pretty often. It can happen on the test server too if you had the page open for a while. It does not happen in production as front-end is only updated at most once every two weeks (when new version comes out)

**Comment by melton-jason** [comment]
Can this issue be closed? 
I believe the _real_ issue here is the loading time for large/very many requests, which may be fixed by upgrading to http 2 (I _know_ we had an issue open for this, but I can not seem to find it at the moment) or improvements for queries on trees.

**Comment by maxxxxxdlp** [comment]
more context for the future:
we identified that this issue likely only affects the current machine - other users trying to reach the specify 7 server are unaffected.
this is due to max connection limit of HTTP 2
