### ISSUE TITLE
Creating DwCA export causes error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3435]
https://user-images.githubusercontent.com/37256050/235734827-b6b6a116-58d6-40e3-8dbd-ecd11df87762.mov

KU Entomology – `v7.8.9`
http://entomology.specify.ku.edu/specify/overlay/make-dwca/

[Specify 7 Crash Report - 2023-05-02T17_01_54.907Z.txt](https://github.com/specify/specify7/files/11375772/Specify.7.Crash.Report.-.2023-05-02T17_01_54.907Z.txt)

**Comment by grantfitzsimmons** [comment]
This error was due to the space character in the resource name for the metadata. This should be fixed, anyway.

**Comment by melton-jason** [comment]
@specify/ux-testing 
Can this issue be quickly tested and its status verified? 
Is this _really_ an issue or can we close it?

**Comment by maxxxxxdlp** [comment]
This user error should be fixed by the visual editor on the xml-editor branch
