### ISSUE TITLE
More Consistent Behaviour When Deleting Tree Root

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3439]
**Describe the bug**
In the rare case that a tree has nothing using it. When you delete the root, behaviour can vary.

**_Performed in Litho Strat_**
1. 404 Error with tree still present under it
2. Crash - Protected Error 

**_This next one was performed  in a Taxon Tree_**
3. Successful Deletion but prevented from creating a new child or interacting with the tree once more.
Although 3 is expected behaviour.
Be great if it was not possible since not having any parent available in LifoStrat makes it difficult to create anything where that is a required it's a required field.

**To Reproduce**
1. Go to `morpaleo` or another mostly empty database
2. Delete root of a tree
3. See error

**Suggestion**
Block delete similar to how it is blocked when children are present

**Screen Recording, Crash Reports and Crash Reports**

1. Crash - Protected Error 
[Specify 7 Crash Report - 2023-05-02T21_11_35.261Z (1).txt](https://github.com/specify/specify7/files/11377814/Specify.7.Crash.Report.-.2023-05-02T21_11_35.261Z.1.txt)
[Specify 7 Crash Report - 2023-05-02T21_11_35.261Z.txt](https://github.com/specify/specify7/files/11377817/Specify.7.Crash.Report.-.2023-05-02T21_11_35.261Z.txt)

https://user-images.githubusercontent.com/53784701/235783960-fee77c11-e290-4863-ab45-aaced85208e4.mp4

2. 404 Error with tree still present under it

https://user-images.githubusercontent.com/53784701/235783839-4bdced86-949d-4548-94bb-ae27eb8aba06.mp4

3. Successful Deletion but prevented from creating a new child or interacting with the tree once more. <The UI Doesn’t allow it>
<img width="1791" alt="Screenshot 2023-05-02 at 3 38 15 PM" src="https://user-images.githubusercontent.com/53784701/235782640-3da32474-30b8-4e48-8799-163467735332.png">

**Desktop:**
OS: Mac OSx Ventura
Browser: Chrome
Specify 7 Version: 7.8.10-prerelease

**Database Name:** Morpaleo or ANY

**Reported By**
Carlos @carlosmbe

**Comment by grantfitzsimmons** [comment]
Closing in favor of https://github.com/specify/specify7/issues/1819
