### ISSUE TITLE
Specify returns unmapped query for tree's root

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3442]
**Describe the bug**
Title

**To Reproduce**
1. Go to any tree
2. Click on the root and generate the query from the same view. 
3. See error

**Expected behavior**
Root Header should be there rather than "Unmapped" 
This query works perfectly fine but is quite misleading since it's expected to crash or be non-saveable due to the unmapped field but nope. It just works.

**Screenshots**

_**Litho Strat**_

<img width="1791" alt="Screenshot 2023-05-03 at 10 46 42 AM" src="https://user-images.githubusercontent.com/53784701/235969773-88a5d1df-fd1b-483a-8f9e-83721f95db27.png">

<img width="1792" alt="Screenshot 2023-05-03 at 10 53 07 AM" src="https://user-images.githubusercontent.com/53784701/235970958-88f9d62a-0ccf-4588-9b4a-339147e64260.png">

<img width="1792" alt="Screenshot 2023-05-03 at 10 54 56 AM" src="https://user-images.githubusercontent.com/53784701/235970968-0ac034e4-0d58-47a1-b64a-6d065c668889.png">

<img width="1604" alt="Screenshot 2023-05-03 at 10 57 08 AM" src="https://user-images.githubusercontent.com/53784701/235972040-60db906b-cd97-45d3-abdb-278aef62e019.png">

**Desktop:**
OS: Mac OSx Ventura
Browser: Chrome
Specify 7 Version: 7.8.10

**Database Name:** morpaleo

**Reported By:**
Carlos @carlosmbe

**Comment by maxxxxxdlp** [comment]
This is because tree root is hidden in the query builder.
The "Query" button in the tree viewer should be disabled for tree root.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-11-release-announcement/1174/1
