### ISSUE TITLE
Workbench picklist ordering is behaving oddly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3444]
> We have seen some weird behaviour with one of our dropdown picklists for a Collecting Event field - In a Query or on a Data Entry form the values appear alphabetically, but in the Workbench they seem to start at "P" instead of "A"!
> 
> ![image](https://user-images.githubusercontent.com/37256050/236025089-2e3297e5-b681-4d7f-a505-7f57707b5000.png)
> 
> I checked in the picklistitem table and the PickListItemID is tagged on the values alphabetically - what else would the workbench be using to order these values?

**Reported By:** CSIRO ([Asana](https://app.asana.com/0/1201972579963460/1204519950464926/f))

@maxxxxxdlp:
> Can we reproduce the issue on our end?
> 
> hmm, weird. It looks like we are not sorting them at all on the front-end
> 
> we don't sort in the wb - but do in other places
> 
> I will modify it to also do sorting

**Comment by grantfitzsimmons** [comment]
Looks like @maxxxxxdlp fixed this in this commit:
https://github.com/specify/specify7/commit/d899e6fecb2ccbf9de548b89ea73c00c109d5ffb

Reopen if this issue appears again

**Comment by maxxxxxdlp** [comment]
yes I fixed it, but the fix is still on the xml-editor branch, not in 7.9
does it need to be verified by someone other than the developer before being closed, or did you already verify it? @grantfitzsimmons
