### ISSUE TITLE
Add preference for selecting default taxon rank when adding a child on taxon form

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#345]
Below is an email thread describing the issue.
Basically, whenever a user wants to add a child to a taxon (i.e. add a 'genus' to a 'family' or add a 'species' to a 'genus'), clicking "add child" in the taxon tree, or looking up the parent taxon on the taxon form calculates the next immediate rank under the parent taxon that's available in the taxon tree definition, then inputs that rank automatically in the "Rank" field of the form. This can be annoying, as less common fields like "subfamily" and "subgenus" are automatically selected instead of "genus" and "species" respectively.

===================================================================
From: Kevin Holston <Kevin.Holston@nrm.se>
Date: Tue, Feb 14, 2017 at 3:51 AM
Subject: Re: A user question
To: Theresa Miller <support@specifysoftware.org>

Thanks, Theresa! I appreciate the frustration Tim expressed. I figured that it might be more pain to address in the look-up than would be worthwhile. Changing the code to select only the enforced levels would make it necessary to "toggle" this choice so unenforced levels could be made available on demand.

My guess is this preference setting could be cryptic to a user. If a rank is not available in the taxon name data entry form, then is it going to be clear to the user that the "hidden" rank is actually in the tree definition? Keeping a user aware of a subset of alternative choices - one set of “preferred” choices and the other set of “relevant” choices - sounds a bit complicated. And it does not really address the expressed desire for a default value.

The only suggestion that have is to set the default value for rank based on a user menu choice for genus names, invoked using the tree interface right-click menu. Instead of the unconstrained “Add child”, a user could select “Add species” and have the genus and the rank of the name (=“species") added automatically. I have not run this particular idea by any “real” users here. I will note, however, that the user who initiated this discussion mentioned that she was using the graphical interface to select the genus to which she wanted to add a species.

So, to cover both of her use cases… “Add genus” as a new choice for family-rank names so “subfamily” is not the default, “Add species” as a new choice for genus-rank names so “subgenus” is not the default. The parent taxon is entered automatically as it was previously. This form-mediated solution would work even when taxon tree definitions do not enforce ranks - and it is unlikely that a taxon tree would lack these ranks. If not, then I suppose there should be an error message like “Rank not available in taxon tree”.

Cheers,
Kevin
On 13 Feb 2017, at 19:17, Theresa Miller <support@specifysoftware.org> wrote:

Kevin,
Great to hear from you.  Tim said that annoys him too but "it just picks the highest rank in the list. It probably wouldn't be hard to change the code so it picked the highest of specify's default enforced levels. Preferred default child level prefs for each rank would probably require a lot of work."
Theresa

Specify User Support
785-864-4400
specify@ku.edu
http://specifysoftware.org
http://vimeo.com/specifysoftwa re

On Mon, Feb 13, 2017 at 7:12 AM, Specify Software Project <specify@ku.edu> wrote:

______________________________ __________
From: Kevin Holston
Sent: Monday, February 13, 2017 7:12:33 AM (UTC-06:00) Central Time (US & Canada)
To: Specify Software Project
Subject: A user question

Greetings from Sweden!

I have a question about setting taxon form preferences.

There seems to be some kind of calculation to figure out which ranks for a name are available, which depends on the selected parent taxon and what ranks are part of the tree definition. Some ranks are rarely used but are at the top of the list of available ranks for certain names. The user wanted to enter a genus as a child of a family name but the rank subfamily is the “default” value although genus is preferred as a default. Similarly, and maybe even more frequent, adding a child to a genus results in the rank “subgenus” as a default instead of the preferred (“species”).

Is it possible to set “genus” as a preferred rank for a child record of a “family” name and a “species” name as a preferred rank for a child record for a “genus” name? Current default values are “subfamily” and “subgenus”, respectively.

Best regards,
Kevin

**Comment by benanhalt** [comment]
Also the possibility of having no default which would force the user to select and not just skip over the field leaving whatever was there.

**Comment by benanhalt** [comment]
Defaulting to next enforced probably makes the most sense.

**Comment by maxxxxxdlp** [comment]
Fixed in d2c3d9f9
The tree rank combo box now defaults to the next enforced rank
