### ISSUE TITLE
"bycatalog" URL does not work when signed in to a different collection

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#3451]
Example: https://sp7demofish.specifycloud.org/specify/bycatalog/KUIT/5085/

It is supposed to switch collection automatically, but that does not happen due to react-router bug

![image](https://user-images.githubusercontent.com/40512816/236271351-b78e72f0-8db9-4f7d-bf85-d0446524bc6c.png)

**Comment by grantfitzsimmons** [comment]
The bulk of the work needed to fix this was likely included in https://github.com/specify/specify7/pull/3452 so we should wrap this up and finish it.
