### ISSUE TITLE
Collector OrderNumber should start at 0.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#346]
The first collector added to a collecting event in Specify 7 receives the order number 1. In Specify 6 it receives 0.

**Comment by garrettgirard** [comment]
Is there somewhere in Specify in which I can see the order number? Is it some agent/collector field or is it something more behind the scenes?

**Comment by benanhalt** [comment]
Hmm. I guess the user that discovered this must have unhidden the field in their database. It is the William&Mary database that you can find in their folder on the Specify share. In that one you can select Order Number in a query.

**Comment by garrettgirard** [comment]
Tested this in William&Mary database. Now when Collecting Event records are created with collectors, the first collector added is given order number = 0, instead of 1.
