### ISSUE TITLE
Order of tables in Data Entry popup does not change consistently after configuration

### ISSUE THREAD

**Issue by mpitblado** [specify/specify7#3461]
**Describe the bug**
When attempting to configure data entry tables through the popup, unclear/inconsistent behaviour from the up and down arrows located to the left of the Select Tables section. Sometimes the table will move up one space after pressing the arrow three times, sometimes it will not move at all, and there are no visual cues in the Configure data entry tables popup to indicate the change in the order (contrasting to how tables visually shift from Possible Tables to Selected Tables when the left and right arrows are pressed).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to sp7demofish.specifycloud.org
2. Click on 'Data Entry' in the navigation panel.
3. Click on the pencil icon to open the Configure data entry tables popup
4. Select a table from the Selected Tables section by clicking on it with the mouse.
5. Click on the up and down arrows to the left of the Select Tables section
6. Close the editor and repeat step 2. Observe the order of the tables presented in the Data Entry popup, and how it does not match the changes made via the arrows.

**Expected behaviour**
The order of the tables within the presented list would change after pressing the arrows. The table names would move up and down based on pressing the up and down arrow buttons within the Configure data entry tables popup.

**Screenshots**
Not applicable

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 - Specify 7 Version: v7.8.10

**Reported By**
Beaty Biodiversity Museum

**Comment by maxxxxxdlp** [comment]
@CarolineDenis Tasks:
1. Reproduce the issue on sp7demofish
2. Check if issue is reproducible on `xml-editor` branch
3. If it is, then fix it on that branch
4. If it isn't then close this issue with a comment saying fixed in next release

**Comment by CarolineDenis** [comment]
fixed in the next release
