### ISSUE TITLE
Cannot loan items in `v7.8.10`

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3462]
Loan the following numbers:
`14898,15771,35657`

This looks to have been introduced in https://github.com/specify/specify7/pull/3370 – @CarolineDenis can you take a look?

`v7.8.9`:
https://vimsfish-v789.test.specifysystems.org/specify/overlay/interactions/
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/37256050/236884610-2e7c3e4e-6aa4-4f4d-b386-efb5d8483ead.png">

`v7.8.10`:
https://vimsfish-v7810.test.specifysystems.org/specify/overlay/interactions/
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/37256050/236884637-c3f7082c-77a6-476e-b0d7-5ce83052bb4f.png">

**Reported By:** VIMS Fish

**Comment by CarolineDenis** [comment]
Issue fixed in https://github.com/specify/specify7/pull/3438

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-11-release-announcement/1174/1
