### ISSUE TITLE
`xml-editor`: Cannot access 'm' before initialization

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3465]
```
ReferenceError: Cannot access 'm' before initialization
```

Whenever I attempt to access an app resource, I see this error:

<img width="1533" alt="Screenshot 2023-05-08 at 1 58 27 PM" src="https://user-images.githubusercontent.com/37256050/236909092-88a657a4-a0d9-49e7-8320-b712f0ac64af.png">

[Specify 7 Crash Report - 2023-05-08T18_58_32.233Z.txt](https://github.com/specify/specify7/files/11424278/Specify.7.Crash.Report.-.2023-05-08T18_58_32.233Z.txt)

https://vimsfish-xml-editor.test.specifysystems.org/specify/resources/app-resource/68/

**Comment by melton-jason** [comment]
I am not able to recreate this on `xml-editor`. 
Is this still an issue?
