### ISSUE TITLE
Feature Request: Add link to Specify Web Portal

### ISSUE THREAD

**Issue by jburleson** [specify/specify7#347]
We would like to be able to have a link to the Specify Web Portal on Specify 7. Maybe a variable define in the specify_settings.py that if not an empty string would add the link on the login page. It might also be nice to have the link somewhere on the pages after you log in as well.

**Comment by benanhalt** [comment]
@jburleson Thanks for the suggestion!

**Comment by maxxxxxdlp** [comment]
This can be implemented by collection managers by displaying a custom HTML page instead of the splash image on the welcome page.

Just point the welcome page to an HTML page that contains a link to Web Portal.

See more info - https://github.com/specify/specify7/issues/500
