### ISSUE TITLE
Storage Tree Using Rank ID Leads To Crash

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3473]
**Describe the bug**
At the moment this is only happening in the `Updated Pripaleo` 
When I try to add a child. Specify crashes. I assume it's related to it having the parent saved as an `ID#` rather than the it's rank.
<img width="1329" alt="Screenshot 2023-05-09 at 3 11 05 PM" src="https://github.com/specify/specify7/assets/53784701/cb9f2833-d8be-4bb6-b594-f3d6bbc23a74">

As for the cause. I am Investigating and will comment any findings. 

**To Reproduce**
Log Into `Pripaleo` I used `testuser`
Go to Storage and try adding a child. When selecting it's parent it should crash.

**Expected behavior**
I select a parent and it does not crash.

**Screen Recording and Crash Reports**

[Specify 7 Crash Report - 2023-05-09T20_14_19.683Z (1).txt](https://github.com/specify/specify7/files/11435754/Specify.7.Crash.Report.-.2023-05-09T20_14_19.683Z.1.txt)

[Specify 7 Crash Report - 2023-05-09T20_14_19.683Z.txt](https://github.com/specify/specify7/files/11435755/Specify.7.Crash.Report.-.2023-05-09T20_14_19.683Z.txt)

https://github.com/specify/specify7/assets/53784701/b10f535d-02ee-4283-99f9-67d06f6dfabe

<img width="1792" alt="Screenshot 2023-05-09 at 3 14 14 PM" src="https://github.com/specify/specify7/assets/53784701/4e51d444-a4eb-4e60-9462-1cc4327e00b6">

**Comment by carlosmbe** [comment]
This is also happening to all children of the tree

<img width="1787" alt="Screenshot 2023-05-09 at 4 01 06 PM" src="https://github.com/specify/specify7/assets/53784701/84c70196-d777-4e16-8e39-4e2620ce82c9">
<img width="1622" alt="Screenshot 2023-05-09 at 4 00 48 PM" src="https://github.com/specify/specify7/assets/53784701/59f02677-af02-46a7-96b8-2887bdcf1b68">
<img width="1331" alt="Screenshot 2023-05-09 at 4 00 42 PM" src="https://github.com/specify/specify7/assets/53784701/ce8fee2d-f3d6-48ac-808e-023f8db11652">

**Comment by grantfitzsimmons** [comment]
Looks like this crash is happening because the form definition references `storageLocation` when it is, in fact, not in the Storage table, but in the Preparation table. I will close as this is specific to this database's incorrect configuration.
