### ISSUE TITLE
Unable to remove Specify 6 access for a user

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3477]
**Error:**
```
"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1"
```

In the `dfo_arc` database on Specify Cloud, I cannot remove collection access for the user "Lou"
`/specify/security/user/2/`

<img width="1200" alt="image" src="https://github.com/specify/specify7/assets/37256050/0edfd9c3-1be1-4afc-9a34-caa5342334a2">

[Specify 7 Crash Report - 2023-05-10T16_18_22.797Z.txt](https://github.com/specify/specify7/files/11444096/Specify.7.Crash.Report.-.2023-05-10T16_18_22.797Z.txt)

**Comment by maxxxxxdlp** [comment]
Duplicate of #1174
