### ISSUE TITLE
The code to allow multiple cos to be added to accessions in Sp6 (bugzilla #10242) broke accessions in 7

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#348]

**Comment by timo11** [comment]
If the accession form opens for new record entry when accessions is clicked on the interactions dialog, the problem is fixed.

**Comment by benanhalt** [comment]
The database I was testing with has InteractionsTaskInit stored in the database, so I wasn't seeing the bug.

**Comment by garrettgirard** [comment]
This bug appears to be fixed. However, before verifying the issue, I just wanted to check to make sure it's the case that Specify 7 doesn't currently support adding Collection Objects to Accessions from the Accession form? I don't see that option available on any database.

**Comment by timo11** [comment]
No. Specify 7 doesn't allow adding collectionobjects on the accessions form.

**Comment by garrettgirard** [comment]
Okay good, just wanted to make sure!
