### ISSUE TITLE
Remove size limit enforcement for pick lists

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3482]
Today, the size limit had a bug related to it, and that refocused our attention on whether the size limit is useful at all. The limit should just be removed if it only serves as a vessel for bugs!

from @maxxxxxdlp:
> Size limit was useful in sp6 as pick list items were added automatically
> not useful in sp7 at all
> and like Ben said, it's an "antifeature"

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-13-release-announcement/1230/1
