### ISSUE TITLE
Cannot create a loan "By Choosing a RecordSet"

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3486]
Applies to gifts as well. Not present in `7.8.10`.

https://github.com/specify/specify7/assets/103299204/c58f73fe-8cbe-4c23-9079-597861e6d212

https://sdnhmpaleo33123-v7811-prerelease.test.specifysystems.org/specify/overlay/interactions/

**Comment by grantfitzsimmons** [comment]
We can't release without this fix

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-11-release-announcement/1174/1
