### ISSUE TITLE
If a user agent was not found for a collection, the web GUI stalls at 'Specify is loading...'

### ISSUE THREAD

**Issue by jburleson** [specify/specify7#349]
Specify 7: v7.2.0-1

If you select a collection that your user does not have an user agent for, the web interface just says `Specify is loading...`. All GUI elements are gone and the only option is to hit the browser back button.

Suggestion: Warning message indicating that the user account does not have access to the collection with a link to go back to previous page.

**Comment by benanhalt** [comment]
@jburleson collections share agents within a discipline so user access to collections is not managed by whether they have associated agents. There is a tool in the "Manage users" dialog available to admin users that allows access to collections to be set for different users.

That said, if a user is missing an agent and tries to login, that error should be caught and handled. This is a regression of issue #179. See also #200.

**Comment by jburleson** [comment]
Hmm....maybe the issue is only related to admin accounts. As an admin, when I login Specify 7 shows me a list of all the collections. This may not be an issue for normal user accounts. It could also be how they setup my user account. Maybe they did not add me correctly when they created it from Specify 6. I will check with the person tomorrow see what my account looks like.

**Comment by benanhalt** [comment]
I was able to reproduce the bug by creating a user and not assigning it any agents.

**Comment by rdcooper408** [comment]
I am getting this same issue with any level of user i have tried.
If i attempt to login as: 
Master user, Full access user, or Guest user (all with agents assigned via security tools window)

I am testing this using the django development server (python specify7/specifyweb/manage.py runserver)
I installed specify just yesterady, and am using a newly created DB
OS: Ubuntu 16.04 LTS
