### ISSUE TITLE
`agent-merging-extremos`: Merging agents does not work

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3499]
https://sp7demofish-agent-merging-extremos.test.specifysystems.org/specify/overlay/merge/Agent/?records=3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%2C11%2C12%2C13%2C14%2C15%2C16

Attempting to merge a batch of agents shows a 404 message.

https://sp7demofish-agent-merging-extremos.test.specifysystems.org/specify/overlay/merge/Agent/?records=3%2C4%2C5%2C6

https://github.com/specify/specify7/assets/37256050/cd76651b-cde1-4aae-92d6-62b897a190ac

**Comment by melton-jason** [comment]
This is actually a frontend issue. The frontend has not yet been updated to use the updated endpoint. 
I will see if I can update the frontend to use the updated endpoint

**Comment by melton-jason** [comment]
@grantfitzsimmons 
This should be fixed in [03f11a11](https://github.com/specify/specify7/commit/03f11a11dcd02dd94c1c28629d514d15794a875a)
Feel free to test agent merging on this branch again!

**Comment by grantfitzsimmons** [comment]
Fixed in https://github.com/specify/specify7/commit/03f11a11dcd02dd94c1c28629d514d15794a875a
