### ISSUE TITLE
Empty Trees Should Not Be Interactive 

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3500]
**Describe the bug**
In the event of a tree being completely empty and having it's root gone. The Tree should not be interactive as there is no direct easy way of creating a new root and performing certain task  like adding a child become impossible as there is no Parent. However, you can still try and either it throws a 404 or forever loads until you refresh the page.

Sometimes the expected behaviour is met but not always

**To Reproduce**
1. Go to `invertpaleo`
2. Enter the `Taxon Tree`
3. Enter another tree that has items and then go back to the `Taxon Tree`
4. Do something that requires a Parent. I.E Add a child
5. See errors

**Screenshots**

<img width="1792" alt="Screenshot 2023-05-15 at 12 36 59 PM" src="https://github.com/specify/specify7/assets/53784701/f04cd8c2-101b-455d-9c1c-1aea03704394">

<img width="1788" alt="Screenshot 2023-05-15 at 12 37 42 PM" src="https://github.com/specify/specify7/assets/53784701/20dc6157-3016-4737-b74e-1fd14a07b77b">
<img width="1792" alt="Screenshot 2023-05-15 at 12 37 54 PM" src="https://github.com/specify/specify7/assets/53784701/6aac939c-c4db-4555-8889-be598da8a375">
<img width="1792" alt="Screenshot 2023-05-15 at 12 38 08 PM" src="https://github.com/specify/specify7/assets/53784701/e24cc44b-25d5-4caf-aff0-c2a75db661b0">

This load never ends
<img width="1792" alt="Screenshot 2023-05-15 at 12 38 15 PM" src="https://github.com/specify/specify7/assets/53784701/d5dd712d-d07d-465d-8cb1-b3747cd16310">

**Comment by CarolineDenis** [comment]
Fixed in https://github.com/specify/specify7/pull/3586
