### ISSUE TITLE
Trees on narrow screens display incorrectly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3504]
https://github.com/specify/specify7/assets/37256050/b4d51039-73a9-493b-afa0-10f6230ff97c

Once the buttons become scrollable, the tree also only occupies a small amount of space instead of being full height.

**Comment by CarolineDenis** [comment]
@grantfitzsimmons I cannot reproduce this. 
Tried on: 
- prod Chrome
- prod Safari 
- prod Firefox 
- Testpanel Chrome 
- Testpanel Firefox

**Comment by grantfitzsimmons** [comment]
I was able to recreate this consistently for weeks, but as of this moment, I cannot. Maybe I need to try again on an external monitor. Thanks for trying to verify this! I will reopen if I encounter this issue again.

**Comment by maxxxxxdlp** [comment]
> was able to recreate this consistently for weeks, but as of this moment, I cannot. Maybe I need to try again on an external monitor. Thanks for trying to verify this! I will reopen if I encounter this issue again.

Likely because it was a browser bug that is now fixed on their side

**Comment by grantfitzsimmons** [comment]
<img width="859" alt="image" src="https://github.com/specify/specify7/assets/37256050/91a5436d-71a3-41a6-810b-ec2d353c280c">

It's in Firefox now, too!

https://sp7demofish.specifycloud.org/specify/tree/taxon/?conformation=%7E%7E1%7E15797%7E17025%7E4-----
