### ISSUE TITLE
Unable to save WorkBench Datasets

### ISSUE THREAD

**Issue by melton-jason** [specify/specify7#3512]
I am unable to save Workbench Datasets on `production`. This applies to both new datasets and pre-existing datasets. 

Here is a very simple, one-column dataset that was created on this branch. 
The `Save` button remains unclickable (disabled), regardless of any changes done to the Dataset (adding other columns produces the same behavior). 

https://github.com/specify/specify7/assets/64045831/ab76dcb1-4ecd-4a3a-befa-3d74b4c60e1d

Specify acts like the Dataset needs saved, as cells remain colored after modifications, the `Validate` button becomes disabled, and a 'Changes have not been saved' dialog is shown when trying to navigate away from the page.

https://github.com/specify/specify7/assets/64045831/ef4c87ba-9cc3-46ad-8e34-241ffeb2bdc1

Specify 7 Version: `production`
Browser: `Chrome`
Databases Tested: A local instance, `KU_Fish_5_16_23`, `KU_Birds_5_16_23`

**Comment by maxxxxxdlp** [comment]
Fixed in a0d926fb4
