### ISSUE TITLE
Disable Colour Picker When User Does Not Have Permission To Change App Resources 

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3519]
**Describe the bug**
Title. Everything else is disabled. I.E TextFields, Drop Downs and Save Button does not work. But the colour picker still shows up. It doesn't really affect anything(you can not save) but it would be better if it doesn't show up.

**To Reproduce**
1. Go to `App Resource: UserPreferences` as a user without permissions 
2. Click on any colour
3. See error

**Expected behavior**
Not interactive like everything else

**Screen Recording**

https://github.com/specify/specify7/assets/53784701/beb84390-d7bb-4746-9ad1-b61181646dc8

**Desktop:**
 - OS: MacOSx Ventura
 - Browser: Chrome
 - Specify 7 Version: 7.8.11

**Database Name:** Gree -> Logged in as `Carlos_Wilson`

**Comment by maxxxxxdlp** [comment]
This is already fixed on the xml-editor branch. Can you test?

**Comment by carlosmbe** [comment]
@maxxxxxdlp This issue is not fixed in XML Editor.
