### ISSUE TITLE
Console error when exiting query builder

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#3523]
1. Open production branch
2. Open query builder
3. Add any field
4. Open any other page
5. See an error in the console

![Screenshot 2023-05-22 at 12 43 38](https://github.com/specify/specify7/assets/40512816/7d199ee9-fba2-4b02-8044-eb474b7f15b2)

<details><summary>Hint</summary>
<p>

Turns out the value of `mirror` is not always of type `Element | null`.

</p>
</details> 

<details><summary>Solution</summary>
<p>

Replace:
```ts
      const mirror = (
        sortable as unknown as { readonly mirror: Element | null }
      ).mirror;
      if (mirror !== null) mirror.parentNode?.removeChild(mirror);
```
with:
```ts
      const mirror = (
        sortable as unknown as { readonly mirror?: Element | null }
      ).mirror;
      mirror?.parentNode?.removeChild(mirror);
```

</p>
</details>

**Comment by melton-jason** [comment]
It appears there was a typo in this issue's title. 
Is it supposed to be 'Console error when exiting query builder'?

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-12-release-announcement/1202/1
