### ISSUE TITLE
Wrong size `Save` button used in query builder

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#3524]
During the recent refactoring of button names, the save buttons were made to use a different component. Unfortunately, in the process, the sizes of save buttons changed in some places. One example is the schema config header.

![Screenshot 2023-05-22 at 13 00 43](https://github.com/specify/specify7/assets/40512816/a51bbd08-f668-4095-9a46-fdf7dddbc7e4)

Please fix the sizing of this button (see older version of specify if need to compare how it looked) and review all the other save buttons to check where size might be been changed mistakingly

**Comment by grantfitzsimmons** [comment]
I liked these big buttons 😂

**Comment by maxxxxxdlp** [comment]
I would say I do too

When I opened this issue, I was mainly concerned about this being an unintentional change, that I didn't stop to consider whether it's actually a change for good. 😢 

Though my other intention with this issue was to revisit all the buttons that were changed just to make sure none of them broke in a worse way than this one
