### ISSUE TITLE
Attachments - Sort By Timestamp Created Unavailable 

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3526]
**Describe the bug**
Timestamp created is not showing up in the attachment sort by options. 
It only shows up on first launch since, I assume, it's the default. However, if you look at the screen shot. Only the current selected(Descending) `Timestamp Created` is available. Otherwise, it's not showing up in the (Ascending)

After selecting another option the initially selected Timestamp Cerated Sort disappears

**To Reproduce**
1. Go to Attachments
2. Click on `Order By`
3. See error

**Screenshots**
<img width="1791" alt="Screenshot 2023-05-22 at 4 01 02 PM" src="https://github.com/specify/specify7/assets/53784701/b2380961-c650-473e-ae97-a62643401769">
<img width="1790" alt="Screenshot 2023-05-22 at 3 59 22 PM" src="https://github.com/specify/specify7/assets/53784701/25b08e49-e7f5-441f-976e-e5d7a12e3e8e">

**Desktop:**
 - OS: Mac OsX Ventura 
 - Browser: Chrome
 - Specify 7 Version: 7.8.11
 
**Database Name:** KUFish_5_16_23  _[Also known as the new Fresh Fish/Cold Fish]_

**Comment by carlosmbe** [comment]
The assumption from @maxxxxxdlp was correct. It was hidden. 
After talking to Jason about it. It was noted that the default value is either the cache and if that is empty then it's `Timestamp Created`. 
A good alternative would be that whatever the first unhidden value is, would be the default if the cache is empty
🤷🏾‍♂️

**Comment by emenslin** [comment]
Intended behavior right now
