### ISSUE TITLE
Log in screen improvememts

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3530]
> Can we change this login screen to shorten the dialog text to:
> Username and/or password not recognized.
> Both fields may be case sensitive.
> (so that the text appears on two lines only-- that's the main thing)
> Should the word "Language"
> be on top of the pick list at the top, like Username and Password are below, for consistency?

Change from this:
![image](https://github.com/specify/specify7/assets/37256050/482aaeb0-f941-4197-a4b6-728b97008f94)

To this:
![image](https://github.com/specify/specify7/assets/37256050/2547763b-f3bb-45a3-842d-7561b5c67acb)

Make sure spacing is correct on the padding between language and the language chooser if this is implemented

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-12-release-announcement/1202/1
