### ISSUE TITLE
Use proper icons for paginator elements

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3536]
Not this:
<img width="282" alt="image" src="https://github.com/specify/specify7/assets/37256050/c108ff50-9d9c-46b8-aa80-e0ff6d6a2239">

Should be this:
<img width="320" alt="image" src="https://github.com/specify/specify7/assets/37256050/98c244a4-c56e-4d52-9953-27055edcc900">

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-12-release-announcement/1202/1
