### ISSUE TITLE
Investigate unicode support in schema localization

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#3541]
Sorry, this is an old screenshot so don't have much data, but switching schema language to Ukrainian and opening a collection object form in Specify 7 displayed these Unicode escape codes rather than the characters:

<img width="684" alt="Screenshot 2023-02-21 at 12 49 08" src="https://github.com/specify/specify7/assets/40512816/ea353064-a6ed-4e70-853b-c23076c87be9">

(the "Attachments" separator on the Collection Object form is not displayed correctly)

Note, that the 2nd line on the screenshot displays correctly, thus this could be an issue with this particular string and not the entire file.
Thus, need to do some testing to see if issue can be replicated

**Comment by grantfitzsimmons** [comment]
I am going to close this unless we replicate the issue again.
