### ISSUE TITLE
`Show Field Mapper` Has No Background. Similar to a disabled button

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3547]
**Describe the bug**
The Button still works. It just looks like it's disabled. Similar to how the `Save Query` Button looks like when in an already saved query

<img width="1792" alt="Screenshot 2023-05-31 at 1 34 59 PM" src="https://github.com/specify/specify7/assets/53784701/d2cedb7a-3730-4b6f-a822-ed0f2dcdd44b">

**To Reproduce**
1. Go to Query
2. Click on `Hide Field Mapper`
3. See error

**Screenshots**

https://github.com/specify/specify7/assets/53784701/e4e4c096-c51b-4596-989a-35a7fcee1053

**Desktop:**
 - OS: Mac OSx Ventura
 - Browser: Chrome
 - Specify 7 Version: 7.8.11 and Edge as of 31 May 2023

**Comment by maxxxxxdlp** [comment]
Seems like the issue is that the styles for the `aria-pressed="true"` button and `disabled="disabled"` button are similar

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-13-release-announcement/1230/1
