### ISSUE TITLE
Have side menu background in dark mode at all times. 

### ISSUE THREAD

**Issue by CarolineDenis** [specify/specify7#3554]
![IMG_3039](https://github.com/specify/specify7/assets/108160931/b8ed4249-7c4c-477f-86a1-132483e4c0f9)
will change to: 
![IMG_1503](https://github.com/specify/specify7/assets/108160931/3711982e-1352-448e-b51f-d0fd5dea7e4d)

**Comment by grantfitzsimmons** [comment]
I proposed the initial screenshots ^^ ⭐️
This could look really nice

**Comment by CarolineDenis** [comment]
> I proposed the initial screenshots ^^ ⭐️
> This could look really nice

Agree! This is going to look so good.
