### ISSUE TITLE
`xml-editor`: Hierarchy Exception when defining formatters and aggregators for some tables.

### ISSUE THREAD

**Issue by realVinayak** [specify/specify7#3564]
**Describe the bug**
The backend raises a Hierarchy Exception when defining formatters and aggregators for some tables. Need to do more digging into what the cause is. 

**To Reproduce**
1. Go to the visual editor for defining formatters and aggregators.
2. Go to either Formatters menu or the Aggregators menu.
3. Click on table 'Appraisal' and then click on 'Add'

**Expected behavior**
It shouldn't crash and allow to make formatters / aggregators

**Screenshots**
![image](https://github.com/specify/specify7/assets/61122018/7da6d170-99e5-44a0-a1c7-685df6d32acc)

Also: HierarchyException when choosing a table on the web link form

Describe the bug
When choosing a table for a web link, a HierarchyException occurs

HierarchyException at /api/specify/agentidentifier/ queryset model Agentidentifier has no hierarchy field 
To Reproduce

Go to a 'WebLinks' app resource
Edit a web link by choosing one from the list (or create a new one)
Choose the 'Agent Identifier' table as a base
See error appear
Screen Recording
https://github.com/specify/specify7/assets/37256050/bae92ea3-323e-4c3e-a0f9-0e9930b0fc3f

[Specify 7 Crash Report - 2023-12-05T15_21_29.112Z.txt](https://github.com/specify/specify7/files/13561952/Specify.7.Crash.Report.-.2023-12-05T15_21_29.112Z.txt)

Also: Creating a new formatter for AccessionCitation throws an error

image
https://kufish51623-issue-3565.test.specifysystems.org/specify/resources/app-resource/9/formatter/AccessionCitation/58

[Specify 7 Crash Report - 2023-10-24T01_18_54.997Z.txt](https://github.com/specify/specify7/files/13096897/Specify.7.Crash.Report.-.2023-10-24T01_18_54.997Z.txt)

Encountered when testing https://github.com/specify/specify7/pull/4114

**Comment by melton-jason** [comment]
I've seen this error before too, and it's a backend exception.

The exception is defined and used in [filter_by_col.py](https://github.com/specify/specify7/blob/production/specifyweb/specify/filter_by_col.py)
Here are the relevant lines

```python

HIERARCHY = ['collectionobject', 'collection', 'discipline', 'division', 'institution']

... # Lines tuncated for clarity

for fieldname in HIERARCHY:
        if getattr(queryset.model, fieldname, None):
            break
    else:
        if strict:
            raise HierarchyException('queryset model ' + queryset.model.__name__ + ' has no hierarchy field')
        else:
            return queryset
```


I'm assuming this problem also occurs in the `xml-editor`backend-fixes` branch?

**Comment by acwhite211** [comment]
So I was able to avoid the HierarchyException error by setting `strict=False` in the call to the filter_by_collection function
https://github.com/specify/specify7/blob/3b468ec22baf38bc29dfeb77ad7bde6a54bf05ed/specifyweb/specify/api.py#L803C18-L803C18
```python
# objs = filter_by_collection(objs, logged_in_collection)
objs = filter_by_collection(objs, logged_in_collection, strict=False)
```
I'm looking into if this could be an appropriate fix, or if another solution would be better.

**Comment by acwhite211** [comment]
Seems like the two options to prevent the hierarchy exception from occurring in this case are to either set `domainfiler=false` in the api call, or set `strict=False` in the apply_filters function.

https://github.com/specify/specify7/blob/e2d245febde1791a82f3c9ef421fbc761a422fd5/specifyweb/frontend/js_src/lib/components/Formatters/Preview.tsx#L35-L49
```typescript
        fetchCollection(
          table.name,
          {
            limit: defaultPreviewSize,
            domainFilter: false,
          },
          {
            orderBy: [
              ...(table.getField('timestampModified') === undefined
                ? []
                : ['-timestampModified']),
              '-id',
            ].join(','),
          }
        ).then(({ records }) => records.map(deserializeResource)),
```

https://github.com/specify/specify7/blob/28044671d26ac62409c0b557db0cd2668e3744d1/specifyweb/specify/api.py#L802-L803
```python
if control_params['domainfilter'] == 'true':
        # objs = filter_by_collection(objs, logged_in_collection)
        objs = filter_by_collection(objs, logged_in_collection, strict=False)
```

Any ideas if setting `strict=False` in this case would cause any problems in other situations?
Think it would be simplest to just set `domainfiler=false` on the front-end.  Thoughts? @melton-jason

**Comment by melton-jason** [comment]
> Any ideas if setting strict=False in this case would cause any problems in other situations?

I would rather not set strict=False when calling `filter_by_collection` at  https://github.com/specify/specify7/blob/28044671d26ac62409c0b557db0cd2668e3744d1/specifyweb/specify/api.py#L802-L803. 

Every API call which fetches a collection of resources (like `api/specify/collectionobject/`) goes through that line of code of applying filters, and `filter_by_collection` is only called here if `domainfilter` is explicitly passed as a parameter in the query, so I think it's sensible to raise the exception. 

If a proper solution to the root cause can not be found in time, I agree the better short term solution would be to remove the `domainfilter` parameter from https://github.com/specify/specify7/blob/e2d245febde1791a82f3c9ef421fbc761a422fd5/specifyweb/frontend/js_src/lib/components/Formatters/Preview.tsx#L35-L49

This has already been somewhat discussed in #4330 (see https://github.com/specify/specify7/pull/4330#issuecomment-1870455248 and https://github.com/specify/specify7/pull/4330#issuecomment-1870478510)

**Comment by melton-jason** [comment]
> This might be a duplicate of #3564, so feel free to combine if so.
> 
> **Describe the bug**
> 
> ```
> HierarchyException at /api/specify/address/ queryset model Address has no hierarchy field
> ```
> 
> <img alt="Screenshot 2024-01-13 at 10 48 10 AM" width="1136" src="https://private-user-images.githubusercontent.com/37256050/296504277-8192f133-e0d2-4f08-a17c-5d78f04152cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxNjU2ODUsIm5iZiI6MTcwNTE2NTM4NSwicGF0aCI6Ii8zNzI1NjA1MC8yOTY1MDQyNzctODE5MmYxMzMtZTBkMi00ZjA4LWExN2MtNWQ3OGYwNDE1MmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDE3MDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYTA5NTQ3ZjExZDk3ODg1YjUzZjk1ZDgyM2RkNjliN2E3MGZmZWNkZWI3Y2QzMTVlMjQzNmFhY2I1MDUyNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X983jnPeZ0ufNbij3_6AzNqAu_bmk6ojIxDMm2jit74">
> [Specify 7 Crash Report - 2024-01-13T16_48_26.826Z.txt](https://github.com/specify/specify7/files/13928889/Specify.7.Crash.Report.-.2024-01-13T16_48_26.826Z.txt)
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Create a new `DataObjFormatters` app resource
> 2. Go to Address
> 3. Click on the `Address` format
> 4. See error in toast
> 
> macOS, Arc, `xml-editor`

From https://github.com/specify/specify7/issues/4401#issue-2080386620
