### ISSUE TITLE
`xml-editor`: Add definition is not enabled by default for a new formatter

### ISSUE THREAD

**Issue by realVinayak** [specify/specify7#3565]
**Describe the bug**
When making a new formatter, the 'Add definition' is not enabled by default. It suggests that 'Condition Field' needs to mapped. However, 'Condition Field' can be temporarily mapped, and 'Add definition' is then enabled. Then, fields can be added, and then 'Condition Field' can be unmapped. Since no error occurs, it looks like 'Condition Field' is allowed to be unmapped (which I think is the current behavior)

**To Reproduce**
1. Go to the visual editor for defining Formatters.
2. Click on 'Collecting Trip Attribute' table for as an example.
3. Add definition is disabled.
4. Add a Condition field temporarily, add fields and then remove the Condition field. This should be allowed be default.

**Expected behavior**
Add definition should be enabled by default, and not require a Condition field definition.

![image](https://github.com/specify/specify7/assets/61122018/f9f1d78e-39b4-4eb8-bbe9-3fc057265313)

**Comment by CarolineDenis** [comment]
In the code we added 

`const hasCondition = formatter.definition.conditionField !== undefined;`

and we disable the button in case hasCondition is false. 

`<Button.Success
            disabled={!hasCondition}
            title={
              hasCondition ? undefined : resourcesText.addConditionFieldFirst()
            }
            onClick={(): void =>
              handleChange([
                ...formatter.definition.fields,
                {
                  value: undefined,
                  fields: [],
                },
              ])
            }
          >
            {resourcesText.addDefinition()}
          </Button.Success>`

I am guessing we have done that for a reason. @maxxxxxdlp can you share your reflexion behind this? Can we enable the button 'addDefinition' without field? 

(If a field is not selected, the title of the button is 'Add condition field first' which shows the need of it...)

**Comment by maxxxxxdlp** [comment]
I might have made a mistake in the code. My intention was to disable the button if you already have 1 or more definition, but no condition field yet (i.e force the user to specify the condition field before adding 2nd definition)
