### ISSUE TITLE
`xml-editor`: Changes are not synced if Condition field is unmapped in formatters

### ISSUE THREAD

**Issue by realVinayak** [specify/specify7#3566]
**Describe the bug**
If there is a definition for formatter with switch fields with condition field unmapped, then it looks like changes are not synced to XML if condition field is unmapped and then saved.

**To Reproduce**
1. Go to visual editor of formatters, and choose any formatter. If there is no Condition field, map a condition field and make multiple definitions.
2. Click on save and record the XML generated.
3. Unmap the Condition field, and every definition should disappear (as desired)
4. Click on save, and the record the XML again. The changes are not reflected in the XML. Additionally, the frontend seems to remember that Condition field is unmapped (and thus it does not reflect the actual XML, where Condition field is still mapped.).

**Expected behavior**
The changes should be synced.

**Screenshots**
The first two pics show the visual and xml representation of formatter before the condition field is unmapped.
![before unmapping condition field visual](https://github.com/specify/specify7/assets/61122018/5023f110-7184-4ecd-9ceb-45c307cbc81a)
![before unmapping Condition field](https://github.com/specify/specify7/assets/61122018/e55d3e11-dda2-4a53-83b1-048e70a7ff95)
</br>
</br>
The second two pics show the visual and xml representation of formatter after the condition field is unmapped. Notice the discrepancy between XML and visual editor
![after unmapping condition field visual](https://github.com/specify/specify7/assets/61122018/b448e933-d9e1-46fd-93c0-402c1cce3fa4)
![after unmapping condition field](https://github.com/specify/specify7/assets/61122018/f7c4b9b4-1ec9-485d-8b0c-1104d59535e0)

**Comment by CarolineDenis** [comment]
Fixed with changes made in https://github.com/specify/specify7/pull/4114

**Comment by maxxxxxdlp** [comment]
At least part of this behavior might have been intentional.

I remember thinking if user had definitions, and they removed the condition field, the definitions should still be preserved in the XML just in case they would set back the condition field and would want to see old definitions again (we do this in several places - for example in the date picker on the form, if you change type from "full date", to "year", and then back, the month and day are preserved, even though it doesn't make sense for month and date to be there for the "year" type)

If that seems more confusing than helpful, than feel free to change

**Comment by pashiav** [comment]
Reproduced on branch `issue-3565`. 

**Selected Conditional Formatter and saved:**
visual:
![issue-3566-vis-b](https://github.com/specify/specify7/assets/118556884/cd91dc2c-458e-4222-82f6-50f343ca3ea0)
xml:
![issue-3566-xml-bf](https://github.com/specify/specify7/assets/118556884/d179db8e-5053-4cc8-ab01-16e50cce3fd1)


**After deselecting conditional formatter and saving:**
![issue-3566-after](https://github.com/specify/specify7/assets/118556884/98fc3f80-3285-4fd1-823f-0e5c38463bdf)

Changes are not synced.
