### ISSUE TITLE
Map batches of records.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#357]
E.g. Query results and record sets.

**Comment by timo11** [comment]
This can be tested for query results. The query builder now has a 'Create KML' button. It behaves the same way as Create CSV. When you download the KML file you will have load it into Google Earth, or any other app that processes KML files. I guess dbl-clicking the download will open your system's default app for KML files. For Create KML to work, queries must include latitude1 and longitude1 OR lat1text and long1Text. Individual records that don't have geocoords are not added to the KML file. In Google Earth, clicking on a KML marker pops up a window displaying the values of the fields in the query with 'Show In Results' on. The last row in the window is a url that should display the source record in Sp7.

**Comment by timo11** [comment]
For exporting to KML, queries must contain latitude1 and longitude1. Lat1Text and Long1Text won't work.

**Comment by timo11** [comment]
If latitude2, longitude2 and LatLongType are included in the query results, lines and rectangles will be included in the kml file. They will display with plain white lines, with a placemarker at lat1/lng1. 
If lat2 and lng2 are included but not LatLongType, a Line element will be created.

**Comment by yvonneekanim** [comment]
I limited my query to the first 100 catalog numbers but the results show over 400 records

**Comment by yvonneekanim** [comment]
Tested in Sam Noble, kml returns correct number of records on google earth.
