### ISSUE TITLE
404 In Trees If You Don't Interact With One After Messing With Another 

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3578]
**Describe the bug**
Let's say I was in Taxonomy or Geography and added some children or anything really. The top buttons become active and interactive. If you go to another tree, the buttons are still interactive despite not selecting anything in this new tree. Using them will produce 404 Errors.

**To Reproduce**
1. Go to Geography and interact with the tree
2. Go to another tree, like Storage
3. Click on any buttons on top

**Expected behavior**
Buttons should be deactivated 

**Screen Recording**

https://github.com/specify/specify7/assets/53784701/090f37f5-0a37-4e62-9190-073ae2c5ee83

**Desktop:**
 - OS: Mac OSx Ventura
 - Browser: Chrome
 - Specify 7 Version: 7.8.11 and 7.8.12

**Database Name:** Any

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-13-release-announcement/1230/1
