### ISSUE TITLE
Query Builder export to KML ignores selected rows

### ISSUE THREAD

**Issue by melton-jason** [specify/specify7#3589]
Similar to #2348, but with the `Export to KML` option.

Now, #2348 has been fixed in #3476, but there is still no way for the Query Builder to export only selected rows to KML. 

(As a reminder, the Export to KML button is only visible when there is coordinate data, like Latitude1 and Longitude1, in the Query)

**Comment by emenslin** [comment]
Can recreate in edge (7.9.6)
