### ISSUE TITLE
Auto-populate rank field when adding new tree node

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3597]
**Describe the solution you'd like**
Auto-fill the next lowest rank when adding a child node to a tree. This should be in the required rank field 

**Describe alternatives you've considered**
Could allow the option to choose from the pick list while still auto-populating with the next most logical option
Could add auto-population as a boolean in preferences
Could allow for user override settings for certain ranks in preferences

**Additional context**
Was available in 6 and is being requested

**Comment by melton-jason** [comment]
I agree we can have the Rank field autopopulate when there is only one possible rank. 

However, ranks can be non-enforceable, meaning there may be more than one possible rank for a tree node. 

> Could allow the option to choose from the pick list while still auto-populating with the next most logical option

If there is more than one possible rank, what would be the 'most logical rank'? Would it be the closet rank to the parent? The furthest?

**Comment by maxxxxxdlp** [comment]
I'm pretty sure we had the code that automatically selected the next enforced rank from the pick list - I don't think we removed that so it likely just stopped working. @melton-jason could you research a bit?

**Comment by maxxxxxdlp** [comment]
Ah, yes, in TreeLevelPickList.tsx there is this code:

```
 defaultValue={props.defaultValue ?? items?.slice(-1)[0]?.value}
```

But apparently that doesn't work if this issue was opened. @melton-jason could you take a look?
