### ISSUE TITLE
Split Tree View

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3600]
> It would be lovely to see the split tree view that was present in Specify 6 in Specify 7. The was where you could have two windows open, stacked one above the other on the same screen and scroll to different parts of the tree. This would be particularly useful for synonymy and merging nodes in our taxon tree which is rather large!

**Requested By:** Sally King on [Speciforum](https://discourse.specifysoftware.org/t/split-tree-view-in-specify-7/1197)

- _Liked by Liath Appleton at UT Austin_

**Comment by tlammer** [comment]
You could also drag a tree node from one of the screens to the other to indicate to where you wanted to merge/move/synonymize the node.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/split-tree-view-in-specify-7/1197/2
