### ISSUE TITLE
Do Not Show Skeltons if Collection Has No Attachments

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3606]
**Is your feature request related to a problem? Please describe.**
When a collection/institute has no attachments. You can change how the "Attachments" are sorted. This causes the skeleton loaders to flash for a moment. 

**Describe the solution you'd like**
It would be great if this didn't happen. Since there's nothing to sort.
Or...
We could disable the picker if they are no attachments
Or...
You decide. ¯\_(ツ)_/¯
 
**Beautiful Pictures (Screen shoots and recordings)**

https://github.com/specify/specify7/assets/53784701/b997fcc3-76f9-45b5-bf71-22fc7def8e6c

**Reported By**
@carlosmbe from specify collections consortium

**Comment by grantfitzsimmons** [comment]
As mentioned in the PR (https://github.com/specify/specify7/pull/3712) that worked to solve this, it is probably not worth the potential issues to solve:

@maxxxxxdlp 
>I don't think this fix is worth the disadvantages it brings (for databases with a lot of collection object attachments, it could take a while to fetch the count)

There may be a better fix, but this is a non-issue in my opinion. Please reopen if a user requests this in the future 🙏
