### ISSUE TITLE
Make Date Format `Month/Year` Place Holder More Consistent With Other Formats

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3607]
**Is your feature request related to a problem? Please describe.**
It's a bit strange that we have the other date formats(Full Date and Year) have letters as their place holder, while Month/Year just has Dashes.

**Describe the solution you'd like**
Make the place holder `MONTH YEAR` or `mmmmmm yyyy` You decide
OR....
You could just make it be the current day with a different format. IE 2023-06-09 and 2023 and June 2023
OR....
You decide, I'm just a tester throwing ideas ¯\_(ツ)_/¯

**Beautiful Pictures**

<img width="1201" alt="Screenshot 2023-06-09 at 12 38 09 PM" src="https://github.com/specify/specify7/assets/53784701/51e4f4e9-2d7f-4129-8df8-00db3de0de00">
<img width="1148" alt="Screenshot 2023-06-09 at 12 38 52 PM" src="https://github.com/specify/specify7/assets/53784701/18bd5c40-7d72-4d0e-804c-3ce181a0420e">
<img width="1154" alt="Screenshot 2023-06-09 at 12 39 05 PM" src="https://github.com/specify/specify7/assets/53784701/06c5d811-7fdc-4d63-a218-c66da75309f4">

**Reported By**
@carlosmbe from specify collections consortium

**Comment by maxxxxxdlp** [comment]
> You could just make it be the current day with a different format. IE 2023-06-09 and 2023 and June 2023

The date entered in the field won't always be current date, so having selector show preview of current date might look confusing.

That might look something like this:

```
the first box below    the second box below
| June 2023       |  | August 2013        |

```

Versus current:

```
the first box below    the second box below
| Mon / Year       |  | August 2013        |

```

**Comment by maxxxxxdlp** [comment]
I believe the current behavior matches that of sp6, and is what people are used to, though that doesn't mean we can't improve it.

Also, `Mon / Year` is shorter that `mmmmmm yyyy` or `MONTH YEAR` or many other variants, and width is very important as the date picker is already way too wide

**Comment by CarolineDenis** [comment]
@grantfitzsimmons , can you check the behavior on xml-editor and let me know if this needs to be kept open or not?

**Comment by grantfitzsimmons** [comment]
Nothing has changed on `xml-editor` that would affect this. In my opinion, this could be closed, and showing the current date (like @maxpatiiuk said) would be misleading to the user. 

`Mon / Year` makes sense to me and to our users from what I understand. Even that often takes up too much space. I would like to see the picker use a more appropriate amount of space, but this issue is not a pain point.

<img width="295" alt="image" src="https://github.com/specify/specify7/assets/37256050/35a67dee-d825-4252-a421-7ba3b1c49394">
