### ISSUE TITLE
Auto fill cataloger field.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#361]
Cataloger fills in automatically with the agent associated with whichever user is logged in where the data is being entered. I'm not positive why it works sometimes and sometimes not.

**Comment by maxxxxxdlp** [comment]
This does not seem to be fixed
<img width="416" alt="Screen Shot 2020-03-03 at 10 03 58 AM" src="https://user-images.githubusercontent.com/40512816/75794361-4ece9500-5d36-11ea-9dae-dcbb1a9b7fea.png">

**Comment by benanhalt** [comment]
The fix hasn't been merged yet.

**Comment by maxxxxxdlp** [comment]
I see. I guess I am not able to test any of these things on the server until after the release?

**Comment by benanhalt** [comment]
The issues in the "Finished on Branch" zenhub board aren't available for testing, yet. We haven't decided whether to include them in the release.

**Comment by benanhalt** [comment]
Ready for testing in the "default-values" build.
