### ISSUE TITLE
Support auto open of CE, Prep, or COA tables.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#362]
In Specify 6 you can set a preference in local prefs to automatically activate either CE, Prep, or COA tables (this is rarely used).

**Comment by benanhalt** [comment]
I couldn't find any pref for collecting event but if collecting event is embedded it will already auto create one.

**Comment by benanhalt** [comment]
Ready for testing in the "default-values" build.

**Comment by yvonneekanim** [comment]
@benanhalt can you provide the prefs?

**Comment by benanhalt** [comment]
They can be turned on and off in Specify 6 by going to System -> System Setup -> Configuration and finding Activate Subforms in the panel on the left.

![image](https://user-images.githubusercontent.com/287254/101685922-f8f9ec80-3a2d-11eb-9e10-368d0d5118df.png)
