### ISSUE TITLE
Upon first run of Specify 7 with a Specify 6 database, an error occurrs

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3626]
```
{"exception": "ProgrammingError", "message": "1146", "data": "Table 'paleo.spuserpolicy' doesn't exist",
```

Migrations are never run the first time you run `just-specify7` with a new Specify 6 database. We need to solve this so that users do not need to follow this guide each time they start using Specify 7– it gives a bad impression.

https://discourse.specifysoftware.org/t/upgrading-to-specify-7-7-http-500-error/733

**Comment by grantfitzsimmons** [comment]
Oh, of course. 

https://github.com/specify/specify7/#make-django_migrations

To run the `django_migrations`, the `MASTER_USER` credentials must be root temporarily. That is the real issue here.

> Applies Specify schema changes to the database named in the settings. This step may fail if the master user configured in the settings does not have DDL privileges. Changing the MASTER_NAME and MASTER_PASSWORD settings to the MySQL root user will allow the changes to be applied. Afterward, the master user settings can be restored.

We need to include instructions in the `docker-compose.yml` file so that it's not so confusing.

**Comment by maxxxxxdlp** [comment]
Ben tried to fix some of these things in https://github.com/specify/specify7/pull/1037
