### ISSUE TITLE
WorkBench errors not reported after validation cannot be navigated between

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3635]
<img width="1800" alt="WorkBench errors not showing in the interface" src="https://github.com/specify/specify7/assets/37256050/e0ca298b-9edf-413c-b503-f6d0330ea1c8">

After validating, I see no indication that there were errors and have to find them myself manually. See that there is no error in the navigation options at the bottom. 

I am using `v7.8.12` without Internet on a brand-new Paleo database.

**Comment by grantfitzsimmons** [comment]
<img width="1876" alt="image" src="https://github.com/specify/specify7/assets/37256050/4702843a-6416-4e63-a2a5-b36116071cf1">

@specify/developers this is extraordinarily urgent

**Comment by melton-jason** [comment]
This bug does not seem to prevent the functionality of the Error Cells button, just the number of affected cells displayed in the button (and other navigation buttons).
The below screen recording is on `v7.8.12`. 

https://github.com/specify/specify7/assets/64045831/1dfe7092-f970-4083-8a60-746e922debb5

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-13-release-announcement/1230/1
