### ISSUE TITLE
Taxon query crashes with `object has no attribute 'determinationtreedef'`

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3637]
<img width="1798" alt="image" src="https://github.com/specify/specify7/assets/37256050/a379c9a4-3b4e-4cc2-b313-d7b7b7a718c6">

**Steps to Recreate:**
1. Create a new Collection Object query
2. Go to Determination --> Preferred Determination
3. Double-click on any rank to add the (formatted) record to the query
4. See crash once run

https://github.com/specify/specify7/assets/37256050/8064f5cc-cb7c-486b-b383-adcb3e101be5

```
AttributeError
'Discipline' object has no attribute 'determinationtreedef'
Content
"None"
```

[Specify 7 Crash Report - 2023-06-17T14_45_32.802Z.txt](https://github.com/specify/specify7/files/11779269/Specify.7.Crash.Report.-.2023-06-17T14_45_32.802Z.txt)

**Version:**
Specify 7.8.11
Chrome on macOS

**Comment by maxxxxxdlp** [comment]
Not the first github issue for this bug, but can't find the other ones

**Comment by grantfitzsimmons** [comment]
[Specify 7 Crash Report - 2024-06-13T17_22_54.848Z.txt](https://github.com/user-attachments/files/15826232/Specify.7.Crash.Report.-.2024-06-13T17_22_54.848Z.txt)

Recreated this today in `v7.8.9` on NMSU's database. Not sure if this can be recreated with a new version, so I'm going to reach out.

**Comment by grantfitzsimmons** [comment]
Can't recreate this. Double-clicking on a rank now adds the "Full Name" automatically instead of "(formatted)".

**Comment by melton-jason** [comment]
> Can't recreate this. Double-clicking on a rank now adds the "Full Name" automatically instead of "(formatted)".

This was added as of `v7.9.2` in #3026
