### ISSUE TITLE
Change default forms to hide portions of agents form depending on agent type using conditional forms

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#364]
Eg only show members for groups.

Also are the subform labels correct?

**Comment by maxxxxxdlp** [comment]
Also, the same agent can be made a member multiple times
<img width="858" alt="Screen Shot 2020-06-29 at 5 33 58 PM" src="https://user-images.githubusercontent.com/40512816/86018995-aaaae100-b9eb-11ea-9792-d6694b4d7ad0.png">

**Comment by tlammer** [comment]
requested again by LSUMNS Ichthyology

**Comment by maxxxxxdlp** [comment]
Same applies to the PickList table (some fields should be hidden depending on the pick list type)

From @grantfitzsimmons:

> ![image](https://user-images.githubusercontent.com/37256050/179046120-d2bb949c-3c74-4e54-960c-210df44f1466.png)
> 
> When viewing the RefrenceWorkType pick list, the Table Name and Field Name are displaying as invalid.
> 
> db: `newmexico_july22` user: spadmin
> 
> https://a11y-2-2.test.specifysystems.org/specify/view/picklist/14/

**Comment by maxxxxxdlp** [comment]
This is now possible thanks to https://github.com/specify/specify7/issues/2860

Just have to change the default form definitions

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp Should we rename this issue or open a new one?

**Comment by maxxxxxdlp** [comment]
We already have an issue for conditional rendering. The only thing left here is to edit the default form after that is merged in. Feel free to rename this issue (though current name is fine by me)

**Comment by grantfitzsimmons** [comment]
Fixed in https://github.com/specify/specify7/commit/f60a4051581d47fa2e6a1d3261091ba420aaaa08
