### ISSUE TITLE
Conditional forms are not working

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3641]
This could be a case of misconfiguration, but I am trying to create an example geology form using conditional forms. See the snippet of XML below (this is on `localhost`, so I apologize for not having a URL):

https://github.com/specify/specify7/assets/37256050/71abc9a1-7c28-4153-8779-68fa730faa07

```xml
                <row>
                <cell type="panel" coldef="100px,2px,76px" colspan="6">
                  <rows>
                    <!-- This view definition will be displayed in Specify 6, or if all other conditions don't match -->
                    <row>
                      <cell type="label" label="Default view definition." />
                    </row>
                  </rows>
                  <rows condition="text1=1">
                    <row>
                      <cell type="label" label="You chose 1!" />
                    </row>
                  </rows>
                  <rows condition="text1=Mineral" coldef="13px,14px,15px">
                    <row>
                      <cell type="label" label="You chose Mineral!" />
                    </row>
                  </rows>
                </cell>
                </row>
```

I have a pick list of options in `text1` on the Collection Object, with a Title of `Mineral` and Value of `1`. I wanted to see which value would be used by the conditional form system, but neither have any effect. 

**Version:**
`v7.8.12`, macOS, Chrome

**Here's the full file:** [Geology Views.xml.zip](https://github.com/specify/specify7/files/11779687/Geology.Views.xml.zip)

**Comment by grantfitzsimmons** [comment]
_I followed the form system documentation as closely as I could!_

**Comment by CarolineDenis** [comment]
https://github.com/specify/specify7/assets/108160931/66af12bf-7731-4ecb-8f34-a2a52f0f28f7

made today with KuFish db on local branch xml-editor

**Comment by CarolineDenis** [comment]
`<viewdef>
	<desc>The Collection Object form.</desc>
	<enableRules/>
	<columnDef>100px,2px,195px,5px,86px,2px,210px,5px,74px,2px,146px,15px,p:g</columnDef>
	<columnDef os="lnx">115px,2px,195px,5px,125px,2px,210px,5px,125px,2px,131px,15px,p:g</columnDef>
	<columnDef os="mac">130px,2px,215px,5px,138px,2px,260px,5px,138px,2px,155px,15px,p:g</columnDef>
	<columnDef os="exp">p,2px,min(p;220px),5px:g,p,2px,p,5px:g,p,2px,200px,p,p:g</columnDef>
	<rowDef auto="true" cell="p" sep="2px"/>
	<rows>
		<row>
			<cell type="label" labelfor="1"/>
			<cell type="field" id="1" name="catalogNumber" uitype="formattedtext"/>
			<cell type="label" labelfor="3"/>
			<cell type="field" id="3" name="accession" uitype="querycbx" initialize="name=AccessionCO;title=AccessionCO" isrequired="false"/>
			<cell type="label" labelfor="4"/>
			<cell type="field" id="4" name="fieldNumber" uitype="text" readonly="false"/>
		</row>
		<row>
			<cell type="panel" coldef="100px">
				<rows>
					<row>
						<cell type="label" label="This will be displayed in Specify 6"/>
					</row>
				</rows>
				<rows condition="always">
					<row>
						<cell type="label" label="This will be displayed in Specify 7"/>
					</row>
				</rows>
			</cell>
		</row>
		<row>
			<cell type="panel" coldef="100px,2px,76px" colspan="6">
				<rows>
					<row>
						<cell type="label" labelfor="fieldNumber" label="testCondition"/>
						<cell type="field" id="fieldNumber" name="fieldNumber" uitype="text" readonly="false"/>
					</row>
				</rows>
				<rows condition="fieldNumber=2">
					<row>
						<cell type="label" label="Field Number is 2!"/>
					</row>
				</rows>
				
			</cell>
		</row>
		<row>
			<cell type="panel" coldef="100px,2px,76px" colspan="6">
				<rows>
					<row>
						<cell type="label" labelfor="fieldNumber" label="Is there before cat # cdt"/>
					</row>
				</rows>
				<rows condition="catalogNumber=000111111">
					<row>
						<cell type="label" label="cat num is 11-11-111"/>
					</row>
				</rows>
			</cell>
		</row>
	</rows>
</viewdef>`

**Comment by grantfitzsimmons** [comment]
Safe to close this issue then?
