### ISSUE TITLE
Second Progress Bar After Running Query for Tree

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3643]
**Describe the bug**
A second loading bar sometimes appears at the bottom of query results. Still investigating the cause but at the bare minimum a query need to be run from a Tree Node.

https://github.com/specify/specify7/assets/53784701/33a33383-e69f-4033-a722-c069d01c7b42

**Comment by maxxxxxdlp** [comment]
This is not caused by tree query but by the fact that query returned fewer results than fits on the screen, thus the logic for automatically fetching more query results when you scrolled to the bottom of the query results went haywire (it breaks quite often - quite fragile :sigh:)

**Comment by emenslin** [comment]
Fixed
