### ISSUE TITLE
Revisit Lat Long UI

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#365]

**Comment by maxxxxxdlp** [comment]
Keyboard navigation is broken for the Lat Long UI on the Locality form
(enter the value for Lat1, press Tab, the focus is lost)

**Comment by maxxxxxdlp** [comment]
a11y issues were fixed in f604ae6d
@benanhalt Is there anything else you wanted to change about LatLongUI

**Comment by grantfitzsimmons** [comment]
This fix is not live on my end (a11y branch on test server). I am able to recreate the focus being lost after entering data into Lat1 and pressing tab. Pressing tab once again navigates to Coord Type, then again back to Lat1, and then Lat2.
