### ISSUE TITLE
Completely Unmapped Query can produce csv

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3650]
**Describe the bug**
Title.
It's a bit strange to be honest.

**To Reproduce**
1. Go to Query Builder
2. Create a query with unmapped values
3. Run Query
4. Create CSV
5. See error

**Expected behavior**
Nothing made.

**Screenshots**

<img width="1621" alt="Screenshot 2023-06-21 at 3 25 49 PM" src="https://github.com/specify/specify7/assets/53784701/d920babc-96f6-4e19-85e1-7c644b348302">

https://github.com/specify/specify7/assets/53784701/17cb84f3-b068-4062-97bb-240ecf2aec87

**Desktop:**
 - OS: Mac OS
 - Browser: Chrome
 - Specify 7 Version: 7.9, Probably present in 7.8.12
 
 Could share a solution with https://github.com/specify/specify7/issues/3649

**Comment by emenslin** [comment]
Fixed, need a mapped field to create csv
