### ISSUE TITLE
Add the ability to hide QCBX buttons

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3657]
>Is it possible to selectively remove the ‘+’ function to add a new agent/taxon/geography etc from the form. This is for users that have full access otherwise. We found that users tend to click on the ‘+’ symbol when they want to select something from a QCBX, rather than use the type-ahead or search functionality. Of course, this partly a training exercise, but we were wondering if we can just remove that option from the form, so when they actually want to add something new they have to go via the tree or the relevant Data Entry form.
>
>![image](https://github.com/specify/specify7/assets/37256050/36b95579-990d-4287-9bb6-a224713aaace)

This request is essentially asking for another attribute so that the `+` button could be hidden on the form.

Per the [form system documentation](https://github.com/specify/specify7/wiki/Form-System#querycbx), there is already an attribute named `cloneBtn` that can be set to true or false. Adding an attribute named `addBtn` that had a default of true and could be made false would solve this issue.

> - `cloneBtn` ('true' | 'false', optional, default: 'false')

**Requested By:** CSIRO on [Asana](https://app.asana.com/0/1201972579963460/1204830887216582/f)

**Comment by maxxxxxdlp** [comment]
Sp7 supports the `initialize="cloneBtn=true"` attribute only
Sp6 supports more: `searchBtn, cloneBrn, editBtn, newBtn`.
