### ISSUE TITLE
More Consistent Query Builder Overlay in Stats Page

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3662]
It'd be awesome if we had one consistent size. Like maybe large or small. Perhaps it's a taste thing but the different sizes can be quite jarring.

<img width="1792" alt="Screenshot 2023-06-22 at 2 55 45 PM" src="https://github.com/specify/specify7/assets/53784701/05538a56-2aab-4b5b-ac91-61c1473c7601">
<img width="1792" alt="Screenshot 2023-06-22 at 2 56 05 PM" src="https://github.com/specify/specify7/assets/53784701/87551503-236f-451b-8e41-0064513b19f7">
<img width="1792" alt="Screenshot 2023-06-22 at 2 55 55 PM" src="https://github.com/specify/specify7/assets/53784701/cd818c94-7a25-4cc6-97a7-81157fbd6eff">
<img width="1791" alt="Screenshot 2023-06-22 at 2 56 28 PM" src="https://github.com/specify/specify7/assets/53784701/6040fbba-22c1-4716-8f6f-edcd6fdfd4f2">

**Comment by maxxxxxdlp** [comment]
@realVinayak take a look at the `QueryBuilderSearch` component - it fixes this issue by adding a class name, which in turn mandates a certain min width

**Comment by grantfitzsimmons** [comment]
We will use @maxxxxxdlp's proposed solution
