### ISSUE TITLE
Broken Query Breaks Stats Page

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3666]
**Describe the bug**
Title.
After adding a Query that has an error. You're left in a soft loop. As whenever you open Stats Page it crashes.

You can observe it on NHMD as `PetrifiedRoadKill` on Amber
**To Reproduce**
1. Save a broken query or make one  
2. Go to stats page, click on edit and add the broken query
3. See error

**Expected behavior**
Stat should have `Error` not throw an Error Screen. It's a soft block right now 

**Screen Recording**

https://github.com/specify/specify7/assets/53784701/fab06815-8025-43e8-ae02-f8010844221f

<img width="1615" alt="Screenshot 2023-06-22 at 4 51 40 PM" src="https://github.com/specify/specify7/assets/53784701/400cba09-a19f-40b0-a04b-89c928cb32d8">

**Desktop:**
 - OS: Mac OS
 - Browser: Chrome
 - Specify 7 Version: 7.9

**Comment by realVinayak** [comment]
Good for testing again

**Comment by carlosmbe** [comment]
Nice work. It works.

https://github.com/specify/specify7/assets/53784701/6abd10fb-0e0d-465f-8263-586b4ab9cae8
