### ISSUE TITLE
Test picklists with huge number of items.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#367]
We want to know if there is any problem with super big picklists in Sp7. I guess it could be tested with progressively larger lists. Say from 100 items up to 100,000 or so, just to see what happens. Any problems should be entered as new issues.

**Comment by garrettgirard** [comment]
The Florida VP db has a little over 1000 items in one of their Locality picklists. There didn't seem to be any issue with this. Do you want me to test up to 100,000 items? I'm not sure how easy it will be to get add that many items to a picklist is my only concern.

**Comment by garrettgirard** [comment]
Theresa said that the user who had an issue with this in the past (Specify 6) was in fact Florida. So as it works fine with their biggest picklist I could find, this one is good to go.
