### ISSUE TITLE
XML Editing does not preserve all comments

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#3677]
If I put a comment in here (see line 3):

<img width="756" alt="Screenshot 2023-04-26 at 10 03 00" src="https://github.com/specify/specify7/assets/40512816/09e13b7c-0741-43f7-8e46-30f4fea89323">

It won't be preserved after saving changes.

Not a big deal in this case, but I don't know the extent of the bug thus should be investigated and fixed before XML editing release

**Comment by CarolineDenis** [comment]
I cannot reproduce. 
@specify/dev-testing @specify/ux-testing can you?

**Comment by CarolineDenis** [comment]
NOTES: 
- comments made inside <rows/> are preserved, the other not. 
- would it be because the xmlChildren() look for 'columnDef' 'desc' 'rowDef' and 'rows' than sync but get rid of the rest?

**Comment by maxpatiiuk** [comment]
> should we create something like a tag `<comments/>`

no,no,no. some of the reasons:
- XML already has the syntax for comments
- users are already using that syntax for comments (thus if this bug is not fixed, those comments would be lost)
- users already know that syntax for comments (they don't need to be re-educated or look in docs)

> would it be because the xmlChildren() 

it only looks for some tags, but the Syncer is designed not to throw away anything it doesn't recognize/care about - comments should not have been touched
