### ISSUE TITLE
Some XML Editor errors appear on a wrong line

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#3678]
This error is supposed to be shown down below next to one of the `class="..."` attributes, not on top of the file:

<img width="999" alt="Screenshot 2023-04-25 at 12 17 48" src="https://github.com/specify/specify7/assets/40512816/0ba18cb7-631d-418e-8674-ec2a33028b6f">

The code for positioning the errors does this when it fails to find the place where to put the error message.

Note, this error may be connected to the presence of `<?xml  ...` in this file (though, it should have been able to handle that)

Note, I have tests for error placement, so if you fix this bug, remember to add the test case to prevent it in the future

**Comment by CarolineDenis** [comment]
I cannot reproduce

**Comment by maxxxxxdlp** [comment]
yeah, would have been more helpful if I have provided the file that triggers the error.
instead, best we can do is try out a file that contains the `<?xml` declaration like in the screenshot

**Comment by CarolineDenis** [comment]
@carlosmbe , @bronwyncombs can you reproduce? If yes can you add details here please?

**Comment by realVinayak** [comment]
Can replicate in this xml: 
[faulty line.txt](https://github.com/specify/specify7/files/13341014/faulty.line.txt)
![image](https://github.com/specify/specify7/assets/61122018/290ae2fe-dc7e-4939-8172-b2574617a65e)
The error is at line 236 (and it is not included in the yellow highlighted region)
![image](https://github.com/specify/specify7/assets/61122018/05bc4597-f6d3-4b24-9fe2-0f5cd9496a9a)

**Comment by CarolineDenis** [comment]
NOTES: 
We define the line on which the error will be display in the linter here: 
```javascript
const declaration = xml.startsWith('<?') ? xml.indexOf('>') + 1 : 0;
```
https://github.com/specify/specify7/blob/7d2754354f6af86a807301506bf4719a906caf0f/specifyweb/frontend/js_src/lib/components/Syncer/findNodePosition.ts#L11C1-L11C1
To define the value of 'declaration' we check if the xml string begins with '<?' BUT in the case of the formatter, the xml starts with <formatters> therefore the declaration is = to 0. Which causes our issue

**Comment by maxxxxxdlp** [comment]
While it's possible that there is a bug here, this line is here intentionally.
When it's not clear what a certain line is doing, try to play around with a simplified example.
For example, see this small code sample:

```ts
xml = `<?xml version="1.0" encoding="UTF-8"?>
<formatters>...</formatters>`;
declaration = xml.startsWith('<?') ? xml.indexOf('>') + 1 : 0;
trimmedXml = xml.slice(declaration)
```

do you see what it is doing?
all it says is if the XML string starts with the [XML declration](https://www.tutorialspoint.com/xml/xml_declaration.htm), then strip the declaration - that's it!
(by slicing away the part of the string that is before the `declaration` number)
and if it does not start with the declaration, then `declaration` is set to 0, which essentially doesn't strip anything!

does this logic make sense?

if it clarifies things for you, feel free to rename the `declaration` variable to `declarationEndPosition` or something like that

> Which causes our issue

Do you know how is this causing the issue? were you able to see in the debugger that this is the cause?
This line looks good to me.
Note that this variable is used in two more places:
https://github.com/specify/specify7/blob/7d2754354f6af86a807301506bf4719a906caf0f/specifyweb/frontend/js_src/lib/components/Syncer/findNodePosition.ts#L13-L16
do those look good?

**Comment by maxxxxxdlp** [comment]
Note that we also have good test coverage for this function - https://github.com/specify/specify7/blob/7d2754354f6af86a807301506bf4719a906caf0f/specifyweb/frontend/js_src/lib/components/Syncer/__tests__/findNodePosition.test.ts#L6-L69

The test cases include both XML strings with XML declaration and not

Since the bug is still occurring, our test coverage is not good enough for this function - when you find the cause of the bug, make a test case for it, see that the test case reproduces the bug, fix the bug, and see that the test case passes - this will give you assurance that you actually found the cause, that you fixed it, and that this bug would not happen again in the future (since now you have a test case)

**Comment by CarolineDenis** [comment]
@realVinayak, which version did you try this on? 
I cannot reproduce the issue on the last version of xml-editor 
![Screenshot 2023-11-15 at 9 03 51 AM](https://github.com/specify/specify7/assets/108160931/27d567b7-c2a2-4537-8bbd-b2b2f735d53d)
![Screenshot 2023-11-15 at 9 04 05 AM](https://github.com/specify/specify7/assets/108160931/85cdd44b-e433-42e7-a382-7ff3328d329a)

**Comment by CarolineDenis** [comment]
@maxxxxxdlp, yes everything makes sense and seems to be working fine to me

**Comment by realVinayak** [comment]
@CarolineDenis can still replicate this on the latest version of xml-editor. I attached the formatter xml I used to replicate in here (https://github.com/specify/specify7/issues/3678#issuecomment-1809061035)

Here is it again: 
[faulty line.txt](https://github.com/specify/specify7/files/13429680/faulty.line.txt)

Paste the contents into record formatters app resource and see that the error gets reported on the wrong line

**Comment by CarolineDenis** [comment]
NOTES: 
the issue is somewhere in findChild(), didn't solve it yet
