### ISSUE TITLE
Add a Web Link URL preview

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#3679]
Web Link previews render web link elements, which are clickable and can open the webpage:

<img width="999" alt="Screenshot 2023-04-25 at 11 57 30" src="https://github.com/specify/specify7/assets/40512816/a9cdd845-eefe-4c47-b56c-f1514ef125b7">

However, it would be more user-friendly if these previews also showed the raw link in a text file to the side of the weblink

**Comment by CarolineDenis** [comment]
copy of: https://github.com/specify/specify7/issues/4335
