### ISSUE TITLE
Do formatting and sorting on server side for QueryCBX search function.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#368]
Since sorting is done in the browser (see #329) if the query limit is exceeded, the missing results will occur throughout the list and not just at the end.

**Comment by maxxxxxdlp** [comment]
Looks like this was fixed in April 2017:

https://github.com/specify/specify7/blob/ffbd9f89ccc7aed4852f2770c0e1d535983b8af6/specifyweb/frontend/js_src/lib/querycbx.js#L69
