### ISSUE TITLE
Weird positioning of buttons on narrow screens

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#3681]
The query builder toolbar buttons are arranged into a "holy trinity" on narrower screens

![Screenshot 2023-06-24 at 19 24 47](https://github.com/specify/specify7/assets/40512816/459674d8-8331-4691-82f9-b1455642ac13)

Happend on the xml-editor branch

**Comment by CarolineDenis** [comment]
Is in production too 
![Screenshot 2023-06-30 at 12 56 45 PM](https://github.com/specify/specify7/assets/108160931/4130e25e-7e30-4011-b997-745fc4ab7dd9)

**Comment by CarolineDenis** [comment]
could be justify end: 
![Screenshot 2023-06-30 at 1 06 48 PM](https://github.com/specify/specify7/assets/108160931/bad00e87-155f-4e33-bd25-87c92c03c4bd)

**Comment by CarolineDenis** [comment]
NOTES: 
This happens only in a rare case: 
![Screenshot 2023-06-30 at 1 11 01 PM](https://github.com/specify/specify7/assets/108160931/9177f802-76f7-4319-a027-7ead0d7dbcdb)

**Comment by maxxxxxdlp** [comment]
ok, then maybe not big deal

though I am still not a fun of centering headers - don't think that looks good, but I will defer to others for this

**Comment by CarolineDenis** [comment]
@grantfitzsimmons @melton-jason, do you prefer center, left or right? I personally don't have a strong opinion. I'll go with the majority.

**Comment by grantfitzsimmons** [comment]
I vote right-aligned! 
I am also not a fan of centering headers.

**Comment by melton-jason** [comment]
> NOTES: This happens only in a rare case, 2mm over or 2mm under and we're good ![Screenshot 2023-06-30 at 1 11 01 PM](https://user-images.githubusercontent.com/108160931/250191040-9177f802-76f7-4319-a027-7ead0d7dbcdb.png)

Just based from this picture, I would prefer something like the first option! 
Right align might make more sense to make better use of the space! The left side is probably going to usually be the busiest side!
