### ISSUE TITLE
Opening new query from dialog after sorting in a current query auto-loads Locality fields

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3683]
**Describe the bug**
After querying on a CE with multiple fields and sorting by catalog number at the top (or any of the fields), trying to begin a new query causes a strange error.
Once first query is produced and results sorted, clicking on "new query" when prompted from sidebar causes the New Query page to load with 6 Locality fields/filters already set in place. Attempting to delete one of these fields with the button adds two "NOT MAPPED" fields (similar to WorkBench) and prompts multiple additional errors. 

**To Reproduce**
1. Go to Queries and add new CE query
2. Add these fields: CE Info (formatted), Locality (formatted), and CO > Cat Number (Any)
3. Click "Query"
4. Click one of the headers at the top to sort by this field
5. Now use side bar to open another new query of a different form
6. See error
        - Trying to delete one of the locality fields causes subsequent errors

**Expected behavior**
Should open a blank new query page without Locality fields present

**Screenshots**

**All of the fields in the screenshot automatically appeared after opening the new query**
![CT query Loc error](https://github.com/specify/specify7/assets/135047322/72913a8f-9d54-48bf-93d8-276b431a846f)

**NOT MAPPED fields after clicking delete button**
![CT query error SS](https://github.com/specify/specify7/assets/135047322/5a73975d-7ce8-49f4-aae3-c045d7b83cff)

**Desktop:**
 - OS: Windows 10
 - Browser: Edge
 - Specify 7 Version: 7.9-dev

**Database Name:** 
 UOregonPaleo (6.8.01) 

**Additional context**

**Comment by bronwyncombs** [comment]
[Specify 7 Crash Report - 2023-06-26T14_10_07.815Z.txt](https://github.com/specify/specify7/files/11871161/Specify.7.Crash.Report.-.2023-06-26T14_10_07.815Z.txt)

**Comment by Cazza1965** [comment]
I'm just a workbench user. Where do I create a support ticket? my workbench has stopped working. I sign in write an SOQL query but then it jumps straight back to the signin page

**Comment by bronwyncombs** [comment]
@Cazza1965 You can reach our support team by sending an email to support@specifysoftware.org. Make sure you provide a description of the issue along with your institution name!

**Comment by maxxxxxdlp** [comment]
FYI: this is likely related by query builder automatically adding several locality fields to a query that includes any locality field

those fields are queried, but not visible in the query fields list, unless the user explicitly added them

those fields are used to power the feature for plotting query results on the map
