### ISSUE TITLE
Paleo Context queries for table-linked data throws error

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3686]
**Describe the bug**

When using query builder directly or creating statistic, error for the GeologicTimePeriod Table 

**To Reproduce**
1. Go to Queries
2. Click on "New"
3. Scroll down to 'Paleo Context'
4. Go to select field linked to table (e.g. bio strat, chrono strat)
5. See error

**Expected behavior**

Allow to query on paleo context table information

**Screenshots**
![Paleo context ](https://github.com/specify/specify7/assets/135047322/724cfe70-a4cd-45f0-9352-b23ca55d3ed8)

**Desktop:**
 - OS: Windows 10
 - Browser: Edge
 - Specify 7 Version: 7.9-dev

**Database Name:** UOregonPaleo (6.8.03) _AND_ herb_rbge_3_31_23 (6.8.03)

**Additional context**
Database name or any other context about the problem here.
[Specify 7 Crash Report - 2023-06-26T16_40_16.208Z (1).txt](https://github.com/specify/specify7/files/11871852/Specify.7.Crash.Report.-.2023-06-26T16_40_16.208Z.1.txt)

**Comment by emenslin** [comment]
Fixed
