### ISSUE TITLE
Stats Page UI - Sections have a wrong colour 

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3687]
**Describe the bug**
The **default** colour of `Shared` and `Private` section buttons are brighter than the rest of the buttons in Specify. This is harder to notice in light mode but when in Dark Mode, the contrast is noticeable. 

**To Reproduce**
1. Go to Stats Page
2. Change to dark mode
3. Make sure all buttons are using the default colours

**Expected behavior**
The **Default** colour should match the other buttons.

**Beautiful Picture**
<img width="763" alt="Stats Colors " src="https://github.com/specify/specify7/assets/53784701/0d0be5bf-9dbc-4704-b627-cceb80e6123d">

**Desktop:**
 - OS: Mac
 - Browser: Chrome
 - Specify 7 Version: 7.9

**Comment by grantfitzsimmons** [comment]
Will try to fix, not necessary to fix urgently
