### ISSUE TITLE
v7.8.13 Vertical scrolling in Trees is very glitchy

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3688]
**Describe the bug**

Scrolling vertically on tree page causes intense screen glitch/flash.  
This was not re-creatable on my MacBook using Chrome, though. 

**To Reproduce**
1. Go to 'Trees'
2. Scroll down 
3. See error

**Expected behavior**

**Screenshots**

https://github.com/specify/specify7/assets/135047322/6d97cdbc-c19f-4f89-9ee5-16f522c7870e

**Desktop:**
 - OS:  Windows 10
 - Browser: Edge
 - Specify 7 Version: 7.8.13-prerelease

**Database Name:** coloradopaleo

**Reported By**
Name of your institution

**Additional context**
Database name or any other context about the problem here.

**Comment by maxxxxxdlp** [comment]
Duplicate of #2775
