### ISSUE TITLE
Report attachment.CreatorID error

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#370]
In the New Hampshire Herbarium database, on both branches, attempting to generate the report "New Report" results in the error attached below. It appears to have something to do with the CreatorID field in the attachment table. Otherwise, after checking the report in Specify 6, it appears the report has nothing but a barcode. So it could have something to do with barcodes.

![sp7reporterror](https://cloud.githubusercontent.com/assets/12533028/24868123/bd826fe8-1dd4-11e7-86f1-8fa494e68184.png)

**Comment by benanhalt** [comment]
I think this probabry because the database is 6.6.04.

**Comment by garrettgirard** [comment]
After updating the database, I get a different error, and the you can't continue with generating the report:

couldn't determine table id for report New Report
getRecordSets @ reports.js:213
getReportParams @ reports.js:241
(anonymous) @ reports.js:133
fire @ jquery.js?27d9:3232
fireWith @ jquery.js?27d9:3362
(anonymous) @ jquery.js?27d9:3502
fire @ jquery.js?27d9:3232
fireWith @ jquery.js?27d9:3362
(anonymous) @ jquery.js?27d9:3418
fire @ jquery.js?27d9:3232
fireWith @ jquery.js?27d9:3362
(anonymous) @ jquery.js?27d9:3418
fire @ jquery.js?27d9:3232
fireWith @ jquery.js?27d9:3362
done @ jquery.js?27d9:9834
callback @ jquery.js?27d9:10300

**Comment by benanhalt** [comment]
It looks like it's because that is a workbench report.

**Comment by benanhalt** [comment]
I created a separate issue for that: #372
