### ISSUE TITLE
Move Form Meta After Changing Sub Form to Grid

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3702]
**Describe the bug**
The Form Meta Button "disappears" after changing Type from Subform to grid.

To be more accurate. Can we move the Form Meta Button to the Same place as a Sub Form? Having it only show when expanded is confusing.

**To Reproduce**
1. Go to a form with a sub form
2. Click on its Form Meta. 
3. Change  Type from Subform to grid

**Expected behavior**
Form Meta Button should still be present on top so I that I can easily change back to Sub Form

**Beautiful Picture**

https://github.com/specify/specify7/assets/53784701/7b41a22d-53c1-43b8-864f-667d7ec40b92

**Desktop:**
 - OS: Mac Os
 - Browser: Chrome
 - Specify 7 Version: 7.8.13

**Comment by maxxxxxdlp** [comment]
Form Meta is specific to a resource.

Form table displays several resources at the same time, so you can't have form meta button at the top

Instead, if you expand a single form table row, you will see a form meta button at the right side of the row
