### ISSUE TITLE
Unedited record triggering save button without any changes

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3703]
**Describe the bug**

**To Reproduce**
1. Navigate to the following record (`catalogNumber` : `MZB 2015-8279`): 
    https://mcnb41123-edge.test.specifysystems.org/specify/view/collectionobject/1084175/
2. See that **Save** is enabled even without making any changes 

![image](https://github.com/specify/specify7/assets/37256050/75b5dfcd-bfd0-483a-8b8b-f29a76e588fa)

User: `mcnbadmin`
Database: `mcnb_4_11_23`

**Reported By:** Barcelona ([Trello](https://trello.com/c/p813apne/68-save-changes-and-activate-clone-add-options))

**Comment by maxxxxxdlp** [comment]
Same issue as #3259 (thus this is either a duplicate, or a different cause for same issue)

**Comment by grantfitzsimmons** [comment]
Will close with #3774
