### ISSUE TITLE
Specify crash on taxon form when locality button pressed via Taxon record

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3704]
**Describe the bug**
Error thrown when Loc button pressed from taxon form

**To Reproduce**
1. Go to a Taxon record
2. Click 'Loc' button at top
3. See error

**Expected behavior**
GeoMap should open

**Screenshots**
![msedge_DgDB6O89Zq](https://github.com/specify/specify7/assets/135047322/9eb4e2a5-7e61-4f3b-9cd9-90c9b90612f1)

**Desktop:**
 - OS: Windows 10
 - Browser: Edge
 - Specify 7 Version: works on v7.9.12 not working on v7.8.13-prerelease

**Database Name:** If applicable
coloradopaleo (6.8.03)

**Reported By**
Name of your institution

**Additional context**
Database name or any other context about the problem here.
[Specify 7 Crash Report - 2023-06-29T19_36_32.243Z (1).txt](https://github.com/specify/specify7/files/11909817/Specify.7.Crash.Report.-.2023-06-29T19_36_32.243Z.1.txt)

**Comment by grantfitzsimmons** [comment]
https://coloradopaleo-v7813-prerelease.test.specifysystems.org/specify/view/taxon/2/

**Comment by grantfitzsimmons** [comment]
I am not having any issues when clicking on the Locality form. I did verify that @bronwyncombs experienced this consistently.

**Comment by grantfitzsimmons** [comment]
Can't duplicate.
