### ISSUE TITLE
Enable adding a View (👁️) button to a query combo box

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3707]
## Mock-up

<img width="1449" alt="image" src="https://github.com/specify/specify7/assets/37256050/ad3be9b0-6b13-40ca-b60c-f6d5d53e2cce">

This is using the existing eye icon and behavior when viewing a record in read-only mode

## Rational

Theresa and I met with Willem of SAIAB after he raised the following concerns:

> I want to raise the issue of over-writing of linked records. If I’m not mistaken, it was in 2009 (Specify 6) that the application stopped making a copy of a linked record if it was edited, and started to allow the record to be edited.
> 
> I have seen some terrible cases of corruption of the taxon and geography trees, and over-writing of agent records. I used to think that this was related to education level or job grade or country development level. But now I think it’s just a human thing.
> 
> I think Specify should revert back to cloning a linked record that gets edited. This was a good idea to preserve data integrity. The claim that it causes duplication is perhaps true, but this duplication is by far the lesser evil.
> 
> I’m not really concerned about my database. I can train our people and do frequent checks. But I think this is a reputational issue for Specify, and I predict that if left unattended it could result in some really bad press down the line. I actually regret not being more assertive when I first detected the change. I think I should have made a stronger case to keep the cloning feature.

Training can not be sufficient for some staff, and explaining how a relational database system works can be tricky.

The implications of editing a linked record are difficult to understand for the layman. 

## Recommended Solution

When clicking on the 👁️ (eye), it should display the linked record in a read-only view. When the user clicks on the link out button next to the record name, it should bring them to the normal form which they can edit.

The idea is that linked records accessed using the 👁️ (eye) icon should not be editable when displayed in a dialog. 

This should be implemented as https://github.com/specify/specify7/pull/3669 is, where a new attribute is added to the form definition/configuration that allows an administrator to replace the plus button with an eye icon. Users should still be able to clone, add, or search even if they cannot edit the linked record from the form.

**Comment by CarolineDenis** [comment]
@grantfitzsimmons 
- The edit buttons in the primary form should be replaced by an eye icon that opens the related form in read only (always or set in pref?) 
- The "open in new tab" icon will keep the same behavior and it's through that flow that the user can edit the resource. 
![Screenshot 2023-06-30 at 1 19 50 PM](https://github.com/specify/specify7/assets/108160931/56515ff2-d7dc-44a1-93ac-7f949346
![Screenshot 2023-06-30 at 1 20 32 PM](https://github.com/specify/specify7/assets/108160931/84b90c57-1cf8-4223-8911-53fb614ad9d0)
36bd)

**Comment by maxxxxxdlp** [comment]
This issue is very related to https://github.com/specify/specify7/pull/3553
It was possibly fixed/mitigated by it, or can be modified slightly to do so

**Comment by grantfitzsimmons** [comment]
@CarolineDenis 

We just need to add a new attribute to show an eye icon that opens the form in a read-only view in addition to the others
