### ISSUE TITLE
`xml-editor`: Unknown table: Hashtable

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3708]
<img width="414" alt="image" src="https://github.com/specify/specify7/assets/37256050/980c5071-e730-485c-a92a-e042a477400e">

From `herb_rbge`'s forms. Not sure if this is unknown due to an oversight.

```xml
        <viewdef
            type="form"
            name="Collection Object Search"
            class="java.util.Hashtable"
            gettable="edu.ku.brc.af.ui.forms.DataGetterForHashMap"
            settable="edu.ku.brc.af.ui.forms.DataSetterForHashMap">
            
            <desc><![CDATA[The Collection Object form.]]></desc>
            <enableRules/>
            
            <columnDef>120px,2px,p,2px,120px,2px,p,2px,60px,2px,p,p:g</columnDef>
            <rowDef auto="true" cell="p" sep="2dlu"/>
            
            <rows>
                <row>
                    <cell type="label" labelfor="1"/>
                    <cell type="field" id="1" name="catalogNumber" uitype="text"/>
                    <cell type="label" labelfor="2"/>
                    <cell type="field" id="2" name="collection_collectionName" uitype="text"/>
                </row>
                <row>
                    <cell type="label" labelfor="3"/>
                    <cell type="field" id="3" name="accession_number"  uitype="formattedtext" uifieldformatter="AccessionNumber"/>
                    <cell type="label" labelfor="4"/>
                    <cell type="field" id="4" name="cataloger" uitype="text"/>
                    <cell type="label" labelfor="5"/>
                    <cell type="field" id="5" uitype="plugin" name="this" initialize="name=PartialDateUI;df=catalogedDate;tp=catalogedDatePrecision" uifieldformatter="Date"/>
                </row>
            </rows>
        </viewdef>
```

https://herbrbge33123-issue-3657.test.specifysystems.org/specify/resources/view-set/1/

**Comment by grantfitzsimmons** [comment]
It exists twice, though I have commented them out so that I can test other behavior. You can try on a copy of their database if you are interested!

**Comment by maxxxxxdlp** [comment]
This is a special thing from sp6. One of many special non-database tables.
Sp7 form editor supports those and handles correctly - as you can see this is shown as a warning rather than as an error

1. The warning being shown twice is a bug, but maybe not specific to this table
2. We could consider detecting this specific case and not even emitting a warning to not confuse the user

**Comment by grantfitzsimmons** [comment]
If I recall correctly, it prevents **saving the record** since it is invalid.

**Comment by maxxxxxdlp** [comment]
Warnings should not be preventing save - if they are, it's a bug

**Comment by grantfitzsimmons** [comment]
https://github.com/specify/specify7/assets/37256050/525db78f-21db-409c-bb9e-3771e4228229

_My memory was correct!_ I cannot save.
