### ISSUE TITLE
Some reports/labels won't generate

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#371]
I'm not sure if it's for the same reason for all of them, but on several databases, I've tried generating a label or report and it takes will over 10 minutes and does not appear to make any progress. On the Florida IVP database, I tested the IVP Label with the recordset "WHB" (which only has 4 records) and it displays the same issue. I get an error before clicking on the recordset, so it must have something to do with the label itself. The error is below.

![sp7labelerror](https://cloud.githubusercontent.com/assets/12533028/24871130/48d985e6-1dde-11e7-9d33-98b563b81b33.png)

**Comment by benanhalt** [comment]
Which is another database that is showing this problem? For Florida VP, mysql is getting stuck in the statistics state for the query. I want to see if it is the same in other cases.

**Comment by garrettgirard** [comment]
You can also see this happening in the Tomislav database, by generating the Loan Extension report.

**Comment by beach53** [comment]
This issue appears to be stale.  Any updates from anyone?

**Comment by grantfitzsimmons** [comment]
Not enough details.
