### ISSUE TITLE
KML Files Do Not Have Locality Name

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3711]
**Describe the bug**
Title

**To Reproduce**
1. Go to a Locality Query
2. Click on Create KML
3. Import in Google Earth

**Expected behavior**
More information aside from the placement alone. Here is a link to the [KML Documentation](https://developers.google.com/kml/documentation/kml_tut#:~:text=The%20simplest%20Placemark%20includes%20only,other%20geometry%20elements%20to%20it.).

**Beautiful Pictures**

The Exported Query

[query_results_2023-06-30T19_24_10.686032.kml.zip](https://github.com/specify/specify7/files/11919958/query_results_2023-06-30T19_24_10.686032.kml.zip)

<img width="1791" alt="Screenshot 2023-06-30 at 3 55 00 PM" src="https://github.com/specify/specify7/assets/53784701/ffb67327-d645-40cc-9275-9734b3b08e7c">
<img width="1792" alt="Screenshot 2023-06-30 at 3 55 15 PM" src="https://github.com/specify/specify7/assets/53784701/ff29a46c-1948-4f06-a8ec-e369f40e0501">

<img width="1792" alt="Screenshot 2023-06-30 at 2 38 56 PM" src="https://github.com/specify/specify7/assets/53784701/4a8803d4-18a8-427b-a850-6639d35dfb29">

**Desktop:**
 - OS: Mac Os Ventura
 - Browser: Chrome
 - Specify 7 Version: 7.8.13

**Database Name:** If applicable

**Reported By**
Name of your institution

**Additional context**
Database name or any other context about the problem here.

**Comment by emenslin** [comment]
Fixed, if it's a locality query it will display the locality name now and if it is a CO query it displays the catalog number
