### ISSUE TITLE
Background Preference Colour Option is very difficult to notice and does not apply in Preferences Page

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3714]
**Describe the bug**
You can customise the background colour in User Preferences. The issue is that the Colour Picker for the `Background` is the same Colour as the `Background` which makes it practically invisible. I only noticed that this was a colour picker when I was changing from light mode to dark mode.

**To Reproduce**
1. Go to Customization -> Preferences -> Appearance
2. Click on `Background`
3. See error

I honestly thought it was a sub heading for the longest time.

Secondly, after changing the colour. The Background changes throughout Specify but not in this page.

**Expected behavior**
A more clear indicator that this a colour picker. 

And this one is tricky as it leads to the first issue. But since Background is controlled by this Colour Picker. Shouldn't changing it cause the Preferences Background to change and match the new option.

**Beautiful Pictures**
<img width="1630" alt="Screenshot 2023-07-03 at 12 22 19 PM" src="https://github.com/specify/specify7/assets/53784701/e11828f1-6be1-4fef-984c-5b1fe5804f1c">
<img width="1628" alt="Screenshot 2023-07-03 at 12 23 08 PM" src="https://github.com/specify/specify7/assets/53784701/e67746ed-4f0d-4aac-8bc0-b1e91255ca4f">
<img width="1627" alt="Screenshot 2023-07-03 at 12 24 31 PM" src="https://github.com/specify/specify7/assets/53784701/13b91d7c-4274-44c1-9bf3-9e2179f3c0b7">
<img width="1625" alt="Screenshot 2023-07-03 at 12 29 59 PM" src="https://github.com/specify/specify7/assets/53784701/4f7c00da-46f0-41ba-8eb1-015bf3665973">

**Desktop:**
 - OS: Mac OS
 - Browser: Chrome
 - Specify 7 Version: 7.8.13

**Comment by maxxxxxdlp** [comment]
@carlosmbe while we appreciate you reporting these usability issues, can you please also give a try to testing business rules, attachments, reports or forms? those components have real bugs that lead people to loose data or even leave specify altogether.
then you can also start looking into fixing the bugs you discover (of course, after receiving a proper introduction to the code)

I have a lot of recorded videos where I go over the source code of all the major components of specify - https://drive.google.com/drive/u/0/folders/176NrPNS1qlqu9YBsx9pk1AMb0VFhlcBL

Those should be an excellent start.

See also https://github.com/specify/specify7/wiki/Docker-Workflow-for-Development for instructions on deploying specify locally
