### ISSUE TITLE
Rename Security and Accounts `Create Button`

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3716]
**Is your feature request related to a problem? Please describe.**
The work flow for adding roles and permissions to a new user is not very User Friendly right now. After discussing with a senior Sales team member they agree.

**Describe the solution you'd like**
An area that we could easily improve is the `Collection User Roles` Section. It'd be great if we renamed its `Create` Button to something similar to `Add Role` and perhaps if you'd like to keep the `Create` Button. Use it in place of the `New` Role Button. The `Create Role` Title could also be `Add Role To Collection`.

<img width="752" alt="Screenshot 2023-07-03 at 2 02 58 PM" src="https://github.com/specify/specify7/assets/53784701/27ec0ce7-ef8e-48fe-80a7-bf89d396e260">
<img width="880" alt="Screenshot 2023-07-03 at 2 07 01 PM" src="https://github.com/specify/specify7/assets/53784701/2864c142-92a2-4376-b4f3-4dc6727e1790">

**Comment by grantfitzsimmons** [comment]
Should be solved by #3778
