### ISSUE TITLE
Long record titles cause alignment issues with forms

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3718]
**Describe the bug**
If you have an attachment with an unreasonably long title and click on `Hide Form`. The Image is not centralised. It leans towards the left

**To Reproduce**
1. Upload an attachment with a long title. For example,
68747470733a2f2f696d672e776174747061642e636f6d2f73746f72795f70617274732f313030303034323035322f696d61.gif
2. Click on `Attachments` in the Navigation Bar
3. Find the Attachment and open it up in the `Gallery`?
4. Click `Hide Form`
5. See error

**Expected behavior**
Centralised. Similar to other images.

**Beautiful Pictures**

https://github.com/specify/specify7/assets/53784701/ee48d510-9906-45fa-9318-c8ff044d8de4

<img width="1580" alt="Screenshot 2023-07-03 at 2 39 52 PM" src="https://github.com/specify/specify7/assets/53784701/f6730e55-ef5c-49bd-840c-aa10011baa50">
<img width="1236" alt="Screenshot 2023-07-03 at 2 39 58 PM" src="https://github.com/specify/specify7/assets/53784701/cfebf7ba-b5ae-4e80-b34c-65023a4c121a">
<img width="1136" alt="Screenshot 2023-07-03 at 2 40 58 PM" src="https://github.com/specify/specify7/assets/53784701/2b4e651b-8a04-47c8-965a-18324e2f9a03">

**Desktop:**
 - OS: Mac OS
 - Browser: Chrome
 - Specify 7 Version: 7.8.13

**Comment by CarolineDenis** [comment]
fixed in xml-editor
