### ISSUE TITLE
Query Builder crash with (formatted) is added to Collection Object base table

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3721]
**Describe the bug**
Adding formatted field to query on collection object table crashes

**To Reproduce**
1. Go to query builder > new
2. Click on Collection Object
3. Apply (formatted) field at top of builder
4. Run query
5. See error

**Expected behavior**
Should run query results

**Screenshots**

**Desktop:**
 - OS: Windows 10
 - Browser: Edge
 - Specify 7 Version: edge

**Database Name:** If applicable
herb_rbge_3_13_23

**Additional context**
Database name or any other context about the problem here.
Not consistent among other tables or fields. Seems to be specific to the CO table and (formatted) field
[Specify 7 Crash Report - 2023-07-03T18_55_11.854Z (1).txt](https://github.com/specify/specify7/files/11941087/Specify.7.Crash.Report.-.2023-07-03T18_55_11.854Z.1.txt)

**Comment by melton-jason** [comment]
View the attached video
(_Note: Running the query with the Catalog Number field  is not required to recreate the issue. I just included it to highlight that only the (formatted) field causes a crash_)
 
https://github.com/specify/specify7/assets/64045831/a02c59ad-2f82-4298-bfc0-35d0bfd50d34

**Comment by CarolineDenis** [comment]
@bronwyncombs can you reproduce this on v7.9-dev?

**Comment by bronwyncombs** [comment]
> @bronwyncombs can you reproduce this on v7.9-dev?

@CarolineDenis No, it is working as expected there

**Comment by CarolineDenis** [comment]
Good news. That means we can close this.

**Comment by CarolineDenis** [comment]
Fixed in v7.9-dev
