### ISSUE TITLE
Apply button color preferences to statistics page save button

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3722]
**Describe the Bug**
Changing save button color in preferences has no effect on save button in stats page. Currently, the save button is still controlled by 'Secondary button color'. 

**To Reproduce**
1. Go to preferences and change button color
2. Go to statistics and click edit to show save button

**Expected behavior**
Secondary button color shouldn't apply to stats save button. Save color should apply to stats save button.

**Screenshots**
![Screen Shot 2023-07-05 at 11 44 08 AM](https://github.com/specify/specify7/assets/135047322/4d204cf2-e329-4f92-8ef4-199130a9b221)
![Screen Shot 2023-07-05 at 11 43 48 AM](https://github.com/specify/specify7/assets/135047322/17b759ce-54ed-4049-ae36-37920278ec14)

**Desktop:**
 - OS: macOS 
 - Browser: Chrome
 - Specify 7 Version: v7.9-dev

**Database Name:** If applicable
uoregonpaleo

**Additional context**
Database name or any other context about the problem here.

**Comment by bronwyncombs** [comment]
Let's also unify the save button in the Edit Page dialog. Currently is set as an info button

![Screen Shot 2023-07-06 at 2 47 35 PM](https://github.com/specify/specify7/assets/135047322/83db1076-8773-4248-b66a-1b517aa9f3a9)

**Comment by maxxxxxdlp** [comment]
Love all these colors!

makes it look like `material you`:

![image](https://github.com/specify/specify7/assets/40512816/45c1c831-f2b0-4064-896f-71869ac6d404)

**Comment by grantfitzsimmons** [comment]
Solved by https://github.com/specify/specify7/pull/3747
