### ISSUE TITLE
Cannot create a form definition at the discipline level

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3729]
https://github.com/specify/specify7/assets/37256050/a9e5a3fd-326e-473f-85bf-c41faba3e16d

**Steps to Recreate:**
1. Go to the App Resources viewer
2. Create a new form definition at the discipline level
3. See that it is created under the collection level

https://geology-v7813.test.specifysystems.org/specify/resources/view-set/9/

I could not recreate initially, but I was able to today. 

**Versions:**
* Tested on `v7.8.5`, `v7.8.12`, and `v7.8.13` 
* macOS, Chrome

**Reported By:** CSIRO ([Asana](https://app.asana.com/0/1201972579963460/1204951868944436/f))

**Comment by maxxxxxdlp** [comment]
Any form editing bugs bugs should be tested on the XML editor branch to check if they are reproducable

**Comment by CarolineDenis** [comment]
@grantfitzsimmons let me know if you want to keep this one open

**Comment by grantfitzsimmons** [comment]
No... it seems to be fixed. Ignore my misleading & ridiculous video
