### ISSUE TITLE
`v7.9`: KeyError when using query combo box

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3731]
**Steps to Recreate:**
1. Open a new Collection Object form
2. Type "a" in the Collecting Event query combo box
3. See error

```
KeyError at /stored_query/ephemeral/ 'field' 
```

https://github.com/specify/specify7/assets/37256050/f907c787-d2b7-4b20-a4ca-a87080615098

[Specify 7 Crash Report - 2023-07-06T15_33_41.977Z.txt](https://github.com/specify/specify7/files/11969881/Specify.7.Crash.Report.-.2023-07-06T15_33_41.977Z.txt)

`v7.9` (`issue-2210`), Chrome, macOS

**Comment by emenslin** [comment]
Cannot reproduce
