### ISSUE TITLE
Statistics query 'Browse in Forms' doesn't allow browsing

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3739]
**Describe the bug**
Using the `Browse in Forms` button in query dialog through stats page requires save before moving pages. 

**To Reproduce**
1. Go to statistics page
2. Click on a statistic with query attached
3. Click on `Browse in Forms`
4. Use paginators
5. See error

**Expected behavior**
Should allow to click through forms since no edits are made.

**Screenshots**

https://github.com/specify/specify7/assets/135047322/9b8b0b13-4cc0-4002-8eda-6eb97e8dfbb2

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Specify 7 Version: 7.9-dev

**Database Name:** If applicable
herb_rbge_3_31_23

**Reported By**
Name of your institution

**Additional context**
Database name or any other context about the problem here.

**Comment by maxxxxxdlp** [comment]
Likely same cause as https://github.com/specify/specify7/issues/3259
I will merge them
