### ISSUE TITLE
The isEnforced settings in the tree definitions should be enforced

### ISSUE THREAD

**Issue by timo11** [specify/specify7#374]
When adding/editing a tree node it should not be possible to set the rank to a value that violates the isenforced settings for the tree. For example if class, order, family are enforced, it should not be possible to make a subtribe a child of a class.

**Comment by timo11** [comment]
This issue applies to adds/edits in forms. 
Moves in the tree also do not follow the isEnforced settings.

**Comment by yvonneekanim** [comment]
Tested in a new database. Only enforced ranks can be added.

**Comment by benanhalt** [comment]
The tree level field is now not being set to the default value when the form is opened causing an error when attempting to save new taxa unless the rank is specifically set (even though it does show a value on the form).

**Comment by yvonneekanim** [comment]
New nodes can now be added from trees.
