### ISSUE TITLE
Fictitious record sets show `newRecordSet` instead of user-friendly string upon hover

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3742]
<img width="456" alt="image" src="https://github.com/specify/specify7/assets/37256050/84a81d45-dfcc-497b-ba25-ed6418a005b7">

https://github.com/specify/specify7/assets/37256050/7b65f0a6-f904-4bff-999e-3a1a81a4e750

`v7.8.13`, macOS, Chrome

**Steps to Recreate:**
1. Create a new record
2. Click **Add** to create a new record in a series
3. Click **Save**
4. Hover over the newly visible "create record set button"

**Comment by CarolineDenis** [comment]
@grantfitzsimmons I think this if fixed in v7.9.0 
![Screenshot 2023-07-13 at 1 05 48 PM](https://github.com/specify/specify7/assets/108160931/ead39819-6a91-425d-ac3f-0172ef327f31)

**Comment by CarolineDenis** [comment]
@grantfitzsimmons can this be closed and added to 7.9 milestones ?

**Comment by emenslin** [comment]
Fixed
