### ISSUE TITLE
Add Hide Field Mapper button to stats query dialog 

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3745]
**Describe the bug**
There's no button to hide the mapper in stats query dialog

**To Reproduce**
1. Go to Statistics page
2. Open stat with query

**Expected behavior**
Dialog should have `Hide Field Mapper` option somewhere

**Screenshots**

_**Statistics Page:**_
![Screen Shot 2023-07-07 at 10 05 53 AM](https://github.com/specify/specify7/assets/135047322/5dca32c7-3c68-4230-bec0-a1baa87f41dd)

**_Query Builder:_**
![Screen Shot 2023-07-07 at 10 10 20 AM](https://github.com/specify/specify7/assets/135047322/cce44145-c6ba-4c11-85d9-f8f691928f03)

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Specify 7 Version: 7.9-dev

**Database Name:** If applicable
herb_rbge_3_31_23

**Additional context**
Database name or any other context about the problem here.

Since `Save` is at the bottom and in place of `Save Query` button, it could be better to add this below the mapper by `Count` and `Query`. Depends on what you guys think. Adding this alone at the top might take up space and look out of place/lonely.

**Comment by CarolineDenis** [comment]
The dialog in the stat page containing the query builder is using the same design as the other dialogs container query builder (see below). 
Do we agree to add the "Hide Field Mapper" in all the query builder dialogs? 
@grantfitzsimmons @bronwyncombs @melton-jason 
![Screenshot 2023-07-07 at 10 13 18 AM](https://github.com/specify/specify7/assets/108160931/ba64f0b3-16cf-4ba0-8f51-bd719b6c2180)

**Comment by grantfitzsimmons** [comment]
>Do we agree to add the "Hide Field Mapper" in all the query builder dialogs?

@CarolineDenis Yes
