### ISSUE TITLE
Clicking a link in a notification does not dismiss the notification dialog

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3754]
https://github.com/specify/specify7/assets/37256050/5e5cb9f2-8425-47b3-a819-4406b83ed3e3

**Steps to Recreate:**
1. Transfer a WorkBench data set from one user to the current logged in user
2. See notification on the current user's account
3. Click on the link
4. See that the dialog is not dismissed when clicked

This is a rare situation, so prioritize accordingly.

`v7.8.13`, macOS, Chrome

**Comment by maxxxxxdlp** [comment]
most links in notifications open a new tab - this one does not.
Easy fix - make it open a new tab
A proper fix - listen for link click (without preventing it), check if links opens in new tab, and if not, close the dialog
