### ISSUE TITLE
Renaming a query while it's open should change the Opened Query's Title

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3757]
It'd be nice to have the title change after you rename the title of a saved query. 

A possible implementation is that if the user does not have any unsaved changes have the page refresh after the rename.

https://github.com/specify/specify7/assets/53784701/7d9aa471-336e-438e-a0d3-78fb71495f3a

**Comment by maxxxxxdlp** [comment]
This issue, https://github.com/specify/specify7/issues/3579, and many more like this will be fixed automatically once and forever once we migrate off backbone

**Comment by melton-jason** [comment]
Duplicate of #2234
