### ISSUE TITLE
Able to run empty query 

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3758]
**To Reproduce**
1. Go to query builder
2. Select a base table
3. Don't add any fields and click `Query`

**Expected behavior**
`Query` button should be disabled when mapping is empty

**Screenshots**

https://github.com/specify/specify7/assets/135047322/415e9967-3108-4100-a2bf-c848aaf156fe

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Specify 7 Version: 7.9-dev

**Database Name:** fwri_6_1_23
Not in `v7.8.13`

**Comment by melton-jason** [comment]
> 4. See error

Does this really show an error? 
If not and it "runs" the empty query, then I believe this behavior is intentional. 
Look at related issue #2520. 

Was this behavior different in other recent versions?

**Comment by grantfitzsimmons** [comment]
It's funny that #2520 is totally the opposite of #3758.

**Comment by CarolineDenis** [comment]
@grantfitzsimmons since this was a features requested should we keep this issue open?

**Comment by grantfitzsimmons** [comment]
We should probably close this issue
