### ISSUE TITLE
Stats Page's `Pages` Can Have Blank Name

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3759]
**Describe the bug**

**To Reproduce**
1. Go to Stats Page
2. Click on Edit
3. Add a new page
4. For the title press the space button
5. Save
6. See error

**Expected behavior**
I shouldn't be allowed to have the title be whitespace

**Screen Recording**

https://github.com/specify/specify7/assets/53784701/ae3ed553-82ac-4484-882d-e4b9bb8e089f

**Desktop:**
 - OS: Mac OS
 - Browser: Chrome
 - Specify 7 Version: 7.9

**Comment by grantfitzsimmons** [comment]
This is not worth resolving in `v7.9`, and maybe not at all.

**Comment by grantfitzsimmons** [comment]
Minor design recommendations should be placed on the front-end backlog to be discussed or implemented according to priority :smile:

**Comment by carlosmbe** [comment]
I imagine it shouldn't be too difficult to fix since there already is some function making sure that the `Category` titles are not empty

**Comment by maxxxxxdlp** [comment]
Empty and consisting of whitespace only are not the same things

The code works correctly to prevent empty titles.

We could prevent this issue to by force-trimming titles, but not worth spending developer time on this
