### ISSUE TITLE
Highlight new cells in workbench.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#376]

**Comment by yvonneekanim** [comment]
I tested this in a new database with no previous records and new cells were not highlighted.

**Comment by timo11** [comment]
If you want new cells (and cells with multiple matches) to be highlighted you need to check the 'match while validating' setting. (Click the Settings button.)

**Comment by yvonneekanim** [comment]
Match while validating was selected; only invalid cells are highlighted in the workbench.

**Comment by timo11** [comment]
Only taxa, geography, locality, and some agent fields are highlighted if they're new or multiply matched.

**Comment by yvonneekanim** [comment]
I uploaded some fictional data and some of the new cells were highlighted. 
![untitled](https://user-images.githubusercontent.com/28809154/29841892-c00bcc02-8ccc-11e7-91b7-f6d8f388d51f.png)
