### ISSUE TITLE
Saving a record set of stacked forms gets 404 after save  

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3765]
**Describe the bug**
Saving a record set fictitiously created via opening form types (aka not via add, clone, or carry forward) leads to 404. These are later able to be accessed from Record Sets on side bar and are unlabeled. When opened, the first record will show, but going to the next record triggers 404. 

**To Reproduce**
1. Go to Data Entry or Interaction form
2. Click on save
3. Go to another Data Entry or Interaction form (notice paginators are now in the top right)
4. Click on save (notice record set icon is now in top left)
5. Click on record set icon to save records as a record set
6. Attempt to move pages 
7. See error

**Expected Behavior**
Save and be able to view all assigned records

**Screenshots**

https://github.com/specify/specify7/assets/135047322/9dcc1281-8039-465f-9d80-1a1a03faf1d9

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Specify 7 Version: v7.9-dev

**Database Name:** If applicable
`fwri_6_1_23`

**Additional context**
- N/A to previous versions
- Found using different form types in one set, but issue persists with same form type used (e.g. CO>save>Data Entry>CO>save)

**Comment by maxxxxxdlp** [comment]
For those who will be debugging this: see how the URL changes between `0:17` and `0:19` in the video - that change is very suspicious, as if ID is appended to existing ID

**Comment by emenslin** [comment]
Fixed
