### ISSUE TITLE
Add preference to toggle between showing thumbnails or originals in the attachment preview

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3770]
> Oh, bummer. The Attachment server is online – you can still access the Attachment from the download button or “Open As a new Tab”. As it stands, Zack and Sara will never be able to see that image then. Browsers have an optimized feature that stops a page load if it takes a long time. The Attachment will show up if I reduce the JPG and upload that as the Attachment – but the curators would like to Specify to store and give visitors access to the highest quality image through Specify.

No preview will ever load because their images are too big:

<img width="670" alt="image" src="https://github.com/specify/specify7/assets/37256050/b816897d-5ef1-4a38-bfeb-4b6b51fca7f0">

>If I may suggest changing this behavior to point to a reduced JPG (similar to how thumbnails were handled), and allow only the Download button and Open As a new Tab to link to the original, high-resolution file?

**Requested By:** New Mexico Herbarium

**Comment by CarolineDenis** [comment]
@grantfitzsimmons, isn't this working? 

![Screenshot 2023-07-13 at 9 47 10 AM](https://github.com/specify/specify7/assets/108160931/61e91091-9f3e-436a-96f9-be55ccfdca6f)

**Comment by grantfitzsimmons** [comment]
<img width="1389" alt="image" src="https://github.com/specify/specify7/assets/37256050/b007496b-8fb6-4983-b116-d891af766366">

It works on `v7.9` I see. I looked for that option, didn't see it, and didn't know if it was ever added. Great to see. Thanks @CarolineDenis !!
