### ISSUE TITLE
Custom form definitions established at the global level are overridden by default discipline form definitions

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3780]
**Describe the bug**
Even though there are no conflicting form definitions at any level, the global view definition is not used in favor of using the default form definition for the discipline.

**To Reproduce**
1. Go to this link and see the form definition 
    https://morpaleo2may-v79-dev-2.test.specifysystems.org/specify/resources/view-set/1/
    Download: [paleocontext global view.xml.zip](https://github.com/specify/specify7/files/12045861/paleocontext.global.view.xml.zip)
2. See that the `paleocontext` definition is not being used in favor of the default 
Vertebrate Paleontology form definition: 
    https://morpaleo2may-v79-dev-2.test.specifysystems.org/specify/view/paleocontext/new/

**Expected behavior**
The default form definitions should be applied absolutely last, if possible.

**Screenshots**
### Global View definition (see no `lithoStrat`)
<img width="1392" alt="Screenshot 2023-07-13 at 9 54 32 PM" src="https://github.com/specify/specify7/assets/37256050/11eb3944-287c-4c1e-8b6e-7959923c0a07">

### Form as it displays (see `lithoStrat` is present)
<img width="962" alt="image" src="https://github.com/specify/specify7/assets/37256050/337b013d-e750-481b-867a-c66ce35adad3">

Also see that there is no "Edit form definition" link as it is using a default form:
<img width="590" alt="Screenshot 2023-07-13 at 10 03 13 PM" src="https://github.com/specify/specify7/assets/37256050/0aaac998-b5b2-4ceb-b815-c8ed195dc42f">

**Reported By:**
CSIRO ([Asana link](https://app.asana.com/0/1201972579963460/1204951868944436/f))

**Comment by grantfitzsimmons** [comment]
Tables that do not have form definitions established for them in the default discipline-specific form definition can be established at a global level without any issue. The issue is that these defaults are being applied before Specify looks at the custom global views in the hierarchy.

**Comment by grantfitzsimmons** [comment]
Zsuzsanna Papp at the University of Copenhagen is also looking for this functionality

**Comment by CarolineDenis** [comment]
@grantfitzsimmons , is this linked to: https://github.com/specify/specify7/issues/3956

**Comment by grantfitzsimmons** [comment]
It very well could be. Need to have a tester verify this

**Comment by CarolineDenis** [comment]
@carlosmbe @bronwyncombs @pashiav can one of you test if this is still an issue on the xml-editor branch? 
Thank you!

**Comment by CarolineDenis** [comment]
@grantfitzsimmons, Tested with morpaleo2may on xml branch and seems to be fixed

**Comment by CarolineDenis** [comment]
fixed on xml-editor
