### ISSUE TITLE
Query Browse in Forms dialog changes size as you navigate

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3784]
**Describe the bug**

The dialog shrinks and grows as you click through. Makes it hard to go through at a decent pace since you have to move your mouse between forms. Not in `v7.8.13`.
 
**To Reproduce**
1. Query on Accession table
2. Click on `Browse in Forms`
3. Browse pages

**Expected behavior**

Dialog should stay uniform size as you browse

**Screenshots**

https://github.com/specify/specify7/assets/135047322/a6242a1e-90cb-4e57-8c75-8e71e630f931

**Desktop:**
- MacOS, Chrome, v7.9-dev

**Database Name:** 
`fwri_6_1_23`

**Comment by grantfitzsimmons** [comment]
>An aggravating thing I have just come across in Specify 7.  I am navigating a record set using the arrows in the top right hand corner and trying to navigate through multiple records with multiple clicks.  I am finding that based on the form structure, the arrows are moving horizontally slightly which means that I inadvertently hit the >> button and it takes me right to the end. 

**Reported By:** @acbentley

**Comment by CarolineDenis** [comment]
@maxxxxxdlp, do you remember what we could have changed for this to happen?

**Comment by beach53** [comment]
Dont know what is cause and what is effect, but the change in width corresponds to the length of the text in the notes field in the middle of the page.  If the text string is long enough to word wrap the form enlarges, if the text is only partial width of the field, it contracts.

**Comment by maxxxxxdlp** [comment]
@CarolineDenis
We added a feature that remembers dialog sizes
But, it only kicks in if the user manually tries to change the dialog size. And it is stored in the local storage, so is lost if browser cache is hard cleaned

The other thing you added is a feature that allows dialogs to grow in width, but never shrink. I remember there were some issues with that. Don't remember if we fixed the issues and merged it in, or discarded the idea

**Comment by grantfitzsimmons** [comment]
> We added a feature that remembers dialog sizes

Do not enjoy this feature.

**Comment by maxxxxxdlp** [comment]
yeah, it has bad side effects if your display/browser window size changes - we need to modify the code slightly to handle that case (add `max-height: 100vh` OR instead of on dialog having this CSS stlye `height: 123px`, have `height: min(123px, 100vh)`). @CarolineDenis can you look into doing that?

> Do not enjoy this feature.

and you can always disable

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp 

>and you can always disable

I live by defaults, as most users do :wink:
I also do not work in the same database for a prolonged period of time, unfortunately.

**Comment by CarolineDenis** [comment]
> min(123px, 100vh)

Are you referring to the width not the height in those lines? 
`      style={{
        overlay: { zIndex },
        content:
          typeof initialSize === 'object'
            ? {
                width: `${initialSize.width}px`,
                height: `${initialSize.height}px`,
              }
            : undefined,
      }}`

**Comment by maxxxxxdlp** [comment]
both width and height I suppose. see https://specifydev.slack.com/archives/CC6V12D3J/p1685113569604869

also, check if any of these tailwind class names work, if so, it would be cleaner than using `style`
![Screenshot 2023-08-17 at 19 52 04](https://github.com/specify/specify7/assets/40512816/2162f775-5e24-428d-87d6-b93c57d37e6c)

**Comment by maxxxxxdlp** [comment]
sorry for the confusion,

my suggestions were in response to Grant's comment, not in response to the original bug. see https://specifydev.slack.com/archives/CC6V12D3J/p1685113569604869
