### ISSUE TITLE
Extra record added to Browse in Forms set that never loads 

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3785]
**Describe the bug**
On some queries, selecting Browse in Forms will add one record to the total count in that dialog. If you attempt to go to that extra page, it never fully loads. Have not been able to reproduce from main query builder thus far. 

**To Reproduce**
1. Go to Statistics
2. Click on a query Statistic and note count
3. Click on Browse in Forms
4. See error (maybe)

**Screenshots**

https://github.com/specify/specify7/assets/135047322/a41f7a6f-9c90-4fb5-8986-cdd8936eb8bd

![Screenshot 2023-07-14 at 10 49 16 AM](https://github.com/specify/specify7/assets/135047322/faea0936-dff0-406d-ad94-b2d0703a77c7)

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Specify 7 Version: 7.9-dev

**Database Name:** Seen in `fwri_6_1_23`, `UOregonPaleo`, and `NHMD_Test_03_08_23`

**Additional context**
- Choose a stat with less than 80 results since the total count won't load initially
- You may have to try several statistics to recreate. The issue is sporadic and moves around. 
- Have seen with: Preparations, Loans, Digitization, Collections Objects Cataloged, Localities Georeferenced

**Comment by maxxxxxdlp** [comment]
This might be fixed by https://github.com/specify/specify7/pull/3764. Can you try it on the `issue-3756` branch?

**Comment by bronwyncombs** [comment]
> This might be fixed by https://github.com/specify/specify7/pull/3764. Can you try it on the issue-3756 branch?

Good news! I tested all stats and that does seem to be the case. Can we close as 

https://github.com/specify/specify7/assets/135047322/ade0b739-d78d-4504-9d03-a0831d46c50a
