### ISSUE TITLE
Cloned records should erase values from unique fields

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3787]
**Describe the bug**
Consider the case of Preparation `barcode`. It must be unique at the collection level, yet when you clone a record (and its associated preparations), the barcode value is preserved. When saving, you then see a destructive error dialog saying that the barcode is not unique to the collection.

These fields need to be cleared when cloning to prevent situations like this one from taking place!

**Comment by maxxxxxdlp** [comment]
Unique fields should already be excluded from clone

See https://github.com/specify/specify7/blob/701daf3eff7f35a767f383651e1afe8130e5eae7/specifyweb/frontend/js_src/lib/components/DataModel/resourceApi.js#L128

If they aren't then it's probably a bug

**Comment by grantfitzsimmons** [comment]
The uniqueness rules system @melton-jason implemented resolves this!
![image](https://github.com/specify/specify7/assets/37256050/00bb50d1-3dea-48d2-a6d1-4a94add4a6a9)
