### ISSUE TITLE
Removing Interaction Agent name from field triggers error

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3795]
**Describe the bug**
Error when deleting an agents name from the fields in the agent subform of some Interaction forms. (Accession, Gift, Borrow, and Repository Agreement)

**To Reproduce**
1. Go to one of the Interaction forms listed above
2. Enter the required # field and add an agent to Agent subform
3. Click Save
4. Remove agent name from the field 
5. See error

**Screenshots**

https://github.com/specify/specify7/assets/135047322/fe5e9d57-960a-47ba-955d-871c75261f93

![Screenshot 2023-07-17 at 11 29 07 AM](https://github.com/specify/specify7/assets/135047322/ccb25681-a12e-4bc6-891d-d26e0899fb89)

**Desktop:**
 - macOS, Chrome, `v7.8.13` & `v7.9-dev`

**Database Name:** sdnhmpaleo_3_31_23

**Comment by maxxxxxdlp** [comment]
the `&agent=null` part in the request URL causes the issue - looking at the video, the request is likely sent by a business rule

need to debug why that is null

**Comment by emenslin** [comment]
Fixed
