### ISSUE TITLE
Data Model Issue - Shipments and Exchange Out

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3799]
**Describe the bug**
Shipments have an Independent Relation ship with Exchange Out and this is an issue that was overlooked from the 5->6 Data Model (According to Theresa) since we could always modify independent sub views in 6.

Shipments needs to have a dependent relationship with Exchange out similar to the other Types like Borrows have a relationship with Shipments.

The main Issue caused by this is that it's not possible to add Shipments to a Exchange Out in Specify 7

**To Reproduce**
1. Go to Interactions
2. Click on Exchange Out
3. See error

**Screenshots**
<img width="1206" alt="Screenshot 2023-07-17 at 2 11 45 PM" src="https://github.com/specify/specify7/assets/53784701/e4d77879-a939-4e25-bc63-9d1d71b1b9ce">

**Desktop:**
 - OS: Mac OS
 - Browser: Chrome
 - Specify 7 Version: 7.9

**Database Name:** Mor Paleo

**Comment by maxxxxxdlp** [comment]
Need ot either change data model, or fix https://github.com/specify/specify7/pull/3125

**Comment by melton-jason** [comment]
Fixed with the implementation of Independent Subview support in Specify 7:  #5253
