### ISSUE TITLE
Don't use node numbers in queries created from tree view.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#380]

**Comment by benanhalt** [comment]
For QA check that queries generated from nodes in all types of trees are working.

**Comment by benanhalt** [comment]
The current fix won't work because it only filters on the node name at the given level. But clearly there could be nodes with the same name in separate subtrees.

**Comment by benanhalt** [comment]
For testing:

In the tree view, you can *right-click* a node and choose *Query*. This will open a query builder tab that queries for collection objects associated with that node or its descendants. The resulting queries should return the same results between the *master* and *develop* branches.

**Comment by yvonneekanim** [comment]
Tested this in UTAustinpaleo; queries made from tree view in the internal version return the same results as the external version where node numbering is still enabled.
