### ISSUE TITLE
Agent Merging - TransactionManagementError 

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3802]
**Describe the bug**
Could be related to this

https://github.com/specify/specify7/pull/3794

**To Reproduce**

1. Go to NHMD -> Amber -> Queries
2. Create a `formatted` query for `Agents`
3. Merge the first 40 Agents that show up (in one go)
[Specify 7 Crash Report - 2023-07-18T20 46 37.534Z.txt](https://github.com/specify/specify7/files/12088934/Specify.7.Crash.Report.-.2023-07-18T20.46.37.534Z.txt)

**Screenshots**
<img width="1792" alt="Screenshot 2023-07-18 at 3 46 35 PM" src="https://github.com/specify/specify7/assets/53784701/92c1be7d-4295-437e-bcde-3d516f49b58b">

**Desktop:**

OS: Mac
Browser: Chrome
Specify 7 Version: 7.9

**Comment by realVinayak** [comment]
Resolved in https://github.com/specify/specify7/pull/3812
