### ISSUE TITLE
Business Rules / Agent Merging - BusinessRuleException GroupPerson must have unique member in group

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3807]
**Describe the bug**
Talk to Jason for more details. 

The way I understood it is that the error occurs when you try to merge an Agent into a group that it's already a part of.

**To Reproduce**
1. Go to NHMD -> NHMD AMBER
2. Create a `Formatted` Query for Agents
3. Reverse the results sorting order so that it's Descending 
4. Merge the Agents without a name
5. See error

**Beautiful Pictures**

Part1
https://drive.google.com/file/d/1sLBe98F9NTtO4wLmjswvSVwfZ369_Vy9/view?usp=share_link

Part2
https://drive.google.com/file/d/1wONptMpw8xrt3_07Iw47sEIoi_aUyEyG/view?usp=share_link

**Desktop:**
 - OS: Mac OS
 - Browser: Chrome
 - Specify 7 Version: 7.9

**Comment by carlosmbe** [comment]
Linking to PR #3832

**Comment by grantfitzsimmons** [comment]
Fixed in #3832
