### ISSUE TITLE
Don't use node numbers for tree level queries.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#381]

**Comment by benanhalt** [comment]
For testing:

This change affects the way queries work with trees. I recommend comparing the query results involving tree using the same database on both the *develop* and *master* branch servers. The results should be the same, but the *develop* server should be a lot faster.

**Comment by benanhalt** [comment]
Note: this may also affect query combo boxes, if they use any tree fields.

**Comment by garrettgirard** [comment]
I didn't really notice much of a difference in how quickly the results returned for tree queries. Is there any other way to test this?
