### ISSUE TITLE
Add "Basic View" to query dialog in statistics

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3811]
Statistics query dialogs should have a button for the `Basic View` option too. [Pertinent Pull Request](https://github.com/specify/specify7/pull/3454#event-9865084008)

**Comment by maxxxxxdlp** [comment]
Relevant comment: https://github.com/specify/specify7/pull/3748#pullrequestreview-1520834905

Thus, the fix for https://github.com/specify/specify7/issues/3000 will fix this issue too

**Comment by CarolineDenis** [comment]
duplicate of https://github.com/specify/specify7/issues/3830
NOTES: query dialog and query instant use the same component
