### ISSUE TITLE
Move the merging process to the worker

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3817]
@acwhite211 

Move the agent merging process to the worker!

**Comment by maxxxxxdlp** [comment]
How long does it take to do the merging?
The worker was used so far only for long-running processes as there is added complexity and performance overhead - but maybe it's worth it in this case

**Comment by grantfitzsimmons** [comment]
Can take 15-20 minutes for a batch of agents with a lot of references. It also overwhelms some laptops (ask @carlosmbe)

**Comment by CarolineDenis** [comment]
@grantfitzsimmons @acwhite211 can we close this?
