### ISSUE TITLE
Calculate tree view stats without use of node numbers.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#382]

**Comment by benanhalt** [comment]
For testing:

The tree stats refer the the parenthesized numbers that appear the lower levels of the tree to indicate the numbers of associated collection objects. Testing would involve checking that these numbers appear and are correct.

**Comment by garrettgirard** [comment]
Verified in LSU Mammals. The new method of calculating the tree stats works correctly, and the number in parentheses is the same as it was before (same as number of associated COs).
