### ISSUE TITLE
Scroll bars appearing for no reason in app resources

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3826]
**Describe the bug**
When using both Chrome and Firefox on `v7.9-dev`, you can see unnecessary scroll bars in App Resources.

<img width="1920" alt="Screenshot 2023-07-21 at 3 04 51 PM" src="https://github.com/specify/specify7/assets/37256050/8eec2170-ef82-4657-b262-2700819d008b">

## Solution

The issue is with this CSS:

```
  @media (min-width: 640px)
.sm\:overflow-scroll {
  overflow: scroll;
}
```

When it is disabled, it appears correctly.

https://github.com/specify/specify7/assets/37256050/dacbe93d-6a0c-4230-aca7-bf32a792fd8a

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp Can you let me know if this class is applied for a specific reason?

**Comment by maxxxxxdlp** [comment]
the scrollbars where there for a good reason I am pretty sure, but current behavior does not look right - possibly something in the code changed which caused an issue here

generally, scrollbar gutter preserve is for reducing UI shifts

**Comment by grantfitzsimmons** [comment]
No

<img width="959" alt="image" src="https://github.com/specify/specify7/assets/37256050/f468aa70-99f1-492b-9222-c8a40cc438fa">

**Comment by grantfitzsimmons** [comment]
Should be solved by https://github.com/specify/specify7/pull/3827 if I recall correctly
