### ISSUE TITLE
`DefaultUserPreferences` do not funciton at a global level

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3828]
<img width="1624" alt="Screenshot 2023-07-21 at 3 40 08 PM" src="https://github.com/specify/specify7/assets/37256050/5efb4fbf-15c7-4bb1-804e-21cbcf77d34c">

See that I have custom colors and a background image:

```
{"general":{"appearance":{"accentColor1":"#eaaec8","accentColor2":"#de81aa","accentColor3":"#d45d92","accentColor4":"#ca3979","accentColor5":"#84234e"}},"welcomePage":{"general":{"mode":"customImage","source":"https://herbarium.nmsu.edu/documents/nmsu-herbarium_logo.jpg"}},"treeEditor":{"geography":{"treeAccentColor":"#55af3c"},"storage":{"treeAccentColor":"#5a45f7"}}}
```

These apply when they exist at the discipline level, but not when it exists at the Global level.

`v7.8.13`

**Comment by maxxxxxdlp** [comment]
hmm, did you delete this app resource from the discipline level? if it is on the discipline level, than that will take priority, even if it is also defined at a global level (and it does not do merging of multiple levels at the moment)

the other possibility, which is much more worrisome, is that the app resource is in a global directory, but not the same global directory (for sp6 legacy reasons, there are several global directories, but sp7 front-end makes it look like there is just one by merging them together visually just to simplify things)

**Comment by grantfitzsimmons** [comment]
I cleared my cache and tried different browsers. I ensured there was no existing or conflicting default or regular user preferences. I understand the scoping, but this is worse :wink:

I hope it's some kind of caching issue or user error, but I could never get the default preferences to apply when they existed at the global level!

**Comment by emenslin** [comment]
Fixed
