### ISSUE TITLE
Strange Rendering of Locality Results

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3829]
**Describe the bug**

I performed these tests in Mor Paleo and NHMD. When performing a locality query and hiding every option in the results. There's a weird layout in the results.

**To Reproduce**
1. Go to Queries and Create (or Open) a Locality Query
2. Add some fields and make them all invisible 
3. Run Query
4. Scroll down to results
5. See error

**Expected behavior**
Similar behaviour to when you hide Collection Objects

**Screenshots**
<img width="1632" alt="Screenshot 2023-07-21 at 4 56 22 PM" src="https://github.com/specify/specify7/assets/53784701/b7e98f16-54c6-4a0b-b176-0f7c760ebee1">

<img width="1627" alt="Screenshot 2023-07-21 at 4 48 35 PM" src="https://github.com/specify/specify7/assets/53784701/d5a39638-9672-43cf-b8ad-125073de8735">

https://github.com/specify/specify7/assets/53784701/9e22d0f7-e692-412b-82ae-b4691de76621

**Desktop:**
 - OS:  Mac OS 
 - Browser: Chrome
 - Specify 7 Version: 7.9 and 7.8.13

**Comment by bronwyncombs** [comment]
Crash report when distinct is selected after hiding a field. 

https://github.com/specify/specify7/assets/135047322/827c7637-1c10-4d4f-9083-9b02ebb874dc


[Specify 7 Crash Report - 2023-07-24T15_03_28.052Z.txt](https://github.com/specify/specify7/files/12147304/Specify.7.Crash.Report.-.2023-07-24T15_03_28.052Z.txt)

**Comment by CarolineDenis** [comment]
NOTES: due to phantom fields

**Comment by melton-jason** [comment]
There might already be a fix for this on the `use-dynamic-ranks` branch. 
See https://github.com/specify/specify7/issues/3327

Can we confirm if this is fixed?

**Comment by CarolineDenis** [comment]
> There might already be a fix for this on the `use-dynamic-ranks` branch. See #3327
> 
> Can we confirm if this is fixed?

it is not

**Comment by maxxxxxdlp** [comment]
> NOTES: distinct should not be an option when all fields are hidden.

why? it would still affect the count

@grantfitzsimmons can you remind me, is distinct applied to all fields, or only displayed fields?

**Comment by grantfitzsimmons** [comment]
> @grantfitzsimmons can you remind me, is distinct applied to all fields, or only displayed fields?

It's due to #3327

**Comment by melton-jason** [comment]
#3327 is fixed on `use-dynamic-ranks` (it is no longer throwing the error), but the strange formatting of results due to phantom fields is still present. 

> ... is distinct applied to all fields, or only displayed fields?

If I recall correctly, distinct is only applied to displayed fields (hence which caused #3327 in the first place) .

**Comment by CarolineDenis** [comment]
So what is the conclusion? We keep distinct option when everything is hidden or not? 
@melton-jason @grantfitzsimmons

**Comment by grantfitzsimmons** [comment]
We should prevent the query from running if there are no visible columns.

> You cannot run a query when all fields are hidden from results.

There may be some situations where only the count should be returned, but they can just press count and have the columns visible.
