### ISSUE TITLE
Add the ability to switch from detailed to basic view in query dialogs

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3830]
<img width="1202" alt="image" src="https://github.com/specify/specify7/assets/37256050/656e700b-7f0c-454a-83d3-2df841b17c3a">

At this time, there is no way to switch to the basic view, which would be very useful for these dialogs in particular as edits are not being made.

**Comment by bronwyncombs** [comment]
For more context, @maxxxxxdlp left this [comment](https://github.com/specify/specify7/issues/3811#issuecomment-1642909764) on a similar issue I opened: 

> Relevant comment: https://github.com/specify/specify7/pull/3748#pullrequestreview-1520834905
Thus, the fix for https://github.com/specify/specify7/issues/3000 will fix this issue too

**Comment by CarolineDenis** [comment]
Now that we want 2 of the 4 buttons of the query header in the dialog I think we should display the whole header like we discussed before
![Screenshot 2023-07-24 at 1 08 01 PM](https://github.com/specify/specify7/assets/108160931/fa5e42c9-d4fa-473a-9d98-7431af67ecd7)

**Comment by CarolineDenis** [comment]
@grantfitzsimmons, what do you think?

**Comment by grantfitzsimmons** [comment]
:rocket:

**Comment by grantfitzsimmons** [comment]
> <img width="1202" alt="image" src="https://github.com/specify/specify7/assets/37256050/656e700b-7f0c-454a-83d3-2df841b17c3a">
> 
> At this time, there is no way to switch to the basic view, which would be very useful for these dialogs in particular as edits are not being made.

Interestingly, the actual problem this issue was opened to resolve was not.

<img width="868" alt="Screenshot 2023-10-09 at 8 52 15 AM" src="https://github.com/specify/specify7/assets/37256050/38d607a5-15be-4e99-9b29-3ab3069ae4b4">

Will keep opened until the reports dialog also is fixed.

**Comment by CarolineDenis** [comment]
> > <img alt="image" width="1202" src="https://user-images.githubusercontent.com/37256050/255436253-656e700b-7f0c-454a-83d3-2df841b17c3a.png">
> > At this time, there is no way to switch to the basic view, which would be very useful for these dialogs in particular as edits are not being made.
> 
> Interestingly, the actual problem this issue was opened to resolve was not.
> 
> <img alt="Screenshot 2023-10-09 at 8 52 15 AM" width="868" src="https://user-images.githubusercontent.com/37256050/273606061-38d607a5-15be-4e99-9b29-3ab3069ae4b4.png">
> Will keep opened until the reports dialog also is fixed.

https://github.com/specify/specify7/issues/4094
