### ISSUE TITLE
Agent Merging - Record Set Trying to Merge Agent Into Self leads to 404

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3836]
**Describe the bug**
If you merge an Agent from a Record Set via the "Merge Records" Button. The list of possible Agents gets updated to include our newly merged Agent. Which means it's possible to merge an agent with itself. Which leads to a 404 Error.

**To Reproduce**
1. Go to a Agent Record Set
2. Click on the Gear Icon (I think it's official name is Form Meta)
3. Click on Merge Records
4. Search for an agent (or use * as a wild card)
5. Merge the Agents
6. Do it again with the same Agent you just merged
7. See error

This is probably easier on a super small Database or just one you intimately know.

**Expected behavior**
The agent should no longer be searchable since they're now in a better place.

**Beautiful Picture**

https://github.com/specify/specify7/assets/53784701/d8e179be-1e3c-44a9-826d-90a2e99c4764

**Desktop:**
 - OS: Mac OS Ventura
 - Browser: Chrome
 - Specify 7 Version: 7.9

**Comment by carlosmbe** [comment]
@realVinayak. Hello there, I promised to ping you whenever Agent Merging is having trouble.
UwU

**Comment by CarolineDenis** [comment]
same type of issue: https://github.com/specify/specify7/issues/3507

**Comment by CarolineDenis** [comment]
NOTES: after merge, navigate to record set at ids[index-1] or ids[index+1]; index being the current id index in the array ids that just been merged.

**Comment by CarolineDenis** [comment]
DECISION: remove the merge component from META for now.
