### ISSUE TITLE
specify 7 can't display current determination in transaction items sub form

### ISSUE THREAD

**Issue by timo11** [specify/specify7#385]
The default Sp6 loanitems form contains the following:

cell type="field" id="cd6" name="preparation.collectionObject.currentDetermination.preferredTaxon.fullName" readonly="true" uitype="text"

This causes the loan items subform in sp7 to be blank, not there.

**Comment by timo11** [comment]
This field def in the loan items form works for me:

<cell type="field" id="2" name="preparation.collectionObject.currentDetermination.preferredTaxon.fullName" uitype="dsptextfield" readonly="true"/>

**Comment by yvonneekanim** [comment]
Taxon full name is now displayed in loan items subform
