### ISSUE TITLE
No Longer Works - Creating Children for Synonymized Nodes

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3867]
**Describe the bug**
We added this feature in 7.8.4 and here is the [documentation](https://discourse.specifysoftware.org/t/enable-creating-children-for-synonymized-nodes/987/1). Ever since 7.8.13, it no longer works. I theorise that it's due to this [PR](https://github.com/specify/specify7/pull/3586). Yet, that's only a theory.

**To Reproduce**
1. Follow the documentation to enable creating children for synonymized nodes
2. Go to Trees
3. Click on a synonymized node and try adding a child

**Expected behavior**
I should be able to add a child if it's enabled 

**Screenshots**

### 7.9
<img width="1792" alt="Screenshot 2023-07-31 at 9 52 22 AM" src="https://github.com/specify/specify7/assets/53784701/e536f7c0-d3e9-407d-b623-475522d7da40">

### 7.8.12
<img width="1792" alt="Screenshot 2023-07-31 at 9 53 24 AM" src="https://github.com/specify/specify7/assets/53784701/cbed61fb-4eea-4a8c-843c-70b1fae3e0c4">

**Desktop:**
 - OS: Mac
 - Browser: Chrome
 - Specify 7 Version: 7.9 / 7.8.13
 
 Reported By: MCNB

**Comment by grantfitzsimmons** [comment]
@specify/developers 
This should be addressed in 7.9 if possible.

**Comment by CarolineDenis** [comment]
@carlosmbe could you follow those steps and tell me if it fixes it: 
- go to the same deployment you were on 
- go to app resource 
- click on global resources 
- click remote preferences 
- add the line "sp7.allow_adding_child_to_synonymized_parent.Taxon=true" 
- save 
- clear cache 
- go back to tree, test again add child

**Comment by melton-jason** [comment]
To keep everything connected:

The related issue - #751 
The Remote Preference was added in PR - #2778

**Comment by CarolineDenis** [comment]
For me there is no issue, it behave like it should

**Comment by grantfitzsimmons** [comment]
@bronwyncombs can you verify this issue?

**Comment by carlosmbe** [comment]
@grantfitzsimmons Could we add the clear cache bit to the docs and see if it helps MCNB

**Comment by grantfitzsimmons** [comment]
Yes! That's fine!

**Comment by grantfitzsimmons** [comment]
Cannot replicate.
