### ISSUE TITLE
Handle auto-numbering field exceeding maximum length

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3869]
**Describe the bug**
For example, NHMD has 3 Digit Permit Numbers( ### ). If the last created object was 999. It will not create a new Permit. It will be null. Leading to a 404.

**To Reproduce**
1. Go to NHMD Amber
2. Create and save a Permit with 999 as it's value
3. Create another Permit. This time relying on auto numbering

**Expected behavior**
Communicate to the Users that Auto Numbering can handle this.

**Beautiful Screen Recording**

https://github.com/specify/specify7/assets/53784701/7ae9b76b-562c-4ca9-acfb-a199b6e3d1c9

**Desktop:**
 - OS: Mac
 - Browser: Chrome
 - Specify 7 Version: 7.9

**Comment by grantfitzsimmons** [comment]
**Original Title:** Creating Record with Auto Numbering Throws 404 if on last possible number

**Comment by emenslin** [comment]
Closing in favor of #4362
