### ISSUE TITLE
Test TACC Paleolocation plugin

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#387]
The plugin has to be added to one of the Location / Collecting Event / Collection Object forms in a paleo database depending on which table is connected to the Paleo Context. The plugin name is `PaleoMap`.

**Comment by tlammer** [comment]
Paleo Map does not come up.  In the UTAustin database, I put the paleomap plugin on the collecting event form (where PC is), entered a chronostrat with a start date and end date and a locality with coordinates.  When I clicked the Paleo Map plugin, a blank Collecting Information window popped up.

**Comment by tlammer** [comment]
![paleomap blank window](https://cloud.githubusercontent.com/assets/12532430/26324541/d0b160ca-3ef8-11e7-8241-7cf487a87322.png)

**Comment by benanhalt** [comment]
The problem is that the UT paleolocation mapping service is setting the `X-Frame-Options` header to `SAMEORIGIN` which prevents the browser from embedding the map in any web page not hosted under *paleolocation.org*. I will email Tomislav to see if he can get that header removed.

**Comment by benanhalt** [comment]
Tomislav has removed the `X-Frame-Options` header. The map now displays correctly for me on the test server.

**Comment by yvonneekanim** [comment]
Tested in UTAustinpaleo. Paleomap plugin works correctly.
