### ISSUE TITLE
Gifts - Weird Behaviour with Bulk Select

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3870]
**Describe the bug**
 
 I started a new Gift via a Bulk Select. Some Values did not get a value assigned to them. 
 
 If I give them a 0. I get TypeError at /api/specify/gift/ '<' 
 
 If I enter 1, BusinessRuleException at /api/specify/gift/ ('gift preparation quantity exceeds availability (None: 1 0)
 
[Specify 7 Crash Report - 2023-07-31T15_11_09.370Z.txt](https://github.com/specify/specify7/files/12216512/Specify.7.Crash.Report.-.2023-07-31T15_11_09.370Z.txt)

[Specify 7 Crash Report - 2023-07-31T15_16_35.325Z.txt](https://github.com/specify/specify7/files/12216547/Specify.7.Crash.Report.-.2023-07-31T15_16_35.325Z.txt)

**To Reproduce**
1. Go to NHMD Amber
2. Go to Interactions -> Gifts
3. Create a Gift with the ` I am testing a new feature record set`
4. Bulk Select with a value of 1
5. Enter the missing values as described above
6. See error

**Expected behavior**
I don't these Issues warrant a crash. Would be better if we had a pop up or prevented saving.

**Beautiful Screen Recording **

https://github.com/specify/specify7/assets/53784701/bd5ff6f7-4203-465c-8061-9dacfe32dd58

**Desktop:**

- OS: Mac
- Browser: Chrome
- Specify 7 Version: 7.9 

**Database Name:** NHMD

**Comment by emenslin** [comment]
Fixed
