### ISSUE TITLE
Merge dialog: Stretching a large `textarea` field into the other records section leaves it stuck

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3873]
https://github.com/specify/specify7/assets/37256050/76af545c-7833-4590-998e-575be47c2fcc

Expanding a text box outside of its specific column leaves it stuck under other text boxes. You cannot click or shrink it back to its original size.

It should be restricted to the width of its column.

**Comment by grantfitzsimmons** [comment]
From @bronwyncombs (who was the first to discover this):

> **Describe the bug**
> Resizing remarks fields past the column in merge dialog can't be undone 
> 
> **Screenshots**
> 
> https://github.com/specify/specify7/assets/135047322/0f0becf3-ef5b-4fa4-a830-ea45843f5ded
> 
> 
> **Desktop:**
> - macOS, chrome, `v7.9-dev`, `herbrbge_3_31_23`
>

**Comment by maxxxxxdlp** [comment]
Just need to disable horizontal resizing (While still allowing vertical resizing)

https://developer.mozilla.org/en-US/docs/Web/CSS/resize
https://tailwindcss.com/docs/resize

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp thank you :smile:
