### ISSUE TITLE
Remarks field in agent merge dialogs isn't constrained

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3875]
**Describe the bug**
Resizing remarks fields past the column in merge dialog can't be undone 

**Screenshots**

https://github.com/specify/specify7/assets/135047322/0f0becf3-ef5b-4fa4-a830-ea45843f5ded

**Desktop:**
- macOS, chrome, `v7.9-dev`, `herbrbge_3_31_23`

**Comment by grantfitzsimmons** [comment]
Duplicate of https://github.com/specify/specify7/issues/3873
