### ISSUE TITLE
Loan/Gift preparations without count display as NaN on preparation selecting dialog

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3881]
**Describe the bug**
If a preparation doesn't have a count entered, it will show as NaN in the Preparations dialog for loans and gifts. It is also falsely linked. 

**To Reproduce**
1. Create a CO, add preparation but leave count blank
3. Create New Loan or Gift and enter Cat # for the CO record you made 
4. See error in Preparations selection dialog

**Expected behavior**
It should probably default to 1 in the available column and 0 for unavailable. Currently, you can add a preparation to the loan or gift without a count. Count isn't a required field, so this makes sense, but I'm not sure if we want that. 
**Screenshots**

https://github.com/specify/specify7/assets/135047322/6eceb988-134e-4db0-957e-0ea9e5fb138e

**Desktop:**
 - macOS, Chrome, v7.9-dev

**Database Name:** archireef

**Comment by grantfitzsimmons** [comment]
@bronwyncombs Can you see if this behavior happens on `v7.8.13` as well? We can prioritize accordingly based on what you find 😄

**Comment by CarolineDenis** [comment]
I'm wondering if I didn't fix that on the xml branch

**Comment by grantfitzsimmons** [comment]
> <img width="1512" alt="Screenshot 2023-09-07 at 10 22 28 PM" src="https://github.com/specify/specify7/assets/37256050/9c56c313-f63e-4419-b8b6-c14c1bb684b8">
> 
> https://sbnature9523-v7813.test.specifysystems.org/specify/overlay/interactions/
> https://sbnature9523-v79-dev.test.specifysystems.org/specify/overlay/interactions/
> 
> These preparations have no count (no value in the DB), so when creating a loan based on these records the count shown is "NaN". This should be changed to something intuitive to the user. `NaN` doesn't mean anything to non-programmers
