### ISSUE TITLE
Reordering query items with buttons does not trigger the 'Save Query' button

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3888]
**Describe the bug**

>**Zoe W:**
> This is non-urgent and minor.
> After building a query and saving it, and then using the move buttons to change the order of the fields in the query, this edit does not activate the ‘Save Query’ button. To commit the move changes, you need to perform an additional action that does generate the ‘Save Query’ button (either clicking on ‘show in results' or ‘sort’ buttons or adding/deleting a field).

>**Rob VH:**
>This is a bug, the expected result is that any change to the query, including a change in the order of the query rows, would activate the save button, so the user would be able to save the change, if desired.

**To Reproduce**
1. Go to an existing query
2. Use the buttons to reorder the fields
3. See that the save button is not triggered

**Expected behavior**
The save button should be triggered since the order has changed.

**Screenshots**
https://github.com/specify/specify7/assets/37256050/00ae3ed8-0c0f-4a9f-a474-4ad889de9c9c

**Reported By**
CSIRO

**Comment by emenslin** [comment]
Fixed
