### ISSUE TITLE
TypeError when opening Preferences

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3898]
**Describe the bug**
I was viewing attachments, opened preferences, and got this error

**Screenshots**

![Screenshot 2023-08-03 at 11 41 04 AM](https://github.com/specify/specify7/assets/135047322/ab2cc49b-781d-4e35-871c-65697184e181)

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Specify 7 Version:v7.9-dev

**Database Name:** `sp7demofish`

**Additional context**

[Specify 7 Crash Report - 2023-08-03T16_41_12.534Z.txt](https://github.com/specify/specify7/files/12253114/Specify.7.Crash.Report.-.2023-08-03T16_41_12.534Z.txt)

**Comment by bronwyncombs** [comment]
Attachments section disappears from preferences: 

https://github.com/specify/specify7/assets/135047322/a46b9477-8b65-4c84-8fd9-e3e37bc88425

User Preferences App Resource: 

![Screenshot 2023-08-03 at 12 04 48 PM](https://github.com/specify/specify7/assets/135047322/91bb809a-5192-49ad-913f-40d9f481bb3e)

Hopefully will be fixed by PR #3806

**Comment by melton-jason** [comment]
The fix for this is not included in https://github.com/specify/specify7/pull/3806 (that is a separate issue). 
There were a lot of changes to Preferences in v7.9-dev... 

This issue does not happen with other users on that database (I tested `abentley`). 
Though I can not immediately see anything wrong with the attachment preferences at a first glance. 

This would theoretically be solved by deleting the User Preferences, logging out and logging back in. Which will regenerate the Preferences. 
I've downloaded a copy of the database to investigate this further.

**Comment by grantfitzsimmons** [comment]
```json
{"form":{"preferences":{"printOnSave":{"CollectionObject":false,"Loan":true},"enableCarryForward":["CollectionObject"]},"definition":{"flexibleSubGridColumnWidth":true},"behavior":{"makeFormDialogsModal":true}},"treeEditor":{"behavior":{"searchAlgorithm":"contains"}},"attachments":{"behavior":{"displayOriginal":false,"autoPlay":true}},"statistics":{"appearance":{"layout":[{"label":"Personal","categories":[{"label":"Collection","items":[{"type":"DefaultStat","pageName":"user","itemName":"collectionObjectsCataloged","categoryName":"holdings","label":"Collection Objects Cataloged","itemType":"QueryStat"},{"type":"DefaultStat","pageName":"user","itemName":"collectionObjectsDetermined","categoryName":"holdings","label":"Collection Objects Determined","itemType":"QueryStat"},{"type":"DefaultStat","pageName":"user","itemName":"collectionObjectInventorized","categoryName":"holdings","label":"Collection Objects Inventorized","itemType":"QueryStat"}]}]}]}},"general":{"ui":{"theme":"dark"}}}
```

For future reference, this is the `CollectionPreferences` file causing the issue.

**Comment by grantfitzsimmons** [comment]
>  There were a lot of changes to Preferences in `v7.9-dev`.

Closing as this is the most likely reason for this broken file. We can investigate and reopen if this problem occurs beyond the demo database.

**Comment by realVinayak** [comment]
A bit concerning that this even happened in the first place
