### ISSUE TITLE
Pick Lists that are "Entire Table" or "Field From Table" are broken

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3901]
**Describe the bug**
When creating a new pick list that is either Entire Table or Field From Table, you get this error when selecting a table name. Not in v7.8.13. 

**To Reproduce**
1. Create new pick list 
2. For type, select Entire Table or Field From Table
3. Try to select a table 

**Screenshots**

https://github.com/specify/specify7/assets/135047322/fc4bca13-09dc-4be6-b027-844fa51b3dde

![Screenshot 2023-08-04 at 9 53 53 AM](https://github.com/specify/specify7/assets/135047322/38114bb3-e9c4-4940-b0f4-ccf792659fb1)

**Desktop:**
 - macOS, Chrome, `v7.9-dev`

**Database Name:** `aafcaac_3_8_23`

**Comment by bronwyncombs** [comment]
**Reported By:** Matthew Cruz at The University of Michigan 

Schema Config > Attempts to view existing pick list forms > Error

[Specify 7 Crash Report - 2023-08-10T14_48_42.913Z.txt](https://github.com/specify/specify7/files/12316812/Specify.7.Crash.Report.-.2023-08-10T14_48_42.913Z.txt)

**Comment by grantfitzsimmons** [comment]
Another good catch!
