### ISSUE TITLE
Fictitious record set header appears too late

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3903]
**Describe the bug**
When you use the Add or Clone button to add a record, the form doesn't appear to have stacked records until the second record is saved. 

## v7.9:

https://github.com/specify/specify7/assets/135047322/be8cb12b-431d-4fcb-bb97-dfb0207322fa

## v7.8.13:

https://github.com/specify/specify7/assets/135047322/296257b6-a411-413f-86e0-68efb5e82e11

 - macOS, Chrome, `aafc_aac_3_8_23`

**Comment by grantfitzsimmons** [comment]
Good catch!

**Comment by CarolineDenis** [comment]
related: https://github.com/specify/specify7/issues/3706
