### ISSUE TITLE
Re-route back button on table selection dialog when coming from "Change Base Table" 

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3904]
`Change Base Table` button  in schema config brings you to the dialog for table selection. Selecting `Back` on this dialog takes you to the language selection dialog that you encounter when first entering Schema Config tool. From here, you can only add a language or select `Close`, which takes you to the home screen. 

Instead, the `Back` button should bring you back to the schema config page of the table you selected previously- essentially functioning as a back arrow in a browser.

https://github.com/specify/specify7/assets/135047322/9483744d-1485-4a77-89f5-721e1f392069

**Comment by grantfitzsimmons** [comment]
Closing in favor of implementing https://github.com/specify/specify7/issues/1252
