### ISSUE TITLE
Improve Security and Accounts on narrow screens

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3905]
### Current:
![image](https://github.com/specify/specify7/assets/37256050/a0f72aff-5fad-4953-9562-19a247867fbd)

### Proposed:
<img width="1139" alt="image" src="https://github.com/specify/specify7/assets/37256050/5bab0fbb-afe0-4ec7-84ab-a358bd537749">

Something as simple as forcing it to take up only 33% of the screen until it stacks would be excellent.

**Comment by maxxxxxdlp** [comment]
also, consider changing flex layout to vertical on smaller screens (just like in app resources and schema editor)
