### ISSUE TITLE
Race condition exists for embedded collecting event (and paleo context).

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#391]
A race condition between the processing of `domain.json` and `datamodel.json`. If the schema is built from `datamodel.json` before the values of `collectingEventEmbedded`, `paleoContextChild`, and `embeddedPaleoContext` are obtained from `domain.json`, then Collecting Event and Paleo Context will not be correctly treated as dependent resources. This problem was exacerbated by the fix for #373, since having `domain.json` not be cache results in it being much more likely to be processed after the data model.

**Comment by benanhalt** [comment]
For testing:

This bug is difficult to reproduce, but the fix should be tested to make sure it doesn't break embedded Paleo Context databases.

**Comment by benanhalt** [comment]
Hotfixed into master and on SpecifyCloud.

**Comment by benanhalt** [comment]
I made a mistake in this fix impacting paleocontext. Fixed here ef6b86b9e0a7bd93da1d0b9f2d02eac9686ca343

**Comment by yvonneekanim** [comment]
Tested in testinvp. Paleo context is working correctly.
