### ISSUE TITLE
`TypeSearches` and `DataObjFormatters` cannot be applied at a global level

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3918]
Likely due to the same issue as #3828 

<img width="765" alt="image" src="https://github.com/specify/specify7/assets/37256050/29160d40-4c49-4e98-8d9c-9e0269e349f9">

System defaults are being used instead, requiring me to copy both of these to every single discipline so that they are applied.

**Comment by CarolineDenis** [comment]
Might be fixed in https://github.com/specify/specify7/pull/4196

**Comment by emenslin** [comment]
Could not reproduce in edge or xml editor.
