### ISSUE TITLE
Leaving finished merge screen open gets a lot of errors

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3928]
**Describe the bug**

Leaving the screen with the finished merge dialogs open for a while leads to a ton of errors. It keeps making the network requests to fetch the status even after the merge is complete.

**To Reproduce**
1. Merge an agent
2. Leave the screen be for 5-10 minutes
3. See error

**Screenshots**

https://github.com/specify/specify7/assets/135047322/6cb342ec-0cae-4e7d-9a2a-c315aba200b7

**Desktop:**
 - macOS, Chrome, v7.9-dev

**Database Name:** FWRI

**Comment by CarolineDenis** [comment]
Fixed in latest version
