### ISSUE TITLE
Precision Date not set to `null` when date is deleted

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3930]
https://github.com/specify/specify7/assets/37256050/7b64c286-d5bd-4575-bf34-f83c1ad3789a

**Steps to Recreate:**
1. Add a date to the form
2. Set a value
3. See precision is set
4. Delete the date
5. See precision is kept in the database without the date after deletion

This was discovered because agent merging shows date precision if the date is not visible.

This was specifically discovered in a copy of `morpaleo`'s database locally. 

`v7.9-dev` and `v7.8.13`

**Comment by maxxxxxdlp** [comment]
The PartialDateUi component was supposed to remove the precision - when fixing this issue, fix it in there

**Comment by CarolineDenis** [comment]
Fixed in xml-editor with Max new PartialDateUi code
