### ISSUE TITLE
Operations API doc links to the wrong place

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3933]
<img width="368" alt="image" src="https://github.com/specify/specify7/assets/37256050/b1105730-5a4a-486e-9cb9-da00635cd141">

https://sp7demofish.specifycloud.org/documentation/api/operations/all/

```json
        "externalDocs": {
            "description": "How to use specifyweb API as a generic webservice",
            "url": "https://github.com/specify/specify7/wiki/Api-Demo",
        },
```

The link contained in the Specify 7 Operations API docs page links to 
`https://github.com/specify/specify7/wiki/Api-Demo` instead of `https://github.com/specify/specify7/wiki/API-Documentation-Demo`

**Comment by maxxxxxdlp** [comment]
yeah, one big issue with github wiki is that renaming the page can break things, and github doesn't warn you.
they should really do redirects
or at least add a warning
or add ability to assign a hardcoded URL for the page
