### ISSUE TITLE
Stats Page - Spam Clicking Refresh Stops Refresh from working

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3949]
**Describe the bug**
If you rapidly click the Refresh button. Some stats will load. Others will be in a "Loading" State. This continues until the page is refreshed. Other wise clicking refresh again will do nothing but repeat this behaviour 

**Beautiful Screen Recording**

https://github.com/specify/specify7/assets/53784701/1b28a8b2-6075-4bdb-b269-9ac0580d675a

**Desktop:**
 - OS: Mac OS
 - Browser: Chrome
 - Specify 7 Version: 7.9

**Database Name:** morpaleo

**Comment by grantfitzsimmons** [comment]
Solved by #3950
