### ISSUE TITLE
Query offers more tables than can/should be queried on

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#395]
When you click to query a database, the list of tables returned includes more tables than can be queried on, such as Address of Record, Author, and Preparation

**Comment by maxxxxxdlp** [comment]
The list of tables is coming from this Sp6 file: https://github.com/specify/specify6/blob/master/config/querybuilder.xml.

Admins can edit that file to change the list of tables shown.

Or, we can create a simple UI that allows hiding/unhiding and grouping those tables. Though that is a separate issue - https://github.com/specify/specify7/issues/524
