### ISSUE TITLE
Permit Number Being Cloned 

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3960]
Permit Number should not be carried over since it's a unique field. Saving the permit leads to a business rule error.

https://github.com/specify/specify7/assets/53784701/bdbb2e9e-57f5-4625-9801-e1de82ed3705

[Specify 7 Crash Report - 2023-08-31T20_06_20.320Z.txt](https://github.com/specify/specify7/files/12489909/Specify.7.Crash.Report.-.2023-08-31T20_06_20.320Z.txt)

**Comment by grantfitzsimmons** [comment]
https://github.com/specify/specify7/blob/312139ad3ee9290dd00500e764dd0f0c36f8b026/specifyweb/businessrules/uniqueness_rules.py#L99C1-L100C11

**Comment by melton-jason** [comment]
Fixed in https://github.com/specify/specify7/pull/3996
