### ISSUE TITLE
Value Error - Exceeding Auto-Numbering Limit with Attachment Causes Error

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3964]
**Describe the bug**
If you have auto numbering enabled and hit the limit. For example, by having the last item be 999. When you create a new item. It throws a 404. However, if that item had an attachment we get a very loud error message.

[Specify 7 Crash Report - 2023-09-01T19_34_17.423Z.txt](https://github.com/specify/specify7/files/12501079/Specify.7.Crash.Report.-.2023-09-01T19_34_17.423Z.txt)

https://github.com/specify/specify7/assets/53784701/f53114da-d48d-4902-9cb1-5d3c39f6d7c8

**Comment by emenslin** [comment]
Related to #3869

**Comment by emenslin** [comment]
Closing in favor of #4362
