### ISSUE TITLE
Interactions - Field 'id' expected a number but got 'null'.

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3967]
EDIT:

This bug happens to all Interaction Specific Agents. Borrow Agents, Loan Agents, Gift Agents and e.t.c

**Describe the bug**
If you remove all characters from a saved Gift's `Gift Agent`'s name we get an error. It happens in 7.9 and 7.8.13. Please note that the Gift has to be saved for this issue to happen. 

Agent can be both new or existing.

**To Reproduce**
1. Go to a saved Gift
2. Click on Agent
3. Remove all characters 

https://github.com/specify/specify7/assets/53784701/a2aa611e-6fcd-429c-814d-f1adccdc269c

[Specify 7 Crash Report - 2023-09-01T20_37_13.291Z.txt](https://github.com/specify/specify7/files/12501408/Specify.7.Crash.Report.-.2023-09-01T20_37_13.291Z.txt)

https://github.com/specify/specify7/assets/53784701/8a453964-08f6-48ec-a16c-943c1dc976ba

[Specify 7 Crash Report - 2023-09-01T20_40_54.964Z.txt](https://github.com/specify/specify7/files/12501407/Specify.7.Crash.Report.-.2023-09-01T20_40_54.964Z.txt)

**Comment by carlosmbe** [comment]
Same behavior happening with `Borrow Agents`

**Comment by grantfitzsimmons** [comment]
**Reported By:** Robyn at RBGE

> One of the team received two crash reports today whilst trying to change the name of an Agent associated with the Gift table.
> 
> The record was one that had been saved previously and she was trying to edit this record. She clicked into the agent field and then used the backspace key to delete the data in the field. It is all ok until she deletes the last character at which point Specify crashes. I’m not too sure why this is happening – I’ve not had it reported for other Agent fields. 

[Specify 7 Crash Report - 2023-08-31T09_41_15.801Z (1).txt](https://github.com/specify/specify7/files/12516404/Specify.7.Crash.Report.-.2023-08-31T09_41_15.801Z.1.txt)
[Specify 7 Crash Report - 2023-08-31T09_40_35.138Z (1).txt](https://github.com/specify/specify7/files/12516406/Specify.7.Crash.Report.-.2023-08-31T09_40_35.138Z.1.txt)

**Comment by melton-jason** [comment]
This will probably happen with _every_ QueryComboBox and has been in Specify since at least `v7.8.0`

**Comment by emenslin** [comment]
Fixed
