### ISSUE TITLE
Creating gifts doesn't work (v7.9)

### ISSUE THREAD

**Issue by realVinayak** [specify/specify7#3974]
Go to v7.9

Try creating gift. A forever loading screen is displayed. No network request is made, so not backend being busy

**Comment by grantfitzsimmons** [comment]
💀

**Comment by grantfitzsimmons** [comment]
Seems to be happening to many (if not all) tables

**Comment by realVinayak** [comment]
NOO

**Comment by grantfitzsimmons** [comment]
Solved by #3976
