### ISSUE TITLE
Change error message text to remove contractions

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3977]
> Can we change this error message to:
> We are sorry, something has gone a bit wrong.
> Click to see details.
> [skip the contractions and put periods at the end of sentences.]
> 
> ![image](https://github.com/specify/specify7/assets/37256050/9f732124-5608-4671-b600-4d7afc3e24eb)
> 

Reported by: @beach53

**Comment by maxxxxxdlp** [comment]
I took this from an error message on a shopping website - their error message looked very friendly - I hoped that would make our errors friendlier too
But I understand that the language appropriate in a shopping website might not fit in a collection management software
