### ISSUE TITLE
The same field can be opened multiple times when making a query

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify7#398]
I noticed that I could open the same field more than once when making a query. This happens with expandable fields (in taxon, collection object, storage, etc.)  The query returns a number of results but no actual data and an endless blank page I can scroll through.

![problem with query](https://cloud.githubusercontent.com/assets/28809154/26457000/5b70ba8e-4134-11e7-87a7-c5e1f61eda97.png)

**Comment by maxxxxxdlp** [comment]
Duplicate of #107
