### ISSUE TITLE
Clone a CO with collector brings to crash

### ISSUE THREAD

**Issue by CarolineDenis** [specify/specify7#3982]
- Create a CO with a collector 
- Clone the CO 
- Save new CO 
- See error 
- (do not happened when no collector) 
v7.9-dev - db: herbrgbe9323
![Screenshot 2023-09-07 at 7 44 45 AM](https://github.com/specify/specify7/assets/108160931/70762429-69c8-43ac-9762-44144a4b3432)

**Comment by melton-jason** [comment]
> > When cloning accessions, I still get this error when there is an existing agent: #3967
> > Is this in the scope of this PR?
> 
> That issue (#3967) has been around since at _least_ `v7.8.10` (and possibly earlier, I just stopped checking previous versions). I do not think there is enough overlap in underlying cause to justify that solution being included in this PR.
> 
> _However_, it still could be included in the `v7.9` release in it's own PR if it is important enough (at the cost of further delaying the release)

- https://github.com/specify/specify7/pull/3963#issuecomment-1709136162

**Comment by melton-jason** [comment]
Ah, yes you are correct. 
There is a discrepancy between production and `v7.9-dev`. 
As of #3963, I stopped Specify from cloning _any_ fields that had associated uniqueness rules, yet it looks like Collector -> Agent is still being allowed to be carry over/ cloned (and with null values!)

In this case, the frontend _should_ allow cloning/carry forward of Collectors (and **_properly_** carry the values over), as it is in production.
