### ISSUE TITLE
Exchange In query `Browse in Forms` not seeing data 

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3991]
**Describe the bug**
Exchange In query result not being recognized when `Browse in Forms` is clicked. This record was created in a previous version. 
It does work when the result is selected first. 
Not in `v7.8.13`. 

**To Reproduce**
1. Go to https://purherb-v79-dev.test.specifysystems.org/specify/query/103/
2. Run query
3. Click on `Browse in Forms`

**Screenshots**

https://github.com/specify/specify7/assets/135047322/4808e433-0df0-4cef-9206-9c2ce0f9fec7

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Specify 7 Version: 7.9-dev

**Database Name:** PURHerb

**Comment by melton-jason** [comment]
I am not able to recreate this issue on Chrome... 
I have attempted running the query in every collection in the database as well as creating a new query and attempting to recreate the issue


https://github.com/specify/specify7/assets/64045831/4125c3da-4840-47e6-8853-8686debe5a54

Do you consistently encounter this problem?

**Comment by grantfitzsimmons** [comment]
Can't recreate this issue either. Going to close for now...
