### ISSUE TITLE
Can't add information to record sets using the "Record Sets" tab

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify7#400]
When creating a record set using the "Record sets" tab, you can't add information after creating the RS. When the new (empty) record set is opened, it gives an option of adding or deleting the new record set. When the "add" button is clicked, it returns a blank page. This only applies to record sets for trees (taxon. geography, etc),

**Comment by maxxxxxdlp** [comment]
Fixed in `7.7.0` by making record set creation dialog use a form.

You can define a custom form for the `RecordSet` table with all the fields you need, or unhide those fields in the schema so that they appear on the autogenerated form
