### ISSUE TITLE
Date Precision not maintained in edited records

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#4000]
When I edit an existing record to add a precision date that is other than the full date, after I save, the precision goes back to full date.
Reproduced in PRIPaleo and UWFC

1) create a new CO record or open an existing CO record.
2) either link to an existing CE or if it is an existing CO, edit the existing CE.
3) Change either the start or end date precision to something other than full date and enter a value
4) save the record.

When viewing the record, the date field will have reverted back to full date.  I have been able to reproduce it in CE Start Date, CE End Date, and Determinations Determined Date

**Comment by tlammer** [comment]
https://github.com/specify/specify7/assets/12532430/ab60ad76-6355-4cb5-9152-fe54f3cbd554

**Comment by grantfitzsimmons** [comment]
I'd like to start by congratulating @tlammer on issue #4000! 🎉

---

In the `uwfc_3_28_23` database, see the following:
|CollectingEventID|TimestampCreated|TimestampModified|Version|EndDate|EndDatePrecision|
|-----------------|----------------|-----------------|-------|-------|----------------|
|70847|2016-09-22 11:25:55.000|2023-09-11 18:49:58.000|1|1963-01-01|1|
|3689|2001-11-30 14:46:11.000|2023-09-11 18:49:06.000|1|1963-01-01|1|
|3616|2001-12-03 12:28:05.000|2023-09-11 18:37:05.000|1|1963-01-01|1|
|71013|2023-09-11 18:35:30.000|2023-09-11 18:35:30.000|0|1963-01-01|3|
|48464|2011-05-24 16:22:06.000|2023-09-11 18:35:11.000|1|1963-01-01|1|
|71012|2023-09-11 18:02:41.000|2023-09-11 18:02:41.000|0|1963-01-01|3|
|3425|2001-12-03 12:21:13.000|2023-09-11 18:01:35.000|1|1960-09-01|1|
|71011|2023-09-11 18:00:31.000|2023-09-11 18:00:31.000|0|||
|41624|2006-10-16 15:20:31.000|2023-09-11 17:56:50.000|1|1983-01-01|1|
|70015|2020-09-28 16:43:36.000|2020-09-28 16:43:36.000|0||1|
|70038|2020-09-28 16:43:36.000|2020-09-28 16:43:36.000|0||1|
|70018|2020-09-28 16:43:36.000|2020-09-28 16:43:36.000|0||1|
|70055|2020-09-28 16:43:36.000|2020-09-28 16:43:36.000|0||1|

Newly created records have an `EndDatePrecision` that aligns with the selection made on the form.
Old records have an `EndDatePrecision` that is always set to `1`.

**Comment by emenslin** [comment]
Cannot reproduce
