### ISSUE TITLE
Record set created from a fictional record set does not request the user to make a title

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4002]
<img width="754" alt="image" src="https://github.com/specify/specify7/assets/37256050/9b8e5bc8-32aa-44c4-9546-8038bd3da080">

**Comment by realVinayak** [comment]
also doesn't respect base tables

**Comment by grantfitzsimmons** [comment]
>also doesn't respect base tables

This seems like a bigger issue that should be written up

**Comment by emenslin** [comment]
Fixed
