### ISSUE TITLE
Counts are ambiguous in delete blockers and agent merging references

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4005]
**Describe the bug**
Counts shown in the deletion blocker dialog and agent merging reference section do not show what the references refer to.

**To Reproduce**
1. Go to an agent with many references (https://dbfordocskufish-v79-dev.test.specifysystems.org/specify/view/agent/1514/)
2. Try to delete the agent
3. See issue

**Screenshots**
<img width="484" alt="image" src="https://github.com/specify/specify7/assets/37256050/09b123e1-bbf3-4053-ac03-0eab4c2905de">

**Expected behavior**
Instead of showing **Collection Object** 4 times with indiscernible counts, it should show what the counts are for:
<img width="642" alt="image" src="https://github.com/specify/specify7/assets/37256050/df5439b9-4b12-4625-bea5-cf6d1fac79a5">

`v7.9-dev`, KU Fish database copy

**Comment by realVinayak** [comment]
I'm not sure if that'd be clear to the user, or more confusing. I've implemented the described solution in https://github.com/specify/specify7/pull/4008. I still think it is unclear (and confusing) to the user. Although, the previous method in production was not much better, and just showed one relationship LOL. So, maybe this is fine.
