### ISSUE TITLE
Show record identifier in the browser tab

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4010]
<img width="448" alt="image" src="https://github.com/specify/specify7/assets/37256050/dd034e9d-d578-4e68-b6e2-d4857703ebe8">

It can be difficult to determine my location for certain things because the record identifier is not displayed in the browser tab or history.

<img width="323" alt="image" src="https://github.com/specify/specify7/assets/37256050/0bd412fa-97d2-4b42-9324-a7f7fc92ff26">

**Comment by CarolineDenis** [comment]
@grantfitzsimmons , is this fixed by https://github.com/specify/specify7/issues/4263

**Comment by emenslin** [comment]
Fixed in edge and xml
<img width="458" alt="Screenshot 2024-01-04 141328" src="https://github.com/specify/specify7/assets/150940840/b5287d01-af85-4d99-834b-49978ecbb887">
