### ISSUE TITLE
There are some missing data entry forms 

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify7#402]
I noticed that there are no data entry forms for taxon, geography, storage, geological time period under the "data entry" tab. When I click on any of these tabs under "data entry" it returns a blank page. However, when editing in a tree, the form shows up.

**Comment by yvonneekanim** [comment]
This only happens in the internal version

**Comment by loveablelobster** [comment]
We are having the opposite problem on our production Specify 7.3.1, trying to add e.g. a new taxon via the tree (contextual menu 'add child' item), we get a blank pop-up without data entry form:

<img width="647" alt="Screen Shot 2020-03-17 at 12 56 48" src="https://user-images.githubusercontent.com/6605039/76854440-58382100-684f-11ea-96fb-95e77c6d9f64.png">

**Comment by benanhalt** [comment]
I'm not seeing either of these problems currently. I'm guess the first case was some transient issue.

@loveablelobster I suggest looking in the browser developer tools console to see if there are any errors. That would help to diagnose the problem.

**Comment by loveablelobster** [comment]
There are only two errors, the first one might point to a hickup in the viewdef


<img width="1302" alt="Screen Shot 2020" src="https://user-images.githubusercontent.com/6605039/76871041-deae2c00-686a-11ea-9099-758dcfdb041c.png">

**Comment by benanhalt** [comment]
I think the second is what is causing it not to work, but the first might be related. Possibly the weblink button element in the form is missing a Specify field name. Can you send the form definitions?

**Comment by benanhalt** [comment]
Adding a ```name``` attribute to said element in the form fixed the problem for me. Waiting for confirmation from @loveablelobster.

**Comment by loveablelobster** [comment]
confirmed!
