### ISSUE TITLE
Permission policy selection list incorrectly disables rows

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4027]
**Describe the bug**

From Robyn at RBGE:

> I’ve taken a look at the role and it looks like I already have added Geography, in that I can’t select it from the list of tables:
> 
>  
> ![image](https://github.com/specify/specify7/assets/135047322/fcba61c5-cbd1-4a93-8593-1ec3e22d489d)
>  
> 
> However when I look through all of the selected permissions I can’t see Geography in the list.

---

I am able to recreate this with the policy-creating interface in the other areas of Security & Accounts too. 

For now, I found a workaround that looks like this: 

https://github.com/specify/specify7/assets/135047322/3b49fda0-d853-45dd-b9ec-fe8e0c6a4859

You select another table from the list first, reopen the list, and then all the tables will become available to add. 

I believe this is another bug that should be fixed eventually since it allows you to add policies that already exist.

**Comment by emenslin** [comment]
Fixed
