### ISSUE TITLE
Add the ability to customize the Loan creation dialog fields

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4028]
> When selecting preparations for loan, we need to see more fields than just the preptype and count.
> 
> <img width="592" alt="Screenshot 2023-09-19 at 9 43 49 PM" src="https://github.com/specify/specify7/assets/37256050/c846b7db-bc1d-4f70-ba23-b27aefaadf57">

<img width="941" alt="image" src="https://github.com/specify/specify7/assets/37256050/0c231a01-9bce-4a2f-8138-26b3513bec0d">

> We'd like to add the text1 field from the preparation table as that describes the type of bone (or tissue or whatever).

**Requested By:** Jon Fong at California Academy of Sciences

**Comment by grantfitzsimmons** [comment]
**Requested By:** CSIRO

![image](https://github.com/specify/specify7/assets/37256050/8f2524da-3dc6-4f15-86c0-e3132ed53d01)

**Comment by maxxxxxdlp** [comment]
Duplicate of https://github.com/specify/specify7/issues/1200? If so, merge one of these

**Comment by jfong** [comment]
Yes, this is a duplicate of #1200, so these can be merged. Thanks.

**Comment by grantfitzsimmons** [comment]
Duplicate of #1200
