### ISSUE TITLE
Adding a new line to a simple query does not auto-scroll to the new line

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4038]
> https://github.com/specify/specify7/assets/37256050/b8f9c12d-67c8-477f-9829-8d2ae22de7ee
>
> see video: I though this was a bug until I realized it was adding fields at the bottom (should at least scroll down to show newly added field)

https://github.com/specify/specify7/assets/37256050/666a84e2-bb7c-49a8-b201-f08c77e2c266

`v7.9-dev`

**Reported By:** @maxxxxxdlp

**Comment by CarolineDenis** [comment]
Found: 
When clicking on a new field in the field mapper, the code scrollIntoView to the <li> div but in case of basic view, the <li> has the className 'contents' which prevents the expected scroll behavior.

**Comment by maxxxxxdlp** [comment]
good job debugging that
