### ISSUE TITLE
Bulk move preparation locations in the storage tree

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4042]
After our discussion, we would need to create a new function for the Storage tree that allows you to change the preparation's storage locations from one node to another.

<img width="1244" alt="image" src="https://github.com/specify/specify7/assets/37256050/b1b031db-f8c6-48eb-a65b-ef347630088e">

**Functionality:**
1. Select a storage node that contains 1 or more preparations
2. Click "Move Items" (I would love the <img width="20" alt="image" src="https://github.com/specify/specify7/assets/37256050/a9e54476-3ade-45bd-adca-5ff821f891d6"> `Truck` heroicon)
3. Select the new location to move the items to
4. Click "Move items from {Current Location} here" in the toolbar
    <img width="1245" alt="image" src="https://github.com/specify/specify7/assets/37256050/18b5531e-add7-4179-bbcf-aa5d8b5e69bd">
5. Items are moved!

Both storage locations should still exist at the end of this interaction, just the preparations that were previously pointing to the first location should now point to the new one.

---

Add a feature where you can move all items in one storage location to another.

**Use Case:**
- Box has 81 positions.
- A sample can be put in one position.
- It would be nice to move that preparation to another position in another box easily.

**Requested By:** KU Mammals

**Comment by grantfitzsimmons** [comment]
This has been discussed much more in-depth in our GeoSpecify discussions.

**Comment by CarolineDenis** [comment]
NOTES: 
- See how we do for merge has we update the det of a CO
