### ISSUE TITLE
Tests failing from Weblate validation issue

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4045]
`Weblate config for "merging" component for "addons" setting does not match what is expected.`

**Expected:** 
```
{"weblate.autotranslate.autotranslate":{"mode":"fuzzy","filter_type":"todo","auto_source":"mt","component":null,"engines":["google-translate"],"threshold":20},"weblate.cleanup.generic":{}}
```

**Received:** 
```
{"weblate.autotranslate.autotranslate":{"mode":"fuzzy","engines":["google-translate"],"component":null,"threshold":20,"auto_source":"mt","filter_type":"todo"},"weblate.cleanup.generic":{}}
```

https://github.com/specify/specify7/actions/runs/6303520378/job/17124866948

**Comment by maxxxxxdlp** [comment]
When it creates a new component (merging in this case), I believe it was supposed to configure it correctly to.

The matching configuration check is there to prevent against manual changes getting out of sync (it enforced that all components have same settings, and if you want to change settings, you have to edit the test first)

**Comment by maxxxxxdlp** [comment]
oh I see, looks like their API changed the sort order
