### ISSUE TITLE
Expand merging table support

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4046]
- [ ] Locality
- [ ] Paleo Context
- [ ] Collecting Event

and more.

We should do this once `xml-editor` is merged.

**Comment by grantfitzsimmons** [comment]
Paleo Context

**Requested By:** Calvert Marine Museum

**Comment by grantfitzsimmons** [comment]
@CarolineDenis This would be great for our data quality workshop we're hosting with iDigBio (Data Quality Toolkit 2024). It would address a number of issues and help reduce duplicate localities, events, objects, etc. It looks like this would be a simple change for the devs and mostly work for the testers as previously discussed. Maybe this can be included by the end of March.

**Comment by CarolineDenis** [comment]
Reference pr: https://github.com/specify/specify7/pull/3825/files
