### ISSUE TITLE
Update heroicons in various dialog headers

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4055]
**Choose Collection:**
![Screenshot 2023-09-29 at 10 35 10 AM](https://github.com/specify/specify7/assets/135047322/5116796b-e3dd-4e74-ac33-cc7cada1f906)
Add Heroicon: Archive

**Notifications:**
![Screenshot 2023-09-29 at 10 37 01 AM](https://github.com/specify/specify7/assets/135047322/4d636c21-9025-466e-9dc4-a145429646e1)
New Heroicon: Bell

**Search:**
![Screenshot 2023-09-29 at 10 38 40 AM](https://github.com/specify/specify7/assets/135047322/60868e73-9a48-465b-8fd9-9884edd39145)
New Heroicon: Search

**QCBX search:**
![Screenshot 2023-09-29 at 10 47 40 AM](https://github.com/specify/specify7/assets/135047322/0d4d2e7b-b751-4904-bf98-3424fd5afc36)
New Heroicon: Search

**Embedded Query Builder:**
![Screenshot 2023-09-29 at 10 39 07 AM](https://github.com/specify/specify7/assets/135047322/95142a7b-ae3a-481f-aa09-25c16ceef17e)
New Heroicon: Document Search

**Comment by carlosmbe** [comment]
Should Be Fixed in #4098
