### ISSUE TITLE
Some virtual fields are not queryable 

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4056]
This includes `isOnLoan` and `actualCountAmt`

> The "Is on Loan" indicator that you can see in the preparation section of a form is not currently a field option in the query builder:
>
>![image](https://github.com/specify/specify7/assets/37256050/f5ba86f1-47f0-4cf8-b1c8-d07fb96e51a5)

**Requested By:** Dan Baker at CSIRO ([Asana](https://app.asana.com/0/1201972579963460/1205536478752069/f))

**Comment by maxxxxxdlp** [comment]
Duplicate of #2359
