### ISSUE TITLE
Usernames can be created without linking it to an agent in the agent table 

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify7#406]
It appears that a username can be created without linking it to an agent in the agent table i.e. it is left up to the user to make sure that they link it as a secondary step.  If this is not done then no agent is filled in for modified by or created by fields or any of the default cataloged by fields which can be problematic.

**Comment by maxxxxxdlp** [comment]
Fixed in 7f4fb84a and b2c6e051
