### ISSUE TITLE
Add record merging permission as a policy

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4063]
> Is it possible to set permissions so that certain users are prevented from using the merging tool, while retaining full access to the agents table?
> 
> As admin, it would be nice to be able to easily control it via the tool dropdown.

The issue is just because someone has permission to read, create, and update all tables **record by record** they shouldn't necessarily have the ability to perform bulk updates across the database.

There should be an independent permission for merging in the tool menu or query builder

![image](https://github.com/specify/specify7/assets/37256050/a787b60c-92e6-4fd7-a3dc-03675bf43654)

**Requested By:** Cris at Gothenburg museum of natural history

**Comment by realVinayak** [comment]
Not needed. Already implemented

![image](https://github.com/specify/specify7/assets/61122018/b66c7dac-3c61-4e9a-985c-6d69fe50361c)

But a small bug here
https://github.com/specify/specify7/blob/b63632a7eb9d247b879023d7e19ca4fba07a567c/specifyweb/frontend/js_src/lib/components/QueryBuilder/Results.tsx#L218
Should include delete too (which is what meta dialog checks for)
From a branch: https://github.com/specify/specify7/blob/cdef0a7cd22eac75f88b3f2f907b5228f2f2548f/specifyweb/frontend/js_src/lib/components/FormMeta/index.tsx#L176-L177

**Comment by grantfitzsimmons** [comment]
>Not needed. Already implemented

Disagree, no user would ever find this and find it to be intuitive.

**Comment by realVinayak** [comment]
Aren't all permissions here? That should be part of the documentation. Why is this more harder to find that csv permission?

**Comment by realVinayak** [comment]
Should be part of record, though. Not query builder. Rename replace to merge?

**Comment by maxxxxxdlp** [comment]
Note, the name is coming from back-end, so has to be changed there

**Comment by melton-jason** [comment]
What is the purpose for distinguishing two separate permissions for this feature? (`update` and `delete`)
Should these not be handled by the table permissions which are being updated/deleted and instead we have a single `/record/merge/` policy? 

Or should it be the case that all record updates while merging are handled by the /record/merge/ update permissions and all record deletions be handled by /record/merge/ delete? Thus even if the user would not have permission to update a table, they still could if it were through record merging?
(Though this seems somewhat redundant as the user can simply make any requested changes to the 'canonical' merged record)

Currently there is not much point to two separate permissions: 

The frontend only checks if the user has `update` permissions on both the table and record/replace and then shows the record merging button in the QueryBuilder:

https://github.com/specify/specify7/blob/e2d245febde1791a82f3c9ef421fbc761a422fd5/specifyweb/frontend/js_src/lib/components/QueryBuilder/Results.tsx#L216-L217

The backend only checks if the user has _both_ record replace permissions at the very start of the merging process (yes, this is probably a bug which can throw an error if the user has update permissions, but not delete):

https://github.com/specify/specify7/blob/e2d245febde1791a82f3c9ef421fbc761a422fd5/specifyweb/specify/views.py#L475

**Comment by melton-jason** [comment]
> Should be part of record, though. Not query builder. Rename replace to merge?

While I agree with this decision conceptually, I do think it is perhaps a little too unintuitive for the common user and even having it in the QueryBuilder section (in a separate subsection from `Query`)  would probably be more useful! 
The QueryBuilder would probably be the first place one looks for this permission, as there is no 'primary' section which includes 'Merge' and they will almost always use the QueryBuilder to merge records (I doubt anyone is directly using the URL to navigate to the dialog). 
I think an important question to have an answer to is whether most Collection Managers (assuming they are the ones who dole out permissions) are familiar with the concept of a 'Record' in the first place and can readily make the necessary association. Even most managers are probably not SQL gurus or experienced with the terminology! :sweat_smile: 

However, renaming the policy to `/record/merge/` and writing documentation on the Speciforum may alleviate most concerns (although still not ideal as most would need to blindly check each 'primary' category of permission until they reach /merge/, or spend time looking to external documentation) .

**Comment by maxpatiiuk** [comment]
1. I agree that it's redundant to have both update and delete
2. I see value in collection admins being able to allow someone to edit a record, without trusting them to bulk-edit those records (which is what record merging is essentially doing). Following this logic, to allow the user to merge Agents, they should have Agent delete, Agent update permissions and /record/replace permission. Is this what front-end and back-end are currently enforcing? if not, we should consider changing it
