### ISSUE TITLE
Query builder Browse in Forms results numbering inconsistent

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#4065]
**Describe the bug**
The record numbering in the results from a query builder query when viewed in Browse In Forms is inconsistent

**To Reproduce**
1. Use the "CE observation records" query in the voucher collection of the KU_Fish_Tissue database when logged in as abentley
2. Run the query and then select "browse in Forms" from the header menu bar
3. Try and navigate to record 130 by typing in the number in the numbering toggle in the top right.  You will get a never-ending spinning orange wheel and never be directed to the correct record.
4. Re-run the query and now use the slider to bring up more records than are on the first page of the paginated result set.  Then select Browse in Forms and you will be directed to the following record:

![image](https://github.com/specify/specify7/assets/7501989/1f549f98-ca56-417d-9e01-e5d0c1064f1e)

However, this is not the 130th record

6. If you use the arrow keys to navigate one by one to the 130th record you get this record:

![image](https://github.com/specify/specify7/assets/7501989/b2094eca-c4a9-4cd8-a318-ea2e49b3de1f)

**Expected behavior**
Numbering should be consistent no matter which method is used to navigate to through the records while selecting a number in the top right should work without having to scroll.

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Specify 7 Version: 7.9

**Database Name:** KU_Fish_Tissue

**Reported By**
KUBI

**Comment by CarolineDenis** [comment]
Issue: 
The results fetched when loading the browse in form in the example below contain the first 120 (multiple of 40) first records. 
The index entered in the slider box is 150. 
When the function onSlide() is called in the ToForm.tsx we do results[index] which results in undefined and therefore handleFetchMore?(index) is not called as it should.
