### ISSUE TITLE
Aspect ratio of forms changes during record navigation in query builder

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#4066]
**Describe the bug**
The aspect ration of forms changes when navigating between records in the query builder when using Browse in Forms

**To Reproduce**
1. Go to CE Observation records query in KU_Fish_Tissue database when logged in as abentley
2. Run the query and select Browse in Forms option from menu
3. Using arrow keys, navigate between records
4. Note how the aspect ratio of the forms changes and the arrows jump around sometimes making you select the wrong button if navigating quickly between records

**Expected behavior**
Aspect ratio should remain static

**Screenshots**

https://github.com/specify/specify7/assets/7501989/43cb7af3-7cc9-4d66-a1db-01e7c39b92d1

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Specify 7 Version: 7.9

**Database Name:** If applicable

KU_Fish_Tissue

**Reported By**
KUBI

**Additional context**
Database name or any other context about the problem here.

**Comment by grantfitzsimmons** [comment]
This should be fixed in 7.9.1 (https://github.com/specify/specify7/pull/3927)
