### ISSUE TITLE
`TypeError: value.trim is not a function` when uploading a spreadsheet in the WorkBench

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4067]
<img width="797" alt="image" src="https://github.com/specify/specify7/assets/37256050/66d0e183-57a0-4a1b-b1da-cd7779a003d6">

**Steps to Recreate:**
1. Upload this spreadsheet as a new data set for the WorkBench
2. See error

[**Link to Spreadsheet**](https://docs.google.com/spreadsheets/d/1vQpWDXa1PPWABGqX3tzJlj5IJELkCszD/edit?usp=drive_link&ouid=115297369899192276851&rtpof=true&sd=true) 🖨️ 

**Crash report from `localhost`:**
[Specify 7 Crash Report - 2023-10-04T21 14 44.858Z.txt](https://github.com/specify/specify7/files/12809102/Specify.7.Crash.Report.-.2023-10-04T21.14.44.858Z.txt)

This crash happens on any database, not specific to Edinburgh when using this spreadsheet.
Firefox, both on `v7.9.0` and `v7.8.13`. Seems to be specific to this spreadsheet.

Creating a new spreadsheet with the same contents still results in a crash.

**Reported By:** RBGE

**Comment by CarolineDenis** [comment]
https://github.com/specify/specify7/blob/ef5eacdd19de2144271f03957f445f0e223ce3d7/specifyweb/frontend/js_src/lib/components/WbImport/helpers.ts#L68
