### ISSUE TITLE
Improve the navigation menu's simple search dialog

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4077]
`v7.9` **vs** `v7.9.1`

<img width="1906" alt="Screenshot 2023-10-06 at 11 29 19 AM" src="https://github.com/specify/specify7/assets/135047322/13b28a56-3c92-4588-82ee-0a1eef7b882f">

- Add magnifying glass search icon to top left
- Configure Search button to be blue Info button

**Comment by carlosmbe** [comment]
First half is part of of #4055 and fixed in #4098. Changing the colour will be done in different branch. 🖖🏾<- This is an easter egg if Grant ever looks at this

**Comment by grantfitzsimmons** [comment]
>🖖🏾<- This is an easter egg if Grant ever looks at this

🖖
