### ISSUE TITLE
Adding Loan Preparations does not show "add items" dialog in default forms

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4078]
When using the default Loan form (defined in the `common.views.xml` file), it renders the Loan Preparations in a "table" view rather than a grid. When in this view, the **add** button does not show the 'add items' dialog that shows when the type is not specified.

---

Form definition that **does** offer the ability to add preps from a record set or list of identifiers: 

https://github.com/specify/specify7/assets/37256050/2fac02be-8a3f-4aa1-8a06-f3bfa3eca015

```xml
                <row>
                     <cell type="subview" viewname="LoanItems" id="LoanItems" name="loanPreparations" defaulttype="table" colspan="15" rows="4"/>
                </row>
```

---

Form definition that **does not** offer the ability to add preps from a record set or list of identifiers: 

https://github.com/specify/specify6/blob/945d28f00288d2d64979848fb2fb63fda34bdd1b/config/common/common.views.xml#L5712C17-L5714

https://github.com/specify/specify7/assets/37256050/cf9f3fca-1f1d-46f1-878f-6442bb2c8aae

```xml
                <row>
                    <cell type="subview" viewname="LoanItems" id="10" name="loanPreparations" colspan="17" rows="4"/>
                </row>
```

---

`v7.9.1-prerelease` and `v7.9.0`
Arc browser, macOS Sonoma

**Reported By:** @bronwyncombs

**Comment by CarolineDenis** [comment]
@grantfitzsimmons or @bronwyncombs, would you have the name of a db and collection  that you know has the pop up dialog when clicking on + to add loan preparation?

**Comment by grantfitzsimmons** [comment]
> @grantfitzsimmons or @bronwyncombs, would you have the name of a db and collection that you know has the pop up dialog when clicking on + to add loan preparation?

You just need to change the definition to look like this:

```xml
                <row>
                     <cell type="subview" viewname="LoanItems" id="LoanItems" name="loanPreparations" defaulttype="table" colspan="15" rows="4"/>
                </row>
```

**Comment by grantfitzsimmons** [comment]
This was encountered and reported by The University of Michigan today
