### ISSUE TITLE
Move record attachment gallery view button in header

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4081]
The paginator buttons should be on the far right of the dialog. Moving the gallery button to the other side is more consistent with the other areas. 

<img width="725" alt="Screenshot 2023-10-06 at 1 05 00 PM" src="https://github.com/specify/specify7/assets/135047322/fc83a43b-96ad-43bc-bb49-560984df1be3">

Reported by: @grantfitzsimmons

**Comment by grantfitzsimmons** [comment]
beautiful drawing @bronwyncombs
