### ISSUE TITLE
Deleting last record in query results causes visual glitch 

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4084]
**Describe the bug**
Deleting the last record in the list of query results causes the page to glitch pretty badly after returning to query results. 

**To Reproduce**

1. Query on loans (because no delete blocker and usually not too many results)
2. Delete the last result in the list 
3. See error

**Screenshots**

### all results in browse in forms:

https://github.com/specify/specify7/assets/135047322/aa4f98cc-2ce8-49f9-afe2-b9d88c0ce6cb

### just last result in browse in forms:

https://github.com/specify/specify7/assets/135047322/f6623121-f41b-4a87-af93-b31c4ecd6131

**Desktop:**
 - OS: macOS Sonoma
 - Browser: Chrome
 - Specify 7 Version: v7.9

**Database Name:** `lsumz_fishes_1_6_23`

**Additional Context**
- have recreated with query on shipments table 
- couldn't recreate with loans on fwri -- not long enough list of results?

**Comment by emenslin** [comment]
Fixed
