### ISSUE TITLE
`xml-editor`: Form editing still caching the old form definitions for other tables

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4104]
<img width="1451" alt="image" src="https://github.com/specify/specify7/assets/37256050/337824e3-0999-4112-9b2e-af7b12540bb2">

In this instance, I edited the `Determiner` form so that the remarks field was removed.
When I went to then edit the `Determination` form, I saw the old form.
This was only remedied after I cleared my cache, which kind of defeats the whole "what you see is what you get" idea.

**Comment by maxxxxxdlp** [comment]
For developers debugging this:
The code responsible for clearing form cache is here:
https://github.com/specify/specify7/blob/0fdc86eaa4598135f6240c9b81f2bdf92af45cf9/specifyweb/frontend/js_src/lib/components/FormEditor/index.tsx#L65-L71
