### ISSUE TITLE
Multiple preparations cannot be checked at once in loan prep form

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify7#411]
Multiple preparations cannot be checked at once in loan prep form although the preparations that were previously checked are applied to the loan.

![loan prep](https://user-images.githubusercontent.com/28809154/27044986-287d5be8-4f65-11e7-942c-56fb7a558897.png)
![loan prep 2](https://user-images.githubusercontent.com/28809154/27044995-2bf35b24-4f65-11e7-8835-ed724d9c2aa7.png)

**Comment by timo11** [comment]
unable to duplicate. The select/deselect checkbox works correctly for me.
