### ISSUE TITLE
Borrow Save Button Not Turning Yellow When You Change Date

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#4121]
**Describe the bug**
Even though you can save. The button is not getting filled to illustrate that it's now interactive.

**To Reproduce**
1. Go to Interactions
2. Click on Borrow
3. Create a borrow
4. Save
5. Change Borrow Date
6. See error

**Expected behavior**
It fills up.

**Beautiful Screen Recording**

https://github.com/specify/specify7/assets/53784701/f79bef30-73b1-435f-abe3-d765f67023f3

**Desktop:**
 - OS: Mac Os X
 - Browser: Chrome
 - Specify 7 Version: 7.9 and 7.9.1

**Comment by CarolineDenis** [comment]
fixed in xml-branch
