### ISSUE TITLE
Stats Page - Download As TSV still produces 2 copies

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#4123]
**Describe the bug**
Title. When I download the TSV of stats page

**To Reproduce**
1. Go to Stats Page
2. Click on Download as TSV
3. See error

**Expected behavior**
Download only one copy. 
Theoretically speaking this should be easy as we made a PR addressing this issue around the 7.8.8 -> 7.8.13 era

**Beautiful Screen Recording**

https://github.com/specify/specify7/assets/53784701/8f220db7-0899-462d-a398-c20e72b49317

**Desktop:**
 - OS: Mac Os X
 - Browser: Chrome
 - Specify 7 Version: 7.9

**Comment by maxxxxxdlp** [comment]
I will merge this with https://github.com/specify/specify7/issues/2638

**Comment by carlosmbe** [comment]
Thanks @maxxxxxdlp. Greatly appreciate it. UwU
