### ISSUE TITLE
`xml-editor`: Add checkbox to enable/disable localized field labels while editing forms

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4127]
<img width="624" alt="image" src="https://github.com/specify/specify7/assets/37256050/6c00672a-c890-4c7a-946c-6ac8c3775866">

This would be useful to make it clear what fields are being modified. Ideally, this would not require a full page reload since it should be toggle-able.

**Comment by maxxxxxdlp** [comment]
> I would argue that this should be renamed "Use Schema Config Labels" instead of "Use Localized Field Labels" in both this place and in the Form Meta Menu

I would have assumed "Use Localized Field Labels" would be clearer for less technical user, but I suppose this feature would only be used by more technical users.
Don't think it matters much either way so go with whatever you want

**Comment by grantfitzsimmons** [comment]
I thought some more about this...

Maybe making it match the schema configuration makes the most sense?
My new favorite is this:
* Use Field Captions
