### ISSUE TITLE
Implement Show Loans button

### ISSUE THREAD

**Issue by timo11** [specify/specify7#413]

**Comment by timo11** [comment]
Clicking the button will show open loans, resolved loans, gifts and exchanges associated with the preparation.
Clicking on a transaction number opens the associated transaction.

Existing forms may need to change the label for the button from "SHOW_LOANS" to 'Show Transactions' or something.

It may be preferable to disable the button when the form is being edited, or to open associated transactions in a new browser tab.

**Comment by yvonneekanim** [comment]
"Show Loans" button works as described.
