### ISSUE TITLE
`xml-editor`: Preparation form not displaying in the visual editor

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4130]
<img width="1913" alt="image" src="https://github.com/specify/specify7/assets/37256050/34b8c45f-541f-49d4-9435-7a426aaab4f4">

https://nbm-mnb.specifycloud.org/specify/resources/view-set/2/Preparation/Preparation

https://nbmmnb5523-xml-editor.test.specifysystems.org/specify/resources/view-set/2/Preparation/Preparation

`xml-editor`, macOS, Chrome, `nbm_mnb_5_5_23` on test panel

**Comment by CarolineDenis** [comment]
NOTES: 
- viewdef is created when creating a new resource by ex PreparationFormView but when looking in the complete xml file the name attributed to this new view def is incorrect. (it's "preparation")
- there is a loop of calls due to one view def calling itself.

**Comment by grantfitzsimmons** [comment]
More context:

Here is the excerpt that was causing the issue:
```xml
<viewdef type="form" name="Preparation" class="edu.ku.brc.specify.datamodel.Preparation" gettable="edu.ku.brc.af.ui.forms.DataGetterForObj" settable="edu.ku.brc.af.ui.forms.DataSetterForObj" useresourcelabels="true">
	<desc>Preparation for Collection Object form.</desc>
	<enableRules/>
	<columnDef>100px,2px,195px,5px,91px,2px,60px,5px,83px,2px,60px,5px,85px,2px,123px,2px,70px,p:g</columnDef>
	<columnDef os="lnx">115px,2px,200px,5px,110px,2px,67px,5px,82px,2px,67px,5px,100px,2px,126px,2px,75px,p:g</columnDef>
	<columnDef os="mac">130px,2px,215px,5px,110px,2px,80px,5px,93px,2px,80px,5px,105px,2px,174px,2px,70px,p:g</columnDef>
	<columnDef os="exp">p,2px,p:g(2),5px:g,p,2px,p:g,5px:g,p,2px,p:g,5px:g,p,2px,p:g,10px,p:g</columnDef>
	<rowDef auto="true" cell="p" sep="2dlu"/>
	<definition>PreparationFormView</definition>
...
```

Notice the piece at the bottom:
```xml
<definition>PreparationFormView</definition>
```

This linked to the `PreparationFormView` definition.
Unfortunately, the loop was caused because the `view` section for it was configured like this:

```xml
<view name="PreparationFormView" class="edu.ku.brc.specify.datamodel.Preparation" busrules="edu.ku.brc.specify.datamodel.busrules.PreparationBusRules" resourcelabels="false">
	<desc>Subform within the Preparation form.</desc>
	<altviews>
		<altview name="PreparationFormView Table View" viewdef="Preparation Table" mode="view"/>
		<altview name="PreparationFormView Table Edit" viewdef="Preparation Table" mode="edit"/>
		<altview name="PreparationFormView View" viewdef="Preparation" mode="view"/>
		<altview name="PreparationFormView Edit" viewdef="Preparation" mode="edit" default="true"/>
	</altviews>
</view>
```

This led to a **loop** as the `viewdef` that was being referenced was the original `Preparation` form itself! This was due to a misconfiguration in the form definition.

**Comment by grantfitzsimmons** [comment]
Here's the current issue:
Because the definition points to `PreparationFormView` when viewed as a form, it shows a loading page:
If you remove the `definition`, it will display correctly.

```xml
<definition>PreparationFormView</definition>
```

https://github.com/specify/specify7/assets/37256050/a944e216-5b4b-4ac9-8fc5-62dcc0828080

This form definition exists only to control **how it displays in grid view**. Since it can't display the form in grid view, it can't display at all.

**Comment by CarolineDenis** [comment]
Need to be tested once we have https://github.com/specify/specify7/issues/4134 done
