### ISSUE TITLE
Make Specify Network icons bigger

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4140]
> In a future release could we make the Specify Network icons bigger to roughly correspond to the size of the buttons on the bottom of the CO form?  They deserve more visibility and prominence.  They are so cool!!! 

**Requested By:** @beach53

**Comment by CarolineDenis** [comment]
![Image](https://github.com/specify/specify7/assets/108160931/af67e26c-502f-4fc4-a626-bca5896da946)

**Comment by grantfitzsimmons** [comment]
@CarolineDenis I'm not a fan of the aesthetic when the icons are larger than the meta menu and the main record's table icon. Do you think we can just close this issue? I think they are as large as they need to be already.

What do you think?

**Comment by CarolineDenis** [comment]
@grantfitzsimmons, I totally agree with you
