### ISSUE TITLE
Forms for *attachment tables are ignored.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#415]
The form definitions for collectionobjectattachment etc tables are ignored because Specify 7 has to use a different plugin to display the attachment. There needs to be some way to customize these forms, though, so that fields can be added. Need to determine if it is possible to use the Specify 6 definition somehow, or introduce a way to define a special forms for 7 that are still customizable.

**Comment by hexx870206helen** [comment]
Hey benanhalt,

Does that mean we can not customize the attachment forms, such as collection object attachment form etc  in Specify 7 currently? 

Kind Regards,
Helen

**Comment by benanhalt** [comment]
@hexx870206helen, yes. I'm afraid that is currently the situation.

**Comment by tlammer** [comment]
request for this feature added by Gothenburg

**Comment by maxxxxxdlp** [comment]
Fixed in 7b1164e3
