### ISSUE TITLE
New taxa cannot be added from taxon tree

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify7#416]
When adding a child node from a parent node on a tree (taxon, geography,etc) an error occurs if the rank that is suggested by Specify is not changed.

**Comment by benanhalt** [comment]
This is related to #374.

Fixed in c4e73586cc0df6749af43c8a53ac7f7af9203b26

**Comment by yvonneekanim** [comment]
New nodes can now be added whether rank is changed or not.

**Comment by loveablelobster** [comment]
We have a similar issue, where nodes can not be added to the tree; the error we get (as of version 7.3.0) is 'An unexpected error has occured during communication with the server'
