### ISSUE TITLE
Some invalid URLs don't show 404 page - show blank page instead

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#4161]
Go to https://sp7demofish.specifycloud.org/specify/view/Accession

See blank page - expected 404 error instead

See console:

![Screenshot 2023-10-25 at 19 19 32](https://github.com/specify/specify7/assets/40512816/89343b7a-1f7c-44d4-8731-f963445b07b7)

The "Not allowed to load local resource: chrome://branding/content/about-logo@2x.png" error is weird 🤔 (though I also see it at https://sp7demofish.specifycloud.org/specify/)

Would be good to audit if there are any other places where 404 page is not shown (this type of bug is specific to each place where it happens - likely no easy way to fix it once and for all)

**Comment by emenslin** [comment]
Cannot recreate
