### ISSUE TITLE
`xml-editor`: Projects or many-to-many items on the form should be a warning, not an error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4167]
<img width="1574" alt="image" src="https://github.com/specify/specify7/assets/37256050/c1731ef9-222a-43e9-819e-a2c75c43a49f">

Projects not being supported should not prevent saving.

**Comment by maxxxxxdlp** [comment]
Good point. Things that are (hopefully) temporary unavailable but were available in sp6 shouldn't be forbidden strictly
sorry for the oversight
