### ISSUE TITLE
Warning text for "no restrictions mode" in the query builder is misleading

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4172]
If you want to enable this in the UI at all times, you can check "No restrictions mode" in User Preferences under Query Builder. The warning here is misleading as it is reused from the "Data Mapper" no restrictions mode, so you can safely ignore it. Building a query should not lead to data loss or database corruption.

<img width="675" alt="image" src="https://github.com/specify/specify7/assets/37256050/3b25afb7-ec0c-4f5d-8543-bb86aca81958">

The reason it is showing this absurd text is because it is reusing the warning for the no restrictions mode in the WorkBench section:

<img width="680" alt="image" src="https://github.com/specify/specify7/assets/37256050/c4eaaab4-c9c4-4fee-80f7-39f1ad0095a7">

In that case, it is justified.

**Desired Behavior:**

Just remove the warning. There is no value in it, and having a "no restrictions mode" for query builder is not problematic for advanced users.

**Comment by maxxxxxdlp** [comment]
The reason I added it is that in no-restrictions mode you can query system tables
Then, you can open those systems tables using "Browser in Forms"
From there, it's easy to make changes or hit Delete

If No restrictions mode is not enabled, then non-advanced users can't get to those tables (while advanced users can still change the URL to query any table they want)

Though, now that the permission system is here, that is less fo an issue. @grantfitzsimmons if you think it is not useful, then I am ok with removing it
