### ISSUE TITLE
`xml-editor`: Forms from different disciplines shown under the same header when creating new form based on existing one

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4176]
<img width="797" alt="Screenshot 2023-10-31 at 9 11 06 AM" src="https://github.com/specify/specify7/assets/37256050/a4fee168-759b-4364-bad2-59fabd4cedbd">

When creating a new form based on an existing one, all forms are shown under the same discipline even thought they are distinct. This can be seen in the `nbm_mnb` database where the two preparation forms come from Ichthyology and Herpetology, but they are shown under the same header.

**Comment by maxxxxxdlp** [comment]
Good catch

Should probably have `Discipline > Herpetology` and `Discipline -> Fish` headings (just like we have in the `Copy default form` section)

**Comment by CarolineDenis** [comment]
> Good catch
> 
> Should probably have `Discipline > Herpetology` and `Discipline -> Fish` headings (just like we have in the `Copy default form` section)

We are grouping by 'Category' 
In this example the category for both of them is 'Discipline' therefore the category key value is not well set when we create the view sets. Where do we assign this category?
