### ISSUE TITLE
`xml-editor`: Hide default XML forms that users should not use as a base

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4178]
Here is the full current list of forms that users can use as a base for a new form definition:
```
Reptile
Reptile > Manager > Reptile
Fish
Fish > Fishbase
Fish > Manager > Fish
Fish > Guest > Fish
Vertpaleo
Vertpaleo > Manager > Vertpaleo
Vertpaleo > Guest > Vertpaleo
Accessions
Botany
Botany > Manager > Botany
Botany > Guest > Botany
Common
Invertpaleo > Paleo
Invertpaleo > Manager > Paleo
Invertpaleo > Guest > Paleo
Invertebrate
Invertebrate > Manager > Invertebrate
Invertebrate > Guest > Invertebrate
Bird
Bird > Manager > Bird
Bird > Guest > Bird
Insect > Ento
Insect > Manager > Ento
Insect > Guest > Ento
Mammal
Mammal > Manager > Mammal
Mammal > Guest > Mammal
Herpetology
Herpetology > Manager > Herpetology
Herpetology > Guest > Herpetology
Backstop > Editorpanel
Backstop > Global
Backstop > Gbif
Backstop > Preferences
Backstop > Search
Backstop > System
Vascplant
Vascplant > Manager > Vascplant
Vascplant > Manager > Botany
```

We should remove the following (at least):
```
Fish > Fishbase
Accessions
Backstop > System
Backstop > Editorpanel
Backstop > Gbif
```

**Comment by maxxxxxdlp** [comment]
trying to come up with a generic rule...
exclude all where path has >1 segment and does not include user type? (Manager/Guest/...)

**Comment by maxxxxxdlp** [comment]
Note, it **may** be appropriate to fix this on the back-end (where endpoint returns list of view defs for this view name), rather than on the front-end

**Comment by realVinayak** [comment]
What does `backstop` mean though in Specify6? 

> only include those that have 1 path segment OR includes the user type in the path? (Manager/Guest/...)

Looks like specify6 defines users in `/Specify/config/usertypes.xml`. Are those related to the user type above? In that case, we can read `usertypes.xml` files first and use users from there. Also looks like disciplines get defined too in `/Specify/config/disciplines.xml` file. Can we read disciplines from there? "accessions" discipline was commented out, so maybe we read this file first and then select viewset files?

I don't think relying on "1 path segment" will be enough, we will skip over "Mammal" and others in that case. 

If we know how Sp6 organizes and makes files, that would be the best. But maybe this will work:

> only includes the user type in the path (Manager/Guest/...) or user type gets included in a file in the same directory

For example, 
```
Herpetology
Herpetology > Manager > Herpetology
Herpetology > Guest > Herpetology
```
First `Herpetology` gets included because the second `Herpetology > Manager > Herpetology` is present (which has Manager). 

Accessions do not get included because there is no corresponding `Manager/User` resource.

**Comment by realVinayak** [comment]
See https://github.com/specify/specify7/commit/50f8ff965d5f463445cf75078e994de6877bab3d, for a potential fix. It looks up based on disciplines defined in `disciplines.xml`

At least for me, Specify6 didn't create files for `Accessions`, even though it created directory `Accession`. `Accessions` also happens to be not included in `disciplines.xml`, so maybe Specify6 doesn't create viewset files for disciplines not included?

**Comment by maxpatiiuk** [comment]
> What does backstop mean though in Specify6?

The form system are setup as cascade layers - when resolving the view, it looks at one layer, and if view is not defined there, it looks at a parent and so on (user, user type, collection, ...). Backstop is the absolute top layer


> I don't think relying on "1 path segment" will be enough, we will skip over "Mammal" and others in that case.

Can you clarify this? all of the following would be included:

```yaml
Mammal
Mammal > Manager > Mammal
Mammal > Guest > Mammal
```

because 1st one is just "1 path segment", and the other two have user type in the path

> Looks like specify6 defines users in /Specify/config/usertypes.xml. Are those related to the user type above? In that case, we can read usertypes.xml files first and use users from there. Also looks like disciplines get defined too in /Specify/config/disciplines.xml file. Can we read disciplines from there? "accessions" discipline was commented out, so maybe we read this file first and then select viewset files?

If possible I would suggest avoiding adding reliance on any specify 6 .XML files. I would actually prefer we hardcode the exclude-list than rely on specify 6 files for this one - after all, we are trying to reduce dependence on sp6.
(hard code the exclude list if we can't come up with a generic rule)

all user types are defined in here - https://github.com/specify/specify7/blob/1d6409c522a5ebd60ebb2fa6a30c00e2ac60f6e4/specifyweb/frontend/js_src/lib/components/PickLists/definitions.ts#L55-L60

**Comment by realVinayak** [comment]
> > I don't think relying on "1 path segment" will be enough, we will skip over "Mammal" and others in that case.
> 
> Can you clarify this? all of the following would be included:

My bad, I didn't mean that. What I meant was "Accessions" will be included because of "1 path segment", which Grant says shouldn't be included.

**Comment by maxpatiiuk** [comment]
> My bad, I didn't mean that. What I meant was "Accessions" will be included because of "1 path segment", which Grant says shouldn't be included.

Thanks for clarifying.
I don't think a simple & generic rule can handle all cases perfectly, but this might be good enough, and simple enough.

> We do read discipline in other places on the backend

Thanks for clarifying. I didn't realize that

**Comment by acwhite211** [comment]
I created a PR #4387 that implements the rule to filter out viewsets where the user type is not encompassing or is in a new predefined list FORM_RESOURCE_EXCLUDED_LST.  Let me know if you think this is too restrictive, or if I should add more form xml files to exclude.

In my testing on sp7demofish with user type "Manager", the viewsets api call went from
```json
[
  "herpetology/herpetology.views.xml",
  "herpetology/manager/herpetology.views.xml",
  "herpetology/guest/herpetology.views.xml",
  "insect/ento.views.xml",
  "insect/manager/ento.views.xml",
  "insect/guest/ento.views.xml",
  "reptile/reptile.views.xml",
  "reptile/manager/reptile.views.xml",
  "vascplant/vascplant.views.xml",
  "vascplant/manager/vascplant.views.xml",
  "vascplant/manager/botany.views.xml",
  "mammal/mammal.views.xml",
  "mammal/manager/mammal.views.xml",
  "mammal/guest/mammal.views.xml",
  "accessions/accessions.views.xml",
  "botany/botany.views.xml",
  "botany/manager/botany.views.xml",
  "botany/guest/botany.views.xml",
  "invertpaleo/paleo.views.xml",
  "invertpaleo/manager/paleo.views.xml",
  "invertpaleo/guest/paleo.views.xml",
  "common/common.views.xml",
  "backstop/editorpanel.views.xml",
  "backstop/global.views.xml",
  "backstop/system.views.xml",
  "backstop/gbif.views.xml",
  "backstop/preferences.views.xml",
  "backstop/search.views.xml",
  "vertpaleo/vertpaleo.views.xml",
  "vertpaleo/manager/vertpaleo.views.xml",
  "vertpaleo/guest/vertpaleo.views.xml",
  "fish/fishbase.views.xml",
  "fish/fish.views.xml",
  "fish/manager/fish.views.xml",
  "fish/guest/fish.views.xml",
  "bird/bird.views.xml",
  "bird/manager/bird.views.xml",
  "bird/guest/bird.views.xml",
  "invertebrate/invertebrate.views.xml",
  "invertebrate/manager/invertebrate.views.xml",
  "invertebrate/guest/invertebrate.views.xml"
]
```
down to this
```json
[
  "herpetology/herpetology.views.xml",
  "herpetology/manager/herpetology.views.xml",
  "herpetology/guest/herpetology.views.xml",
  "insect/ento.views.xml",
  "insect/manager/ento.views.xml",
  "insect/guest/ento.views.xml",
  "reptile/reptile.views.xml",
  "reptile/manager/reptile.views.xml",
  "vascplant/vascplant.views.xml",
  "vascplant/manager/vascplant.views.xml",
  "vascplant/manager/botany.views.xml",
  "mammal/mammal.views.xml",
  "mammal/manager/mammal.views.xml",
  "mammal/guest/mammal.views.xml",
  "botany/botany.views.xml",
  "botany/manager/botany.views.xml",
  "botany/guest/botany.views.xml",
  "invertpaleo/paleo.views.xml",
  "invertpaleo/manager/paleo.views.xml",
  "invertpaleo/guest/paleo.views.xml",
  "common/common.views.xml",
  "backstop/global.views.xml",
  "backstop/preferences.views.xml",
  "backstop/search.views.xml",
  "vertpaleo/vertpaleo.views.xml",
  "vertpaleo/manager/vertpaleo.views.xml",
  "vertpaleo/guest/vertpaleo.views.xml",
  "fish/fish.views.xml",
  "fish/manager/fish.views.xml",
  "fish/guest/fish.views.xml",
  "bird/bird.views.xml",
  "bird/manager/bird.views.xml",
  "bird/guest/bird.views.xml",
  "invertebrate/invertebrate.views.xml",
  "invertebrate/manager/invertebrate.views.xml",
  "invertebrate/guest/invertebrate.views.xml"
]
```
and then down to this for the "guest" user type
```json
[
  "herpetology/herpetology.views.xml",
  "herpetology/guest/herpetology.views.xml",
  "insect/ento.views.xml",
  "insect/guest/ento.views.xml",
  "reptile/reptile.views.xml",
  "vascplant/vascplant.views.xml",
  "mammal/mammal.views.xml",
  "mammal/guest/mammal.views.xml",
  "botany/botany.views.xml",
  "botany/guest/botany.views.xml",
  "invertpaleo/paleo.views.xml",
  "invertpaleo/guest/paleo.views.xml",
  "common/common.views.xml",
  "backstop/global.views.xml",
  "backstop/preferences.views.xml",
  "backstop/search.views.xml",
  "vertpaleo/vertpaleo.views.xml",
  "vertpaleo/guest/vertpaleo.views.xml",
  "fish/fish.views.xml",
  "fish/guest/fish.views.xml",
  "bird/bird.views.xml",
  "bird/guest/bird.views.xml",
  "invertebrate/invertebrate.views.xml",
  "invertebrate/guest/invertebrate.views.xml"
]
```
