### ISSUE TITLE
Can't search for ranks below first rank in full name in parent of taxon qrycmbbx

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#418]
In the taxon data entry form, assuming full name includes Family, Genus, and Species, if you try to search for any taxon with rank Genus or below without including the full name ranks above it (i.e. Family), the search will result in no hits. In Specify 6, if you search for a lower full name rank, such as species, it will show up as a result in full name format.

**Comment by timo11** [comment]
For any querycombobox is associated with a tree, a wild card char is now implicitly added before the entered search string.  This might result in slow response times given 7's char by char search strategy.

**Comment by garrettgirard** [comment]
This still appears to be an issue. If you try searching for any Species in KU VP using the querycombobox, they won't appear in the results.

**Comment by garrettgirard** [comment]
Nevermind, it works fine. I was searching for a parent that was already currently at the lowest rank currently available in that tree.
