### ISSUE TITLE
`xml-editor`: Deleting a definition deletes **all** `<viewdef>`s!

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4180]
Deleting a definition deletes **all** `<viewdef>`s!!!

https://github.com/specify/specify7/assets/37256050/705de67e-6b06-4ca6-af79-5b229be8a29f

**Comment by grantfitzsimmons** [comment]
[NBM Fish Views.xml.zip](https://github.com/specify/specify7/files/13221169/NBM.Fish.Views.xml.zip)

**Comment by maxxxxxdlp** [comment]
welp, this is awkard.
could it have something to do with you having two views by the same name?
though the code was supposed to handle that too

The way I remember writing it, is that for each viewdef it will check if any altview in this file references it, and if not, then deletes it.

**Comment by CarolineDenis** [comment]
we should retest this once the unique name and the right viewdef names PRs have been merged
