### ISSUE TITLE
New Collection Relationship Form Missing Left and Right Side Query Comboboxes

### ISSUE THREAD

**Issue by mpitblado** [specify/specify7#4185]
**Describe the bug**
According to the documentation found at https://discourse.specifysoftware.org/t/collection-relationships/182, a new collection object should be able to be added via appending the following to an instance's url `/specify/view/collectionreltype/new/`. The documentation has the following image, indicating what the form is supposed to look like.

![ce100e8fe9c4a7124395b9ce1f4ec99766513f99](https://github.com/specify/specify7/assets/116753126/1b748d81-5b68-4bbf-9ed5-9c69219a308b)

However, upon going to this route, the following form is presented, which appears to be missing the left and ride side query comboboxes. There is a single arrow that demonstrates where the fields should likely be.

![image](https://github.com/specify/specify7/assets/116753126/f1b0ee13-3f8d-4f45-92dd-5a160073f9df)

**To Reproduce**
1. Go to `https://example.com/specify/view/collectionreltype/new/`
2. Observe the form, and how it is not the same as the documentation and not expected.

**Expected behavior**
The form should contain the fields as present in the documentation, or at least the necessary fields to add the collection object relationship (i.e. the left and right joins)

**Screenshots**
See above

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox version 119.0 64 bit
 - Specify 7 Version: 7.9.1

**Database Name:** Tested on both the Beaty Museum Database and Sp7Demofish. Bug is reproducible in each.

**Reported By**
Beaty Biodiversity Museum

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/problem-creating-a-new-collection-relationship-type/1479/3

**Comment by bronwyncombs** [comment]
Duplicate of #4069
