### ISSUE TITLE
`batch-image-upload`: Numeric catalog numbers not named `CatalogNumberNumeric` are not recognized as numeric

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4187]
When the catalog number field is assigned to `CatalogNumberNumeric` in both the `collection` table and in the schema:
![image](https://github.com/specify/specify7/assets/37256050/32681842-3a88-477b-9446-8f89e07c61cf)

When the catalog number field is assigned to `KUPBcatno` in both the `collection` table and in the schema:
<img width="1060" alt="image" src="https://github.com/specify/specify7/assets/37256050/b85eb2a4-9a38-40a6-b388-55a9dd5fcca1">

See that the numeric matching logic is not supported when it is a custom defined field format.

https://kupaleobot8312023-batch-image-upload.test.specifysystems.org/specify/attachments/import/11

`KUPBcatno`:
```xml
  <format system="false" name="KUPBcatno" class="edu.ku.brc.specify.datamodel.CollectionObject" fieldname="catalogNumber">
  <autonumber>edu.ku.brc.specify.dbsupport.CollectionAutoNumber</autonumber>
    <field type="numeric" size="7" inc="true"/>
  </format>
```

`CatalogNumberNumeric`:
```xml
  <format system="true" name="CatalogNumberNumeric" class="edu.ku.brc.specify.datamodel.CollectionObject" fieldname="catalogNumber" default="false" length="9">
  <autonumber>edu.ku.brc.specify.dbsupport.CollectionAutoNumber</autonumber>
    <external>edu.ku.brc.specify.ui.CatalogNumberUIFieldFormatter</external>
  </format>
```

This is defined in the [UIFormatters](https://github.com/specify/specify6/blob/master/config/backstop/uiformatters.xml) file in app resources and the catalog number format is assigned in the schema and in the `collection` table in the `catalogFormatNumName` field.

**Comment by realVinayak** [comment]
Fixed in https://github.com/specify/specify7/pull/3539/commits/ff473a4f8e2634f7c4150d731af2a19306f945c2
