### ISSUE TITLE
`xml-editor`: XML-editor allows saving even if there are errors in the XML definition

### ISSUE THREAD

**Issue by realVinayak** [specify/specify7#4209]
Steps to replicate:
1. Open a data object formatter definition in xml-editor. 
2. Modify `<field>SOME_FIELD</field>` of any formatter definition to be incorrect. For example, set it to  `<field>SOME_FIELD.</field>` (notice the period after "SOME_FIELD" . 
3. Notice that `Save` button is not disabled. In fact, clicking on Save actually saves the incorrect definition.
4. Next time opening that formatter definition leads to specify crashing, so user cannot fix the issue in any case.

While the actual issue is that save button is not disabled if there is an error, I think that it is a bit too restrictive to entirely crashing if there is a faulty xml-definition (for example, the ones edited in specify 6 could have a typo in the `<field>SOME_FIELD</field>` definition. 

The faulty xml: 
[faulty role xml.txt](https://github.com/specify/specify7/files/13340966/faulty.role.xml.txt)

The faulty lines:
```
    <format
        name="AccessionAgent"
        title="AccessionAgent"
        class="edu.ku.brc.specify.datamodel.AccessionAgent"
        default="true"
        >
        <switch single="true">
            <fields>
                <field formatter="Agent">agent</field>
                <field sep=" - ">role.</field>
            </fields>
        </switch>
    </format>
```

The crash report that occurs the moment the definition is opened: 
[Specify 7 Crash Report - 2023-11-13T20_32_43.280Z.txt](https://github.com/specify/specify7/files/13341001/Specify.7.Crash.Report.-.2023-11-13T20_32_43.280Z.txt)

**Comment by maxxxxxdlp** [comment]
> Modify <field>SOME_FIELD</field> of any formatter definition to be incorrect. For example, set it to <field>SOME_FIELD.</field> (notice the period after "SOME_FIELD" .

do you receive an error in the XML editor after you make this change?

if you receive an error and it doesn't prevent you from saving, then it's a bug with the save button/save blockers
if you don't receive the error, then it's a bug with the XML syncer spec for the formatters

**Comment by realVinayak** [comment]
Looks like syncer is not catching the error correctly, still comes up in console as an uncaught error. I think save blockers are fine, just that we are not catching it 
![image](https://github.com/specify/specify7/assets/61122018/6387dde5-cac9-47f8-b0b7-c583668031c8)

**Comment by maxxxxxdlp** [comment]
Potentially caused by https://github.com/specify/specify7/issues/3678 🤷?

**Comment by CarolineDenis** [comment]
> Potentially caused by #3678 🤷?

still reproducible after #3678 fixes
