### ISSUE TITLE
Query builder: error when using IsEmpty for formatted fields.

### ISSUE THREAD

**Issue by timo11** [specify/specify7#422]
![emptyissue](https://user-images.githubusercontent.com/2915306/27975722-fc8a3498-6328-11e7-833d-31e72a2f4fc5.png)

**Comment by maxxxxxdlp** [comment]
Unable to reproduce.
I am not getting any exceptions when using isEmpty with the following fields:
Locality > Short Name
Collecting Event > Cataloged Date (Full Date)
Collecting Event > Cataloged Date (Year)
Taxon > Full Name
