### ISSUE TITLE
`xml-editor`: Date fields not working as expected

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4225]
**Steps to Recreate:**
1. Go to a form with a date field (make sure accessible date picker is turned on in preferences)
2. Try to type in a date ending in `2021`
3. See that it is not possible

Arc Browser, macOS Sonoma

## How it works on `xml-editor`:

https://github.com/specify/specify7/assets/37256050/bd0b529f-6e11-469e-a241-95cca379e341

## How it should work (`v7.9.1`):

https://github.com/specify/specify7/assets/37256050/fadd6498-c1ad-40f5-9c9b-5afeacd70342

**Comment by CarolineDenis** [comment]
NOTES: 
When selecting precision 'year' there is an issue as well.
