### ISSUE TITLE
`xml-editor`: Forms being used for searching should not allow attachments or records to be created

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4226]
<img width="1221" alt="image" src="https://github.com/specify/specify7/assets/37256050/03ae52f2-05fe-402a-800c-e679218c0f8d">

Currently, when you try to search for records to preview how an aggregator/format will look, it displays the whole form (unless a search dialog form is defined). For instance, look at the `Preparation` aggregation editor here:
https://saiabjan1023-xml-editor.test.specifysystems.org/specify/resources/app-resource/233/formatter/Preparation/43

You can upload attachments here and they will end up on the asset server. Everything should be read-only in this dialog, as it's meant to act as a place to search for records.

**Comment by maxxxxxdlp** [comment]
nice find!
though this bug might have been present since 7.7
