### ISSUE TITLE
`xml-editor`: Unable to define new formatters as fields cannot be added

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4227]
On `xml-editor` there's no way to actually add fields to a format at this time. This worked at some point I believe.

## How it should look

<img width="644" alt="image" src="https://github.com/specify/specify7/assets/37256050/87f55016-1dee-4043-9b74-75b156118f51">

## How it looks

<img width="641" alt="image" src="https://github.com/specify/specify7/assets/37256050/0a550f84-41fa-4fcd-829a-c16a0d658177">

https://saiabjan1023-xml-editor.test.specifysystems.org/specify/resources/app-resource/233/formatter/CollectionObject/62

**Comment by maxxxxxdlp** [comment]
hmm, doesn't look right.

does it appear if you select a condition field? or check the "Default" checkbox (you shouldn't have to - the "Add definition" button should be enabled even without that)

**Comment by grantfitzsimmons** [comment]
No, it doesn't appear at all

**Comment by CarolineDenis** [comment]
Should be verified/ revisited once https://github.com/specify/specify7/pull/4114 is merged in xml
