### ISSUE TITLE
Remove "Back to Form" button from paleomap plugin.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#423]
Tomislav added a url param to suppress the button for embedding purposes. Now I just need to add the flag to the requests made by Specify.

**Comment by benanhalt** [comment]
For testing:

The paleo map plugin map should no longer display the "Back to form" button at the top.

**Comment by yvonneekanim** [comment]
Tested in UTAustinpaleo, "Back to form" button is not displayed.
