### ISSUE TITLE
Search in WorkBench is not operational

### ISSUE THREAD

**Issue by pashiav** [specify/specify7#4232]
Update: https://github.com/specify/specify7/issues/4232#issuecomment-1881647892
**Describe the bug**
The search functionality in WorkBench is not operational. When entering text into the Search bar, no cells are being retrieved.

**To Reproduce**
1. Go to WorkBench ⇒ select any data set (https://nbmmnb5523-xml-editor.test.specifysystems.org/specify/workbench/61/)
2. Enter any term into the Search bar within the WorkBench set (e.g., "gift")
3. Press the return/enter key on the keyboard
4. See that there is no response and no cells are returned

**Expected behavior**
The cells containing the specified Search input should be highlighted in green. 

**Screen Recordings**
https://nbmmnb5523-xml-editor.test.specifysystems.org/specify/workbench/61/

https://github.com/specify/specify7/assets/118556884/283e95b4-05d3-4912-93e6-ebb1d926f8d5

_Expected behavior:_
branch: `v7.9` https://nbmmnb5523-v79.test.specifysystems.org/specify/workbench/61/

https://github.com/specify/specify7/assets/118556884/ab7ba417-d878-46e9-9064-c9428a126bc5

Also tested with: `KU_Fish_2023` https://kufish2023-xml-editor.test.specifysystems.org/specify/workbench/13/

**Desktop:**
 OS: macOS Monterey (12.6.5)
 Browser: Chrome
 Specify 7 Version: `xml-editor`

**Comment by pashiav** [comment]
Not functional in both `xml-editor` and `edge`.

https://nbmmnb5523-xml-editor.test.specifysystems.org/specify/workbench/61
https://nbmmnb5523-edge.test.specifysystems.org/specify/workbench/61

https://github.com/specify/specify7/assets/118556884/641e8ed3-178b-47ac-91b6-945bcaa3a0f7

**Comment by CarolineDenis** [comment]
@specify/ux-testing , 
I cannot reproduce this issue, can you please test again

**Comment by pashiav** [comment]
Can no longer reproduce in `edge`.
![Screen Shot 2024-03-20 at 12 42 50 PM](https://github.com/specify/specify7/assets/118556884/6227f837-64a4-423a-9ab2-e3dc1a56f4af)
