### ISSUE TITLE
`ParseError` upon logging in when a user has an invalid `ExpressSearchConfig`

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4235]
```
Error occurred fetching from https://sandbox-rbge.specifycloud.org/context/available_related_searches.json

ParseError
not well-formed (invalid token): line 1, column 1
Content
"None"
```
[Specify 7 Crash Report - 2023-11-27T18_16_21.485Z.txt](https://github.com/specify/specify7/files/13478880/Specify.7.Crash.Report.-.2023-11-27T18_16_21.485Z.txt)

User `rcubey` at Edinburgh is reporting an issue upon logging in. Immediately after logging in, this error occurs.

It appears that their `ExpressSearchConfig` is invalid:

<img width="819" alt="image" src="https://github.com/specify/specify7/assets/37256050/bc5394aa-4666-4bd6-9ce1-5fd92ad33e81">
[Broken_ExpressSearchConfig.xml.zip](https://github.com/specify/specify7/files/13478850/Broken_ExpressSearchConfig.xml.zip)

Here's it fixed, after fixing the formatting, and now the error does not occur:
<img width="959" alt="image" src="https://github.com/specify/specify7/assets/37256050/52688c66-cd64-4250-a6bb-698fb276707f">
[Fixed_ExpressSearchConfig.xml.zip](https://github.com/specify/specify7/files/13478847/Fixed_ExpressSearchConfig.xml.zip)

Normally I would not write this as a bug, as the file is not structured properly, but this error is only happening in `v7.9.1` and not `v7.9.0`. If no other reports come out, feel free to close this, but it's strange/potentially an issue that the error was not being reported before.

It should fall back and use the default if the file is corrupt, not throw a warning each time.

**Reported By:** RBGE

**Comment by melton-jason** [comment]
It may be the case the file being misformed/corrupted is a result of an agent merging bug (see https://github.com/specify/specify7/pull/4237#issue-2017195096). 

Would #4237 resolve this issue, or is the intended fix to handle the case when an AppResource is misformed in such a manner?

**Comment by emenslin** [comment]
fixed
