### ISSUE TITLE
Changing an Admin User's Collections Permissions removes admin

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#425]
If you are logged in as an admin user, if you go to Manage Users, then change the collections permissions for another admin (or even the currently logged-in admin), whether you add collections to their permissions or take them away, saving the new permissions removes Admin status from that user. Either Admins should not be able to change their collections permissions (they should have permission to all collections), or their Admin status should not be changed when they add or remove collections permissions.

**Comment by maxxxxxdlp** [comment]
Superseded by https://github.com/specify/specify7/issues/833
