### ISSUE TITLE
`xml-editor`: `HierarchyException` when choosing a table on the web link form

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4255]
**Describe the bug**
When choosing a table for a web link, a `HierarchyException` occurs

```
HierarchyException at /api/specify/agentidentifier/ queryset model Agentidentifier has no hierarchy field 
```

**To Reproduce**
1. Go to a 'WebLinks' app resource
2. Edit a web link by choosing one from the list (or create a new one)
3. Choose the 'Agent Identifier' table as a base
4. See error appear

**Screen Recording**
https://github.com/specify/specify7/assets/37256050/bae92ea3-323e-4c3e-a0f9-0e9930b0fc3f

[Specify 7 Crash Report - 2023-12-05T15_21_29.112Z.txt](https://github.com/specify/specify7/files/13561952/Specify.7.Crash.Report.-.2023-12-05T15_21_29.112Z.txt)

**Comment by melton-jason** [comment]
Related to #3564. 
The solution for that issue should also fix this one.

**Comment by CarolineDenis** [comment]
Added to https://github.com/specify/specify7/issues/3564
