### ISSUE TITLE
Unable to get tree ranks for a Taxon table error for user with limited access

### ISSUE THREAD

**Issue by pashiav** [specify/specify7#4259]
**Describe the bug**
Error appears when arriving on Data Entry page for New Taxon as a user with limited access to Taxon table.

**To Reproduce**
1. Log in as `testuser` (https://nbmmnb5523-edge.test.specifysystems.org/specify/)
2. Go to Data Entry ⇒ Taxon (https://nbmmnb5523-edge.test.specifysystems.org/specify/view/taxon/new/)
3. See error
[Specify 7 Crash Report - 2023-12-06T21_46_11.121Z.txt](https://github.com/specify/specify7/files/13592070/Specify.7.Crash.Report.-.2023-12-06T21_46_11.121Z.txt)

**Expected behavior**
No error popup. Should allow user to Read, Create, Update, and Delete in Taxon table.

**Screenshots**
![new-taxon-error](https://github.com/specify/specify7/assets/118556884/cc683468-83ad-46a6-8987-1e2b00c21370)

Taxon Trees page is just a blank screen: (https://nbmmnb5523-edge.test.specifysystems.org/specify/tree/taxon/)
![Screen Shot 2023-12-06 at 4 09 00 PM](https://github.com/specify/specify7/assets/118556884/723d5175-e695-495d-9964-00f46408bcf6)

`testuser` permissions: (https://nbmmnb5523-edge.test.specifysystems.org/specify/security/user/4/)
![permissions](https://github.com/specify/specify7/assets/118556884/2710d49a-4167-4ed4-9ccb-6bc919143b98)

**Desktop:**
 - OS: macOS Monterey (12.6.5)
 - Browser: Google Chrome
 - Specify 7 Version: `edge`, also tested on `v7.9.1`

**Database Name:**
`nbm_mnb_5_5_23`

**Comment by grantfitzsimmons** [comment]
It looks like this error occurs because `testuser` does not have read access to the discipline which is required to create a record in the `taxon` table. Once I added read access to the discipline to the role, the error no longer occurs. The tree viewer becomes visible once this change is made as well.
