### ISSUE TITLE
Page titles are not always displayed in the tab

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4263]
The titles in the browser tabs have gone missing recently. I could recreate it in `v7.9.1` and `edge`, but this could have been introduced in `v7.9.0`. Below I am using the last version of `v7.8`, `v7.8.9`, as a reference. 

## Log In

**Left:** https://kufishdemo-v789.test.specifysystems.org/accounts/login/?next=/specify/
**Right:** https://kufishdemo-edge.test.specifysystems.org/accounts/login/

<img width="960" alt="image" src="https://github.com/specify/specify7/assets/37256050/5ca143c7-be70-4c2f-bbac-853d5f27e263">

## New Collection Object

**Left:** https://kufishdemo-v789.test.specifysystems.org/specify/view/collectionobject/new/
**Right:** https://kufishdemo-edge.test.specifysystems.org/specify/view/collectionobject/new/

<img width="1918" alt="image" src="https://github.com/specify/specify7/assets/37256050/5455c503-bdd2-48f4-91e2-676f30a96a8e">

## Attachments

**Left:** https://kufishdemo-v789.test.specifysystems.org/specify/attachments/
**Right:** https://kufishdemo-edge.test.specifysystems.org/specify/attachments/

<img width="1917" alt="image" src="https://github.com/specify/specify7/assets/37256050/061e81c8-84f2-40a9-b383-fbc7d2979688">

## App Resource: {Name of resource}

**Left:** https://kufishdemo-v789.test.specifysystems.org/specify/resources/app-resource/108/
**Right:** https://kufishdemo-edge.test.specifysystems.org/specify/resources/app-resource/108/

<img width="961" alt="image" src="https://github.com/specify/specify7/assets/37256050/2d9872d3-132c-4a07-9f1d-830c918a1f05">

## Security and Accounts

**Left:** https://kufishdemo-v789.test.specifysystems.org/specify/security/
**Right:** https://kufishdemo-edge.test.specifysystems.org/specify/security/

<img width="1920" alt="image" src="https://github.com/specify/specify7/assets/37256050/a29b04b7-e7a5-49f1-b915-8ffecfdec6e0">

## Record Preview (Taxon: Animalia | Specify 7)

**Left:** https://kufishdemo-v789.test.specifysystems.org/specify/view/taxon/15797/
**Right:** https://kufishdemo-edge.test.specifysystems.org/specify/view/taxon/15797/

<img width="1919" alt="image" src="https://github.com/specify/specify7/assets/37256050/77920064-e5ed-4f8c-8f97-6a096ac706b5">

## Record Sets (Record Set: k | Specify 7)

**Left:** https://kufishdemo-v789.test.specifysystems.org/specify/view/collectionobject/6/?recordsetid=44
**Right:** https://kufishdemo-edge.test.specifysystems.org/specify/view/collectionobject/6/?recordsetid=44

<img width="1920" alt="image" src="https://github.com/specify/specify7/assets/37256050/d2bb1761-73aa-4478-ac1f-8dc373482839">

**Reported By:** Garth at University of Michigan 

>In this bug, browser tab titles are missing for many but not all tabs in S7.9.1, where the version we currently have installed at UMich (S7.8.5) displays fuller titles. 
>
>In the below screenshot, two windows are displayed, with the same set of pages opened in tabs in each window. From left to right, these are: the Specify 7 collection home page, a new query, and specific collection object, a new collection object, and a new taxon. As you can see, in S7.9.1, only the new query has a distinctive browser tab title, whereas the other tabs are all titled simply 'Specify 7'. 
>
>One collection manager reported that this is a serious issue, as they work with multiple tabs open at the same time. Without titles displayed, this becomes very disorienting. 
>
>Please let me know what you think, and whether this is an issue that can be resolved in our local version of Specify 7. I'm guessing that this may not be possible without including a bug fix in an updated version of Specify 7?

**Comment by maxpatiiuk** [comment]
Seems to have been caused by my change back in March 14th of last year in 5e93f97ab
