### ISSUE TITLE
Loans created in 6 not showing up in 7

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify7#429]
Some loans created in Speciy 6 are not showing up in 7. This is happening in some databases but not all.

**Comment by timo11** [comment]
What databases is it happening in? For which loans?

**Comment by yvonneekanim** [comment]
Bishop reported this issue; it was replicated in "herps" on the test server

**Comment by timo11** [comment]
What are the loanumbers of some loans that are not showing up in 7?

**Comment by yvonneekanim** [comment]
001; loan items are not showing up

**Comment by timo11** [comment]
In the herps db no loan items show up no matter how or where they are added because the loanpreparations form contains CurrentDetermination, which specify7 doesn't support. (I think there is already a 7 bug about that.)
