### ISSUE TITLE
Error switching base tables in queries 

### ISSUE THREAD

**Issue by emenslin** [specify/specify7#4294]
**Describe the bug**
When switching between base tables when querying without saving an error message pops up.
[Specify 7 Crash Report - 2023-12-15T14_32_58.308Z (1).txt](https://github.com/specify/specify7/files/13686449/Specify.7.Crash.Report.-.2023-12-15T14_32_58.308Z.1.txt)

**To Reproduce**
1. Create a new query using any tree table
2. Add anything to the query 
3. Don't save and add a new query under a different table 

**Expected behavior**
I would expect there to be no error and you should be able to switch between queries with no problems.

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Specify 7 Version: edge

**Database Name:** lsumzmammals (6.8.03)

**Comment by melton-jason** [comment]
> **Describe the bug** If you create a query based on any of the Trees:
> 
> 1. Taxon
> 2. Storage
> 3. Geography
> 4. Lithostrat
> 5. Chronostrat
> 
> Then go and create another new query with any other table as a base. It's going to through an OperationalError
> 
> **Expected behavior** No error [Specify 7 Crash Report - 2023-11-24T22_08_09.151Z.txt](https://github.com/specify/specify7/files/13462329/Specify.7.Crash.Report.-.2023-11-24T22_08_09.151Z.txt)
> 
> **Beautiful Screen Recording**
> 
>  Screen.Recording.2023-11-24.at.4.07.31.PM.mp4 
> **Desktop:**
> 
> * OS: Mac OsX
> * Browser: Chrome
> * Specify 7 Version: Any

From @carlosmbe in https://github.com/specify/specify7/issues/4231#issue-2010253721
