### ISSUE TITLE
Query pops up invalid response dialog when searching using Between operator when one criteria is considered valid

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#4296]
I did a Contains query on a formatted catalog number field (#####A) using just a single number.  It returned the correct results.  I switched to a Between query using a single number in both fields.  It popped up an invalid response error message.
If I do the same Between query BEFORE doing the contains query, it indicates there is an issue with the format (highlights the field values in the query in red) and returns results like the criteria wasn't there.
Expected behavior would be to indicate there is an issue with the format used and not return results.

https://github.com/specify/specify7/assets/12532430/d5923b8a-fc0f-431c-aee8-94892710b363

**Comment by tlammer** [comment]
First 5 lines of the error received:
TypeError at /stored_query/ephemeral/ between() missing 1 required positional argument: 'cright' Request Method: POST Request URL: http://blanksuffixcatnumber-v791.test.specifysystems.org/stored_query/ephemeral/ Django Version: 3.2.15 Python Executable: /opt/specify7/ve/bin/python3.8 Python Version: 3.8.0 Python Path: ['/opt/specify7', '/opt/specify7', '/opt/specify7/ve/bin', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/opt/specify7/ve/lib/python3.8/site-packages', '/opt/specify7'] Server time: Fri, 15 Dec 2023 18:59:37 -0600 Installed Applications: ('django.contrib.sessions', 'django.contrib.staticfiles', 'django.contrib.contenttypes', 'django.contrib.auth', 'specifyweb.specify', 'specifyweb.permissions', 'specifyweb.accounts', 'specifyweb.stored_queries', 'specifyweb.businessrules', 'specifyweb.express_search', 'specifyweb.context', 'specifyweb.attachment_gw', 'specifyweb.frontend',

**Comment by emenslin** [comment]
Fixed
