### ISSUE TITLE
`xml-editor`: Schema config table list appears incorrectly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4307]
**Describe the bug**
The list of tables in the Schema Config tool do not display, and when you view them all, the scroll bar is immediately to the right of the list, not the along the side of the window.

**To Reproduce**
1. Go to Schema Config in the User Tools menu
2. See issue

https://github.com/specify/specify7/assets/37256050/805de557-ec0d-4a36-aea0-8de929c3aadd

https://kufishdemo-xml-editor.test.specifysystems.org/specify/schema-config/en/

Arc on macOS

**Comment by CarolineDenis** [comment]
NOTES: 
- we added a check box to only display the tables that have an app resource in the app resource tool instead of the advanced table check box
- the same component is used in schema config
