### ISSUE TITLE
`xml-editor`: Clicking edit or add for a pick list causes the page to reload before the user can take action

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4308]
**Describe the bug**
After loading the Schema Config, if I want to add or edit a pick list from the 'field format' menu, it first reloads the page and I have to click edit or add once again after it finishes.

**To Reproduce**
1. Go to a table in the Schema Config
2. Select a field
3. Try to add a pick list
4. See page refresh
5. Try to add a pick list again
6. See that it works now

**Expected behavior**
It should let you add or edit a pick list immediately, not require a reload.

**Screenshots**

https://github.com/specify/specify7/assets/37256050/6848fc13-ad2b-4f32-a489-e4af56f254f4

**Desktop:**
Arc on macOS

**Comment by maxpatiiuk** [comment]
might be related to https://github.com/specify/specify7/pull/3441 and https://github.com/specify/specify7/issues/3528

**Comment by realVinayak** [comment]
Also happens when you go to a tree and click on "add child" or "edit".

Noticed that this issue doesn't happen without `LazyResourceView` introduced in https://github.com/specify/specify7/pull/4240.
