### ISSUE TITLE
The border for the disabled Save button is slightly darker than for the BorderedGray buttons

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4309]
<img width="508" alt="image" src="https://github.com/specify/specify7/assets/37256050/18067bb8-32c9-4b21-a423-0eb5e3c56dbb">

I noticed this while reevaluating the styling for Batch Attachment Upload and other areas. Minor inconsistency.

**Comment by maxpatiiuk** [comment]
some concerns: see https://github.com/specify/specify7/commit/7556e7e44132ad64a6b6608d31f7e73811d9508b#r135472982

**Comment by grantfitzsimmons** [comment]
Replied to concerns: see https://github.com/specify/specify7/commit/7556e7e44132ad64a6b6608d31f7e73811d9508b#r135509985
