### ISSUE TITLE
Schema changes not being reflected in workbench

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify7#433]
In pripaleo, taxon.source was added to the workbench but the changed field caption is not being reflected there.

**Comment by timo11** [comment]
I don't understand. 
Source for taxon levels is already in the workbench schema. Changing the caption in the workbench schema with the schema configurer in Sp6 changes the caption in the workbench template mapper in 7. Workbench column titles are usually determined by the headers in the file the workbench is imported from. Changing captions in the workbench schema doesn't change column headers in pre-existing workbenches. Does any of this have anything to do with the issue?
