### ISSUE TITLE
`xml-editor`: Add weblink's text next to the icon

### ISSUE THREAD

**Issue by realVinayak** [specify/specify7#4335]
Currently, to see the link, I'd have to rely on browser making a little popup on the bottom left corner on highlighting the weblink. I think it is worth making the link visible right next to the button.

@specify/ux-testing @CarolineDenis @grantfitzsimmons thoughts?

![Screenshot (321)](https://github.com/specify/specify7/assets/61122018/c4bc8fe6-5b07-48e2-a400-19f0e2e7c8a2)

**Comment by maxpatiiuk** [comment]
1. great idea
2. I was pretty sure we already had this 😵‍💫 (originally requested by Grant)

implementing this is pretty simple. Just add a `{url}` in between these two:

https://github.com/specify/specify7/blob/1d6409c522a5ebd60ebb2fa6a30c00e2ac60f6e4/specifyweb/frontend/js_src/lib/components/WebLinks/index.tsx#L157-L158

(may require wrapping the url in a div to add styling if necessary)
