### ISSUE TITLE
Determination.isCurrent included in export CSV

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#434]
Although the Determination.isCurrent field is hidden (should not display in CSV), when the export CSV is created, the field is included and bumps some other fields into the incorrect columns.

**Comment by benanhalt** [comment]
It seems to me that it is already fixed in the development branch, but is present in the current release v7.2.1

**Comment by timo11** [comment]
this is supposed to have been fixed in bug #357 as a result of fixing a similar problem for export to kml

**Comment by garrettgirard** [comment]
I don't know if you guys saw Theresa's comment on this. But I think she just wanted me to add this bug as a record of it existing or something. I can't find the email thread right now though.

**Comment by benanhalt** [comment]
@garrettgirard that's correct. Can you please verify that is not happening in the development branch, then mark it as fixed.

**Comment by yvonneekanim** [comment]
When I added "is current" ="tue" as a parameter for the CO query I ran, the csv file generated has a column for it. It doesn't seem to affect other records

**Comment by benanhalt** [comment]
This is working for me. Can you confirm that the "is current" field is set to invisible by unchecking the lightbulb icon on the right side of the query field?
