### ISSUE TITLE
'Use localized field labels' checkbox in App Resource should be a button

### ISSUE THREAD

**Issue by CarolineDenis** [specify/specify7#4341]
From @maxpatiiuk comment: 

> Given that the "Use localized field labels" checkbox is reloading the page, it would be more semantically correct to have that as a button.
> I know that it's reused with the Form Meta menu, so we could convert it to a button there too.
> If it's a button, the label would have to be different depending on on/off state

**Comment by CarolineDenis** [comment]
@maxpatiiuk , For the check box in form meta, if we change the "Use localized field" check box to a button, don't you think we should also change the " Use autogenerate form" ? 
![Screenshot 2024-01-02 at 10 34 24 AM](https://github.com/specify/specify7/assets/108160931/84f1fb73-1e8e-474c-bd9c-59f51f271a7e)

**Comment by maxpatiiuk** [comment]
The "Use Localized Field Labels" checkbox causes the page to reload
The "Use Auto Generated Form" checkbox does not cause the page to reload

When I see a checkbox on the web, I don't expect that clicking the checkbox would reload the entire application (at very least, there would be some "Save" button or "Confirm" before that happens)
When I see a button, then it's more possible that it would cause the page to reload (i.e button is doing some action)

So while you could change both checkboxes to a button for consistency, if we are going by what is semantically correct, it should remain as a checkbox

Feel free to double check with Grant or someone else what they think

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/get-started-with-specify-7-localization/956/7
