### ISSUE TITLE
Inconsistent Behavior with Tables Hidden in Schema and New Query/Possible Query lists 

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4342]
**Describe the bug**

**From Zoe at CSIRO:** 

 > Steps to re-create what I've found (Sp v7.8.13 ANWC UAT)
 > 1.       From Queries module, I select New Query. As expected I’m given a list of tables to choose from to start my new query.
 > ![image](https://github.com/specify/specify7/assets/135047322/0920ff77-14ff-4e3c-8b1f-7b8edc093eaf)
 > 
 > 2.       I want to refine the list and remove ‘Appraisal’, as I never build an Appraisal query. I select the ‘pencil’ edit icon next to 'New Query' heading and open the ‘Configure visible query tables’ pop up.
 > ![image](https://github.com/specify/specify7/assets/135047322/c0ce5ba1-cd4c-43db-8b39-2db31d3b5e4d)
 > 3.      As you can see above, ‘Appraisal’ isn’t in the ‘Selected Tables’ list. It’s not in the Possible Tables list on the right either. So how do I remove it?
 > 4.       I also looked in Sp6 to see if that is where the configuration was coming from, but the configured list there is different to the list presented in Sp7, Appraisal does not appear at all. 
> ![image](https://github.com/specify/specify7/assets/135047322/d027022a-8391-4005-80b5-9cbdaf21ecf7)
> 5.      Appraisal also doesn’t appear when I ‘Configure Query Creators’ in Sp6. 
> ![image](https://github.com/specify/specify7/assets/135047322/88ad48cf-5caf-44d9-8c0f-5151fb15fe25)
> 
> 6. Nor does it appear in the lists if I hit the green plus + icons
> ![image](https://github.com/specify/specify7/assets/135047322/0909304b-abad-4a6e-96e8-f074656cde4e)
> 
> So I’m a bit flummoxed.

**Desktop:**
version: v7.8.13 ANWC UAT

**Additional context**
Database name or any other context about the problem here.

Could not be recreated on the test panel (DB: Balearicis | v7.8.13) or on production. Still investigating the cause.

**Comment by zoewarner1** [comment]
Thanks @bronwyncombs for adding this - I've just had a duh! moment - we had hidden Appraisal table through the schema config tool:
![image](https://github.com/specify/specify7/assets/144304519/d9aab702-bc40-4d5d-8726-6da9fbbad023)
If I unhide it, it then appears in the Selected Tables list.
This can be closed :)

**Comment by zoewarner1** [comment]
Sorry @bronwyncombs - I've had another look at another of our instances. We have also hidden the Appraisal table there, but it does not appear in the New Query list. So now I'm back to being confused, there must be something else contributing to what appears when in the new query list.
![image](https://github.com/specify/specify7/assets/144304519/b8bff139-9180-45aa-83d5-ae29b37aa34d)

**Comment by maxpatiiuk** [comment]
Thank you for identifying a few edge cases we didn't properly handle. The following issues are present:

- The "New Query" dialog included hidden tables, but the "Possible Tables" hid the hidden tables - will be resolved to have both dialogs exclude tables that are hidden, or system, or user does not have read access to
  - Note, to have hidden and system tables present in the list, user can enable "No restrictions mode" for query builder in user preferences
- The "Possible Tables" was not excluding the tables user did not have read access to - will be resolved

The default list for "New Query" dialog (before user customizations) is separate from the default list in sp6, but we tried to keep them similar. Hopefully, resolving these bugs would keep them more similar.

**Comment by zoewarner1** [comment]
Hi @CarolineDenis - I've just noticed in 7.9.4, that I can't see 'Sp Audit Log' table in my Selected or Possible table query config options. I'm logged in as an admin with full access to all tables. And Sp Audit table itself is not 'hidden'. How do I build a new query to search audit table? Thank you!
 
![image](https://github.com/specify/specify7/assets/144304519/52469391-29cb-4505-acf6-1307fd056437)
![image](https://github.com/specify/specify7/assets/144304519/3f82a092-1309-4bdb-b260-052a7cd5d1f0)

**Comment by zoewarner1** [comment]
Hi @CarolineDenis - please ignore my last post - have just re-read max's comment:
'Note, to have hidden and system tables present in the list, user can enable "No restrictions mode" for query builder in user preferences'
Enabling 'no restrictions mode' meant I could then see audit log as an option in 'possible' list. Thanks
