### ISSUE TITLE
`xml-editor`: Tree rank picklist suggests primary key

### ISSUE THREAD

**Issue by realVinayak** [specify/specify7#4348]
1. Go to a tree.
2. Click on a node which can have a child.
3. Click on "+" icon. Notice that in the Rank field, the primary key (id) appears instead of the name by default.

![image](https://github.com/specify/specify7/assets/61122018/956f5df5-2077-4a67-806d-57f35ac4d285)

**Comment by CarolineDenis** [comment]
Might be fixed by https://github.com/specify/specify7/pull/4353
Need to test once merged in prod and prod merged in xml

@melton-jason @realVinayak

**Comment by CarolineDenis** [comment]
fixed by https://github.com/specify/specify7/pull/4353
