### ISSUE TITLE
`xml-editor`: Default values of some picklists is "(current, invalid value)"

### ISSUE THREAD

**Issue by realVinayak** [specify/specify7#4350]
1. Go any interaction, and go to Role picklist for interaction agent

XML Editor:
![image](https://github.com/specify/specify7/assets/61122018/a7e6b091-689b-4335-b6d3-18d9e34f6766)
![image](https://github.com/specify/specify7/assets/61122018/5dbaa713-5b8a-4793-9a9a-ddaff6a57a12)
![image](https://github.com/specify/specify7/assets/61122018/2815bbe7-4576-4234-9677-529e7aa7c0d3)

Production
![image](https://github.com/specify/specify7/assets/61122018/e0cbf4da-a025-43ed-91d7-bdb672aa2df1)
![image](https://github.com/specify/specify7/assets/61122018/bc41304e-1310-4e23-ac70-b5d9a24ce964)
![image](https://github.com/specify/specify7/assets/61122018/92f1f341-9cdf-40da-84d1-4fdcf4145f10)

**Comment by CarolineDenis** [comment]
Happened when agent role pick list is read only
