### ISSUE TITLE
Gene sequence not counting Comp, total residues and ambiguous

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify7#436]
In 6 when a sequence is typed into the gene sequence field, the total residues, comp A,G,C,T and ambiguous fields are counted automatically. This is not happening in 7, the count has to be input manually.
Also, there is no 'save' button on the material samples form.

**Comment by benanhalt** [comment]
There must be a plugin or a business rule class in Specify 6 that adds the counts. A corresponding mechanism will have to be added to 7. The material sample form doesn't get a save button because it is a part of the collection object record, so it gets saved when the collection object is saved.

**Comment by maxxxxxdlp** [comment]
> The fields at the left that are supposed to show the count of `A`, `G`, `T` and `C` residues do not get updated on the input to the text field on the right
> 
> Also, these fields are editable, while they are supposed to be readonly ![Screen Shot 2020-06-25 at 11 34 02 AM](https://user-images.githubusercontent.com/40512816/85685507-be291580-b694-11ea-8905-bb0394c092d2.png)
