### ISSUE TITLE
Cannot create new taxon 

### ISSUE THREAD

**Issue by emenslin** [specify/specify7#4361]
**Describe the bug**
When adding a new taxon within the determinations table it autofill's the rank but then says it cannot save because the  "field is required"

**To Reproduce**
1. Go to data entry and create a new collection object 
2. Add a determination and add new taxon
3. Add a parent 

**Expected behavior**
This should be able to save without any error.

https://github.com/specify/specify7/assets/150940840/203030a9-9d21-4295-8e7f-9580b36cc434

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Specify 7 Version: xml editor 

**Database Name:** lsumz mammals

**Comment by grantfitzsimmons** [comment]
Please add `xml-editor` issues to the `xml-editor` release milestone (at this time– 7.9.4)
