### ISSUE TITLE
Fix reports handling to accept all image expressions.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#437]
The reports UI code currently parses the JRXML to replace references to local image files. But, it also rejects any expressions that it doesn't understand. This should be relaxed to allow any image expression, and only process local file references.

**Comment by benanhalt** [comment]
fixed in 4d5927fcdcd1ba42cf3a8032b25f5463ba1b5fef

**Comment by benanhalt** [comment]
This can be tested on the next-release branch.

**Comment by maxxxxxdlp** [comment]
Can you send me example XML files to test?

**Comment by maxxxxxdlp** [comment]
Worked fine when I added this to a report definition:

```xml
<imageExpression class="java.net.URL"><![CDATA["https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Limosa_lapponica_2_-_Taren_Point.jpg/1920px-Limosa_lapponica_2_-_Taren_Point.jpg"]]></imageExpression>
```
