### ISSUE TITLE
`xml-editor`: Add support for rearranging items in a table format

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4379]
**Describe the bug**
You can add items to a table format but you cannot remove them. To change the order, you are required to remove everything and add them in a different order.

**To Reproduce**
1. Create or edit a table format
2. Add fields
3. See issue 

https://kufishdemo-xml-editor.test.specifysystems.org/specify/resources/app-resource/9/formatter/Loan/39

https://github.com/specify/specify7/assets/37256050/0f5788ed-e52f-466a-870a-5aecda7827f8

macOS, Arc

**Comment by maxpatiiuk** [comment]
Can be similar to the work @CarolineDenis did with rearranging query fields
