### ISSUE TITLE
`xml-editor`: Table Format field mappings stack inappropriately and are not separated 

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4380]
**Describe the bug**
Nested items in the table format editor appear in a large stack rather than taking up the available width in the dialog, resulting in confusing appearance.

Separators are also not visible between items in the table format, making it appear like they run into each other.

https://kufishdemo-xml-editor.test.specifysystems.org/specify/resources/app-resource/9/formatter/Loan/39

**To Reproduce**
1. Create or edit a table format
2. See that any nested fields are stacked
3. See visual/interface issues

<img width="1157" alt="Screenshot 2024-01-09 at 3 17 14 PM" src="https://github.com/specify/specify7/assets/37256050/5c381783-3c4f-4710-ace2-c1f4fabc1a51">

**Expected behavior**
Separators should be placed between fields and mapped fields should take up the full width available. 

**Screenshots**

<img width="938" alt="image" src="https://github.com/specify/specify7/assets/37256050/3f13f633-fb94-423d-8f65-111e058cb10b">

<img width="946" alt="image" src="https://github.com/specify/specify7/assets/37256050/2e429aad-f77a-4897-bcce-313ae61babae">

https://github.com/specify/specify7/assets/37256050/10bc984b-fe3b-4096-a5b7-506ae2a62563

**Comment by maxpatiiuk** [comment]
Yes, a bug
They are not supposed to stack like that - they are supposed to display as horizontal lines (like in workbench or query builder)
