### ISSUE TITLE
Wrong value is selected when a QueryCBX search result is chosen.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#440]
Introduced by #329.

In the query cbx search dialog activated by the magnifying glass, the list of search results will be sorted. But, when a value is chosen from the list, the value entered in the query cbx may not match the selection.

>  there still seems to be a problem with the storage locations on the object forms. When I look up a storage location and select it from the list, a different storage location appears on the object form. For example, if I'm trying to put a storage location of Dyche, rm.321C, Cab.13, 12: I search 12 and select Cab.13, 12 from the list, but Cab.11, 12 appears on the object form.

**Comment by yvonneekanim** [comment]
Value entered matches selection
