### ISSUE TITLE
Swagger misconfigured

### ISSUE THREAD

**Issue by xpusostomos** [specify/specify7#4411]
Hard to know where to report this bug, but anyway...

Unless I'm missing something, the swagger API is misconfigured...

https://sp7demofish.specifycloud.org/documentation/api/tables/

e.g. let's say I want to try the /api/specify/collectionobject/{id} GET method. There's nowhere on the screen to enter the id. Thus it doesn't work.

**Expected behavior**
Should be a way to run that api.

 - Browser: chrome
 - Specify 7 Version: whatever you're running on your own web site.

**Comment by maxpatiiuk** [comment]
Thanks for reporting the issue!
The fix will be included in the next version
