### ISSUE TITLE
`xml-editor`: 'Show Data Model Field Names' does not prompt the user to save before reloading

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4421]
**Describe the bug**
When pressed, the 'Show Data Model Field Names' button refreshes the page and the user loses their progress.

**To Reproduce**
1. Go to a form definition
2. Add a new view definition for a table
3. Make some edits
4. Click on the 'Show Data Model Field Names' button
5. See that you reload the page while the changes aren't preserved
6. See that you now see a 404

**Expected behavior**
If the button is going to reload the page, it should first ask the user to save so that they do not lose the changes they've been working on.

**Screenshots**

https://github.com/specify/specify7/assets/37256050/9eaa7f63-d2c0-44bf-9d55-fcb45e6ee6d9

**Desktop:**
macOS, Arc, `xml-editor`

https://crazyfish-xml-editor.test.specifysystems.org/specify/resources/view-set/4/CollectionObject/CollectionObject

**Comment by CarolineDenis** [comment]
DECISION: 
- the button to change the field label will be disabled in the case there is unsaved changes in the view def
