### ISSUE TITLE
`xml-editor`: Move the delete button to the `spappresource` edit dialog

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4422]
**Describe the bug**
I must admit, I've deleted several form definitions in my time testing `xml-editor` because I assume the bottom left 'delete' button refers to the view definition and not to the entire form definition file. After deleting, it is irrecoverable. I imagine I will not be alone in this.

I propose we move the delete button for form definitions (and maybe all app resources) to be behind the ✏️ (pencil) icon next to the resource name. It's all too easy to make this mistake and I imagine this will frustrate users (and myself) into the future.

**To Reproduce**
1. Go to a form definition
2. Go to a view definition within that form definition
3. Delete the view definition
4. See that you thought about clicking the bottom left delete before seeing the top right 'delete definition' button

**Expected behavior**

**Screenshots**
![image](https://github.com/specify/specify7/assets/37256050/baba35a8-43c8-42e6-8a85-88ee30b327b8)

![image](https://github.com/specify/specify7/assets/37256050/19fae2b7-8a8b-4891-8e6c-50f5d5624595)

**Comment by maxpatiiuk** [comment]
I faced this during development too 🤦 but didn't realize that it's an issue that I should address
And deleting app resources shouldn't be a common workflow, so hiding the button makes sense

**Comment by grantfitzsimmons** [comment]
@maxpatiiuk I tried to convince myself that this is something a user would adjust to with time, but despite extensive use, I still seem to delete form definitions regularly by mistake 😅
