### ISSUE TITLE
Create a 'Release checklist' issue template

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4424]
@maxpatiiuk asked if we should create a release checklist. I believe it's worth considering and potentially useful so we can ensure we complete all necessary tasks. This process is mostly in our heads at the moment, so formalizing it and making it public might be a good idea.

> It would have items on it like general testing, getting release milestone to 0, creating tag, updating specify cloud and etc
> 
> and it could also have post-release cleanup tasks like updating dev dependencies and merging PRs before they get stale
> 
> one way to do that is to create a "Release Checklist" issue template, and create an issue out of that template for each release (and maybe even pin it in the list of issues)
> alternatively, this could be a google doc, but I would prefer it to be on github (better integration with github's issues/PRs/milestons, and the fact that it is public)

**Comment by CarolineDenis** [comment]
@grantfitzsimmons, can this be closed?

**Comment by grantfitzsimmons** [comment]
Oh yes!
