### ISSUE TITLE
Clear browser cache dialog not being displayed

### ISSUE THREAD

**Issue by emenslin** [specify/specify7#4432]
**Describe the bug**
When I click the clear browser cache button on edge the popup does not show up like it does on 7.9.2

**To Reproduce**
1. Click on clear browser cache in user tools 
2. See that there is no popup 

**Expected behavior**
You should get the popup saying that the cache was cleared. 

**Screenshots**
First I tested in edge and then I switched to 7.9.2 to show the original/expected behavior 

https://github.com/specify/specify7/assets/150940840/e7d0c633-c40e-4007-ad15-a31d7a3927d0

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Specify 7 Version: edge

**Comment by melton-jason** [comment]
After some brief investigation, the `Clear Browser Cache` button still clears the cache: the issue here is that the Dialog is not being displayed.
