### ISSUE TITLE
Add the ability to customize column width in grid view

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4434]
> I’m having trouble adjusting the column widths in collapsed grid views.
> Eg: I want to make the Institution/Reference column wider in below:
> 
> ![image](https://github.com/specify/specify7/assets/37256050/47d9dd50-7d1e-41fa-a9a5-471c0d6f6c3d)
> I've had a look at Customizing form table column widths in [Form System · specify/specify7 Wiki · GitHub](https://github.com/specify/specify7/wiki/Form-System#customizing-form-table-column-widths). It provides a column def example:
>  <columnDef os="table">100px,0,200px,0,250px,0,p:g,0,p:g</columnDef> 
> 
> I copied it straight into our Other Identifier grid form xml to see what would happen
> 
> ```xml
> <viewdef
>             name="OtherIdentifiers_Grid"
>         
>             type="form"
>             class="edu.ku.brc.specify.datamodel.OtherIdentifier"
>             gettable="edu.ku.brc.af.ui.forms.DataGetterForObj"
>             settable="edu.ku.brc.af.ui.forms.DataSetterForObj">
>             <desc><![CDATA[OtherIdentifier subform for Collection Object form.]]></desc>
>             <enableRules/>
>                <columnDef>150px,2px,210px,5px,76px,2px,260px,5px,90px,2px,140px,0px,p:g</columnDef>
>             <columnDef os="lnx">50px,5px,285px,2px,198px,0px,15px,p:g</columnDef>
>             <columnDef os="table">100px,0,200px,0,250px,0,p:g,0,p:g</columnDef>
>             <columnDef os="mac">160px,2px,260px,5px,100px,2px,288px,5px,108px,2px,180px,0px,p:g</columnDef>
>             <columnDef os="exp">p,2px,p:g,5px:g,p,2px,p:g,5px:g,p,2px,p:g(2),0px</columnDef>
>             <rowDef auto="true" cell="p" sep="4px"/>
>             <rows>
> ```
> 
> but it did not do what I expected. I tried adjusting px values and adding more values but could not get it right.
> 
> ![image](https://github.com/specify/specify7/assets/37256050/713376cc-aa9d-4212-ad33-1f01e44ca6bc)
>

@melton-jason, @bronwyncombs, and myself have been able to verify this.

It does not respect the column definition of the `<definition>` that defines which fields appear in collapsed grid view, nor are the `colspan` attributes respected when collapsed. 
 
**Requested by:** CSIRO, NBM, UMich, and others

**Comment by maxpatiiuk** [comment]
> It does not respect the column definition of the <definition> that defines which fields appear in collapsed grid view, nor are the colspan attributes respected when collapsed.

Seems strange. It's likely using a wrong form definition somehow
Could you send the forms where you have subview that has view="" pointing to the formtable that has `<definition>` pointing to OtherIdentifiers_Grid?

(the fact that the name ends with `_Grid` does not mean anything for specify 7)

**Comment by CorinnaPaeper** [comment]
@maxpatiiuk - we have been using these instructions to create Grid views (hence the _Grid): https://discourse.specifysoftware.org/t/edit-the-form-grid-to-display-different-fields-than-the-subform/435

**Comment by grantfitzsimmons** [comment]
Fixed.
