### ISSUE TITLE
Interaction agents causing issues saving

### ISSUE THREAD

**Issue by emenslin** [specify/specify7#4439]
**Describe the bug**
Not entirely sure what the issue is but when adding an agent to an interaction it lets you save but after it saves the buttons then turn red and it won't let you do anything else. 

**To Reproduce**
1. Create a new disposal 
2. Add disposal agent 
3. Click save

**Expected behavior**
It should save without an issue 

**Screenshots**
<img width="958" alt="Screenshot 2024-01-19 142354" src="https://github.com/specify/specify7/assets/150940840/245a0555-b324-4b3b-87f6-d7facf8a226e">

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Specify 7 Version: edge

**Database Name:** lsumz mammals

**Comment by bronwyncombs** [comment]
can recreate on `fwri`. Not in `v7.9.2`. Consistent with Gifts and Disposal records. 
note: clone and add buttons still work, they are just red. (?)

**Comment by grantfitzsimmons** [comment]
😢
