### ISSUE TITLE
FormMeta Subview Order By is broken for Grid View

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4446]
**Describe the bug**

Form Meta allows you to "Order By". This sorts subform records added to a form by values of a given field on that subview.  An example is Preparations on the Collection Object form. 

Order By does not work when the subviews are Grid type. 

On `edge` changing the order of preparations based on Count does not work for grid view, even after engaging save with changes elsewhere on the form. Switching to subform type and again initiating save will correct the display order according to formMeta config. 

https://github.com/specify/specify7/assets/135047322/c7d9cf50-6096-4cb7-8722-76badee5e412

On `v7.9.2`, changing the order of preparations does work for the count field in grid view once save is enabled and clicked. 

https://github.com/specify/specify7/assets/135047322/62f22740-9274-49b1-ab7b-80e1c7caeb80

**Desktop:**
 - OS: macOS
 - Browser: Chrome

**Database Name:** `KU_Paleobot_8_31_2023`

**Comment by CarolineDenis** [comment]
NOTES: 
- works with fwri db
