### ISSUE TITLE
Save Prevention warning for field reiterates if ignored 

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4447]
**To Reproduce**
1. Go to form
2. Click on formMeta
3. Turn auto numbering off, and on again in the same step
4. Note the `! Value must be unique to Collection` warning
5. Ignore it, click Save or other areas of the form
6. See error

**Expected behavior**

Message shouldn't grow visually if ignored

**Screenshots**

<img width="1892" alt="Screenshot 2024-01-22 at 3 27 15 PM" src="https://github.com/specify/specify7/assets/135047322/8d822977-63d3-4726-a20e-22453881620a">

![image](https://github.com/specify/specify7/assets/135047322/400e7f01-04aa-4a9b-92a4-f5433fd4f39a)

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Specify 7 Version: `edge`, not in `v7.9.2`

**Database Name:** `KU_Paleobot_8_31_2023`

**Comment by bronwyncombs** [comment]
`KU_Paleobot_8_31_2024` had an existing CO with cat number of `#######`. Once changed this error no longer occurs when turning auto numbering back on.
Also closing because we have not been able to reproduce to reiterating/growing message issue.

**Comment by CarolineDenis** [comment]
@bronwyncombs, can this issue be closed?

**Comment by emenslin** [comment]
Cannot reproduce
