### ISSUE TITLE
Typing in New Password field inputs to Confirmation Field

### ISSUE THREAD

**Issue by pashiav** [specify/specify7#4448]
**Describe the bug**
When creating a new user and typing in the `Set Password` **Password** field, after the first character, all other characters are inputted into the **Confirm** field.

**To Reproduce**
1. Go to Security & Accounts  ⇒ Institution ⇒ Create New User (https://nbmmnb5523-edge.test.specifysystems.org/specify/security/user/new/)
2. Click on `Set Password`
3. Click on **Confirm Password** field
4. Click on **Password** field and type in at least 2 characters
5. See that characters are inputted into the **Confirm Password field**

**Expected behavior**
All characters inputted into a field should only be in that field.

**Evidence**

https://github.com/specify/specify7/assets/118556884/7c9404be-ba7e-4fb1-a89c-33140ab94bed

**Desktop:**
OS: macOS Monterey (12.6.5)
Browser: Chrome
Specify 7 Version: `edge`

**Database Name:** `nbm_mnb_5_5_23`

**Comment by maxpatiiuk** [comment]
The validation logic was refactored a bit on `xml-editor` - could this be tested there to see if it can be replicated?

---

Caused by the validation triggering too-early OR validation moving focus from one field to another prematurely

**Comment by melton-jason** [comment]
Duplicate of #3603
