### ISSUE TITLE
`xml-editor`: WorkBench error cells not highlighted and do not display the error message

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4450]
**Describe the bug**
Error cells do not display a warning when hovered over

**To Reproduce**
1. Validate a data set
2. See errors
3. Navigate to the error
4. See the cells are not highlighted and no error shows upon hovering

**Expected behavior**

**Screenshots**

`xml-editor` (incorrect behavior):

https://github.com/specify/specify7/assets/37256050/d7a32022-3454-499a-a9a9-b51700e23adb

`edge` (correct behavior):

https://github.com/specify/specify7/assets/37256050/60275ce2-ffca-429f-95ff-3860facd45e8

**Desktop:**
macOS, Arc

https://umherb11024-xml-editor.test.specifysystems.org/specify/workbench/15/
`HerbAdmin` is the user

**Comment by CarolineDenis** [comment]
@maxpatiiuk , 
Would you have an idea where to look for this issue? I have spent quite some time to debug it with luck so far.

**Comment by maxpatiiuk** [comment]
hmm, I'm unable to replicate the issue, the errors display correctly for me:

https://github.com/specify/specify7/assets/40512816/cb944c88-f3c4-4fc5-a13a-8167a9e6a888

(I'm on edge, which was xml-editor at the time this issue was created)

**Comment by CarolineDenis** [comment]
@maxpatiiuk, 
It happens when having more rows. I juste tried with your data set and the bug started after row 53. 
![Screenshot 2024-02-23 at 8 53 12 AM](https://github.com/specify/specify7/assets/108160931/1baa516d-05d2-4573-8c6a-a01749e06da7)
