### ISSUE TITLE
Uniqueness rules configuration: spelling error in leave w/o save confirm dialog 

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4453]
**Describe the bug**

"your" --> "you"
also maybe "would" should be "will"?

<img width="779" alt="Screenshot 2024-01-23 at 8 41 46 AM" src="https://github.com/specify/specify7/assets/135047322/d0d8fc89-9037-4476-8637-888c2982ed81">

**To Reproduce**
1. Go to schema config>uniqueness rules
2. add uniqueness rule
3. click close without saving

**Comment by melton-jason** [comment]
Note: that string is already localized and used in other places in Specify and is not isolated to just configuring Uniqueness Rules

https://github.com/specify/specify7/blob/ee754f7a503cff609a70c002c6e5baf927344f52/specifyweb/frontend/js_src/lib/localization/main.ts#L233-L247

Other usages are: 
- The unload protect dialog when modifying a Role

![image](https://github.com/specify/specify7/assets/64045831/07dfdd0d-1bc4-4308-af28-44e27449d62f)

- The unload protect dialog when modifying an Attachment Dataset

![image](https://github.com/specify/specify7/assets/64045831/00405c83-b59a-46eb-895e-d128e080d261)
