### ISSUE TITLE
Cannot Save after deleting new blank data from entry

### ISSUE THREAD

**Issue by pashiav** [specify/specify7#4459]
**Describe the bug**
When adding then deleting blank information that requires a field to an entry, Save is blocked with no information shown to the user as to why they cannot save.

**To Reproduce**
1. Go to an Agent (https://kufish2023-edge.test.specifysystems.org/specify/view/agent/4526/) 
2. Edit any field to see that Save is allowed 
3. Add a Member
4. Delete that Member
5. See that Save is blocked

**Expected behavior**
Saving should be allowed with the current inputs.

**Evidence**

https://github.com/specify/specify7/assets/118556884/b8bb401f-07b7-4ab1-9c16-c5c38ebfbf6f

OS: macOS Monterey (12.6.5)
Browser: Chrome
Specify 7 Version: `edge`
Database Name: `KU_Fish_2023`

**Comment by CarolineDenis** [comment]
cannot reproduce
@specify/ux-testing can you confirm and close if true

**Comment by emenslin** [comment]
Fixed
