### ISSUE TITLE
`Field 'id' expected a number but got 'null'.` when viewing an accession with accession agents

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4464]
`Field 'id' expected a number but got 'null'.`

**Steps to recreate:**
1. Build an accession query
2. Browse in forms
3. See that an error appears for each accession agent

https://kufishtissue20240124-v793.test.specifysystems.org/specify/query/new/accession/

**Version**
`v7.9.3`
[Specify 7 Crash Report - 2024-01-26T14_25_33.544Z.txt](https://github.com/specify/specify7/files/14065945/Specify.7.Crash.Report.-.2024-01-26T14_25_33.544Z.txt)

**Comment by grantfitzsimmons** [comment]
Related to https://github.com/specify/specify7/issues/3967?

**Comment by realVinayak** [comment]
Should be closed?
