### ISSUE TITLE
Step by Step Specify7 Installation

### ISSUE THREAD

**Issue by sinombre5** [specify/specify7#447]
Hi Guys,

I am trying to install specify7 and the specify web portal on debian 9. But i have many troubles.
I try to follow the steps provided but i always have diferrent errors.
Is there a videotutorial installation of this software?

Thank you in advance for your answers.

Regards.

**Comment by benanhalt** [comment]
@sinombre5 I am afraid we don't have videos addressing installation specifically. If can describe the problems you are experiencing to us via support@specifysoftware.org, it is likely we can assist you.

**Comment by maxxxxxdlp** [comment]
The dockerized version of Specify 7 has fewer installation steps - https://github.com/specify/specify7#installation-with-docker
