### ISSUE TITLE
Admin users can assign their own agent to another user.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#448]
An admin level user can currently change or add another user account to use the agent record currently associated with their own user record, effectively causing their user account to become agentless. Thereafter, they will be unable to login or even load any page.

The agent selection tool should filter out the agent assigned to the currently logged in user to prevent this from happening.

**Comment by maxxxxxdlp** [comment]
Fixed in 7f4fb84a and b2c6e051
