### ISSUE TITLE
Syntax highlighting for `preferences` app resources is missing

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4496]
<img width="2048" alt="image" src="https://github.com/specify/specify7/assets/37256050/6ef1aa75-9769-4bb2-94ad-747efb7e0b39">

https://geology-edge.test.specifysystems.org/specify/resources/app-resource/4/

On the right is `v7.8.9`

**Comment by grantfitzsimmons** [comment]
<img width="1596" alt="image" src="https://github.com/specify/specify7/assets/37256050/a7259900-d814-4de5-939e-e66e02222cae">

The mime type is identical (blank)

**Comment by CarolineDenis** [comment]
NOTES: 
difference between prod and 9.3 
prod: 
<img width="466" alt="Screenshot 2024-02-15 at 1 09 19 PM" src="https://github.com/specify/specify7/assets/108160931/b7670bf1-ea89-4971-b215-7d270c1c9c53">
9.3: 
<img width="248" alt="Screenshot 2024-02-15 at 1 09 43 PM" src="https://github.com/specify/specify7/assets/108160931/157eb8c3-e790-4b5f-9b6d-f8d23d52c558">

**Comment by maxpatiiuk** [comment]
see this:
https://github.com/specify/specify7/blob/issue-4545/specifyweb%2Ffrontend%2Fjs_src%2Flib%2Fcomponents%2FAppResources%2FEditorComponents.tsx#L244-L245

**Comment by CarolineDenis** [comment]
NOTES: 
in 
```ts
const language =
      mode === 'json'
        ? [json(), jsonLinter(handleLinted)]
        : mode === 'properties'
        ? [StreamLanguage.define(properties)]
        : mode === 'jrxml' || mode === 'xml'
        ? [xml(), xmlLinter(xmlSpec?.())(handleLinted)]
        : [];
```
mode === 'txt' for global pref resource

**Comment by maxpatiiuk** [comment]
as per https://github.com/specify/specify7/pull/4556#discussion_r1496804090, the above seems like a bug as mode should be `properties ` for properties files
