### ISSUE TITLE
Value being carried into wrong field in conditional forms when switching

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4497]
**Describe the bug**
When using conditional forms, a value from one form can be incorrectly carried into a different field on another form.

**To Reproduce**

1. Go to the `geology` database (https://geology-edge.test.specifysystems.org/)
2. Go to 'collectionobjectproperties' (Stratigraphies) and add a new record
3. Select 'Magnetostratigraphy' from the 'Stratigraphy' pick list
4. See 'Magnetic Polarity' is filled in by default with "Normal (northward-directed)"
5. Switch to 'Chemostratigraphy'
6. See that Geochecmical Ratio is filled in with "Normal (northward-directed)" despite being a different field

[vertpaleo.views.xml.xml.zip](https://github.com/specify/specify7/files/14216114/vertpaleo.views.xml.xml.zip)

```xml
<cell type="label" label="Geochemical Ratio"/>
<cell type="field" id="GeochemicalRatio" name="text18" uitype="text" colspan="8" default="Normal (northward-directed)"/>
```

```xml
<cell type="label" label="Magnetic Polarity"/>
<cell type="field" id="Mag" name="text14" uitype="text" default="Normal (northward-directed)"/>
```

These are authentically two different fields (in both `name` and `id`. I've seen this behavior with other conditional forms, and it seems to be caused by the fields being in the same 'order' (in this case, they are both the third field in the form definition).

**Expected behavior**
Values should only be carried over when switching between conditional forms **IF** the fields have the same `name` (such as `text1`). 

**Screenshots**

https://github.com/specify/specify7/assets/37256050/d17f2dfd-a08a-4eca-b881-0888e659f8d3

Arc, macOS, `edge` as of Feb 8 2024

**Comment by maxpatiiuk** [comment]
Likely caused by react trying to be efficient and "reusing" the same fields as much as possible
If that is indeed the case, then the fix is as simple as adding a `key` prop to the conditional form container
