### ISSUE TITLE
Problem with missing report images for anonymous users.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#450]
If there is an image referenced in a report, and there has not been an attachment created for it, the dialog to upload an attachment is available to anonymous users. Though if they try to use it, they will receive an exception.

This mechanism should only be presented to logged in (admin?) users.

**Comment by maxxxxxdlp** [comment]
I am not sure why anonymous users would receive an error trying to upload an image. Is it because the csrftoken is not set unless you explicitly signed in?
Is this mitigated by the 7.7.0's permission system?

**Comment by grantfitzsimmons** [comment]
Closing unless this is reported as an issue again.
