### ISSUE TITLE
Adding Preps from Loan record clones existing prep & disregards count availability

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4504]
**Explain the Bug:**

- Adding preparation clones existing preparation
- New preparations can't be added to Loan from Loan form
- Existing preparation counts are exceeded with the cloned additions

**To Reproduce**

1. Go to New Loan
2. Add a preparation
3. By Loan Preparations subform, click `+`
4. See duplicate preparation record added
5. Save

**Expected behavior**

Should open the add preparations dialog prompting to enter cat numbers or choose from record set. 

**Screenshots**

Prep on CO: (note count of 1)

<img width="1669" alt="Screenshot 2024-02-09 at 1 34 52 PM" src="https://github.com/specify/specify7/assets/135047322/2f852835-0cff-43ea-82b1-c6ca8350acce">

On Loan: 

https://github.com/specify/specify7/assets/135047322/4ac39fbc-b96c-4712-ba64-b9568dbdcace

**Crash Report**

If the bug resulted in an error message, please click on "Download Error
Message" and attach it here

Alternatively, please fill out the following information manually:

- OS: macOS
- Browser: Chrome
- Specify 7 Version: `edge`
- Database Name: `fwri_1_9_24`

**Comment by CarolineDenis** [comment]
@bronwyncombs, 
Can you confirm this is fixed on edge?
