### ISSUE TITLE
Aggregation ordering inconsistent between form and queries 

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4510]
**Describe the bug**
Despite there being one aggregation configured, the order of items in the aggregation differs based on whether it is viewed in the query or on the form.

**To Reproduce**
1. Go to https://sp7demofish2924-edge.test.specifysystems.org/specify/query/87/
2. Run the query
3. See the aggregation for "Collectors" in the query results
4. Browse in forms
5. See the aggregation in the "Collectors" field on the CE form

**Expected behavior**
The behavior should be consistent.

Note that in the examples below, the aggregator orders by `isPrimary` and only one collector _is_ primary. That collector is `Abe, Francine`, and they should appear last in the order since the ordering goes from lowest number to highest number (though it would be nice to configure #4507)

**Expected order:** `Caire, M | Bagley, Justin | Abe, Francine`
_Note that this is the order we see in the query builder in both `edge` and `v7.9.3`_

<img width="405" alt="image" src="https://github.com/specify/specify7/assets/37256050/5b9ad546-63ed-453e-9b74-29d2918dd7c6">

https://sp7demofish2924-edge.test.specifysystems.org/specify/resources/app-resource/103/aggregator/Collector/10

### `edge` (xml-editor):
<img width="932" alt="image" src="https://github.com/specify/specify7/assets/37256050/11838235-9e45-498d-ae4d-3d983fbafd0e">

Collectors in query:
`Caire, M | Bagley, Justin | Abe, Francine`

Collectors on the form:
`Bagley, Justin | Caire, M | Abe, Francine`

### `v7.9.3`:
<img width="937" alt="image" src="https://github.com/specify/specify7/assets/37256050/adde7b82-fb54-4959-a7dc-2e24a1f6bbb3">

Collectors in query:
`Caire, M | Bagley, Justin | Abe, Francine`

Collectors on the form:
` |  | `

**Reported By**
[CSIRO on Asana](https://app.asana.com/0/1201972579963460/1206502287128493/f)

<img width="798" alt="image" src="https://github.com/specify/specify7/assets/37256050/2dfa1760-aa23-466d-a307-96a9e91f47d0">

**Comment by maxpatiiuk** [comment]
Query builder does aggregation on the back-end
XML Editors, and Form does it on the front-end
*form sometimes gets aggregation from the back-end too
Thus, these are different implementations and so bugs like this are possible

In this case, it appears that the back-end is not respecting the "Sort Field" option

**Comment by realVinayak** [comment]
> In this case, it appears that the back-end is not respecting the "Sort Field" option

> *form sometimes gets aggregation from the back-end too

To make sure, the problem is this backend (rather than query builder backend)? In that case, I think it will be very very worth it combining the query builder backend formatting with the form aggregation, given the refactoring done in https://github.com/specify/specify7/pull/3545

**Comment by acwhite211** [comment]
It seems that the sub-query generated by SQLAlchemy for the aggregator was using `LIMIT 0`, thus not returning anything.  This might have been the only issue in the code causing the problem, after doing some testing, it seems to be solved.  Still doing some more testing before calling this finished.

**Comment by acwhite211** [comment]
The first problem is that the sub-query generated by SQLAlchemy for the aggregator was using `LIMIT 0`, thus not returning anything.

The other problem is that SQLAlchemy crashes with an error when the collector aggregator's sort fields is set to 'IsPrimary', or any other Boolean field.

Here is the problem query being generated by SQLAlchemy
```sql
SELECT DISTINCT (SELECT IFNULL(GROUP_CONCAT(IFNULL(concat(IFNULL(concat(' ', agent_1.`LastName`), ''), IFNULL(concat(', ', agent_1.`FirstName`), '')), '') ORDER BY collector.`IsPrimary` !=  '| ' SEPARATOR 0), '') AS blank_nulls_1
FROM collector LEFT OUTER JOIN agent AS agent_1 ON agent_1.`AgentID` = collector.`AgentID`
WHERE collector.`CollectingEventID` = collectingevent.`CollectingEventID`) AS anon_1
FROM collectingevent
WHERE collectingevent.`DisciplineID` = 3
LIMIT 0, 40
```

It should be 
`ORDER BY collector.`IsPrimary` !=  0 SEPARATOR ' | '`
instead of 
`ORDER BY collector.IsPrimary !=  '| ' SEPARATOR 0`
also, it would be better to use 
`collector.IsPrimary != FALSE`
instead of 
`collector.IsPrimary != 0`

**Comment by acwhite211** [comment]
It seems like it is setup properly, here in the expression created during the query building process
```
GROUP_CONCAT(IFNULL(concat(IFNULL(concat(:concat_1, agent_1."LastName"), ''), IFNULL(concat(:concat_2, agent_1."FirstName"), '')), '') ORDER BY collector."IsPrimary" != :IsPrimary_1 SEPARATOR :group_concat_1)
```

This seems correct, so it is odd that the parameters substituted ends up being wrong.
```
[parameters: (' ', ', ', ' | ', 0, 3, 40, 40)]
```
