### ISSUE TITLE
Dialogs not returning to proper size after expanding

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4511]
**Describe the bug**
After adding new items to a dialog, it no longer returns to the proper size when something is removed.

**To Reproduce**

1. Go to a dialog with a grid layout (OtherIdentifiers on https://umherb11024-edge.test.specifysystems.org/specify/view/collectionobject/new/)
3. Add new items
4. See it resize
6. See that it does not reduce in size when the items are removed

https://github.com/specify/specify7/assets/37256050/15be69ed-ebf9-445a-b9fd-4ea046145193

Arc, macOS

**Comment by grantfitzsimmons** [comment]
This manifests all over the application, not just in this instance. For example:

https://github.com/specify/specify7/assets/37256050/f9e1ec3c-8e31-463f-80f2-fec2c353c813

Same database. I've never resized the dialogs before. Once it expands, it just doesn't shrink.

**Comment by grantfitzsimmons** [comment]
This might be solved by https://github.com/specify/specify7/pull/4433, and it could be caused by the same underlying issue it was looking to solve, but that PR doesn't fix things entirely.

**Comment by grantfitzsimmons** [comment]
@maxpatiiuk said this on the app resources dialog being too large issue (which may be a duplicate):

> I don't think this is caused by useDialogSize i.e in useDialogSize set a logpoint to see the value of initialSize at least on my machine, the bug is reproducable despite `initialSize` being undefined all the time
> 
> This could be caused by the Loading skeleton temporary increasing the dialog size, and then `useFreezeDialogSize` getting activated to prevent the dialog from shrinking back
> 
> can you verify if that's the case? if so, one possible solution may be to modify useFreezeDialogSize to ignore dialog size shrinking during the first 1s of dialog existence to account for possibility of dialog resizing while content is loading (simple, but a bit hacky, as 1s timeout is not a silver bullet - it might not be enough on slower servers - still, might be good enough for many situations) another solution might be to modify the loading skeleton for this table to be smaller (or to make loading skeletons in tables smaller), or to disable loading skeleton for this particular dialog, or to modify loading skeleton styling so that it takes all the space available, but does not force expand the available space

**Comment by emenslin** [comment]
Dialogs are still remaining remaining in the larger size and do not reduce in size. 

https://github.com/specify/specify7/assets/150940840/8b75af04-b33b-40c8-895d-9b7f654a99cf

https://kufish51623-edge.test.specifysystems.org/specify/view/collectionobject/new/

**Comment by CarolineDenis** [comment]
@maxpatiiuk, wasn't this the behavior you intended to have?
