### ISSUE TITLE
Record Set queries from Edit dialog not scoped to table

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4522]
**Describe the bug**

**To Reproduce**

1. Go to Record Set
2. Click on pencil icon by name
3. Click on `Query` button
4. Click on existing query of a different table 
5. See error

**Expected behavior**

Should scope queries available to use to the table of the Record Set records

**Screenshots**

https://github.com/specify/specify7/assets/135047322/b98686c5-11d2-41a6-87d7-4745d4a694e9

**Crash Report**

[Specify 7 Crash Report - 2024-02-12T15_19_32.661Z.txt](https://github.com/specify/specify7/files/14240082/Specify.7.Crash.Report.-.2024-02-12T15_19_32.661Z.txt)

- OS: macOS
- Browser: Chrome
- Specify 7 Version: `edge`
- Database Name: `fwri_1_9_24`

**Comment by grantfitzsimmons** [comment]
https://github.com/specify/specify7/assets/37256050/28b4fb03-0711-4624-a74e-57b74b55fe14
