### ISSUE TITLE
Web link behavior has changed– prompt now reads field as text

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4525]
**Describe the bug**
On `v7.9.3`, this web link immediately took the user to the URL part + field value.
Now on `edge` this web link prompts the user to enter a value for `altCatalogNumber`, which is not resolved to a field name nor taking the value of the field.

<img width="553" alt="image" src="https://github.com/specify/specify7/assets/37256050/c5f5af04-0ebd-48b5-ae76-a517ed575044">

```xml
  <weblinkdef>
    <name><![CDATA[RBGELivingCat]]></name>
    <desc><![CDATA[]]></desc>
    <baseURLStr><![CDATA[https://data.rbge.org.uk/living/<altCatalogNumber>]]></baseURLStr>
    <args>
      <weblinkdefarg>
        <name><![CDATA[altCatalogNumber]]></name>
        <prompt><![CDATA[true]]></prompt>
        <isEditable><![CDATA[false]]></isEditable>
      </weblinkdefarg>
    </args>
    <usedByList/>
  </weblinkdef>
```

([WebLinks resource](https://herbrbge252024-edge.test.specifysystems.org/specify/resources/app-resource/25/web-link/))

Fundamentally, we need to decide what the behavior of "Prompt field" is. Is it 

**To Reproduce**

1. Go to https://herbrbge252024-edge.test.specifysystems.org/specify/view/collectionobject/35846/?recordsetid=650
2. Scroll down until you see the field "RBGE Living Collection Accession No."
3. Click on the web link button next to the field
4. See the described behavior

**Expected behavior**
It should link out to the site as it did before. 
If `<prompt><![CDATA[true]]></prompt>` is configured (as it is here), it should at least retain the value from the specified field _and_ show the appropriate caption for the field, not just the name of the field entered in the 'Prompt field' definition.

<img width="523" alt="image" src="https://github.com/specify/specify7/assets/37256050/c0c428c6-e46b-4299-aa51-a3dc0722d48f">

This does accurately recreate the behavior in Specify 6:

https://github.com/specify/specify7/assets/37256050/af9592bc-47eb-413d-8fa1-1c72dfd78df5

<img width="445" alt="image" src="https://github.com/specify/specify7/assets/37256050/0d3f2b72-ea39-4bed-9866-4568f9f75deb">

**Screenshots**
<img width="539" alt="image" src="https://github.com/specify/specify7/assets/37256050/2125d4e0-56cb-4d6e-a833-76ff77554faf">

You are shown `altCatalogNumber` verbatim (as it is interpreted as a text string, and `xml-editor` accepts any string as it assumes this is a label) rather than it being interpreted as a field name.

https://github.com/specify/specify7/assets/37256050/009c523a-54c4-4a56-bbe6-76daed0574f3

**Comment by grantfitzsimmons** [comment]
Spoke with @tlammer– seems like we might just need to explain how to make this change so that we are more consistent in the future. May require no code changes.

**Comment by maxpatiiuk** [comment]
> Now on edge this web link prompts the user to enter a value for altCatalogNumber, which is not resolved to a field name nor taking the value of the field.

This is because Specify did not support prompt fields before at all - now it does, so if anything, the behavior should match sp6 closer now.

---


When adding a visual web link editor in Specify 7, I wanted to simplify things (while being compatible with sp6 as much as possible)

So instead of a table with 3 columns, some of which are redundant or unused in some contexts, the Sp7 UI just has a picklist and a single field next to the pick list

> You are shown altCatalogNumber verbatim (as it is interpreted as a text string, and xml-editor accepts any string as it assumes this is a label) rather than it being interpreted as a field name.

For me, it didn't make sense that a field could be referring to a database field, and yet you want to be prompted to edit it when you click on the link.
Either the link is using a field that is stored in the database (and so is somewhere on your form, and is subject to validation if needed), OR, weblink asks you for some field on the fly, in which case the web link definition then specifies what to prompt the user for in the dialog.

Does this sound good?

If needed, we could rename the "Prompt field" in the UI to something else that differentiates it more from database fields. Maybe "Prompt user" or "Prompt dialog"

**Comment by grantfitzsimmons** [comment]
Prompt field should definitely be renamed, but I think it makes sense that the user would need to configure this in the WebLinks app resource instead. I think this may be a case of something we supported historically that we should just break instead of trying to support in some unclear way. 

Ultimately, I would be willing to fix these for users who configured it this way, but it might take a non-insignificant amount of time/effort from our team. I'd like to better determine the scope, but I do think the number of users affected will be minimal at this time.

**Comment by maxpatiiuk** [comment]
If we decide that prompt field is not useful, I am fine with letting it go
I was just going under the assumption that if it was in sp6 and not in sp7 then it's a missing feature that must be added to close the gap, and to help people migrate

**Comment by grantfitzsimmons** [comment]
Based on our development discussion and feedback from Andy, it looks like we should just drop support for this feature. It doesn't seem that this provides much value and adds confusion.

**Comment by grantfitzsimmons** [comment]
@emenslin Can you verify that the behavior is now as it was before in the example above?

**Comment by emenslin** [comment]
>  Can you verify that the behavior is now as it was before in the example above (no prompt)?

@grantfitzsimmons yes the weblink now takes you to an actual link instead of just showing text.

**Comment by grantfitzsimmons** [comment]
Thank you so much! 😄
