### ISSUE TITLE
Invalid cells in WB remain red even after they have been corrected  

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify7#454]
Invalid cells remain red after corrections have been made. Red highlight only goes away after corrections have been saved and dataset revalidated.

**Comment by timo11** [comment]
Seven's wb doesn't validate as you edit. The only way it knows the cells have been corrected is by saving and revalidating.

**Comment by maxxxxxdlp** [comment]
Fixed in 7.6.00
Live validation is achieved though "Data Check"
