### ISSUE TITLE
Workbench Scroll bar is buggy

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#455]
This may only be a problem in Windows, but sometimes the scrollbar at the bottom of a workbench dataset will either no appear or it will appear in the space under the Windows Taskbar. Users may think that there just isn't a scrollbar at all. I also have only been able to get this to happen in Chrome. It happens sometimes in VIMS Fish.

**Comment by maxxxxxdlp** [comment]
Fixed in 7.6.00
