### ISSUE TITLE
Disposal workflow changed, can't add unassociated item

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4559]
**Describe the bug**

On `v7.9`, creating a new Disposal takes you straight to the record and you add preparations from there. It looks like this: 
<img width="931" alt="Screenshot 2024-02-19 at 12 53 29 PM" src="https://github.com/specify/specify7/assets/135047322/ddcfc630-c3b2-4cc4-bb4e-ac70813b55b2">

On `edge`, selecting Disposal from the Interactions dialog prompt something similar to the add preparations dialog for Loans or Gifts. The difference here is that you don't have the option to add unassociated items. 

<img width="964" alt="Screenshot 2024-02-19 at 12 54 58 PM" src="https://github.com/specify/specify7/assets/135047322/25a8f620-b383-4dc4-ae3e-cad8badb9a62">

You can still add unassociated items once in the record like in `v7.9`, but the creating workflow is different and i'm not sure if it was intentional. 
<img width="964" alt="Screenshot 2024-02-19 at 12 55 26 PM" src="https://github.com/specify/specify7/assets/135047322/994bf6d9-5f0e-4001-8d56-8d851a00df71">

I think changing the beginning steps of making a Disposal to match other Interactions like Loans and Gifts with the Add Items dialog does make sense, but leaving out unassociated items is inconsistent behavior. 

- OS: macOS
- Browser: Chrome
- Specify 7 Version: `7.9.3.1`, `edge`
- Database Name: `fwri_1_9_24`

**Comment by grantfitzsimmons** [comment]
Disposals should not be created without any items. We need to revisit this when the Deaccession system is implemented.
