### ISSUE TITLE
WorkBench Results button broken

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4563]
**Describe the bug**

https://github.com/specify/specify7/assets/135047322/8795d6c4-5dba-484c-bf89-2d6e2e282204

**To Reproduce**

1. Go to data set in workbench
2. Click on Results button

**Expected behavior**

It's supposed to open a "side panel" which tells you how many records were created and of what table(s)

**Screenshots**

- OS: macOS
- Browser: Chrome
- Specify 7 Version: `v7.9`, goes back to at least `7.8.0`
- Database Name: [e.g. kufish] (you can see this in the "About Specify 7" dialog)

**Additional context**
Database name or any other context about the problem here.

<img width="911" alt="Screenshot 2024-02-19 at 2 19 54 PM" src="https://github.com/specify/specify7/assets/135047322/3edf5f71-244d-4188-962a-bbfccd35296b">

**Comment by emenslin** [comment]
Can recreate in edge (7.9.6) seems to mostly happen with larger datasets but does happen sometimes with smaller ones

**Comment by grantfitzsimmons** [comment]
I don't think this is an issue– seems like it may have to do with no new cells being shown. In the video, there are only error cells, so results only work if the data set has been validated and the WB recognizes that new records are going to be created.
