### ISSUE TITLE
Convert js to ts files

### ISSUE THREAD

**Issue by CarolineDenis** [specify/specify7#4573]
From @maxpatiiuk in https://github.com/specify/specify7/pull/4558#issuecomment-1953453957:
> After spending several hours trying to resolve the build issues from https://github.com/specify/specify7/actions/runs/7963889013/job/21740345853, I got these results:
>
> As a workaround for https://github.com/privatenumber/tsx/issues/38, converted .js files to .ts
> But also, it's time for those to be TypeScript
> Note, I added // @ts-nocheck to the top of the files to suppress
> TypeScript errors for now, but this should be removed once we move way from Backbone
> Refactored our configs to use ESM over Common JS because I wasn't able to get swc-node to work.
> tsx however works fine when using "type": "module" in package.json.
> And it's about time to convert to ESM anyway - while there would still be some friction expected, going forward, there > would be more friction from not using ESM than using ESM
> Fix issues with Leaflet in node.js. See commit comment in https://github.com/specify/specify7/commit/342a727f5b1cc63b037e64d0ace54b2e37b63d17

**Comment by maxpatiiuk** [comment]
This issue is redundant with https://github.com/specify/specify7/issues/4286
