### ISSUE TITLE
Collectors subform showing up as read only 

### ISSUE THREAD

**Issue by emenslin** [specify/specify7#4578]
**Describe the bug**
In the collection object form when opening the collectors subform it shows up as read only fields and you have to expand to be able to type anything. 

**To Reproduce**

1. Go to collection object form
2. Click on the collectors subform 
3. See error

**Expected behavior**
The form should open up as fields that can be typed in without having to expand the form 

**Screenshots**
Edge behavior vs 7.9.3

https://github.com/specify/specify7/assets/150940840/2ca21cbe-8965-4998-ae3c-4a68812b8912

Alternatively, please fill out the following information manually:

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: lsumzmammals9823

**Comment by CarolineDenis** [comment]
NOTES: 
the onAdd function in RecordSelector.tsx is being called but should not 
https://github.com/specify/specify7/blob/ea626945cd30ae3cb331ec03d1083ac0ed44da46/specifyweb/frontend/js_src/lib/components/FormSliders/RecordSelector.tsx#L124
