### ISSUE TITLE
Cannot set checkbox to default to true

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4580]
**Describe the bug**
When configured, a checkbox field defaulting to true is not being respected.

**To Reproduce**

1. Add this row to the Locality form:
   
   ```xml
   <row>
       <cell type="label" label="Yes No BOX"/>
       <cell type="field" id="testYesNo" name="yesNo1" uitype="checkbox" default="true" colspan="3"/>
   </row>
   ```
   
2. Clear browser's cache
3. Go to the form
4. See that the `default="true"` is not being respected.

**Expected behavior**
It should be checked!

**Screenshots**
<img width="1912" alt="image" src="https://github.com/specify/specify7/assets/37256050/e4ee9126-2255-4145-ac46-7048d816cd19">

**Version**
`v7.9.3.1`, need to verify on `edge`

**Comment by CarolineDenis** [comment]
cannot reproduce in edge
