### ISSUE TITLE
Allow setting a default value for boolean/checkbox fields

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4581]
> Is it possible to set a default value for a yesNo tickbox? When viewing an unticked box on a form it is impossible to know if the database value is NULL or 0 - this can cause users to not find all the relevant data if they don't set up the query correctly. This could be fixed if we could set the default value to 0 for unticked boxes but we don't see a way to do that via the form xml? (Having three possible values for a binary result is a little counter-intuitive!)

**Reported by:** CSIRO in October 2022

>These nullable Boolean fields appear to currently operate differently in Specify 6 versus 7 when checkboxes are not explicitly checked on record creation. When new records are created in Specify 6, the checkboxes default to No whereas in Specify 7, they default to null/blank.
>
>From the user perspective, it would be better to have the two versions operate as similarly as possible in the default configuration. 

**Reported by:** Garth at University of Michigan in February 2024

**Comment by grantfitzsimmons** [comment]
**After investigation:**
`uitype="checkbox" default="false"` and `default="0"` result in a `NULL` value in the database. The only way to make sure the value is `0` is to intentionally check and uncheck the box, which is not awesome.

**Comment by maxpatiiuk** [comment]
Yay, you just created an issue with the longest title in the specify's history
