### ISSUE TITLE
Deleting a WebLink is Allowed to a user with read-only permissions

### ISSUE THREAD

**Issue by pashiav** [specify/specify7#4586]
**Describe the bug**
Logged in as a user with read-only permissions, in App Resources, the user is shown and can click the **Delete** button to remove Web Links. 

**To Reproduce**
1. Log in as a user with read-only permissions (user: `guest`, db: `KUFish_5_16_23`)
2. Go to WebLinks (https://kufish51623-edge.test.specifysystems.org/specify/resources/app-resource/8/web-link/)
3. Click any Web Link 
4. Click **Delete** and see that it removes the link from the list

**Expected behavior**
There should not be a **Delete** button at all for read-only users. Otherwise, on-click there should be a pop up that lets the user know that they do not have sufficient privileges.
**Note**: User cannot save the change after deleting a link since there is no **Save** button.

**Evidence**

https://github.com/specify/specify7/assets/118556884/ddeddceb-460c-4687-8c21-47d6593b19ba

OS: macOS Monterey (12.6.5)
Browser: Chrome
Specify 7 Version: `edge`
Database Name: `KUFish_5_16_23`

**Comment by CarolineDenis** [comment]
Fixed in https://github.com/specify/specify7/pull/4612
