### ISSUE TITLE
bug(FormEditor): deleted form offered in the "Create" dialog

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#4590]
1. Create a form
2. Save it
3. Delete it
4. Click on the "Create" button again - the form created in step 1 and deleted in step 3 is offered in the list of forms

![Screenshot 2024-02-27 at 19 46 51](https://github.com/specify/specify7/assets/40512816/89831c46-9c4e-4741-9aa0-08ce424b8ada)

v7.9.4, kufish

**Comment by CarolineDenis** [comment]
cannot reproduce anymore in edge.
