### ISSUE TITLE
Incorrect tree rank is being set during editing and creation of tree records

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4598]
UPDATE from @grantfitzsimmons:

I was able to recreate it thanks to more information provided by CSIRO. 

**This is something that must be resolved before 7.9.4 is released.**

Presumably introduced in https://github.com/specify/specify7/pull/4462?

<img width="2048" alt="image" src="https://github.com/specify/specify7/assets/37256050/85f6a5fe-0cd6-4b4a-af7a-39c9607e2dc5">

Left is [v7.9.2](https://kufish212-v792.test.specifysystems.org/specify/tree/taxon/?conformation=%7E%7E1%7E15797%7E17025%7E5%7E21%7E135%7E685%7E10135---------), right is [edge](https://kufish212-edge.test.specifysystems.org/specify/tree/taxon/?conformation=~~1~15797~17025~5~21~135~685~10135---------)

Notice that the taxonomic rank is shifted one rank over (so even though `brevirostrum` is a node at the 'Species' rank, it shows 'Subspecies'.

Despite this, a query will return the correct rank as expected.

<img width="991" alt="image" src="https://github.com/specify/specify7/assets/37256050/62bf103b-f445-46c6-8f7d-6c41b3d56da0">

When you select a node in the tree, you will see immediately that it is "unsaved", indicating that there have been changes made. Unfortunately, this change is that Specify tries to change the rank by default.

https://github.com/specify/specify7/assets/37256050/b963d350-216f-4852-b97b-8a4fd952766f

Once saved, it updates the rank and now it is incorrect.

**Reported by:** Corinna at CSIRO ([Asana](https://app.asana.com/0/1201972579963460/1206699861047218/f))

---

Original description by @bronwyncombs:

> This might already be on your radar as we observed this in our Sandbox environment which is on the edge version. We are not seeing this in the stable 7.9.3.1 release.
> 
> We have noticed that the taxon rank displayed in the tree doesn’t align with the taxonomic rank displayed when you open the taxon node in Edit mode. We have seen this in fish, insect and wildlife – all collections have different numbers of taxon ranks. In the insect collection we have seen this go down all the way to Species being displayed as ‘subspecies’ in the Edit screen.
> 
> ETA: I just ran a quick query and data is fine there, so it seems to be an issue with the rank being pulled into the taxon node screen.
> ![image](https://github.com/specify/specify7/assets/135047322/bd7d81e2-ce8b-4ba0-ad8f-d0efde695b41)
> ![image](https://github.com/specify/specify7/assets/135047322/e812c3ef-18cf-40ae-84cd-89530ca621c7)
> ![image](https://github.com/specify/specify7/assets/135047322/b54c0004-8137-4faf-8964-cbcb0554ee6d)
> ![image](https://github.com/specify/specify7/assets/135047322/3b87efaa-746f-4e41-a806-b87d8a6a49c6)

---

I haven't been able to recreate, but given the nature of this but I figured it should be reported for dev assessment.

**Comment by grantfitzsimmons** [comment]
I was able to recreate it thanks to more information provided by CSIRO. 
This is something that must be resolved before 7.9.4 is released.

<img width="2048" alt="image" src="https://github.com/specify/specify7/assets/37256050/85f6a5fe-0cd6-4b4a-af7a-39c9607e2dc5">

Left is [v7.9.2](https://kufish212-v792.test.specifysystems.org/specify/tree/taxon/?conformation=%7E%7E1%7E15797%7E17025%7E5%7E21%7E135%7E685%7E10135---------), right is [edge](https://kufish212-edge.test.specifysystems.org/specify/tree/taxon/?conformation=~~1~15797~17025~5~21~135~685~10135---------)

Notice that the taxonomic rank is shifted one rank over (so even though `brevirostrum` is a node at the 'Species' rank, it shows 'Subspecies'.

Despite this, a query will return the correct rank as expected.

<img width="991" alt="image" src="https://github.com/specify/specify7/assets/37256050/62bf103b-f445-46c6-8f7d-6c41b3d56da0">

When you select a node in the tree, you will see immediately that it is "unsaved", indicating that there have been changes made. Unfortunately, this change is that Specify tries to change the rank by default.

https://github.com/specify/specify7/assets/37256050/b963d350-216f-4852-b97b-8a4fd952766f

Once saved, it updates the rank and now it is incorrect.

**Comment by grantfitzsimmons** [comment]
Same issue across other trees.

https://kufish212-edge.test.specifysystems.org/specify/tree/geography/?conformation=~~1~1732~1735-~1745~1746-~1755~1756--~1748-----

<img width="1000" alt="image" src="https://github.com/specify/specify7/assets/37256050/12d3ca28-265a-4ef6-b0c3-6296d642aace">
