### ISSUE TITLE
Blank cell type not accepted in visual editor

### ISSUE THREAD

**Issue by emenslin** [specify/specify7#4599]
**Describe the bug**
When trying to enter a blank cell type in visual editor it does not let you save but in XML editor and 7.9.3.1 it does work.

**To Reproduce**

1. Go to form definition 
2. Have visual editor on
3. Add a blank cell type 
5. Switch to XML editor
6. See you can save 

**Expected behavior**
You should be able to save a blank cell type without issue. 

**Screenshots**

https://github.com/specify/specify7/assets/150940840/25242413-b804-4362-a6f3-3218a1aebf61

Alternatively, please fill out the following information manually:

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: lsumzmammals9823

**Comment by CarolineDenis** [comment]
@maxpatiiuk, 
Is adding blank here ok? 
https://github.com/specify/specify7/blob/9044ffc1e29eea13e1d18ccf20cad10ef5290978/specifyweb/frontend/js_src/lib/components/FormEditor/viewSpec.ts#L75

**Comment by maxpatiiuk** [comment]
ups, this is an oversight - I forgot to add it

yes, add it there, and then here too https://github.com/specify/specify7/blob/9044ffc1e29eea13e1d18ccf20cad10ef5290978/specifyweb/frontend/js_src/lib/components/FormEditor/viewSpec.ts#L84
