### ISSUE TITLE
Make the formatter picklist UI more apparent as a picklist in the aggregator formatter menu

### ISSUE THREAD

**Issue by acwhite211** [specify/specify7#4614]
**Describe the bug**
I created a new DataObjFormatter, set is as "The Default Table Formatter", and save it.  I then went to the query builder and re-ran the query, but the same aggregator was being used.  It didn't switch over to using the new default aggregator until I deleted the old one.

I tried doing this again, and when I created the new formatter and checked it as default at the sametime, the change was reflected when rerunning the query.  But, then when I went to switch the default formatter back to the original (and pressed save), the change was not reflected when rerunning the query.

The DataObjFormatter UI seems to reflect the default formatter has been changed, but I suppose the default value might not be updated in the database.

**To Reproduce**

0. Tested on edge with the sp7demofish_2_9_24 database
1. Go to App Resources -> Record Formatters -> Collector -> Add
2. Press the "Save" button.
3. Create a "Collecting Event" query, and select "Collectors -> aggregated"
4. Try switching the default table formatter between the two (make sure to press Save), and see that when a new query runs, the field formatting in the query results remains unchanged.

**Expected behavior**
The fields in the query builder should be using the updated default formatting.

**Screenshots**
![image](https://github.com/specify/specify7/assets/2774057/5448ee73-9002-4936-b6d4-bcd7ee8a50f5)
![image](https://github.com/specify/specify7/assets/2774057/9e140bdc-dc1e-4d95-9fb1-72ab259b4379)
![image](https://github.com/specify/specify7/assets/2774057/341cb1a2-3ff7-4d8a-9a9e-30956930d1f5)
![image](https://github.com/specify/specify7/assets/2774057/3a906392-576e-471a-8afc-7b5160648e45)
![image](https://github.com/specify/specify7/assets/2774057/7fe5b42f-5f61-4386-8fed-77c64604147e)

Alternatively, please fill out the following information manually:

- Specify 7 Version: edge (7.9.4 pre-release, after xml-editor merge)
- Database Name: sp7demofish_2_9_24
- Collection name:  KU Fish Voucher

**Comment by acwhite211** [comment]
This might just be a cache issue.  Will re-test.

**Comment by realVinayak** [comment]
I doubt it is a cache issue. This is a backend problem not a frontend one. it doesn't look up by default anywhere [here](https://github.com/specify/specify7/blob/production/specifyweb/stored_queries/format.py). Any change by frontend is immediately visible by backend, cmon.

Try swapping the definitions in xml. I suspect [it](https://github.com/specify/specify7/blob/0e4f46c5a5234cc9d62f0524e07d3d1cd908883f/specifyweb/stored_queries/format.py#L52-L72) takes whatever the first is incase of two.

**Comment by grantfitzsimmons** [comment]
This was reported on the forum by Taylor at the Florida Museum:

> Several of our collections have multiple table aggregators assigned to various tables. We use these in the label and reports, most importantly. When I run a query in Specify 7 the first one defined in the DataObjectFormatter xml for that table, is always used, even if it is not the default. In Specify 6, the way we set a non-default aggregator in a query, was to export it, modify the ‘formatName’ attribute of the xml node for that field, then re-import the query. When I try the same thing in the json of an exported query, then re-import it, it ignores the change and the first aggregator defined in the DataObjectFormatter is still used. I have found a workaround by just moving the default aggregator in the DataObjectFormatter to be the first in order, but would like to know if there is a way to assign other aggregators to aggregated query fields. I don’t seem to figure out a way to do that, or maybe I’m ignoring something.

https://discourse.specifysoftware.org/t/specify-7-and-multiple-table-aggregators-in-queries/1604

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-and-multiple-table-aggregators-in-queries/1604/2

**Comment by acwhite211** [comment]
After looking through the code, it seems that this is the intended behavior.  Each aggregator has a 'format' field that points to the name of the formatted to use.  So, instead of using the default formatted for that table type, it uses the one specifically specified for that aggregator.

```xml
<aggregator name="Collector" title="Collector" class="edu.ku.brc.specify.datamodel.Collector" default="true" separator=" | " ending="" count="0" format="Collector" orderfieldname="orderNumber"/>

<format name="Collector (Old)" title="Collector" class="edu.ku.brc.specify.datamodel.Collector" default="true">
		<switch single="true">
			<fields>
				<field sep=" ">text1</field>
				<field sep="  - ">agent.lastName</field>
			</fields>
		</switch>
	</format>
	<format name="Collector" title="Collector (2)" class="edu.ku.brc.specify.datamodel.Collector" default="">
		<switch single="true">
			<fields>
				<field sep=" ">agent.lastName</field>
				<field sep=" , ">agent.firstName</field>
			</fields>
		</switch>
	</format>

```

___

Maybe to make this a little more clear in the xml editor, you could make the 'Formatter' textbox look more like a picklist by adding the dropdown arrow symbol, like the 'Sort Field" option has.
![image](https://github.com/specify/specify7/assets/2774057/6ba092e7-23c8-4603-83c3-9b757a8f8d6b)
![image](https://github.com/specify/specify7/assets/2774057/2b0188f6-559c-4d3d-8a40-267db1d15838)

**Comment by CarolineDenis** [comment]
Arrow already present when hover 
![Screenshot 2024-03-19 at 6 35 53 AM](https://github.com/specify/specify7/assets/108160931/ea174a7f-5a2d-4687-ba49-ec0f67100fe0)
