### ISSUE TITLE
Can't upload large datasets into Workbench

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#462]
In Specify 6, you can upload datasets with 70 columns but Specify 7 does not allow it.
Requested by Willem

**Comment by maxxxxxdlp** [comment]
Fixed in 7.6.00

Tested Data Sets with up to 200 columns
Tested Data Sets with 18,000 rows and 50 columns
The performance starts to diminish for Data Sets with 800,000 cells and more (as tested on my machine)
