### ISSUE TITLE
Non-functional trash icon appears below "Add Field" when no fields are added to a table format

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4621]
https://github.com/specify/specify7/assets/37256050/f9f8816c-6ce5-462e-911b-4b6e57ea0f4a

https://umherb11024-issue-1959.test.specifysystems.org/specify/resources/app-resource/92/formatter/CollectingEvent/58
User `HerbAdmin` in `herbarium_catalog` collection

**Describe the issue:**
Immediately upon creating a new table format, the user sees a trash can icon below "Add Field". This also appears if no fields are added to a table format or all fields are removed.

This has no function and should be removed.

**Steps to recreate:**
1. Add a new table format
2. See the trash can appears under "Add Field"
3. It should not be there

**Comment by emenslin** [comment]
It's back 
<img width="959" alt="Screenshot 2024-03-14 095140" src="https://github.com/specify/specify7/assets/150940840/d5f2f882-538c-4a14-a967-849a4bd74523">

**Comment by CarolineDenis** [comment]
@emenslin, yes I know it's fixed in: https://github.com/specify/specify7/pull/4648
(You reviewed it yesterday)
