### ISSUE TITLE
Remove "Default" from table format and aggregation after 6

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4651]
> After 7.9.4

**Describe the bug**
Specify insists that you need to set a "default" table format. The question is why? Is this a fallback in case there is not a format/aggregation defined in the schema?

Users are expected to choose a "default" table format in Specify, but as far as I can tell, this really shouldn't be user-configurable in 7 as it does nothing in this version.

In Specify 6, every table with a format is required to have one be "default", but not every table has a format. The "default" format seems to have already decided by the application, and if there is no format, there is simply no reason to have one.

![image](https://github.com/specify/specify7/assets/37256050/032c4424-89f8-4bc1-bf59-58cc3aa04160)

* Query combo boxes use the schema-assigned table format
* Query results use the schema-assigned table format

It seems redundant and confusing to have both options visible to the user if 7 is consistent in using the schema-assigned format.

**Solution:**
After Specify 6 is no longer used with the same database as Specify 7, we should remove this "default" option as it is confusing and unnecessary in 7.

**Comment by grantfitzsimmons** [comment]
Upon further review, this is the default an aggregator would use upon construction. Maybe it does have some value... though I am confused why it is defined in two places. Something to consider re-doing in the future.

**Comment by maxpatiiuk** [comment]
I think the purpose of default is to allow formatting the resource without forcing everyone to specify which formatter then want to use.

This is also nice as you can modify which is the default, without having to update all the usages of the previous formatter.

Though in practice, if there is a place that requires an explicit formatter to be chosen, that place may need to be modified to make it optional
