### ISSUE TITLE
Disposals do not impact the actual count and count available of preparation records

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4655]
In Specify 6, disposals would update the actual count and count available of preparations that were linked to them. 

When a disposal has a disposal preparation, the counts should be affected similar to when loan preparations are linked to preparations.

**Reported by:** Royal Botanic Garden Edinburgh and many other users

**Comment by grantfitzsimmons** [comment]
<img width="1505" alt="image" src="https://github.com/specify/specify7/assets/37256050/d0fb5a71-7d75-4905-b6a8-737ec627d63f">

After reviewing the behavior, creating a disposal prep seems to impact the count appropriately

**Comment by melton-jason** [comment]
Implemented in https://github.com/specify/specify7/commit/0c11698b26f0d3167f332343f925e30c192292d7 (`v7.9.0`)
