### ISSUE TITLE
Unsaved changes/new records are preserved during data entry in trees 

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4667]
**Describe the bug**

Another issue where reverting behavior is necessary

**In `v7.9.3.1`:**

https://github.com/specify/specify7/assets/135047322/486a67a3-a07f-4779-8a5f-a7b506b3428e

- unsaved record is not preserved
- re-opening record with pencil icon takes you to record for the node

**In `edge`:**

https://github.com/specify/specify7/assets/135047322/928307f1-35d8-4e11-b333-f5d8b6803ab6

- unsaved record is preserved
- re-opening node record with pencil icon takes you to new empty record
- selecting another node and then going back to the original one clears this and the pencil icon opens the record with information again

---

**Environment:**
- OS: macOS
- Browser: Chrome
- Specify 7 Version: `edge`
- Database Name: `KU_Fish` and `KUBirds`
- Collection name: KU Fish Tissue, Ornithology

**Comment by CarolineDenis** [comment]
This is known new behavior, happens since #4347 
If they save, the tree refreshes, and so we have no such issue
If they didn't save, opening Edit again, kind of makes sense that they would see the new resource as they didn't finish it
