### ISSUE TITLE
Choosing Parent of taxon record does not auto populate Rank

### ISSUE THREAD

**Issue by pashiav** [specify/specify7#4676]
**Describe the bug**
When creating a new taxon record and choosing a Parent, the Rank field does not auto populate. 
From #4462, https://github.com/specify/specify7/pull/4462#issue-2100900341:

> - wait a few seconds for the taxonomic rank to be populated 

**To Reproduce**
1. Create Taxon record (https://umherb11024-edge.test.specifysystems.org/specify/view/taxon/new/)
2. Choose a Parent (ex: Fungi)
3. Wait a few seconds and see that Rank field stays empty

**Expected behavior**
Rank field should be auto populated with the correct rank when choosing a Parent.
Expected behavior from `v7.9` | Behavior on `edge`:

https://github.com/specify/specify7/assets/118556884/a5a8ebdf-6492-405f-8ac6-ae7b869e1c12

OS: macOS Ventura (13.2.1)
Browser: Chrome
Specify 7 Version: `edge`
Database Name: `umherb_1_10_24`

**Comment by melton-jason** [comment]
Should be fixed in #4665

**Comment by CarolineDenis** [comment]
@emenslin can you verify that this is fixed in https://github.com/specify/specify7/pull/4665 ?
Thanks!

**Comment by emenslin** [comment]
> @emenslin can you verify that this is fixed in #4665 ? Thanks!

@CarolineDenis Yes this issue is fixed in #4665
