### ISSUE TITLE
Circular table formats not detected/handled 

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4687]
**Describe the bug**
from issue #3266:

>  I.e, if accession includes accession agent formatter, and accession agent formatter includes accession formatter.
> 
> The fix:
> If the same resource appears the 2nd time in the formatting, exclude relationship fields from the formatter (thus, Accession will be formatted, Accession -> Accession Agents will be formatted, Accession -> Accession Agents -> Accession -> Accession Number will be formatted, but Accession -> Accession Agents -> Accession -> Accession Agents won't be
> 
> With the formatter/aggregator editor being available and so easy to use, and showing a live preview of formatter on any change, this issue is far more likely to happen. And once it does, the front-end will be rapidly sending requests to the back-end.

**To Reproduce**

Create an Accession format like this:

<img width="1508" alt="Screenshot 2024-03-25 at 3 01 32 PM" src="https://github.com/specify/specify7/assets/135047322/0595c122-fbe9-4516-aec3-c54f9bbeb51d">

And an Accession Agent format like this: 

<img width="1423" alt="Screenshot 2024-03-25 at 3 12 01 PM" src="https://github.com/specify/specify7/assets/135047322/6194ef5e-1c80-4807-b6af-c5a1d7aed7cd">

Query with these fields (formatted) & see the problem in results: 

<img width="1747" alt="Screenshot 2024-03-25 at 3 01 22 PM" src="https://github.com/specify/specify7/assets/135047322/820eaed8-9cdc-41cc-b16e-be17e1b71699">

**Expected behavior**

Results should display in query builder like they do on the "Preview" section of the table format dialog 

Not totally sure if it should prevent creating a "circular" table format like this, or just handle it differently/better ... 

- OS: macOS
- Browser: Chrome
- Specify 7 Version: `edge`
- Database Name: `herb_rbge_2_5_2024`
- Collection name: Herbarium

**Comment by maxpatiiuk** [comment]
Front-end has logic that short-circuts the formatter as soon as a cycle is detected
Back-end (which is used for query results) does not have such logic yet.
I am not too familiar with back-end implementation, but I am assuming it would just need to not generate the sql command recursively once it detects that it visited the same relationship again, thus short-circuiting the cycle
