### ISSUE TITLE
Grid view not showing headings by default

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4692]
**Describe the bug**
In `v7`, grid view shows a heading above a list of records. In `edge`, this heading is missing, but can return if you expand and collapse a grid subview.

**To Reproduce**

1. Go to https://fitznhmaoct2023-edge.test.specifysystems.org/specify/view/collectionobject/608836/
2. See there is no heading above the record in **Preparations**
3. Expand "Preparations"
4. Collapse "Preparations"
5. See that the heading now appears

**Expected behavior**
It should be visible at all times as it was in `v7`.

In `v7`:

https://github.com/specify/specify7/assets/37256050/23a57ab9-e00c-476f-8426-9160416cfede

https://fitznhmaoct2023-v7.test.specifysystems.org/specify/view/collectionobject/608836/

**Screenshots**

In `edge`:

https://github.com/specify/specify7/assets/37256050/0e30a636-efbc-4086-8d48-a9f62d12a193

https://fitznhmaoct2023-edge.test.specifysystems.org/specify/view/collectionobject/608836/

**Comment by CarolineDenis** [comment]
@maxpatiiuk , 

This change is due to https://github.com/specify/specify7/pull/4546
Can we change the classes and always have them visible?

**Comment by maxpatiiuk** [comment]
> In v7, grid view shows a heading above a list of records. In edge, this heading is missing, but can return if you expand and collapse a grid subview.

Hmm, I might be not seeing it right, but both videos seem to have the same behavior:
- Heading not visible when there is only 1 row and that row is expanded
- Heading visible in other cases (i.e when row is collapsed)

Where is the bug?

**Comment by grantfitzsimmons** [comment]
> Hmm, I might be not seeing it right, but both videos seem to have the same behavior:
> 
> * Heading not visible when there is only 1 row and that row is expanded
> * Heading visible in other cases (i.e when row is collapsed)
> 
> Where is the bug?

Before expanding in `edge`, see no header:

<img width="519" alt="image" src="https://github.com/specify/specify7/assets/37256050/9cf068f2-0c02-43df-9e3f-f0877671c8a6">
