### ISSUE TITLE
Choosing a picklist item prevents form from being saved

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4693]
**Describe the bug** 
After selecting a pick list item in this instance, the form can not be saved. This is not something I can recreate every time, but after one or two refreshes it happens. This pick list in particular is affected, and cannot recreate in `v7`.

**To Reproduce**

1. Go to https://fitznhmaoct2023-edge.test.specifysystems.org/specify/view/collectionobject/608836/
2. Add a new "Col Obj Attribute" record
3. Choose an item from the "Sex" pick list
4. See that the Save button is blocked

**Expected behavior**
It should allow you to save after selecting a value from the pick list. It should also indicate _why_ it is blocking the save.

**Screenshots**

https://github.com/specify/specify7/assets/37256050/f323d3c0-97d0-4dd7-8912-aa314f992b20

[Specify 7 System Information - 2024-03-27T18_27_51.565Z.txt](https://github.com/specify/specify7/files/14779952/Specify.7.System.Information.-.2024-03-27T18_27_51.565Z.txt)

**Comment by CarolineDenis** [comment]
@grantfitzsimmons I cannot reproduce (same db same users etc)

**Comment by grantfitzsimmons** [comment]
https://github.com/specify/specify7/assets/37256050/b49602c8-0689-452d-8220-ea111944dc82

I am able to recreate. Arc browser in Chromium Engine Version 123.0.6312.59

**Comment by CarolineDenis** [comment]
@grantfitzsimmons , @specify/ux-testing, 
Can we recreate that with a new CO or another one than #10? 
Can we recreate that with another db? 
I tried several ways again and never run into the issue

**Comment by grantfitzsimmons** [comment]
> @grantfitzsimmons , @specify/ux-testing, 
> 
> Can we recreate that with a new CO or another one than #10? 
> 
> Can we recreate that with another db? 
> 
> I tried several ways again and never run into the issue 

I have been able to recreate on this instance consistently every time both in Arc and the latest version of Chrome. If there's anything I can provide, let me know!
