### ISSUE TITLE
Date picker does not fully occupy the space provided in grid view when using "full date" precision

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4707]
**Describe the bug**
The date picker does not fully occupy the space provided in grid view when using "full date" precision.

Not necessarily something we need to resolve by the release of `v7.9.4`, but need to make a note. Different behavior than in `v7.9.3.1`.

**To Reproduce**
_This is all with the accessible date picker enabled._

1. Go to a subview that is displayed as a grid with a date field visible
2. Add a record with a full date
3. Add a record with a day/month precision
4. Collapse into grid view
5. See sizing inconsistency

**Expected behavior**
The width of the date picker should be consistent between precisions when viewed in a grid.

**Screenshots**
Left is `v7.9.3.1` ([link](https://fitznhmaoct2023-v7.test.specifysystems.org/specify/view/collectionobject/729345/)), right is `edge` ([link](https://fitznhmaoct2023-edge.test.specifysystems.org/specify/view/collectionobject/729344/))
<img width="1807" alt="image" src="https://github.com/specify/specify7/assets/37256050/01a4bca2-a988-4b19-bb5c-b36ff6c45885">

https://fitznhmaoct2023-edge.test.specifysystems.org/specify/view/collectionobject/729344/

**System Information**
[Specify 7 System Information - 2024-04-01T15_47_19.140Z.txt](https://github.com/specify/specify7/files/14825754/Specify.7.System.Information.-.2024-04-01T15_47_19.140Z.txt)

- OS: macOS
- Browser: Arc
- Specify 7 Version: `edge` for 7.9.4 testing
- Database Name: `Fitz_NHMA_Oct_2023 `
- Collection name: NHMA Malacology
- User Name: `petrifiedroadkill`

**Comment by grantfitzsimmons** [comment]
<img width="889" alt="image" src="https://github.com/specify/specify7/assets/37256050/dcf44131-944c-4d24-8a38-d94450942d45">

It seems this is not restricted to grid view

https://fitznhmaoct2023-edge.test.specifysystems.org/specify/view/accession/4/

**Comment by emenslin** [comment]
Fixed
