### ISSUE TITLE
Initiate record attachment gallery on save 

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4708]
**Describe the bug**

The attachment gallery buttons for a record -- embedded in attachment subform and in record header -- should appear when attachments are added and saved to the form. 

This doesn't happen in `edge`. Neither icon appear when attachments are saved right now. 

**To Reproduce**

1. Go to new record
2. Add an attachment
3. Save
4. See no record gallery icons 

**Screenshots**

**`edge` on left, `v7.9` on right**
<img width="1854" alt="Screenshot 2024-04-01 at 11 02 11 AM" src="https://github.com/specify/specify7/assets/135047322/1c455b55-c992-4473-a7f9-fedd01c8c011">

- OS: macOS
- Browser: Chrome
- Specify 7 Version: `edge`
- Database Name: `herb_rbge_2_5_2024`
- Collection name: Herbarium
- User Name: spadmin

**Comment by CarolineDenis** [comment]
NOTES: 
The Attachments Icon on the top right should not be present so that's not an issue. But the gallery icon in the attachment header should be present, that's an issue
