### ISSUE TITLE
Fictitious record sets can have records from multiple tables

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4709]
**Describe the bug**
A fictitious record set can have records from a number of tables (collection object, loan, etc.).

This is a problem in both `edge` and `v7.9.3.1`

**To Reproduce**

1. Create a new Collection Object record
2. Create a new Loan from the navigation menu
3. See that the current fictitious record set has both the Collection Object and the Loan in the same series
4. Make a record set from the current fictitious record set
5. Open new record set
6. Navigate to an item in the set that is from another table besides Collection Objet (in this case, Loan)
7. See 404 message

**Expected behavior**
This is problematic in and of itself, as new records in other tables should be created in a new tab rather than being in a temporary set of working records.

There are a couple of solutions to this issue:
1. Don't allow multiple records from different tables to exist in the same fictitious record set
    (Preferred) I believe a new tab should open when creating a record from a new table to prevent confusion, but I see how this may enable some workflow I cannot anticipate.
3. Don't allow the user to create a new record set from a fictitious record set containing records from multiple tables

**Screenshots**
`v7.9.3.1` on left, `edge` on right

https://fitznhmaoct2023-v7.test.specifysystems.org/specify/view/collectionobject/3/?recordsetid=767
https://fitznhmaoct2023-edge.test.specifysystems.org/specify/view/collectionobject/4/?recordsetid=768

https://github.com/specify/specify7/assets/37256050/10ec91fe-a28c-4b3f-99cf-56bd00c8afc9

**Crash Report**
[Specify 7 System Information - 2024-04-01T15_47_19.140Z.txt](https://github.com/specify/specify7/files/14825754/Specify.7.System.Information.-.2024-04-01T15_47_19.140Z.txt)

- OS: macOS
- Browser: Arc
- Specify 7 Version: `edge` and `v7.9.3.1`
- Database Name: `Fitz_NHMA_Oct_2023 `
- Collection name: NHMA Malacology
- User Name: `petrifiedroadkill`

**Comment by emenslin** [comment]
Fixed
