### ISSUE TITLE
Loan Prep Return: Deselect All button causes enlarged dialog

### ISSUE THREAD

**Issue by pashiav** [specify/specify7#4711]
**Describe the bug**
When Returning a Loan with preparations: clicking the **Select All** then **Deselect All** button causes the dialog to enlarge.

**To Reproduce**
1. Go to any Loan with preparations (https://umherb11024-edge.test.specifysystems.org/specify/view/loan/2414/)
2. Click on **Return Loan** at the bottom of the form
3. Click **Select All**
4. Click **Deselect All**
5. See that dialog enlarges

**Expected behavior**
Dialog should remain the same size.
Expected behavior in `v7.9.3.1`:

https://github.com/specify/specify7/assets/118556884/4be551f2-2179-41d9-ae63-ba799d9b7009

**Evidence**

https://github.com/specify/specify7/assets/118556884/604c01f8-fb8c-4a7b-ab65-f798b5249be5

OS: macOS Monterey (12.6.5)
Browser: Chrome
Specify 7 Version: `edge`
Database Name: `umherb_1_10_24`
[Specify 7 System Information - 2024-04-01T17_18_47.238Z.txt](https://github.com/specify/specify7/files/14826712/Specify.7.System.Information.-.2024-04-01T17_18_47.238Z.txt)

**Comment by CarolineDenis** [comment]
NOTES: 
- When putting break points on handleResized and initialSize, the dialog keeps the right height.
