### ISSUE TITLE
Fix memory issue on the KU Django server

### ISSUE THREAD

**Issue by acwhite211** [specify/specify7#4713]
After some investigation, it seems after adding new Specify instances to the KU server, it has become pretty tight on memory and storage. We'll need to increase the swap memory for now, but we should maybe look into adding more memory or storage to the server in the future.  Pruning the docker images reduced storage usage by 5GB, so that should give us enough room to add more swap memory.

```
                   total        used        free      
Mem:          5.5Gi       3.9Gi       118Mi       
Swap:         4.0Gi       3.9Gi        28Mi
```

**Comment by grantfitzsimmons** [comment]
Issues should only be created on this repository if they are related to Specify 7.

If we want to manage internal tasks, I think we should create a new private repository and either manage separate milestones or create a organization-wide project to track development progress.
