### ISSUE TITLE
Add tool tip for relative date query operators back in

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4715]
**Describe the bug**

We lost it! 

https://github.com/specify/specify7/assets/135047322/7400952e-8454-4ff6-b1be-fcd1dfc4224e

**To Reproduce**

1. Go to query builder
2. Map date field
3. Use operator 
4. Hover over the "Switch to relative" icon
5. See error

- OS: macOS
- Browser: Chrome
- Specify 7 Version: `edge`
- Database Name:  pripaleo_schemaupdated
- Collection name: Paleontological Research Institution 
- User Name: testuser

**Comment by CarolineDenis** [comment]
@bronwyncombs , I tried several times with several db and cannot reproduce.
