### ISSUE TITLE
'Bad Tree Structure' warning no longer prevents saving when it should

### ISSUE THREAD

**Issue by combs-a** [specify/specify7#4717]
**Describe the bug**
The 'bad tree structure' warning no longer appears when selecting an invalid parent (i.e. a parent that's the lowest rank in the taxon tree, such as subspecies), and allows for the user to save, leading to a crash.

**To Reproduce**
1. Go to Create Entry -> New Taxon.
2. Fill name, add a parent that _is not_ the lowest taxon rank to fill the taxonomic rank field (i.e. Animalia).
3. Change parent to lowest taxon rank (i.e. Darlingtonia haetiana haetiana).
4. The parent form will show as valid and you can save, leading to an error.

**Expected behavior**
A warning should flag the parent and prevent the user from saving.

**Screenshots**
First is the edge server, after error message is v7.

https://github.com/specify/specify7/assets/71564869/222610c5-3555-426c-a9e6-f4e39c04e928

**Crash Report**

[Specify 7 Crash Report - 2024-04-01T20 40 51.788Z.txt](https://github.com/specify/specify7/files/14828365/Specify.7.Crash.Report.-.2024-04-01T20.40.51.788Z.txt)

- OS: Windows 10
- Browser: Firefox & Chrome
- Specify 7 Version: edge
- Database Name: KU_Herps_8_17_23
- Collection name: Herpetology
- User Name: spherpsadmin

**Additional context**
May be related to issues #4455 and PR #4462. Crash is likely from issue #2637, but could also be something with adding a child to the smallest rank.

**Comment by pashiav** [comment]
From the PR https://github.com/specify/specify7/pull/4726#issue-2220738960:

> - [ ] Clear the Parent QueryComboBox (the tree rank should clear as well) 


Erasing the Parent taxon input causes the dialog to enlarge and the Rank field to be filled with an API URL.


`edge`

https://github.com/specify/specify7/assets/118556884/a51d878f-f196-4786-a2f9-ab27c59dfd3d


Expected Behavior `v7.9.3.1`: 

https://github.com/specify/specify7/assets/118556884/002401df-31df-4f07-94bc-7dd93dbe550d

**Comment by combs-a** [comment]
Wasn't able to recreate this issue I think? Dialog is definitely no longer resizing, though there's a brief flash when it's edited.

@CarolineDenis is autofilling to the taxonomic root expected behavior? This makes sense to me, since the only rank w/o a parent is the taxonomic root, and when you fill in a new parent, it autofills the rank normally as far as I can tell.

https://github.com/specify/specify7/assets/71564869/f63a7ebb-7e15-4579-8b20-0a42da814534

https://github.com/specify/specify7/assets/71564869/0a48e849-1494-4171-b59b-4f981a76d21d

**Comment by CarolineDenis** [comment]
@combs-a, yes correct
For the flashing there is an open issue already on GitHub
