### ISSUE TITLE
'Parent' field on lithostratigraphy forms are no longer query combo boxes.

### ISSUE THREAD

**Issue by lexiclevenger** [specify/specify7#4719]
**Describe the bug**
Parent fields that have a query combo box in v7 do not have a query combo box in edge on the same database.

This could be recreated in all of the paleontology databases I checked; I tried fitz_nhmd_oct2023, pripaleoschemaupdatedcm202304211540, and KUPaleobotany. In all databases, the Parent field is a query combo box in v7 and is not in edge.

**To Reproduce**

1. Go to Data Entry.
2. Click on Lithostratigraphy
3. See error on Parent field.

**Expected behavior**
Parent field should be a query combo box

**Screenshots**
<img width="1920" alt="Screenshot 2024-04-01 at 4 46 12 PM" src="https://github.com/specify/specify7/assets/164079735/180e3b57-9c42-416a-b1d4-e553f8107a0f">

https://fitznhmdoct2023-edge.test.specifysystems.org/specify/view/lithostrat/new/

[Specify 7 System Information - 2024-04-01T22_09_41.728Z.txt](https://github.com/specify/specify7/files/14829029/Specify.7.System.Information.-.2024-04-01T22_09_41.728Z.txt)

Please, also fill out the following information manually:

- OS: Mac
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: fitz_nhmd_oct2023
- Collection name: Vertebrate Paleontology
- User Name: petrifiedroadkill

**Comment by CarolineDenis** [comment]
@lexiclevenger, 
In 9.4 we have now the possibility to specify in the app resource if we want or not to display the edit and the add icon in the initialize attributes of the field. In the db you used for this issue, in your LithoStrat app resource definition, you had editBtn=false and addBtn=false, hence the fact that you couldn't see them. If you remove those attributes or set them to true they are present again. 

See bellow 
![Screenshot 2024-04-02 at 8 35 53 AM](https://github.com/specify/specify7/assets/108160931/c08dc625-b3bb-4b3f-b726-09eff7df6f2b)
![Screenshot 2024-04-02 at 8 35 35 AM](https://github.com/specify/specify7/assets/108160931/97a538ca-2421-456d-9fb9-5b0c5c6b20bd)
