### ISSUE TITLE
w-full class applied to dialog fields causing max expansion unnecessarily

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4722]
**Describe the bug**

Fields in dialogs such as add preparations to new loans and Return Loan are expanded fully across the width of the dialog because of a class being applied here inappropriately. 

**To Reproduce**

1. Go to new loan
2. Enter cat numbers or choose record set with preparations
3. See width of bulk select in choose preps dialog
4. Save new loan and click `Return Loan` button
5. See width of Returned Date and Received By fields 

**Screenshots**

See selecting and un-selecting the `w-full` class for the Bulk Select field: 

https://github.com/specify/specify7/assets/135047322/257b9cd4-b92e-4b26-b1d8-8501e9c9edf0

- OS: macOS
- Browser: Chrome
- Specify 7 Version: `edge`
- Database Name: pripaleo
- Collection name: Paleontological
- User Name: testuser

**Comment by CarolineDenis** [comment]
Fixed bulk select taking full width in PR. 
But the returned date and received by in return dialog prep is the same as in 9.3 
![Screenshot 2024-04-02 at 8 14 04 AM](https://github.com/specify/specify7/assets/108160931/19fe0523-48d9-4843-bbf1-6eb1ee330bc1)
