### ISSUE TITLE
Clicking attachment in attachment gallery causes Specify tab to freeze

### ISSUE THREAD

**Issue by combs-a** [specify/specify7#4732]
**Describe the bug**
When clicking on an attachment in attachment gallery, the tab freezes, which forces you to either close and reopen it or wait for the browser to give you an option to stop the page so you can reload.

**To Reproduce**

1. Go to a collection object with attachments.
2. Click on attachment gallery.
3. Click on an attachment.
4. Tab freezes and doesn't allow you to close the gallery, click on the other attachments, etc. You can use other tabs while it's frozen, and it doesn't seem to cause a full browser crash.

**Expected behavior**
Attachment opens with no freezing.

**Screenshots**

Issue on `edge`:

https://github.com/specify/specify7/assets/71564869/f77fd255-3df7-4601-8b8c-6c5e7805a43b

Expected behavior (`7.9.3`):

https://github.com/specify/specify7/assets/71564869/bb514506-82c1-462d-a86f-36a687acd8ff

**Crash Report**

N/A

- OS: Windows 10
- Browser: Firefox & Chrome
- Specify 7 Version: `edge`
- Database Name: `sdnhm_herps_2_8_24`
- Collection name: `Herp-PC`
- User Name: `testuser`

**Additional context**
In the browser's Development Tools' Network tab, there were no network requests made when reproducing the issue.

**Comment by CarolineDenis** [comment]
NOTES: 
`  const resource = React.useMemo(
    () => deserializeResource(attachment),
    [attachment]
  );`
  in Attachments/Dialog.tsx line 42
  is being called in a infinite loop when called from AttachmentsCollection
