### ISSUE TITLE
Unable to Use New View Definition as Form for Subview with `﻿defaulttype="table"` Attribute

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4737]
**Describe the bug:**
After creating a new view definition, I cannot successfully use it as the form for a subview when that subview includes `defaulttype="table"` in the XML as the original view definition is being used instead. See below for additional details!

---

In the CollectionObject view definition (https://herb32124-edge.test.specifysystems.org/specify/resources/view-set/1/CollectionObject/CollectionObject), I have the following row defined:

```xml
<row>
	<cell type="subview" viewname="Preparation" id="8" name="preparations" defaulttype="table" colspan="13"/>
</row>
```

Because of this, I would expect it to use the `Preparation` view definition as the definition for the Preparation form. 

Since I have the XML attribute `defaulttype="table"`, it is automatically shown in a table view on the form. I suspect this may be a big part of this confusion or issue.

See below that this is not using the `Preparation` view definition when collapsed, but rather using the `Preparation Abridged` definition, which is not referenced in the `CollectionObject` view definition:

<img width="1114" alt="image" src="https://github.com/specify/specify7/assets/37256050/3d25ff84-1d0b-4c4a-9c18-04b4305908e3">

For reference, here is the `Preparation` view definition that is being referenced from the `CollectionObject` view definition:

```xml
<viewdef type="form" name="Preparation" class="edu.ku.brc.specify.datamodel.Preparation" gettable="edu.ku.brc.af.ui.forms.DataGetterForObj" settable="edu.ku.brc.af.ui.forms.DataSetterForObj" useresourcelabels="true">
	<desc>Preparation for Collection Object form.</desc>
	<enableRules/>
	<columnDef>100px,2px,178px,5px,100px,2px,163px,5px,100px,2px,163px,2px,10px,p:g</columnDef>
	<columnDef os="lnx">115px,2px,190px,5px,115px,2px,180px,5px,115px,2px,180px,2px,4px,p:g</columnDef>
	<columnDef os="mac">110px,2px,230px,5px,110px,2px,220px,5px,110px,2px,220px,2px,14px,p:g</columnDef>
	<columnDef os="exp">p,2px,p:g(2),5px:g,p,2px,p:g,5px:g,p,2px,p:g,10px,p:g</columnDef>
	<rowDef auto="true" cell="p" sep="2dlu"/>
	<rows>
		<row>
			<cell type="label" labelfor="prepType"/>
			<cell type="field" id="prepType" name="prepType" uitype="combobox" picklist="PrepType" default="Herbarium specimen/sheet"/>
			<cell type="label" labelfor="barcode"/>
			<cell type="field" id="barcode" name="barCode" uitype="text"/>
			<cell type="field" id="WebLink" name="this" uitype="plugin" initialize="name=WebLinkButton;weblink=RBGECat"/>
			<cell type="field" id="isOnLoan" name="isOnLoan" uitype="checkbox" label="IS_ON_LOAN" readonly="true"/>
			<cell type="command" id="ShowLoansBtn" name="ShowLoansBtn" label="Show Interactions" ignore="true"/>
		</row>
		<row>
			<cell type="label" labelfor="labelStatus"/>
			<cell type="field" id="labelStatus" name="text10" uitype="combobox"/>
			<cell type="label" labelfor="sheetNum"/>
			<cell type="field" id="sheetNum" name="integer1" uitype="text"/>
			<cell type="label" labelfor="numInSet"/>
			<cell type="field" id="numInSet" name="integer2" uitype="text"/>
		</row>
		<row>
			<cell type="separator" label="" colspan="14"/>
		</row>
		<row>
			<cell type="label" labelfor="storage"/>
			<cell type="field" id="storage" name="storage" uitype="querycbx" initialize="name=Storage" colspan="5" default="Main Herbarium"/>
		</row>
		<row>
			<cell type="separator" label="" colspan="14"/>
		</row>
		<row>
			<cell type="label" labelfor="donor"/>
			<cell type="field" id="donor" name="text5" uitype="text"/>
			<cell type="label" labelfor="herbColl"/>
			<cell type="field" id="herbColl" name="text3" uitype="text"/>
			<cell type="label" labelfor="collSeries"/>
			<cell type="field" id="collSeries" name="text4" uitype="text"/>
		</row>
		<row>
			<cell type="label" labelfor="project"/>
			<cell type="field" id="project" name="text6" uitype="text" colspan="5"/>
		</row>
		<row>
			<cell type="label" labelfor="labelHeader"/>
			<cell type="field" id="labelHeader" name="text1" uitype="text" colspan="11"/>
		</row>
		<row>
			<cell type="label" labelfor="labelFooter"/>
			<cell type="field" id="labelFooter" name="text2" uitype="text" colspan="11"/>
		</row>
		<row>
			<cell type="label" labelfor="remarks"/>
			<cell type="field" id="remarks" name="remarks" uitype="textareabrief" rows="2" colspan="11"/>
		</row>
		<row>
			<cell type="label" labelfor="intMisc"/>
			<cell type="field" id="intMisc" name="text12" uitype="textareabrief" rows="2" colspan="11"/>
		</row>
		<row>
			<cell type="subview" id="PreparationAttributes" viewname="PreparationAttributes" name="preparationAttribute" colspan="13"/>
		</row>
		<row>
			<cell type="separator" label="Destructive Sampling" colspan="14"/>
		</row>
		<row>
			<cell type="label" labelfor="materialtype"/>
			<cell type="field" id="materialtype" name="description" uitype="combobox"/>
			<cell type="label" labelfor="derivedFrom"/>
			<cell type="field" id="derivedFrom" name="text9" uitype="text"/>
		</row>
		<row>
			<cell type="label" labelfor="deniedRequests"/>
			<cell type="field" id="deniedRequests" name="text13" uitype="text" colspan="14"/>
		</row>
		<row>
			<cell type="label" labelfor="preparedDate"/>
			<cell type="field" id="preparedDate" uitype="plugin" name="this" initialize="name=PartialDateUI;df=preparedDate;tp=preparedDatePrecision" uifieldformatter="Date" colspan="3"/>
		</row>
		<row>
			<cell type="separator" colspan="14"/>
		</row>
		<row>
			<cell type="label" labelfor="BGBASENum"/>
			<cell type="field" id="BGBASENum" name="number2" uitype="label" readonly="true"/>
		</row>
		<row>
			<cell type="subview" id="attachments" viewname="ObjectAttachment" name="preparationAttachments" initialize="align=right;btn=true;icon=PreparationAttachment"/>
		</row>
		<row>
			<cell type="field" id="countAmt" name="countAmt" uitype="text" initialize="visible=false" default="1"/>
		</row>
	</rows>
</viewdef>
```

In the **Preparation** view definition list, there is only one definition:
<img width="317" alt="image" src="https://github.com/specify/specify7/assets/37256050/f2f58ab5-9b9d-45c1-b21f-12131067fb4f">

In the `<views>` section, there are the following Preparation view defs:
```xml
<view name="Preparation" class="edu.ku.brc.specify.datamodel.Preparation" busrules="edu.ku.brc.specify.datamodel.busrules.PreparationBusRules" resourcelabels="false">
	<desc>Subform within the Preparation form.</desc>
	<altviews>
		<altview name="Preparation Table View" viewdef="Preparation Abridged Table" mode="view"/>
		<altview name="Preparation Table Edit" viewdef="Preparation Abridged Table" mode="edit"/>
		<altview name="Preparation View" viewdef="Preparation" mode="view"/>
		<altview name="Preparation Edit" viewdef="Preparation" mode="edit" default="true"/>
	</altviews>
</view>
```

Here's the "Preparation Abridged" view definition that defines how the columns are appearing when collapsed:

```xml
<viewdef type="form" name="Preparation Abridged" class="edu.ku.brc.specify.datamodel.Preparation" gettable="edu.ku.brc.af.ui.forms.DataGetterForObj" settable="edu.ku.brc.af.ui.forms.DataSetterForObj" useresourcelabels="true">
	<desc>Preparation for Collection Object form.</desc>
	<enableRules/>
	<columnDef>100px,2px,133px,5px,91px,2px,210px,5px,87px,2px,123px,2px,70px,p:g</columnDef>
	<columnDef os="lnx">115px,2px,150px,5px,110px,2px,223px,5px,100px,2px,126px,2px,75px,p:g</columnDef>
	<columnDef os="mac">130px,2px,165px,5px,110px,2px,260px,5px,105px,2px,174px,2px,70px,p:g</columnDef>
	<columnDef os="exp">p,2px,p:g(2),5px:g,p,2px,p:g,5px:g,p,2px,p:g,10px,p:g</columnDef>
	<rowDef auto="true" cell="p" sep="2dlu"/>
	<rows>
		<row>
			<cell type="label" labelfor="barcode"/>
			<cell type="field" id="barcode" name="barCode" uitype="dsptextfield" align="left"/>
			<cell type="label" labelfor="prepType"/>
			<cell type="field" id="prepType" name="prepType" uitype="combobox" picklist="PrepType"/>
			<cell type="label" labelfor="storage"/>
			<cell type="field" id="storage" name="storage" uitype="querycbx" initialize="name=Storage" colspan="3"/>
			<cell type="field" id="isOnLoan" name="isOnLoan" uitype="checkbox" label="IS_ON_LOAN" readonly="true"/>
		</row>
	</rows>
</viewdef>
```

You can see that this view def is used when the Preparations subview is collapsed in "table" or "grid" view since the "Preparation Abridged" definition is used when the type is "table".

<img width="867" alt="image" src="https://github.com/specify/specify7/assets/37256050/70ac8956-913f-4df5-a1b8-5194eaf51dd6">

The issue arrises when I create a new `Preparation` view definition:

**Steps to recreate:**
1. Create a new view definition under the `Preparation` table
2. Copy the current custom view definition and name it `Preparation_New`
3. Remove all fields aside from `prepType`, the web link `RBGECat`,`isOnLoan`, and the `ShowLoansBtn` plugin
4. Edit the `CollectionObject` view definition to use the `viewname` `Preparation_New` instead of `Preparation`
   ```xml
		<row>
			<cell type="subview" viewname="Preparation_New" id="8" name="preparations" defaulttype="table" colspan="13"/>
		</row>
   ```
5. Add a Preparation record to the Collection Object form preview and see that it uses the `Preparation` view definition (along with the `Preparation Abridged` definition to define the columns):

   https://github.com/specify/specify7/assets/37256050/d2524056-cb86-482f-aa2d-6743c384ccef

   <img width="857" alt="image" src="https://github.com/specify/specify7/assets/37256050/cf6eab30-60d5-41f7-9057-1404934f986c">
   <img width="1110" alt="image" src="https://github.com/specify/specify7/assets/37256050/7e0b0223-d85a-4e98-95e8-f5371f99fbb4">

   It should be using the `Preparation_New` view definition instead.

Let's take a closer look at what Specify created in this instance.

It added the following `<view>` section upon the creation of `Preparation_New`:

```xml
		<view name="Preparation_New" class="edu.ku.brc.specify.datamodel.Preparation" busrules="edu.ku.brc.specify.datamodel.busrules.PreparationBusRules" resourcelabels="false">
			<desc>Subform within the Preparation form.</desc>
			<altviews>
				<altview name="Preparation Table View" viewdef="Preparation Abridged Table (2)" mode="view"/>
				<altview name="Preparation Table Edit" viewdef="Preparation Abridged Table (2)" mode="edit"/>
				<altview name="Preparation View" viewdef="Preparation (2)" mode="view"/>
				<altview name="Preparation Edit" viewdef="Preparation (2)" mode="edit" default="true"/>
			</altviews>
		</view>
```

The `Preparation (2)` view definition looks just as I'd expect it to, containing the edits I made above:
```xml
<viewdef name="Preparation (2)" class="edu.ku.brc.specify.datamodel.Preparation" type="form" gettable="edu.ku.brc.af.ui.forms.DataGetterForObj" settable="edu.ku.brc.af.ui.forms.DataSetterForObj" useresourcelabels="true">
	<desc>Preparation for Collection Object form.</desc>
	<enableRules/>
	<columnDef>100px,2px,178px,5px,100px,2px,163px,5px,100px,2px,163px,2px,10px,p:g</columnDef>
	<columnDef os="lnx">115px,2px,190px,5px,115px,2px,180px,5px,115px,2px,180px,2px,4px,p:g</columnDef>
	<columnDef os="mac">110px,2px,230px,5px,110px,2px,220px,5px,110px,2px,220px,2px,14px,p:g</columnDef>
	<columnDef os="exp">p,2px,p:g(2),5px:g,p,2px,p:g,5px:g,p,2px,p:g,10px,p:g</columnDef>
	<rowDef auto="true" cell="p" sep="2dlu"/>
	<rows>
		<row>
			<cell type="label" labelfor="prepType"/>
			<cell type="field" id="prepType" name="prepType" uitype="combobox" picklist="PrepType" default="Herbarium specimen/sheet"/>
			<cell type="field" id="WebLink" name="this" uitype="plugin" initialize="name=WebLinkButton;weblink=RBGECat"/>
			<cell type="field" id="isOnLoan" name="isOnLoan" uitype="checkbox" label="IS_ON_LOAN" readonly="true"/>
			<!--<cell type="subview" id="giftPreparations" name="giftPreparations" viewname="giftPeps" initialize="btn=true;align=left"/>-->
			<cell type="command" id="ShowLoansBtn" name="ShowLoansBtn" label="Show Interactions" ignore="true"/>
		</row>
	</rows>
</viewdef>
```

The `Preparation Abridged Table (2)` view definition seems innocent enough, until we take a closer look:
```xml
<viewdef name="Preparation Abridged Table (2)" class="edu.ku.brc.specify.datamodel.Preparation" type="formtable" gettable="edu.ku.brc.af.ui.forms.DataGetterForObj" settable="edu.ku.brc.af.ui.forms.DataSetterForObj">
	<desc>Preparation subform table for Collection Object form.</desc>
	<definition>Preparation Abridged</definition>
</viewdef>
```

It explicitly tells Specify to use the `Preparation Abridged` view definition on this line:
```xml
<definition>Preparation Abridged</definition>
```

This, unfortunately, leads us back to the grid view used for the original `Preparation` form definition. 

If I remove the `defaulttype="table"`, it will properly use the view definition `Preparation_New` since it presumably knows to only use the viewdef named `Preparation (2)` linked by the `Preparation_New` view.

<img width="609" alt="image" src="https://github.com/specify/specify7/assets/37256050/88853e76-6b9f-464d-b398-f248de339e6b">

https://github.com/specify/specify7/assets/37256050/a47110f9-8c60-4780-8041-c8a40fdd5fe4

---

**Expected behavior:** If the user creates a new view definition under a table and explicitly references it in the `viewname=""` attribute for a subview, it should be properly interpreted when it is either using `defaulttype="table"` or `defaulttype="form"`.

[botany.views.xml.zip](https://github.com/specify/specify7/files/14872211/botany.views.xml.zip)

**Crash Report**
[Specify 7 System Information - 2024-04-04T13_55_50.012Z.txt](https://github.com/specify/specify7/files/14872268/Specify.7.System.Information.-.2024-04-04T13_55_50.012Z.txt)

- OS: macOS
- Browser: Arc
- Specify 7 Version: `edge` for 7.9.4 testing
- Database Name: `herb_3_21_24 `
- Collection name: Herbarium
- User Name: `spadmin`

**Comment by grantfitzsimmons** [comment]
Creating an entirely new view definition based on the default for Botany (in this instance, named `NewPreps2`) and assigning it also does not allow the user to show it in "table" view:

<img width="1117" alt="image" src="https://github.com/specify/specify7/assets/37256050/3c0013bf-2491-4aaa-b361-ac96b4794a87">

https://herb32124-edge.test.specifysystems.org/specify/resources/view-set/5/CollectionObject/CollectionObject

**Comment by CarolineDenis** [comment]
NOTES: 
- the view def are created and constructed properly 
- the issue is that when you put defaulttype="table" for a subview it looks at the default form and not the one you specified in the viewName. 
- to test this theory you can see that the form table displayed is the same whether you put a view name or not in the attribute of the cell

**Comment by CarolineDenis** [comment]
@maxpatiiuk , 

Why do we pass fullViewDefinition and not viewDefinition? 
https://github.com/specify/specify7/blob/e3baa7b6b157588b4d5daac59a479fff006866f6/specifyweb/frontend/js_src/lib/components/FormCells/FormTable.tsx#L313

**Comment by melton-jason** [comment]
I think the issue is that we are fetching the wrong view for `fullViewDefinition`. 

https://github.com/specify/specify7/blob/e3baa7b6b157588b4d5daac59a479fff006866f6/specifyweb/frontend/js_src/lib/components/FormCells/FormTable.tsx#L164-L170

Specifically, the value of `relationship.relatedTable.view` does match the correct view name. 

Take a look at the Preparation views Specify fetches when loading a CollectionObject form: 

<img width="879" alt="Screenshot 2024-04-04 at 8 56 44 PM" src="https://github.com/specify/specify7/assets/64045831/3cabdb59-cac5-4024-86a8-9d61d6bc426d">

https://herb32124-edge.test.specifysystems.org/context/view.json?name=Preparation_New
https://herb32124-edge.test.specifysystems.org/context/view.json?name=Preparation

For `fullViewDefinition`, Specify is fetching the view with name `Preparation` because the value of `relationship.relatedTable.view` is Preparation. 

The table.view comes from the backend datamodel endpoint `/context/datamodel.json`. 
Specifically, 

Frontend:
https://github.com/specify/specify7/blob/e3baa7b6b157588b4d5daac59a479fff006866f6/specifyweb/frontend/js_src/lib/components/DataModel/specifyTable.ts#L205-L209

Backend: 
https://github.com/specify/specify7/blob/e3baa7b6b157588b4d5daac59a479fff006866f6/specifyweb/specify/load_datamodel.py#L177-L180

Thus `table.view` for Preparation will _always_ be `Preparation`

<img width="449" alt="Screenshot 2024-04-04 at 9 10 32 PM" src="https://github.com/specify/specify7/assets/64045831/afb421c0-bb74-497f-acda-4c13f31a77ec">

---

To resolve this, I think the `viewName` and `fallbackViewName` arguments being passed to `useViewDefinition` for `fullViewDefinition` need to match that of `viewDefinition`. 

Instead of _always_ fetching the view defined on the table in the datamodel, we need to fetch the view provided as an argument to the `FormTable` function. 
The fallbackViewName can then be the view defined on the table.

https://github.com/specify/specify7/blob/e3baa7b6b157588b4d5daac59a479fff006866f6/specifyweb/frontend/js_src/lib/components/FormCells/FormTable.tsx#L164-L170

https://github.com/specify/specify7/blob/e3baa7b6b157588b4d5daac59a479fff006866f6/specifyweb/frontend/js_src/lib/components/FormCells/FormTable.tsx#L157-L163

**Comment by maxpatiiuk** [comment]
> Why do we pass fullViewDefinition and not viewDefinition?

fullViewDefinition is for expanded row
viewDefinition is for collapsed row

feel free to rename the variables to make them more clear (expandedViewDefinition/collapsedViewDefinition)

> Instead of always fetching the view defined on the table in the datamodel, we need to fetch the view provided as an argument to the FormTable function.
The fallbackViewName can then be the view defined on the table.

Yes! you are correct
Sorry, not sure how I missed this part. Funny that's it's correct for `viewDefinition` but not for `fullViewDefinition`

**Comment by melton-jason** [comment]
> Fixed. I tested both issues and now they both have desired behavior.
> 
> ### Algorithm
> #### When collapsed
> Use provided view name if provided and found a view by that name. Otherwise, use default view name. If no default view, use auto generated view.
> 
> #### When expanded
> Use default view name (just the table name). If there is no view for the default name, use the custom view name if provided and there is view by that name. Else, use auto generated view.
> 
> As part of testing this, please test #2366 again

From https://github.com/specify/specify7/issues/2412#issuecomment-1327967090

This behavior was intentional. In some cases (see list of views in https://github.com/specify/specify7/pull/4760/commits/5c91a89e633130899af46b3446aaa282ef41920d) the FormTables were defined such that Specify should default to using the default table view (which is in an entirely separate view from the one which defines the collapsed layout).  

For a further breakdown, see https://github.com/specify/specify7/pull/4760#issuecomment-2046022176. 

Although as observed in this Issue with Preparation, there are additional ways in which the default forms define FormTables. 
Furthermore, before #4740, that way of defining FormTable views means they would not be customizable by the user. 

Potential solution proposed in https://github.com/specify/specify7/pull/4760#issuecomment-2046022176:

> Thankfully there is some consistency amongst the table-only views.
> Notably, every altview in the altviews of the view points to a view definition which is of type formtable.
> When reading a form definition for a subview on the frontend, if every altview points to a formtable viewdef in a view, we can likely fallback to using the table.view view for rendering the expanded definition of the subview (the collapsed view can still remain the original view).

**Comment by melton-jason** [comment]
The issue mentioned in https://github.com/specify/specify7/issues/4737#issuecomment-2048322097 was fixed in https://github.com/specify/specify7/pull/4776
