### ISSUE TITLE
`sortField` attribute incorrectly flagged as an error when related table field is referenced

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4741]
**Describe the bug**

**To Reproduce**

1. Go to the `CollectionObject` view definition (https://herbrbge252024-issue-4737.test.specifysystems.org/specify/resources/view-set/1/CollectionObject/CollectionObject or [botany.views.sortField.xml.zip](https://github.com/specify/specify7/files/14885554/botany.views.sortField.xml.zip))
2. Add or see the `determinations` subview below:
   ```xml
   <row>
      <cell type="subview" viewname="Determination" id="6" name="determinations" defaulttype="table" colspan="13" rows="5" initialize="sortField=-isCurrent"/>
   </row>
   ```
3. See error prevents saving

**Expected behavior**
When a field is referenced in an `initialize="sortField={fieldName}"`, it should not be seen as an error as long as the field exists in the related table.

See the form system documentation here: https://discourse.specifysoftware.org/t/editing-forms-in-specify-7/1557#subview-20

**Screenshots**

<img width="1720" alt="image" src="https://github.com/specify/specify7/assets/37256050/30bd61d9-4ca4-4f31-ad2b-15f6dfc75fe0">

<img width="993" alt="image" src="https://github.com/specify/specify7/assets/37256050/8075d2ef-bdc9-4861-bb9a-cfafc17cff3e">

**Crash Report**

[Specify 7 System Information - 2024-04-04T13_55_50.012Z.txt](https://github.com/specify/specify7/files/14885566/Specify.7.System.Information.-.2024-04-04T13_55_50.012Z.txt)

Please, also fill out the following information manually:

- OS: macOS
- Browser: Arc
- Specify 7 Version: `issue-4737` (same on `edge`)
- Database Name: herb_3_21_24
- Collection name: Herbarium
- User Name: spadmin

**Comment by CarolineDenis** [comment]
There is even a test for that... weird 
(cells.test.ts line 346)

**Comment by CarolineDenis** [comment]
NOTES: 
In the code: 
```ts
  field: (
    tableName: keyof Tables | undefined,
    mode: 'silent' | 'strict' | 'warn' = 'strict'
  ) =>
    syncer<string | undefined, RA<LiteralField | Relationship> | undefined>(
      (fieldName) => {
        if (fieldName === undefined || tableName === undefined)
          return undefined;
        const field = genericTables[tableName].getFields(fieldName);
        if (field === undefined && mode !== 'silent')
          console[mode === 'strict' ? 'error' : 'warn'](
            `Unknown field: ${fieldName}`
          );
        return field;
      },
      (fieldName) => fieldName?.map(({ name }) => name).join('.')
    ),
```

for the example: 
```ts
<row>
   <cell type="subview" viewname="Determination" id="6" name="determinations" defaulttype="table" colspan="13" rows="5" initialize="sortField=-isCurrent"/>
</row>
```

`const field = genericTables[tableName].getFields(fieldName);`
is: 
`const field = genericTables[collectionObject].getFields(isCurrent);`
should be: 
`const field = genericTables[determination].getFields(isCurrent);`
