### ISSUE TITLE
Unsaved changes are retained in qcbx edit dialogs

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4746]
**Describe the bug**

On a form, qcbx edit dialogs (pencil icon) retain changes that aren't saved. In some cases, Saving is then blocked upon attempting to revert to the original data 

> ^^ This exists in production

 

For Taxon specifically, I noticed that simply pasting the original text back in the field still results in a save block.

> ^^ This does not!! For `7.9.4`, we just need to address the save block upon trying to revert the data.

**To Reproduce**

1. Go to existing Collection Object
2. Click on pencil icon by taxon qcbx with data already entered
3. Remove text from required field in this dialog
4. Click cancel
5. Click pencil again
6. See invalid form, paste original name
7. See error with save block and message 

**Expected behavior**

Unsaved changes to a field should not be maintained i.e. if a field is emptied but not saved, the next time you open that record it should have the original data preserved

For `7.9.4`, restoring original data should validate the form again

**Screenshots**

**Example with Agent:**

https://github.com/specify/specify7/assets/135047322/d72eeae6-9b78-48fa-b7bd-8732d28c2b9e

**Example with Taxon:**

https://github.com/specify/specify7/assets/135047322/e79087b9-54f6-4426-ae44-630d154b84cd

VS Production: 

https://github.com/specify/specify7/assets/135047322/15c46327-6f87-415d-b6df-940b01d56c9e

**Crash Report**

[Specify 7 Crash Report - 2024-04-05T16_40_36.695Z.txt](https://github.com/specify/specify7/files/14887970/Specify.7.Crash.Report.-.2024-04-05T16_40_36.695Z.txt)

- `pripaleo` w/ testuser on Chrome
- `edge`

**Comment by CarolineDenis** [comment]
@maxpatiiuk any thoughts on this?

**Comment by maxpatiiuk** [comment]
> In some cases, Saving is then blocked upon attempting to revert to the original data

This is a bug and should be fixed

> On a form, qcbx edit dialogs (pencil icon) retain changes that aren't saved

I don't have a problem with this behavior. It might even be useful in some cases (you want to temporary close the dialog to see some content behind, and then open it back to finish editing).

But I would delegate this decision to @grantfitzsimmons 

If we do decide to revert unsaved changes upon dialog close, then we should probably also show a dialog saying "your have unsaved changes on this resource, are you sure you want to close it?" (and we could change the `close` button to `cancel`?)

**Comment by grantfitzsimmons** [comment]
In my opinion, closing a dialog with unsaved changes is not intuitive. It is unclear that changes have not been saved once you return to the form. Instead of asking if users want to close, we should require them to save changes before closing the dialog.
