### ISSUE TITLE
Can bypass saveblocker in form definition 

### ISSUE THREAD

**Issue by emenslin** [specify/specify7#4751]
**Describe the bug**
In the form definition even if there is a saveblocker from an error you can navigate back and save it. 

**To Reproduce**

1. Go to app resources and select a form definition 
2. Select any form 
3. Change something so the form is invalid and you get an error 
4. Click the back arrow 
5. See save button is orange and click it 
6. Navigate back to the form and see error 

**Expected behavior**
If there is an error you should not be able to bypass the saveblocker and navigate away 

**Screenshots**

https://github.com/specify/specify7/assets/150940840/5017363d-8815-47d2-93f3-28f0df1b79e4

Please, also fill out the following information manually:

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: lsumzmammals9823
- Collection name: mammals
- User Name: SpAdmin
[Specify 7 System Information - 2024-04-05T20_38_54.328Z.txt](https://github.com/specify/specify7/files/14890558/Specify.7.System.Information.-.2024-04-05T20_38_54.328Z.txt)

**Comment by CarolineDenis** [comment]
@maxpatiiuk , thoughts?

**Comment by maxpatiiuk** [comment]
option 1: turn the back link into a disabled button when any validation errors are present
option 2: allow users to do this, just in case the form validation logic is not completely correct or if we need an invalid form definition for testing purposes
