### ISSUE TITLE
verticalAlign=center not showing in Visual Editor preview

### ISSUE THREAD

**Issue by combs-a** [specify/specify7#4752]
**Describe the bug**
verticalAlign=center doesn't show in the Visual Editor preview until you reload the page.

**To Reproduce**

1. Go to App Resources -> form definition that has a subview next to another panel (horizontal) -> Edit.
 (i.e. https://sdnhmherps2824-edge.test.specifysystems.org/specify/resources/view-set/5/CollectionObject/CollectionObject)
3. In the editor, go to the subview. (in link above, collectionObjectAttachments)
4. Give verticalAlign the center property.
5. See that preview doesn't update.

**Expected behavior**
For it to be vertically centered in the preview without needing to reload.

**Screenshots**

https://github.com/specify/specify7/assets/71564869/05ba062b-f692-4de2-abab-ba957542761b

- OS: Windows 10
- Browser: Firefox
- Specify 7 Version: `edge`
- Database Name: `sdnhm_herps_2_8_24`
- Collection name: `Herp-PC`
- User Name: `testuser`

**Additional context**
When inspecting with developer tools, it does have the center property, and it does also get applied to forms, though seeing it on forms may require clearing the cache.

**Comment by maxpatiiuk** [comment]
> need to save to see the changes. but works

that's a bug then. Form Editor is supposed to provide "live preview"

**Comment by emenslin** [comment]
Can recreate in edge (7.9.6)

**Comment by pashiav** [comment]
Reproduced on `v7.11`.
