### ISSUE TITLE
Decimal fields prevent saving and display a misleading error until the fields are focused on

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4754]
**Describe the bug**
Save blockers are triggered because a decimal field is not a whole number until it is focused, then the record can be saved once focus is lost.

**To Reproduce**
1. Go to https://herb32124-v793.test.specifysystems.org/specify/view/collectionobject/1253799
2. See that you cannot save
3. Click "Save" and notice your focus is now on "Lat Seconds" warning that you need to enter a valid value
4. Click "Save" again and notice your focus is now on "Long Seconds" giving the same warning
5. Click "Save" again and see that you can save

**Expected behavior**

**Screenshots**

`edge` on left, `v7.9.3.1` on right

https://github.com/specify/specify7/assets/37256050/3cca6781-e566-40e6-aabb-886d2873082d

https://herb32124-v793.test.specifysystems.org/specify/view/collectionobject/1253799

**Crash Report**

[Specify 7 System Information - 2024-04-05T21_00_25.376Z.txt](https://github.com/specify/specify7/files/14890734/Specify.7.System.Information.-.2024-04-05T21_00_25.376Z.txt)

- OS: macOS
- Browser: Arc
- Specify 7 Version: `edge`
- Database Name: `herb_3_21_24`
- Collection name: Herbarium
- User Name: `spadmin`

**Comment by acwhite211** [comment]
On one of the times I clicked save, I got `number3: "35.4"` on the collection object PUT response, but other times it was correct `number3: 35.4`.  It should always be a number value, not a string.
 
Looking at the body of the collection object PUT request, there is `number3: "36.4"` and `number6: "54.2"`.  The front-end should be sending these as numbers and not as strings.  In the body of the PUT request `api/specify/collectionobject/1253799/`, the path is `collectingevent -> collectingeventattribute->number3`.

They seem correlated, so the back-end returns a string when the front-end sends a string.  I would think the back-end should just throw an error in the response.  I think having the front-end sending a number instead of a string might help.

**Comment by CarolineDenis** [comment]
NOTES: 
can confirm that pr #4016 is not responsible for this issue

**Comment by CarolineDenis** [comment]
https://codeburst.io/my-escape-from-input-validation-hell-82551765f422

**Comment by CarolineDenis** [comment]
NOTES: 
- the value of input field must always be a multiple of the value of step 
- if value is === to 9.3 but step is 0.5 it will throw an error 
- if value is === to 9.3 and step is 0.1 or 0.01 it will work as expected and increase value by 0.1 or 0.01 when using up/down arrows 
- Flow: 
   -  the user creates a record (value = 9.3) with an input field that has no initialize step as attribute than save => no error 
   - the user updates the form def and add the attribute initialize step === 0.5 to the input field and save
   - the user open his record with value = 9.3, an error is now being thrown
   - >>> need to update the value to a multiple of the step before adding the initialize attribute

**Comment by maxpatiiuk** [comment]
> NOTES:

so you mean the form was edited to tighten up the validation (the step value), but there is exciting data in the database that doesn't conform to the new validation constraints? If that's the case, then that's expected and we don't handle such case very well yet

but, if this is a float field, and user did not set the step attribute, and yet it is enforcing a step of 1, then this is a bug as the step should not be present for float fields (unless it was set explicitly in the form definition) - implicit step of 1 should be present for integer fields only

**Comment by CarolineDenis** [comment]
> so you mean the form was edited to tighten up the validation (the step value), but there is exciting data in the database that doesn't conform to the new validation constraints? If that's the case, then that's expected and we don't handle such case very well yet


yes this, after my change in the PR everything seem to work fine
