### ISSUE TITLE
WB not allowing deleting last row

### ISSUE THREAD

**Issue by realVinayak** [specify/specify7#4768]
![image](https://github.com/specify/specify7/assets/61122018/4d87a439-63eb-4813-8e1b-34c1432dd839)

In 7.9.3.1

**Comment by grantfitzsimmons** [comment]
<img width="801" alt="image" src="https://github.com/specify/specify7/assets/37256050/1ad8f170-2c12-4906-8b7b-a5675ae5105c">

**Comment by realVinayak** [comment]
say less
