### ISSUE TITLE
Order By option in subview form meta greyed out in read only mode

### ISSUE THREAD

**Issue by combs-a** [specify/specify7#4769]
**Describe the bug**
The Order By option in a subview form meta is greyed out in read only mode, so you can't change it.

**To Reproduce**

1. Go to a Collection Object
2. Enable read only mode through its form meta
3. Go to a subview's form meta after it reloads (I used the Determination subview)
4. See that you can't change "Order By"

**Expected behavior**
For Order By to be changeable (not grayed out).

**Screenshots**
In `edge`:
![image](https://github.com/specify/specify7/assets/71564869/5509b873-785c-47ca-beff-751542f9a269)

In `v7.9.3`:
![image](https://github.com/specify/specify7/assets/71564869/7a3f4bbf-5afb-4263-8d21-fb360d34faac)

Please, also fill out the following information manually:

- OS: Windows 10
- Browser: Firefox
- Specify 7 Version: `edge`
- Database Name: `sdnhm_herps_2_8_24`
- Collection name: `Herp-PC`
- User Name: `testuser`

**Additional context**
[Specify 7 System Information - 2024-04-10T15 59 57.967Z.txt](https://github.com/specify/specify7/files/14934624/Specify.7.System.Information.-.2024-04-10T15.59.57.967Z.txt)

**Comment by CarolineDenis** [comment]
NOTES: 
We currently have the `order picker` used for "order by" disabled if the form is read only
We are using this `order picker` in:
- order by in form meta
- user pref choose collection sort order
- in the attachment
Is there any value of having it disabled for any of those cases when read only is true?
