### ISSUE TITLE
Can save invalid conditional format definitions in table formatter

### ISSUE THREAD

**Issue by combs-a** [specify/specify7#4774]
**Describe the bug**
For conditionally formatted tables, you can add any amount of invalid definitions and save it, which causes infinite load and error messages upon querying/trying to search in the formatted table.

**To Reproduce**

`edge`:
1. Go to App Resources -> Record Formatters -> Any table
2. Check 'Conditional Format'
3. Add a blank field or invalid value (example of 'invalid value' would be putting something besides true/false in a true/false field)
4. Close and save
5. Try to query with `formatted` or use the querycombobox for the table you changed the formatting of
6. See error messages appear, infinite load

`v7.9.3`:
1. Go to App Resources -> DataObjFormatters
2. Add a `<fields/>` or `<fields value="(invalid value here)"/>` tag to one of the formats
3. Save
4. Go through steps 5 and 6 from above

**Expected Behavior**
Unsure, but there shouldn't be error. Issue is also present in v7.9.3.

**Screenshots**
Saving and querying/checking query combo box:

https://github.com/specify/specify7/assets/71564869/eecdea49-839d-48df-b973-400d58dbce5c

Second example of issue:

https://github.com/specify/specify7/assets/71564869/b789f79d-1c3a-4fac-9706-849ea23d2995

In XML formatter (same between `edge` and `v7.9.3`):
![image](https://github.com/specify/specify7/assets/71564869/13865407-3246-40c3-8ab5-8b5bbe10b951)

**Crash Report**
[Specify 7 Crash Report - 2024-04-10T20 41 51.328Z.txt](https://github.com/specify/specify7/files/14937599/Specify.7.Crash.Report.-.2024-04-10T20.41.51.328Z.txt)

- OS: Windows 10
- Browser: Firefox
- Specify 7 Version: `edge`, `v7.9.3`
- Database Name: `sdnhm_herps_2_8_24`
- Collection name: `Herp-PC`
- User Name: `testuser`

**Additional Context**
Similar in behavior to issue #4747 on the surface, but crash report cites IndexError rather than AttributeError.

_Originally posted by @combs-a in https://github.com/specify/specify7/pull/4757#pullrequestreview-1991848646_

**Comment by emenslin** [comment]
Was able to recreate this issue in edge

https://github.com/specify/specify7/assets/150940840/9f0607e3-1e22-4c40-829f-b78e52f4f5db


[Specify 7 Crash Report - 2024-04-30T19_33_29.597Z.txt](https://github.com/specify/specify7/files/15170126/Specify.7.Crash.Report.-.2024-04-30T19_33_29.597Z.txt)
