### ISSUE TITLE
Frontend/templates are not showing and the app shows "Specify is loading"

### ISSUE THREAD

**Issue by DanJhonatan** [specify/specify7#478]
Hello,
I did all the developer instructions of specify7, being attention for each step of tutorial. Everything was done correctly (include the system dependencies). 

However, when I run my server, I can see the login view, enter with my user, choose on collection (it's mean that database connection is working), but the templates, css and js files don't load and, after I select one collection, the app stops on "Specify is loading" message and I can not do anything else. Just go back.

I have some console messages:
Failed to load script with source "http://127.0.0.1:8000/static/js/login.bundle.js"
Failed to load script with source "http://127.0.0.1:8000/static/js/choosecollection.bundle.js"
Failed to load script with source "http://127.0.0.1:8000/static/js/main.bundle.js"

On browser:
![browser](https://user-images.githubusercontent.com/6060492/45436534-63722580-b689-11e8-811a-4d734268fc8b.png)

On linux terminal:
![captura de tela de 2018-09-12 11-42-13](https://user-images.githubusercontent.com/6060492/45433906-92859880-b683-11e8-8df5-b33952cb8e2e.png)

**Comment by benanhalt** [comment]
The test server will only serve static files when debugging is enabled. That is probably the problem. See: https://github.com/specify/specify7/blob/master/README.md#turn-on-debugging

**Comment by DanJhonatan** [comment]
Thanks for your answer @benanhalt . I did what you said and the specify7 is working now.
Thanks again.

**Comment by benanhalt** [comment]
You're welcome!
