### ISSUE TITLE
Conditional format not being removed from xml

### ISSUE THREAD

**Issue by emenslin** [specify/specify7#4784]
**Describe the bug**
When you set a conditional format for a table and then if you remove it and set a non conditional format the xml still shows the conditional format and running a query gives an error.  

**To Reproduce**

1. Go to app resources-> record formatters (using visual editor) 
2. Click on accesssion 
3. Add a conditional format (having at least 2 definitions) 
4. Save 
5. Remove conditional format 
6. Add just one field 
7. Save 
8. Check xml to see it still shows the conditional format 
9. Query and see error 

**Expected behavior**
The xml should remove the old conditional format and correct to the new table format. 

**Screenshots**

https://github.com/specify/specify7/assets/150940840/3fbda393-b601-4873-a39c-f99045059719

**Crash Report**

[Specify 7 Crash Report - 2024-04-12T16_49_06.763Z.txt](https://github.com/specify/specify7/files/14961421/Specify.7.Crash.Report.-.2024-04-12T16_49_06.763Z.txt)

Please, also fill out the following information manually:

- OS: Windows 11
- Browser: Chrome 
- Specify 7 Version: edge
- Database Name: lsumzmammals9823
- Collection name: mammals
- User Name: SpAdmin

**Comment by grantfitzsimmons** [comment]
If the user checks/unchecks "Conditional Format", we need to clear all fields as if no definitions were created. 
Only "Name", "Title", and "Default" should be preserved when it is cleared.
