### ISSUE TITLE
add 'remember me' feature to login

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#48]
see:
set_expiry function in
https://docs.djangoproject.com/en/3.2/topics/http/sessions/#django.contrib.sessions.backends.base.SessionBase.set_expiry

and

https://djangosnippets.org/snippets/1881/

should have master setting to enable.

**Comment by maxxxxxdlp** [comment]
See also https://www.digitala11y.com/understanding-sc-2-2-1-timing-adjustable/

**Comment by maxxxxxdlp** [comment]
New release partially negated the need for this by adding SSO support
