### ISSUE TITLE
Loan Preps not loading when there are a lot of loan preps

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#480]
Discovered by KUVP.
their loan 181 takes a long time to load in Specify 6 because there are 300+ preps. But in Specify 7, the section stays blank.  The loan preps never seen to load

**Comment by yvonneekanim** [comment]
It took about two minutes for all the information for 400+ loan preps to load

**Comment by maxxxxxdlp** [comment]
Fixed in 7.7 by adding loading indicators when fetching more
