### ISSUE TITLE
Add calculated fields to Accession

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4802]
**Is your feature request related to a problem? Please describe.**
Specify 6 has a number of calculated fields for Accession that are not supported in Specify 7.

- `totalCountAmt` - Sum of all Preparation counts based on the `countAmt` field
- `actualTotalCountAmt` - Sum of all Preparation counts based on the `actualCountAmt` virtual field (the count of preparations available after subtracting preps used in interactions)
- `collectionObjectCount` - Count of all Collection Object records in the Accession
- `preparationCount` - Count of all Preparation records associated with COs in the Accession

**Reported By**
CSIRO

From my comment:
> <img width="2044" alt="image" src="https://github.com/specify/specify7/assets/37256050/d4ef29a8-cc91-45ce-8785-a8f91984c5b8">
>
> Specify 7 supports the `actualTotalCountAmt` calculated field, but as Bronwyn mentioned, we do not support the other fields included on the default Accession form (`totalCountAmt`, `preparationCount`, or `collectionObjectCount` )
> 
> The count field you are looking for to give a sum of all collection objects is unfortunately the `collectionObjectCount` field rather than the `actualTotalCountAmt` field which sums the counts of all preparations in the list of associated collection objects.

[See on Asana](https://app.asana.com/0/0/1206146417621746/1206176849663205/f)

**Comment by grantfitzsimmons** [comment]
<img width="983" alt="image" src="https://github.com/specify/specify7/assets/37256050/6ee14747-3b72-4455-8382-2bc4c1989219">

@acwhite211 @CarolineDenis Did we add this in 7.9.4? This is on `edge`

**Comment by CarolineDenis** [comment]
@grantfitzsimmons, this can be closed

**Comment by emenslin** [comment]
Fixed
