### ISSUE TITLE
Viewing highest ranked node causes unload protect

### ISSUE THREAD

**Issue by emenslin** [specify/specify7#4807]
**Describe the bug**
When clicking on the highest node in a tree to view the record if you try to close out of it you get the unload protect.

**To Reproduce**

1. Go to any tree (e.g. storage) 
2. Click on the highest ranking node-> edit
3. Try to close out of the dialog

**Expected behavior**
You should be able to close out of the dialog since no changes were made 

**Screenshots**

Edge

https://github.com/specify/specify7/assets/150940840/d7144941-b527-45d2-80a1-775f8b193beb

7.9.3

https://github.com/specify/specify7/assets/150940840/284f1555-ff45-493d-b2e7-0b2983f5786f

Please, also fill out the following information manually:

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: lsumzmammals9823
- Collection name: mammals
- User Name: Spadmin
[Specify 7 System Information - 2024-04-18T16_27_44.330Z.txt](https://github.com/specify/specify7/files/15027699/Specify.7.System.Information.-.2024-04-18T16_27_44.330Z.txt)

**Comment by acwhite211** [comment]
Ya, good catch, it seems that the problem is just with the root node.  Seems to be working for the rest of the nodes.  Not a huge issue, as the root node is rarely viewed/edited, but worth fixing

**Comment by acwhite211** [comment]
Edit, talked with Caroline, this is the expected behavior for the root node.  So no issue.

**Comment by CarolineDenis** [comment]
@acwhite211, the fact that the taxonomic rank is empty is not an issue but the fact that we have an error on parent is a bug
