### ISSUE TITLE
Cloning an app resource with a visual editor does not clone the visual editor part 

### ISSUE THREAD

**Issue by emenslin** [specify/specify7#4809]
**Describe the bug**
Cloning any app resource that has a visual editor component (e.g. web links, record formatters) only clones the XML portion and you cannot access the visual editor. 

**To Reproduce**

1. Go to app resource
2. Click on any resource with a visual editor (e.g. web links) 
3. Click on the 'clone' or 'add' button
4. Save 
5. See there is no option to switch to visual editor 

**Expected behavior**
It should clone the entire resource and you should be able to use the visual editor 

**Screenshots**

https://github.com/specify/specify7/assets/150940840/d98bbd5a-940b-47e2-9483-a440f2d5e516

Please, also fill out the following information manually:

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: lsumzmammals9823
- Collection name: mammals
- User Name: Spadmin
[Specify 7 System Information - 2024-04-18T19_16_36.584Z.txt](https://github.com/specify/specify7/files/15029547/Specify.7.System.Information.-.2024-04-18T19_16_36.584Z.txt)

**Comment by CarolineDenis** [comment]
@maxpatiiuk, 

is this an issue for you? It's only for certain resources

**Comment by grantfitzsimmons** [comment]
That is because the visual editor only is used when the resource is named exactly WebLinks. Specify will only use app resources that define web links if they are named exactly. This is also true for DataObjFormatters and UIFormatters. Since the resource is cloned, it adds a (2), which means Specify doesn’t recognize it as a resource that can be edited visually nor will it use it as a valid source for web links.

**Comment by maxpatiiuk** [comment]
Grant is correct.

Though, I guess we could make the process better.
Mainly:
- either disable the clone button for such resources (easy, but not ideal)
- or, when clone is pressed, show a dialog prompting the user to pick the destination location for the resource (and ensure the destination does not have a resource by this name already)
  - though I guess this dialog would be useful for most app resource types
  - OR, when creating a new app resource, give an option to select an existing app resource (or even ability to clone from a  default app resource that ships with specify) - this is kind of what Form Definition creation has already

**Comment by grantfitzsimmons** [comment]
>either disable the clone button for such resources (easy, but not ideal)

During today's development meeting, it was decided that this would be the solution for now.

**Comment by CarolineDenis** [comment]
@grantfitzsimmons, 
Can yo confirm that those are the three resources we need to disable the clone button for? 
- WebLinks
- DataObjFormatters 
- UIFormatters

**Comment by grantfitzsimmons** [comment]
We need to disable the clone button for any app resources that are recognized by name alone, which most likely includes:

* TypeSearches
* WebLinks
* DataObjFormatters
* UIFormatters
* QueryFreqList
* QueryExtraList
* DataEntryTaskInit
* InteractionsTaskInit
* UserPreferences
* CollectionPreferences
* ExpressSearchConfig
* leaflet-layers
