### ISSUE TITLE
Partial dates assigning current date portions to the missing sections

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#481]
partial date fields are assigning random values to the missing portions of the dates.
Reported by South Africa
Confirmed in db1 of the test server
I changed the format to both month/year and just year in the start date and cataloged date, entered a value (02/1915 or 1915), and saved the record.  When I viewed the date in the full date format, values like 10 and 28 were put in the missing sections.

**Comment by tlammer** [comment]
The values are not random.  The missing date portions are being filled in by the values for the date the record is created

**Comment by yvonneekanim** [comment]
Partial dates are still assigning current date to missing day/month

**Comment by benanhalt** [comment]
@yvonneekanim when I was fixing the test server I think I mixed up the master and development branches. Would you mind checking this again?
