### ISSUE TITLE
Cloning collection preferences causes a 404 error

### ISSUE THREAD

**Issue by emenslin** [specify/specify7#4810]
**Describe the bug**
When clicking clone on a collection preferences it gives you a 404 error. Probably similar to issues #4683 and #4809 

**To Reproduce**

1. Go to app resources
2. Click on collection preferences
3. Click on clone

**Expected behavior**
You should not get a 404 error. Either you should not be able to clone it or it should let you clone it without error. 

**Screenshots**

https://github.com/specify/specify7/assets/150940840/29ee5094-35cf-419d-98ae-83476a6aa611

Please, also fill out the following information manually:

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: lsumzmammals9823
- Collection name: mammals
- User Name: Spadmin
[Specify 7 System Information - 2024-04-18T19_16_36.584Z.txt](https://github.com/specify/specify7/files/15041608/Specify.7.System.Information.-.2024-04-18T19_16_36.584Z.txt)

**Comment by CarolineDenis** [comment]
NOTES: 
- the id of the directory seems to be the wrong one

**Comment by CarolineDenis** [comment]
Not relevant after https://github.com/specify/specify7/pull/4902
(Remove cloning option for this resource)
