### ISSUE TITLE
Reports using images stored in attachment server fail completely when attachment server is unavailable.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#482]
net.sf.jasperreports.engine.JRException: Byte data not found at: undefined?coll=&amp;type=O&amp;filename=beda3c2e-01e4-45a8-a68e-c9947f3720db.jpg&amp;downloadname=&amp;token=.

**Comment by benanhalt** [comment]
For testing see https://github.com/specify/specify7/issues/191#issuecomment-484255466. The exception listed there is an instance of this bug, so this can be tested by testing with that database and report.

**Comment by yvonneekanim** [comment]
The reports run without errors when the attachment server is unavailable.
