### ISSUE TITLE
Locality form allows user to input invalid latitude/longitude values

### ISSUE THREAD

**Issue by lexiclevenger** [specify/specify7#4822]
**Describe the bug**
When creating a locality, invalid values can be entered into the coordinate fields.

Latitude should be between -90 and 90
Longitude should be between -180 and 180

**To Reproduce**

1. Go to Data Entry
2. Create new Locality
3. Enter a value outside -90 and 90 in the Latitude field
4. Enter a value outside -180 and 180 in the Longitude field
5. See that there is no error

**Expected behavior**
User should be blocked from saving the form after inputting invalid values as in v7.

**Screenshots**

https://github.com/specify/specify7/assets/164079735/169b994b-114e-4528-8fed-0976a2c1672f

[Specify 7 System Information - 2024-04-23T22_05_39.686Z.txt](https://github.com/specify/specify7/files/15083522/Specify.7.System.Information.-.2024-04-23T22_05_39.686Z.txt)

Please, also fill out the following information manually:

- OS: Mac
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: KUPaleoBot_8_31_2023
- Collection name: Paleobotany
- User Name: sppaleobotadmin

**Comment by grantfitzsimmons** [comment]
I can recreate this on `v7.8.13`, `v7.9.3.1`, and `v7.9.4`. Should be resolved ASAP in my opinion
