### ISSUE TITLE
Add Containers as they work in Specify 6

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4826]
Containers should be implemented as they are currently in Specify 6 for review. This is the first part of a multi-step process to achieving https://github.com/specify/specify7/issues/1150, which will be our final implementation for containers in GeoSpecify. This is for internal testing and evaluation before moving ahead.

Currently Container is only half-baked in Specify 7, lacking the plugin on the Collection Object form that Specify 6 has.

It is also missing the plugin on the Container form that allows the user to dictate which Collection Object within a container is the "owner" of the container.

<img width="1364" alt="image" src="https://github.com/specify/specify7/assets/37256050/1a4a2474-84ed-4064-bb59-1c55e62d0bb1">

https://geology-edge.test.specifysystems.org/specify/view/collectionobject/new/

[My breakdown of Container in Specify 6 is available internally here](https://docs.google.com/document/d/1m_Hj3a8N7RXakgne73TrPQeaDr6e1Ssgw7yxMQz-UTM/edit?usp=sharing)

As I currently see it, no database schema changes are required to make this functional.

**Comment by CarolineDenis** [comment]
Closed in favor of COGs
