### ISSUE TITLE
allow unicode characters in passwords.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#484]
currently throws an exception.

**Comment by tlammer** [comment]
need to make sure it works in 6 and 7

**Comment by timo11** [comment]
Six does not allow unicode passwords. The encryption/decryption process fails, and generates an exception popup window.

**Comment by benanhalt** [comment]
Can now use unicode passwords in Specify 7, but be aware that setting a password with nonascii characters will prevent Specify 6 logins from working.

**Comment by yvonneekanim** [comment]
Unicode passwords work in 7
