### ISSUE TITLE
Failed to fetch error when opening Loans/Gifts

### ISSUE THREAD

**Issue by lexiclevenger** [specify/specify7#4850]
**Describe the bug**
Trying to create a new Loan or Gift record triggers a Failed to Fetch error.

**To Reproduce**

1. Open Interactions on the KUPaleoBot_8_31_2023 database
2. Click on Loan or Gift
3. See error

**Expected behavior**
No error message should appear.

**Screenshots**

https://github.com/specify/specify7/assets/164079735/2e5a89d4-732d-4a7e-a782-a8e9a194f0b3

https://kupaleobot8312023-edge.test.specifysystems.org/specify/overlay/interactions/create/Loan/

**Crash Report**

If the bug resulted in an error message, please click on "Download Error
Message" and attach it here
[Specify 7 Crash Report - 2024-04-26T19_44_22.348Z.txt](https://github.com/specify/specify7/files/15134738/Specify.7.Crash.Report.-.2024-04-26T19_44_22.348Z.txt)

Please, also fill out the following information manually:

- OS: Mac
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: KUPaleoBot_8_31_2023
- Collection name: Paleobotany
- User Name: sppaleobotadmin

**Comment by grantfitzsimmons** [comment]
I can't recreate this. Have you tried this on another browser?

**Comment by grantfitzsimmons** [comment]
Closing the issue as it seems cache-related, despite us clearing it...
