### ISSUE TITLE
Creating new tree-related records triggers unload protect

### ISSUE THREAD

**Issue by lexiclevenger** [specify/specify7#4856]
**Describe the bug**
Leaving a new record associated with a tree (such as Taxon, Storage, Geography) without editing it triggers unload protect.

**To Reproduce**

1. Go to Data Entry
2. Create a new Taxon/Storage/Geography record
3. Try to leave newly created record without editing it

**Expected behavior**
Unload protect should not occur unless a user edits the record.

**Screenshots**

https://github.com/specify/specify7/assets/164079735/738f0fc1-1f1a-4aaf-aeb8-404763c7a0f8

https://fitznhmaoct2023-edge.test.specifysystems.org/specify/view/taxon/new/

**Crash Report**

If the bug resulted in an error message, please click on "Download Error
Message" and attach it here

[Specify 7 System Information - 2024-04-29T19_44_26.831Z.txt](https://github.com/specify/specify7/files/15154134/Specify.7.System.Information.-.2024-04-29T19_44_26.831Z.txt)

Please, also fill out the following information manually:

- OS: Mac
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: Fitz_NHMA_Oct_2023
- Collection name: NHMA Vertebrate
- User Name: petrifiedroadkill

**Comment by grantfitzsimmons** [comment]
Can this be recreated on `v7`?

**Comment by lexiclevenger** [comment]
@grantfitzsimmons No, just edge.

**Comment by lexiclevenger** [comment]
This also happens when adding a new record using the 'Add Child' button from the Tree page, but only the first time you try to add a taxon after opening the page. In this case, the button to exit the new record is also labeled 'Cancel' instead of 'Close'.

This is what it looks like the first time you add a new record:
<img width="1918" alt="Screenshot 2024-04-29 at 3 09 07 PM" src="https://github.com/specify/specify7/assets/164079735/ea2cd74f-2f20-4072-be19-724b046b40e9">


This is what it looks like the next time you add a new record:
<img width="1918" alt="Screenshot 2024-04-29 at 3 09 17 PM" src="https://github.com/specify/specify7/assets/164079735/4984252f-082e-4660-9fb0-7af8baa37619">

**Comment by CarolineDenis** [comment]
From lines: 
```
      resource?.set(
        'definitionItem',
        props.defaultValue ?? items?.slice(-1)[0]?.value ?? ''
      );
```

https://github.com/specify/specify7/blob/9349a132d5a549a8265d1d5ae39826f25716b448/specifyweb/frontend/js_src/lib/components/PickLists/TreeLevelPickList.tsx#L143C7-L146C9
