### ISSUE TITLE
Weblinks are confused by mixcase field names.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#486]

**Comment by yvonneekanim** [comment]
Does the name of the weblink have to be mixed case or the label of the field itself?

**Comment by benanhalt** [comment]
This fragment of XML is from the form where the problem was discovered:
```
<cell type="field" id="gan" name="genbankAccessionNumber" uitype="plugin" initialize="name=WebLinkButton" colspan="3"/>
```
The presence of uppercase characters in "genbankAccessionNumber" is what triggered the bug.

**Comment by yvonneekanim** [comment]
Weblinks work as expected regardless of whether field name is mixed case or not
