### ISSUE TITLE
Table Aggregation only uses the oldest aggregation, doesn't respect new selected aggregation

### ISSUE THREAD

**Issue by combs-a** [specify/specify7#4864]
**Describe the bug**
When you create multiple aggregations, the only aggregator used is the oldest one created. Setting a different aggregator as the default, setting it in Schema Config, and changing the Custom Field Format in a Table Format that uses the aggregation does not change it.

**To Reproduce**

1. Go to App Resources
2. Create a new 'Determination' table aggregation (do not remove the old one)
3. Set it as default
4. Query on Collection Object using a Table Format that has the field Determinations -> Aggregated
5. See that it uses the old table aggregation
6. Go back to App Resources -> Table Formatters -> Collection Object
7. Check "Customize field formats"
8. Change the Determination's field format to the new table aggregation's name
9. Repeat steps number 4 and 5
10. (OPTIONAL) Go to Schema Config and set Determination's Table Aggregation to the new table aggregation you made
11. (OPTIONAL) Repeat 4 and 5
12. Delete the old table aggregation
13. Repeat 4, see that it is now using the new aggregation

(Optional on the schema config changes, since unsure if these are supposed to affect queries on other tables. It seemed to not affect anything.)

**Expected behavior**
You should be able to switch the table aggregation.

**Screenshots**
For these, I had table aggregation in the Schema Config -> Determinations set to None.

Steps 1-5:

https://github.com/specify/specify7/assets/71564869/b5994c80-594f-446e-ab2e-bcad58d47dc1

Steps 6-9, then 12-13:

https://github.com/specify/specify7/assets/71564869/51461a01-7680-475a-864c-0733f9cd0698

- OS: Windows 10
- Browser: Firefox
- Specify 7 Version: `edge` and `v7.9.3`
- Database Name: `sdnhm_herps_2_8_24`
- Collection name: `Herp-PC`
- User Name: `testuser`

[Specify 7 System Information - 2024-05-01T15 03 34.772Z.txt](https://github.com/specify/specify7/files/15178274/Specify.7.System.Information.-.2024-05-01T15.03.34.772Z.txt)

**Comment by CarolineDenis** [comment]
@combs-a , 

Could you verify that this is still an issue in https://github.com/specify/specify7/pull/4646? 
Thank you

**Comment by combs-a** [comment]
Sorry I didn't see your comment last week! This did fix the issue with it not respecting the newer aggregation when it was set to default. Good work!

**Comment by combs-a** [comment]
Hm, I've run into the issue again in `v7.9.6`... unsure what happened. In the video below, you can see that the aggregator with `/` is selected as default in Table Aggregators as well as being selected in Schema Config, but it still uses the older aggregation (Determination_2).

https://github.com/specify/specify7/assets/71564869/7abe37f6-89ee-4b7a-aaa5-a8159a2818a8

**Comment by emenslin** [comment]
Fixed
