### ISSUE TITLE
404 when going to edit a subview on Collecting Event using the visual editor

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4876]
**Describe the bug**
When attempting to edit the Collectors subview under Collecting Event, I get a 404.

**To Reproduce**

1. Go to https://ummp91923-edge.test.specifysystems.org/specify/resources/view-set/14/CollectingEvent/CollectingEventSub/
2. Add a Collector in the preview
3. Click the pencil icon to edit the `Collectors` form (which both exists in the current form definition and is explicitly referenced in the XML)
4. See 404

**Expected behavior**
I should then be editing the Collector form rather than seeing a 404.

**Screenshots**

https://ummp91923-edge.test.specifysystems.org/specify/resources/view-set/14/Collector/Collectors/

https://github.com/specify/specify7/assets/37256050/b75c0d69-af2d-41ff-8f33-93f362ff87b8

**Crash Report**

User `bauerjen` in University of Michigan Invertebrate Paleontology

[Specify 7 System Information - 2024-05-02T18_47_53.329Z.txt](https://github.com/specify/specify7/files/15192715/Specify.7.System.Information.-.2024-05-02T18_47_53.329Z.txt)

**Comment by CarolineDenis** [comment]
NOTES: 
The collector form is invalid, hence the broken link. 
If we create a new valid def for collector, the edit link is then working
