### ISSUE TITLE
New view defintions are not used if the name does not match the default

### ISSUE THREAD

**Issue by lexiclevenger** [specify/specify7#4887]
**Describe the bug**
If the name of a view definition does not match the default name, the default view definition is used instead. For example, if the name for the Agent view definition is 'Agent2' instead of 'Agent'. The default view definition will also be used in 7.9.3 as well as Specify 6 instead of the newly created one. This happens even if it is the only view definition for that form in the collection.

**To Reproduce**

1. Create a new Agent view definition
3. Name it something other than 'Agent'
4. Edit using the Visual Editor and save
5. Check the Agent form to see if the view definition you created is visible

**Expected behavior**
The newly created view definition should be used instead of the default.

**Screenshots**
Behavior when the name does not match the default:

https://github.com/specify/specify7/assets/164079735/06237768-10d4-4d68-ad8b-64949c01d65c

Behavior when the name matches the default:

https://github.com/specify/specify7/assets/164079735/018cb1b7-5a77-4ccf-b711-649a5ff74bd1

**Crash Report**

[Specify 7 System Information - 2024-05-03T21_17_00.198Z.txt](https://github.com/specify/specify7/files/15205135/Specify.7.System.Information.-.2024-05-03T21_17_00.198Z.txt)

Please, also fill out the following information manually:

- OS: Mac
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: Fitz_NHMD_Oct_2023
- Collection name: Ornithology
- User Name: petrifiedroadkill

**Comment by CarolineDenis** [comment]
This is not an issue. 
@grantfitzsimmons will post a comment here later on with relevant documentation
