### ISSUE TITLE
Gallery icon remains in fictitious record sets made using "Browse in Forms"

### ISSUE THREAD

**Issue by lexiclevenger** [specify/specify7#4898]
**Describe the bug**
The gallery icon was removed from fictitious record sets in the PR #4220. However, it was only removed from fictitious record sets created using the 'Add' button on an existing form, and not from those created using 'Browse in Forms' from a Query.

**To Reproduce**

1. Use a new or existing Query to query for records
2. Select more than one record
3. Click 'Browse in Forms' to create a fictitious record set
4. See gallery icon in the top right

**Expected behavior**
The gallery icon should be removed in order to be consistent with fictitious record sets made using the 'Add' button:
<img width="1920" alt="Screenshot 2024-05-08 at 4 53 05 PM" src="https://github.com/specify/specify7/assets/164079735/f145160f-96b7-4af7-9e3d-690e030abb0f">

**Screenshots**

https://github.com/specify/specify7/assets/164079735/23b19d06-b928-4129-bfa7-1a2c1aa424d3

[Specify 7 System Information - 2024-05-08T22_03_10.639Z.txt](https://github.com/specify/specify7/files/15255457/Specify.7.System.Information.-.2024-05-08T22_03_10.639Z.txt)

Please, also fill out the following information manually:

- OS: Mac
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: Fitz_NHMD_Oct_2023
- Collection name: Vertebrate Paleontology
- User Name: petrifiedroadkill

**Comment by grantfitzsimmons** [comment]
If there are records in a fictitious record set that have attachments, why would we not show the gallery icon? It seems logical to be able to view attachments using the gallery viewer on any record within a fictitious set _as long as it is not a new record_.

Apologies that I was unable to respond before #4220 was merged. What do you think @CarolineDenis?

**Comment by grantfitzsimmons** [comment]
Based on our discussion, what we need to do is:

* Make the "Create new record set" icon display only
   * when all records in a fictitious record set are from the same table
   * when the record is saved (not when it is new)

* Make the "Attachment gallery" icon display only 
   * when all records in a fictitious record set are from the same table
   * when the record is saved (not when it is new)

The attachment gallery icon can show when there are no attachments in the record set, but it should only be shown under the conditions above.

**Comment by maxpatiiuk** [comment]
> when all records in a fictitious record set are from the same table

Could you please clarify when is this ever the case?
I though Specify only allowed record sets to have records from one table at a time (until we have https://github.com/specify/specify7/issues/2627 😊)
is that something unique to `fictitious record set`? I didn't think so - isn't fictitious record set just a record set we create implicitly on the front-end (and later give user a choice to save it explicitly)?
