### ISSUE TITLE
picklists with more items than their limit show extra values as invalid

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#49]
Probably should check the actual number of items against the limit and somehow alert the user if there are too many.

**Comment by benanhalt** [comment]
In Sp6 the limit only affects the picklists where users can dynamically add values.

**Comment by benanhalt** [comment]
Removing the `limit` option on the request will probably result in a maximum of 20 items being returned. That is the default for the API: to return items 20 at a time. So, I think this may not be fixed.

Use `limit = 0` in the API to return *all* items. Or, it might be safer to limit it to something like 100,000 just to prevent any weird pathological case that would somehow return like a billion items.

**Comment by yvonneekanim** [comment]
Tested in a new database, I am able to add more items past the limit set in the Specify 6 instance of the database.
