### ISSUE TITLE
IntegrityError when trying to delete new user as admin

### ISSUE THREAD

**Issue by combs-a** [specify/specify7#4908]
**Describe the bug**
Made a new guest user with no access to collections/etc. so no agent attached to it. Tried to delete it as an admin and got an integrity error.

**To Reproduce**

1. Log in as an admin user
2. Go to Security and Accounts and create a new user. Don't give it collection access, only give it a username, password and put it in the Guest user group.
3. Save the new user.
4. After the page reloads after saving, try to delete the new user.
5. See crash.

**Expected behavior**
User should've been deleted without any crashes.

**Screenshots**

https://github.com/specify/specify7/assets/71564869/12ae06fe-01c1-45e8-b358-81714b58ea9a

**Crash Report**
[Specify 7 Crash Report - 2024-05-10T20 00 19.385Z.txt](https://github.com/specify/specify7/files/15279581/Specify.7.Crash.Report.-.2024-05-10T20.00.19.385Z.txt)

- OS: Windows 10
- Browser: Firefox
- Specify 7 Version: `edge` and `v7.9.3`
- Database Name: `sdnhm_herps_2_8_24`
- Collection name: `Herp-PC`
- User Name: `testuser`, `sdnhmherp` (Both admin users)

[Specify 7 System Information - 2024-05-10T20 12 46.637Z.txt](https://github.com/specify/specify7/files/15279618/Specify.7.System.Information.-.2024-05-10T20.12.46.637Z.txt)

**Comment by melton-jason** [comment]
From the crash report:

```
'Cannot delete or update a parent row: a foreign key constraint fails (`sdnhm_herps_2_8_24`.`spprincipal_sppermission`, CONSTRAINT `FK9DD8B2FA99A7381A` FOREIGN KEY (`SpPrincipalID`) REFERENCES `spprincipal` (`SpPrincipalID`))'
```

This issue appears to be a duplicate of #2784.
