### ISSUE TITLE
Certain fonts generate errors when report is run

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify7#491]
Users get this exception when using certain fonts:

![image001](https://user-images.githubusercontent.com/28809154/53661853-0bbf7a80-3c27-11e9-83c2-eb230202ac36.png)

**Comment by tlammer** [comment]
will not fix. requires documentation on which fonts can be used and how to add new fonts to list of available fonts.

**Comment by benanhalt** [comment]
Instructions are at https://github.com/specify/report-runner-service#fonts. I sent Norine the list of fonts currently installed on the cloud.

**Comment by benanhalt** [comment]
Superseded by #512
