### ISSUE TITLE
Workbench does not allow highest and lowest lat/long values

### ISSUE THREAD

**Issue by lexiclevenger** [specify/specify7#4914]
**Describe the bug**
Workbench considers the minimum and maximum latitude/longitude values invalid.

Latitude values from -90 to 90 should be valid.
Longitude values from -180 to 180 should be valid.

**To Reproduce**

1. Go to Workbench
2. Upload or create new data set with latitude1 and longitude1 columns
3. Set Latitude1 to -90 or 90
4. Set Longitude1 to -180 or 180
5. Save and Validate
6. See errors

**Expected behavior**
Latitude values -90 and 90 as well as longitude values -180 and 180 should not be marked as errors.

**Screenshots**
<img width="1920" alt="Screenshot 2024-05-13 at 3 10 56 PM" src="https://github.com/specify/specify7/assets/164079735/e03637ce-6b46-47b5-a325-b044eab7049a">

[Specify 7 System Information - 2024-05-13T19_45_03.423Z.txt](https://github.com/specify/specify7/files/15299447/Specify.7.System.Information.-.2024-05-13T19_45_03.423Z.txt)

Please, also fill out the following information manually:

- OS: Mac
- Browser: Chrome
- Specify 7 Version: edge, 7.9.4
- Database Name: Fitz_NHMD_Oct_2023
- Collection name: Vertebrate Paleontology
- User Name: petrifiedroadkill

**Comment by melton-jason** [comment]
Should be fixed as of 9d647e558d256f51284f83c738328601c7c2acc4 in #4548! 
The WorkBench and Locality Update tool should now accept -90 and 90 for latitude values, and -180 and 180 for longitude values.
