### ISSUE TITLE
User IDs other than the original not recognized by RSS Export Feed

### ISSUE THREAD

**Issue by combs-a** [specify/specify7#4916]
**Describe the bug**
Updating the RSS feed on certain databases and on certain accounts gives an error saying that the user does not exist. The original user ID attached to the RSS Export Feed was 30 when first looking at the database, which is Susie Ross. After making an account with this agent, it seems that the RSS feed only works when this user's ID is inputted, and sends the notification to whichever user you're logged in as.

**To Reproduce**

1. Open the `herb_rbge_2_5_2024` database and log in as spadmin.
2. Go to App Resources -> RSS Feed -> XML editor and set userId and notifyUserId to 28754 (ID for the agent connected to spadmin)
3. Try and update the RSS feed. 
4. See that you get an error that "Specifyuser doesn't exist".

Next steps are to validate that this *does* work for other original IDs:

5. Go to App Resources -> RSS Feed -> XML editor and change userId and notifyUserId to 30 (ID for the agent connected to sross)
6. Try and update the RSS feed.
7. See that you get a notification (may take a while).
8. Repeat steps 5-7 while logged in as sross.

**Expected behavior**
The RSS feed should probably send the notification to the userId specified, and the error shouldn't be Specifyuser doesn't exist if there was an issue, since the user clearly does exist.

If userId and notifyUserId aren't used to determine which account the notification is sent to, it's very confusing what they're meant for--if this is expected behavior this may need to be clarified. Currently it seems like you should be able to change this and have it refer to another 

**Screenshots**

RSS Export Feed code used:
```<?xml version="1.0" encoding="UTF-8"?>
<channel>
	<title>Test</title>
	<description>Test</description>
	<item collectionId="4" userId="28754" notifyUserId="28754" definition="DwCA_RBGE" metadata="DwCA_Metadata" days="7" filename="herb.zip" publish="true">
		<title>Herb RBGE RSS Feed</title>
		<id>ba7b743e-3263-4016-aebf-995f0d6a6e19</id>
	</item>
</channel>
```

(Since the export sometimes takes awhile to load, a video is a bit impractical--I can provide one if necessary)

**Crash Report**

Error message:
[ekPk1gGk.txt](https://github.com/specify/specify7/files/15300096/ekPk1gGk.txt)

- OS: Windows 10
- Browser: Firefox
- Specify 7 Version: `edge`
- Database Name: `herb_rbge_2_5_2024`
- Collection name: `Herbarium`
- User Name: `spadmin`

**Comment by CarolineDenis** [comment]
@combs-a , 
Could you verify that it's still an issue in https://github.com/specify/specify7/pull/4660 ? 
Thanks!

**Comment by combs-a** [comment]
Tried following my test instructions, and I ran into an error 404 page after editing the XML. I can't seem to open it back up and edit it again. 

https://github.com/specify/specify7/assets/71564869/3857a606-74b9-4e43-809b-b7798d4d422a

**Comment by combs-a** [comment]
Figured out the problem with it, it was user error and not realizing you had to use Specify User ID and not the ID of the agent associated with the user. Opening a new issue for the 404 now.
