### ISSUE TITLE
Cannot search/replace default values in Workbench

### ISSUE THREAD

**Issue by lexiclevenger** [specify/specify7#4917]
**Describe the bug**
Searching for a value filled using the 'Use Default Value' causes mapping option  'Replace all Matches' to fail.

**To Reproduce**

1. Go to Workbench
2. Create or use an existing data set with empty cells
3. Under Data Mapping, click 'Mapping Options' (gear icon) next to a column with empty cells
4. Enable 'Use Default Value' checkbox, input a default value, save
5. Go to grid editor
6. Search for the default value you chose and hit enter
7. Input a different value for 'Replace' and hit enter
8. See that the values are not replaced

**Expected behavior**

**Screenshots**

https://github.com/specify/specify7/assets/164079735/f42d8efc-e6e6-4b7c-8f4c-a846321c918c

[Specify 7 System Information - 2024-05-13T21_35_28.426Z.txt](https://github.com/specify/specify7/files/15300195/Specify.7.System.Information.-.2024-05-13T21_35_28.426Z.txt)

Please, also fill out the following information manually:

- OS: Mac
- Browser: Chrome
- Specify 7 Version: edge, 7.9.4
- Database Name: Fitz_NHMA_Oct_2023
- Collection name: Vertebrate Paleontology
- User Name: petrifiedroadkill

**Comment by grantfitzsimmons** [comment]
@lexiclevenger Does this work in `v7.9.3.1`?

**Comment by grantfitzsimmons** [comment]
I don't think you should be able to search/replace default values anyway.
