### ISSUE TITLE
Accept report image expression that specify "java.net.Url" as the element class.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#492]
Such as 
```
<imageExpression class="java.net.URL">
<![CDATA["http://biodiversity.ku.edu/sites/all/themes/bootstrap/bootstrap_biotheme/img/jayhawk.png"]]>
</imageExpression>
```

Relates to #437

**Comment by yvonneekanim** [comment]
I'm having some issue using this expression format. iReport will not validate this format

**Comment by benanhalt** [comment]
You may have to edit the XML directly.

**Comment by yvonneekanim** [comment]
Java.net.URL element class is now accepted in image expression. Reports run without errors
