### ISSUE TITLE
Workbench icon used as Batch Attachment Upload default

### ISSUE THREAD

**Issue by combs-a** [specify/specify7#4934]
**Describe the bug**
The default icon (when you haven't selected a path) for data sets in the Attachment Import Data Sets dialog is the Workbench icon.

**To Reproduce**

1. Go to Attachments and click on Import.
2. Create a new batch attachment upload and save.
3. Go back to Attachments and click on Import again.
4. See that the icon for the set is the Workbench icon.

**Expected behavior**
The default icon for Workbench shouldn't be there and it should be something else.

**Screenshots**
![image](https://github.com/specify/specify7/assets/71564869/3f2db8c0-1669-4477-875e-46f44d9a1fb4)

**Crash Report**

Please, also fill out the following information manually:

- OS: Windows 10
- Browser: Firefox
- Specify 7 Version: `edge`, `v7.9.4`
- Database Name: `sdnhm_herps_2_8_24`
- Collection name: `Herp-PC`
- User Name: `testuser`

**Additional context**
In `v7.9.3` there weren't any icons for batch attachment uploads--I think having icons _is_ better than none, but it still shouldn't be the workbench icon.

**Comment by emenslin** [comment]
Can recreate in edge (7.9.6)
