### ISSUE TITLE
Error when opening Loan records uploaded via WorkBench

### ISSUE THREAD

**Issue by lexiclevenger** [specify/specify7#4960]
1)
**Describe the bug**
An error is thrown when opening Loan records uploaded through the Workbench. The records can be opened in 7.9.5 without issue. Likely related to issue #4601.

**To Reproduce**

1. Open this loan record: (https://fitznhmdoct2023-edge.test.specifysystems.org/specify/view/loan/393/)
2. See error

**Expected behavior**
Records uploaded using the WorkBench should open without error.

**Screenshots**

https://github.com/specify/specify7/assets/164079735/57287018-de70-46dc-bc4f-b8b5f8732f01

**Crash Report**

[Specify 7 Crash Report - 2024-05-28T18_58_50.111Z.txt](https://github.com/specify/specify7/files/15474709/Specify.7.Crash.Report.-.2024-05-28T18_58_50.111Z.txt)

Please, also fill out the following information manually:

- OS: Mac
- Browser: Chrome
- Specify 7 Version: Edge
- Database Name: Fitz_NHMD_Oct_2023
- Collection name: Vertebrate Paleontology
- User Name: petrifiedroadkill

**Additional Context**
The linked record was uploaded from the data set labeled 'ISSUE':
https://fitznhmdoct2023-v795.test.specifysystems.org/specify/workbench/279/

2) 
**Describe the bug**
An error is thrown when viewing or saving a loan with unassociated items as preparations. This does not occur in previous versions.

**To Reproduce**

1. Go to Interactions
2. Create a Loan record with or without preparations
3. Click the plus button in the loan preparations subview, then click 'Add Unassociated Items'
4. Save the record and see error

**Expected behavior**
No error should occur when adding unassociated items to Loan records.

**Screenshots**

https://github.com/specify/specify7/assets/164079735/732efd92-7f1a-4d47-8647-163e8f310238

**Crash Report**
[Specify 7 Crash Report - 2024-05-29T18_49_51.072Z.txt](https://github.com/specify/specify7/files/15489486/Specify.7.Crash.Report.-.2024-05-29T18_49_51.072Z.txt)

Please, also fill out the following information manually:

- OS: Mac
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: Fitz_NHMD_Oct_2023
- Collection name: Vertebrate Paleontology
- User Name: petrifiedroadkill

**Comment by melton-jason** [comment]
> TypeError at /api/specify/loan/393/\nunsupported operand type(s) for -: 'int' and 'NoneType'

This error was caused by #4824 

The error happens in the following code: 
https://github.com/specify/specify7/blob/afa695fae15d7b916ffa0e1ea6494a81f44c632a/specifyweb/specify/calculated_fields.py#L107-L111

specifically at `prep["quantity"] - prep["quantityresolved"]`. 

Here is the uploadPlan for the WorkBench dataset. Note that `quantityresolved` is never mapped, so the Loan Preparations will be uploaded with a None (null) quantityresolved. 

```json
{
    "baseTableName": "loan",
    "uploadable": {
        "uploadTable": {
            "wbcols": {
                "loannumber": "Loan Number"
            },
            "static": {},
            "toOne": {},
            "toMany": {
                "loanpreparations": [
                    {
                        "wbcols": {
                            "quantity": "Loan Preparations · Quantity"
                        },
                        "static": {},
                        "toOne": {
                            "preparation": {
                                "uploadTable": {
                                    "wbcols": {
                                        "countamt": "Preparation · Count"
                                    },
                                    "static": {},
                                    "toOne": {
                                        "collectionobject": {
                                            "uploadTable": {
                                                "wbcols": {
                                                    "catalognumber": "Catalog Number"
                                                },
                                                "static": {},
                                                "toOne": {
                                                    "cataloger": {
                                                        "uploadTable": {
                                                            "wbcols": {
                                                                "lastname": "Last Name"
                                                            },
                                                            "static": {},
                                                            "toOne": {},
                                                            "toMany": {}
                                                        }
                                                    }
                                                },
                                                "toMany": {}
                                            }
                                        },
                                        "preptype": {
                                            "mustMatchTable": {
                                                "wbcols": {
                                                    "name": "Prep Type"
                                                },
                                                "static": {},
                                                "toOne": {},
                                                "toMany": {}
                                            }
                                        }
                                    },
                                    "toMany": {}
                                }
                            }
                        }
                    }
                ]
            }
        }
    }
}
```
