### ISSUE TITLE
Error when saving Loan records with unassociated items

### ISSUE THREAD

**Issue by lexiclevenger** [specify/specify7#4963]
**Describe the bug**
An error is thrown when viewing or saving a loan with unassociated items as preparations. This does not occur in previous versions.

**To Reproduce**

1. Go to Interactions
2. Create a Loan record with or without preparations
3. Click the plus button in the loan preparations subview, then click 'Add Unassociated Items'
4. Save the record and see error

**Expected behavior**
No error should occur when adding unassociated items to Loan records.

**Screenshots**

https://github.com/specify/specify7/assets/164079735/732efd92-7f1a-4d47-8647-163e8f310238

**Crash Report**
[Specify 7 Crash Report - 2024-05-29T18_49_51.072Z.txt](https://github.com/specify/specify7/files/15489486/Specify.7.Crash.Report.-.2024-05-29T18_49_51.072Z.txt)

Please, also fill out the following information manually:

- OS: Mac
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: Fitz_NHMD_Oct_2023
- Collection name: Vertebrate Paleontology
- User Name: petrifiedroadkill

**Comment by CarolineDenis** [comment]
Added to issue https://github.com/specify/specify7/issues/4960
