### ISSUE TITLE
Error when saving changes in tree definition forms

### ISSUE THREAD

**Issue by lexiclevenger** [specify/specify7#4964]
**Describe the bug**
After making and saving changes in definition forms, an error message is shown briefly and the page reloads without saving the changes.

**To Reproduce**

1. Go to Trees
2. Click on the pencil button next to a tree
3. Make changes to the name or remarks field and save

**Expected behavior**
No error should occur when saving changes, and the page should not reload unless changes are saved.

**Screenshots**

https://github.com/specify/specify7/assets/164079735/79c4a463-7584-4fe7-aa63-f8f5fbdc4210

[Specify 7 System Information - 2024-05-29T20_10_41.191Z.txt](https://github.com/specify/specify7/files/15490327/Specify.7.System.Information.-.2024-05-29T20_10_41.191Z.txt)

A crash report cannot be downloaded due to the page reload.

Please, also fill out the following information manually:

- OS: Mac
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: Fitz_NHMD_Oct_2023
- Collection name: Vertebrate Paleontology
- User Name: petrifiedroadkill

**Comment by acwhite211** [comment]
This ended up being a simple fix.  I'm going to go ahead and include this in 7.9.6 https://github.com/specify/specify7/pull/4977
