### ISSUE TITLE
Merging agents unchecks isCurrent checkbox in associated determinations

### ISSUE THREAD

**Issue by lexiclevenger** [specify/specify7#4969]
**Describe the bug**

Merging agents that are a determiner for a collection object causes the 'isCurrent' checkbox to become unchecked. 

I was only able to recreate it using the following workflow in 7.9.5 and edge, but Corinna P also reports encountering it in 7.9.3.1 and 7.9.4.

**To Reproduce**

1. Create and save two Agent records
2. Create a Collection Object record
3. Add a determination and add one of the two agents as a determiner
4. Merge the Agent records
5. Revisit the Collection Object record and see that 'iscurrent' is unchecked

**Expected behavior**
The 'isCurrent' checkbox should remain checked after merging the determiner.

**Screenshots**
Before merging determiner:
<img width="1920" alt="Screenshot 2024-05-30 at 1 16 34 PM" src="https://github.com/specify/specify7/assets/164079735/305d1ca0-5e93-4ca9-b7ce-1f00a0ffa3d5">

After merging determiner:
<img width="1920" alt="Screenshot 2024-05-30 at 1 17 42 PM" src="https://github.com/specify/specify7/assets/164079735/85c7a9d7-03a8-499e-ad9e-207e7e94b86f">

[Specify 7 System Information - 2024-05-30T18_22_57.148Z.txt](https://github.com/specify/specify7/files/15504276/Specify.7.System.Information.-.2024-05-30T18_22_57.148Z.txt)

Please, also fill out the following information manually:

- OS: Mac
- Browser: Chrome
- Specify 7 Version: 7.9.3.1 through edge
- Database Name: Fitz_NHMD_Oct_2023
- Collection name: Vertebrate Paleontology
- User Name: petrifiedroadkill

**Reported By**
Corinna P from CSIRO via [Asana](https://app.asana.com/0/1201972579963460/1207440244761554/f)

> We recently noted the isCurrent flag disappearing from determinations (in the hundreds). After a lot of trouble shooting, we have narrowed it down to the agent merging process. It appears to happen where the Determiner agentID is replaced as part of the merge process.

**Comment by realVinayak** [comment]
caused by https://github.com/specify/specify7/pull/4237
