### ISSUE TITLE
Log changed fields in audit log.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#498]

**Comment by benanhalt** [comment]
@timo11 I was working on unicode characters in passwords and noticed that this enhancement currently breaks saving unicode in other fields.

**Comment by benanhalt** [comment]
I created the branch `audit-log` for this issue.

**Comment by timo11** [comment]
The unicode problem seems to be solved. This fix and a lot of logging and log querying code is currently on the summer19 branch.

**Comment by timo11** [comment]
Auditing can be customized with two remote prefs.
auditing.do_audits when false stops auditing completely. To re-enable auditing set it to true or remove.
auditing.audit_field_updates can be set to false to turn off field level auditing.
