### ISSUE TITLE
Can only add a certain amount of Taxon to Determinations before query combo box stops working

### ISSUE THREAD

**Issue by combs-a** [specify/specify7#4983]
**Describe the bug**
When there are many determinations, after a certain amount, you cannot continue to add Taxon via the query combo box until you minimize some of the other determinations if you are using the Grid layout.

**To Reproduce**

1. Go to Data Entry -> Collection Object
2. Open the form meta for determinations and switch Type to Grid
3. Add several determinations and make sure they're not minimized
4. Give each determination a taxon one by one via the query combo box (don't open search, do it directly in the field)
5. See at some point (~4-6 in my tests) that the picklist for the query combo box no longer appears
6. Minimize some of the other determinations
7. Repeat step 4 until 5 happens again

**Expected behavior**
The picklist should not stop appearing at any point.

**Screenshots**

![03_detpicklist](https://github.com/specify/specify7/assets/71564869/7e88e6b9-13e6-438e-b573-3249031ef58e)

**Crash Report**

- OS: Windows 10
- Browser: Firefox
- Specify 7 Version: `edge`
- Database Name: `sdnhm_herps_2_8_24`
- Collection name: `Herp-PC`
- User Name: `testuser`

**Additional context**
Doesn't seem to just be a performance issue on the machine's part, checked on a laptop and two different work PCs.

**Comment by lexiclevenger** [comment]
Related to #3373?

**Comment by combs-a** [comment]
Yes, looks like it. This one seems to be a duplicate then perhaps. Thanks for mentioning it, I didn't find it when I was looking for an open issue on this!

**Comment by combs-a** [comment]
Duplicate of #3373
