### ISSUE TITLE
Validate XML resources when uploading.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#499]

**Comment by maxxxxxdlp** [comment]
Added client-side live validation for XML and JSON resource files.

**Comment by benanhalt** [comment]
Nice. Eventually I would like to validate the schema of the resources as well, where possible. I started defining the schema for the Specify forms here: https://github.com/specify/viewset-schema

**Comment by maxxxxxdlp** [comment]
I see. I opened a separate issue for that.
