### ISSUE TITLE
Workbench rollback success dialog showing on the incorrect data set

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4992]
**Describe the bug**
Similar to https://github.com/specify/specify7/issues/3633

On `v7.9.5`, I was unable to recreate. Can we have another member of the @specify/ux-testing team take a look?

**To Reproduce**

1. I open a workbench and complete the "Roll Back" operation.
2. I dismiss the success-dialog.
3. I switch to another workbench.
4. I am shown the rollback success-dialog AGAIN from doing the previous rollback.

**Expected behavior**
This dialog should only show up in the data set that was rolled back.

**Screenshots**

https://github.com/specify/specify7/assets/37256050/8ad5e93b-fb73-4162-b29a-e81b80e9ebbc

**Reported By**
Matthew Cruz at The University of Michigan

**Comment by sharadsw** [comment]
Which specify version is this? Before `7.9.5`, the workbench would show the last completed operation's result dialog when opening a dataset. Should be fixed in `7.9.5` I believe.

**Comment by grantfitzsimmons** [comment]
@sharadsw Matthew let me know he is using `v7.9.1.1`
