### ISSUE TITLE
Unload protect triggered when switching between records of a record set 

### ISSUE THREAD

**Issue by emenslin** [specify/specify7#4995]
**Describe the bug**
When switching between records in a record set the unload protect gets triggered. This does not happen in 7.9.5 and I believe was working earlier in edge so potentially broken by pr #4977. Not sure if this happens with all record sets but at least seems to happen with most locality record sets. 

**To Reproduce**

1. Go to a locality record set (e.g. https://kufish51623-edge.test.specifysystems.org/specify/view/locality/6858/?recordsetid=10) 
2. Use the arrows to navigate through a few records 
3. See unload protect 

**Expected behavior**
Unload protect should not be triggered 

**Screenshots**

https://github.com/specify/specify7/assets/150940840/a98f70bc-4c0e-41ca-ad5c-29b46f1d4ee6

Please, also fill out the following information manually:

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: lsumzmammals9823
- Collection name: mammals
- User Name: spadmin

**Comment by sharadsw** [comment]
Looks like it broke in #4606
