### ISSUE TITLE
timing problem with resource.populated being set after fetch promise is resolved

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#50]
see the multiple gets of locality 191 in the network pane in the screenshot.
![populated_delay](https://cloud.githubusercontent.com/assets/287254/4564157/eeaf6bb6-4f14-11e4-814c-b49ab6fe7af7.png)

**Comment by benanhalt** [comment]
I have just verified that this issue still exists on the development branch.

**Comment by maxxxxxdlp** [comment]
Should not happen anymore given that fetch promise is saved even before it's resolved, and subsequent requests would use the existing promise, rather than create a new one
