### ISSUE TITLE
Enabled Splash Screen Customization

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#500]
SDSU requested being able to change the splash screen.  This is an option in Specify 6.  They said they share their database with a few other agencies who then share their login information with other researchers.  They want to have their collection name, who to contact, and any terms visible for visitors.  This was a very important issue for the university and one of the reasons they went with 6 in the first place.

**Comment by maxxxxxdlp** [comment]
Added this ability on branch `welcome-page-refactor`

Wiki page with instructions - https://github.com/specify/specify7/wiki/Customizing-the-splash-screen

**Comment by grantfitzsimmons** [comment]
[![image](https://user-images.githubusercontent.com/37256050/164727025-f8b3b60b-00c8-4ae5-843d-62d6b1a06cd8.png)
](https://github.com/specify/specify7/issues/1310)
