### ISSUE TITLE
RSS Feed visual editor allows saving without metadata resource and resource selection dialog doesn't close after selection

### ISSUE THREAD

**Issue by combs-a** [specify/specify7#5000]
**Describe the bug**
Due to using the Create DwC Archive dialogs, the resource selection dialogs don't close after selecting an option (though you can see it update in the background) and lets you skip Metadata Resource.

**To Reproduce**

1. Go to App Resources
2. Create a new RSS Export Feed or open an existing one
3. Choose a DwCA Resource and choose an option
4. See that dialog does not close, but option is selected
5. Close dialog
6. Choose a Metadata Resource and choose an option
7. See that dialog does not close, but option is selected
8. Click skip
9. See that Metadata Resource is now empty
10. Save
11. Open User Tools and click Update RSS Feed
12. See that the notification is an error

**Expected behavior**
Both DwCA Resource and Metadata Resource are necessary for updating the Export Feed, so they should be required. Additionally, the dialogs should close after selecting an option, or at the very least have some more forward indication that it has been changed.

Can be separated into 2 separate issues if needed, but I put them both here due to both issues mainly being from using the Create DwC Archive dialogs.

**Screenshots**

https://github.com/specify/specify7/assets/71564869/b62f31fb-923d-4ad3-b0fc-d1d6ff8fcc78

When switching to XML editor, you can see that it requires metadata:
![image](https://github.com/specify/specify7/assets/71564869/15203250-8bc2-4b49-8bb7-da403172be9a)

**Crash Report**

Error from notification (just says that it's missing the metadata):
[Q2VziBAF.txt](https://github.com/user-attachments/files/15808377/Q2VziBAF.txt)

- OS: Windows 10
- Browser: Firefox
- Specify 7 Version: `edge`
- Database Name: `sdnhmherps_2_8_24`
- Collection name: `Herp-PC`
- User Name: `testuser`

**Comment by sharadsw** [comment]
Does this happen on `7.9.5`?

**Comment by combs-a** [comment]
> Does this happen on `7.9.5`?

No, since the visual editor isn't in `7.9.5` and the XML editor was properly flagging missing required fields.
