### ISSUE TITLE
Cannot open User Tools menu without merge permissions

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#5004]
**Describe the bug**
When attempting to open the user tools menu as a user with only the "Full Access - Legacy" role, I get a permission erorr.

**To Reproduce**

1. Create a user and assign the "Full Access - Legacy" role to them
2. Open the user tools menu
3. See error

**Expected behavior**
A user should be able to use the user tools menu without a permission error if they cannot merge.

**Screenshots**

https://github.com/specify/specify7/assets/37256050/75a07931-c97c-4fab-8dc2-e03e7d47a705

`edge` (testing for `v7.9.6`), cannot recreate in `v7.9.5`

**Comment by melton-jason** [comment]
Is this fixed in #5001?
