### ISSUE TITLE
Schema Config WebLink editing has confusing behavior on Save

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#5011]
**Describe the bug**

- edit web link in schema config embedded dialog
- save changes
- leave page confirmation message appears, warns that schema changes won't be saved (this is confusing)
- If close, it just closes and returns to the embedded weblink editor but the save button is still enabled
- If leave, it closes weblink dialog and returns to schema 

**Expected behavior**
- Upon saving, should load and then remain on webLink dialog
- Save button should be disabled on the dialog and the user can close
- No warning or unload protect for schema should appear in this process
     - Should only get that if: user makes changes to webLink config and clicks Close without saving first

**Screenshots**

https://github.com/specify/specify7/assets/135047322/f6656242-a1ff-470e-8b09-452d8f4a00ec

- OS: macOS
- Browser: Chrome
- Specify 7 Version: 7.9.5
- Database Name: ohiomollusk (localhost)
- Collection name: Bivalves
- User Name: testuser

**Comment by emenslin** [comment]
Fixed
