### ISSUE TITLE
Cannot delete tree ranks 

### ISSUE THREAD

**Issue by emenslin** [specify/specify7#5021]
**Describe the bug**
When making a new tree rank even if it has no nodes it cannot be deleted unless it is the very last rank in the tree 

**To Reproduce**

1. Go to any tree 
2. Add a new rank 
3. Select any parent node that is not the last one 
4. Try to delete the rank 
5. See error 

**Expected behavior**
If there are no nodes in the rank you should be able to delete it, this was the initial behavior in pr #4257 

**Screenshots**

https://github.com/specify/specify7/assets/150940840/f552c581-28d7-4184-a31c-d7264e3b6cf1

Please, also fill out the following information manually:

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: lsumzmammals9823
- Collection name: mammals
- User Name: spadmin

**Comment by realVinayak** [comment]
on_delete shouldn't be that (should be DO_NOTHING)
https://github.com/specify/specify7/blob/a0497035b6cfec7ee9cf552aa9c992816273fef1/specifyweb/specify/models.py#L7060

Looks like a merge error. see original [diff](https://github.com/specify/specify7/pull/4257/files#diff-58d5c35742ada65c2848e45b735f3391fea83ebaceb19fd1e2ed2a68af483623)
