### ISSUE TITLE
Deaccession Total Preps field is calculated incorrectly

### ISSUE THREAD

**Issue by lexiclevenger** [specify/specify7#5037]
**Describe the bug**
The Total Preps calculated field for Deaccessions does not calculate the sum of all associated preparations. Instead, it seems to calculate how many tables (Gift Preparation, Exchange Out Preparation, Disposal Preparation) contain associated preparations.

**To Reproduce**

1. Create a Deaccession record
2. Go to a Gift, Disposal, or Exchange Out record with **more than one preparation** and add it to the Deaccession you created using the Deaccession query combo box
3. Return to the Deaccession record
4. See that the Total Preps field displays '1' instead of the sum of all associated preparations

**Expected behavior**
From the PR #4824:

> Deaccession’s
> - Total Preps (Sum of all associated disposal, gift, and exchange out preparations)
> - Total Items (Sum of all associated collection object preparations)
> 

**Screenshots**
Here, the Total Preps value is 2, when it should be 3.

<img width="1920" alt="Screenshot 2024-06-24 at 1 45 00 PM" src="https://github.com/specify/specify7/assets/164079735/ef9c27ca-925a-4417-a7f5-b4526c606649">

[Specify 7 System Information - 2024-06-24T18_47_03.981Z.txt](https://github.com/user-attachments/files/15960080/Specify.7.System.Information.-.2024-06-24T18_47_03.981Z.txt)

Please, also fill out the following information manually:

- OS: Mac
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: Fitz_NHMA_Oct_2023
- Collection name: NHMD Vertebrate
- User Name: petrifiedroadkill

**Comment by combs-a** [comment]
Also experienced this issue on Firefox in `sdnhm_herps_2_8_24`.
