### ISSUE TITLE
Show Interactions button is not displaying correctly on form

### ISSUE THREAD

**Issue by beach53** [specify/specify7#504]
Latest 6 version changed "Show Loans" button to "Show Interactions" button and the new caption is not displaying correctly.

**Comment by tlammer** [comment]
CSIRO has noticed this and would like it to get resolved

**Comment by maxxxxxdlp** [comment]
From @grantfitzsimmons:

> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/37256050/192625300-fcb38e28-5eb3-44b6-a7c5-8f45658f4b18.png">

**Comment by maxxxxxdlp** [comment]
Fixed. If this still won't work, please post button XML
