### ISSUE TITLE
Show interactions ui plugin needs to be implemented

### ISSUE THREAD

**Issue by beach53** [specify/specify7#505]
may be linked to #504 
In latest version of Specify 6, show loans functionality was changed to show interactions.  7 does not

**Comment by maxxxxxdlp** [comment]
I belive this is just for the button label, not the actual functionality
Also, I belive this is fixed already, but needs verification

**Comment by bronwyncombs** [comment]
Sp7 button reads "Show Interactions" 
Dialog title is "Transactions"
Dialog contents include open loans, resolved loans, and gift records. 
<img width="1438" alt="image" src="https://github.com/specify/specify7/assets/135047322/1fa23672-5121-432c-9664-eff0ec87cb5a">
If there are associated interactions, the dialog will display the count. These record numbers can be clicked on to view associated interaction records. 

https://github.com/specify/specify7/assets/135047322/0c2fe369-f766-4a20-8146-fdc3ec6ac377

---

Sp6 button reads "SHOW_LOANS"
Dialog title is "Show Interactions" 
If preps are in gift or loans, clicking button brings up those records in separate windows 

<img width="1142" alt="Screenshot 2024-01-04 at 12 41 41 PM" src="https://github.com/specify/specify7/assets/135047322/3681200c-8c45-4988-a86d-cc87a028ba77">

https://github.com/specify/specify7/assets/135047322/40f973c4-c013-43f2-b2ea-2c6c161de250
