### ISSUE TITLE
Tree uses so much memory it crashes

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#5067]
**Describe the bug**
Every time you open the Vascular Plants tree in the `hujinnhc` and navigate to 'Orchidaceae' and expand it, the browser runs out of memory.

There are 386,143 nodes in this taxon tree.

**To Reproduce**

1. Log into a test panel copy of `hujinnhc` as `spadmin` and select `Vascular` as the collection
2. Go to `/specify/tree/taxon/?conformation=~~4~3643485~3643486~3655819~3693849~3704974~3732987--------` in the tree (or 'Orchidaceae') and expand species children
3. Wait and see crash

**Expected behavior**
It should not crash.

**Screenshots**

https://github.com/specify/specify7/assets/37256050/4bef9cda-82d4-4b94-a3d5-5b1e83f54d37

**Crash Report**
[Specify 7 System Information - 2024-07-03T17_11_21.670Z.txt](https://github.com/user-attachments/files/16088443/Specify.7.System.Information.-.2024-07-03T17_11_21.670Z.txt)

macOS, Arc, `v7.9.6`

![image](https://github.com/specify/specify7/assets/37256050/c506b13c-968a-4912-b168-7e67000ddf77)
![image](https://github.com/specify/specify7/assets/37256050/0af8f13b-f242-4941-bff8-25db5437bfff)

Chrome, Windows, `v7.9.6`

>Meanwhile, a new and possibly related bug has appeared in the taxon tree. In some genera (I suspect those with more species) when you try to unfold the species list the system thinks for a while (showing a clock icon on the node) and then crashes:
>
> This happens in more than one machine to different users. It's much more problematic the the geography issue because it hangs the whole site and severely affects the workflow.

**Reported By**
Eyal Ben-Hur at The Hebrew University of Jerusalem

**Comment by realVinayak** [comment]
Happened because of https://github.com/specify/specify7/pull/4704. 

A backend solution for this will be better, it'll optimize performance quite a bit. 

@grantfitzsimmons @CarolineDenis Nice first issue

**Comment by grantfitzsimmons** [comment]
RBGE is reporting the same today.

> I wanted to raise an issue we have had several reports of this week, following the upgrade.
> 
> When searching the taxon tree we have had several instances of the tab/Specify crashing and ‘This page is having a problem’ being reported.
>  
> ![image](https://github.com/user-attachments/assets/bf524020-bda4-4c96-b8df-6a8fbc4926a3)
> 
> 
> This was reported today by a user searching the taxon tree for a genus. It was also reported on Wednesday by a different digitiser, and I have experienced this myself as well.
> 
> This only seems to happen when users are searching the taxon tree, and has been noted in different web browsers.

**Comment by emenslin** [comment]
Fixed
