### ISSUE TITLE
Support choosing the Full Name Direction in Sp7 tree def editing interface

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#5073]
**Is your feature request related to a problem? Please describe.**

With the implementation of adding and editing tree ranks and full name construction configuration in Sp7, we left out an ability that Sp6 had: changing the direction that full names are ordered. In Sp6, this option is included in the dialog from clicking the pencil by the tree name in the Edit Tree Definition page

<img width="1273" alt="Screenshot 2024-07-05 at 1 49 57 PM" src="https://github.com/specify/specify7/assets/135047322/dfec3406-416b-449f-8b0b-44dcc6d2fa11">

This has already been run into in the ohio mollusk conversion, but we're able to work around it in this case. 

> one question, while we're on this form — where does the definition for the aggregated field in the "geography" field here live? I want to modify it to display in the opposite order

Still, I think it's important that all functions available in 6 be sufficiently carried over to 7.

**Describe the solution you'd like**
I think a dedicated full name editing dialog with a similar display to the grid view in sp6 could be added. This could be accessed from a button that appears to the left of the rank names once edit ranks is selected? This would allow for all ranks and whether or not they're in the full name to be viewed at once, and give a better place for the 

Icon for button could be "Adjustments" from hero icon

<img width="1151" alt="Screenshot 2024-07-05 at 3 27 13 PM" src="https://github.com/specify/specify7/assets/135047322/ff60d458-cca6-400d-b102-e63ef5c7e3ec">

![image](https://github.com/specify/specify7/assets/135047322/00dc53ab-f5ef-4146-9572-61b20c6182fd)

**Alternatives:**
- In matching 6, this option should be added to the main geography tree edit dialog, rather than the individual edit rank dialogs. Or somewhere else where it appears once for the whole tree. However, putting this in that dialog does seem a bit out of place or risky.

<img width="585" alt="Screenshot 2024-07-05 at 2 57 39 PM" src="https://github.com/specify/specify7/assets/135047322/e4fa024e-9164-47ab-919c-fd8e952f0666">

- This may be able to be added to preferences under the Trees section, but there's the issue of scoping. A global or remote pref line could also be an option but is not ideal since this is harder/more confusing than the way 6 handles it. 

**Additional context**

> Looks like even if you add it to the TreeDef form the field remains readonly...
> Max hardcoded this in Specify  back in October 2022: https://github.com/specify/specify7/commit/2162e3215ef3f9ff066d4301121305d81e0e3aa5
> So there is no way right now to change the full name direction in the application
> ![image](https://github.com/specify/specify7/assets/135047322/1dc8ef55-53ea-4ab8-95cf-4e0c7f04a88c)

> When you create a new TreeDef through the application, it doesn't assign it a fullnamedirection.
> I'd hope Specify 7 just assumes this is forward, but not sure how 6 reacts to that...
> ![image](https://github.com/specify/specify7/assets/135047322/10bcba7e-655b-41fb-85a5-44411f908977)

**Comment by melton-jason** [comment]
As a workaround to not being able to set the full name diretion, you can create a picklist with two items:

| Title   | Value |
|---------|-------|
| Forward | 1     |
| Reverse | -1    |

https://github.com/specify/specify7/assets/64045831/b4722753-9291-4797-870b-964495e0ffde

Actually, this is what the frontend should be doing automatically. 
Looks like that picklist functionality broke somewhere along the line: 

https://github.com/specify/specify7/blob/080b32ceaec14d747291bbb020d6329f48dcedc0/specifyweb/frontend/js_src/lib/components/PickLists/definitions.ts#L143-L146

--- 

 > ![346220602-ff60d458-cca6-400d-b102-e63ef5c7e3ec](https://github.com/specify/specify7/assets/64045831/4eeacf3e-d4ef-4901-bb00-6ad225821fc2)


Using the picklist we defined previously, this layout is actually already possible in Specify 7 by defining a TreeDef form. 

<img width="1437" alt="Screenshot 2024-07-05 at 8 16 42 PM" src="https://github.com/specify/specify7/assets/64045831/7bcdc28d-f9d1-47b8-a95b-c65634bc43ee">

https://github.com/specify/specify7/assets/64045831/fa1ac41e-01eb-42da-a1aa-a667766f9e6b

```xml
<viewdef name="TaxonTreeDef" class="edu.ku.brc.specify.datamodel.TaxonTreeDef" type="form" gettable="edu.ku.brc.af.ui.forms.DataGetterForObj" settable="edu.ku.brc.af.ui.forms.DataSetterForObj">
	<desc>The TaxonTreeDef Table</desc>
	<enableRules/>
	<columnDef>p,2px,p,2px,p,2px,p,2px,p,2px,p,p:g</columnDef>
	<rowDef auto="true" cell="p" sep="2px"/>
	<rows>
		<row>
			<cell type="label" labelfor="name"/>
			<cell type="field" id="name" name="name" uitype="text"/>
		</row>
		<row>
			<cell type="label" labelfor="fullNameDir"/>
			<!--   The FullNameDirection picklist can be explicitly specified here, but is inferred because the PickList is assigned at the Schema Config for the field -->
			<cell type="field" id="fullNameDir" name="fullNameDirection" default="1" uitype="combobox"/>
		</row>
		<row>
			<cell type="label" labelfor="remarks"/>
			<cell type="field" id="remarks" name="remarks" uitype="textareabrief" rows="2" colspan="6"/>
		</row>
		<row>
                         <!--    Not specifying viewname: Specify is using the view called TaxonTreeDefItem (default for the table)   -->
			<cell type="subview" id="items" name="treeDefItems" colspan="8" defaulttype="table" initialize="sortField=rankId"/>
		</row>
	</rows>
</viewdef>
```

**Comment by grantfitzsimmons** [comment]
Fixed for all trees in https://github.com/specify/specify7/commit/6ef80460c66c94db83398beb0b7c63feadbb7ed5

**Comment by grantfitzsimmons** [comment]
Fixed for all trees in https://github.com/specify/specify7/commit/6ef80460c66c94db83398beb0b7c63feadbb7ed5
