### ISSUE TITLE
Properly scope query builder and tree viewer to Taxon records from trees available in the current collection only

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#5079]
**Describe the bug**
Properly scope query builder and tree viewer to Taxon records from trees available in the current collection only

As of https://github.com/specify/specify7/pull/5036, trees are unscoped in several places. This means you can switch between **any tree** within a database as the schema changes required to scope certain trees to a specific collection are not yet added (will be in https://github.com/specify/specify7/pull/5016).

**Expected behavior**
Only trees visible within the current collection should be searchable and selectable in the tree viewer and QB.

**Comment by CarolineDenis** [comment]
Fixed in https://github.com/specify/specify7/pull/5036
