### ISSUE TITLE
Fix Schema Config and View Definition for New SP7 Tables

### ISSUE THREAD

**Issue by acwhite211** [specify/specify7#5098]
For the new Specify 7 only tables added to v7.9.7, we need to add the new fields and tables to the Schema Configurations.

Fix error 'Unable to find SpLocaleConatiner for Role' error when trying to access any of the sp7_only tables in Schema Config.

We also need to add other SP7 only tables that are missing from the Schema config, like spUserRole and spAttachmentDataSet.

Also, we might need to create viewset definitions for the new tables as well.  This will avoid the 404 error for http://localhost/context/view.json?name=CollectionObjectGroupJoin.

**To Reproduce**

1. Go to Schema Config
2. Open up one of the new tables like CollectionObjectType, CollectionObjectGroupType, CollectionObjectGroup, and CollectionObjectGroupJoin.
3. See the error.
4. This also affects the new field collectionobjecttype in the CollectionObject table, and collectionobjecttype in the Collection table.

**Comment by grantfitzsimmons** [comment]
<img width="728" alt="image" src="https://github.com/user-attachments/assets/5fbeac2c-c0c8-41a8-87cb-7d4afd2eb32c">

Note that these relationships should most likely not be visible by default for all collections.

**Comment by acwhite211** [comment]
I wrote a function that creates default values for the schema config, generated from the datamodel.  There might be some fields in the schema config that got generated that we'll want to adjust.

**Comment by CarolineDenis** [comment]
@sharadsw, 
Can you verify that this is fixed with your PR? If yes, can you close it?

**Comment by CarolineDenis** [comment]
Closed in favor of https://github.com/specify/specify7/issues/5258
