### ISSUE TITLE
Support default="today" for PartialDateUI form cells.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#510]

**Comment by yvonneekanim** [comment]
default="today" not populating partial date fields. Tested in db1 using 'fwri' and 'testdb'

**Comment by benanhalt** [comment]
These aren't going out in the next release, so they haven't been merged into the testing branch, yet.

**Comment by benanhalt** [comment]
Ready for testing in the "default-values" build.

**Comment by yvonneekanim** [comment]
I've set catalog dates and determined dates to default to today in two separate dbs and they aren't populating with today's date

**Comment by benanhalt** [comment]
It's working for me in the lsumam database on db2. Maybe your browser cached the old version of the form. Can you try it after clearing your browser cache?
