### ISSUE TITLE
Support navigation backwards and forwards among records added by with "Save and Add Another".

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#511]

**Comment by benanhalt** [comment]
The browser history now records items entered using the "Save and Add Another" button allowing the back and forward buttons to navigate among them.

**Comment by benanhalt** [comment]
This is ready for testing in the `new-record-navigation` build.

**Comment by maxxxxxdlp** [comment]
For next release:
While browser arrows can accomplish this, it is quite implicit and doesn't let you see the total numbers of records or go the the last/first one with single click.
Thus, in addition to current mechanism, there would also be "+", "-", and slider arrows always present (like in sp6) at the top. This essentially creates a "virtual record set". It should also be saveable if the user chooses too.

---

Credit: Suggested by the group during one of the meetings

**Comment by maxxxxxdlp** [comment]
> Is there any way in Specify 7 that we can keep multiple records visible during a session when doing data entry?  I am finding that during a session I need to go back and edit a record I have entered before but can't get to it without searching.  It would be nice if there were arrows at the top (like when I browse in forms from a query) that I could use to navigate between records during a session.  Specify 6 does this and it is very handy.

**Requested By:** @acbentley

**Comment by maxxxxxdlp** [comment]
Suggested by @beach53 

Currently, the form table is only used in subviews.
The feature is underutilized.
It would be nice to also use that for record set items and maybe other places too

**Comment by maxxxxxdlp** [comment]
A simple way to implement this:
Extend the Record Set component to allow being rendered with a front-end only record set (a record set resource that was created on the front-end and does not exist in the database)
The code needs to be modified to check if record set exists on the back-end (`!recordSet.isNew()`) before making API calls.
Also, if record set is front-end only, there should be a button to save it as a real record set
