### ISSUE TITLE
Add support for searching COG Type on COG form

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#5118]
**Describe the bug**
<img width="414" alt="image" src="https://github.com/user-attachments/assets/ac061430-ded6-41d4-8937-ed9ca8413dbd">

No results are returned, despite there being a record:

<img width="294" alt="image" src="https://github.com/user-attachments/assets/ad3a3b70-1a07-40c5-b69d-4e3b071789a3">

Currently, COG types cannot be searched using a QCBX. This needs to be remedied before it is released widely.

## How it should work

<img width="424" alt="image" src="https://github.com/user-attachments/assets/c7f7427e-c87b-4f87-810e-51085d1231f2">

To make this happen in the current release, I did the following:

1. Added to the `TypeSearches` app resource:
```xml
    <typesearch tableid="1018"   name="CollectionObjectGroupType"              searchfield="name" displaycols="name"    format="%s"     dataobjformatter=""/>
```

2. Added the following table format:
```xml
	<format name="CollectionRelType" title="CollectionRelType" class="edu.ku.brc.specify.datamodel.CollectionRelType" default="true">
		<switch single="true">
			<fields>
				<field>name</field>
			</fields>
		</switch>
	</format>
```

**Comment by grantfitzsimmons** [comment]
Let's just do a picklist!

**Comment by CarolineDenis** [comment]
Added to https://github.com/specify/specify7/issues/5215
