### ISSUE TITLE
Create custom form definition for CoJo table to fix child relationship fields

### ISSUE THREAD

**Issue by acwhite211** [specify/specify7#5126]
The CoJo form view is not displaying the `childcog` and `childco` relationship fields because they are not required fields.  The situation is that one of these child fields must to filled out, but not both.  Given this situation, we cannot have both of the fields be required.  We need to create a custom default form definition for the CoJo table so that these two fields appear.

**To Reproduce**

1. Go to http://localhost/specify/view/collectionobjectgroupjoin/new/
2. See that only the `parentcog` relationship appears.

**Expected behavior**
The `parentcog`, `childcog`, and `childco` relationships should all appear.

**Comment by CarolineDenis** [comment]
Closed in favor of https://github.com/specify/specify7/issues/5258
