### ISSUE TITLE
`Sp Audit Log` no longer shows up in query builder 

### ISSUE THREAD

**Issue by emenslin** [specify/specify7#5128]
**Describe the bug**
The sp audit log table does not show up in the list of tables to query on and the only way to query on it is by editing the url or using the embedded query builder to do it by record 

**To Reproduce**

1. Go to queries 
2. Click on `new`
3. Select the edit pencil next to `new query`
4. Scroll down to the bottom of each list 
5. See `Sp Audit Log` (and other tables) do not show up on either list 

**Expected behavior**
All tables should show up in either the selected or possible behavior 

7.9.3.1 (last release it was present) 
![Screenshot 2024-07-22 154654](https://github.com/user-attachments/assets/e5f0ef4d-4aab-406d-9158-749b48afb18f)

**Screenshots**
edge
![Screenshot 2024-07-22 154710](https://github.com/user-attachments/assets/af9c6ed0-6136-4367-96db-8bee9b4a41fe)

![Screenshot 2024-07-22 154807](https://github.com/user-attachments/assets/dae52255-0302-4382-b386-7a4771b79fd5)

Please, also fill out the following information manually:

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge (goes back to 7.9.4) 
- Database Name: lsumzmammals9823
- Collection name: mammals
- User Name: spadmin

**Comment by grantfitzsimmons** [comment]
The table was erroneously hidden when we determined which tables should be visible for the form and record formatter editors. It should be visible for users with the appropriate permissions by default as one of the queryable tables.

**Comment by grantfitzsimmons** [comment]
As of `v7.9.6.2` on our demo fish instance

## Visible in the query list but shouldn't be:

Spdataset
Spmerging
Message
Spuserexternalid
Spattachmentdataset
UniquenessRule
UniquenessRuleField
LocalityUpdate
LocalityUpdateRowResult
UserPolicy
Role
LibraryRole
UserRole
RolePolicy
LibraryRolePolicy
PreparationAttr

## Should be visible in the query list but isn't:

Collection
Discipline
Division
SpAuditLog

**Comment by maxpatiiuk** [comment]
> Visible in the query list but shouldn't be

most of these look like system tables - system tables should be hidden
if they aren't system tables we should change them to be system tables
