### ISSUE TITLE
Correct the tables in the new query list

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#5135]
As of `v7.9.6.2` on our demo fish instance

## Visible in the query list but shouldn't be:

Spdataset
Spmerging
Message
Spuserexternalid
Spattachmentdataset
UniquenessRule
UniquenessRuleField
LocalityUpdate
LocalityUpdateRowResult
UserPolicy
Role
LibraryRole
UserRole
RolePolicy
LibraryRolePolicy
PreparationAttr

## Should be visible in the query list but isn't:

Collection
Discipline
Division
SpAuditLog

**Comment by melton-jason** [comment]
Is this a duplicate of #5128? 
Can one be closed in favor of the other?
