### ISSUE TITLE
In light mode field outline is missing in report query 

### ISSUE THREAD

**Issue by emenslin** [specify/specify7#5149]
**Describe the bug**
When opening a report and then clicking query the outlines for the fields are missing 

**To Reproduce**

1. Go to reports in the navigation bar
2. Click on any report/label 
3. Select query 

**Expected behavior**
They should have the backgrounds like they did in 7.9.5

**Screenshots**
edge: 
![Screenshot 2024-07-26 151809](https://github.com/user-attachments/assets/009c1817-760d-4ac8-9743-7c34981aa4d0)

7.9.5:
![Screenshot 2024-07-26 152305](https://github.com/user-attachments/assets/9f260c71-6964-4c42-b8b4-3b86c4c25152)

Please, also fill out the following information manually:

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: kufish2_12
- Collection name: voucher
- User Name: spfishadmin

**Comment by grantfitzsimmons** [comment]
Encountered several times and others have reported this inside Specify as well

**Comment by grantfitzsimmons** [comment]
Caused by https://github.com/specify/specify7/commit/8c80571775465202b166463b0a5b4c209457319c, fixing now
