### ISSUE TITLE
MOTs: Add `SpLocaleContainerItem` migration for CollectionObjectType to make it available in Schema Config

### ISSUE THREAD

**Issue by sharadsw** [specify/specify7#5172]
Related to #5098

A migration is needed to add relevant records to ~`SpLocaleContainer` and~ `SpLocaleContainerItem` to make `CollectionObjectType` available as a relation in the Schema Config for CollectionObject. This would enable the user to configure a picklist in the Schema Config for CollectionObjectType. A default system picklist for CollectionObjectType containing names of all CollectionObjectTypes in the db also needs to be added.

**Comment by grantfitzsimmons** [comment]
Those records already exist, no? https://github.com/specify/specify7/issues/5192

**Comment by sharadsw** [comment]
Records exist for new geo tables and their fields/relations. The pre-geo tables do not have records for the newly added fields/relations
