### ISSUE TITLE
A single user account can be associated with multiple agents or no agents.

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify7#518]
This causes Specify to generate a generic error

**Comment by maxxxxxdlp** [comment]
Fixed in next release

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/167704532-04634571-6dad-46db-acac-9122b7a964e5.png)

Not a user friendly error but it does prevent this issue.

After trying again, this friendly error appears:

![image](https://user-images.githubusercontent.com/37256050/167704749-4b195594-49ef-4216-97c7-83c9346e84f8.png)

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons The unfriendly error should not happen
Can you test this again?
What are the steps to replicate it?
