### ISSUE TITLE
Cannot view or create Taxon record sets from older WorkBench imports

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#5187]
**Describe the bug**
After the latest changes for multiple trees and MOTs are present on my database, my Taxon record set no longer functions. I also can't create a new record set based on this old import. I cannot recreate before the migrations were run.

I've uploaded this database to the test panel, with the user in this case being `spadmin`. 
Database is `geo_swiss_2024_08_05`.

**To Reproduce**

1. Go to an existing Taxon record set
2. See the `No Taxon matches the given query.` error message
3. Go to the WorkBench data set where you uploaded the taxon records
4. Try to create a 

**Expected behavior**
Existing taxon record sets should still be usable and I should still be able to create a record set from taxonomy uploaded in an earlier version (before MOTs).

**Screenshots**

https://github.com/user-attachments/assets/98999946-93c2-4728-ad9e-e3983eb13920

**Crash Report**
Arc, macOS

Database is `geo_swiss_2024_08_05`. User is `spadmin`

`edge`
Git SHA: https://github.com/specify/specify7/commit/9f37028b2e20f10eb9972d50f4058790b3dcca9f

`No Taxon matches the given query.`: [Specify 7 Crash Report - 2024-08-05T16_25_20.425Z.txt](https://github.com/user-attachments/files/16500287/Specify.7.Crash.Report.-.2024-08-05T16_25_20.425Z.txt)

**Comment by realVinayak** [comment]
@grantfitzsimmons are you sure this isn't because the record was deleted later-on? That is, wb created the tree record, but it was deleted outside of wb. in that case, the error is correct...

**Comment by grantfitzsimmons** [comment]
@realVinayak, you can check the database if you'd like. I believe those records still exist.

The concept of a "correct" error is not something a user would understand.

**Comment by realVinayak** [comment]
I did! Those weren't present....

that's fair, it should likely be a dialog whenever you open a recordset of records that no longer are present

**Comment by grantfitzsimmons** [comment]
@realVinayak I'll check it out! Thank you!

**Comment by CarolineDenis** [comment]
Should be fixed in the WB pr
