### ISSUE TITLE
Schema labels and configuration are not being respected with new tables

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#5192]
**Describe the bug**
Despite each field in the schema config being assigned a label and visibility status, the forms and queries do not respect field visibility, descriptions, or captions.

This is on a local copy similar to `geo_swiss_2024_08_05` on the test panel
 
**To Reproduce**

1. Customize the schema for `collectionobjectgroup` and `collectionobjectgroupjoin`
2. Go to the query builder (`/specify/query/new/collectionobjectgroup/`) or to the form (`/specify/view/collectionobjectgroup/new/`)
3. See that the custom visibility/labels/descriptions are not being respected

**Expected behavior**
It should work as it does across other tables.

**Screenshots**
<img width="1505" alt="image" src="https://github.com/user-attachments/assets/e70eda5e-f3a2-4de4-b237-a229562272dd">

See that a number of these fields are hidden and my custom schema names are not being respected (`isprimary` should be `Is Primary`).

**Crash Report**
System Information:
macOS, Arc
Git SHA: https://github.com/specify/specify7/commit/9f37028b2e20f10eb9972d50f4058790b3dcca9f

[Specify 7 System Information - 2024-08-05T17_13_03.215Z.txt](https://github.com/user-attachments/files/16500712/Specify.7.System.Information.-.2024-08-05T17_13_03.215Z.txt)

**Comment by CarolineDenis** [comment]
See this line: 
https://github.com/specify/specify7/blob/32d330173e2863db7bafb711ab39dad2660b95c9/specifyweb/frontend/js_src/lib/components/DataModel/resource.ts#L104
