### ISSUE TITLE
Adding a Collecting Event record to a CO deletes all Determinations

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#5198]
**Describe the bug**
Adding a Collecting Event record on the CO deletes all Determinations

**To Reproduce**

1. Go to a record with a 'Collection Object Type' set (`/specify/view/collectionobject/126/?recordsetid=13`)
2. Add a dependent Collecting Event via the subview
3. See the determination(s) are all deleted

**Expected behavior**
Those should not be deleted!

**Screenshots**

https://github.com/user-attachments/assets/b28bfa20-e4e0-4fe8-9a6e-26d68d8f9feb

**System Information:**
Arc, macOS

Running locally, this is similar to the database `geo_swiss_2024_08_05` on the test panel.

GitSHA: https://github.com/specify/specify7/commit/196fe71f3ba3276b6fb766b1ed3a338362b01408

[Specify 7 System Information - 2024-08-07T14_46_34.262Z.txt](https://github.com/user-attachments/files/16530336/Specify.7.System.Information.-.2024-08-07T14_46_34.262Z.txt)

**Comment by CarolineDenis** [comment]
NOTES: 
Adding a Collecting Event triggers the fieldChecks collectionObjectType, hence remove any determinations 
(line 173 businessRuleDefs.ts)
