### ISSUE TITLE
CollectionObjectType is not required in bulk carry forward configuration

### ISSUE THREAD

**Issue by lexiclevenger** [specify/specify7#5207]
**Describe the bug**
The collectionObjectType field is required in the database schema, but it is not marked as required in the "Bulk Carry Forward" configuration. If a record is bulk carried forward without the field enabled, the collectionObjectType name will change to the default for the collection. If a Determination for this record is carried over, the resulting record can end up with the wrong collectionObjectType for the Taxon tree associated with the Determination.

**To Reproduce**
You must be in a database that has two or more trees in the same collection, and you must have a collectionObjectType associated with each tree.

1. Add a field for collectionObjectType on the Collection Object form
```xml
<cell type="label" labelfor="cot"/>
<cell type="field" id="cot" name="collectionObjectType" uitype="combobox"/>
```
3. Create a new Collection Object
4. Go to the form meta and click "Show Carry Forward Button"
5. Enable "Show Bulk Carry Forward Count" and click the gear next to it
6. Find the collectionObjectType relationship and uncheck it, then close all dialogs.
7. Choose a collectionObjectType that is not the default for your collection (it should not have the same name as your collection)
8. Create a Determination with a Taxon from the tree associated with that collectionObjectType
9. Fill in any remaining required fields and save
10. Set the bulk carry forward count to be greater than 1 and click "Carry Forward"
11. See that the new records have the wrong collectionObjectType for their Determinations

**Expected behavior**
The field should be forcibly enabled in the Bulk Carry Forward configuration like other required fields.

**Screenshots**

https://github.com/user-attachments/assets/46e6c5ed-58d2-4aee-97c2-b394c75c1953

[Specify 7 System Information - 2024-08-07T19_48_57.067Z.txt](https://github.com/user-attachments/files/16533384/Specify.7.System.Information.-.2024-08-07T19_48_57.067Z.txt)

Please, also fill out the following information manually:

- OS: Mac
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: fwri_1_9_24
- Collection name: Ichthyology
- User Name: spadmin

**Comment by CarolineDenis** [comment]
Will be fixed in https://github.com/specify/specify7/issues/5172
