### ISSUE TITLE
Warn the user that determinations will be cleared when changing Collection Object Type

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#5209]
See the current behavior here:

https://github.com/user-attachments/assets/2c7b0a4b-8b98-42f1-9324-4b53dd7747b5

**All** determinations are automatically deleted when the COT is changed. If there is already an entered determination, we should warn the user that it will be deleted automatically when this change is made. This would provide an opportunity for them to save the information so it isn't lost forever.

**Comment by CarolineDenis** [comment]
close because we do not clear Determinations anymore 

https://github.com/specify/specify7/pull/5248
