### ISSUE TITLE
Make partial dates reflect date format changes

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#521]
When the date format is changed, such as to YYYY-MM-DD, the full date reflects the change, but the partial date (month and year) still shows the default format (MM-YYYY).
Requested by National Shell

**Comment by maxxxxxdlp** [comment]
Fixed alongside https://github.com/specify/specify7/issues/830 by replacing month text box with a proper month picker.
Also, added option in 7cef8e6c to change the partial date formatter for month-year dates

This can be configured via remote prefs:

```properties
# Full Date Format
ui.formatting.scrdateformat=YYYY-MM-DD

# Year/Month format
ui.formatting.scrmonthformat=MM/YYYY

### NOTE:
# Date format and partial date format may be overridden by browser if fancy date picker is used
# which is why there is an option to disable them:

# Whether to use fancy date picker
ui.formatting.accessible_date_input=true

# Whether to use fancy month picker
ui.formatting.accessible_month_input=true
```

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/167703154-8a72466f-560e-4f5f-8537-1ab04e57dcdb.png)

In remote prefs: (`oldfish`)
![image](https://user-images.githubusercontent.com/37256050/167703244-a6f4050f-b5cc-4981-a8cd-e84bf2289c77.png)

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp Do I have this configured incorrectly?

**Comment by maxxxxxdlp** [comment]
Yes you do.
Turns out there was a bug connected with parsing remote prefs. Should be fixed.

Though, I decided to move those options from remote prefs to user preferences as it makes more sense to set accessibility settings on the user level. They are now under the "Forms > User Interface" section in preferences
