### ISSUE TITLE
TreeDefItem default form is missing uiType

### ISSUE THREAD

**Issue by combs-a** [specify/specify7#5210]
**Describe the bug**
The TreeDefItem form definitions are missing uiType by default.

**To Reproduce**

1. Go to App Resources -> New or existing Form Definition
2. Click show all tables and select any TreeDefItem
3. Click Create and select [treename]TreeDefItem (i.e. TaxonTreeDefItem) from under Copy default view definition
4. See "Required attribute uiType is missing" error for multiple fields

**Expected behavior**
Default forms shouldn't have errors that block saving.

**Screenshots**
![image](https://github.com/user-attachments/assets/47edffa4-0072-48d1-98dc-432dd2abca91)

Please, also fill out the following information manually:

- OS: Windows 10
- Browser: Firefox
- Specify 7 Version: `v7.9.6`, `v7.9.4`
- Database Name: `sdnhmherps_2_8_24`
- Collection name: `Herp-PC`
- User Name: `testuser`

**Additional context**
Put under v7.9.8 milestone since it seems like this would line up with the default form changes.

**Comment by CarolineDenis** [comment]
Close in favor of https://github.com/specify/specify7/issues/5258

**Comment by grantfitzsimmons** [comment]
Fixed in https://github.com/specify/specify7/pull/5367/commits/5344210ba00718fdd3015d75b2978fc74d661cb1
