### ISSUE TITLE
Include more identifying info for records in disambiguate records dialog 

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#5212]
**From Robyn @ RBGE on [discourse](https://discourse.specifysoftware.org/t/additional-information-to-help-with-disambiguation-in-the-workbench/1897):** 

> It would be incredibly helpful if the disambiguation dialog box in the work bench could be configured to include some additional information. We often have a situation where we are trying to disambiguate a taxon where there are multiple records for the rank in question in the same family. It is very difficult to know which is the correct record, and we want to keep the ‘duplicate’ records, as they are often homonyms which we need to maintain.
> 
> The inclusion of a record id, or author would be very helpful with this process.
> 
> e.g. Abies in Pinaceae
> 
> ![image](https://github.com/user-attachments/assets/240d5e8d-0e7c-4197-8905-1fa6f5157e45)
> ![image](https://github.com/user-attachments/assets/5c94f3a2-4fea-4b51-9612-7543dc589b21)

**Reported By**
RBGE

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/additional-information-to-help-with-disambiguation-in-the-workbench/1897/2

**Comment by grantfitzsimmons** [comment]
> I don’t know if it’s possible to configure the workbench to do this, but during the taxonomy import, we’re running into issues with ambiguous terms at the species, subspecies, and genus levels. We need to be able to view the author of the taxon description [Taxon table | author field] in order to disambiguate the term.
> 
> Could the workbench be configured to display the author of the taxon when right-clicking on identical terms?
> 

From Jordi at Museu de Ciències Naturals de Barcelona on the [Speciforum](https://discourse.specifysoftware.org/t/additional-information-to-help-with-disambiguation-in-the-workbench/1897/4?u=grant)

**Comment by grantfitzsimmons** [comment]
The API returns this information, the front end just doesn't show it.

You can see the problem:
<img width="1731" alt="image" src="https://github.com/user-attachments/assets/c4ca7230-7feb-4704-bfd3-4a3fee781e43" />


<img width="600" alt="image" src="https://github.com/user-attachments/assets/f452372c-b6e3-42cf-b574-aaf955d449fd" />

Two identically named taxa with different authors:
<img width="400" alt="image" src="https://github.com/user-attachments/assets/12e65d22-8b35-4ff4-8100-4495259a648c" />
<img width="400" alt="image" src="https://github.com/user-attachments/assets/d93b7daa-80d4-4377-b36f-9093654016ab" />

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/additional-information-to-help-with-disambiguation-in-the-workbench/1897/5
