### ISSUE TITLE
Add `Splocalecontaineritem` migrations for new geo fields + COG Type pick list + missing tables

### ISSUE THREAD

**Issue by sharadsw** [specify/specify7#5215]
From: #5191 

A) Some new fields added to old tables in `geodude` still need to be added to Schema Config. 

> On a side note, we should also create the schema config items (splocalecontaineritems) for the other fields created in the migrations of https://github.com/specify/specify7/pull/5032.
These are:
~Collection -> collectionObjectType
GeographyTreeDef -> discipline
GeologicTimePeriodTreeDef -> discipline
LithostratTreeDef -> discipline
TaxonTreeDef -> discipline~ (Added in a different migration)
StorageTreeDef -> institution

~B) We also need to add other SP7 only tables that are missing from the Schema config, like spUserRole and spAttachmentDataSet.~ (Added already)

C) Add picklist for COG -> Cogtype and Cogtype -> type

**Comment by CarolineDenis** [comment]
NOTES: 
can be added in #5118
