### ISSUE TITLE
'make all' connection to web-asset-server

### ISSUE THREAD

**Issue by joshuaganger** [specify/specify7#522]
I'm trying to modify the specify7 Docker container to include a copy of the web asset server.  I can successfully run both in Docker, but when I attempt include the WEB_ATTACHMENT_URL in my local_specify_settings.py file in order to integrate them, the build process attempts to make an http to get web_asset_store.xml.  Is this necessary at build time?  The server isn't running during build, and thus the process fails.  

Thanks for suggestions.

**Comment by maxxxxxdlp** [comment]
Should be fixed in this docker build - https://github.com/specify/specify7-docker/
