### ISSUE TITLE
Bulk Carry Forward has Catalog Number checked and greyed out on certain databases, causing crashes

### ISSUE THREAD

**Issue by combs-a** [specify/specify7#5226]
**Describe the bug**
Catalog Number is checked (and greyed out, so you can't uncheck it) in Bulk Carry Forward settings on databases with regex, non-incrementing catalog # formats. This causes a crash when you try to do Bulk Carry Forward.

**To Reproduce**

1. Go to `sdnhmherps_2_8_24`
2. Create or go to a record
3. Open form meta menu and check both Carry Forward and Bulk Carry Forward settings
4. See that in Bulk Carry Forward, Catalog Number cannot be changed and it is checked automatically
5. Try to use Bulk Carry Forward
6. See error message

**Expected behavior**
Should not be experiencing a crash.

Either Bulk Carry Forward should be disabled in these databases, or catalog number shouldn't be required. Likely the former, since only one form can be unsaved at a time and catalog number is always required.

**Screenshots**

https://github.com/user-attachments/assets/00ec1a27-a573-4b60-bbce-c46ccbc7c134

**Crash Report**
[Specify 7 Crash Report - 2024-08-15T14_55_06.965Z.txt](https://github.com/user-attachments/files/16626512/Specify.7.Crash.Report.-.2024-08-15T14_55_06.965Z.txt)

Please, also fill out the following information manually:

- OS: Windows 10
- Browser: Firefox
- Specify 7 Version: `edge`, `v7.9.7`
- Database Name: `sdnhmherps_2_8_24`
- Collection name: `Herp-PC`
- User Name: `testuser`

**Additional context**
sdnhmherps catalog number format is AAAAAA, which is custom. Unsure of the scope of the issue since I'm unsure how many users use non-incremental catalog numbers like this. Once this is fixed, this needs to be tested on DBs with this setup.

**Comment by CarolineDenis** [comment]
NOTES: 
Verify `const tableValidForBulkClone()`
