### ISSUE TITLE
Create New Tree Tool V1

### ISSUE THREAD

**Issue by CarolineDenis** [specify/specify7#5268]
1. [After multiple tree support is introduced] Next to the dropdown tree type, there is a new "+" icon button.
2. Click on the "+" button to open a dialog with a list of available default trees.
3. Select the tree you want and click "Continue".
4. A form will appear to define the tree name and remarks. Fill out the form and click "Continue".
5. The available rank names for the selected tree will be displayed in a list with checkboxes. Pick the ranks you want to include in your tree and click "Continue".
6. A call will be made to the backend to create an empty tree with just the ranks.
7. Page refresh on original tree

**Comment by acwhite211** [comment]
Fixed in this commit https://github.com/specify/specify7/pull/5080/commits/48e728f6d3afd6498212ae2b91af6951809cab4e
Fixed in #5080
