### ISSUE TITLE
Add default view def for new geo age tables 

### ISSUE THREAD

**Issue by CarolineDenis** [specify/specify7#5285]
New tables: 
- Relative Age 
- Absolute Age 
- Tectonic Unit 
- Relative Age Citation 
- Absolute Age Citation 
- Relative Age Attachment 
- Absolute Age Attachment 

- Do we want to add relative and absolute age to the default geo CO form?

**Comment by grantfitzsimmons** [comment]
>Do we want to add relative and absolute age to the default geo CO form?

I think so
