### ISSUE TITLE
'Default Collection Object Group Types' pick list is incorrectly defined

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#5289]
In the current Geo migration:

```py
 cog_type_picklist = Picklist.objects.create(
            name='Default Collection Object Group Types',
            tablename='Collectionobjectgrouptype',
            issystem=False,
            type=1,
            readonly=False,
            collection=collection
        )
        for cog_type in DEFAULT_COG_TYPES:
            Picklistitem.objects.create(
                title=cog_type,
                value=cog_type,
                picklist=cog_type_picklist
            )
```

This is how it looks in the app:

<img width="451" alt="image" src="https://github.com/user-attachments/assets/34fa22bb-78f5-4b3b-a1c8-e8b52b2efa08">

This means that the pick list is based on the formatted record for the `CollectionObjectGroupType` table, however that table includes no values now. Even if it did, and the table format was the name of the COG, it should be using a fixed number of items.

[COGT-APIreturn.json](https://github.com/user-attachments/files/17171815/COGT-APIreturn.json)

In any case, those defined items don't even show in the UI unless you switch it to "User Defined Items".

* This should **not** be set to a table, and should instead be a system picklist that has fixed values
* Size limit should be set when the record is created

---

# **There should be 2 pick lists:**
1. `SystemCOGTypes`
   - **Type:** `User Defined Items`
   - **Name:** `SystemCOGTypes`
   - **System?:** `True`
   - **Read Only:** `True`
   - **Table Name:** `NULL`
   - **Size Limit:** `3`
   - **Pick List Items:** Discrete, Consolidated, Drill Core
2. `COGTypes`
   - **Type:** `Field From Table`
   - **Name:** `COGTypes`
   - **System?:** `True`
   - **Read Only:** True
   - **Table Name:** `collectionobjectgrouptype`
   - **Field Name:** `name`
   - **Size Limit:** `-1`
   - **Pick List Items:** None!

<img width="509" alt="image" src="https://github.com/user-attachments/assets/ab21161b-3f89-4b4f-8e99-5c43c1cf6cc5">

**Comment by sharadsw** [comment]
Should be fixed in #5257
