### ISSUE TITLE
Creating a COG without a type causes a crashes

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#5293]
After creating my own COG type records, I tried to create a COG.

|COGTypeID|Name|Type|Version|TimestampCreated|TimestampModified|CollectionID|CreatedByAgentID|ModifiedByAgentID|
|---------|----|----|-------|----------------|-----------------|------------|----------------|-----------------|
|1|Discrete|Discrete|0|2024-09-27 21:24:23.420|2024-09-27 21:24:23.420|4|||
|2|Consolidated|Consolidated|0|2024-09-27 21:24:23.420|2024-09-27 21:24:23.420|4|||
|3|Drill Core|Drill Core|0|2024-09-27 21:24:23.420|2024-09-27 21:24:23.420|4|||

It failed when I tried to create a new COG record with this type set:

<img width="938" alt="image" src="https://github.com/user-attachments/assets/7840118e-18e8-4a08-b484-e615668c1c3e">

```
AssertionError at /api/specify/collectionobjectgroup/ Bad URI: Consolidated Request 
```

<img width="893" alt="image" src="https://github.com/user-attachments/assets/4f0a1b78-b600-4b9c-af93-2190db020dce">

[Specify 7 Crash Report - 2024-09-28T02_26_35.341Z.txt](https://github.com/user-attachments/files/17171955/Specify.7.Crash.Report.-.2024-09-28T02_26_35.341Z.txt)

😢

**Comment by sharadsw** [comment]
Cannot reproduce in #5257 
I think your picklist might be a type 2 picklist due to which it's not able to create the correct relation for Cog -> cogtype. It should work with a type 1 picklist like this one.
![image](https://github.com/user-attachments/assets/ecc66bfc-3ef3-4972-b631-704cd24f7841)

**Comment by grantfitzsimmons** [comment]
@sharadsw If I do not set a type, I still get a crash.

<img width="868" alt="image" src="https://github.com/user-attachments/assets/f5c3b517-05e5-4e94-aab3-2853a31678a8">

`IntegrityError at /api/specify/collectionobjectgroup/ (1048, "Column 'COGTypeID' cannot be null")`

[Specify 7 Crash Report - 2024-10-21T18_39_19.808Z.txt](https://github.com/user-attachments/files/17465583/Specify.7.Crash.Report.-.2024-10-21T18_39_19.808Z.txt)
