### ISSUE TITLE
Subview with `defaulttype="table"` limits to 20 items 

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#5298]
**Describe the bug**

> In Collecting Event form, we have Collection Object subview, which we have set to default as grid view rather than sub form, so users can scroll down a list of collection objects attached to the Collecting Event. 
> However, the list only displays and scrolls down over the first 20. To look at the other collection objects, you need to adjust on the fly to subform view type.
> ![image](https://github.com/user-attachments/assets/05714d35-c97b-43e6-8a0d-e8400841cb8e)
> 
> If you go into demofish, and change the type from subform to grid for the Collection Objects in this Collecting Event, you can see what I mean. There are 26 objects, but you'll only see 20 in grid view. [Collecting Event: 054-RFM-04: 2004-09-02: USA, Kansas, Montgomery: Drum Creek, 37.267665863, -95.5879974365 | Specify 7 (specifycloud.org)](https://sp7demofish.specifycloud.org/specify/view/collectingevent/8/)
> This 20 limitation isn't in Loan forms, if you have more that 20 loan preparations, you can see them all in grid view.
> This old closed ticket seems to suggest there may be an intended limit of 20 in some cases [If a grid view contains more than 20 items, it is truncated, but no warning that data is missing is shown · Issue #1936 · specify/specify7 (github.com)](https://github.com/specify/specify7/issues/1936)

The issue Zoe links is resolved by [this commit](https://github.com/specify/specify7/pull/1976/commits/0565b6221c6731dd0eee11488f816fd33194481d) in PR #1976. The reviews don't explicitly show this as being fixed, but I have confirmed the bug is present on demofish and ohiomollusks and needs to be addressed again. 

**To Reproduce**

1. Go to [ohiomollusks CE example record](https://ohiomollusk07302024-v7.test.specifysystems.org/specify/view/collectingevent/290978/) on test panel (ID: 290978)
2. Scroll down to Collection Objects subview, see count above 20
4. See limit of 20 CO table items on form

**Expected behavior**
Scrollbar: Load additional items automatically within panel/`rows="#"` allotment; scroll bar appears on right (i.e. QB mapped fields list and results list behavior)

https://github.com/user-attachments/assets/35962c99-f719-4cc6-bc9f-81944188dfcc

Another idea is adding pages; a dropdown to select the amount shown (e.g. 20, 50, 100, unlimited), and paginator arrows. 
<img width="430" alt="Screenshot 2024-10-01 at 2 08 39 PM" src="https://github.com/user-attachments/assets/267dba94-04f6-4c19-b39e-d34fe7ffd524">
We don't know how many records with grid subviews containing more than 20 records exist across instances, but ideally the page UI would only be added to these forms when there are more than 20 records added. Because of this, I think the scrollbar and continuous loading would suffice. 

**Screenshots**

https://github.com/user-attachments/assets/a52e99f3-3073-458a-ae26-2477aa24ceb7

- OS: macOS
- Browser: chrome
- Specify 7 Version: `v7` [[Git SHA]](https://github.com/specify/specify7/commit/production)
- Database Name: ohiomollusks_7_30_2024
- Collection name: bivalves
- User Name: testuser

**Reported By**
Zoe @ CSIRO

**Comment by melton-jason** [comment]
Will be fixed in #5253!

**Comment by grantfitzsimmons** [comment]
Verified that this is working on `production`!

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/incomplete-sets-of-related-records-are-displayed-when-subform-views-are-formatted-as-grids/2291/2
