### ISSUE TITLE
Save blocker prevents user from selecting valid taxon from querycombobox in Collection Object form

### ISSUE THREAD

**Issue by mpitblado** [specify/specify7#5299]
**Describe the bug**
When searching for a taxon in a querycombobox from the Collection Object table in Data Entry, an error appears when a valid taxon is selected, preventing the user from being able to save the record.

**To Reproduce**
1. Click on Data Entry
2. Select Collection Object
3. Scroll down to the Determinations subview
4. Enter any taxonomic identification into the Taxon querycombobox
5. Notice that the field will turn red, an error message will appear, and the save button for the Collection Object will be disabled.

**Expected behavior**
The user is able to enter a taxonomic identification that is a node in the tree and click save.

**Screenshots**
![image](https://github.com/user-attachments/assets/0ead89fd-351a-4878-a9fa-ad91eaff07e8)

**Crash Report**

N/A

Please, also fill out the following information manually:

- OS: Windows 10
- Browser: Firefox 130.0.1
- Specify 7 Version: 7.9.7
- Database Name: beaty
- Collection name: Birds, mammals, vascular plants tested. Assumed to affect all collections

**Reported By**
Beaty Biodiversity Museum

**Additional context**
This appears to be a regression with the 7.9.7 release. May be resolved by 572c2493da5c4773ab375cd71ac81109cdf5aebd

**Comment by grantfitzsimmons** [comment]
I can recreate:
<img width="1030" alt="image" src="https://github.com/user-attachments/assets/4a704ee4-a95e-438b-a565-b92a6b9ff136">

**Comment by grantfitzsimmons** [comment]
![image](https://github.com/user-attachments/assets/8246efd1-4be7-47a9-8775-1d5cce2f9127)

This is a migration issue

**Comment by sharadsw** [comment]
Save blocker has been removed in #5248
