### ISSUE TITLE
viewUrl called on resource w/out id CollectionObjectResource

### ISSUE THREAD

**Issue by shuaiscott** [specify/specify7#53]
I connected a Specify 6.6 database to Specify 7 and when trying to create a Collection Object, or viewing a Record Set, I get this error in the JavaScript console in Chrome.
I didn't get any errors when running the debug. 
I tried this on another database, and these functions worked flawlessly.
Other functions like creating a new Taxon or Agent work fine.

``` bash
main-built.js:217 viewUrl called on resource w/out id CollectionObjectResource {specifyModel: r.Model, dependentResources: Object, cid: "c169", attributes: Object, _changing: false…}_changing: false_events: Object_pending: false_previousAttributes: Objectattributes: ObjectbusinessRuleMgr: nchanged: Objectcid: "c169"dependentResources: ObjectneedsSaved: truenoBusinessRules: undefinednoValidation: undefinedrecordsetid: 40saveBlockers: ispecifyModel: r.Model__proto__: i
```

```
System Information
Version:	v7.0.0-7-gc899ce9(debug)
Specify 6 Version:	6.6.00
Database Version:	6.6.00
Schema Version:	2.1
```

Thanks for all your hard work on this!

**Comment by benanhalt** [comment]
Are you seeing any incorrect behavior or just the error in the console?

**Comment by shuaiscott** [comment]
The whole form for viewing/editing the information doesn't show up. The entire screen is blank besides the Specify menu bar

![image](https://cloud.githubusercontent.com/assets/5650363/5901768/5adb350e-a532-11e4-804b-2af70b0f5071.png)

**Comment by benanhalt** [comment]
We have the following databases from BYU from when they were converted. If it is one of these that is showing the problem, I will import it here and see if I can replicate the problem.

-rwxr-xr-x 1 ben ben  15453215 Jan 27  2012 Birds2_6.sql
-rwxr-xr-x 1 ben ben  14025204 Mar  8  2012 BYUbirds8Mar.sql
-rwxr-xr-x 1 ben ben  52303861 Jan 26  2012 Entomology_6.sql
-rwxr-xr-x 1 ben ben  36607949 Jan 27  2012 Fish3_6.sql
-rwxr-xr-x 1 ben ben  38041962 Jan 31  2012 Herps3_6.sql
-rwxr-xr-x 1 ben ben  26912102 Jan 31  2012 Lichens2_6.sql
-rwxr-xr-x 1 ben ben 153891678 Jan 27  2012 Plants_6.sql
-rwxr-xr-x 1 ben ben  25657289 Jan 31  2012 Shells2_6.sql
-rwxr-xr-x 1 ben ben   6452102 Jan 27  2012 Trophy_6.sql

**Comment by shuaiscott** [comment]
This is a database that was created since the upgrade. Could I email the mysql dump to see if you could replicate it?

**Comment by benanhalt** [comment]
Absolutely. If it's small enough to attach (10mb?) you can send it to me directly at ben.anhalt@gmail.com. If it is too big for that, email Theresa at specify@ku.edu and she can tell you how to upload it to us.

**Comment by shuaiscott** [comment]
Thanks Ben!

**Comment by benanhalt** [comment]
You will need to redo the 'make ...' steps from the README after 'git pull'.

Thanks for your patience and help shaking out these issues.
