### ISSUE TITLE
Cannot open Workbench on some test panel DBs

### ISSUE THREAD

**Issue by combs-a** [specify/specify7#5308]
**Describe the bug**
On `sdnhmherps` and `ChadronTest` in the test panel, an IntegrityError occurs when trying to create a new dataset through either Create New or Import.

**To Reproduce**

1. Go to one of the above databases
2. Click on Workbench
3. Click Create New
5. Go back to Workbench after reloading
6. Click Import
7. Import a CSV
8. Try to upload
9. See error

**Expected behavior**
No error.

**Screenshots**

https://github.com/user-attachments/assets/138530cc-cec3-4831-a7fb-3b8ce83bbffd

**Crash Report**

From create new:
[Specify 7 Crash Report - 2024-10-03T20_41_33.885Z.txt](https://github.com/user-attachments/files/17250018/Specify.7.Crash.Report.-.2024-10-03T20_41_33.885Z.txt)

From import:
[Specify 7 Crash Report - 2024-10-03T20_53_57.628Z.txt](https://github.com/user-attachments/files/17250019/Specify.7.Crash.Report.-.2024-10-03T20_53_57.628Z.txt)

Please, also fill out the following information manually:

- OS: Windows 10
- Browser: Firefox
- Specify 7 Version: `v7.9.5` to `v7.9.7`
- Database Name: `ChadronTest` and `sdnhherps_2_8_24`
- Collection name: `Paleo` and `Herp-PC`
- User Name: `testuser` for both

**Additional context**
Pretty sure its a migrations issue, considering these databases were fine in 7.9.5 and 7.9.6 last I knew.

**Comment by realVinayak** [comment]
Ughh a side-effect of https://github.com/specify/specify7/pull/4929. However, I fixed that, so if you were to open the database under `wb_improvements` again, it would automatically be fixed.

**Comment by combs-a** [comment]
Yep, that fixed it! Probably should have some kind of message/etc in Slack so other people on the test panel know that that's all they have to do will fix it.
