### ISSUE TITLE
Cleanup static files and fix related issues 

### ISSUE THREAD

**Issue by CarolineDenis** [specify/specify7#5312]
1) Existing issues: 

- [x] https://github.com/specify/specify7/issues/4591
- [x] https://github.com/specify/specify7/issues/3120
- [x] https://github.com/specify/specify7/issues/364
- [x] https://github.com/specify/specify7/issues/5073
- [x] https://github.com/specify/specify7/issues/1254
- [x] https://github.com/specify/specify7/issues/4737

2) Cleanup duplicates 
Besides that, since there is a lot of duplication for each discipline, I've only left a single comment for each type of app resource in a single discipline. Any comments on a type of app resource should apply anywhere it appears.
If there are no comments on a type of app resource, that means I found usages of the app resource in Specify 7 and it should be kept.

- [x] [config/accessions/app_resources.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-34065b584f85c34ad58457af9b4dad00a5621f989e4660f18fa83bfa0243212a)
I actually don't think Specify 7 accesses any file in the `accessions` directory. 
It looks like it is supposed to be a type of discipline, but even if a discipline has the `accessions` type, it's not defined in the DISCIPLINE_DIRS: 

https://github.com/specify/specify7/blob/2a0b516e3e249816a90fb0c196875670ca41cbf0/specifyweb/context/app_resource.py#L26-L41

So it will never be accessed when determining the file path: 

https://github.com/specify/specify7/blob/2a0b516e3e249816a90fb0c196875670ca41cbf0/specifyweb/context/app_resource.py#L88-L103

- [x] [config/backstop/collstats.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-4df51c7f62b7884525190bad0e74c3f3343ae0e981a46548b8ad4a190eb2e186)
This file shouldn't be needed: Specify 7 has its own implementation for statistics.
Although, people can still access this file using /context/app.resource?name=CollStats, so keep it if you want 🤷

2) Shouldn't be needed: 
- [x] [config/backstop/preferences.views.out.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-eac3f630927c8d9a7f7ef60641ca94d6d66832ae21a4ef36a0f6dc6f5f84ecac)

- [x] [config/backstop/prefs_panel_def.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-9d14fcc247febb192550e26c0954fd5e3dc3096b7d199300ea338a0625c3ad39)

- [x] [config/backstop/security.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-132f53d788a7759eb4ffe1c652a9b09c56378f4af137da3e968a9b27d4127ef2)

- [x] [config/backstop/statistics.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-06d060f3f4233573f438eaad36a2e8a67876eb8935fcfc64b576089762e2ae22)

- [x] [config/accessions/accessions.views.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-286e98631680c05e1329001d6d20cd9bf9fc8c271581115bf8cc2d17fc2a7362)

- [x] [config/backstop/dialog_defs.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-9bef4dee2f54ca700dec6be53a54e569cc4b634b5a4ba0fcd75f49c6afe4fd53)

> I'm pretty sure this file shouldn't be needed either. 
> I couldn't find any references to this file (even with its "human readable" name: DialogDefs) except in a static test file on the frontend. 
> 
> Looks like Specify 6 uses this to define the respective Java classes for all Dialogs which are used in the App:
> https://github.com/specify/specify6/blob/master/src/edu/ku/brc/specify/ui/DBObjDialogFactory.java
> (Something that Specify 7 doesn't care about) 
> 
> Further, for all views in Specify 7, Specify accesses the `viewset_registry.xml` in the level directory and iterates over all entries in the registry: 
> 
> https://github.com/specify/specify7/blob/2a0b516e3e249816a90fb0c196875670ca41cbf0/specifyweb/context/viewsets.py#L38-L46
> https://github.com/specify/specify7/blob/2a0b516e3e249816a90fb0c196875670ca41cbf0/specifyweb/context/viewsets.py#L124-L144
> 
> So most of the time, Specify 7 is directly getting the search views from `search.views.xml` in backstop: 
> https://github.com/specify/specify7/blob/8534551acea49e4721587d6b0259abd6edf20307/config/backstop/viewset_registry.xml#L5

- [x] [config/backstop/editorpanel.views.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-53011939e62e7611dd6bef72b97489a929c447e373d7ad825645294823802a61)

- [x] [config/backstop/gbif.views.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-ff2ba49445ed33fe48c0892a2e64c9de44c64764a94378b366742dfce9ed86ad)

> This specific view file is commented out in the backstop viewset registry, so it will never be used currently: 
> https://github.com/specify/specify7/blob/8534551acea49e4721587d6b0259abd6edf20307/config/backstop/viewset_registry.xml#L6
> 
> Additionally, the GBIFCollection will not work as a Specify 7 form 
> It also has a similar definition in `global.views.xml` which Specify 7 can not use, and so can be removed

- [x] [config/backstop/preferences.views.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-515a91e2cb1912fb37551d6890ba0192f2d2520564993698dca08cfac5bfe90d)

> Same thing as `CollStats` and similar views in the backstop viewset registry: this viewset is used to create the forms for preferences in Specify 6. 
> 
> See the Java files in the below directory for references - you can search for the string `createForm("Preferences` -  
> https://github.com/specify/specify6/tree/master/src/edu/ku/brc/specify/prefs
> 
> Specify 7 doesn't really care about this file then, as it has its own implementation of preferences. 

- [x] [config/backstop/search_config.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-b9a3712e8675ddb2458b70220f005733ab8613868f7d5e3ef783bb68017d044f)

- [x] [config/backstop/uistrformatters.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-ea014d3132946ba98ddf53ee929541b2795894915fe808da10dd4a25e6e9c733)

- [x] [config/bird/guest/startup_panel.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-aab45c37cbee81b55d4c14a591031c2ed27ab4fcada4c4d2210c4fc7e08caed5) 

> All StartUpPanel files (startup_panel.xml in the app resource registries) are not used or accessed by Specify 7

- [x] [config/bird/guest/statistics_panel.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-6fe3d7cf740ddd08631ab34fdbfec22caf43e573da5239fffb45f6dcc7cf35ff)

> All StatisticsPanel files (statistics_panel.xml in the app resource registries) are not used or accessed by Specify 7

- [x] [config/bird/guest/stats_summary_panel.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-41898ad46cc52f6070d2fe03ea11ca27734346817e43b7c55eb91a93db869a85)

> All StatsSummaryPanel (stats_summary_panel.xml in the app resource registries) are never used or accessed by Specify 7.

- [x] [config/bird/picklist.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-efb91cd285fa95075a84500bb905bffd83416984f5ba52d5ac0225047c4f06c1)

> All <discipline>/picklist.xml files are unused by Specify 7.

- [x] [config/bird/preptypes.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-6b3dd3c4277f505e07f2f3d542b43a9da5a0b04026924010569a267b0cfe9429)

- [x] [config/bird/queryextralist.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-ee199fbd39d9b8f2d9b1be6fbaf01cb41dde9cb5d3fca3118a69702ea38934c8)

> Specify 7 also doesn't use the <discipline>/queryextralist.xml (aka, QueryExtraList).

- [x] [config/bird/queryfreqlist.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-60401e7db13e7beac880e72edb7ffc2cbe8de83f9fcff294e29852aa61cebf46)

> Specify 7 also does not use the <discipline>/queryfreqlist.xml (aka, QueryFreqList).

- [x] [config/bird/show_fields.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-ec34abe8789152fea26cf7ababc88f68a00899cc906457757ba4bec409a9a61f)

> Specify 7 does not use any of the <discipline>/show_fields.xml files.

- [x] [config/bird/startup_panel.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-70e578f1009e31eeba2157880b3ea5da266c38aa0fff5b67b4f4f7673f340c8e)

> Specify 7 doesn't use any of the <discipline>/startup_panel.xml files (aka StartUpPanel).

- [x] [config/bird/statistics_panel.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-8b6329f9672ad1a6db27d98078cb0078d697628cb56f0f517324e66c02af06f5)

> Same thing with the other statistics related files: Specify 7 does not use any of the <discipline>/statistics_panel.xml files.

- [x] [config/bird/stats_summary_panel.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-87ec96c54a1c82c8c9a833d45ce95b7ceb08a8fefc5bd5b9785ec502622f02c8)

> Specify 7 doesn't use any of the <discipline>/stats_summary_panel.xml files (StatsSummaryPanel).

- [x] [config/bird/taxon_init.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-ebcd073d8d73f30bb8fefd264aea4e76d7cb795ccdcaeb3bc3361065700501dd)

> Specify 7 doesn't use any of the <discipline>/taxon_init.xml files.

- [x] [config/botany/default_sgr_matchers.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-ddba286a91048eabbd63fbb44f4b7fac7a3dd3d00ccd24b8e919f5a06e0f8706)

- [x] [config/defaultperms/prefsperms.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-e8791681c388dc8de85a0e9bae995d4f1ec443efe10604b1e534270175d50137)

- [x] [config/defaultperms/tasks.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-0ed5c4293f98e8b3ac82224d20523891b6853937c428307917faf403d10b001f)

- [x] [config/defaultperms/dataobjs.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-b5d4624674def6e18fa777a5e25468aa91355b41221f560e880e73be352947d0)

- [x] [config/disciplines.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-270b62ad52c2b2382151c2276229992b434c4d5b9868069c54b9464fe086b2cc)

- [x] [config/icon_factory_mapping.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-2f693ceda2a00fa328fd53180542740d025d84f29955412f4cb122ff19530485)

- [x] [config/ireportconfig.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-4a6de9eaab2f6298ddd4b2236ff32ac273a78b30d352f9ffa144ba705f9a2d92)
- [x] [config/specify_workbench_upload_def.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-69f6dca841e58b3f9cbb3eec1132cd4d3231c83196478e872684856676f83762)

3) change the path of the config directory: 
- [x] [config/bird/schema_localization.xml](https://github.com/specify/specify7/pull/5266/files/8534551acea49e4721587d6b0259abd6edf20307#diff-8af9de8d0c31f1435ed942996066ae82810f137644781ddf89a7cbf77ae059cd)

> Looks like @maxpatiiuk already started integrating these `schema_localization.xml` files with Weblate: 
> 
> https://github.com/specify/specify7/tree/production/specifyweb/frontend/js_src/lib/localization/schema-localization
> 
> Though now that we have the files directly in the Specify 7 repository, maybe we can change the path of the config directory which lot of that code uses: 
> 
>https://github.com/specify/specify7/blob/2a0b516e3e249816a90fb0c196875670ca41cbf0/specifyweb/frontend/js_src/lib/localization/schema-localization/pull.ts#L27-L30

From the analyze of @melton-jason on pr https://github.com/specify/specify7/pull/5266

**Comment by maxpatiiuk** [comment]
Is this issue going to be resolved in the same PR or a separate PR?
I would strongly encourage to delete the useless file in the PR that added them and then squash-merge the PR so as not to pollute our git history with needless files.
The history in the Specify 6 repo was quite polluted, and repository was quite slot - one of the first things Ben did at Specify was to clean up the git history of sp6 - let's not have to do the same in sp7

**Comment by grantfitzsimmons** [comment]
Fixed in https://github.com/specify/specify7/issues/3120
