### ISSUE TITLE
The querycbx for tree parent nodes can't find nodes below the 20th level of a given tree.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#532]
From original email:

> Ku ento is having issues adding children to subgenus level from the forms in Specify 7.  If they try to add a child in the tree, it is not an issue.  But, if they go to Collection Object -> determination, then click the plus to add a new taxon, Specify will not find the subgenus when entered in the parent field.  The same thing happens if they go to Taxon to try to add the taxon.
> I can do it without a problem in Specify 6 and I can do it in other databases, just not theirs in 7.

**Comment by yvonneekanim** [comment]
I'm able to add taxa via the forms past the 20th level without issues
