### ISSUE TITLE
Schema records for new Geo fields are not present

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#5339]
We have a field in `CollectionObjectGroup` named `childCojos`, but it does not have a schema record created for it. Others are presumably affected as well.

<img width="1034" alt="image" src="https://github.com/user-attachments/assets/03d07cd1-b18b-4c2d-9b28-cc0e8287511d">

<img width="868" alt="image" src="https://github.com/user-attachments/assets/9fe6cec3-aa14-4a25-a2c6-81048dc3faf2">

The `0002_geo` migration creates the schema records for the initial migration, but when we added this field migrations were not changed from what I understand.

**Comment by sharadsw** [comment]
Added in #5257
