### ISSUE TITLE
Setting active related express search sometimes doesn't work.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#535]
The schema for the `ExpressSearchConfig` appresource appears to have changed or is variable. It is unclear to me why sometimes it has one form and sometimes the other. Of the following snippets, the first one works with Specify 7 but the second does not:
```xml
    <relatedquery isactive="true">
      <id>36</id>
      <displayOrder>21</displayOrder>
    </relatedquery>
```

```xml
    <relatedquery>
      <id>12</id>
      <displayOrder>17</displayOrder>
      <isActive>true</isActive>
    </relatedquery>
```

**Comment by yvonneekanim** [comment]
Should this be added to the global prefs? What should happen?

**Comment by benanhalt** [comment]
I'm not sure there is a good way to test this one. Sometimes Specify 6 saves the express search one way and sometimes the other and I have no idea why or how to control it. This is just a bug I discovered. I can verify that the fix worked for what I found. So if the express search still seems to work okay for you, then I probably didn't break anything and we can leave it at that.
