### ISSUE TITLE
COG & CO form's Add and Clone buttons cause crash upon save

### ISSUE THREAD

**Issue by alesan99** [specify/specify7#5373]
**Describe the bug**
When you create a collectionObjectGroup and click the add or clone buttons the new record will result in a crash upon saving.

The Clone button will also fail to carry over the isPrimary child property, though the cloning functionality probably shouldn't work with COGs.

**To Reproduce**

1. Use the COG viewdefs: https://github.com/specify/specify7/pull/5275
2. Create a new COG
3. Save
4. Click Add or Clone
5. Save

**Expected behavior**

The add button should save successfully.

The Clone button should probably be disabled or at least clear the children.

**Screenshots**

https://github.com/user-attachments/assets/e708a0db-ce15-4921-9de5-4c00dee22369

**Crash Report**

[Specify 7 Crash Report - 2024-11-05T16_22_08.713Z.txt](https://github.com/user-attachments/files/17635621/Specify.7.Crash.Report.-.2024-11-05T16_22_08.713Z.txt)

Please fill out the following information manually:
- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: e3cd0bc46ba542ce169287e74d7d54c83ae1e3f5 (7.9.8 production)
- Database Name: kubirds82523
- User Name: spadmin
- URL: [https://kubirds82523-issue-5246.test.specifysystems.org/specify/view/collectionobjectgroup/9470/](https://kubirds82523-issue-5246.test.specifysystems.org/specify/view/collectionobjectgroup/9470/)

**Comment by CarolineDenis** [comment]
NOTES: 
Related to createdByAgent missing field? 

error: bad foreign key field in data Request
