### ISSUE TITLE
Support audit log queries

### ISSUE THREAD

**Issue by timo11** [specify/specify7#538]
Audit log information should be accessible in the Query builder. (see #498)

**Comment by timo11** [comment]
Strange things are showing up in the ParentRecordId column. Not sure yet if the logged values are incorrect or if there is a problem displaying them....

**Comment by timo11** [comment]
How AuditLog Queries Differ from Standard Queries:

1. They are only available to manager level users.

2. A Format check box appears next to the Distinct check box. 
When this box is checked, dataobject formatters are used to display the RecordId and ParentId fields as well as OldValue and NewValue when they contain foreign keys. Checking Format also causes user customized titles to be displayed in the TableNum, ParentTableNum, and FieldName fields. When Format is not checked, RecordID, ParentID, and foreign keys in OldValue and NewValue are displayed as numbers; also, TableNum, ParenTableNum, and FieldName will be displayed with actual object names (not the table numbers for TableNum and ParentTableNum). 

If format is checked, when a formatter for a record is not defined, or the record has been deleted,  values will be displayed as TableName:{RecordID}, for example "CollectionObject:{123456}".

Formating will not be used for OldValue and NewValue if FieldName is not selected (and shown) in the query, even when Format is checked.

**Comment by yvonneekanim** [comment]
When 'format' is checked, the query results only display some of the records.

Image of when format is not checked:
![unchecked](https://user-images.githubusercontent.com/28809154/76566335-8cd86100-647a-11ea-9bad-8527c4d60cac.png)

When format is checked:
![checked](https://user-images.githubusercontent.com/28809154/76566359-99f55000-647a-11ea-825d-a28a21adb057.png)

**Comment by timo11** [comment]
yvonneekanim I can't duplicate this problem. Can you put the db on specify6 please?

**Comment by yvonneekanim** [comment]
@timo11 I put the database in your directory. The db name is pripaleo

**Comment by yvonneekanim** [comment]
I just noticed it happens only when there is a filter added to any of the fields

**Comment by yvonneekanim** [comment]
I'm still experiencing the issue in rsa db on the test server. I now happens a bit further down the query results and repeats the last few rows infinitely

![Screenshot (68)](https://user-images.githubusercontent.com/28809154/77007847-f4872400-6932-11ea-82d6-99ae0bddb4b0.png)

**Comment by timo11** [comment]
@yvonneekanim what is the test server url? Is it possible to download dbs from the server?

**Comment by yvonneekanim** [comment]
Yes you can @timo11. http://biwebdbtest.nhm.ku.edu/

**Comment by timo11** [comment]
This is fixed, but the rsa database, and any other db for which recs were deleted since the fix to truncate log entries was done will still have the problem unless query conditions that newval and oldval are not equal to None is added.
