### ISSUE TITLE
Negation setting not cleared with operator in Query builder

### ISSUE THREAD

**Issue by timo11** [specify/specify7#539]
If there is negated operator on a field, when the operator is cleared, the negation remains in effect and even though the operator is "any", a != '' condition is added for the field, generating incorrect results.

Also if you subsequently change the operator from any to something else, negation will be selected automatically.

**Comment by yvonneekanim** [comment]
Negation only clears when switching to 'any' and remains clear when switching from 'any' to other operators.

**Comment by maxxxxxdlp** [comment]
This seems to be fixed and working like expected
