### ISSUE TITLE
Remove log entries older than a user specified max age

### ISSUE THREAD

**Issue by timo11** [specify/specify7#540]
Audit log items older than the user-specified AUDIT_LIFESPAN_MONTHS global preference are deleted the first time an audit is recorded during a specify session, and every 80 minutes or so while the session is open.

**Comment by timo11** [comment]
Audit log items older than the user-specified AUDIT_LIFESPAN_MONTHS global preference are deleted the first time an audit is recorded after the instance server is started, and then when audits are recorded and more than 15 minutes have elapsed since the last purge.

Note: Changes to logging prefs won't be processed until the next purge.

**Comment by timo11** [comment]
Also: It's possible and likely that when a huge number of log records need to be purged, the save/edit/delete that triggered the purge will take a long long time.

**Comment by yvonneekanim** [comment]
I can't get it to work in databases where I have to manually add the pref. Some databases already had the pref and others didn't.

**Comment by timo11** [comment]
It worked for me.
My database had remote prefs and global prefs in the 'Global' category. Are you sure you added the pref to global prefs?
Did you wait 15 minutes?
Did you trigger an audit by saving a change?
Did you verify that the auditing.do_audits pref is true or not present? (If it's not there auditing will be on by default.)

**Comment by maxxxxxdlp** [comment]
It worked for me in `TestBiology8`. I did change the prefs
And it did work with `TestBiology9` (with default prefs)
Did not delete anything for `Temp` (KU Entro) (default settings)
