### ISSUE TITLE
Return Loan is not working

### ISSUE THREAD

**Issue by timo11** [specify/specify7#541]
Choose Interactions - Return Loan and enter a loan a number, and it blows up -- "bundles[Symbol.iterator] is not a function" -- at *** in snippet from stringlocalization.js below.  
Happens on master and summer19 branches.

    localize: function localize(s, fallback) {
        var _iteratorNormalCompletion = true;
        var _didIteratorError = false;
        var _iteratorError = undefined;

        try {
 ***           for (var _iterator = bundles[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
                var bundle = _step.value;

                var localized = props.getProperty(bundle, s);
                if (localized) return localized;
            }

**Comment by timo11** [comment]
"fixed" by rewriting localization method in std js w/o extensions, seems to have been a compilation issue?

**Comment by yvonneekanim** [comment]
I'm testing this on the current develop branch and when I click on return loan and enter a loan number, nothing happens

**Comment by maxxxxxdlp** [comment]
This is fixed, but, like @yvonneekanim mentioned, there is no feedback provided (#586)
