### ISSUE TITLE
Add Records from DB to an existing Record Set

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#544]
Requested by MN dragonfly +many
Dragonfly noted that after they have saved a record, the only way to add a new record is to go to data, then select the table from the list.  They asked if there could be a button allowing them to add a new record from the record they are currently on.  In 6, you have a green plus at the top of the window to add a new record.

**Comment by benanhalt** [comment]
Maybe add a "new" button and allow configuration of carry-forward.

**Comment by maxxxxxdlp** [comment]
Turned "Save and Add Another" button into "Add Another". It is available for any record, assuming there are no unsaved changes.

If you want, I can instead make this button have two roles: save the record if needed, and create new record, but that might be confusing to the user.
