### ISSUE TITLE
Set isPrimary when at least one CO is in a consolidate COG

### ISSUE THREAD

**Issue by CarolineDenis** [specify/specify7#5440]
Only for consolidated COG: 

- Set first added CO to isPrimary 
- When deleting that CO set isPrimary to the second CO if present 
- Be sure this works in any condition, COG is saved, CO is added, CO is added by QB etc etc

**Comment by CarolineDenis** [comment]
NOTES: 
In cojo_rules 
have a presave COG and check if consolidate if consolidate then check all cojo.isprimary and if nothing set the first one to true

**Comment by sharadsw** [comment]
Closing in favor of setting a save blocker instead (#5427)
