### ISSUE TITLE
Default form for TectonicUnit uses Taxon QCB

### ISSUE THREAD

**Issue by alesan99** [specify/specify7#5446]
**Describe the bug**
The default form for TectonicUnit data entry lets me select Taxon as the accepted Tectonic Unit

**To Reproduce**

1. Use the most up-to-date default geo forms
2. Go to data entry for tectonicUnit
3. Try to enter an Accepted Tectonic Unit into the QCB

**Expected behavior**
Should use a TectonicUnit QCB

**Screenshots**

https://github.com/user-attachments/assets/e4fbb97c-029e-4b67-ad53-7bfd025786fd

https://github.com/user-attachments/assets/2460ba77-894d-440b-a8f4-becefc24bcab

Please fill out the following information manually:
- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: 6b071d7ce274d5f85d17974e4c8e368b96727f3f
- Database Name: chadrontest_2024_08_15 (local copy)
- Collection name: Paleo
- User Name: testuser

**Comment by CarolineDenis** [comment]
@grantfitzsimmons , 
Since we will change xml files in this pr could we add the changes for the parentCog as well? (On CO & COG forms)

**Comment by pashiav** [comment]
Found duplicate options when searching in the text field of accepted Tectonic Unit.


<img width="1270" alt="Screenshot 2024-12-09 at 9 34 13 AM" src="https://github.com/user-attachments/assets/a54cdfae-1b6b-47ff-a7b6-251ee1dacb3e">
<img width="1152" alt="Screenshot 2024-12-09 at 9 34 26 AM" src="https://github.com/user-attachments/assets/b14d438b-e709-413c-898e-faa065e7eb69">

**Comment by grantfitzsimmons** [comment]
1. It's crazy that Specify didn't handle this case and looked at the Taxon tree 😂 
2. @pashiav Can you try this again on this PR?

https://github.com/specify/specify7/pull/5448

**Comment by pashiav** [comment]
Duplicates are fixed in #5448!
