### ISSUE TITLE
Adding COG to itself should not throw an error 

### ISSUE THREAD

**Issue by emenslin** [specify/specify7#5450]
**Describe the bug**
If you add a COG to itself using the children subview it throws an error and you lose any other changes that were made. 

**To Reproduce**

1. Go to collection object group 
2. Fill out name and type
3. Save
4. Use search/query to add COG to itself 
5. Try to save 
6. See error 

**Expected behavior**
There should be a save blocker or anything other than a full error that forces the user to leave the form. It is very easy to accidentally click the wrong COG and if a user was selecting multiple at once and accidentally selected the COG their on they would lose everything. 

**Screenshots**

https://github.com/user-attachments/assets/62af25a7-ff46-49c5-ae9b-b0f80138dc32

**Crash Report**

[Specify 7 Crash Report - 2024-12-05T21_52_41.376Z.txt](https://github.com/user-attachments/files/18030116/Specify.7.Crash.Report.-.2024-12-05T21_52_41.376Z.txt)

Please fill out the following information manually:
- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: production
- Database Name: calvertmarinemuseum20241114
- Collection name: Invertebrates
- User Name: spadmin
- URL: https://calvertmarinemuseum20241114-production.test.specifysystems.org/specify/

**Comment by grantfitzsimmons** [comment]
At a minimum, this just needs to be caught and block saving. The tooltip should tell the user exactly how to fix it (e.g. "Please remove the COG from itself").

A better solution would be to exclude the COG from the search results _or_ from the set of records sent to the backend for creating the children.
