### ISSUE TITLE
Record sets can't be created using a subset of query results

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#546]
Willem reported users complaining that they could not create record sets that contain some of the records returned in a query.  It has to be all of the records.

**Comment by grantfitzsimmons** [comment]
I experienced this exact issue today. Since the WB cannot currently support 'and' statements (ex. CO # between 100 and 101, 150 and 151), this should definitely get looked into.

**Comment by benritchie** [comment]
Agree, this is a really useful feature of 6, that's missing from 7.

**Comment by maxxxxxdlp** [comment]
@benritchie This will be available in next release
