### ISSUE TITLE
Removing a CO from a COG does not remove it from the CO form until a page reload

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#5460]
> I think there is a usability concern here with the requirement for users to reload the page each time they remove a COG. I spoke with @CarolineDenis about this, and we understand that this is the only place in the application that functions this way. Other "join" tables are similarly affected, but this one is likely to be noticed by users due to the fundamental workflow likely brushing up against it. 
> 
> https://github.com/user-attachments/assets/04fd5c35-118b-4b8d-9654-7b79a0c7cbef
> 
> 
> >PS: it is not possible to delete a parent on the child form
> 
> This leads to an error that will be seen to the user if they attempt this deletion:
>
> ```
> IntegrityError at /api/specify/collectionobjectgroup/7/ (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`geo`.`collectionobject`, CONSTRAINT `collectionobject_CoParentCogID_952ffbf8_fk_collectio` FOREIGN KEY (`CoParentCogID`) REFERENCES `collectionobjectgroup` (`collectionobjectgroupid`))') 
> ```
> 
> Is this something that can be handled by save blockers? If this is outside the scope of this PR, we need to open another issue for this. I don't believe this is outside of a usual workflow if one were to extensively use COGs.

Split from https://github.com/specify/specify7/pull/5433#pullrequestreview-2496080001

**Comment by acwhite211** [comment]
It seems that there is no error gets thrown anymore.  There is still an issue with parentCog still being present in the CO's parentCog field on the UI after the user uses the "Edit Pencil" to remove the childCO from the COG in the subview.  The field does get updated if you refresh the page.  So, we just need to edit the front-end logic to refresh and update the Cojo section of the CO form.

**Comment by CarolineDenis** [comment]
close in favor of: 
https://github.com/specify/specify7/issues/5508
