### ISSUE TITLE
Changing the COG parent of a CO does not add the CO to the new parent's list of children.

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#5462]
> If you add a CO to a COG, it appears in the list of children _most of the time_. If you change the COG parent of that CO, it does not appear in the list of children when you open the record in a dialog until you refresh the page.
> 
> https://github.com/user-attachments/assets/46d60920-fe11-46fe-bbdd-7379a1b898aa

Split from https://github.com/specify/specify7/pull/5433#pullrequestreview-2496080001

**Steps to Recreate:**
1. Add a CO to a COG using the COG Join subview
2. Save the record
3. Change the COG parent of the CO via the COG Join subview
4. Open the COG parent record using the pencil in the query combo box
5. See that the CO is not listed as a child

Vivaldi, macOS, `issue-5428`

**Comment by CarolineDenis** [comment]
Close in favor of 
https://github.com/specify/specify7/issues/5508
