### ISSUE TITLE
When adding a new taxon tree no default information is filled out 

### ISSUE THREAD

**Issue by emenslin** [specify/specify7#5467]
**Describe the bug**
If you try to add a new taxon tree the name for the tree is blank along with all the ranks in the tree. 

**To Reproduce**

1. Go to taxon tree
2. Add new tree 
3. Select any tree 
4. See name is blank 
5. Look at ranks
6. See those are blank 

**Expected behavior**
All the information should be filled out 

**Screenshots**

https://github.com/user-attachments/assets/8194096c-9aba-4fa8-9362-d68efc3191b9

Please fill out the following information manually:
- OS: Windows 11
- Browser: Chrome 
- Specify 7 Version: production 
- Database Name: ojdmnh
- Collection name: fossil invertebrates 
- User Name: spadmin
- URL: https://ojsmnh20241003wb-production.test.specifysystems.org/specify/tree/taxon/?conformation=%7E-

**Comment by CarolineDenis** [comment]
NOTES: 
Happens since: https://github.com/specify/specify7/pull/5431/
