### ISSUE TITLE
Cannot add Record Set items to a COG

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#5486]
**Describe the bug**

**To Reproduce**

1. Go to https://geo-swiss.specifycloud.org/specify/view/collectionobjectgroup/4/?recordsetid=16 ([access credentials here](https://docs.google.com/document/d/1l1cAKXyWBPQa9UooVwrioPbPJmzZMp1rAoeQfSVJh4o/edit?usp=sharing))
2. Search for CO children
3. Click on **Record Set**
4. Select a CO record set
5. See that no children are added, despite not being in any other COGs

https://github.com/user-attachments/assets/24d86fed-8171-41fc-bdbe-87b8b9114d3b

**Crash Report**

[Specify 7 System Information - 2024-12-18T16_54_48.538Z.txt](https://github.com/user-attachments/files/18186359/Specify.7.System.Information.-.2024-12-18T16_54_48.538Z.txt)

Version: https://github.com/specify/specify7/commit/b69dac305cd93466a93b2dea773174df5f14524f

macOS, Vivaldi

**Comment by acwhite211** [comment]
This seems to be a duplicate issue of this https://github.com/specify/specify7/issues/5481

**Comment by grantfitzsimmons** [comment]
It could be caused by the same underlying issue, but it results in a different problem. Both can be resolved by the same PR if that addresses this issue.

**Comment by CarolineDenis** [comment]
NOTES: 
- missing onAdd in <SearchDialog/> props in COJODialog.tsx
-
