### ISSUE TITLE
Add a tool to populate trees

### ISSUE THREAD

**Issue by CarolineDenis** [specify/specify7#5492]
tbd

**Comment by grantfitzsimmons** [comment]
This was part of the requirements for the "Add Tree" utility initially, but it was dismissed some point during development of that tool and oddly when we finished the initial GeoSpecify schema.

From #4976:

> Component of #4833
> 
> We must be able to use a set of defaults for the ranks and configuration of a new tree.
> Our default trees are available in `xlsx` files on our site:
> https://files.specifysoftware.org/taxonfiles/
> 
> These should be used as a basis if desired when adding a new tree


> ```xml
> <vector>
>     <file discipline="fish"         title="Ichthyology" coverage="" file="col2008_fishes.xls" src="Catalog of Life 2008" size="11228672">
>         <description>FishBase: 533 families; 4883 genera; 8759 species.</description>
>     </file>
>     <file discipline="herpetology"  title="Herpetology" coverage="" file="col2008_herps.xls" src="Catalog of Life 2008" size="6911488">
>         <description>Amphibs: 48 families; 449 genera; 5752 species.  Reptiles: 62 families; 1072 genera; 8759 species.</description>
>     </file>
>     <file discipline="bird"         title="Ornithology" coverage="" file="col2008_aves.xls" src="Catalog of Life 2008" size="7839232">
>         <description>178 families; 2123 genera; 9913 species.</description>
>     </file>
>     <file discipline="mammal"       title="Mammalogy"   coverage="" file="col2008_mammalia.xls" src="Catalog of Life 2008" size="2727424">
>         <description>146 families; 1151 genera; 4832 species.</description>
>     </file>
>     <file discipline="insect"       title="Entomology"  coverage="" file="col2008_orthoptera.xls" src="Catalog of Life 2008" size="9502720">
>         <description>Order Orthoptera only: 40 families; 4320 genera; 23042 species.</description>
>     </file>
>     <file discipline="botany"       title="Botany"      coverage="" file="col2008_poales.xls" src="Catalog of Life 2008" size="4817408">
>         <description>Order Poales only: 16 families; 558 genera; 13246 species.</description>
>     </file>
>     <file discipline="invertebrate" title="Invertebrate Zoology" coverage="" file="col2008_inverts.xls" src="Catalog of Life 2008" size="8188416">
>         <description>Phyla Mollusca, Cnidaria and Echinodermata only: 826 families; 4092 genera; 22584 species.</description>
>     </file>
> </vector>
> ```

**Comment by grantfitzsimmons** [comment]
Closing this in favor of https://github.com/specify/specify7/issues/4976 since that issue represents the same idea but it was closed incorrectly
