### ISSUE TITLE
Null values in partial dates are being filled with '1'

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify7#552]
Reported by Shell Museum:

When a query that includes partial date fields is ran, the values that should be null are being populated with "1". E.g a partial date with year only precision is shown as 1/1/2019 instead of just 2019.

This also affects reports and data exports.

**Comment by benanhalt** [comment]
I think this was fixed by Tim in b37bb1f848e69fb8064d6bc70f816308b3fa6056 which went out in v7.5.0.
