### ISSUE TITLE
Support Default Date on Collection Object form

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify7#554]
When default date is set to "today" in the form, Specify 7 ignores it and leaves it as blank

**Comment by maxxxxxdlp** [comment]
Fixed in next release
Can also set default value to a relative date (i.e `today + 2 months`)
Documentation: https://github.com/specify/specify7/wiki/Form-System#:~:text=For%20date%20fields%2C%20can%20set%20this%20to%20today%20to
