### ISSUE TITLE
Sp7 needs to display blank form after saving

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify7#556]
Minnesota Dragonfly reported this issue:

When save or save and add another are selected after filling out the form, the new page that loads still has details from the last record that was saved. This seems to happen for collections with Catalog Numbers that are string fields

**Comment by maxxxxxdlp** [comment]
Seems related to https://github.com/specify/specify7/issues/124

**Comment by maxxxxxdlp** [comment]
Fixed in 7.7 by:
Removing "Save and Add Another" button
Adding an "Add Another" button that opens a blank form
Adding a "Clone" button that opens new form with carry forward
