### ISSUE TITLE
In operator in Query requires padded catalog number when using Catalog Number Numeric format

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#560]
When querying on a series of numbers in catalog number, using the In operator, you must enter the entire string, not what appears as the number.  For example, catalog number 1 appears in the forms as 1, but is recorded as 000000001 in MySQL.  When querying, you need to enter the full number or it doesn't acknowledge it.  This is inconsistent with Specify 6

**Comment by maxxxxxdlp** [comment]
Fixed in dfd1e783
