### ISSUE TITLE
Create Record Set from Tree query results

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify7#561]
Reported by Florida fish and wildlife:
Currently, if you create a query from the taxon tree (right click, query) the button to create a record set from those results is not available

![image001 (1)](https://user-images.githubusercontent.com/28809154/71695913-2bf52400-2d79-11ea-8035-ff717bd79825.jpg)

**Comment by maxxxxxdlp** [comment]
Not sure why this wasn't allowed, but this works in the new query builder
