### ISSUE TITLE
Possible spurious "Unsaved form" message after save.

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#570]
When pressing the `Save` button, I get a message that changes have not been saved, even though my changes are saved after I press the `Leave` button

I would suppose that that event is initialized by the browser and specify should learn to ignore it whenever it is not needed

![Screenshot from 2020-01-17 09-56-45](https://user-images.githubusercontent.com/40512816/72634591-b27c3a80-390f-11ea-9fad-fd3a727807b2.png)

**Comment by maxxxxxdlp** [comment]
This happens for almost every form

**Comment by benanhalt** [comment]
What web browser are you using?

**Comment by maxxxxxdlp** [comment]
Google Chrome 80

**Comment by benanhalt** [comment]
This isn't happening for me. Can you check that it happens on biwebdbtest.nhm.ku.edu and on other systems?

**Comment by maxxxxxdlp** [comment]
Get the following error message after restoring that database on the server (`TestBiology`)
![Screenshot from 2020-01-21 15-14-46](https://user-images.githubusercontent.com/40512816/72851570-d9fd3b00-3c60-11ea-973f-0c33e04e6904.png)

And this is the error with `Ku Entro`:
![Screenshot from 2020-01-21 15-17-09](https://user-images.githubusercontent.com/40512816/72851678-26487b00-3c61-11ea-8c9d-0e5a1851c551.png)
I think it is connected to some table not existing

**Comment by maxxxxxdlp** [comment]
This warning message does not happen anymore (after the system reboot)
Though, it may start again in the future. I have no idea what was the trigger for it

**Comment by maxxxxxdlp** [comment]
Seems like the related code is located in `/specifyweb/frontend/js_src/lib/savebutton.js` on line `43`

**Comment by maxxxxxdlp** [comment]
Happened on a test server [http://db2.biwebdbtest.nhm.ku.edu/](http://db2.biwebdbtest.nhm.ku.edu/]) in the `TestBiology` database

<img width="583" alt="Screen Shot 2020-02-11 at 10 59 39 AM" src="https://user-images.githubusercontent.com/40512816/74259557-b35d7d80-4cbd-11ea-8a9d-67d5f6b5735e.png">

I am using Chrome Beta 80 on the client-side

Seems like it does not happen every time. Will try to pinpoint the trigger
Seems that it can happen for every form, then it is not related to a one specific field

**Comment by maxxxxxdlp** [comment]
Happened in Safari (stable) with macOS 10.15.5 (stable) in python3 when adding new accession
![Screen Shot 2020-06-25 at 1 46 49 PM](https://user-images.githubusercontent.com/40512816/85705943-53cda080-b6a7-11ea-8db0-7603808b5a92.png)

Here are the last few lines from the log:
![Screen Shot 2020-06-25 at 1 48 52 PM](https://user-images.githubusercontent.com/40512816/85706229-9becc300-b6a7-11ea-8c96-0723b1c8ffcf.png)

Seems like this bug may be exclusive to Interations

**Comment by maxxxxxdlp** [comment]
Happened in Firefox 78 (Beta)

<img width="1440" alt="Screen Shot 2020-06-29 at 5 47 04 PM" src="https://user-images.githubusercontent.com/40512816/86020403-7df7c900-b9ed-11ea-8b36-8e1332fbde58.png">

**Comment by maxxxxxdlp** [comment]
<img width="1440" alt="Screen Shot 2020-06-29 at 5 52 58 PM" src="https://user-images.githubusercontent.com/40512816/86021094-55240380-b9ee-11ea-89a5-af1dd6b162c1.png">

**Comment by maxxxxxdlp** [comment]
Also, I received the same message on the `Storage Tree`. Is this message supposed to be shown for trees at all?

**Comment by maxxxxxdlp** [comment]
Also happened on this page after pressing the `Done` button and specifying the name for a new Data Set

![Screen Shot 2020-07-03 at 8 46 43 PM](https://user-images.githubusercontent.com/40512816/86489906-52494b80-bd2b-11ea-97e0-2a96af2a57c3.png)

**Comment by maxxxxxdlp** [comment]
Happened again on the `Gift` form

![Screen Shot 2021-07-14 at 12 56 53 AM](https://user-images.githubusercontent.com/40512816/125530936-2f38d144-91a3-40ae-8e6b-637bf2e826db.png)

**Comment by maxxxxxdlp** [comment]
Happened again when I edited an accession from the CO form
After saving all changes, the unloadProtect stack had 7 elements, "This form has not been saved.", all linked to a SaveButton and the Accession resource

**Comment by maxxxxxdlp** [comment]
Happened again a bunch of times during tree editing (creating and moving nodes)
