### ISSUE TITLE
Autocomplete stops working in query combobox.

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#571]
There is autocomplete available for some fields

![Screenshot from 2020-01-17 10-01-38](https://user-images.githubusercontent.com/40512816/72634932-7e554980-3910-11ea-8118-58b73c89c253.png)

After it was shown once, if the user deletes the content from the field without selecting any proposed value and the field loses focus, autocomplete does not work for that field anymore

![Screenshot from 2020-01-17 10-02-08](https://user-images.githubusercontent.com/40512816/72634933-7e554980-3910-11ea-8f9b-73f105468d71.png)

**Comment by benanhalt** [comment]
I can't reproduce this behavior. In fact, for required fields it is impossible to delete a value from the querycbx once one has been selected... But I can't get it to happen for non required fields either.

**Comment by maxxxxxdlp** [comment]
Here is the video of actions that lead to this bug: [https://youtu.be/J2tewxGhybQ](https://youtu.be/J2tewxGhybQ)

Fixes after a page restart
The video was recorded on a local server with a Vertebrate Paleontology database
I am also able to reproduce this on [http://db1.biwebdbtest.nhm.ku.edu](http://db1.biwebdbtest.nhm.ku.edu)

**Comment by benanhalt** [comment]
I'm only able to get it to occur through the following exact steps:

1. Enter a single character in the cbx that results in a list of completions.
2. Click outside the box to abort the autocomplete. (The box clears itself.)
3. Enter the exact same single character. The completions list fails to appear.

Entering anything in the cbx other than the exact character from step one returns the cbx to normal behavior.

Unless this can be shown to happen in more common circumstances, I'm going to recommend it be backlogged as low priority.

**Comment by maxxxxxdlp** [comment]
Same problem with picklists in addition to #684

**Comment by maxxxxxdlp** [comment]
Happened here, even though I have more that one character

![Screen Shot 2020-07-07 at 11 07 23 PM](https://user-images.githubusercontent.com/40512816/86836776-9c03a000-c063-11ea-972e-024634b0ec0f.png)

**Comment by maxxxxxdlp** [comment]
Seems to happen only if there was a single character in the field when autocomplete was shown and then the field lost focus.
As a workaround, typing two characters into the field and then erasing the extra one fixes the issue.
Seems to be a bug with the current version of jQuery. Fixed in newer jQuery versions
