### ISSUE TITLE
Make `Add` links focusable

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#573]
Unlike Specify 6, Specify 7 does not provide a way to focus on the `Add` links and add new elements using keyboard alone

![Screenshot from 2020-01-17 10-11-39](https://user-images.githubusercontent.com/40512816/72635496-cd4fae80-3911-11ea-8dc3-696c8d1f744f.png)

I would imagine it would not be hard to modify the styles to make ilinks be focusable

**Comment by maxxxxxdlp** [comment]
Even after that commit links do not seem to have the `href` attribute

I modified some file and hopefully, the attribute will be present now

<img width="402" alt="Screen Shot 2020-03-03 at 9 30 22 AM" src="https://user-images.githubusercontent.com/40512816/75791045-9d2d6500-5d31-11ea-9dd6-d53a439917f3.png">

**Comment by maxxxxxdlp** [comment]
Even though the links do have the focus effect when I manually add `href="#"` to them, pressing `Spacebar` or `Enter` while focused does not trigger the click event

**Comment by maxxxxxdlp** [comment]
Still does not work

**Comment by benanhalt** [comment]
This is working for me now. I think it just didn't get updated to the test server, before.

**Comment by maxxxxxdlp** [comment]
Works, but only for the `Add` and `Remove` links. Can you also implement it for other buttons? (`edit`, `+`, `search`)

**Comment by benanhalt** [comment]
It should be there. You may need to clear the cache in your browser.

**Comment by maxxxxxdlp** [comment]
You were right. `Ctrl+F5` solved the issue
