### ISSUE TITLE
Make tree nodes show the number of children

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#574]
Currently, all of the tree nodes display `(0)` regardless of the amount of children they have

![Screenshot from 2020-01-17 10-16-35](https://user-images.githubusercontent.com/40512816/72635768-75fe0e00-3912-11ea-8cf9-4077d752bf2f.png)

**Comment by benanhalt** [comment]
That is the number of collection objects determined to the taxon, not the number of children.

**Comment by maxxxxxdlp** [comment]
Seems to work like intended when I add CO to localities that belong to the geography and children

![Screenshot from 2020-02-13 11-12-01](https://user-images.githubusercontent.com/40512816/74459894-ae313780-4e51-11ea-8874-8059e75729b7.png)
