### ISSUE TITLE
Problems with python-ldap

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#577]
I receive a lot of errors when trying to `make all`

Partial console output:
```
  Building wheel for python-ldap (setup.py) ... error
  ERROR: Command errored out with exit status 1:
```
![Screenshot from 2020-01-17 12-16-07](https://user-images.githubusercontent.com/40512816/72643316-3f7cbf00-3923-11ea-90fd-7d2f1ba36824.png)
![Screenshot from 2020-01-17 12-16-26](https://user-images.githubusercontent.com/40512816/72643315-3f7cbf00-3923-11ea-8b57-7510ac6b8654.png)
![Screenshot from 2020-01-17 12-16-35](https://user-images.githubusercontent.com/40512816/72643314-3f7cbf00-3923-11ea-926c-984507d0e9fe.png)

Full console output:
[output.zip](https://github.com/specify/specify7/files/4078898/output.zip)

I used the following command to fix the issue (one of those packages must have been required):
```
sudo apt-get install build-essential python3-dev libldap2-dev libsasl2-dev slapd ldap-utils lcov valgrind
```

Also, I am using MariaDB with Ubuntu 19.10. This issue did not appear on the similar VM with MySQL installed

**Comment by benanhalt** [comment]
This was added to the README in the master branch in 83c9fd172f537cccbb74b633aac417bba8a32196
