### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#580]
This it the message users currently get when there is an exception in Specify 7

![Screenshot from 2020-01-17 12-49-10](https://user-images.githubusercontent.com/40512816/72645200-e2373c80-3927-11ea-8fc1-18ef266a6c40.png)

Since exceptions happen so oftenly, it would be wise to show stack trace and give user ability to copy the debug information like they can in Specify 6. This will make it easier for developers to diagnose and traceback the issue and would give users without server access ability to report errors

**Comment by benanhalt** [comment]
It is supposed to include the exception in that dialog if the server is running in debug mode. It looks like that has stopped working (possibly because Django changed the exception formatting?)
