### ISSUE TITLE
Transfer information to the next form when adding records using query combobox.

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#582]
![Screenshot from 2020-01-20 07-41-49](https://user-images.githubusercontent.com/40512816/72739351-59531780-3b58-11ea-9d8e-aff5af491433.png)

If the user specifies any information in a field and then presses the `+` (Add) button, a new form will be opened, yet the information user has entered will be deleted

This bug is fixed in Specify 6. For example, if there is text in the `Agent` field, it gets transferred into `Last Name` field on a new form

This applies to all fields that have `+` (Add) button near them

**Comment by maxxxxxdlp** [comment]
Same problem with `Search` window

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/167701865-4b7433ef-8f9b-4850-a11a-10570380aef5.png)

@maxxxxxdlp Is this implemented?

**Comment by maxxxxxdlp** [comment]
Looks like it was implemented to transfer the value only when the "Add" entry in the suggestions list was selected.
I extended it now to also work when the add icon is pressed

For future reference, it puts the pending value into the first non-relationship field from the list of typeSearch searchFields.

**Comment by grantfitzsimmons** [comment]
![msedge_fiigN5MYWe](https://user-images.githubusercontent.com/37256050/167856026-64839bb4-db53-4247-80a8-993a12dae8ad.gif)

Does not seem to be working either way at the moment (Security Panel)

**Comment by maxxxxxdlp** [comment]
Works fine for me:

https://user-images.githubusercontent.com/40512816/167989192-9e10af13-8652-42eb-b229-2c87ba2b7cab.mov

Maybe the server hasn't yet updated when you tried it. Can you test this again?
