### ISSUE TITLE
No feedback on `Loan Return`

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#586]
![Screenshot from 2020-01-20 08-59-15](https://user-images.githubusercontent.com/40512816/72744824-29f5d800-3b63-11ea-9a34-516572b1353f.png)

User receives no error and success messages when returning a loan by its number
This means that the user can specify a non existing Loan Number (make a typo) and not even know that the Loan was not returned

**Comment by maxxxxxdlp** [comment]
Also, Specify 7 uses `Loan Return` and `Return Loan` from time to time. There should be the same name used in every case

![Screenshot from 2020-01-20 09-01-52](https://user-images.githubusercontent.com/40512816/72744985-85c06100-3b63-11ea-856e-642a4ef66531.png)

**Comment by benanhalt** [comment]
I get this dialog when returning loans. If I put in an incorrect loan number, it says 0 preparations returned.

![loan-return](https://user-images.githubusercontent.com/287254/74373534-47087a00-4da2-11ea-91a2-e8f8c495d2b4.png)

**Comment by maxxxxxdlp** [comment]
Does not happen when tested on biwebdbtest.nhm.ku.edu
