### ISSUE TITLE
query fields remember their value when the operation is changed even though the input field is cleared

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#59]
Create a taxon table query and add the field 'species = foobar'. Click on '=' to start selecting a different operation, but choose '=' again. The text field will now be empty, but running the query will filter to 'foobar' species.

**Comment by benanhalt** [comment]
Actually this could be a feature, if the text field would reflect the remembered value.

**Comment by benanhalt** [comment]
this was fixed in 7d251e5b06c1c889fab69f725432497c7446ac2f

**Comment by drew-wallace** [comment]
verified in aeae848fde4eb5ad3f477fef7f7d47a65605821a

It no longer "remembers" my catalog number from IN operator after selecting a
new operator.
