### ISSUE TITLE
Specify freezes for extended time when creating loan or gift from record set.

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#591]
Specify freezes when the user selects a record set for a loan

![Screenshot from 2020-01-21 07-07-57](https://user-images.githubusercontent.com/40512816/72816816-933a2180-3c1d-11ea-9de3-442553f04a0c.png)

This can last for about 20 seconds. At this point there is no output in the console/terminal and window can not be closed. There absolutely must be a loading message that will tell user that the program is not frozen, but is processing the requested action

**Comment by maxxxxxdlp** [comment]
Same problem with gifts

**Comment by benanhalt** [comment]
Does this depend on the size of the record set?

**Comment by maxxxxxdlp** [comment]
Tested with a Record Set that has 50 CO. No lag in this case

Tried with a Record Set that has 9125 CO. Same issue as disciplined above. Except this time Google Chrome even showed a `this page is unresponsive` prompt message. Resolves automatically if uses just waits. But still, this is certainly not the way any web application should work
