### ISSUE TITLE
Use the same date format everywhere

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#596]
Specify 7 requires date to be inputed in one style in a query builder, yet outputs the result in a different format

![Screenshot from 2020-01-28 10-43-25](https://user-images.githubusercontent.com/40512816/73294616-0bbf5600-41bb-11ea-8b76-2970213fafb0.png)

For consistency, there should be the same format used everywhere, or user should be allowed to use more that one format

**Comment by benanhalt** [comment]
I'm not seeing this behavior. I think it might actually be because of #442. @maxxxxxdlp can you check if that is the problem. If not indicate which database is exhibiting the bug.

**Comment by maxxxxxdlp** [comment]
Originally found in a freshly created Botany database with all of the settings on default

I can replicate it right now on [http://db1.biwebdbtest.nhm.ku.edu/](http://db1.biwebdbtest.nhm.ku.edu/)

![Screenshot from 2020-02-07 15-03-34](https://user-images.githubusercontent.com/40512816/74065749-31b6d880-49bb-11ea-8ca9-df10e6dbb452.png)

Also, for some reason, the count says that there are `2` search results returned, where in reality there is only one. Before adding the CO that is displayed here, it did not display any rows, but the count was at `1`

![Screenshot from 2020-02-07 15-04-44](https://user-images.githubusercontent.com/40512816/74065754-324f6f00-49bb-11ea-81bb-9e4b1961c46e.png)

**Comment by benanhalt** [comment]
Ok, thanks. I checked that database and the problem is due to #442
