### ISSUE TITLE
Check if build works in the latest version of Node.js

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#599]

**Comment by benanhalt** [comment]
I have node v10.15.3 installed on my workstation and it works OK.

**Comment by benanhalt** [comment]
There is a deprecation warning when installing the old version of Node, so I'm making a commit to change the instructions to use v10.x
![deprecation_nodejs_screenshot](https://user-images.githubusercontent.com/287254/74195347-a3dc2700-4c20-11ea-83d4-b6c8c3a42082.png)
