### ISSUE TITLE
Order of queried items is not preserved in a Record Set

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#601]
Originally found by Norine Spears

In Specify6, when the user creates a RecordSet out of sorted Query Results, records in the RecordSet preserve their ordering

This, however, is not the case is Specify 7, which saves the RecordSet with default ordering

**Comment by maxxxxxdlp** [comment]
Norine Spears asked to include the fix in the next release

> Hi Maksym,
>
> Do you remember the bug that I had you test that was ordering Record Sets in Specify? Basically, you can do a query and sort by the Collection Object number, which orders the results, then create a Record set form the results and when you click on the record set in Specify you can view the records in the forms and they maintain their order. Tim did some testing and this seems to work as expected in Sp 6 but not in Sp 7. I believe that Tim created a bug. I am wondering if you could find the bug and prioritize it (or mark it) so that Ben sees it and it can hopefully make this release.
>
> thanks
>
> \- Norine Spears

**Comment by benanhalt** [comment]
There is a complication to this request. Currently creating a record set implicitly adds a distinct clause to the query so that the record set will not contain duplicates. But removing duplicates can potentially change the order of the results. For instance if a record appears twice in the results, at row 10 and at row 20, which one should be removed as a duplicate? The order of the final list depends on which one is removed. In general, the ordering and distinct requirements are incompatible and one has to be sacrificed for the other.

**Comment by maxxxxxdlp** [comment]
How was this issue solved in Specify 6? Does it use a distinct clause?
How about leaving out all but the first instance?

**Comment by timo11** [comment]
In 6 you can't export a recordset from 'distinct' query results because the recordids are removed to enable complete distinctness.

**Comment by benanhalt** [comment]
@timo11, so in 6 you can generate recordsets from a query in which a given record appears more than once?

**Comment by timo11** [comment]
Yes. It's very annoying when trying to view the contents of an rs with duplicate recordids in form view.

**Comment by maxpatiiuk** [comment]
From @grantfitzsimmons:

> **Describe the bug**
> Query result sort ordering not being preserved when creating a record set.
> 
> If individual records are selected, ordering is preserved. Seems to be on the back-end.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. In the `ciscollections_2_15_24` test panel database, go to the query `/specify/query/31/` (2/14/2024 Anthropology Query for NAGPRA)
> 2. See that the ordering has the catalog number sorted in ascending order
> 3. Create a record set from the query
> 4. See that the order is not preserved
> 
> **Screenshots**
> The query:
> ![image](https://github.com/specify/specify7/assets/37256050/1ba37254-5190-4a01-a6b5-403c02b006af)
> 
> `ciscollections`, `v7.9.2`
> 
> [Specify 7 System Information - 2024-02-15T16_23_48.347Z.txt](https://github.com/specify/specify7/files/14299403/Specify.7.System.Information.-.2024-02-15T16_23_48.347Z.txt)
> 
> **Reported by:** @`CWood` from Cranbrook on the [Speciforum](https://discourse.specifysoftware.org/t/select-all-entries-from-a-query-for-record-set-and-csv/1556/4)

**Comment by emenslin** [comment]
Closing in favor of #4967
