### ISSUE TITLE
Replace Table Num and Action inputs with Picklists in Query Builder

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#604]
Replace Table Num and Action inputs with Picklists in Query Builder

**Comment by timo11** [comment]
This kind of can't be done until picklists are implemented in general in 7's Query Builder. No picklist support is currently present. Also, fields with numeric code picklists like referencework.type and agent.type (that may be all of them) need to be queried using the numeric codes.

**Comment by timo11** [comment]
The codes for Actions and Tables are now displayed in brackets following their names, for use in filters.
