### ISSUE TITLE
Add `Sp Audit Log` to the list of tables in `New Table Type`

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#605]
Specify 6 allows configuring the tables shown in the `More Tables` and on the side when creating a query

![Screenshot from 2020-02-13 10-38-03](https://user-images.githubusercontent.com/40512816/74456768-f1d57280-4e4c-11ea-8582-3e1882996051.png)

Is this feature available in Specify7?

![Screenshot from 2020-02-13 10-37-45](https://user-images.githubusercontent.com/40512816/74456766-f13cdc00-4e4c-11ea-866f-d1f93a87e81e.png)

`Sp Audit Log` table is not available in the list by default in 6 or 7, but 6 allows to add it, whereas 7 requires creating a saved query in 6 before importing a database to 7 just to be able to query that table

**Comment by timo11** [comment]
SpAuditLog is available for databases created with the 6.8.00 wizard and 6.7.04 dbs that have been updated to 6.8.00

**Comment by maxxxxxdlp** [comment]
Created a database in Specify 6.8
Logged In
Logged Out
Backuped
Restored in 7 on biwebdbtest.nhm.ku.edu
Run it on db2 (develop)

Does not show `Sp Audit Log` in the list
Does not appear even if I unhide it in Specify6 beforehand

![Screenshot from 2020-02-14 13-36-23](https://user-images.githubusercontent.com/40512816/74561877-21f54200-4f2f-11ea-8e02-b0e0e7faae98.png)

The only way right now seems to create and save a query in 6 and use it in 7

**Comment by timo11** [comment]
Is 7's specify6 instance 6.8.00?

**Comment by maxxxxxdlp** [comment]
> Is 7's specify6 instance 6.8.00?

@timo11 I guess no, I can not really update it. I guess @benanhalt needs to add a 6.8 server that will update itself daily
