### ISSUE TITLE
Problems with Search

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#606]
Search for localities returns weird results

First of all, it returns several counties, which is okay, but we have no way of knowing which state any of those belong to. 

![Screenshot from 2020-02-13 10-58-54](https://user-images.githubusercontent.com/40512816/74459003-2e569d80-4e50-11ea-8b08-a9e2f22dbc35.png)

Searching for `Kansas Douglas County` returns no results
Yet even searching for `Douglas County` returns no results

![Screenshot from 2020-02-13 10-59-15](https://user-images.githubusercontent.com/40512816/74459005-2e569d80-4e50-11ea-848a-265263a5438f.png)

There have been similar problems when searching for other states and counties

Also, the number of search results is limited

![Screenshot from 2020-02-13 11-05-23](https://user-images.githubusercontent.com/40512816/74459378-d0768580-4e50-11ea-945f-a4cfe17a3465.png)

**Comment by grantfitzsimmons** [comment]
Fixed at some point between then and now.

<img width="580" alt="image" src="https://user-images.githubusercontent.com/37256050/218633988-6b445587-d7d2-427e-b18f-7f039fa1b843.png">
