### ISSUE TITLE
Add ability to configure shown tables in the Query Builder

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#607]
Specify 6 allows configuring the tables shown in the `More Tables` and on the side when creating a query

![Screenshot from 2020-02-13 10-38-03](https://user-images.githubusercontent.com/40512816/74456768-f1d57280-4e4c-11ea-8582-3e1882996051.png)

This feature is missing from Specify 7

![Screenshot from 2020-02-13 10-37-45](https://user-images.githubusercontent.com/40512816/74456766-f13cdc00-4e4c-11ea-866f-d1f93a87e81e.png)

See also #605 and #395

**Comment by grantfitzsimmons** [comment]
Works great! Not impacted by the issue associated with #1817 at this moment 😄
