### ISSUE TITLE
Sort saved queries in the same order in Specify 6 and Specify 7

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#615]
From Michigan by Andy

<img width="273" alt="Screen Shot 2020-03-09 at 12 07 46 PM" src="https://user-images.githubusercontent.com/40512816/76240108-a8d0ce00-6200-11ea-9095-23dcaa70c019.png">
<img width="343" alt="Screen Shot 2020-03-09 at 12 20 30 PM" src="https://user-images.githubusercontent.com/40512816/76240112-aa01fb00-6200-11ea-8426-eb268fb286d7.png">

**Comment by grantfitzsimmons** [comment]
In Specify 7:
![image](https://user-images.githubusercontent.com/37256050/163582540-a2f87e48-e6ea-467c-becf-9eceee11347a.png)

In Specify 6:
![image](https://user-images.githubusercontent.com/37256050/163582571-7ea74978-47b4-4e4b-8be5-d2b4bbc4b26c.png)

**Comment by maxxxxxdlp** [comment]
You can change the sort order of queries in sp7 by clicking on the column header
It also remembers your sort options between sessions

**Comment by grantfitzsimmons** [comment]
I was able to sort by name and by date. No configuration matched the saved queries order in Specify 6. 
I prefer the sorting from Specify 7, so this should only be fixed if we want to keep consistency.

**Comment by maxxxxxdlp** [comment]
If you sort by query name in ascending order, isn't the sort order the same between 6 and 7?

**Comment by grantfitzsimmons** [comment]
I thought it would be the case but it is not! Very odd

**Comment by maxxxxxdlp** [comment]
This is caused by https://github.com/specify/specify7/issues/669.
Otherwise the sort order is the same
