### ISSUE TITLE
Compare Sp6 and Sp7 auditing logs

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#630]
Compare Sp6 and Sp7 auditing logs

**Comment by maxxxxxdlp** [comment]
Sp7 saves a bunch of SpQuery records in auditing for each change to the saved query

![Screenshot from 2020-03-17 14-16-57](https://user-images.githubusercontent.com/40512816/76893239-034dd800-685a-11ea-83be-8dd678955eb4.png)

Sp6 does not do that

**Comment by maxxxxxdlp** [comment]
`Timestamp Created` and `Timestamp Modified` are shown differently in Sp6 and Sp7, even though they are saved the same way in SQL. Can we change the way the date is displayed in Sp7 to make it show the time too?

![Screenshot from 2020-03-17 14-30-28](https://user-images.githubusercontent.com/40512816/76894307-e74b3600-685b-11ea-99a8-17cdabd15a30.png)
![Screenshot from 2020-03-17 14-30-38](https://user-images.githubusercontent.com/40512816/76894309-e7e3cc80-685b-11ea-8ca9-4e59bd6eff37.png)

**Comment by grantfitzsimmons** [comment]
Closing this as not planned unless we find a reason to investigate further.
