### ISSUE TITLE
Bad layout in Report/Label dialog for CSU Fullerton database

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#65]
![csu_fullerton_reports](https://cloud.githubusercontent.com/assets/287254/7284549/15b88fba-e904-11e4-9615-1baf6bfd3665.png)

**Comment by benanhalt** [comment]
I'm not sure why this is happening. I can't see any difference in the styling between the Reports section and the Labels section. Also I'm not seeing it in other databases. Maybe it is because the only name in the table, "Tags", is short?

**Comment by benanhalt** [comment]
It is because the name is short.

**Comment by glg4920** [comment]
All values have to be short to trigger bug
