### ISSUE TITLE
Is on Loan checkbox is checked by default in Preparation forms

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#650]
The checkbox should be unchecked unless the preparation is on loan.  Currently, as soon as I click the green plus to create a Prep record, the checkbox is checked.

**Comment by tlammer** [comment]
Edinburgh noted this as well and created their own bug here https://github.com/RBGE-Herbarium/Specify_functionality/issues/13

**Comment by benanhalt** [comment]
Ready for testing in the issue-650 build.

**Comment by norinespears** [comment]
I am testing this in the WorkBench.test.specifycloud (version next-release) and it is still happening. As soon as I click the '+' button to add a Preparation the 'Is on Loan' checkbox is checked.

**Comment by benanhalt** [comment]
This isn't merged in yet. It has to be tested in the issue-650 build.

**Comment by maxxxxxdlp** [comment]
I can't test it because I am getting this error when I open the Preparation form -https://github.com/specify/specify7/issues/874

**Comment by norinespears** [comment]
So we have to test each ticket individually with each separate build, or can we skip some and test upstream and catch more than one?

**Comment by benanhalt** [comment]
@maxxxxxdlp I think #874 is happening when you try to open the prep form as a top level form `/specify/view/preparation/new/`. In practice the prep form only is used as a subform. Can you test this issue by adding  a prep through the collection object form? Either a new CO or an existing one.

**Comment by maxxxxxdlp** [comment]
@benanhalt oh, yup, it works fine on the form
But it still shows up in the list of tables. Does it mean that it as a separate form in Sp6?

**Comment by benanhalt** [comment]
It's not a separate form in 6 to my knowledge. What list of tables is it showing up on?

**Comment by maxxxxxdlp** [comment]
Data entry menu in KU Fish

![Screen Shot 2021-07-15 at 7 55 29 PM](https://user-images.githubusercontent.com/40512816/125827224-0361cf7a-52c6-4386-871c-0405614ddcf4.png)

**Comment by benanhalt** [comment]
I think that is just a weirdly configured database. Maybe someone added Prep to the data entry task to test something.

**Comment by maxxxxxdlp** [comment]
As far as original issue goes:
The checkbox is disabled and not checked

**Comment by benanhalt** [comment]
Great, I'll merge after the meeting.
