### ISSUE TITLE
`EnvironmentError: mysql_config not found` when running pip install

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#652]
My docker container fails on the following line when executing the following line in the specify7 makefile:

![Capture2](https://user-images.githubusercontent.com/40512816/79906372-4a8d3280-83dd-11ea-94e5-e5933a8a084a.PNG)

That is the error I get:
![Capture](https://user-images.githubusercontent.com/40512816/79906370-49f49c00-83dd-11ea-9d8a-05af795f5e72.PNG)
```
/usr/bin/pip install --upgrade -r requirements.txt
Collecting Django==1.10.2 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/8a/09/46f790104abca7eb93786139d3adde9366b1afd59a77b583a1f310dc8cbd/Django-1.10.2-py2.py3-none-any.whl (6.8MB)
Collecting mysqlclient==1.3.13 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/ec/fd/83329b9d3e14f7344d1cb31f128e6dbba70c5975c9e57896815dbb1988ad/mysqlclient-1.3.13.tar.gz (90kB)
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-py4VCj/mysqlclient/setup.py", line 18, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 53, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 28, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-py4VCj/mysqlclient/
Makefile:18: recipe for target 'pip_requirements' failed
```

These are all of the libraries I install
```bash

RUN apt-get update && apt-get -y install \
	git python-pip python-dev default-libmysqlclient-dev \
	apache2 libapache2-mod-python libapache2-mod-wsgi \
	build-essential curl python-lxml git \
	libssl-dev libsasl2-dev libldap2-dev aptitude
RUN apt-get install -f && aptitude install -y nodejs npm
```

My full Dockerfile:
[Dockerfile.zip](https://github.com/specify/specify7/files/4512424/Dockerfile.zip)

I think I am missing some packages. Any idea what can it be?
Thanks!

P.S: I also tried replacing `libmysqlclient-dev` with `default-libmysqlclient-dev` but I still got the same error message

**Comment by maxxxxxdlp** [comment]
I still have the same problem after adding `MySQL-server` to the package list. I will try my luck again tomorrow
Any other suggestions on what can solve this issue?

**Comment by benanhalt** [comment]
Is it possible to get a command line inside the container to check and see if `/usr/bin/mysql_config` exists?

**Comment by maxxxxxdlp** [comment]
It is not present, but I have all of these directories in `/usr/bin/`:

![Capture](https://user-images.githubusercontent.com/40512816/80024967-7e338f80-84a5-11ea-95de-c21f6f0fc695.PNG)

**Comment by benanhalt** [comment]
They should not be directories, maybe symlinks? Can you try manually running `apt install libmysqlclient-dev` from there? Also if they are symlinks, `ls -l` should show the link targets. Maybe see if mysql_config is in that location.

**Comment by maxxxxxdlp** [comment]
Running `mkdir /usr/bin/mysql_config` before that, trigggers a similar error message:
![Capture](https://user-images.githubusercontent.com/40512816/80025214-e2565380-84a5-11ea-8947-5b17bab26f70.PNG)
`chown 777 /usr/bin/mysql_config` does not help
`chown -R specify:specify /usr/bin/mysql_config \
	&& chown -R specify:www-data /usr/bin/mysql_config` does not help either

This is the code I try to execute:
![Capture2](https://user-images.githubusercontent.com/40512816/80025868-d919b680-84a6-11ea-9635-a489bbea5696.PNG)

After that, I get `mysql_config ` in that location. Did not have it there before (though, the issues still persists)
![Capture](https://user-images.githubusercontent.com/40512816/80025866-d919b680-84a6-11ea-9bfa-6c81656ec7a4.PNG)

Though, now I get the following error:
![Capture3](https://user-images.githubusercontent.com/40512816/80025869-d919b680-84a6-11ea-9b07-4c2daae9d103.PNG)

Same error if I run these:
`apt-get -y install default-libmysqlclient-dev`
`apt-get -y install libmysqlclient-dev`

**Comment by benanhalt** [comment]
Why are you trying to make it a directory?

**Comment by maxxxxxdlp** [comment]
Oh, should it be a link instead?
I just see that nothing was there and though creating a directory would solve it

**Comment by benanhalt** [comment]
Based on the file sizes of the other mysql_* files, it should probably just be a regular binary file. I thought maybe they were links before because you said they were directories.

**Comment by benanhalt** [comment]
I just checked the biwebdbtest server which is ubuntu 18.04 and the mysql_config command is provided by the libmysqlclient-dev package.

**Comment by benanhalt** [comment]
The list of files provided by that package is at https://packages.ubuntu.com/bionic/amd64/libmysqlclient-dev/filelist

Maybe look and see if any of them are there.

**Comment by maxxxxxdlp** [comment]
None of the solutions shown here (https://stackoverflow.com/questions/7475223/mysql-config-not-found-when-installing-mysqldb-python-interface) worked

Though, replacing `libmysqlclient-dev` with `libmariadbclient-dev` fixed that problem immediately!
Is there any way we can make Specify7 server run with MariaDB?

**Comment by git-arbitrarysystems** [comment]
this worked for me `sudo apt-get install libmysqlclient-dev`

**Comment by kugteg** [comment]
@benanhalt let me know if you want any help enabling mariadb support. I use it a ton and would be happy to help out.

**Comment by maxxxxxdlp** [comment]
Update on this:
MariaDB is now a preferred way to run Specify as it's latest version is compatible both with Specify 6 and Specify 7.
Newest MySQL can still be used with Specify 7, but majority of testing is done using MariaDB (Specify Cloud is using MariaDB too).
Also note that if you plan on using Specify 7 with Specify 6, Specify 6 does not support MySQL versions newer than 5.7

Also, Django, Python and all other back-end dependencies have been updated since this issue was opened, so I am closing this as stale
