### ISSUE TITLE
Allow to query partial `Modified Date` for CO

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#657]
When Querying `Cataloged Date` for CO, we are able to select to query `Full Date` or any part of it. Such options are not available for `Modified Date`

<img width="993" alt="Screen Shot 2020-04-27 at 12 21 14 PM" src="https://user-images.githubusercontent.com/40512816/80401278-ae05dd00-8881-11ea-8396-cc8f553b93de.png">
<img width="993" alt="Screen Shot 2020-04-27 at 12 21 32 PM" src="https://user-images.githubusercontent.com/40512816/80401282-af370a00-8881-11ea-9a12-adcd9115ce5b.png">

**Comment by maxxxxxdlp** [comment]
Fixed in c1ec1eee

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/163607177-190aa924-822b-473c-ad05-b0788a7cc7e4.png)

Well they now act the same... 😂

**Comment by maxxxxxdlp** [comment]
The date fields are split apart.
You can query either the entire date (i.e, `Timestamp Modified`, or only part of it (`Timestamp Modified (Year)`)
