### ISSUE TITLE
Make paleo tree nodes sort by time instead of name

### ISSUE THREAD

**Issue by drew-wallace** [specify/specify7#66]
Right now the are alphabetical by tree node name. It was suggested that the tree nodes be sorted by time. It could be an option to switch between the 2 sorting methods.

**Comment by benanhalt** [comment]
Add a pref to set the sortby field for a tree.

**Comment by timo11** [comment]
Need to decide on details for sortby pref

**Comment by loveablelobster** [comment]
I guess that could only work if the chronological age be given in End and StartPeriod

Otherwise, a general nifty tree feature (and I realize that should be a new issue): manual sorting facilities for tree nodes

**Comment by timo11** [comment]
To sort by startPeriod add the following remote pref:

GeologicTimePeriod.treeview_sort_field=startPeriod

(PrefName='GeologicTimePeriod.treeview_sort_field', value = 'startPeriod')

You can use a different field if you want. To restore to default behavior, remove the pref, or replace 'startPeriod' with 'name'.

This works only for the chronostrat tree view.
It is a database-wide setting.

**Comment by timo11** [comment]
nodes with null startPeriod will sort before non nulls, in unspecified order.

**Comment by benanhalt** [comment]
Re your comment: https://github.com/specify/specify7/commit/e9765db8c6b2f5c59004ef821c6f71dbf8cc134e#diff-d7b2e1c5dc64730e6ae6bf7a852ded49R40

I think it would work better to pass the *order by* column from the client. To sort on the client side would require that `tree_view` api to return all possible sort columns.

Making the api be something like `/api/specify_tree/TREE_NAME/NODE_ID/?order_by=FIELD_NAME` makes sense to me. Then the code in the server would look something like:

```python
@require_GET
def tree_view(request, treedef, tree, parentid):
# ...
    sort_col_name = request.GET.get('order_by', 'name')
    orderby = getattr(node, sort_col_name)
# ...
```

On the client side, look at *dateformat.js* for how to get at remote prefs.

**Comment by benanhalt** [comment]
Also, that makes it possible in the future to let the user dynamically select the sort field in tree page and not rely on a pref.

**Comment by timo11** [comment]
pref is now read by client and passed to server.

the pref can now be set for any tree. eg. taxon.treeview_sort_field=number1

**Comment by yvonneekanim** [comment]
Tested in UTAustinpaleo. When remote pref is added, chronostrat tree sorts by start date. Nodes with no start date sort alphabetically before those with start dates.
