### ISSUE TITLE
JS exceptions thrown when attachments with null mimetype are encountered.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#663]

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp How can I test this?

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons For any record in the Attachment table, set mimeType to NULL (in the database). Then make sure that the front-end still works:
1. Can display that attachment
2. Can display it's metadata
3. Can delete it

**Comment by grantfitzsimmons** [comment]
I cannot see a preview of that attachment (Removed MIME type "application/vnd.ms-excel"), but I can download it. I can display the metadata and I can delete it from the CO record itself.
