### ISSUE TITLE
Disabled "Save changes?" challenge dialog when closing an unaltered data form

### ISSUE THREAD

**Issue by FedorSteeman** [specify/specify7#664]
As a Specify IT User (supporter) I do a lot of testing at the moment, which can involve opening a data entry form to see if everything looks the way it's supposed to or not and then moving on. However, even if had not entered any data it still prompts for being sure to not save any changes. It's trivial in normal use, but can become an irritation moment and time consumer, when opening & closing data entry forms many short times successively. 

So I was wondering if the system could register whether any changes were even made, before asking the user to be sure they want to save the non-existing changes. :smile: 

This also has been reported by me for specify6.

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp I still am getting this-
It it because the form has a default value for a field?

![image](https://user-images.githubusercontent.com/37256050/166008439-52624d43-7a70-4d9e-bbeb-368325e68d0e.png)

**Comment by maxxxxxdlp** [comment]
Fixed in [5fbfecf](https://github.com/specify/specify7/commit/5fbfecfe60351cfcc69bb4e512c307d30bc35c53)
