### ISSUE TITLE
Update transient loan count field names.

### ISSUE THREAD

**Issue by timo11** [specify/specify7#665]
The names were changed in Six, but not Seven.

totalItems -> totalPreps
totalQuantities -> totalItems
unresolvedItems -> unresolvedPreps
unresolvedQuantities -> unresolvedItems

**Comment by timo11** [comment]
see specify6/issues/206 and specify6/issues724

**Comment by timo11** [comment]
This is fixed on the develop branch. I think it will automatically be used on the specify7 testing instance.

**Comment by benanhalt** [comment]
The develop branch is currently in limbo. I moved the commit onto its own branch and setup the "develop" servers on biwebdbtest to use that branch. So @yvonneekanim, it should be possible to test it now.

**Comment by yvonneekanim** [comment]
Great, thanks

**Comment by yvonneekanim** [comment]
Resolved items and resolved preps still aren't being calculated

**Comment by benanhalt** [comment]
Let me check that the fix is present on the server.

**Comment by benanhalt** [comment]
I checked the db1 server and it looks like the changes are there. There are changes to the Javascript, so it might not take effect if you don't clear the browser cache. If that doesn't fix it, I'm not sure what the problem might be.

**Comment by yvonneekanim** [comment]
The fix is there because 4 out of the 6 fields weren't being calculated before the fix. Now it's down to 2

**Comment by timo11** [comment]
resolvedPreps and resolvedItems were added.

**Comment by benanhalt** [comment]
Merged into master and pushed to specifycloud.
