### ISSUE TITLE
Multiple addresses can be primary at the same time

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#672]
One agent can have multiple primary addresses at the same time

![Screen Shot 2020-06-25 at 11 22 29 AM](https://user-images.githubusercontent.com/40512816/85684121-70f87400-b693-11ea-9e1f-31fd696b4577.png)
![Screen Shot 2020-06-25 at 11 22 32 AM](https://user-images.githubusercontent.com/40512816/85684125-71910a80-b693-11ea-8088-393fadf2cdc1.png)

**Comment by melton-jason** [comment]
How do we want to resolve such discrepencies? We could handle this in a way similar to `isCurrent` in Determination. 

That is, when a new Address is added, set it as primary and remove `isPrimary` from all other addresses in the local collection. 

In addition, we can add the following check: when an Address is saved, check its collection to see if it contains multiple primary addresses, and if so and a new Save Blocker to the resource.

**Comment by maxxxxxdlp** [comment]
This should be scoped to Agent, not Collection (a single agent can have only one isPrimary address)

A consideration is also required of the agents that are already out there with multiple primary addresses - adding this business rule would suddenly prevent saving them.

The best solution might be to enforce this in a way similar to isCurrent, but only if a certain remote pref is set (so that it's not on by default)

**Comment by melton-jason** [comment]
I am sorry for the confusion regarding 'Collection'. I meant the the Backbone concept of a 'collection', and not the Collection model: in this instance, all of the Adress records related to an an Agent. 

Yes a preference is a good consideration. The option will always be there for those that want strict data integrity.

**Comment by maxxxxxdlp** [comment]
This is actually part of the bigger need to add more customization to business rules - some people prefer stricter control, while others prefer more flexibility. We should consider adding prefs for all business rules (i.e, a pref to disable non-critical business rules, a pref to enable additional pref rules, a pref to change the scoping of uniqueness - assuming we won't regret this down the road when the code can't assume that a certain business rule is enforced)

**Comment by grantfitzsimmons** [comment]
Encountered again today

**Comment by grantfitzsimmons** [comment]
Still a problem when agent merging.

**Comment by bronwyncombs** [comment]
not able to recreate in terms of more than one address being primary, but there is definitely an issue with this field. As of 7.9.3 release testing on edge, you must unselect a primary address to make another one primary. If you don't, Specify ignores the action on save and reverts to keeping the original primary address as primary. 

For 'current' determinations, selecting one as current when there is one already marked 'current' will automatically deselect that one and allow you to save with the new preference for the 'current' determination. 

Preferably, the primary field would only allow one record to have this selected at once. In the case of two address records where one is primary and you want the second to be primary instead, selecting the primary box on the second should automatically deselect this on the first. 

https://github.com/specify/specify7/assets/135047322/8a78296d-94f7-455e-a454-038957aead3d
