### ISSUE TITLE
Basic user management

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#68]
Admin users should be able to add and remove specify users and reset their passwords.

**Comment by benanhalt** [comment]
This function is accessed by clicking on the user name in the upper right and choosing *Manage Users*. It is only presented to users in the Admin group.

**Comment by drew-wallace** [comment]
All the functions are there and working. But, the Make Admin button shouldn't be enabled unless the permission level is set to manager. Otherwise you can have a guest user that can't add/remove/modify data, but can add/remove/modify users and settings.

**Comment by benanhalt** [comment]
QA note: Make sure admin status is removed when user is saved if they are demoted from manager.

**Comment by drew-wallace** [comment]
Is there a way for the Make Admin button to be enabled all the time? Let's say a user is Limited access but I want them to be an admin. I could click the Make Admin button and the user would automatically be made into a Manager.

**Comment by benanhalt** [comment]
Probably. The complication is that the user type is a property of the user, but admin status is a separate table, meaning there has to be extra mechanisms to ensure invariants like 'only managers can be admins'. For now, I think it is enough that there is some way to manage users. I would rather defer more complicated stuff until we address the permission/security system as a whole.

**Comment by drew-wallace** [comment]
verified in c88655ef95d52c979c9e3b418bbfa849d8c781d5
