### ISSUE TITLE
Python3: Specify adds the same value to picklist multiple times

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#684]
Every time I put a value into a picklist and make the field lose focus, I am getting a prompt to add this value to the list of picklist options

![Screen Shot 2020-06-25 at 2 01 54 PM](https://user-images.githubusercontent.com/40512816/85708082-6d6fe780-b6a9-11ea-8a95-cf8d44e61106.png)

This happens regardless of how many times the value is already present in the list
![Screen Shot 2020-06-25 at 2 02 07 PM](https://user-images.githubusercontent.com/40512816/85708089-6fd24180-b6a9-11ea-87cc-a2f768fc636f.png)

**Comment by benanhalt** [comment]
This does seem like it is probably the same bug as #571 because it only happens if there is a single character. I don't think it is related to the python 3 changes.

**Comment by maxxxxxdlp** [comment]
Closed as per https://github.com/specify/specify7/issues/684#issuecomment-653141800
See #571
