### ISSUE TITLE
Python3: How do I add a new row to a dataset in a Workbench?

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#689]
How do I add a new row to a dataset in a Workbench?

There does not seem to be a button
Filling out all of the fields for the existing row did not do the trick either
Was there supposed to be a new row created at the end as soon as I make any modifications to the last row?

![Screen Shot 2020-06-25 at 2 50 38 PM](https://user-images.githubusercontent.com/40512816/85714596-3224e700-b6b0-11ea-8aa5-9f1907daa9f3.png)

**Comment by benanhalt** [comment]
Right click on the bottom row and select "insert row below".
