### ISSUE TITLE
Python3: New user does not have Saved Queries, Data Sets, Record Sets, Loans, ...

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#693]
A new user does not have Saved Queries, Data Sets, Record Sets, Loans, ...
All of these were present for a different user
This is still the case even after I gave all permissions to the new user

Is this by design or is it a bug?

![Screen Shot 2020-06-25 at 3 05 37 PM](https://user-images.githubusercontent.com/40512816/85716758-66010c00-b6b2-11ea-86f1-bed8d0e1f7e6.png)
![Screen Shot 2020-06-25 at 3 05 41 PM](https://user-images.githubusercontent.com/40512816/85716787-6c8f8380-b6b2-11ea-8c58-aca6347843e1.png)
![Screen Shot 2020-06-25 at 3 05 31 PM](https://user-images.githubusercontent.com/40512816/85716791-6d281a00-b6b2-11ea-856c-888d4f6fe8bd.png)
![Screen Shot 2020-06-25 at 3 05 27 PM](https://user-images.githubusercontent.com/40512816/85716796-6dc0b080-b6b2-11ea-8b91-a8b6087dc88d.png)

**Comment by benanhalt** [comment]
This is how it is supposed to work. Queries, datasets, etc. are per user.
