### ISSUE TITLE
Attachment does not exist, yet is shown on the attachments page

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#695]
Attachment does not exist, yet is shown on the attachments page

<img width="1440" alt="Screen Shot 2020-06-26 at 4 04 05 PM" src="https://user-images.githubusercontent.com/40512816/85860018-b09e8900-b783-11ea-9efc-34f0e413a8ff.png">

<img width="1440" alt="Screen Shot 2020-06-26 at 4 04 08 PM" src="https://user-images.githubusercontent.com/40512816/85860036-b6946a00-b783-11ea-918c-401439d8277b.png">

**Comment by benanhalt** [comment]
Somehow the file was missing from the asset server. I put it back and it's working now.

**Comment by maxxxxxdlp** [comment]
![Screen Shot 2020-06-26 at 9 50 03 PM](https://user-images.githubusercontent.com/40512816/85890956-f1ae9180-b7b3-11ea-98af-87266dce05c8.png)
Works fine now. Except it is present two times. I guess that is not a big deal

**Comment by benanhalt** [comment]
It's there twice because I added it as an attachment to another CO to test that it was working :)
