### ISSUE TITLE
Date format change changes date value

### ISSUE THREAD

**Issue by ianengelbrecht** [specify/specify7#697]
If a full date, ie year/month/day, exists, and the date format is changed to a partial date, eg Year-Month, the day value on the original date is changed to 1. ie the original date value is lost. This might lead to data errors if someone accidentally changes the date format. Suggestion to fix is check first if date value exists on date format change, only add the necessary date parts as 1 if not.

**Comment by maxxxxxdlp** [comment]
Superseded by #1125 (which is now fixed)
