### ISSUE TITLE
Querycbx search button doesn't work for parent field of tree records.

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#698]
Search button does not open a search window on click

<img width="1440" alt="Screen Shot 2020-06-29 at 5 49 47 PM" src="https://user-images.githubusercontent.com/40512816/86020835-08d8c380-b9ee-11ea-9744-3d63e01e3e22.png">

If the value of the field was modified, it gets reset when I click the search button

<img width="1440" alt="Screen Shot 2020-06-29 at 5 49 50 PM" src="https://user-images.githubusercontent.com/40512816/86020842-0aa28700-b9ee-11ea-84e9-40427e135014.png">

**Comment by maxxxxxdlp** [comment]
Still happens after page refresh

**Comment by benanhalt** [comment]
This bug exists in the Python 2 instance, as well.

**Comment by maxxxxxdlp** [comment]
@benanhalt is this fixed?
I am unable to replicate the bug anymore

**Comment by benanhalt** [comment]
It only seems to affect the querycbx for the parent field of tree records.

**Comment by benanhalt** [comment]
The search dialog opens now, but doesn't seem to return any results.

**Comment by maxxxxxdlp** [comment]
That's a separate issue
Looks like the search results are filtered out at this line - https://github.com/specify/specify7/blob/9da39dba6fc93292ccf9a0bab1b3d6a7fc646678/specifyweb/frontend/js_src/lib/querycbxsearch.js#L90

Opened #879
