### ISSUE TITLE
Only admin users should be able to change/add specifyuser resources

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#70]
Presently, any user with edit privileges (Manager, Full Access) can edit and add new SpecifyUser objects. There is no UI presented for them to access these objects, but they can be accessed by directly setting the URL or accessing the API.

They cannot however set passwords or agents for users meaning users they create could never login, so the overall level of exposure is low. The worst thing they can do is change the username of other users. The solution seems like it should be part of the broader table-level access system that will eventually need to be implemented.

**Comment by maxxxxxdlp** [comment]
Fixed by adding permission system
