### ISSUE TITLE
Can't return loan by pressing `Return Loan` on the form

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#700]
This is the message I am getting when I press the `Return Loan` button on the Loan form
As you can see, there is one preparation and it has not been resolved yet
Refreshing the page does not solve the issues

<img width="1440" alt="Screen Shot 2020-06-29 at 5 58 26 PM" src="https://user-images.githubusercontent.com/40512816/86021792-1e9ab880-b9ef-11ea-82e6-76ada3d2f2f5.png">

I am able to return the same loan through `Interactions` > `Return Loan` menu

<img width="1440" alt="Screen Shot 2020-06-29 at 6 00 34 PM" src="https://user-images.githubusercontent.com/40512816/86022003-64f01780-b9ef-11ea-83bb-c67e6760e8df.png">

**Comment by benanhalt** [comment]
It says that because the quantity resolved is equal to the total quantity. I'm not sure how the "Is Resolved" field is supposed to work. At any rate, it seems to be the same in the Python 2 version.
