### ISSUE TITLE
Fields with default dates fail to save.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#71]
In KU Fish, when creating a new loan various date fields are prepopulated, but when the form is saved the values disappear.

**Comment by benanhalt** [comment]
The problem is actually that the date formatting incorrectly replaces null values with the current date. So, I think this problem will show up on any form that has text fields that represent date types in the database. It has nothing to do with default values.

**Comment by benanhalt** [comment]
For QA verification: The KU Fish database has date fields in the loan form which is accessible at `/specify/view/loan/new/`. The bug was that the current date was appearing in those fields. It should not do so.

**Comment by drew-wallace** [comment]
verified in cf41ff6370a9ae1040466626d77a5b8f5cdce94e

No more default date
