### ISSUE TITLE
Catalog number format is not enforced

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify7#714]
If a created catalog number format contains alpha characters, the number format is not enforced in 7

**Comment by benanhalt** [comment]
Do you have a database setup that has this problem that I can look at?

**Comment by yvonneekanim** [comment]
yes 'm' collection in 'database' on db2

**Comment by benanhalt** [comment]
Can you provide more details? It seems to be working for me:

![issue-714](https://user-images.githubusercontent.com/287254/87090145-203d5b00-c1fd-11ea-87e7-d155419e1ac4.png)
![issue-714-2](https://user-images.githubusercontent.com/287254/87090147-20d5f180-c1fd-11ea-9491-b061528bc37e.png)

**Comment by yvonneekanim** [comment]
User error. Shouldn't it have a preview of the format like the other collection or is that because the numeric part doesn't increment?
