### ISSUE TITLE
Generated Geography Query returns no results

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#717]
The following Geography has one CO
![Screen Shot 2020-07-11 at 12 06 23 AM](https://user-images.githubusercontent.com/40512816/87203211-c6c35200-c30a-11ea-98db-7ffb8c1a52ac.png)

Running a query on the CO proves that
![Screen Shot 2020-07-11 at 12 07 52 AM](https://user-images.githubusercontent.com/40512816/87203374-24f03500-c30b-11ea-9ec2-1805fc0abf13.png)

We can go to a formatted query by right-clicking the Geography
![Screen Shot 2020-07-11 at 12 07 47 AM](https://user-images.githubusercontent.com/40512816/87203239-d478d780-c30a-11ea-9161-bec29b465287.png)

Yet, such query returns no results
![Screen Shot 2020-07-11 at 12 07 58 AM](https://user-images.githubusercontent.com/40512816/87203276-ebb7c500-c30a-11ea-8df2-811408338d57.png)

As you can see, it is querying by State ID
Yet, I can't even see such column in the list
![Screen Shot 2020-07-11 at 12 08 52 AM](https://user-images.githubusercontent.com/40512816/87203348-13a72880-c30b-11ea-8f03-5f95f32ab7a3.png)

**Comment by maxxxxxdlp** [comment]
Same problem with `Storage`
![Screen Shot 2020-07-11 at 12 15 24 AM](https://user-images.githubusercontent.com/40512816/87203592-a051e680-c30b-11ea-9b91-5dc1e7dff56a.png)

**Comment by benanhalt** [comment]
It's because the auto generated query includes the `Determination.isCurrent = True` filter. That excludes collection objects with no determinations. Maybe the generated query should be changed to `Determination.isCurrent = True or Null`

![image](https://user-images.githubusercontent.com/287254/87456986-513ad880-c5cd-11ea-9597-5ab5df7918e8.png)

**Comment by benanhalt** [comment]
This was discussed in a meeting and we decide to change the generated query as described in the prior comment.
