### ISSUE TITLE
`make build` throws exceptions on `workbench-upload` branch

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#721]
I am trying it through docker on my mac
`production` branch works fine
![Screen Shot 2020-08-10 at 3 46 50 PM](https://user-images.githubusercontent.com/40512816/89784798-f770f400-db21-11ea-9366-fb0f53c5aa4e.png)

**Comment by benanhalt** [comment]
There are some changes to how the python virtualenv gets set up. (https://github.com/specify/specify7/tree/workbench-upload#creating-and-activating-the-virtualenv) Did you include those in your Dockerfile?

**Comment by maxxxxxdlp** [comment]
Oh, I did not notice those

Unfortunately, it is still throwing errors when running `make build`
<img width="1440" alt="Screen Shot 2020-08-10 at 8 10 29 PM" src="https://user-images.githubusercontent.com/40512816/89810414-b2f74f80-db45-11ea-8e1c-005a09205359.png">

This is how I set up a virtual environment
![Screen Shot 2020-08-10 at 8 10 45 PM](https://user-images.githubusercontent.com/40512816/89810459-c5718900-db45-11ea-8b7d-4c047385c360.png)

I did not see pip in the list of dependencies, so I am installing both `python-pip` and `python3-pip`:
![Screen Shot 2020-08-10 at 8 10 57 PM](https://user-images.githubusercontent.com/40512816/89810514-dde1a380-db45-11ea-80b9-0f8f91e4ea01.png)

**Comment by benanhalt** [comment]
The `bash -c "source ..."` isn't going to work... Try changing where you run make from
```
make pip_requirements && make build
```
to 
```
VIRUTAL_ENV=/usr/local/specify7/ve make build
```
And maybe in the Makefile change `PIP = $(VIRTUAL_ENV)/bin/pip` to `PIP = $(VIRTUAL_ENV)/bin/python -m pip`
