### ISSUE TITLE
Adding paleo context as subview in collecting event table causes issues 

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify7#725]
I've attached screenshots of what the same paleo context subform looks like as a subview in CE table vs CO table. It looks the same in both tables in Specify 6
Paleo context subform in collecting event table:
![CE table](https://user-images.githubusercontent.com/28809154/91332029-33968c80-e791-11ea-87dd-b9b0eea17904.png)
Paleo context subform in collection object table:
![CO table](https://user-images.githubusercontent.com/28809154/91332055-385b4080-e791-11ea-970a-15fbf5254003.png)

**Comment by yvonneekanim** [comment]
Paleo context only works as a subview in CO if it is embedded. Otherwise it looks like the first image above

**Comment by grantfitzsimmons** [comment]
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/37256050/180678108-231ca1de-8ddc-412b-93bd-78c23f87a43d.png">

I have not been able to to add a paleoContext subview on the CE form. It appears but I cannot add items.

```
                <row>
                    <cell type="label" labelfor="pcsh"/>
                    <cell type="field" uitype="querycbx" id="pcsh" name="paleoContext" initialize="name=PaleoContext" colspan="10"/>
                </row>
                <row>
                    <cell type="subview" viewname="SubPaleoContext" id="pcem" name="paleoContext" defaulttype="table" colspan="9"/>
                </row>

```

**Comment by maxxxxxdlp** [comment]
It looks like SubViews for independent fields are rendered as read-only.
I copied that setting from the previous implementation of SubViews: https://github.com/specify/specify7/blob/7fd134e3c8368fbc3adf243499fb768807d574ec/specifyweb/frontend/js_src/lib/subview.js#L49
It's easy to remove that.
@benanhalt do you know why that was added initially?

**Comment by benanhalt** [comment]
Yes. That is the intended behavior. If the paleocontext is set to be embedded according to the schema, then self.field.isDependent() should be true. If it's not then that is the bug.

**Comment by maxxxxxdlp** [comment]
> That is the intended behavior
Can you explain why?

Also, `CollectingEvent -> paleoContext` is not set as dependent at the moment.

**Comment by grantfitzsimmons** [comment]
When creating a new accession record in Specify 6, the Repository Agreement subview under the Accession table is working correctly.

<img width="1210" alt="Screen Shot 2022-09-15 at 9 21 45 AM" src="https://user-images.githubusercontent.com/37256050/190428702-6d21380b-c35f-4765-83bc-0d9b876953c4.png">

When creating a record in Specify 7, there is no way to add a Repository Agreement to an Accession record. The **+** icon is disabled.

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/37256050/190428761-a212d442-3edc-4b8e-ae20-ff03ac43edf2.png">

This is in the same database with the same forms.

The behavior begins to complicate after saving the Accession record:

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/37256050/190429550-8246a687-37ed-4c60-b8d4-14cbddbe9970.png">

**Now a Repository Agreement is randomly assigned. I created a single repository agreement in this database and it immediately selected it. There is no way to remove this relationship or modify it.**

When viewing the same record in Specify 6, it shows there is no Repository Agreement assigned.

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/37256050/190430520-e90f6c46-b358-47fa-9b28-da174339a0be.png">

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/37256050/190431206-dd4a42e5-fb67-43ea-9d44-0ef5ad4b5db6.png">

**Database:** `pripaleo`
**User:** `kmiller`
 
https://pripaleo-edge.test.specifysystems.org/specify/view/collectionobject/70641/

[paleo.views.xml](https://drive.google.com/file/d/1CoIqz4DyTtaoOuJFYpW_R4qYM5y_LIwx/view?usp=sharing)

**Reported By:** Matthew Cruz at The University of Michigan

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp 
> **It affects all subviews to non-dependent relationships. We need to figure out why that limitation was put in place. Once we do, removing it is easy.**

**Comment by maxxxxxdlp** [comment]
Solutions:
- Either mark paleo context relationship as dependent
- Or, render the relationship as a query combo box rather than a SubView. @grantfitzsimmons does this solution work for you?

**Comment by grantfitzsimmons** [comment]
What is the issue with marking paleo context as dependent?

**Comment by grantfitzsimmons** [comment]
And how can I verify that this has been solved? Is it on `testability`?

**Comment by maxxxxxdlp** [comment]
This has not been fixed yet. If you want paleo context to be displayed as a SubView, ask Ben to mark it as a dependent

**Comment by grantfitzsimmons** [comment]
@benanhalt Can you mark this relationship as dependent to solve this problem?

**Comment by benanhalt** [comment]
It isn't always dependent. It can be set to embedded or not, and also it can be set to be embedded in different tables. So the dependent status depends on those settings. I can check to see if it is properly respecting the settings.

**Comment by benanhalt** [comment]
The logic is handled here: https://github.com/specify/specify7/blob/d9776d60818d6a0b2e79dc56c79736fbfadc5140/specifyweb/frontend/js_src/lib/specifyfield.ts#L282

It looks like it is implemented so you need to check if the database has paleo context set to be embedded in collecting event in this database.

**Comment by maxxxxxdlp** [comment]
> Now a Repository Agreement is randomly assigned. I created a single repository agreement in this database and it immediately selected it. There is no way to remove this relationship or modify it.

This could be just a visual bug. @grantfitzsimmons  Are you still able to replicate it

Current behavior:
If "embeddedPaleoContext" boolean is true for the current collection (can be changed on the collection form), then Paleo Context can be displayed as a SubView/form table. Otherwise, it can only be displayed as a query combo box or a subview button
@grantfitzsimmons does that sound good? In which case this issue can be closed

**Comment by grantfitzsimmons** [comment]
Same rule applies to Collecting Events.

If "IsEmbeddedCollectingEvent" boolean is true for the current collection (can be changed on the collection form), then Collecting Event can be displayed as a SubView/form table. Otherwise, it can only be displayed as a query combo box or a subview button
