### ISSUE TITLE
Check attachment file size before attempting to upload to asset server.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#729]
Currently the nginx proxy rejects uploads above a set size. The Sp 7 interface just reports this as an unknown error.

**Comment by maxxxxxdlp** [comment]
> Check attachment file size before attempting to upload

Since specify can not access nginx config, there is no way to detect what's the size limit

> The Sp 7 interface just reports this as an unknown error

Fixed by replacing it by a useful error and possible solutions

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-8-release-announcement/1108/1
