### ISSUE TITLE
Allow browser cache to improve performance

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#73]

**Comment by benanhalt** [comment]
To verify:

When visiting a collection on the test server, open the network tab in the browser dev tools. Make sure cache is not disabled and then change id in the url in the address bar and hit enter so a new resource is loaded. The network tab should show almost all urls other than `/api/*` with size `(from cache)`. See screenshot:

![screenshot from 2015-05-13 12 49 11](https://cloud.githubusercontent.com/assets/287254/7617027/40e064fe-f96e-11e4-954f-b7dee86fc758.png)

**Comment by drew-wallace** [comment]
verified in cf41ff6370a9ae1040466626d77a5b8f5cdce94e

I see the (from cache) for the views
