### ISSUE TITLE
Coords parser is confusing cardinal directions

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#730]
Reported by Royal Botanic Gardens Victoria

If coordinates are in format like `d dd W` or `d° dd S` and the first number is less than 1, cardinal directions are parsed incorrectly:
West is parsed as East
South is parsed as North
East and North is recognized properly

Examples:
Works fine if >1
![Screen Shot 2020-09-14 at 11 34 51 PM](https://user-images.githubusercontent.com/40512816/93135752-8229ad80-f6e3-11ea-880f-ac300bae3b95.png)

Broken for South or West and <1
![Screen Shot 2020-09-14 at 11 35 08 PM](https://user-images.githubusercontent.com/40512816/93135753-835ada80-f6e3-11ea-9cb7-d3a61775dc86.png)

`d.dd S` works fine
![Screen Shot 2020-09-14 at 11 36 56 PM](https://user-images.githubusercontent.com/40512816/93135756-835ada80-f6e3-11ea-93d7-b61e27076339.png)

`d° dd S` format does not work properly either
![Screen Shot 2020-09-14 at 11 37 15 PM](https://user-images.githubusercontent.com/40512816/93135758-83f37100-f6e3-11ea-8f85-a9d952846cba.png)

Original message:
> If a longitude in the western or southern hemispheres where the latitude or longitude is 0 is entered in DMS format, the hemisphere is parsed incorrectly and converted to E or N:
![unnamed](https://user-images.githubusercontent.com/40512816/93135310-c9636e80-f6e2-11ea-97b5-e677799fb748.jpg)
![unnamed](https://user-images.githubusercontent.com/40512816/93135312-ca949b80-f6e2-11ea-8c9f-3ef65810e52f.png)

> The error doesn't occur if the locality is entered in decimal coordinates:
![unnamed (1)](https://user-images.githubusercontent.com/40512816/93135320-cbc5c880-f6e2-11ea-9a50-101e0e122fd4.jpg)

**Comment by benanhalt** [comment]
The underlying issue was also causing the following error:

<img width="287" alt="Screen Shot 2020-12-01 at 1 22 23 AM" src="https://user-images.githubusercontent.com/287254/100784597-092e1e00-33d5-11eb-9db8-b82e5442aab0.png">
