### ISSUE TITLE
Publish Specify Conainer(s) to Docker Hub

### ISSUE THREAD

**Issue by norinespears** [specify/specify7#738]
Email from member: Per your message/request, I want to register enthusiasm and support for a containerized version of Specify. We’ve been using Specify 7 for a few years and it’s been a little rough to maintain over that time (the joys of Ubuntu upgrades!). A production-quality Docker app would give us additional flexibility for the both host and app updates. I would also love to (eventually) see containers published to Docker Hub so that they are pre-built, pre-validated, and designed for easy pulls and upgrades with Docker Compose. That could bring a new level of stability for both development tracks and site administrators.

**Comment by maxxxxxdlp** [comment]
Ben and I have already published them to docker hub - https://hub.docker.com/u/specifyconsortium, though I am not sure we are utilizing all the futures of docker hub yet

**Comment by benanhalt** [comment]
The images in the https://hub.docker.com/repository/docker/specifyconsortium/specify7-service repository are now being automatically generated by a Github action. These are the ones that appear on the test panel. They only include Specify 7 itself and have to be composed with at least a webserver and a copy of Specify 6 from https://hub.docker.com/repository/docker/specifyconsortium/specify6-service. My plan is to create several example compositions in https://github.com/specify/docker-compositions for various setups, such as 

1. single database with all necessary components
2. mysql database server already exists somewhere else
3. one server hosting multiple databases
etc.
