### ISSUE TITLE
Support default values for picklists

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify7#743]
Currently Sp7 does not display a default value that is set in the forms

**Comment by maxxxxxdlp** [comment]
This should have been supported all along.
Either way, I made changes to combo boxes in 3e6997b8, so this needs to be tested
Default values for pick lists can be set by adding a `default="somevalue"` attribute in the form definition for a pick list.

**Comment by grantfitzsimmons** [comment]
> Default values for pick lists can be set by adding a `default="somevalue"` attribute in the form definition for a pick list.

![image](https://user-images.githubusercontent.com/37256050/161287589-e4dc832a-6c61-46b2-a50d-7c5e6ed6d8a5.png)

![image](https://user-images.githubusercontent.com/37256050/161287616-00b346a8-9ed7-4dab-966f-44d20501e578.png)

No luck setting a default. Some picklists are not appearing on the forms at the moment either.

**Comment by maxxxxxdlp** [comment]
Just tested. It works for me, but I had to clean the cache.
Make sure you cleared cache. To clear cache for a specific form, open that form, then, without reloading the page, open the User Tools menu and select "Clear Cache", then press "Reload"
Also, even though it is not a problem in this case, keep in mind that PickList items have both value and title fields. The "default" attribute tries to match by value first and only then by title.
