### ISSUE TITLE
Add UI for running query limited to a record set.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#744]
The capability already exists for label/report purposes.

**Comment by maxxxxxdlp** [comment]
It looks like `reports.js` is setting a `recordsetid` attribute on a SpQuery record
https://github.com/specify/specify7/blob/a73bfa3331163cba4bf0c0a26ad5346ec9f8bff9/specifyweb/frontend/js_src/lib/reports.js#L477

Then, that value is read before query execution
https://github.com/specify/specify7/blob/a73bfa3331163cba4bf0c0a26ad5346ec9f8bff9/specifyweb/stored_queries/execution.py#L115

Yet, I don't see the recordsetid field in the data model - http://workbench.test.specifycloud.org/specify/datamodel/spquery/
I even get a warning from Backbone when trying to set it.

@benanhalt Is it okay to set a value for a field that is not part of data model?

**Comment by maxxxxxdlp** [comment]
Ready for testing on branch `query-toolbar-refactor`

In the dialog that presents a list of record sets, press on the pencil icon and then on the `Query` button.

**Comment by benanhalt** [comment]
>  Is it okay to set a value for a field that is not part of data model?

It's not ideal. This is basically the same thing that was happening with that `captions` data for the KML export.
