### ISSUE TITLE
Can't synonymize taxa that have children

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#751]
Should be able to synonymize taxa with synonymized children.  The way it works in 6, a taxa with children can be synonymized as long as all children have already been synonymized.  If any of the children are considered valid, then you cannot synonymize the parent.

**Comment by maxxxxxdlp** [comment]
@benanhalt Is this a back-end limitation or a UI oversight? The synonymize action seemed to work without problems once I force-enabled the button

**Comment by benanhalt** [comment]
I would expect it to get caught here: https://github.com/specify/specify7/blob/production/specifyweb/specify/tree_extras.py#L216-L218

If that check was removed, one would have to be added to catch the case where there unsynonymized children to maintain that invariant.

**Comment by benanhalt** [comment]
A remote pref was added to get around this. See #1735

**Comment by grantfitzsimmons** [comment]
> > **Plarson:** Ability to add child taxa to synonymized (non-preferred) taxa
> 
> **Schuchert:** yes this is feature we also miss. If you have to enter obsolete names from old labels, you will have to undo the synonymy, add the child taxon and synonymize it, then synonymize the parent again. This is rather cumbersome.
>
> **HeatherC:** YES, this would apply to our collection too! (being able to connect determinations to non-preferred taxa)

**Comment by grantfitzsimmons** [comment]
This continues to be an in-demand feature for the front-end to be built for

**Comment by melton-jason** [comment]
> Plarson: Ability to add child taxa to synonymized (non-preferred) taxa
> 
> Schuchert: yes this is feature we also miss. If you have to enter obsolete names from old labels, you will have to undo the synonymy, add the child taxon and synonymize it, then synonymize the parent again. This is rather cumbersome.
> 
> HeatherC: YES, this would apply to our collection too! (being able to connect determinations to non-preferred taxa)

I believe these all concern adding children to nodes that are already synonymized, which would be rather hard to implement without more consideration (for instance, what should the child's `acceptedId` be?). 
A potential solution around this might be _forcing_ the user to select a non-synonymized node, which could be scoped to it's parent's accepted taxon's children,  to become the accepted taxon for the new child. 
Essentially, allowing the user to add a child but forcing them to synonymize it. 

Regardless, further discussion about this would be required. Any solutions from those discussions are probably outside of the scope of this issue and should be made into their own issues.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-4-announcement/999/1
