### ISSUE TITLE
WB tries to live validate rows without a plan being defined.

### ISSUE THREAD

**Issue by norinespears** [specify/specify7#755]
In Sp 7 WB test database
enter 12121212 in a date field
get a popup error that will only allow you to reload the page

![Screen Shot 2020-12-16 at 2 57 42 PM](https://user-images.githubusercontent.com/61208178/102405664-1f300700-3faf-11eb-9119-ee93c6d60bee.png)
![Screen Shot 2020-12-16 at 2 48 57 PM](https://user-images.githubusercontent.com/61208178/102405449-cb252280-3fae-11eb-8374-dd6b3579ae06.png)

**Comment by benanhalt** [comment]
This should be fixed in subsequent wb-upload-for-testing builds.
