### ISSUE TITLE
Unexpected error popup will not go away without losing my Sp 7 WB changes

### ISSUE THREAD

**Issue by norinespears** [specify/specify7#757]
related to my last bug (755)

I entered what was apparently an invalid date and received an unexpected error. The popup does not let me dismiss it but only gives me the option to 'reload' and 'previous page'. Both do the same thing - cause me to lose my changes. Are these the same thing? They both basically have the same effect. 

There should be an option to dismiss the window without losing anything.

![Screen Shot 2020-12-16 at 2 48 57 PM](https://user-images.githubusercontent.com/61208178/102406762-af228080-3fb0-11eb-8c26-d233f1b2fe2f.png)

**Comment by maxxxxxdlp** [comment]
The error window should not come up in the first place.
If it does show up, then saving changes could fail or cause even greater problems.
Maybe an option to make a copy of the Data Set and then, save changes would be best, but that is currently not implemented.
