### ISSUE TITLE
Make sure data set column headers are unique.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#758]

**Comment by benanhalt** [comment]
I think @maxxxxxdlp implemented this. It should probably be tested by importing a spreadsheet with duplicate column headers.

**Comment by maxxxxxdlp** [comment]
I already tested it extensively
Even cases like this:
```
New Header,New Header (1),New Header
```
Are handled properly:
```
New Header,New Header (1),New Header (2)
```
