### ISSUE TITLE
Support auto-incrementing values across collections.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#76]
Currently, special formatters can be applied to fields indicating that specified numeric portions of the value, when a new record is added, be set to the successor of the existing maximal value for the field with-respect-to the collection to which the record will belong. It is proposed that this function be expanded to allow incrementing with-respect-to the database _en toto_ or some broader scope than collection.

It must be determined:
- How to indicate what scope the incrementing should operate over?
- How would this affect interop with Specify 6?

**Comment by benanhalt** [comment]
Supported in Sp6 through the special autonumbering definition tables.

**Comment by timo11** [comment]
This feature is checked into branch Summer17.
It uses the Sp6 autonumberingscheme and autonumsch_XXX tables.
It works for all tables that contain divisionid, disciplineid, or collectionmemberid, not just collectionobject and accession.
It still requires 'manual' configuration of mysql tables.

**Comment by yvonneekanim** [comment]
Verified; auto numbering works as described.
