### ISSUE TITLE
Adding a Collecting Trip to a Collecting Event opens a search dialog, not a Collecting Trip subform

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#767]
seen in the Cryoarks database.  I click add to add a new collecting trip to Collecting Information, but instead of opening a subform for me to add a collecting trip, it has me search for an existing one.  This is not the way Specify 6 works with the same forms.

**Comment by benanhalt** [comment]
There is a querycbx but is not allowing new CT to be added.

**Comment by benanhalt** [comment]
Looking at Andy's database it looks like collecting trip is supposed to be embedded?

**Comment by benanhalt** [comment]
It is not supposed to be embedded. So this is a form configuration issue. The collecting trip should be in the collecting event form as a query combo box instead of a subform.
