### ISSUE TITLE
Dragging a jquery-ui dialog when the page has been scrolled down causes the dialog to jump down below the cursor, possibly below the bottom of the screen.

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#768]
Seen in the Cryoarks database.
When I click the MS button to open the Material Sample window, the screen returns to the top of the form and the Material Sample window stays at the bottom.  When you scroll to the bottom, it stays at the bottom.  If you try to grab the window and pull it up so you can see the full window, it drops further down.

**Comment by tlammer** [comment]
https://user-images.githubusercontent.com/12532430/102931710-79741080-4464-11eb-97e7-45501d40e8a1.mp4

**Comment by tlammer** [comment]
Related? https://github.com/RBGE-Herbarium/Specify_functionality/issues/15

**Comment by maxxxxxdlp** [comment]
This also seems related: https://github.com/specify/specify7/issues/569

**Comment by benanhalt** [comment]
It is this bug https://bugs.jqueryui.com/ticket/6258

**Comment by benanhalt** [comment]
I tried fixing this by updating to a newer version of jquery-ui, but that breaks a lot of other things.

**Comment by maxxxxxdlp** [comment]
Fixed on branch layout-redesign
