### ISSUE TITLE
Preferred Taxon doesn't display in query results

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify7#773]
If a record has a preferred taxon (such as in the case of a synonym), a query on the preferred taxon name doesn't appear in the query results. The data entry form does show the correct preferred taxon name

**Comment by benanhalt** [comment]
I don't understand the problem. Adding Preferred Taxon to a query returns the correct taxa. Eg the following query finds collection objects that are determined to synonymized taxa and show the synonym and the preferred:

![image](https://user-images.githubusercontent.com/287254/117043786-49226580-acd3-11eb-83c6-689bba91603f.png)

**Comment by maxxxxxdlp** [comment]
This issue is either invalid, or a duplicate of https://github.com/specify/specify7/issues/752
