### ISSUE TITLE
400 Bad Request from `/api/workbench/dataset/`

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#776]
I am receiving a 400 Bad Request response from `/api/workbench/dataset/` when uploading the following CSV datasets:
```csv
Determiner Last Name1,Determiner First Name1
1,1
```

```csv
1,1
1,1
```

```csv
1,1
```

**Comment by benanhalt** [comment]
Pretty sure it was due to the csv parser adding a line with a single empty cell at the end. I fixed that and made the API more forgiving of nonconforming rows.

**Comment by maxxxxxdlp** [comment]
Fixed
