### ISSUE TITLE
Query on pick list fields doesn't offer the pick list values

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#793]
When you add a pick list field to a query, you can't select from the possible options when adding criteria.  In Specify 6, once you add the field, if the field is read only picklist, then the field in the query displays as a pick list and you can choose one or more options from the drop down.
Mentioned by RBGE https://github.com/RBGE-Herbarium/Specify_functionality/issues/33

**Comment by norinespears** [comment]
this might be a 2-for-one with #831; related but different
this is a UI issue: when there is a field that has a pick list defined instead of giving the freeform text box it should show the pick lists

**Comment by maxxxxxdlp** [comment]
Fixed in 64875356
