### ISSUE TITLE
Prevent upload of empty upload plans

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#799]
The following upload plan was uploaded and un-unuploaded without problems:
```json
{
    "baseTableName": "accession",
    "uploadable": {
        "uploadTable": {
            "wbcols": {},
            "static": {},
            "toOne": {},
            "toMany": {}
        }
    }
}
```

But, doing so was completely pointless. We should forbid doing so or at least show some warning message so as not to confuse new users.

Also, the required filed `accessionnumber` was not mapped in this case so fixing #777 can also fix some cases of this issue.

**Comment by maxxxxxdlp** [comment]
Fixed in 44b36c7d7464514569efce63a0d4349189ae46bd

**Comment by maxxxxxdlp** [comment]
@specify/test-corps to test this, on the mapping screen, choose a base table, then press the "Clear Mappings" button and hit "Save".

Afterward, try to initiate upload/validation of a Data Set

**Comment by benanhalt** [comment]
Seems to be fixed. With no mappings the validate button is inactive and clicking on upload results in a dialog saying there is no plan.
