### ISSUE TITLE
Allow users to define grid column widths on data entry forms

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#801]
Requested by Edinburgh.  Currently, the browser resizes based on content

**Comment by norinespears** [comment]
Ben: this is not just rendering, it needs to be defined in the form which complicates the issue
also: pick lists in Sp 7 currently offers extra info. for pick lists that are not found which makes the pick list field long to accommodate and messes up the layout of the form -- should address this as well.

**Comment by benritchie** [comment]
what's the milestone for this?  is it coming in the May release?

**Comment by maxxxxxdlp** [comment]
@benritchie The way next Specify 7 release handles column definitions has changed.
The new behaviour is described here: https://github.com/specify/specify7/wiki/Form-System#column-definition

**Comment by benritchie** [comment]
thanks.  
How does this apply to grid view?  
AFAIK grids are not currently customisable, is that right?  - is that changing in this new version?

**Comment by maxxxxxdlp** [comment]
Ah, you are right. It is not explained there.
In the grid view definition, you can set colSpan for cells. That colSpan should be respected when grid is rendered

**Comment by benritchie** [comment]
thanks.  
Will check that on the new version.  (we have that in schema currently, and its having no effect, but I'm guessing it will spring into life when we upgrade :) )
Thanks

**Comment by benritchie** [comment]
Umm
I'm struggling to get this to work.  
I'm on 7.7, and have tried customising both the column widths, and also the colSpan.  neither seems to have an affect.  
Here's the relevant form snippet:

        <viewdef
            name="Determination Abridged"
            type="form"
            class="edu.ku.brc.specify.datamodel.Determination"
            gettable="edu.ku.brc.af.ui.forms.DataGetterForObj"
            settable="edu.ku.brc.af.ui.forms.DataSetterForObj">
            <desc><![CDATA[Determination subform for Collection Object form.]]></desc>
            <enableRules/>
            
            <columnDef>100px,2px,200px,2px,50px,2px,50px,2px,50px,2px,50px,2px,p:g</columnDef>
            <columnDef os="lnx">100px,2px,200px,2px,50px,2px,50px,2px,50px,2px,50px,2px,50px,2px,50px,2px,p:g</columnDef>
            <columnDef os="mac">130px,2px,260px,5px,130px,2px,238px,5px,108px,2px,150px,0px,p:g</columnDef>
            <columnDef os="exp">p,2px,p:g,5px:g,p,2px,p:g,5px:g,p,2px,p:g(2),0px</columnDef>
            <rowDef auto="true" cell="p" sep="2px"/>

            <rows>
		<row>
		    <cell type="label" labelfor="11"/>
                    <cell type="field" id="11" name="nameUsage" uitype="combobox"/>
		</row>
                <row>
                    <cell type="label" labelfor="1"/>
                    <cell type="field" id="1" name="taxon" uitype="querycbx" initialize="name=Taxon" colspan="1"/>
                   <cell type="field" id="3" name="isCurrent" uitype="checkbox"/>
                </row>
                
                <row>
                    <cell type="label" labelfor="8"/>
                    <cell type="field" id="8" name="qualifier" uitype="combobox"/>
                    
                </row>
                <row>
                    <cell type="label" labelfor="familyNumber" label="Family No."/>
                    <cell type="field" id="familyNumber" name="taxon.text11" uitype="label"/>
                    <cell type="label" labelfor="genusNumber" label="Genus No" colspan="2"/>
                    <cell type="field" id="genusNumber" name="taxon.text12" uitype="label" colspan="2"/>
                </row>

As you can see, there should be a variation in column widths - family number should span 2 cols, and taxon should be teice the width of name usage.  
Actual UI doesn't obey that though:
everything seems to be the same width:
![image](https://user-images.githubusercontent.com/8005676/179790988-dfe19e32-8a73-4078-aacb-18ffa6b87591.png)

**Comment by benritchie** [comment]
any ideas?

**Comment by benritchie** [comment]
Have tried setting a colspan to 5 on the first element (nameusage).  
Made no difference.  
If you want to see the issue - feel free to access our instance - its sandbox-rbge

**Comment by maxxxxxdlp** [comment]
Just tried this again. Was able to visibly increase the column size by increasing the colspan to `40`

Since there is no limit to total colspan, this should give you a flexible way to adjust columns sizes.

The reason colspan in FormTable does not act like it normally does is because column sizes are determined dynamically. While it does have an undesired effect in this case, most of the time flexible column sizes are preferred, as it removes the need for manually adjusting column sizes.

Please try this solution and tell us if it satisfies the use case.

**Comment by benritchie** [comment]
When you say dynamically, what's that based on?  - it would be great to see a quick writeup on how grid layouts are laid out added to the forms docs.  Is that possible?

Dynamic sizing would be great - but currently its resulting in some columns with loads of excess space, and others truncating.  - I'm guessing its not dynamic based on the actual data, but something else?

e.g. this.
***@***.***

Thanks

**Comment by maxxxxxdlp** [comment]
@benritchie What browser are you using?

I am unable to replicate the issue with field not growing. Tested in the latest Chrome, Firefox and Safari on macOS

<img width="1033" alt="Screen Shot 2022-07-22 at 19 50 00" src="https://user-images.githubusercontent.com/40512816/180584252-ccff2ada-7d25-4a32-b894-896b29d22b47.png">
<img width="1033" alt="Screen Shot 2022-07-22 at 19 48 49" src="https://user-images.githubusercontent.com/40512816/180584254-b223fe08-6411-4011-bded-2d82b8a74acc.png">
<img width="1033" alt="Screen Shot 2022-07-22 at 19 47 32" src="https://user-images.githubusercontent.com/40512816/180584255-3d292dbd-0bb7-4a32-8fa8-c9fe8c8c25e5.png">
<img width="1033" alt="Screen Shot 2022-07-22 at 19 46 09" src="https://user-images.githubusercontent.com/40512816/180584256-400d288b-76f2-442d-a417-8bc5ba7ba6d8.png">

**Comment by maxxxxxdlp** [comment]
Also, I think that a better long-term solution would be to fix our automatic column sizing algorithm to make manual adjustments unnecessary - https://github.com/specify/specify7/issues/1885

**Comment by benritchie** [comment]
I think the issue is specific to querycbx's
I've just set both family no. and taxon to have a colspan of 100.  as you can see - taxon (the querycbx) is broken, family no is fine.  
![image](https://user-images.githubusercontent.com/8005676/181517540-c87c44d9-fa77-4d71-b0c5-91b611972805.png)

**Comment by maxxxxxdlp** [comment]
@benritchie A better way to customize table column widths have been added. You don't have to use the `colspan` hack anymore.

See https://github.com/specify/specify7/issues/2008

It is not available in the `edge` build

**Comment by grantfitzsimmons** [comment]
It is *now available :smile: @benritchie
