### ISSUE TITLE
Loan defaults from preferences not getting set in forms

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#806]
In 6, you can set a preference for different fields in loans and the defaults are set in the loan form whenever you create a loan.  7 is not doing that.

**Comment by maxxxxxdlp** [comment]
We agreed to implement this using default values for form fields.
For the "due in x months" field, you can set default value as a relative date, like this:  https://github.com/specify/specify7/wiki/Form-System#:~:text=For%20date%20fields%2C%20can%20set%20this%20to%20today%20to%20initialize%20the%20field
