### ISSUE TITLE
Send notification to recipient user on data set transfers.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#807]
The notification should probably include:
name of data set (which is a link to the data set)
who sent it
timestamp

**Comment by maxxxxxdlp** [comment]
This is how the notification looks like:

<img width="926" alt="Screen Shot 2021-06-03 at 9 11 13 PM" src="https://user-images.githubusercontent.com/40512816/120692296-44a6c380-c4b0-11eb-9d49-85abf32940e7.png">
