### ISSUE TITLE
Upload Plan not Defined error when trying to use existing plan

### ISSUE THREAD

**Issue by norinespears** [specify/specify7#813]
I'm using the demo database version of the Workbench using the Ichthyology collection

Here are my steps: 
Click WorkBench
Click Ichthyology DataSet
the Data Set opens with a dialog that says there is no plan
I choose 'Create' in that dialog
I am presented with a window with what I assume are the DataSet fields but no prompt for what to do next
I see 'Choose Existing Plan' and click it:
![Screen Shot 2021-05-03 at 11 28 20 AM](https://user-images.githubusercontent.com/61208178/116904066-dc3f9a80-ac02-11eb-8ab8-d6c0c3f9a127.png)

I get this error window:
![Screen Shot 2021-05-03 at 11 25 05 AM](https://user-images.githubusercontent.com/61208178/116904052-d649b980-ac02-11eb-9c16-ee82581d9ac6.png)

**Comment by maxxxxxdlp** [comment]
Issue was fixed on the `wb-upload-for-testing` branch. I rebased `api-schema` of it so this bug should be fixed on the server too
