### ISSUE TITLE
Update UI for adding a user 

### ISSUE THREAD

**Issue by norinespears** [specify/specify7#814]
the UI should walk the user through the steps and then give confirmation when and if they are successful - as well as notices when they are not.

**Comment by maxxxxxdlp** [comment]
Fixed in 7f4fb84a and b2c6e051

**Comment by grantfitzsimmons** [comment]
I think that validating that a user has a password (or at least asking if the account creator wishes to give it one) is a good idea before saving.

**Comment by maxxxxxdlp** [comment]
That's what it does right now
If you try to save new user and forgot to assign a password, it will prompt you

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp I have bad news...
