### ISSUE TITLE
No error message on request for a non-existent resource

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#815]
Trying to view a non-existing resource (http://localhost/specify/view/someUnknownResoruce/107/) doesn't show a proper 404 message. The user only sees a blank screen (even though there is an exception in the console)

**Comment by maxxxxxdlp** [comment]
@benanhalt can you double check that I fixed this correctly? `resourceView` is a very important function so I don't want to break it :joy:

**Comment by benanhalt** [comment]
@maxxxxxdlp Looks fine to me.
