### ISSUE TITLE
Add indication that collection has been chosen in the dialog

### ISSUE THREAD

**Issue by norinespears** [specify/specify7#816]
in the api.test.specifycloud database
Manage User
Choose a user
select the collection button
in the next dialog a list of collections is available and I can click on one I have actually chosen it and it is associated but there is no indication that anything has happened. Can we change the dialog to check boxes?
![Screen Shot 2021-05-03 at 1 11 10 PM](https://user-images.githubusercontent.com/61208178/116927861-ddcc8b00-ac21-11eb-9859-d59527bbd01c.png)

**Comment by maxxxxxdlp** [comment]
Hmm, I am not sure whether it is supposed to be that way, but opening this menu and pressing `Save` without making any changes seemed to revoke the admin rights for my user. E.x the `Manage User` menu item is missing and now I get `You lack sufficient privileges for that action` whenever I press the `Collection` button again.
@benanhalt is that supposed to happen? Or is that a known bug?

**Comment by benanhalt** [comment]
@maxxxxxdlp I just tried it and the Save button is disabled unless I change something... But yeah it shouldn't take away admin rights unless you explicitly click "remove admin" or change the user type to something other than Manager.

**Comment by norinespears** [comment]
I was able to do this too (think it relates to a different issue) i.e. 
I'm logged in as an admin user
create a new user
click 'Collection'
the Save button looks disabled but when I mouse-over it I can click on it and save without selecting a collection
I log out of the admin user
I try to login as the new user but there is no collection associated and I get the 'there is no collection associated with this user' dialog

**Comment by benanhalt** [comment]
Oh, I see. The save button in the collection selection menu.

**Comment by maxxxxxdlp** [comment]
The original issue is now fixed and confirmed working
The related bug is described in detail in #833
