### ISSUE TITLE
new user not associated with default collection

### ISSUE THREAD

**Issue by norinespears** [specify/specify7#817]
Logged into the WB demo Specify database:
api.test.speifycloud.org
created a new user
filled out all criteria except for the collection
when I tried to login I got this message:
![Screen Shot 2021-05-03 at 1 08 45 PM](https://user-images.githubusercontent.com/61208178/116927942-fccb1d00-ac21-11eb-9925-d64823e84210.png)

**Comment by maxxxxxdlp** [comment]
Fixed.
When creating a new user from the Collection page in the security preferences, the "Collection Access" checkbox for that collection would be automatically checked
