### ISSUE TITLE
Validating a Data Set without a plan gives Unexpected Error

### ISSUE THREAD

**Issue by norinespears** [specify/specify7#818]
I'm using the demo database at api.test.speifycloud.org and logged in as demouser
In the Ichthyology collection I load the ichthyology Data Set
It opens and I click on 'Validate' 
I get this error:

![Screen Shot 2021-05-03 at 3 57 06 PM](https://user-images.githubusercontent.com/61208178/116932926-81b93500-ac28-11eb-9c57-869507c176ad.png)

**Comment by benanhalt** [comment]
I get this modal dialog if I try that:

![image](https://user-images.githubusercontent.com/287254/116940689-eaf27580-ac33-11eb-9fc1-6a235b10b0ff.png)
