### ISSUE TITLE
Clicking 'Show Plan' when none is defined requires UI

### ISSUE THREAD

**Issue by norinespears** [specify/specify7#819]
I'm using the demo database at api.test.speifycloud.org and logged in as demouser

I choose a Data Set but do not create an upload plan. The 'Show Plan' button is still active and when I click on it I am given a dialog with null value.

![Screen Shot 2021-05-03 at 4 00 36 PM](https://user-images.githubusercontent.com/61208178/116933363-10c64d00-ac29-11eb-8c31-abfe722df663.png)

Can we check for a plan and inactivate the button if one does not exist?

**Comment by maxxxxxdlp** [comment]
`Show Plan` menu would be removed in the production version

**Comment by norinespears** [comment]
Is the demo version not the latest?

**Comment by maxxxxxdlp** [comment]
The latest version is still a development version.
The `Show Plan` menu is useful for development but we decided not to expose the upload plan anywhere in the UI for production version.

**Comment by norinespears** [comment]
Thanks for explaining!!
