### ISSUE TITLE
Users would like to bulk assign Collection Objects to a Reference Work

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#82]
Users have noted that there may be several CO's referenced in an article or book.  They would like to be able to bulk assign the CO's to the reference work instead of assigning the reference work to the CO's one at a time.

**Comment by maxxxxxdlp** [comment]
Already possible though the WB if creating new COs. Will be possible though WB if restriction on base table records being new is lifted.

If Reference work is new, might be possible to pick it as a base table, and then link to COs as related table using Catalog Number

Will be possible through the first iteration of the Batch Editor

**Comment by grantfitzsimmons** [comment]
The WorkBench does what this issue is looking to do.
