### ISSUE TITLE
Clicking 'Validate' while Toolkit is open causes error

### ISSUE THREAD

**Issue by norinespears** [specify/specify7#820]
I'm using the demo database at api.test.speifycloud.org and logged in as demouser
Entomology database and Data Set
upload the Data Set
Create the Data Set plan
Both the Data Set plan and the Data Set have been saved
Open the Toolkit
while the Toolkit is open click on 'Validate' 
this dialog appears:

![Screen Shot 2021-05-03 at 4 14 38 PM](https://user-images.githubusercontent.com/61208178/116934774-0311c700-ac2b-11eb-9d9e-faef9aeb4217.png)

**Comment by benanhalt** [comment]
This isn't happening for me. That is a weird error message though. Let me know if it happens again.
