### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by kantobogy** [specify/specify7#823]
Hello,
Ubuntu 18.04

After execute> specify7/ve/bin/pip install -r specify7/requirements.txt

---
 error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for mysqlclient
  Running setup.py clean for mysqlclient
  Running setup.py bdist_wheel for SQLAlchemy ... error
  Complete output from command /home/salvador_vivar/specify7/ve/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-cvku8179/SQLAlchemy/setup.py';f=getattr(tokenize, 'open', 
open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpc2lzx2qepip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for SQLAlchemy
  Running setup.py clean for SQLAlchemy
  Running setup.py bdist_wheel for python-ldap ... error
  Complete output from command /home/salvador_vivar/specify7/ve/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-cvku8179/python-ldap/setup.py';f=getattr(tokenize, 'open',
 open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpmc_zo3m7pip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for python-ldap
  Running setup.py clean for python-ldap
Failed to build mysqlclient SQLAlchemy python-ldap
Installing collected packages: sqlparse, pytz, Django, mysqlclient, SQLAlchemy, requests, pycryptodome, pyasn1, pyasn1-modules, python-ldap, pyldap, django-auth-ldap
  Running setup.py install for mysqlclient ... done
  Running setup.py install for SQLAlchemy ... done
  Running setup.py install for python-ldap ... done
Successfully installed Django-2.2.10 SQLAlchemy-1.2.11 django-auth-ldap-1.2.15 mysqlclient-1.3.13 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycryptodome-3.9.7 pyldap-3.0.0.post1 python-ldap-3.3.1 pytz-202
1.1 requests-2.2.1 sqlparse-0.4.1
---

Afete execute> make build
npm install
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.13

Afeter execute make frontend
npm install
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.13

---

Afeter execute > make django_migrations
(.venv) salvador_vivar@sp7bioecuador:~/specify7$ make django_migrations
make: *** No rule to make target 'python_prep', needed by 'django_migrations'.  Stop.

Thanks in advance

**Comment by maxxxxxdlp** [comment]
You are probably missing some dependencies
If you are still getting this error, try using our docker build instead - https://github.com/specify/specify7#installation-with-docker
