### ISSUE TITLE
Add easy way to enter special characters

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#825]
RBGE reported there is no easy way to enter special characters.  They've tried using shortcuts but it didn't work.  The only way they've gotten it to work is copy paste.

**Comment by beach53** [comment]
Is this a keyboard issue? Making sure the keyboard is localized for a particular language?  I thought as a UNICODE app, Specify could handle any character given the right input.  Does it also depend on any other system settings?  ÆñÑ, etc on Windows are ALT-numeric keypad codes  ALT-130 é  with the United States keyboard

впк-китвйукмбпкззшбюмкщьФЗЛЬПЛЗ   <<<---  Windows Russian keyboard  Works in 6 and 7.

Can you give examples of the particular special characters they cannot enter?  And Windows or Mac or Web?

**Comment by maxxxxxdlp** [comment]
@tlammer can you give an update on this issue?

**Comment by maxxxxxdlp** [comment]
Added a tool for entering special characters.
It works with all inputs, textareas and even with the workbench.
Once opened, the dialog stays open as you navigate between the pages.
Also, it remembers the category of characters you opened last time and automatically reopens it again.
The dialog can also be used though keyboard alone, though there should probably be a shortcut for opening the dialog without the need for mouse clicks.

For testing:
Test with different types of inputs: remarks, numbers, dates, as well as a workbench
Make sure that the tool does not overwrite any existing selected characters in the field (it should append new characters after the selected region)

**Comment by maxxxxxdlp** [comment]
Here is a demo:

https://user-images.githubusercontent.com/40512816/126225350-0fd09a10-59c5-4f3e-ade3-2c6e57a56734.mov

**Comment by tlammer** [comment]
ooohhh, it stays on screen until you close it.  and you can continue to use it.  nice

**Comment by maxxxxxdlp** [comment]
Windows 10 already has a "Character Map" installed. It allows drag and drop of one character at a time or copy & pasting the whole string. Drag & Drop works with the Workbench too.

There also is an updated version with more customization options - https://microsoft.com/en-us/p/character-map-uwp/9wzdncrdxf41. It does not support drag and drop, but copy & paste works fine.

macOS also has a "Character Viewer", but it is quite hidden:

https://user-images.githubusercontent.com/40512816/126510439-bc74edee-fe5a-4539-8c7f-e3e7ab999f1a.mp4

Other than then, I found it to be very intuitive and convenient.

**Comment by maxxxxxdlp** [comment]
For future reference:
A dialog for entering special characters is available on the `special-characters` branch, but we decided not to merge it into production as operating systems already have a tool for this purpose, which also removes our need to maintain yet another component.
