### ISSUE TITLE
Can't create an empty loan record

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#826]
Reported by RBGE.  In 6, you can create a blank loan record by selecting the Uncataloged Items option or Loans w/o Preps (if there won't be any cataloged items at all).  7 requires a CO be attached in order to start:

https://github.com/RBGE-Herbarium/Specify_functionality/issues/38

**Comment by norinespears** [comment]
Perhaps this should be more comprehensive and Interactions updated to offer the same capabilities as Sp 6.

**Comment by maxxxxxdlp** [comment]
There is a "Without Preparations" button there:

https://user-images.githubusercontent.com/40512816/125703208-669c1cdb-bea2-44a9-b354-17c1379ccfec.mov


[Added in 2018](08abe556b8487285cefeff7d6a50340365b61826)
