### ISSUE TITLE
Cannot search for partial values in taxon query comboboxes

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#83]
If I enter a portion of the taxon name, it does not find the value.  It will not find the value until I enter the full name.
In the accession query combobox, it cannot find the value until you enter the first phrase.  For example, there is an accession with the number "2015-AA-AAA".  It will not find "20" but it will find "2015"

**Comment by yvonneekanim** [comment]
Tested in testinvp.  Partial values return results.
