### ISSUE TITLE
Date fields do not automatically add separators

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#830]
Requested by RBGE
Date fields do not automatically add slashes between date sections in date formatted fields.
Specify 6 formatted date fields add the slash

**Comment by tlammer** [comment]
https://github.com/RBGE-Herbarium/Specify_functionality/issues/8

**Comment by norinespears** [comment]
Needs research for how we want this to work. What are the requirements?
Ben: Can put in the separator based on the format.
How does paste work if there are separators already in the date?

**Comment by beach53** [comment]
Handle Roman numerals?  23 XII 1988

**Comment by norinespears** [comment]
a separate ticket might be created in the future to update the capabilities of dates in the UI

**Comment by maxxxxxdlp** [comment]
Fixed. Ready for testing.

Now it uses the native date picker and reverts to old textbox only if the browser does not support the date pickers.

This should not interfere with pasting. Pasting is also supported, but only if pasting whole and well-formatted date at once (e.x `10/10/2020` or `1111-11-11`). The value you are pasting must be properly formatted and values like `10111213` are not supported. (There is no point in trying to guess whether `10111213` means `1011/12/13` or `10/11/1213`).

**Comment by maxxxxxdlp** [comment]
The issue of the browser's date format not matching the database's format was partially fixed by showing the database format in a tooltip on mouseover.

**Comment by maxxxxxdlp** [comment]
This was merged into branch `a11y`

**Comment by grantfitzsimmons** [comment]
![r7cYtN0Z9y](https://user-images.githubusercontent.com/37256050/145095235-b655f1b7-6d67-495c-bb3e-d10fe3be56b7.gif)
Here is me simply typing '11192000' continuously. Copy & paste works with properly formatted dates just fine however (11/19/2000). This definitely needs some improvement.

Somehow pressing 2 defaults to 1992, then the following 0 sends the date to the year 1.

> Handle Roman numerals? 23 XII 1988 LMIXVIII

_It does not handle Roman numerals._

**Comment by grantfitzsimmons** [comment]
The dates in Sp7 no longer autofill dates like in previous versions in this branch. (E.g. Accessioned date, accession received)

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/146078427-0d95ddb3-7b1b-4984-816f-a42e3353cb18.png)

You cannot paste formatted dates into the Borrow table. CO table works just fine, but their seems to be inconsistencies with how the date entry fields are working.
