### ISSUE TITLE
System pick lists are showing the value not the title in query results

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#831]
Pick lists such as Reference work type and agent type are displaying the value for the pick list, which in these instances are numbers, rather than the title, which is what is displayed on the form.
Further, you cannot edit the values in these pick lists without causing further, significant issues.

**Comment by benanhalt** [comment]
I'm not sure if this affects all picklists or just the ones mentioned. Either way it is probably not too difficult to fix. But it would need testing to be sure new bugs weren't introduced.

**Comment by norinespears** [comment]
Need to research:
does this affect all Pick Lists?
are these supported in Queries?

**Comment by maxxxxxdlp** [comment]
Does not happen for Agent Type for me:

![Screen Shot 2021-07-12 at 6 45 39 PM](https://user-images.githubusercontent.com/40512816/125320843-c4903b00-e344-11eb-90f0-f1a0c4db665a.png)


Though, it seems like the back end returns Agent Type as a title, but Reference Work as an ID:

![Screen Shot 2021-07-12 at 6 54 42 PM](https://user-images.githubusercontent.com/40512816/125321014-f30e1600-e344-11eb-9ac9-a3060af41f7a.png)
![Screen Shot 2021-07-12 at 6 54 50 PM](https://user-images.githubusercontent.com/40512816/125321022-f4d7d980-e344-11eb-824b-b0f03c0468d6.png)

@benanhalt Is value to title conversion supposed to happen on the back end or the front end?

**Comment by maxxxxxdlp** [comment]
Similar issue:

The filtering box expects a number (picklist item id), not a string (picklist item label)

https://user-images.githubusercontent.com/40512816/125321570-80516a80-e345-11eb-8257-5e71f6d48db0.mov

**Comment by grantfitzsimmons** [comment]
![image (2)](https://user-images.githubusercontent.com/37256050/149961184-fbf8d7be-23cc-4c2a-8dc0-e04f1c0c02a5.png)

I had the same issue again. Tipus is showing its value in the database rather than its title (Book, Report, etc).

**Comment by maxxxxxdlp** [comment]
Fixed in 9fd65729
