### ISSUE TITLE
Open CO's associated with a node on a taxon tree (from the taxon tree) in form view

### ISSUE THREAD

**Issue by norinespears** [specify/specify7#834]
The current UI offers a link to a query that the user can then run. The expected behaviour would be for the associated collection objects to open in form view (run the query in the background and present the returned CO's in the CO form). 
Specify 7:
![Screen Shot 2021-06-03 at 12 15 56 PM](https://user-images.githubusercontent.com/61208178/120685600-9f66fd80-c465-11eb-81d8-042cfbe1e9bc.png)
Specify 6:
<img width="265" alt="Screen Shot 2021-06-03 at 12 25 33 PM" src="https://user-images.githubusercontent.com/61208178/120686719-e5709100-c466-11eb-9c71-4a148c23497d.png">

**Comment by benanhalt** [comment]
This should be done by adding the ability to see query results in form view. Then just do that automatically when this option is selected.

**Comment by norinespears** [comment]
Superset of this: going through queries in a form view
Ben: doing both is even better

**Comment by maxxxxxdlp** [comment]
Partially fixed this by automatically running the query and scrolling down to the results section.

Is the desired behavior still for the query to open immediately in the "Browse in Forms" mode? That would be a bit more difficult

**Comment by grantfitzsimmons** [comment]
I think the current solution is just fine. Please reopen this issue if this specific functionality is desired, but you can currently:

1. Click on a node in the tree viewer
2. Click **Query**
3. View the query results in a form view by using the **Browse In Forms** option
