### ISSUE TITLE
Clear any page unload protection when an unhandled server error occurs.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#836]
So that the user doesn't get a spurious "Are you sure?" dialog when selecting reload or previous page from the error dialog.

**Comment by maxxxxxdlp** [comment]
Fixed in bd1b753c

**Comment by benanhalt** [comment]
I tested this by opening a CO form. Attempting to navigate away triggers the unload protection dialog. But after rigging the server to produce an exception, no unload protection dialog appears when leaving the page after the exception dialog has been displayed.
