### ISSUE TITLE
Add ability to augment record sets

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#840]
Currently the only way to add to record set is one at a time by selecting save and add another when you are working in the record set.  It would be helpful if users could add to a record set either by adding query results to an existing record set and/or combining record sets.

**Comment by benritchie** [comment]
As far as I can see - even the above doesn't work as a workaround.  - the "save and add another" only works if you want to add a new item to the catalog and record set.  It doesn't seem to enable adding an existing item in the DB to the record set, so it appears there's no way to do this.  I think adding that ability in is key to making Record Sets usable on 7.

**Comment by maxxxxxdlp** [comment]
Added ability to add exising record to a record set (using search or query builder)
Added ability to remove a single record from a record set
Added ability to go to first, last, or nth record set item
