### ISSUE TITLE
Unable to disambiguate CoA records

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#846]
I suspect that this issue is database-specific, but even if it is, there is no way to deal with it on the user's end:

A column that belongs to the "Collectiion Attribute" table had ambiguous values. Disambiguation dialog does not format the records properly:

![Screen Shot 2021-06-13 at 1 18 04 PM](https://user-images.githubusercontent.com/40512816/121803383-f29d3500-cc49-11eb-89a2-cd4a6c230fd7.png)

I also can't see the data in the form view:

![Screen Shot 2021-06-13 at 1 18 02 PM](https://user-images.githubusercontent.com/40512816/121803400-1496b780-cc4a-11eb-8886-71c8ea15864d.png)

**Comment by maxxxxxdlp** [comment]
Is adding more columns (to solve the ambiguousness) the only sensible solution in this case? If so, the disambiguation dialog should say that this is an option, instead of showing null values.

**Comment by benanhalt** [comment]
COA shouldn't be shared by COs so this shouldn't be a problem. There is supposed to be a mechanism in the uploader that handles that but it seems like something isn't working. I'll take a look.

**Comment by benanhalt** [comment]
I haven't been able to reproduce this. Do you still have the data set and mapping?

**Comment by maxxxxxdlp** [comment]
I don't remember the mapping anymore (at a time I thought this was a generic issue and so did not attach it here).

Here is the dataset, though, it is not very useful without the mapping:
[7000_CO.csv](https://github.com/specify/specify7/files/6695335/7000_CO.csv)

I am not able to reproduce this either so would close the issue for now.

**Comment by benanhalt** [comment]
This is a bit tricky. You are only going to see the MatchedMultiple COAs when there is error that stops the CO from being uploaded. It's actually correct that the COA matched multiple records, it just doesn't usually care because it is a one-to-one relationship and if it has to upload the CO it is going to upload a new COA.

I'm not sure the best way to fix this. Basically the MatchedMultiple should be ignored on one-to-one relationships but there isn't any easy way to know on the frontend which relationships those are. I could maybe add an "ignore" field to the MatchedMultiple result in those cases. Or I might be able to suppress them altogether so there would just be no UploadResult for the COA in this case.

**Comment by maxxxxxdlp** [comment]
If you can't easily add the "ignore" field on the back end, I have a utility function to get a relationship type from the mapping path

**Comment by maxxxxxdlp** [comment]
Or, maybe I should just check if the form is defined for that table? (e.x, no form is defined from CoA)

**Comment by benanhalt** [comment]
I pushed a change that just removes the MatchedMultiple result when it doesn't matter. I think that will solve the problem without you having to change anything.

**Comment by maxxxxxdlp** [comment]
Thanks. To test this, I should just create multiple identical CoA records and make sure I don't see any front-end errors?

**Comment by benanhalt** [comment]
There has to be some other problem that stops the CO from uploading. Otherwise the bug doesn't manifest.

**Comment by benanhalt** [comment]
It would also be good to check that after correcting the "other" problem with the CO that the COA does get uploaded by doing an actual upload and checking the result.

**Comment by maxxxxxdlp** [comment]
Seems to work fine now:

![Screen Shot 2021-08-06 at 12 40 50 PM](https://user-images.githubusercontent.com/40512816/128492653-f3956500-6495-425a-9bbf-f2bd4621c8cb.png)
![Screen Shot 2021-08-06 at 12 40 53 PM](https://user-images.githubusercontent.com/40512816/128492657-3828c40d-be12-4989-94fe-3607924bc865.png)

After fixing the disambiguation errors:
![Screen Shot 2021-08-06 at 12 53 30 PM](https://user-images.githubusercontent.com/40512816/128492974-9e46d0e9-9409-4f2d-9f33-f44028fd5a36.png)

**Comment by realVinayak** [comment]
This has been handled more gracefully now in https://github.com/specify/specify7/pull/4929. Processing one-to-ones and then handing MatchedMultiple was awkward. We don't need to "process" one-to-ones. I included them as part of matching process (as a query predicates). that way, we never have the MatchedMultiple errors
