### ISSUE TITLE
Hide root tree ranks

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#848]
I don't know if this was discussed before, but can we hide the root tree ranks? (Site/Earth/Life). I think Specify 6 might be doing this too.

There is ever only one node in the root rank, so showing it seems useless:
<img width="1479" alt="Screen Shot 2021-06-16 at 8 30 29 PM" src="https://user-images.githubusercontent.com/40512816/122265850-d4e9fd00-cee1-11eb-80ff-a22cf118e85b.png">

Also, you can't even make any changes to the root ranks (e.x add remarks) because the required field "Parent" is missing:
<img width="1479" alt="Screen Shot 2021-06-16 at 8 30 16 PM" src="https://user-images.githubusercontent.com/40512816/122265938-eaf7bd80-cee1-11eb-84ac-15350cf7d2e9.png">

**Comment by maxxxxxdlp** [comment]
Tries making parent field not required for root tree rank, but back-end through an exception, thus there is no way at all to edit root tree ranks, and thus they should be hidden.

**Comment by maxxxxxdlp** [comment]
The difficulty with this is that tree structure does not enforce a rule that tree's must have only one root node.
Hiding the root tree level only if there is only one root seems too complicated

**Comment by grantfitzsimmons** [comment]
>The difficulty with this is that tree structure does not enforce a rule that tree's must have only one root node.
>Hiding the root tree level only if there is only one root seems too complicated

I think we should close this issue as it is more of a non-issue that would only introduce bugs if added IMO
I am happy to reopen if someone feels it is necessary

**Comment by maxxxxxdlp** [comment]
Agree.
I still think this would be great from the UX perspective, but the fact that we don't enforce single tree root strictly enough adds complexity and makes this impractical
