### ISSUE TITLE
Standardize page styles across the appplication

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#856]
Develop a common spreadsheet / Use a library like Tailwind

**Comment by maxxxxxdlp** [comment]
Make sure all components use the same font size, font family and font-weight (especially in the header), unless needed to be otherwise.

**Comment by maxxxxxdlp** [comment]
Disabled buttons should have proper styles (no tabindex, not focusable, no hover/active effect, and the css `cursor` should be `not-allowed` instead of `pointer`)

**Comment by maxxxxxdlp** [comment]
Fixed by refactoring all front-end files to use Tailwind styles

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/168139107-357f9da9-8997-4d06-abb9-e99a809010e1.png)

I can use tab to navigate to "date edited"
