### ISSUE TITLE
Embedded collecting events are not deleted when the embedding collection object is.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#86]
This actually happens for all dependent foreign key relationships.

**Comment by benanhalt** [comment]
Test by creating collection objects with collecting event in some database with embedded collecting events. When the collection object is deleted, the collecting event should also be deleted. It will probably be necessary for #87 to be fixed in order to find any collecting events that are not being deleted.

**Comment by benanhalt** [comment]
Also, this affects lots of things related to deleting and removing dependent items. So those sorts of operations should be tested generally.

**Comment by benanhalt** [comment]
For testing, you can find collecting events with no collection objects using a query like:

CE -> GUID -> (any)
CE -> Collection Objects -> Timestamp Modified -> Empty

**Comment by benanhalt** [comment]
Check if it is working for embedded paleocontext.

**Comment by garrettgirard** [comment]
I tested this for embedded collecting events and embedded paleocontext. It fixed the embedded collecting events, those are now deleted with the Collection Object. However, embedded paleocontext is still not getting deleted when the CO is deleted.

**Comment by benanhalt** [comment]
Closing this in favor of #148 since this bug originally referenced only collecting events.

**Comment by benanhalt** [comment]
see also #32
