### ISSUE TITLE
WB validation fails with "OperationalError"

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#860]
Happened during validation of the 18k rows dataset when the progress bar reached 100%

![Screen Shot 2021-06-25 at 8 54 56 PM](https://user-images.githubusercontent.com/40512816/123466274-d1e4c000-d5f7-11eb-8cf6-7719d59a0acd.png)

**Comment by benanhalt** [comment]
Add `command: --max_allowed_packet=1073741824` to the mysql/mariadb service in your docker-compose.yml

**Comment by maxxxxxdlp** [comment]
That worked. Thanks
