### ISSUE TITLE
Unable to disambiguate when parent field is ambiguous

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#862]
If the table the current column belongs to is not the same as the table that caused the ambiguousness error, the front-end gets confused and tries to disambiguate the wrong table.

Example:
In cases where a column is mapped to `Locality > Geography > Country > Name`, and the validator marks the Locality record as ambiguous, the front-end incorrectly tries to disambiguate the `Geography` table.

**Comment by maxxxxxdlp** [comment]
Instructions for testing:
1. Choose Locality as a base table
1. Map a column to `Locality > Geography > Country > Name`
1. Put a value into that column such that it produces ambiguous matches (you can create several identically named countries 
in the database to archive that)
1. Run Validation
1. Right-click on any ambiguous cell and run disambiguation on it
1. Repeat step 5, but press "Apply All", instead of "Apply"
1. Repeat steps 4 and 5, but use Data check instead of validation

**Comment by beach53** [comment]
This appears to work, the DS responds  appropriately, but I do not know what an error condition woudl look like.  What would be observable evidence for it not working?

**Comment by maxxxxxdlp** [comment]
Before the bug fix the disambiguation dialog would close and the error message would not go away as disambiguation was applied to a wrong table
