### ISSUE TITLE
`ParseFailures` tuple returns results in the wrong order

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#863]
The schema says that ParseFailures would be returned as an array of tuples `(columnName, message)`:

https://github.com/specify/specify7/blob/20c4e62a97c19a5d0e97ef2c0ac2ad3dd19b400d/specifyweb/workbench/upload/upload_results_schema.py#L77-L80

Yet the actual response is `(message, columnName)` (reversed)

Seems like the issue can be fixed by reordering these two lines:
https://github.com/specify/specify7/blob/20c4e62a97c19a5d0e97ef2c0ac2ad3dd19b400d/specifyweb/workbench/upload/parsing.py#L29-L30 (though that may break the tests)

**Comment by maxxxxxdlp** [comment]
For now I pushed 59d72a03 as a workaround. @benanhalt please revert that commit when this issue is fixed.

**Comment by benanhalt** [comment]
Wouldn't it make more sense to fix the schema description?

**Comment by maxxxxxdlp** [comment]
I guess we can. It just seems confusing to have the message before the column name
