### ISSUE TITLE
Exception when adding child to tree node if dialog is closed before request completes.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#876]
In the tree view, right click on a node and select "add child". Fill in the form in the dialog, save and immediately close the dialog using the X. The following exception occurs and the tree view doesn't update though the new node is saved.

![image](https://user-images.githubusercontent.com/287254/125531417-65774b60-9040-4b47-a98f-f08fad478101.png)

**Comment by benanhalt** [comment]
I think this is related to the fix for #312

**Comment by maxxxxxdlp** [comment]
Reproducible only on slow servers :joy:

Seems to happen for "Edit" dialog too and was probably an issue even before the fix for #312.

I made it check if dialog exists before changing the title.

@benanhalt Should I instead forbid closing the dialog while saving/deleting is in progress?

**Comment by benanhalt** [comment]
Nah, I think we should be optimistic that the request will succeed. The generic error handler will catch any failed request in either case.
