### ISSUE TITLE
Data set name change weirdness.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#878]
Changing the name of a data set behaves weirdly.

https://user-images.githubusercontent.com/287254/125658946-c2586f2e-6a8c-4bd9-9f9a-ac60772f690e.mp4

**Comment by maxxxxxdlp** [comment]
Uhh, I though I fixed this

**Comment by benanhalt** [comment]
Also happens in the data set view page:

https://user-images.githubusercontent.com/287254/125659273-ed105ace-3edd-4f6f-a866-8fd5f2e5eff6.mp4

**Comment by maxxxxxdlp** [comment]
That's actually two separate issues. Though both should be fixed now

**Comment by benanhalt** [comment]
cfa683a3a7e0ade26179ad55f531b6bb43da4174 and c104e4e2da6d195ed410cc1ab25acbdd333959e9?

**Comment by maxxxxxdlp** [comment]
Yes.

-- (Forgot to tag the issue)

**Comment by benanhalt** [comment]
Looks good now.
