### ISSUE TITLE
Allow the first column in a dataset to be locked

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#886]
Requested by the canadian national seed herbarium.  The anticipated use case is to have the unique identifier in the first column then they can scroll across their dataset and still keep track of the identifier.

**Comment by tlammer** [comment]
Use case provided by Heather Cole: Thanks for the quick reply, my major use-case is when I am cleaning up the data in the Workbench (eg. weird coordinates or strange species-name), and need to search an image to verify the label info, so need to access the identify to locate the image for reference.

**Comment by maxxxxxdlp** [comment]
Just move the columns in the data set after upload so that the columns you need are both visible

To move a column, click on the header, and drag left or right
