### ISSUE TITLE
Search button on the `Set Agents` form does not work

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#887]
The search button on the `Set User Agents` form (when editing a user) throws an exception when clicked

Seems to happen because `this.populateForm` is undefined on this line: https://github.com/specify/specify7/blob/1d1d8516b60fc17bbc79c25bc7021306767792f4/specifyweb/frontend/js_src/lib/useragentsplugin.js#L115

**Comment by maxxxxxdlp** [comment]
@benanhalt is there a reason why the reference to `populateform.js` is passed around between a lot of backbone views?

Is it because of circular dependency issues?

**Comment by benanhalt** [comment]
Yeah. I think it is because populateform is going around attaching Views to elements some of which are subforms that need to call populateform again. I don't remember exactly.

**Comment by maxxxxxdlp** [comment]
Fixed in next release
