### ISSUE TITLE
Prevent automapper from creating roundabout mappings

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#888]
Don't automap if the mapping path contains base table twice (E.x, if Collection Object is a base table, don't map fields whose mapping path include collection object again)

For example, this mapping for `Gear` is invalid:
<img width="1215" alt="Screen Shot 2021-08-05 at 10 06 09 PM" src="https://user-images.githubusercontent.com/40512816/128408821-941a49cf-b273-4d6b-ba1d-3f163e7bfbc6.png">

There should probably be a few exceptions:
Agent
Taxon
others?

**Comment by maxxxxxdlp** [comment]
Disabled circular mappings in auto mapper for all tables except those that have relationships to themself:
```json
    [
      "[table Agent]",
      "[table Container]",
      "[table Geography]",
      "[table GeographyTreeDefItem]",
      "[table GeologicTimePeriod]",
      "[table GeologicTimePeriodTreeDefItem]",
      "[table LithoStrat]",
      "[table LithoStratTreeDefItem]",
      "[table ReferenceWork]",
      "[table Storage]",
      "[table StorageTreeDefItem]",
      "[table Taxon]",
      "[table TaxonTreeDefItem]",
    ]
```

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-11-release-announcement/1174/1
