### ISSUE TITLE
Uncaught exception in webform for app resources  (e.g. viewsets)

### ISSUE THREAD

**Issue by falkogloeckler** [specify/specify7#892]
https://github.com/specify/specify7/blob/b93379ad6ac4ef0de022b26dadae275fd897cb34/specifyweb/frontend/js_src/lib/appresources.js#L56

There is an uncaught exception as soon as a resource in the database exists, but with empty or NULL value. The objec `this.appresourceData` in line 56 would be `undefined` in that case and throughs a TypeError exception. (see console output below).
The condition of an empty value in the resource could appear from time to time due to an erroneous POST or PUT (which could have several reasons like network hickups or temporary connection issues, not directly related to the Specify7 software).
As a consequence of the uncaught exception rendereing the webform stops and so the resource cannot be edited via the admin webform (textarea) anymore, because the save button won't show up. But this would be the logical next step knowing the issue is caused by the empty resource data.

Currently, the empty value of a resource can only be corrected (or deleted) via direct SQL statements sent to the database. As soon as an arbitrary character (not even valid XML) would be in the database for the particular resource the function in line 56 doesn't through any exception anymore (because `this.appresourceData` is not `undefined` anymore) and the value can be edited in the textarea and saved as usual.
This issue is easily reproducible by createing a new resource (e.g. viewset) and save without any value the textarea. Reload the resource webform and try to edit the (empty) resource.

Any plans to catch the exception, so that the save button would be rendered even if there is an empty or NULL result of the get function? Thx!

```
appresources.js:56 Uncaught TypeError: Cannot read property 'get' of undefined

       at Object.<anonymous> (appresources.js:56)
       at fire (jquery.js?27d9:3232)
       at Object.fireWith [as resolveWith] (jquery.js?27d9:3362)
       at Object.deferred.<computed> (jquery.js?27d9:3461)
       at fire (jquery.js?27d9:3232)
       at Object.fireWith [as resolveWith] (jquery.js?27d9:3362)
       at Object.<anonymous> (jquery.js?27d9:3418)
       at fire (jquery.js?27d9:3232)
       at Object.fireWith [as resolveWith] (jquery.js?27d9:3362)
       at Object.<anonymous> (jquery.js?27d9:3418)
```

**Comment by maxxxxxdlp** [comment]
Reproducible on the current production version
Not reproducible on the `next-release` branch

**Comment by falkogloeckler** [comment]
> Reproducible on the current production version
> Not reproducible on the `next-release` branch
> Probably was initially fixed by @benanhalt on a now merged `appresource-improvements` branch

Thanks! Good to know.
Is there a date for the new release?

**Comment by beach53** [comment]
Next week!

**Comment by falkogloeckler** [comment]
> Next week!

Awesome! :)
