### ISSUE TITLE
Remove redundant pop up when creating data plan

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#894]
After clicking to create a new mapping, you choose the base table, then are taken to the mapper, but before you can do anything, a message pops up saying you haven't mapped anything, which is redundant since I already selected to create a new mapping.
![image](https://user-images.githubusercontent.com/12532430/130280796-5d870c34-5ae2-4b4a-a313-a19590db5a99.png)

**Comment by maxxxxxdlp** [comment]
This falls into the "Embeeded documentation" category. Somewhat similar in role to the "No Upload Plan is Defined" dialog message

Modern applications try to embed documentation in the UI through helpful tooltips and dialog messages. Though, they only show a dialog box once, or have an explicit "Don't show again" checkbox.

This is much better than having a separate "Documentation" that is not maintained by us, or is not easily visible to a confused user.

Ideally, all features in Specify 7 should either be self-explanatory to a beginner user or have tooltips/dialog messages.

**Comment by maxxxxxdlp** [comment]
Added a user pref for disabling this dialog
