### ISSUE TITLE
Add ability to double click to add field to mapping

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#895]
Currently, double clicking on a field in the field list does not add it to the mapping regardless of whether a corresponding column has been selected or not.
Ideally, if a column is selected, double clicking the field would add it to that column and if no column is selected, it would add it as a new column

**Comment by maxxxxxdlp** [comment]
There is currently no way to unselect a column
Mapping a column on double click seems like a good behavior
Though, what should happen when a user double clicks on a mapped field? We can either unmap that field, or scroll the list of columns to show which column is mapped to that field. In the second case, once the column is scrolled into view, unmapping can be atchived by pressing the "X" button.
