### ISSUE TITLE
GeoLocate window does not close after selecting to Save to Your Application

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#897]
I used GeoLocate to georeference a record and when I clicked Save to Your Application, the window appeared to do nothing.  The coordinates do get saved, it just doesn't seem like they did

**Comment by maxxxxxdlp** [comment]
Current behavior allows for GeoLocating multiple localities by simply pressing the "Next" button.
Still, it would be a good idea to add some sort of visual indication. Is there a consistent way in Specify 7 in which we indicate that a dialog box changed the content behind it?

**Comment by tlammer** [comment]
Also, is there a way to detect if there is only one record to geolocate?  If there is then it should close automatically after clicking to save the coordinates

**Comment by maxxxxxdlp** [comment]
Currently, if you have only one cell selected, GeoLocate dialog window would have "Previous" and "Next" buttons that navigate between all localities in the WB
If you selected multiple rows, "Previous" and "Next" would allow navigating between selected rows only

I guess we could change its behavior to close automatically when one cell is selected, though I was under the impression that GeoLocate is commonly used to GeoLocate multiple localities at once

**Comment by maxxxxxdlp** [comment]
This is now fixed on the `next-release` branch

If a single row/cell is selected, the GeoLocate window would close as the button is pressed
If multiple cells from different rows are selected, GeoLocate won't close

**Comment by tlammer** [comment]
Window closes if there is only one record selected and the coordinates have been applied to that record.  If there is more than one record being georeferenced, the user will have to close it themselves.
