### ISSUE TITLE
Ask before discarding changes to subforms?

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#903]
If a record is opened in a subform (e.g an Accession record on the CO form) and it was modified, closing the dialog box by pressing the 'X' button does not create a confirmation dialog like you normally get when navigating away with unsaved changes.

Should this be fixed? Or would it be more annoying then useful?

**Comment by maxxxxxdlp** [comment]
Fixed in 1ef7e484
Subforms now have a blue "Close" button if no changes were made and a red "Cancel" button along with an orange "Save" if changes were made.
The "X" button in the corner is removed

**Comment by grantfitzsimmons** [comment]
The subview has a blue close button regardless if changes were made but no red "Cancel" button appears. The orange Save button is visible if changes were made.  _In my head I want to click the blue button as the save one for some reason._

Closing and reopening the view displays the cancel and save options, but now there is no way to exit unless you modify the subview again and click the orange save. The icon in the top right is the warning circle with an exclamation point.

Saving the record crashes the forms.
