### ISSUE TITLE
Specify does not check for enforced tree ranks when moving tree node

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#915]
Example:
1. Open any tree
2. Create a tree node of any rank (e.g the lowest rank)
3. Right-click on a created tree node
4. Choose "Move" from the context menu
5. Click on any upper-level node (e.g the root node)
6. Chose "Move *** here" from the context menu
7. The node created in step 2 is now a child of node chosen in step 5, without any intermediate ranks

![Screen Shot 2021-08-30 at 8 36 29 AM](https://user-images.githubusercontent.com/40512816/131348003-83fcc04c-166d-4f71-a471-0406d4756c2a.png)
![Screen Shot 2021-08-30 at 8 37 21 AM](https://user-images.githubusercontent.com/40512816/131347996-035c5a95-e106-4d34-9a7a-cb251cc231ea.png)

**Comment by maxxxxxdlp** [comment]
The error is still present in 7.7.
Additionally, though less important, when moving a node, you can select its immediate parent, which essentially has no effect.

**Comment by maxxxxxdlp** [comment]
Fixed by disabling tree node move if it would result in the node being moved not having enforced parents.

However, there is yet another way to make an enforced rank missing:
If the current rank is enforced, move it up the tree one level.
Now, children of current rank have an enforced rank missing.

This however is harder to check for, so won't be fixed for now.

**Comment by grantfitzsimmons** [comment]
Can confirm this fix is working on `testability` now. I recieve the "Can't move this tree node here" message
