### ISSUE TITLE
Workbench mapper not hiding tables that are marked as hidden

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#916]
In LSUMammals database.  Paleo Context is not hidden as a field in CE, but the table itself is hidden.  The workbench mapper is still showing it as a field option in the mapper.
![image](https://user-images.githubusercontent.com/12532430/131377387-3aa8f531-855b-4fa5-a3e4-1eceab53c813.png)

**Comment by maxxxxxdlp** [comment]
@benanhalt is there a way for me to know if a table is marked as hidden? Does specify handle that in some way anywhere else?

![Screen Shot 2021-08-30 at 3 07 23 PM](https://user-images.githubusercontent.com/40512816/131398678-19468f76-fba5-463e-8efc-fa21b75a7332.png)

**Comment by benanhalt** [comment]
It doesn't seem to have been added to the `schema.Model` object. I think there just needs to be a method added in https://github.com/specify/specify7/blob/next-release/specifyweb/frontend/js_src/lib/specifymodel.js such as
```
    isHidden() {
        const l = this._getLocalization();
        return l && l.get('ishidden');
    },

```

**Comment by maxxxxxdlp** [comment]
Okay. Assuming I made the mapper respect the isHidden setting, are there any other places that should handle hidden tables?
For example:
List of interactions and tables for data entry
List of tables in the query builder

**Comment by benanhalt** [comment]
IDK. There are other resources that control what tables are available in those contexts. I'm not sure what Sp6 does.

**Comment by maxxxxxdlp** [comment]
Relationships to hidden tables are now marked as hidden
Also, if a table is hidden, it is removed from the list of base tables, even if "Show Advanced tables" is checked

**Comment by maxxxxxdlp** [comment]
Merged this into next-release
Ready for testing on the test servers

**Comment by tlammer** [comment]
I can still see tables that are hidden

**Comment by maxxxxxdlp** [comment]
Probably a caching issue. I told it to reset the cache. Can you test this again?
If it doesn't work, try incognito tab
