### ISSUE TITLE
Current in Determination should not be an option for mapping in the workbench

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#918]
The first determination should be considered the current determination

**Comment by maxxxxxdlp** [comment]
I think the first option is already considered as current. Right @benanhalt?
The `Is Current` field is there if you want to overwrite this setting (e.g., when migrating a database)

**Comment by benanhalt** [comment]
That's correct.

**Comment by maxxxxxdlp** [comment]
"Current" is now a hidden field
