### ISSUE TITLE
Exchange Out preparations does not trigger Add Items dialog

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#922]
Added by @grantfitzsimmons on Nov 1, 2023:

> ## Specify 7 Behavior
> 
> You can create an **Exchange Out**, but the **Total Preps** and **Total Items** do not work (https://github.com/specify/specify7/issues/1193)
>  
> <img width="933" alt="image" src="https://github.com/specify/specify7/assets/37256050/d1e33ae8-8529-4115-9d06-dc29f59252c9">
> 
> Most importantly, **Exchange Out Preps** _does not work!_
> This means you can't create new preparations or link them with existing records.
> 
> ## Specify 6 Behavior
> 
> 1. Go to **Interactions**
> 2. Click on **Exchange Out**
>    <img width="355" alt="image" src="https://github.com/specify/specify7/assets/37256050/7c126ad4-e266-413e-8e22-33d760521d7e">
> 4. See this dialog:
> 	<img width="478" alt="image" src="https://github.com/specify/specify7/assets/37256050/a8127b38-a60b-4c33-92c5-71e6c35bf04f">
> 	a. Enter Items
>    <img width="344" alt="image" src="https://github.com/specify/specify7/assets/37256050/2e93dd89-0f8c-4b5f-ab06-032d58784155">
> 	b. Record Set
> 	<img width="433" alt="image" src="https://github.com/specify/specify7/assets/37256050/947d9b4f-6639-4a98-ada7-0be6913724e4">
> 6. Create the **Exchange Out**
>    <img width="583" alt="image" src="https://github.com/specify/specify7/assets/37256050/569c7f9f-4ddd-488a-96b1-f028054229ac">
> 7. See new record
> ![image](https://github.com/specify/specify7/assets/37256050/42fa9e72-aa0b-47e2-8a14-84d23c89692d)
> 
> 
> 

---

Currently, clicking on the respective option in the Interactions dialog, triggers the following alert messages:

<img width="1680" alt="Screen Shot 2021-08-29 at 5 03 27 PM" src="https://user-images.githubusercontent.com/40512816/131397931-fa4b6a42-0c47-4a60-b26b-5c0a49c61369.png">

<img width="1680" alt="Screen Shot 2021-08-29 at 5 03 36 PM" src="https://user-images.githubusercontent.com/40512816/131397933-a26e7da7-87e8-405e-9629-cabf03618b47.png">

<img width="1680" alt="Screen Shot 2021-08-29 at 4 53 10 PM" src="https://user-images.githubusercontent.com/40512816/131397929-125eedb6-5b04-44ea-b3f8-3ae76ad5b0a4.png">

See also https://github.com/specify/specify7/issues/516

**Comment by grantfitzsimmons** [comment]
Technically supported, but more extensive support needs to be added.

See https://github.com/specify/specify7/issues/516, https://github.com/specify/specify7/issues/2377, and **importantly** https://github.com/specify/specify7/issues/114

**Comment by grantfitzsimmons** [comment]
Requested by CSIRO

**Comment by maxxxxxdlp** [comment]
More context:
The dialog saying "is not supported" has been removed, and the form can now be edited, but not fancy business rules and counts are supported as of yet

**Comment by grantfitzsimmons** [comment]
## Specify 6 Behavior

1. Go to **Interactions**
2. Click on **Exchange Out**
   <img width="355" alt="image" src="https://github.com/specify/specify7/assets/37256050/7c126ad4-e266-413e-8e22-33d760521d7e">
4. See this dialog:
	<img width="478" alt="image" src="https://github.com/specify/specify7/assets/37256050/a8127b38-a60b-4c33-92c5-71e6c35bf04f">
	a. Enter Items
   <img width="344" alt="image" src="https://github.com/specify/specify7/assets/37256050/2e93dd89-0f8c-4b5f-ab06-032d58784155">
	b. Record Set
	<img width="433" alt="image" src="https://github.com/specify/specify7/assets/37256050/947d9b4f-6639-4a98-ada7-0be6913724e4">
6. Create the **Exchange Out**
   <img width="583" alt="image" src="https://github.com/specify/specify7/assets/37256050/569c7f9f-4ddd-488a-96b1-f028054229ac">
7. See new record
![image](https://github.com/specify/specify7/assets/37256050/42fa9e72-aa0b-47e2-8a14-84d23c89692d)


## Specify 7 Behavior

You can create an **Exchange Out**, but the **Total Preps** and **Total Items** do not work (https://github.com/specify/specify7/issues/1193)
 
<img width="933" alt="image" src="https://github.com/specify/specify7/assets/37256050/d1e33ae8-8529-4115-9d06-dc29f59252c9">

Most importantly, **Exchange Out Preps** _does not work!_
This means you can't create new preparations or link them with existing records.

**Comment by grantfitzsimmons** [comment]
From @bronwyncombs:

- EO preparations are read only and thus count information can’t be tested
- Attempted to remove `defaulttype=“table'` from view xml but behavior persisted
