### ISSUE TITLE
Workbench allows Accession records to be uploaded with no Accession number

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#926]
Accession Number is required in the MySQL schema.
Created a CO record with a few fields in it and the only field from accession was accession date.
Validator did not detect an issue with a mapping.  
Uploader uploaded the CO and Accession.  the Accession only had the date in the record.

**Comment by maxxxxxdlp** [comment]
Did you have a single row in the data set or multiple rows?

**Comment by tlammer** [comment]
single

**Comment by maxxxxxdlp** [comment]
If it is just single row, it would create an accession with a blank accession number
if multiple rows, it would fail on the second row due to duplicate accession number (both rows have empty accession numbers, which are considered duplicate)

**Comment by tlammer** [comment]
but the Accession shouldn't be created without an accession number.  It's required by MySQL according to Tim.  And it shouldn't be considered a duplicate Accession record.  It was a CO based dataset so it should have matched the Accession that was created.

**Comment by tlammer** [comment]
although, once there is an accession record with a blank accession number in the database, it does catch that the field is required and cannot be blank.

**Comment by benanhalt** [comment]
Should we just add a business rule to require accession number?

**Comment by melton-jason** [comment]
Is this an issue anymore? It seems like `accessionNumber` is always a required field in the schema config (is this not the case in some databases?).

The workbench throws an appropriate error during validation which stops the user from uploading the data set when an `accessionNumber` has no value.

**Comment by maxxxxxdlp** [comment]
Does the validation error shown in the wb mention field being required or field being unique?

**Comment by melton-jason** [comment]
Here are a few following cases:
With `Never Ignore` match behavior and `Allow Null Values` checked

![isue_926](https://user-images.githubusercontent.com/64045831/221701136-efb0432e-455c-4a2a-bd5d-d943eccc5a34.png)

- For both errors: `Field is required by schema config`
- - - - 
![issue_926_1](https://user-images.githubusercontent.com/64045831/221701620-18cf165f-0e8f-4f4c-bd50-7efeb03bc420.png)

- Uploads successfully. Creates 1 Accession and 2 CollectionObjects, with both CollectionObjects having a relationship to the created Accession

- - - 
![issue-926_2](https://user-images.githubusercontent.com/64045831/221703529-0581577d-f44a-4221-9e22-aebcbe6567e3.png)

- For all errors: `('Accession must have unique accessionnumber in division', {'table': 'Accession', 'localizationKey': 'childFieldNotUnique', 'fieldName': 'accessionnumber', 'fieldData': ('accessionnumber', '1'), 'parentField': 'division', 'parentData': 'division: id=2', 'conflicting': [8]})`

**Comment by maxxxxxdlp** [comment]
looks good. then you are correct, accession number was marked as required so this is now fixed
