### ISSUE TITLE
Data Sets dialogue open past bottom of screen

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#936]
I have a lot of data sets and every time I select workbench, the data set list window opens partially hidden, which means I have to move the dialogue to see the buttons at the bottom of the window.  a scroll bar on the side might help.
![image](https://user-images.githubusercontent.com/12532430/132064601-9d49203a-4338-4fd8-b4e1-0eeabcb5f4bd.png)

**Comment by maxxxxxdlp** [comment]
This particular dialog is now fixed. I would go over all other dialogs after this release
