### ISSUE TITLE
Make date formats accepted by the workbench consistent with the date order chosen for the database

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#937]
in the same dataset, both 10/15/2021 and 15/10/2021 are uploaded as October 15, 2021

**Comment by benanhalt** [comment]
Only dates that match the database format specified in the remote prefs will now be accepted. Dates can be partial by omitting the day or day and month portion, or by replacing said portions with `00` when the format specifies numeric values.

**Comment by benanhalt** [comment]
To change the database date format, access the app resources function as an admin user by clicking on the user name at the top of the page. Then under the Global resources there should be two options called "preferences". One is the global prefs and the other is the remote prefs, and they can be distinguished by a comment at the top of the file. In the remote prefs, find the `ui.formatting.scrdateformat` property. This property controls the database date format and can be set to one of the following values:

```
MM dd yy
MM dd yyyy
MM-dd-yy
MM-dd-yyyy
MM.dd.yy
MM.dd.yyyy
MM/dd/yy
MM/dd/yyyy
dd MM yy
dd MM yyyy
dd MMM yyyy
dd-MM-yy
dd-MM-yyyy
dd-MMM-yyyy
dd.MM.yy
dd.MM.yyyy
dd.MMM.yyyy
dd/MM/yy
dd/MM/yyyy
dd/MMM/yyy
yyyy MM dd
yyyy-MM-dd
yyyy.MM.dd
yyyy/MM/dd
```

![Screenshot_2021-09-09_17-59-51](https://user-images.githubusercontent.com/287254/132773899-16716772-5b68-499a-afcd-d83e9773ee2a.png)
