### ISSUE TITLE
Cannot make a coordinate South if value is less than 1 degree

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#939]
when typing in a latitude that is less than 1 degree and using the DD MM SS format you cannot make it South by adding a negative sign before the 0.
![image001](https://user-images.githubusercontent.com/12532430/132270495-46aa625e-d810-4c5f-ada3-bf711321fc9e.jpg)

**Comment by maxxxxxdlp** [comment]
Seems fixed. Needs testing

<img width="1800" alt="Screen Shot 2022-07-10 at 20 45 45" src="https://user-images.githubusercontent.com/40512816/178173450-25cf5d75-1d35-4696-b965-9f2a776ff4d5.png">
