### ISSUE TITLE
Rename Live Update in Search and Replace tools

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#941]
That makes it seem like it is related to the replacement not search.  Renaming to specify it relates to the search portion would help.

**Comment by beach53** [comment]
Search-as-you-Go
Incremental Search
Progressive Search

Think I like Progressive Search the best. 
But the technical world refers to it as: Incremental Search
[Incremental Search](https://en.wikipedia.org/wiki/Incremental_search)

**Comment by tlammer** [comment]
I think 'live search' or 'active work' would even work
