### ISSUE TITLE
Able to save citation without required field data 

### ISSUE THREAD

**Issue by norinespears** [specify/specify7#942]
I'm not sure what is expected behavior and what is a bug, but here is what I did:

Using 'Next Release' build and the KU Ento database I was adding a CO. In the Citation field I click the button and a form appears. This screen appears:
![Screen Shot 2021-09-08 at 10 04 08 AM](https://user-images.githubusercontent.com/61208178/132535916-d24f3afc-5fc6-4a2b-a6f2-6451f986b18a.png)

As soon as the form opens a new blank citation is added - even though Reference Work is a required field. And rather than the expected 'Save' button on the bottom right corner of the dialog there is a 'New' button. Therefore, this dialog/form 

1. Works different than the others.
2. Allows a Citation to be saved without required information. 
3. To save the CO I have to go back in and delete the blank Citation record.

**Comment by maxxxxxdlp** [comment]
I noticed this happening for a few other tables too

**Comment by maxxxxxdlp** [comment]
This does not create a citation.

The citation would only be created once you press the `New` button (or post 7.7, the `+` button)

As soon as you press the `+` button, the `Save` button on the main form turns red
