### ISSUE TITLE
Cataloged Date not available in Query creator

### ISSUE THREAD

**Issue by norinespears** [specify/specify7#943]
I am using the 'Next Release' release of Sp 7 
Using the DemoEnto database
Cataloged Date is on my form so unhidden in the schema:
![Screen Shot 2021-09-08 at 11 11 44 AM](https://user-images.githubusercontent.com/61208178/132545874-46319cbf-1601-4e9e-b690-b660f48c7b39.png)

but not available as a field to query:
![Screen Shot 2021-09-08 at 11 11 44 AM](https://user-images.githubusercontent.com/61208178/132546060-813e162e-a6c4-4a5f-a1ad-f6e1d306c9b2.png)

**Comment by maxxxxxdlp** [comment]
Fixed in 62528f74
Hidden fields are now shown in the list if "Reveal Hidden Form Fields" is checked
