### ISSUE TITLE
Can we consider just an outline on the icons when they are not available?

### ISSUE THREAD

**Issue by norinespears** [specify/specify7#944]
![Screen Shot 2021-09-08 at 3 04 01 PM](https://user-images.githubusercontent.com/61208178/132577719-a599f400-3211-48eb-ac9c-80badbebb8b2.png)

**Comment by maxxxxxdlp** [comment]
I think we are going to get rid of provider icons altogether, in favor of viewing that information on the SpiceDig page. Instead, there would only be "Lifemapper" icon that opens the map, and a "Specify Network" icon, that may have `Issues detected` label next to it

**Comment by norinespears** [comment]
Does that mean that you no longer need the Worms icon?

**Comment by maxxxxxdlp** [comment]
All provider icons are now used on the SpiceDig page. We don't need disabled and hover states anymore, but might need them again at some point in the future

For WoRMS, Jim sent me this image:
![image](https://user-images.githubusercontent.com/40512816/132872444-a3e8c540-5893-4ee4-82a0-d4eab9cf0c66.png)

Also, @norinespears, can you send me a high-res version of Specify Network logo (at least 300x300px)?

**Comment by norinespears** [comment]
Just so I understand, we are just displaying the logos of the providers now, they are not buttons or icons?

we do not have a Specify Network logo yet.
