### ISSUE TITLE
WorkBench does not respect embedded/shared collecting event configuration

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#945]
In a database where Co is related to CE in a one to one relationship, Created a ce based dataset and mapped two co's to the collecting event.  The dataset uploaded just fine and both CO's pointed to the same CE record.

**Comment by grantfitzsimmons** [comment]
**Original Title:** Mapping multiple Collection Objects to a Collecting Event in a one to one database results in shared CE

There's a good chance this is a problem for Paleo Context as well.

**Comment by emenslin** [comment]
Fixed
