### ISSUE TITLE
Nodes on Tree unassociated with the Taxon Root

### ISSUE THREAD

**Issue by norinespears** [specify/specify7#947]
Pretty sure I should not be seeing this. There are also more nodes offscreen.
<img width="1581" alt="Screen Shot 2021-09-13 at 5 12 02 PM" src="https://user-images.githubusercontent.com/61208178/133163551-72b041a7-d9cc-43f8-936b-ac676a70706f.png">

**Comment by norinespears** [comment]
<img width="1309" alt="Screen Shot 2021-09-13 at 5 18 20 PM" src="https://user-images.githubusercontent.com/61208178/133163788-df2030aa-2bba-4465-8ca6-e0ab93d666b3.png">

**Comment by norinespears** [comment]
Tried updating the tree manually and got this error:
<img width="808" alt="Screen Shot 2021-09-13 at 5 19 58 PM" src="https://user-images.githubusercontent.com/61208178/133163922-27926624-b238-4499-85aa-4e49983b94f9.png">

**Comment by maxxxxxdlp** [comment]
The tree is broken in that database.
Not sure how that happened
