### ISSUE TITLE
Can not add Preps to existing interactions

### ISSUE THREAD

**Issue by norinespears** [specify/specify7#950]
I query to find an  existing Gift or Loan
I open one of them
I click the 'Add' button 
A new prep record is added but I can not edit it so all fields are empty
![Screen Shot 2021-09-16 at 1 14 23 PM](https://user-images.githubusercontent.com/61208178/133664011-35729d5c-f8f3-4fe6-bc50-397eaf220138.png)

**Comment by maxxxxxdlp** [comment]
Should be fixed in new release
