### ISSUE TITLE
Add way to aggregate authors so they can be listed on citations

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#955]
From Jon Fong (Cal Academy)
We are unable to aggregate authors in Reference Works and by extension, Collection Object Citations and Collection Objects. We'd really like to be able to get citations with author names onto CollectionObject labels. Is there a way to do this?

**Comment by maxxxxxdlp** [comment]
This appears to be already possible:

<img width="1800" alt="Screenshot 2023-03-07 at 22 39 30" src="https://user-images.githubusercontent.com/40512816/223621061-d4daca97-5db4-4b1c-b6dc-59d8b5242d40.png">

@grantfitzsimmons can a query like that be used in a report? If so, this issue should be closed

**Comment by grantfitzsimmons** [comment]
I'm not completely sure what they are asking as all of those seem possible in Specify 7. 

@tlammer – if you have any reason we should reopen this issue please let us know!
