### ISSUE TITLE
[a11y] Add a "Skip to Content" link

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#959]
Fixed in https://github.com/specify/specify7/commit/02b8927ead022d56fda076dc1002bd279d03eaad

**Comment by grantfitzsimmons** [comment]
How should I test this?

**Comment by maxxxxxdlp** [comment]
Pressing Tab key after page is loaded would spawn a "Skip To Content" link in the top left corner.
Then, press "Enter" or "Space". The "Skip To Content" links disappears and focus is moved to the first focusable element on the page (e.g, first field on the form, or first button in the tree viewer)

**Comment by grantfitzsimmons** [comment]
In the WorkBench, after loading a data set, there is no Skip to Content link and you must navigate through the browser's content first.

**Comment by maxxxxxdlp** [comment]
It works like expected for me:
Open data set page.
Press tab to focus on the "Skip to Content" link
Hit enter
Focus is moved to the first WB button

https://user-images.githubusercontent.com/40512816/147500549-2f5b7390-14fe-4231-ae11-6f156f04e0a7.mp4

**Comment by grantfitzsimmons** [comment]
I am not seeing it. Am I testing this correctly? I remember it appearing in December. Maybe it is hidden now

**Comment by maxxxxxdlp** [comment]
Fixed
