### ISSUE TITLE
When making a CE query, "Make Record Set" is available, leads to error

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#96]
If you try to click "Make Record Set" without filling out fields for a query and save, an error comes up.
There also seems to be bugs with the "Query" and "Save" buttons here. If you add fields without filling them out and click either the "Query" button or the "Save" button, any fields in the query disappear and no results show up.

**Comment by benanhalt** [comment]
The expected behavior is for incomplete fields to be removed when an action is selected. This may not be as intuitive as it could be...

**Comment by benanhalt** [comment]
duplicates #51
