### ISSUE TITLE
[a11y] Make jQuery dialogs accessible

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#962]
Fixed in https://github.com/specify/specify7/commit/16426a62034dfb8eb95ad4c5499e37db2741e12e and https://github.com/specify/specify7/commit/071ec7eb3e9bd1d294d552abec7460ee695c648f

**Comment by grantfitzsimmons** [comment]
How do I test this

**Comment by maxxxxxdlp** [comment]
`Escape` key should close the dialog
When dialog is opened, focus should be moved to the dialog
`Tab` key navigates between the focusable elements **inside** the dialog only (and loops around)
Dialogs have titles and headings

Then, there is also screen reader testing (test that dialog is announced properly by the screen reader). Though, I think we would do that part later (we would probably test all pages with the screen reader at once)
