### ISSUE TITLE
Trying to add a CO to a CE doesn't work

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#97]
When you create a Collection Event in data entry, add a field # and save, Add Collection Object shows up on form. If you click "Add Collection Object" and search for a CO, a couple things may happen when selecting the CO that results from the search.
In KUFish (shared relationship between CO and CE), selecting the CO doesn't appear to do anything; the CO isn't added. In KUHerps (embedded relationship between CO and CE), selecting the CO results in an error. The difference in the relationships of CO and CE may be the cause of differing results from selecting the CO.

**Comment by garrettgirard** [comment]
Adding a Collection Object to an Accession results in the same issue.

**Comment by benanhalt** [comment]
Superseded by #114
