### ISSUE TITLE
After adding Collection Object to Collection Event, removing the CO doesn't initially register

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#99]
If you add a CO to a CE and then try to remove it the CO disappears, but next to the Collection Object field there is still a (1), indicating the CO wasn't actually removed. If you then try to delete the CE, a message will pop up saying "The resource cannot be deleted because it is referenced through the following fields: Collection Objects", again indicating that the CO wasn't removed. If you refresh the page, the (1) becomes (0) and it is then possible to delete the CE.

**Comment by benanhalt** [comment]
Superseded by #114
